// 2017년 중앙대(수학과) 편입수학 객관식 30문항 (4지선다)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR="2017", SCHOOL_KO="중앙대", SCHOOL_EN="cau";
const opts4 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:1, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"삼각뿔 부피",
    difficulty:"easyMedium",
    question:"좌표공간의 네 점 $(2,0,1),\\,(1,2,-4),\\,(2,-9,4),\\,(2,0,3)$을 꼭짓점으로 가지는 삼각뿔의 부피는?",
    options:opts4("$1$","$2$","$3$","$6$"),
    correct:"3",
    explanation:"기준점을 $P_0=(2,0,1)$로 두고 세 변 벡터: $v_1=(-1,2,-5),\\,v_2=(0,-9,3),\\,v_3=(0,0,2)$.\n부피 $=\\dfrac{1}{6}|\\det[v_1\\,v_2\\,v_3]|=\\dfrac{1}{6}\\!\\left|(-1)\\cdot((-9)\\cdot 2-3\\cdot 0)\\right|=\\dfrac{1}{6}\\cdot 18=3$.",
  },
  {n:2, subject:"미분학", unit:"도함수", concept:"함수방정식과 미분",
    difficulty:"medium",
    question:"실수 전체 집합에서 정의된 함수 $f$가 다음 두 조건을 만족한다고 할 때, $f(5)$를 구하면?\n(i) $f(x+y)=f(x)+f(y)+4xy\\,(x,y\\in\\mathbb R)$, (ii) $\\displaystyle\\lim_{h\\to 0}\\dfrac{f(h)}{h}=2$.",
    options:opts4("$60$","$80$","$100$","$120$"),
    correct:"1",
    explanation:"$x=y=0$ 대입: $f(0)=2f(0)\\Rightarrow f(0)=0$. (ii)에서 $f'(0)=2$.\n도함수: $f'(x)=\\!\\lim_{h\\to 0}\\dfrac{f(x+h)-f(x)}{h}=\\!\\lim_{h\\to 0}\\dfrac{f(h)+4xh}{h}=2+4x$.\n적분: $f(x)=2x^2+2x$. $f(5)=50+10=60$.",
  },
  {n:3, subject:"적분학", unit:"정적분", concept:"파푸스 회전 부피",
    difficulty:"easyMedium",
    question:"좌표평면 위의 원 $x^2+(y-2)^2=1$로 둘러싸인 영역을 $x$축에 관하여 회전시켰을 때, 생기는 회전체의 부피는?",
    options:opts4("$2\\pi$","$4\\pi$","$2\\pi^2$","$4\\pi^2$"),
    correct:"4",
    explanation:"파푸스 정리: $V=2\\pi\\bar y\\cdot A$. 원의 무게중심 $\\bar y=2$, 면적 $A=\\pi$.\n$V=2\\pi\\cdot 2\\cdot\\pi=4\\pi^2$.",
  },
  {n:4, subject:"미분학", unit:"도함수", concept:"연속·미분가능 조건",
    difficulty:"medium",
    question:"함수 $f(x)$가 두 상수 $a,b$에 의해 실수 전체 집합에서 다음과 같이 정의된다. 이 함수가 연속이고 미분가능할 때, $\\dfrac{b}{a}$의 값은?\n$$f(x)=\\!\\begin{cases}x^2,&(x<1)\\\\a\\sqrt x\\,e^{bx},&(x\\ge 1)\\end{cases}$$",
    options:opts4("$\\sqrt e$","$e$","$\\dfrac{3e}{2}$","$\\dfrac{3e\\sqrt e}{2}$"),
    correct:"4",
    explanation:"연속: $1=ae^b\\Rightarrow ae^b=1$.\n미분가능: $f'(1^-)=2$. $f'(x\\ge 1)=ae^{bx}\\!\\left(\\dfrac{1}{2\\sqrt x}+b\\sqrt x\\right)$, $x=1$ 대입 $=ae^b\\!\\left(\\dfrac{1}{2}+b\\right)=\\dfrac{1}{2}+b=2$. → $b=\\dfrac{3}{2}$.\n$a=e^{-3/2}$. $\\dfrac{b}{a}=\\dfrac{3}{2}e^{3/2}=\\dfrac{3e\\sqrt e}{2}$.",
  },
  {n:5, subject:"적분학", unit:"급수의 수렴/발산", concept:"수렴조건 r 비교",
    difficulty:"medium",
    question:"다음의 급수가 수렴하기 위한 실수 $r$의 범위가 다른 것은?",
    options:opts4("$\\displaystyle\\sum_{n=0}^{\\infty}\\dfrac{1}{(1+2n)^r}$","$\\displaystyle\\sum_{n=2}^{\\infty}\\dfrac{\\ln n}{n^r}$","$\\displaystyle\\sum_{n=2}^{\\infty}\\dfrac{1}{n(\\ln n)^r}$","$\\displaystyle\\sum_{n=1}^{\\infty}n^{1-r}e^{nr}$"),
    correct:"4",
    explanation:"(1) $p$-급수 $r>1$ 수렴.\n(2) $\\dfrac{\\ln n}{n^r}$, $r>1$이면 수렴 ($\\ln n$은 $n^\\epsilon$로 흡수).\n(3) 적분판정 $\\int^\\infty\\dfrac{dx}{x(\\ln x)^r}$, $r>1$ 수렴.\n(4) $r>0$이면 $e^{nr}\\to\\infty$ 발산. 수렴은 $r\\le 0$ 등 다른 조건. 따라서 (4)만 다른 범위.",
  },
  {n:6, subject:"미분학", unit:"도함수", concept:"역함수 미분",
    difficulty:"easy",
    question:"$f(x)=5+9x+e^{-x+1}$일 때, $(f^{-1})'(15)$의 값은?",
    options:opts4("$\\dfrac{1}{8}$","$\\dfrac{1}{4}$","$\\dfrac{1}{2}$","$1$"),
    correct:"1",
    explanation:"$f(1)=5+9+1=15$. $f'(x)=9-e^{-x+1}$, $f'(1)=9-1=8$.\n$(f^{-1})'(15)=\\dfrac{1}{f'(1)}=\\dfrac{1}{8}$.",
  },
  {n:7, subject:"적분학", unit:"정적분", concept:"치환적분",
    difficulty:"easy",
    question:"$\\displaystyle\\int_0^1 x\\sqrt{1-x}\\,dx$의 값은?",
    options:opts4("$\\dfrac{2}{13}$","$\\dfrac{3}{14}$","$\\dfrac{4}{15}$","$\\dfrac{5}{16}$"),
    correct:"3",
    explanation:"$u=1-x$: $\\displaystyle\\int_0^1 x\\sqrt{1-x}\\,dx=\\!\\int_0^1 (1-u)\\sqrt u\\,du=\\!\\int_0^1(u^{1/2}-u^{3/2})du=\\dfrac{2}{3}-\\dfrac{2}{5}=\\dfrac{4}{15}$.",
  },
  {n:8, subject:"적분학", unit:"정적분", concept:"적분으로 정의된 함수",
    difficulty:"medium",
    question:"연속함수 $f$가 $\\displaystyle\\int_1^{2x}f(t)\\,dt=x\\sin^{-1}x$를 만족할 때, $f(1)$의 값은?",
    options:opts4("$0$","$\\dfrac{\\pi+3\\sqrt 3}{12}$","$\\dfrac{\\pi+2\\sqrt 3}{12}$","$\\dfrac{\\pi+\\sqrt 3}{6}$"),
    correct:"3",
    explanation:"양변 미분: $2f(2x)=\\sin^{-1}x+\\dfrac{x}{\\sqrt{1-x^2}}$.\n$x=\\dfrac{1}{2}$ 대입: $2f(1)=\\dfrac{\\pi}{6}+\\dfrac{1/2}{\\sqrt{3}/2}=\\dfrac{\\pi}{6}+\\dfrac{1}{\\sqrt 3}=\\dfrac{\\pi}{6}+\\dfrac{\\sqrt 3}{3}=\\dfrac{\\pi+2\\sqrt 3}{6}$.\n$f(1)=\\dfrac{\\pi+2\\sqrt 3}{12}$.",
  },
  {n:9, subject:"다변수함수", unit:"편도함수", concept:"라그랑주 최댓값 최솟값",
    difficulty:"medium",
    question:"단위원 $x^2+y^2=1$ 위에서 $f(x,y)=xy+y$의 최댓값을 $M$, 최솟값을 $m$이라 할 때, $M-m$의 값은?",
    options:opts4("$\\dfrac{3\\sqrt 3}{2}$","$\\dfrac{3\\sqrt 3}{4}$","$\\dfrac{5\\sqrt 3}{8}$","$\\sqrt 3$"),
    correct:"1",
    explanation:"$x=\\cos\\theta,\\,y=\\sin\\theta$ 매개화: $f=\\dfrac{\\sin 2\\theta}{2}+\\sin\\theta$.\n$f'(\\theta)=\\cos 2\\theta+\\cos\\theta=(2\\cos\\theta-1)(\\cos\\theta+1)=0$.\n$\\cos\\theta=1/2$ ($\\theta=\\pm\\pi/3$): $f=\\pm\\dfrac{3\\sqrt 3}{4}$. $\\cos\\theta=-1$: $f=0$.\n$M-m=\\dfrac{3\\sqrt 3}{4}-\\!\\left(-\\dfrac{3\\sqrt 3}{4}\\right)=\\dfrac{3\\sqrt 3}{2}$.",
  },
  {n:10, subject:"선형대수", unit:"행렬", concept:"Vandermonde 변형 행렬식",
    difficulty:"medium",
    question:"행렬 $\\begin{pmatrix}1&2&3&4\\\\1&2^2&3^2&4^2\\\\1&2^3&3^3&4^3\\\\1&2^4&3^4&4^4\\end{pmatrix}$의 행렬식의 값은?",
    options:opts4("$144$","$288$","$512$","$576$"),
    correct:"2",
    explanation:"$M_{ij}=j^i=j\\cdot j^{i-1}$이므로 $M=V\\cdot D$ ($V$는 표준 Vandermonde, $D=\\mathrm{diag}(1,2,3,4)$).\n$\\det V=\\prod_{1\\le i<j\\le 4}(j-i)=1\\cdot 2\\cdot 3\\cdot 1\\cdot 2\\cdot 1=12$, $\\det D=24$.\n$\\det M=12\\cdot 24=288$.",
  },
  {n:11, subject:"선형대수", unit:"벡터공간", concept:"부분공간 차원 합",
    difficulty:"medium",
    question:"모든 성분이 실수인 $n\\times n$ 행렬의 집합 $M_{n\\times n}(\\mathbb R)$은 행렬의 덧셈과 실수곱에 대해서 벡터공간을 이룬다. $A^T$를 $A$의 전치행렬, $\\mathrm{tr}(A)$를 $A$의 대각합이라 할 때, $V=\\{A\\mid A^T=A\\},\\,W=\\{A\\mid\\mathrm{tr}(A)=0\\},\\,V\\cap W$는 각각 $M_{n\\times n}(\\mathbb R)$의 부분공간이다. $\\dim V+\\dim W+\\dim(V\\cap W)$를 $n$으로 표현하면?",
    options:opts4("$2n^2+n-2$","$2n^2+n+2$","$2n^2+2n-1$","$2n^2+2n+1$"),
    correct:"1",
    explanation:"$\\dim V=\\dfrac{n(n+1)}{2}$ (대칭행렬).\n$\\dim W=n^2-1$ (trace 1차 조건).\n$\\dim(V\\cap W)=\\dfrac{n(n+1)}{2}-1$.\n합 $=n(n+1)+n^2-2=2n^2+n-2$.",
  },
  {n:12, subject:"선형대수", unit:"고유치와 대각화", concept:"행렬 거듭제곱",
    difficulty:"medium",
    question:"$\\begin{pmatrix}3&1\\\\1&3\\end{pmatrix}^{100}\\!\\begin{pmatrix}4\\\\0\\end{pmatrix}=a\\!\\begin{pmatrix}1\\\\-1\\end{pmatrix}+b\\!\\begin{pmatrix}1\\\\1\\end{pmatrix}$을 만족하는 두 실수 $a,b$에 대하여 $\\dfrac{\\log_2 a}{\\log_2 b}$를 구하면?",
    options:opts4("$\\dfrac{101}{201}$","$\\dfrac{201}{101}$","$\\dfrac{112}{201}$","$\\dfrac{201}{112}$"),
    correct:"1",
    explanation:"고유값 $2,4$, 고유벡터 $(1,-1),(1,1)$. $\\binom{4}{0}=2\\binom{1}{-1}+2\\binom{1}{1}$.\n$A^{100}\\!\\binom{4}{0}=2\\cdot 2^{100}\\!\\binom{1}{-1}+2\\cdot 4^{100}\\!\\binom{1}{1}$.\n$a=2^{101},\\,b=2\\cdot 4^{100}=2^{201}$. $\\dfrac{\\log_2 a}{\\log_2 b}=\\dfrac{101}{201}$.",
  },
  {n:13, subject:"선형대수", unit:"벡터공간", concept:"일차독립 판정",
    difficulty:"medium",
    question:"일차독립인 네 개의 벡터 $v_1,v_2,v_3,v_4$에 대하여 다음 <보기> 중 일차독립인 집합의 개수는?\n(가) $\\{v_1+v_2,v_2+v_3,v_3+v_4\\}$\n(나) $\\{v_1+v_2,v_2+v_3,v_3+v_4,v_4+v_1\\}$\n(다) $\\{v_1+v_2-3v_3,v_1+3v_2-v_3,v_1+v_3\\}$\n(라) $\\{v_1+v_2-2v_3,v_1-v_2-v_3,v_1+v_3\\}$\n(마) $\\{v_1,v_1+v_2,v_1+v_2+v_3,v_1+v_2+v_3+v_4\\}$",
    options:opts4("$1$ 개","$2$ 개","$3$ 개","$4$ 개"),
    correct:"4",
    explanation:"(나) $(v_1+v_2)-(v_2+v_3)+(v_3+v_4)-(v_4+v_1)=0$ → 일차종속.\n(가),(다),(라),(마)는 계수행렬의 행렬식이 0이 아님 → 일차독립.\n총 $4$개.",
  },
  {n:14, subject:"다변수함수", unit:"편도함수", concept:"라그랑주 최대 부피",
    difficulty:"medium",
    question:"직육면체가 타원면 $9x^2+4y^2+36z^2=324$에 내접할 때, 부피의 최댓값을 구하면?",
    options:opts4("$18\\sqrt 3$","$36\\sqrt 3$","$108\\sqrt 3$","$144\\sqrt 3$"),
    correct:"4",
    explanation:"$\\dfrac{x^2}{36}+\\dfrac{y^2}{81}+\\dfrac{z^2}{9}=1$, 반축 $a=6,\\,b=9,\\,c=3$.\n부피 $V=8xyz$ 최대화. 라그랑주: $\\dfrac{x^2}{a^2}=\\dfrac{y^2}{b^2}=\\dfrac{z^2}{c^2}=\\dfrac{1}{3}$.\n$V_{\\max}=8\\cdot\\dfrac{abc}{3\\sqrt 3}=\\dfrac{8\\cdot 162}{3\\sqrt 3}=\\dfrac{432}{\\sqrt 3}=144\\sqrt 3$.",
  },
  {n:15, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"두 직선 최단거리",
    difficulty:"medium",
    question:"점 $P$를 직선 $L_1:x=s+4,\\,y=-s+3,\\,z=5s+5$ 위의 점, 점 $Q$를 직선 $L_2:x=t+1,\\,y=-t+3,\\,z=2t-1$ 위의 점이라고 할 때, 점 $P$와 점 $Q$ 사이의 최단 거리는?",
    options:opts4("$3$","$\\dfrac{3}{\\sqrt 2}$","$\\sqrt 3$","$\\dfrac{3}{2}$"),
    correct:"2",
    explanation:"방향 $v_1=(1,-1,5),\\,v_2=(1,-1,2)$. $v_1\\times v_2=(3,3,0),\\,|v_1\\times v_2|=3\\sqrt 2$.\n$P_1=(4,3,5),\\,P_2=(1,3,-1)$, $\\overrightarrow{P_1P_2}=(-3,0,-6)$.\n거리 $=\\dfrac{|\\overrightarrow{P_1P_2}\\cdot(v_1\\times v_2)|}{|v_1\\times v_2|}=\\dfrac{|-9|}{3\\sqrt 2}=\\dfrac{3}{\\sqrt 2}$.",
  },
  {n:16, subject:"다변수함수", unit:"중적분", concept:"구면좌표 삼중적분",
    difficulty:"hard",
    question:"좌표공간에서 두 부등식 $x^2+y^2\\le z^2,\\,x^2+y^2+z^2\\le z$를 만족하는 영역을 $E$라고 할 때, $\\displaystyle\\iiint_E\\dfrac{\\tan^{-1}\\!\\left(\\frac{y}{x}\\right)}{\\sqrt{x^2+y^2+z^2}}\\,dxdydz$의 값은?",
    options:opts4("$\\dfrac{\\pi(4-\\sqrt 2)}{12}$","$\\dfrac{\\pi^2(4-\\sqrt 2)}{12}$","$\\dfrac{\\pi(4+\\sqrt 2)}{12}$","$\\dfrac{\\pi^2(4+\\sqrt 2)}{12}$"),
    correct:"2",
    explanation:"구면좌표: $\\rho\\le\\cos\\phi$ (구), $0\\le\\phi\\le\\pi/4$ (원뿔). 피적분 $=\\theta/\\rho$, $dV=\\rho^2\\sin\\phi\\,d\\rho d\\phi d\\theta$.\n$\\!\\int_0^{2\\pi}\\!\\theta\\,d\\theta\\!\\int_0^{\\pi/4}\\!\\sin\\phi\\,d\\phi\\!\\int_0^{\\cos\\phi}\\!\\rho\\,d\\rho=2\\pi^2\\cdot\\dfrac{1}{2}\\!\\int_0^{\\pi/4}\\!\\sin\\phi\\cos^2\\phi\\,d\\phi$.\n$=\\pi^2\\!\\left[-\\dfrac{\\cos^3\\phi}{3}\\right]_0^{\\pi/4}=\\dfrac{\\pi^2}{3}\\!\\left(1-\\dfrac{\\sqrt 2}{4}\\right)=\\dfrac{\\pi^2(4-\\sqrt 2)}{12}$.",
  },
  {n:17, subject:"선형대수", unit:"고유치와 대각화", concept:"케일리-해밀턴 trace 곱",
    difficulty:"medium",
    question:"특성다항식이 $\\phi(t)=t^4-4t^3-15t^2-38t-108$인 $4\\times 4$ 행렬 $A$와 $A$의 역행렬 $A^{-1}$에 대하여 이들의 대각합의 곱, 즉 $\\mathrm{tr}(A)\\cdot\\mathrm{tr}(A^{-1})$은 얼마인가?",
    options:opts4("$-\\dfrac{27}{38}$","$\\dfrac{27}{38}$","$-\\dfrac{38}{27}$","$\\dfrac{38}{27}$"),
    correct:"3",
    explanation:"$\\phi(t)=t^4-e_1 t^3+e_2 t^2-e_3 t+e_4$ ($e_k$: $k$차 elementary symmetric of eigenvalues).\n$e_1=4=\\mathrm{tr}(A)$, $e_3=38$, $e_4=-108=\\det A$.\n$\\mathrm{tr}(A^{-1})=\\!\\sum 1/\\lambda_i=\\dfrac{e_3}{e_4}=\\dfrac{38}{-108}=-\\dfrac{19}{54}$.\n곱 $=4\\cdot\\!\\left(-\\dfrac{19}{54}\\right)=-\\dfrac{38}{27}$.",
  },
  {n:18, subject:"다변수함수", unit:"중적분", concept:"치환 이중적분",
    difficulty:"medium",
    question:"영역 $R$은 직선 $y=x,\\,x$축, $y=\\dfrac{3}{2}(x-1)$로 둘러싸인 삼각형의 경계와 내부라 하자. 이때, $\\displaystyle\\iint_R e^{\\frac{y}{3x-2y}}\\,dxdy$의 값은?",
    options:opts4("$\\dfrac{1}{2}(e-1)$","$-\\dfrac{1}{2}(e-1)$","$\\dfrac{3}{2}(e-1)$","$-\\dfrac{3}{2}(e-1)$"),
    correct:"3",
    explanation:"$u=y,\\,v=3x-2y$ 치환. 야코비안 $|J|=1/3$.\n경계: $y=0\\to u=0$, $y=x\\to u=v$, $3x-2y=3\\to v=3$. 새 영역: $0\\le u\\le v\\le 3$.\n$\\!\\iint=\\dfrac{1}{3}\\!\\int_0^3\\!\\!\\int_0^v e^{u/v}du\\,dv=\\dfrac{1}{3}\\!\\int_0^3 v(e-1)\\,dv=\\dfrac{1}{3}\\cdot\\dfrac{9(e-1)}{2}=\\dfrac{3(e-1)}{2}$.",
  },
  {n:19, subject:"적분학", unit:"정적분", concept:"리만합 무한급수",
    difficulty:"medium",
    question:"$\\displaystyle\\lim_{n\\to\\infty}\\sum_{k=n}^{\\infty}\\dfrac{n}{n^2+3k^2}$의 값은?",
    options:opts4("$0$","$\\dfrac{\\pi}{6}$","$\\dfrac{\\pi}{6\\sqrt 3}$","$\\dfrac{\\pi}{12}$"),
    correct:"3",
    explanation:"$t=k/n$ 치환: $\\dfrac{n}{n^2+3k^2}=\\dfrac{1}{n}\\cdot\\dfrac{1}{1+3t^2}$. 리만합 → 적분.\n$\\!\\int_1^{\\infty}\\dfrac{dt}{1+3t^2}=\\dfrac{1}{\\sqrt 3}\\!\\left[\\tan^{-1}(\\sqrt 3 t)\\right]_1^{\\infty}=\\dfrac{1}{\\sqrt 3}\\!\\left(\\dfrac{\\pi}{2}-\\dfrac{\\pi}{3}\\right)=\\dfrac{\\pi}{6\\sqrt 3}$.",
  },
  {n:20, subject:"다변수함수", unit:"선적분과 면적분", concept:"스토크스 정리",
    difficulty:"hard",
    question:"곡선 $C$는 원기둥 $x^2+y^2=1$과 평면 $x+y+z=1$이 만나서 생기는 교선이다. $C$의 향(orientation)은 $z$축의 양의 방향에서 바라볼 때 반시계 방향으로 주어진다고 하자. 이때, 선적분 $\\displaystyle\\oint_C\\!\\left(-y^5-\\dfrac{5}{3}x^2y^3\\right)dx+\\!\\left(x^5+\\dfrac{5}{3}x^3y^2\\right)dy-z^5\\,dz$의 값은?",
    options:opts4("$\\dfrac{5\\pi}{3}$","$\\dfrac{5\\pi}{2}$","$5\\pi$","$0$"),
    correct:"1",
    explanation:"$\\mathrm{curl}\\,F=(0,0,5(x^2+y^2)^2)$. 평면 $z=1-x-y$, $d\\mathbf S=(1,1,1)dA$.\n$\\!\\iint_S\\mathrm{curl}\\,F\\cdot d\\mathbf S=\\!\\iint_D 5(x^2+y^2)^2\\,dA=5\\cdot 2\\pi\\!\\int_0^1 r^5 dr=\\dfrac{5\\pi}{3}$.",
  },
  {n:21, subject:"선형대수", unit:"고유치와 대각화", concept:"행렬 100제곱 성분합",
    difficulty:"medium",
    question:"$A=\\begin{pmatrix}1&4\\\\3&2\\end{pmatrix},\\,A^{100}=\\begin{pmatrix}b_{11}&b_{12}\\\\b_{21}&b_{22}\\end{pmatrix}$라 할 때, $b_{12}+b_{21}$의 값은?",
    options:opts4("$\\dfrac{1}{7}(5^{100}-2^{100})$","$5^{100}-2^{100}$","$\\dfrac{1}{7}(5^{100}+2^{100})$","$5^{100}+2^{100}$"),
    correct:"2",
    explanation:"고유값 $5,-2$ (특성 $\\lambda^2-3\\lambda-10=0$). 대각화 후 $A^{100}$ 계산.\n$P=\\begin{pmatrix}1&4\\\\1&-3\\end{pmatrix},\\,\\det P=-7$.\n각 성분 정리하면 $b_{12}=\\dfrac{4(5^{100}-2^{100})}{7},\\,b_{21}=\\dfrac{3(5^{100}-2^{100})}{7}$.\n합 $=5^{100}-2^{100}$.",
  },
  {n:22, subject:"적분학", unit:"급수의 수렴/발산", concept:"수렴 진위 보기",
    difficulty:"medium",
    question:"다음 <보기> 중 수렴하는 것의 개수는?\n(가) $\\displaystyle\\sum_{n=1}^{\\infty}\\tan^{-1}\\!\\left(\\dfrac{1}{n}\\right)$\n(나) $\\displaystyle\\lim_{(x,y)\\to(0,0)}\\sin\\!\\left(\\dfrac{x^2y^2}{x^4+y^4}\\right)$\n(다) $\\displaystyle\\int_1^{\\infty}\\dfrac{1}{\\sqrt{x+e^x}}dx$\n(라) $\\displaystyle\\int_{-\\infty}^{\\infty}x^{100}e^{x-x^2}dx$",
    options:opts4("$1$ 개","$2$ 개","$3$ 개","$4$ 개"),
    correct:"2",
    explanation:"(가) $\\tan^{-1}(1/n)\\sim 1/n$ → 발산.\n(나) 극좌표로 $\\dfrac{x^2y^2}{x^4+y^4}=\\dfrac{\\cos^2\\theta\\sin^2\\theta}{\\cos^4\\theta+\\sin^4\\theta}$ ($\\theta$ 의존) → 극한 부재.\n(다) $1/\\sqrt{e^x}=e^{-x/2}$ 비교 → 수렴.\n(라) $e^{x-x^2}=e^{-x^2+x}$ 가우스형 → 수렴.\n(다),(라) 수렴 → $2$개.",
  },
  {n:23, subject:"다변수함수", unit:"선적분과 면적분", concept:"그린정리 반원",
    difficulty:"medium",
    question:"곡선 $C$는 $C=\\{(x,y)\\in\\mathbb R^2\\mid x=\\cos\\theta,\\,y=\\sin\\theta,\\,0\\le\\theta\\le\\pi\\}$인 반원이며, 반시계 방향으로 향이 주어져 있다. 이때, $\\displaystyle\\int_C(y+x^2)\\,dx+\\!\\left(2x+\\sqrt[3]{\\sin y^3+e^{y^2}}\\right)dy$의 값은?",
    options:opts4("$0$","$\\dfrac{\\pi}{2}-\\dfrac{2}{3}$","$\\dfrac{\\pi}{3}-\\dfrac{2}{5}$","$\\dfrac{\\pi-1}{2}$"),
    correct:"2",
    explanation:"닫힌 영역 (반원+직경)에 그린정리: $\\!\\iint_D(2-1)dA=\\dfrac{\\pi}{2}$.\n직경 $y=0$ 위 적분: $\\!\\int_{-1}^{1}x^2\\,dx=\\dfrac{2}{3}$.\n반원만의 적분 $=\\dfrac{\\pi}{2}-\\dfrac{2}{3}$.",
  },
  {n:24, subject:"적분학", unit:"급수의 수렴/발산", concept:"급수합·수렴구간 진위",
    difficulty:"medium",
    question:"다음 <보기> 중 옳은 것은 몇 개인가?\n(가) $\\displaystyle\\sum_{n=0}^{\\infty}\\dfrac{1}{(2n)!}=\\dfrac{1}{2}\\!\\left(e+\\dfrac{1}{e}\\right)$\n(나) $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{n^2}{3^n}=\\dfrac{3}{2}$\n(다) $\\displaystyle\\sum_{n=0}^{\\infty}\\dfrac{(-3)^n(x-1)^n}{\\sqrt{n+1}}$의 수렴구간은 $\\left(\\dfrac{2}{3},\\dfrac{4}{3}\\right]$이다.",
    options:opts4("$3$ 개","$2$ 개","$1$ 개","$0$ 개"),
    correct:"1",
    explanation:"(가) $\\cosh 1=\\dfrac{e+e^{-1}}{2}=\\!\\sum\\dfrac{1}{(2n)!}$. 참.\n(나) $\\!\\sum n^2 x^n=\\dfrac{x(1+x)}{(1-x)^3}$, $x=1/3$: $\\dfrac{(1/3)(4/3)}{(2/3)^3}=\\dfrac{3}{2}$. 참.\n(다) 수렴반경 $|3(x-1)|<1$, 즉 $(2/3,4/3)$. $x=2/3$: $\\!\\sum 1/\\sqrt{n+1}$ 발산. $x=4/3$: 교대급수 수렴 → 수렴구간 $(2/3,4/3]$. 참.\n모두 옳음 → $3$개.",
  },
  {n:25, subject:"선형대수", unit:"고유치와 대각화", concept:"행렬 진위 보기",
    difficulty:"medium",
    question:"다음 <보기> 중 옳은 것은 몇 개인가?\n(가) $A=\\begin{pmatrix}2t&1\\\\0&2t\\end{pmatrix}$일 때, $e^A=\\begin{pmatrix}e^{2t}&e^{2t}\\\\0&e^{2t}\\end{pmatrix}$이다.\n(나) $A=\\begin{pmatrix}4&2&-2\\\\-5&3&2\\\\-2&4&1\\end{pmatrix}$일 때, $10A^{-1}=A^2-8A+17I$가 성립한다. (단, $I$는 $3\\times 3$ 단위행렬)\n(다) $n\\times n$ 행렬 $A$와 $B$가 동일한 $n$개의 고유벡터를 갖는다면 $AB=BA$가 항상 성립한다.",
    options:opts4("$0$ 개","$1$ 개","$2$ 개","$3$ 개"),
    correct:"4",
    explanation:"(가) $A=2tI+N$, $N$은 nilpotent. $e^A=e^{2t}(I+N)$. 참.\n(나) 케일리-해밀턴: $\\chi(\\lambda)=\\lambda^3-8\\lambda^2+17\\lambda-10$. $A^3-8A^2+17A=10I\\Rightarrow A(A^2-8A+17I)=10I\\Rightarrow 10A^{-1}=A^2-8A+17I$. 참.\n(다) 일차독립인 $n$개의 공통 고유벡터는 동시 대각화를 의미: $A=PD_AP^{-1},\\,B=PD_BP^{-1}$. $D$는 가환이므로 $AB=BA$. 참.\n모두 참 → $3$개.",
  },
  {n:26, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"평면과 점 거리",
    difficulty:"easyMedium",
    question:"두 직선 $\\dfrac{x}{2}=\\dfrac{y-2}{3}=z+1$과 $\\dfrac{x+1}{4}=\\dfrac{y}{6}=\\dfrac{z-3}{2}$를 포함하는 평면 $\\alpha$와 점 $(2,1,3)$과의 거리는?",
    options:opts4("$\\dfrac{33}{\\sqrt{278}}$","$\\dfrac{32}{\\sqrt{278}}$","$\\dfrac{31}{\\sqrt{278}}$","$\\dfrac{34}{\\sqrt{278}}$"),
    correct:"1",
    explanation:"두 직선은 방향 $(2,3,1)\\parallel(4,6,2)$이므로 평행. 점 $P_1=(0,2,-1),\\,P_2=(-1,0,3)$.\n법선 $\\mathbf n=\\overrightarrow{P_1P_2}\\times(2,3,1)=(-1,-2,4)\\times(2,3,1)=(-14,9,1)$.\n평면: $-14x+9y+z-17=0$. 거리 $=\\dfrac{|-14\\cdot 2+9-17+3|}{\\sqrt{278}}=\\dfrac{33}{\\sqrt{278}}$.",
  },
  {n:27, subject:"다변수함수", unit:"중적분", concept:"구면좌표 질량",
    difficulty:"medium",
    question:"각 점에서 밀도함수가 $\\mu(x,y,z)=\\dfrac{3}{x^2+y^2+z^2}$로 주어질 때, 입체 $E=\\{(x,y,z)\\in\\mathbb R^3\\mid z\\ge 0,\\,x^2+y^2+z^2\\le 4,\\,x^2+y^2\\ge 1\\}$의 질량은?",
    options:opts4("$2\\pi\\!\\left(3-\\dfrac{2}{3}\\pi\\right)$","$2\\pi\\!\\left(2-\\dfrac{\\pi}{3}\\right)$","$2\\sqrt 3\\,\\pi\\!\\left(2-\\dfrac{\\pi}{3}\\right)$","$2\\pi(3\\sqrt 3-\\pi)$"),
    correct:"4",
    explanation:"구면좌표: $z\\ge 0\\Rightarrow\\phi\\le\\pi/2$, $\\rho\\le 2$, $\\rho\\sin\\phi\\ge 1\\Rightarrow\\rho\\ge\\dfrac{1}{\\sin\\phi},\\,\\phi\\ge\\pi/6$.\n질량 $=\\!\\int_0^{2\\pi}\\!\\int_{\\pi/6}^{\\pi/2}\\!\\int_{1/\\sin\\phi}^{2}\\!\\dfrac{3}{\\rho^2}\\rho^2\\sin\\phi\\,d\\rho d\\phi d\\theta=6\\pi\\!\\int_{\\pi/6}^{\\pi/2}(2\\sin\\phi-1)d\\phi$.\n$=6\\pi[-2\\cos\\phi-\\phi]_{\\pi/6}^{\\pi/2}=6\\pi(\\sqrt 3-\\pi/3)=2\\pi(3\\sqrt 3-\\pi)$.",
  },
  {n:28, subject:"선형대수", unit:"선형변환", concept:"고유기저 행렬 표현",
    difficulty:"medium",
    question:"3차 이하의 다항식으로 이루어진 벡터공간 $\\mathbb P_3(\\mathbb R)=\\{a+bx+cx^2+dx^3\\mid a,b,c,d\\in\\mathbb R\\}$ 위의 선형사상 $T:\\mathbb P_3(\\mathbb R)\\to\\mathbb P_3(\\mathbb R)$이 $T(1)=1+x,\\,T(x)=3x,\\,T(x^2)=4x+x^2,\\,T(x^3)=8x+x^3$으로 정의된다. 선형사상 $T$를 고유벡터로 이루어진 기저 $\\beta=\\{-2+x,-4+x^2,-8+x^3,x\\}$에 대하여 표현한 $4\\times 4$ 행렬 $[T]_\\beta=(a_{ij})$라 할 때, $\\displaystyle\\sum_{j=1}^{4}\\sum_{i=1}^{4}a_{ij}$의 값은?",
    options:opts4("$4$","$6$","$8$","$10$"),
    correct:"2",
    explanation:"$T(-2+x)=-2(1+x)+3x=-2+x$ → 고유값 $1$.\n$T(-4+x^2)=-4(1+x)+4x+x^2=-4+x^2$ → $1$.\n$T(-8+x^3)=-8(1+x)+8x+x^3=-8+x^3$ → $1$.\n$T(x)=3x$ → $3$.\n$[T]_\\beta=\\mathrm{diag}(1,1,1,3)$. 성분합 $=6$.",
  },
  {n:29, subject:"다변수함수", unit:"중적분", concept:"적분순서 변경",
    difficulty:"easyMedium",
    question:"$\\displaystyle\\int_0^2\\!\\!\\int_0^{\\sqrt{4-x^2}}\\!\\sqrt{4-y^2}\\,dy\\,dx$의 값은?",
    options:opts4("$\\dfrac{4\\pi}{3}$","$\\dfrac{5\\pi}{3}$","$\\dfrac{16}{3}$","$\\dfrac{14}{3}$"),
    correct:"3",
    explanation:"영역 $x^2+y^2\\le 4,\\,x\\ge 0,\\,y\\ge 0$. 순서 변경: $0\\le y\\le 2,\\,0\\le x\\le\\sqrt{4-y^2}$.\n$\\!\\int_0^2\\!\\sqrt{4-y^2}\\!\\int_0^{\\sqrt{4-y^2}}\\!dx\\,dy=\\!\\int_0^2(4-y^2)\\,dy=8-\\dfrac{8}{3}=\\dfrac{16}{3}$.",
  },
  {n:30, subject:"선형대수", unit:"고유치와 대각화", concept:"행렬 6제곱근 개수",
    difficulty:"hard",
    question:"모든 성분이 실수인 $3\\times 3$ 행렬(실행렬) $A$가 서로 다른 양수 $3$개를 고윳값으로 가질 때, $B^6=A$를 만족하는 $3\\times 3$ 실행렬 $B$의 개수는?",
    options:opts4("$1$","$6$","$8$","$64$"),
    correct:"3",
    explanation:"$A$ 대각화: $A=PDP^{-1}$, $D=\\mathrm{diag}(\\lambda_1,\\lambda_2,\\lambda_3)$, 모두 양수.\n$B$도 동일 기저에서 대각화 가능, $B=PEP^{-1}$, $E^6=D$.\n각 $i$에서 $\\mu_i^6=\\lambda_i$의 실수해는 $\\pm\\lambda_i^{1/6}$ — 두 개. 총 $2^3=8$.",
  },
];

if (PROBLEMS.length !== 30) { console.error(`PROBLEMS length=${PROBLEMS.length} (expect 30)`); process.exit(1); }
let okCount=0,failCount=0;
for (const p of PROBLEMS) {
  const num=String(p.n).padStart(2,"0");
  const id=`q-${YEAR}-${SCHOOL_EN}-${num}`;
  const tags=[YEAR,SCHOOL_KO,p.subject,p.unit,p.concept].filter(Boolean);
  const row={id,subject:p.subject,unit:p.unit,concept:p.concept,difficulty:p.difficulty,
    source_type:"imported",pool:"general",
    question:p.question,content_type:"latex",question_image:null,
    options:p.options,correct_option_id:p.correct,
    explanation:p.explanation,explanation_content_type:"latex",explanation_image:null,
    tags,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};
  const{error}=await sb.from("questions").upsert(row,{onConflict:"id"});
  if(error){console.error(`❌ ${id}:`,error.message);failCount++;}
  else{console.log(`✓ ${id}`);okCount++;}
}
console.log(`\n총 ${okCount}건 업로드, ${failCount}건 실패 (대상 ${PROBLEMS.length}건)`);
