// 2020년 중앙대(수학과) 편입수학 객관식 30문항 (4지선다)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR="2020", SCHOOL_KO="중앙대", SCHOOL_EN="cau";
const opts4 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:1, subject:"미분학", unit:"극한과 연속", concept:"테일러 급수 극한",
    difficulty:"easy",
    question:"$\\displaystyle\\lim_{\\theta\\to 0}\\dfrac{\\tan\\theta-\\sin\\theta}{\\theta^3}$의 값은?",
    options:opts4("$-\\dfrac{1}{2}$","$-\\dfrac{1}{6}$","$\\dfrac{1}{6}$","$\\dfrac{1}{2}$"),
    correct:"4",
    explanation:"$\\tan\\theta=\\theta+\\dfrac{\\theta^3}{3}+\\cdots,\\,\\sin\\theta=\\theta-\\dfrac{\\theta^3}{6}+\\cdots$.\n차이 $=\\dfrac{\\theta^3}{3}+\\dfrac{\\theta^3}{6}+\\cdots=\\dfrac{\\theta^3}{2}+\\cdots$. 따라서 극한 $=\\dfrac{1}{2}$.",
  },
  {n:2, subject:"미분학", unit:"도함수", concept:"음함수 접선",
    difficulty:"medium",
    question:"곡선 $e^{x/y}=x-y$ 위의 점 $(0,a)$에서 접선이 직선 $y=x+3$과 점 $(b,c)$에서 만날 때 $a+b+c$의 값은?",
    options:opts4("$5$","$10$","$20$","$40$"),
    correct:"2",
    explanation:"$(0,a)$ 대입: $e^0=-a\\Rightarrow a=-1$.\n양변 미분: $e^{x/y}\\cdot\\dfrac{y-xy'}{y^2}=1-y'$. $(0,-1)$ 대입: $1\\cdot(-1)=1-y'\\Rightarrow y'=2$.\n접선 $y=2x-1$. $y=x+3$과 교점: $2x-1=x+3\\Rightarrow x=4,\\,y=7$. $a+b+c=-1+4+7=10$.",
  },
  {n:3, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"평면 반사 최단거리",
    difficulty:"medium",
    question:"$\\mathbb R^3$의 두 점 $A(1,1,1),B(1,1,2)$와 평면 $2x-y+z=0$ 위의 점 $P$에 대하여 $\\overline{PA}+\\overline{PB}$의 최솟값은? (단, $\\overline{XY}$는 $X,Y$ 사이의 거리를 나타낸다.)",
    options:opts4("$\\sqrt 5$","$\\sqrt 6$","$\\sqrt 7$","$\\sqrt 8$"),
    correct:"1",
    explanation:"$B$의 평면 대칭점 $B'$에 대해 $\\overline{PA}+\\overline{PB}\\ge\\overline{AB'}$.\n$B$에서 평면까지 거리 $=\\dfrac{|2-1+2|}{\\sqrt 6}=\\dfrac{3}{\\sqrt 6}$, $B'=B-\\dfrac{2\\cdot 3}{6}(2,-1,1)=(-1,2,1)$.\n$\\overline{AB'}=|(-2,1,0)|=\\sqrt 5$.",
  },
  {n:4, subject:"다변수함수", unit:"중적분", concept:"삼각형 적분",
    difficulty:"medium",
    question:"세 점 $(1,0),(1,2),(4,1)$을 꼭짓점으로 하는 삼각형의 내부를 $T$라 할 때 $\\displaystyle\\iint_T y^2\\,dxdy$의 값은?",
    options:opts4("$\\dfrac{3}{2}$","$\\dfrac{5}{2}$","$\\dfrac{7}{2}$","$\\dfrac{9}{2}$"),
    correct:"3",
    explanation:"세 변: $x=1$, $y=(x-1)/3$, $y=-(x-1)/3+2$.\n$\\!\\int_0^1\\!\\!\\int_1^{3y+1}y^2\\,dx\\,dy+\\!\\int_1^2\\!\\!\\int_1^{7-3y}y^2\\,dx\\,dy=\\!\\int_0^1 3y^3 dy+\\!\\int_1^2(6y^2-3y^3)dy=\\dfrac{3}{4}+\\dfrac{11}{4}=\\dfrac{14}{4}=\\dfrac{7}{2}$.",
  },
  {n:5, subject:"선형대수", unit:"고유치와 대각화", concept:"고유벡터 거듭제곱",
    difficulty:"medium",
    question:"$2\\times 2$ 행렬 $A$가 $A\\begin{pmatrix}1\\\\-1\\end{pmatrix}=\\begin{pmatrix}2\\\\-2\\end{pmatrix},\\,A\\begin{pmatrix}1\\\\1\\end{pmatrix}=\\begin{pmatrix}3\\\\3\\end{pmatrix}$을 만족할 때 $A^{17}\\begin{pmatrix}11\\\\-5\\end{pmatrix}=\\begin{pmatrix}x\\\\y\\end{pmatrix}$라 놓으면 $x-y$의 값은?",
    options:opts4("$2^{19}$","$2^{21}$","$3^{19}$","$3^{21}$"),
    correct:"2",
    explanation:"$\\binom{1}{-1}$은 고윳값 $2$, $\\binom{1}{1}$은 고윳값 $3$.\n$\\binom{11}{-5}=8\\binom{1}{-1}+3\\binom{1}{1}$.\n$A^{17}\\binom{11}{-5}=8\\cdot 2^{17}\\binom{1}{-1}+3\\cdot 3^{17}\\binom{1}{1}=\\binom{2^{20}+3^{18}}{-2^{20}+3^{18}}$.\n$x-y=2\\cdot 2^{20}=2^{21}$.",
  },
  {n:6, subject:"다변수함수", unit:"중적분", concept:"타원체 최댓값 적분",
    difficulty:"hard",
    question:"$I(E)=\\displaystyle\\iiint_E(1-x^2-2y^2-3z^2)\\,dxdydz$의 값이 최대가 되도록 $\\mathbb R^3$의 영역 $E$를 정할 때 $I(E)$의 값은?",
    options:opts4("$\\dfrac{2\\pi}{15\\sqrt 6}$","$\\dfrac{8\\pi}{15\\sqrt 6}$","$\\dfrac{4\\pi}{5\\sqrt 6}$","$\\dfrac{2\\pi}{5\\sqrt 6}$"),
    correct:"2",
    explanation:"피적분이 양수인 영역 $\\{x^2+2y^2+3z^2\\le 1\\}$을 $E$로 잡아야 최대.\n$u=x,\\,v=\\sqrt 2 y,\\,w=\\sqrt 3 z$ 치환. $dV=du\\,dv\\,dw/\\sqrt 6$, 영역 단위구.\n$I=\\dfrac{1}{\\sqrt 6}\\!\\left(\\!\\dfrac{4\\pi}{3}-\\!\\dfrac{4\\pi}{5}\\right)=\\dfrac{1}{\\sqrt 6}\\cdot\\dfrac{8\\pi}{15}=\\dfrac{8\\pi}{15\\sqrt 6}$.",
  },
  {n:7, subject:"선형대수", unit:"선형변환", concept:"기저 변환 합",
    difficulty:"medium",
    question:"$\\mathbb R^3$의 순서기저 $\\beta=\\{v_1,v_2,v_3\\}$에 관한 선형변환 $T:\\mathbb R^3\\to\\mathbb R^3$의 행렬표현이 $\\begin{pmatrix}1&1&-1\\\\2&0&1\\\\1&1&0\\end{pmatrix}$으로 주어진다. $w_1=v_1+2v_2+4v_3,\\,w_2=v_2+2v_3,\\,w_3=v_3$에 대하여 $T(w_1+w_2+w_3)=\\alpha w_1+\\beta w_2+\\gamma w_3$라 할 때 $\\alpha+\\beta+\\gamma$의 값은?",
    options:opts4("$-2$","$-1$","$0$","$3$"),
    correct:"1",
    explanation:"$T(v_1)=v_1+2v_2+v_3,\\,T(v_2)=v_1+v_3,\\,T(v_3)=-v_1+v_2$. $w_1+w_2+w_3=v_1+3v_2+7v_3$.\n$T(\\cdots)=-3v_1+9v_2+4v_3$. $\\alpha w_1+\\beta w_2+\\gamma w_3=\\alpha v_1+(2\\alpha+\\beta)v_2+(4\\alpha+2\\beta+\\gamma)v_3$.\n$\\alpha=-3,\\,\\beta=15,\\,\\gamma=-14$. 합 $=-2$.",
  },
  {n:8, subject:"다변수함수", unit:"곡선과 곡면", concept:"타원 곡률",
    difficulty:"medium",
    question:"타원 $x^2+4y^2=8$ 위의 점 $(2,1)$에서 곡률의 값은?",
    options:opts4("$\\dfrac{2}{25}\\sqrt 5$","$\\dfrac{4}{25}\\sqrt 5$","$\\dfrac{1}{5}\\sqrt 5$","$\\dfrac{8}{5}\\sqrt 5$"),
    correct:"2",
    explanation:"$x=2\\sqrt 2\\cos t,\\,y=\\sqrt 2\\sin t$. $(2,1)\\Rightarrow t=\\pi/4$. $x'=-2,\\,y'=1,\\,x''=-2,\\,y''=-1$.\n$\\kappa=\\dfrac{|x'y''-y'x''|}{(x'^2+y'^2)^{3/2}}=\\dfrac{|(-2)(-1)-1\\cdot(-2)|}{5^{3/2}}=\\dfrac{4}{5\\sqrt 5}=\\dfrac{4\\sqrt 5}{25}$.",
  },
  {n:9, subject:"선형대수", unit:"고유치와 대각화", concept:"A² 특성다항식 도함수",
    difficulty:"hard",
    question:"$3\\times 3$ 행렬 $A$의 특성방정식이 $\\det(A-tI)=-t^3+2t^2+6t-1$로 주어질 때 행렬 $A^2$의 특성다항식을 $p(t)=\\det(A^2-tI)$라 하면 미분계수 $p'(1)$의 값은? (단, $I$는 $3\\times 3$ 단위행렬이다.)",
    options:opts4("$-5$","$7$","$-11$","$13$"),
    correct:"3",
    explanation:"$A$의 고윳값 $\\lambda_i$. $\\!\\sum\\lambda_i=2,\\,\\!\\sum_{i<j}\\lambda_i\\lambda_j=-6,\\,\\prod\\lambda_i=-1$.\n$p(t)=\\!\\prod(\\lambda_i^2-t),\\,p'(t)=-\\!\\sum\\!\\prod_{j\\ne i}(\\lambda_j^2-t)$.\n$p'(1)=-\\!\\sum_{i<j}(\\lambda_i^2-1)(\\lambda_j^2-1)=-(40-32+3)=-11$.",
  },
  {n:10, subject:"선형대수", unit:"행렬", concept:"rank-nullity",
    difficulty:"medium",
    question:"선형변환 $T:\\mathbb R^4\\to\\mathbb R^5$를 $Tv=Av,\\,A=\\begin{pmatrix}2&0&-2&4\\\\1&0&-2&3\\\\0&4&2&1\\\\6&4&-4&13\\\\2&4&-2&7\\end{pmatrix},\\,v\\in\\mathbb R^4$로 정의한다. $T$의 계수(rank)를 $r$, 영공간(Null Space)의 차원을 $n$이라 할 때 $r-n$의 값은?",
    options:opts4("$0$","$1$","$2$","$3$"),
    correct:"3",
    explanation:"행간소: 행 $4=3$행 $1+$행 $3$, 행 $5=2$행 $2+$행 $3$로 종속. 독립 행 $3$개 → $\\mathrm{rank}=3$.\n$n=4-r=1$. $r-n=2$.",
  },
  {n:11, subject:"선형대수", unit:"행렬", concept:"RREF 자유 결합",
    difficulty:"medium",
    question:"행렬 $M$의 기약행사다리꼴(row-reduced echelon form)이 $\\begin{pmatrix}1&0&-2&0&2\\\\0&1&-3&0&5\\\\0&0&0&1&6\\end{pmatrix}$으로 주어진다고 하자. $M$의 첫째, 둘째, 넷째 열이 각각 $\\binom{1}{1}_{\\!2},\\binom{3}{1}_{\\!-1},\\binom{2}{1}_{\\!1}$일 때 $M$의 다섯째 열의 성분을 모두 합하면? (단, 세로벡터를 가로로 표기.)",
    options:opts4("$29$","$34$","$42$","$47$"),
    correct:"4",
    explanation:"RREF의 5열 $(2,5,6)^T$는 5열 $=2\\cdot$1열$+5\\cdot$2열$+6\\cdot$4열의 결합. 같은 결합을 $M$ 열에 적용:\n$2(1,1,2)+5(3,1,-1)+6(2,1,1)=(29,13,5)$. 합 $=47$.",
  },
  {n:12, subject:"다변수함수", unit:"선적분과 면적분", concept:"곡면적분",
    difficulty:"easyMedium",
    question:"곡면 $S=\\{(x,y,z)\\in\\mathbb R^3:z=\\dfrac{1}{2}y^2,\\,0\\le x\\le 1,\\,0\\le y\\le 1\\}$에 대하여 곡면적분 $\\displaystyle\\iint_S\\sqrt{1+y^2}\\,dS$의 값은?",
    options:opts4("$\\dfrac{1}{3}$","$\\dfrac{2}{3}$","$1$","$\\dfrac{4}{3}$"),
    correct:"4",
    explanation:"$dS=\\sqrt{1+z_x^2+z_y^2}dxdy=\\sqrt{1+y^2}dxdy$.\n$\\!\\iint_S\\sqrt{1+y^2}dS=\\!\\int_0^1\\!\\!\\int_0^1(1+y^2)dxdy=1+\\dfrac{1}{3}=\\dfrac{4}{3}$.",
  },
  {n:13, subject:"선형대수", unit:"선형변환", concept:"삼각형 변환 면적",
    difficulty:"easyMedium",
    question:"$T(1,0)=(1,2),\\,T(0,1)=(1,-3)$을 만족하는 선형변환 $T:\\mathbb R^2\\to\\mathbb R^2$가 세 점 $P(1,1),Q(2,3),R(3,2)$를 각각 $P',Q',R'$으로 옮긴다고 할 때 세 점 $P',Q',R'$을 꼭짓점으로 하는 삼각형의 넓이는?",
    options:opts4("$\\dfrac{9}{2}$","$\\dfrac{11}{2}$","$\\dfrac{13}{2}$","$\\dfrac{15}{2}$"),
    correct:"4",
    explanation:"$|\\det T|=|1\\cdot(-3)-2\\cdot 1|=5$. 원본 삼각형 면적 $=\\dfrac{1}{2}|\\det((1,2),(2,1))|=\\dfrac{3}{2}$.\n변환 후 면적 $=5\\cdot\\dfrac{3}{2}=\\dfrac{15}{2}$.",
  },
  {n:14, subject:"다변수함수", unit:"곡선과 곡면", concept:"매개곡선 길이",
    difficulty:"medium",
    question:"곡선 $\\gamma(t)=\\!\\left(\\dfrac{t+1}{t^2+1},\\,\\dfrac{t(t+1)}{t^2+1}\\right),\\,0\\le t\\le 1$의 길이는?",
    options:opts4("$\\pi$","$\\dfrac{\\pi}{\\sqrt 2}$","$\\dfrac{\\pi}{2\\sqrt 2}$","$\\dfrac{\\pi}{4}$"),
    correct:"3",
    explanation:"복소수 표현 $u(t)=\\gamma_x+i\\gamma_y=\\dfrac{(t+1)(1+ti)}{1+t^2}=\\dfrac{t+1}{1-ti}$.\n$u'(t)=\\dfrac{1+i}{(1-ti)^2}$, $|u'|=\\dfrac{\\sqrt 2}{1+t^2}$.\n길이 $=\\!\\int_0^1\\dfrac{\\sqrt 2}{1+t^2}dt=\\sqrt 2\\cdot\\dfrac{\\pi}{4}=\\dfrac{\\pi}{2\\sqrt 2}$.",
  },
  {n:15, subject:"적분학", unit:"급수의 수렴/발산", concept:"Pochhammer 멱급수",
    difficulty:"medium",
    question:"$c>0$일 때 멱급수 $1+\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{(2)_n(-3)_n}{n!\\,(c)_n}\\!\\left(\\dfrac{x}{2}\\right)^{\\!2n}$의 수렴반경을 구하면? (단, 임의의 실수 $\\alpha$에 대하여 $(\\alpha)_n=\\alpha(\\alpha+1)(\\alpha+2)\\cdots(\\alpha+n-1)$.)",
    options:opts4("$2$","$3c$","$6c$","$+\\infty$"),
    correct:"4",
    explanation:"$(-3)_n=(-3)(-2)(-1)(0)\\cdots=0$ for $n\\ge 4$. 즉 급수가 유한합 (다항식)이 되어 모든 $x$에서 수렴.\n수렴반경 $=+\\infty$.",
  },
  {n:16, subject:"적분학", unit:"정적분", concept:"제곱근 치환적분",
    difficulty:"medium",
    question:"$\\displaystyle\\int_0^1\\sqrt{\\dfrac{1-x}{1+x}}\\,dx$의 값은?",
    options:opts4("$-1-\\dfrac{\\pi}{2}$","$-1+\\dfrac{\\pi}{2}$","$1-\\dfrac{\\pi}{2}$","$1+\\dfrac{\\pi}{2}$"),
    correct:"2",
    explanation:"$x=\\cos 2\\theta$ 치환: $\\dfrac{1-x}{1+x}=\\tan^2\\theta$, $dx=-2\\sin 2\\theta\\,d\\theta$.\n$\\!\\int_0^{\\pi/4}\\tan\\theta\\cdot 4\\sin\\theta\\cos\\theta\\,d\\theta=4\\!\\int_0^{\\pi/4}\\sin^2\\theta\\,d\\theta=4\\!\\left[\\dfrac{\\pi}{8}-\\dfrac{1}{4}\\right]=\\dfrac{\\pi}{2}-1$.",
  },
  {n:17, subject:"적분학", unit:"정적분", concept:"삼각함수 적분",
    difficulty:"easy",
    question:"$\\displaystyle\\int_0^{\\pi/2}\\cos^3 x\\sin^3 x\\,dx$의 값은?",
    options:opts4("$\\dfrac{1}{12}$","$\\dfrac{1}{6}$","$\\dfrac{1}{3}$","$\\dfrac{1}{2}$"),
    correct:"1",
    explanation:"$u=\\sin x$: $\\!\\int_0^1(1-u^2)u^3 du=\\dfrac{1}{4}-\\dfrac{1}{6}=\\dfrac{1}{12}$.",
  },
  {n:18, subject:"적분학", unit:"정적분", concept:"지수 치환적분",
    difficulty:"easy",
    question:"$\\displaystyle\\int_0^1 x^5 e^{-x^3}\\,dx$의 값은?",
    options:opts4("$\\dfrac{1}{3}\\!\\left(1-\\dfrac{2}{e}\\right)$","$-\\dfrac{1}{3e}$","$\\dfrac{1}{3e}$","$\\dfrac{1}{3}\\!\\left(1+\\dfrac{2}{e}\\right)$"),
    correct:"1",
    explanation:"$u=x^3$: $x^5\\,dx=u\\cdot\\dfrac{du}{3}$. $\\dfrac{1}{3}\\!\\int_0^1 ue^{-u}du=\\dfrac{1}{3}[-ue^{-u}-e^{-u}]_0^1=\\dfrac{1}{3}(1-2/e)$.",
  },
  {n:19, subject:"공학수학", unit:"Laplace변환", concept:"이상적분",
    difficulty:"easy",
    question:"$a>0$일 때 특이적분 $\\displaystyle\\int_0^{\\infty}e^{-at}\\cos t\\,dt$를 계산하면?",
    options:opts4("$\\dfrac{1}{1+a^2}$","$\\dfrac{a}{1+a^2}$","$\\dfrac{1+a}{1+a^2}$","$\\dfrac{1}{a}$"),
    correct:"2",
    explanation:"$\\mathcal L[\\cos t](a)=\\dfrac{a}{a^2+1}$.",
  },
  {n:20, subject:"적분학", unit:"부정적분", concept:"치환적분",
    difficulty:"easyMedium",
    question:"$g(x)=\\dfrac{1-x}{1+x}$일 때 $\\displaystyle\\int_0^1\\dfrac{g(x)g'(x)}{\\sqrt{1+[g(x)]^2}}\\,dx$의 값은?",
    options:opts4("$-\\sqrt 2$","$-1$","$1-\\sqrt 2$","$\\sqrt 2-1$"),
    correct:"3",
    explanation:"$u=g(x)$: $\\!\\int\\dfrac{u\\,du}{\\sqrt{1+u^2}}=\\sqrt{1+u^2}$. $g(0)=1,g(1)=0$.\n$[\\sqrt{1+u^2}]_1^0=1-\\sqrt 2$.",
  },
  {n:21, subject:"적분학", unit:"부정적분", concept:"바이어슈트라스 치환",
    difficulty:"medium",
    question:"구간 $[0,1]$에서 연속인 함수 $R$에 대하여 정적분 $I=\\displaystyle\\int_0^{\\pi/2}R(\\cos x)\\,dx$를 새로운 변수 $u=\\tan\\!\\left(\\dfrac{x}{2}\\right)$로 치환하여 올바르게 나타낸 것은?",
    options:opts4("$I=2\\!\\displaystyle\\int_0^1 R\\!\\left(\\dfrac{2u}{1+u^2}\\right)\\dfrac{du}{1+u^2}$","$I=2\\!\\displaystyle\\int_0^1 R\\!\\left(\\dfrac{1-u^2}{1+u^2}\\right)\\dfrac{du}{1+u^2}$","$I=2\\!\\displaystyle\\int_0^1 R\\!\\left(\\dfrac{2u}{1+u^2}\\right)\\dfrac{du}{\\sqrt{1+u^2}}$","$I=2\\!\\displaystyle\\int_0^1 R\\!\\left(\\dfrac{1-u^2}{1+u^2}\\right)\\dfrac{du}{\\sqrt{1+u^2}}$"),
    correct:"2",
    explanation:"$x=2\\arctan u$: $dx=\\dfrac{2\\,du}{1+u^2}$, $\\cos x=\\dfrac{1-u^2}{1+u^2}$, 구간 $[0,1]$.",
  },
  {n:22, subject:"적분학", unit:"정적분", concept:"라이프니츠 도함수",
    difficulty:"medium",
    question:"$t>0$일 때 함수 $A(t)=\\dfrac{1}{2}\\cosh t\\sinh t-\\displaystyle\\int_1^{\\cosh t}\\sqrt{\\theta^2-1}\\,d\\theta$의 도함수 $A'(t)$를 구하면?",
    options:opts4("$A'(t)=\\dfrac{1}{2}+\\sinh^2 t$","$A'(t)=\\dfrac{1}{2}+\\sinh^2 t-\\sinh t$","$A'(t)=\\dfrac{1}{2}$","$A'(t)=\\dfrac{1}{2}+\\sinh^2 t+\\sinh t$"),
    correct:"3",
    explanation:"첫 항 미분 $=\\dfrac{1}{2}(\\sinh^2 t+\\cosh^2 t)$.\n둘째 항: $\\sqrt{\\cosh^2 t-1}\\cdot\\sinh t=\\sinh^2 t$.\n$A'(t)=\\dfrac{1}{2}(\\cosh^2 t-\\sinh^2 t)=\\dfrac{1}{2}$.",
  },
  {n:23, subject:"다변수함수", unit:"곡선과 곡면", concept:"외적 크기",
    difficulty:"medium",
    question:"$r(t)=\\dfrac{1}{\\sqrt t}(\\cos t,\\sin t,t)$일 때 외적 $r(t)\\times r'(t)$의 크기(norm)를 구하면? (단, $t>0$.)",
    options:opts4("$\\sqrt{1+\\dfrac{2}{t^2}}$","$\\sqrt{t+\\dfrac{1}{t}}$","$\\dfrac{1}{2}\\sqrt{\\dfrac{t}{5}+\\dfrac{1}{t^3}}$","$\\sqrt{1+\\dfrac{1+\\sin 2t}{t}}$"),
    correct:"1",
    explanation:"$|r\\times r'|^2=|r|^2|r'|^2-(r\\cdot r')^2$.\n계산하면 $|r|^2=\\dfrac{1}{t}+t,\\,|r'|^2=\\dfrac{5}{4t}+\\dfrac{1}{4t^3},\\,r\\cdot r'=\\dfrac{t^2-1}{2t^2}$.\n전개 후 $|r\\times r'|^2=1+\\dfrac{2}{t^2}$.",
  },
  {n:24, subject:"미분학", unit:"극한과 연속", concept:"테일러 도함수",
    difficulty:"easyMedium",
    question:"함수 $B(x)=\\!\\begin{cases}\\dfrac{x}{e^x-1},&(x\\ne 0)\\\\1,&(x=0)\\end{cases}$의 미분계수 $B'(0)$의 값은?",
    options:opts4("$-\\dfrac{1}{2}$","$-\\dfrac{1}{6}$","$\\dfrac{1}{6}$","$\\dfrac{1}{2}$"),
    correct:"1",
    explanation:"$\\dfrac{x}{e^x-1}=1-\\dfrac{x}{2}+\\dfrac{x^2}{12}-\\cdots$ (베르누이 수). $B'(0)=-\\dfrac{1}{2}$.",
  },
  {n:25, subject:"적분학", unit:"급수의 수렴/발산", concept:"디로그함수 계수",
    difficulty:"medium",
    question:"모든 $|x|<1$에 대하여 $-\\displaystyle\\int_0^x\\dfrac{\\log(1-t)}{t}dt=\\!\\sum_{n=1}^{\\infty}A_n x^n$이 성립할 때 $A_{20}$의 값은?",
    options:opts4("$\\dfrac{1}{441}$","$\\dfrac{1}{420}$","$\\dfrac{1}{400}$","$\\dfrac{1}{380}$"),
    correct:"3",
    explanation:"$\\log(1-t)=-\\!\\sum_{n=1}^{\\infty}\\dfrac{t^n}{n}$. $-\\!\\int_0^x\\dfrac{\\log(1-t)}{t}dt=\\!\\sum_{n=1}^{\\infty}\\!\\int_0^x\\dfrac{t^{n-1}}{n}dt=\\!\\sum\\dfrac{x^n}{n^2}$.\n$A_{20}=\\dfrac{1}{400}$.",
  },
  {n:26, subject:"적분학", unit:"급수의 수렴/발산", concept:"멱급수 전개 진위",
    difficulty:"medium",
    question:"다음 <보기>의 급수 전개에서 옳은 것을 모두 고르면? (단, $|x|<\\dfrac{3}{2}$)\n(가) $\\dfrac{3}{3-2x}=\\!\\sum_{n=0}^{\\infty}\\!\\left(\\dfrac{2}{3}\\right)^{\\!n}x^n$\n(나) $\\dfrac{6x}{(3-2x)^2}=\\!\\sum_{n=1}^{\\infty}n\\!\\left(\\dfrac{2}{3}\\right)^{\\!n}x^n$\n(다) $-\\dfrac{3}{2}\\log(3-2x)=-\\dfrac{3}{2}\\log 3+\\!\\sum_{n=1}^{\\infty}\\dfrac{1}{n}\\!\\left(\\dfrac{2}{3}\\right)^{\\!n-1}x^n$",
    options:opts4("(가),(나)","(가),(다)","(나),(다)","(가),(나),(다)"),
    correct:"4",
    explanation:"(가) $\\dfrac{1}{1-(2x/3)}=\\!\\sum(2x/3)^n$. ✓\n(나) (가) 미분 후 $x$ 곱: ✓\n(다) (가) 적분: $-\\dfrac{3}{2}\\log(3-2x)+\\dfrac{3}{2}\\log 3=\\!\\sum\\dfrac{(2/3)^{n-1}}{n}x^n$. ✓\n셋 다 참.",
  },
  {n:27, subject:"미분학", unit:"도함수", concept:"라이프니츠 곱미분",
    difficulty:"medium",
    question:"실수 전체의 집합에서 무한히 미분가능한 두 함수 $f(x),g(x)$의 $x=1$에서 $n$차 도함수의 값이 각각 $(-2)^n,(-3)^n$이라 할 때 $x=1$에서 $f(x)g(x)$의 $8$차 도함수의 값은?",
    options:opts4("$1$","$2^8$","$3^8$","$5^8$"),
    correct:"4",
    explanation:"라이프니츠: $(fg)^{(8)}(1)=\\!\\sum_{k=0}^{8}\\!\\binom{8}{k}(-2)^k(-3)^{8-k}=(-2-3)^8=(-5)^8=5^8$.",
  },
  {n:28, subject:"다변수함수", unit:"편도함수", concept:"코시-슈바르츠 최댓값",
    difficulty:"easy",
    question:"구 $x^2+y^2+z^2=19$ 위에서 함수 $f(x,y,z)=2x+3y+5z$의 최댓값은?",
    options:opts4("$19\\sqrt 3$","$19\\sqrt 2$","$38\\sqrt 3$","$38\\sqrt 2$"),
    correct:"2",
    explanation:"코시: $|2x+3y+5z|\\le\\sqrt{4+9+25}\\cdot\\sqrt{19}=\\sqrt{38\\cdot 19}=\\sqrt{722}=19\\sqrt 2$.",
  },
  {n:29, subject:"다변수함수", unit:"선적분과 면적분", concept:"그린정리",
    difficulty:"medium",
    question:"영역 $\\Omega=\\{(x,y)\\in\\mathbb R^2:0\\le y\\le x,\\,x^2+y^2\\le 1\\}$의 경계를 $\\partial\\Omega$라 할 때 다음 선적분의 값은? (단, $\\partial\\Omega$의 방향은 시계반대방향이다.)\n$$\\int_{\\partial\\Omega}(x^3-y^3+y^2)\\,dx+(x^3+x+2xy)\\,dy$$",
    options:opts4("$\\dfrac{\\pi}{4}$","$\\dfrac{5}{16}\\pi$","$\\dfrac{5}{8}\\pi$","$\\dfrac{5}{2}\\pi$"),
    correct:"2",
    explanation:"그린: $Q_x-P_y=(3x^2+1+2y)-(-3y^2+2y)=3(x^2+y^2)+1$.\n극좌표 $0\\le\\theta\\le\\pi/4,\\,0\\le r\\le 1$:\n$\\!\\int_0^{\\pi/4}\\!\\!\\int_0^1(3r^2+1)r\\,dr\\,d\\theta=\\dfrac{\\pi}{4}\\!\\left(\\dfrac{3}{4}+\\dfrac{1}{2}\\right)=\\dfrac{5\\pi}{16}$.",
  },
  {n:30, subject:"선형대수", unit:"행렬", concept:"행렬식 방정식",
    difficulty:"hard",
    question:"다음과 같이 행렬식의 방정식이 성립하는 경우를 고르면?\n$$\\det\\begin{pmatrix}a&b&a&b\\\\0&a&b&a\\\\2a&3a+2b&3a+3b&3a+2b\\\\3a&-a+3b&3a-b&3b\\end{pmatrix}=16$$",
    options:opts4("$a=-3,\\,b=-\\dfrac{1}{3}$","$a=-2,\\,b=-\\dfrac{1}{4}$","$a=-1,\\,b=\\dfrac{1}{12}$","$a=1,\\,b=\\dfrac{1}{3}$"),
    correct:"2",
    explanation:"$R_3\\to R_3-2R_1-3R_2,\\,R_4\\to R_4-3R_1$로 행렬식 전개. 정리하면 $\\det=k\\cdot a^p b^q$ 형태가 되고, 옵션 대입하여 $16$이 되는 것은 $a=-2,\\,b=-1/4$.",
  },
];

if (PROBLEMS.length !== 30) { console.error(`PROBLEMS length=${PROBLEMS.length} (expect 30)`); process.exit(1); }
let okCount=0,failCount=0;
for (const p of PROBLEMS) {
  const num=String(p.n).padStart(2,"0");
  const id=`q-${YEAR}-${SCHOOL_EN}-${num}`;
  const tags=[YEAR,SCHOOL_KO,p.subject,p.unit,p.concept].filter(Boolean);
  const row={id,subject:p.subject,unit:p.unit,concept:p.concept,difficulty:p.difficulty,
    source_type:"imported",pool:"general",
    question:p.question,content_type:"latex",question_image:null,
    options:p.options,correct_option_id:p.correct,
    explanation:p.explanation,explanation_content_type:"latex",explanation_image:null,
    tags,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};
  const{error}=await sb.from("questions").upsert(row,{onConflict:"id"});
  if(error){console.error(`❌ ${id}:`,error.message);failCount++;}
  else{console.log(`✓ ${id}`);okCount++;}
}
console.log(`\n총 ${okCount}건 업로드, ${failCount}건 실패 (대상 ${PROBLEMS.length}건)`);
