// 2023년 성균관대 편입수학 객관식 20문항 (원 26~45번을 1~20으로 매핑, 5지선다)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR="2023", SCHOOL_KO="성균관대", SCHOOL_EN="skku";
const opts5 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:1, subject:"다변수함수", unit:"중적분", concept:"구면좌표 범위",
    difficulty:"easyMedium",
    question:"원추면 $z=-\\sqrt{x^2+y^2}$의 위와 구면 $x^2+y^2+z^2=4$의 내부에 있는 입체를 구면좌표(spherical coordinates) $(\\rho,\\theta,\\phi)$를 사용하여 나타낼 때, $\\phi$의 범위는?",
    options:opts5("$0\\le\\phi\\le\\dfrac{\\pi}{6}$","$0\\le\\phi\\le\\dfrac{\\pi}{4}$","$0\\le\\phi\\le\\dfrac{\\pi}{2}$","$0\\le\\phi\\le\\dfrac{3\\pi}{4}$","$0\\le\\phi\\le\\dfrac{5\\pi}{6}$"),
    correct:"4",
    explanation:"구면좌표에서 $\\phi$는 $z$축 양의 방향에서 잰 각이다.\n원추면 $z=-\\sqrt{x^2+y^2}$는 $z=\\rho\\cos\\phi$, $\\rho\\sin\\phi=\\sqrt{x^2+y^2}$이므로 $\\cos\\phi=-\\sin\\phi$, 즉 $\\phi=\\dfrac{3\\pi}{4}$.\n따라서 $z\\ge -\\sqrt{x^2+y^2}$ 영역은 $0\\le\\phi\\le\\dfrac{3\\pi}{4}$.",
  },
  {n:2, subject:"다변수함수", unit:"편도함수", concept:"라그랑주 승수법",
    difficulty:"medium",
    question:"부등식 $x^2+y^2+z^2\\le 10$에 의하여 주어지는 영역에서 함수 $f(x,y,z)=y+2z$의 최솟값을 구하면?",
    options:opts5("$-1$","$-2$","$-5\\sqrt 2$","$-\\sqrt{51}$","$-7\\sqrt 3$"),
    correct:"3",
    explanation:"코시-슈바르츠: $(0^2+1^2+2^2)(x^2+y^2+z^2)\\ge(y+2z)^2$.\n$5\\cdot 10\\ge(y+2z)^2$ → $|y+2z|\\le\\sqrt{50}=5\\sqrt 2$.\n내부에서는 $\\nabla f=(0,1,2)\\ne 0$이므로 임계점이 없어 경계에서 최솟값. 최솟값 $=-5\\sqrt 2$.",
  },
  {n:3, subject:"선형대수", unit:"선형변환", concept:"직교여공간 차원",
    difficulty:"medium",
    question:"선형변환 $T:\\mathbb R^4\\to\\mathbb R^6$를 나타내는 행렬이 $\\begin{pmatrix}1&0&1&1\\\\1&-1&0&0\\\\1&0&1&1\\\\0&1&1&1\\\\0&1&1&1\\\\0&1&1&1\\end{pmatrix}$이고, 유클리드 내적공간 $\\mathbb R^6$ 상의 부분공간 $W$를 $W=\\{w\\in\\mathbb R^6\\mid v\\in\\mathrm{Im}\\,T\\text{인 모든 }v\\text{에 대해 }v\\cdot w=0\\}$로 정의할 때, $W$의 차원(dimension)은? (단, $\\mathrm{Im}\\,T=\\{T(u)\\mid u\\in\\mathbb R^4\\}$이고 $v\\cdot w$는 $\\mathbb R^6$ 상의 표준내적이다.)",
    options:opts5("$1$","$2$","$3$","$4$","$5$"),
    correct:"4",
    explanation:"$W=(\\mathrm{Im}\\,T)^\\perp$이므로 $\\dim W=6-\\dim(\\mathrm{Im}\\,T)=6-\\mathrm{rank}\\,T$.\n행렬의 1행=3행, 4행=5행=6행이고 2행 $=$ 1행 $-$ 4행 (실제로 $(1,0,1,1)-(0,1,1,1)=(1,-1,0,0)$).\n독립 행은 1행, 4행 두 개 → $\\mathrm{rank}=2$.\n$\\dim W=6-2=4$.",
  },
  {n:4, subject:"공학수학", unit:"미분방정식", concept:"적분인자",
    difficulty:"medium",
    question:"미분방정식 $\\dfrac{-2y}{x}\\,dx+(x^2 y\\cos y+1)\\,dy=0$의 적분인자(integrating factor)인 것은?",
    options:opts5("$1$","$\\dfrac{-2}{x}$","$\\dfrac{1}{x^2}$","$-2x$","$x^2$"),
    correct:"3",
    explanation:"$\\mu=\\dfrac{1}{x^2}$을 곱하면 $-\\dfrac{2y}{x^3}\\,dx+\\!\\left(y\\cos y+\\dfrac{1}{x^2}\\right)\\!dy=0$.\n$M_y=-\\dfrac{2}{x^3},\\,N_x=-\\dfrac{2}{x^3}$ → 완미. 따라서 적분인자 $\\dfrac{1}{x^2}$.",
  },
  {n:5, subject:"적분학", unit:"급수의 수렴/발산", concept:"멱급수와 sin",
    difficulty:"medium",
    question:"멱급수(power series) $f(x)=\\displaystyle\\sum_{k=0}^{\\infty}\\dfrac{x^k}{(2k+1)!}=1+\\dfrac{x}{3!}+\\dfrac{x^2}{5!}+\\dfrac{x^3}{7!}+\\cdots$는 모든 실수 $x$에 대하여 수렴한다. 방정식 $f(x)=0$의 해집합은?",
    options:opts5("$\\{-(n\\pi)^2\\mid n=1,2,3,\\cdots\\}$","$\\{-(2n\\pi)^2\\mid n=1,2,3,\\cdots\\}$","$\\{-n\\pi\\mid n=1,2,3,\\cdots\\}$","$\\{-2n\\pi\\mid n=1,2,3,\\cdots\\}$","$\\{-(2n+1)\\pi\\mid n=1,2,3,\\cdots\\}$"),
    correct:"1",
    explanation:"$\\sin t=\\displaystyle\\sum_{k=0}^{\\infty}\\dfrac{(-1)^k t^{2k+1}}{(2k+1)!}$이므로 $\\dfrac{\\sin t}{t}=\\displaystyle\\sum_{k=0}^{\\infty}\\dfrac{(-1)^k t^{2k}}{(2k+1)!}$.\n$x=-t^2$ ($t>0$)로 두면 $f(-t^2)=\\dfrac{\\sin t}{t}$.\n$f(x)=0\\iff\\sin t=0,\\,t\\ne 0\\iff t=n\\pi$ → $x=-(n\\pi)^2$.",
  },
  {n:6, subject:"미분학", unit:"도함수와 그래프", concept:"f' 그래프 해석",
    difficulty:"easyMedium",
    question:"다음 그래프는 도함수 $f'(x)$의 그래프이다. 주어진 $f(x)$값들 중에서 가장 큰 값은?\n\n(그래프 개요: $0<x<1$에서 $f'(x)>0$, $x=1$에서 $f'=0$, $1<x<4$에서 $f'(x)<0$, $x=4$에서 $f'=0$, $x>4$에서 $f'(x)>0$)",
    options:opts5("$f\\!\\left(\\dfrac{1}{2}\\right)$","$f(1)$","$f(2)$","$f(3)$","$f(4)$"),
    correct:"2",
    explanation:"$f'(1)=0$에서 부호가 $+\\to-$이므로 $x=1$에서 극대. $x=4$에서 부호가 $-\\to+$이므로 극소.\n$f(1/2)<f(1)$ ($[1/2,1]$에서 $f'>0$, 누적). $f(2),f(3),f(4)<f(1)$ ($[1,x]$에서 $f'<0$).\n따라서 $f(1)$이 가장 크다.",
  },
  {n:7, subject:"공학수학", unit:"미분방정식", concept:"변수분리",
    difficulty:"easyMedium",
    question:"미분방정식 $y\\,dx+\\sqrt{x^2+1}\\,dy=0$의 해는? (단, $C$는 적분상수를 나타낸다.)",
    options:opts5("$y\\!\\left(1+\\sqrt{x^2+1}\\right)=C$","$y\\!\\left(x+\\sqrt{x^2+1}\\right)=C$","$xy+\\sqrt{x^2+1}=C$","$xy+\\dfrac{y}{\\sqrt{x^2+1}}=C$","$y\\!\\left(1+\\dfrac{x}{\\sqrt{x^2+1}}\\right)=C$"),
    correct:"2",
    explanation:"변수분리: $\\dfrac{dy}{y}=-\\dfrac{dx}{\\sqrt{x^2+1}}$.\n적분: $\\ln|y|=-\\ln\\!\\left|x+\\sqrt{x^2+1}\\right|+C_1$.\n따라서 $y\\!\\left(x+\\sqrt{x^2+1}\\right)=C$.",
  },
  {n:8, subject:"공학수학", unit:"미분방정식", concept:"멱급수해 수렴반경",
    difficulty:"medium",
    question:"$y(x)=\\displaystyle\\sum_{n=0}^{\\infty}a_n(x-1)^n$이 미분방정식 $(x+2)(x^2+4)y''+(x+20)y'+(x^2+23)y=0$의 멱급수해(power series solution)일 때, 이 해의 수렴반경은?",
    options:opts5("$\\dfrac{1}{2}$","$\\sqrt 3$","$2$","$\\sqrt 5$","$\\dfrac{3}{2}$"),
    correct:"4",
    explanation:"$y''$의 계수 $(x+2)(x^2+4)=0$의 근(특이점)은 $x=-2,\\,\\pm 2i$.\n전개점 $x_0=1$에서 각 특이점까지 거리: $|-2-1|=3,\\,|2i-1|=\\sqrt 5,\\,|-2i-1|=\\sqrt 5$.\n수렴반경은 가장 가까운 특이점까지 거리 $=\\sqrt 5$.",
  },
  {n:9, subject:"적분학", unit:"정적분", concept:"floor 함수 적분",
    difficulty:"medium",
    question:"$[x]$가 $x$보다 크지 않은 최대 정수를 나타낼 때, 적분 $\\displaystyle\\int_0^{\\infty}[x]e^{-x}\\,dx$의 값은?",
    options:opts5("$\\dfrac{e}{e^2-1}$","$\\dfrac{1}{e-1}$","$\\dfrac{e-1}{e}$","$1$","$+\\infty$"),
    correct:"2",
    explanation:"$\\displaystyle\\int_0^{\\infty}[x]e^{-x}dx=\\sum_{n=1}^{\\infty}n\\!\\int_n^{n+1}e^{-x}dx=\\sum_{n=1}^{\\infty}n\\!\\left(e^{-n}-e^{-(n+1)}\\right)$.\n$=(1-e^{-1})\\displaystyle\\sum_{n=1}^{\\infty}ne^{-n}=(1-e^{-1})\\cdot\\dfrac{e^{-1}}{(1-e^{-1})^2}=\\dfrac{e^{-1}}{1-e^{-1}}=\\dfrac{1}{e-1}$.",
  },
  {n:10, subject:"적분학", unit:"정적분", concept:"회전체 부피",
    difficulty:"hard",
    question:"다음의 영역 $D=\\{(x,y)\\mid x^2+y^2\\le 1,\\,(x-1)^2+y^2\\le 1\\}$를 $y$축을 중심으로 회전시킬 때 얻어지는 입체의 부피는?",
    options:opts5("$\\dfrac{2}{3}\\pi^2-\\dfrac{\\sqrt 3}{2}\\pi$","$\\dfrac{1}{3}\\pi^2-\\dfrac{\\sqrt 3}{2}\\pi$","$\\dfrac{1}{3}\\pi-\\dfrac{\\sqrt 3}{2}\\pi^2$","$\\dfrac{1}{2}\\pi^2-\\dfrac{\\sqrt 3}{2}\\pi$","$\\dfrac{2}{3}\\pi-\\dfrac{\\sqrt 3}{3}\\pi^2$"),
    correct:"1",
    explanation:"교집합 $D$는 $0\\le x\\le 1$. 원통껍질법: $V=2\\pi\\!\\displaystyle\\int_0^1 x\\cdot 2y_{\\max}(x)\\,dx$.\n$x\\in[0,1/2]$: $y_{\\max}=\\sqrt{2x-x^2}$. $x\\in[1/2,1]$: $y_{\\max}=\\sqrt{1-x^2}$.\n$\\displaystyle\\int_{1/2}^1 x\\sqrt{1-x^2}\\,dx=\\dfrac{\\sqrt 3}{8}$.\n$\\displaystyle\\int_0^{1/2}x\\sqrt{2x-x^2}\\,dx$: $u=x-1$ 치환·삼각치환 $u=\\sin\\theta$로 $\\dfrac{\\pi}{6}-\\dfrac{\\sqrt 3}{4}$.\n합 $=\\dfrac{\\pi}{6}-\\dfrac{\\sqrt 3}{8}$. $V=4\\pi\\!\\left(\\dfrac{\\pi}{6}-\\dfrac{\\sqrt 3}{8}\\right)=\\dfrac{2}{3}\\pi^2-\\dfrac{\\sqrt 3}{2}\\pi$.",
  },
  {n:11, subject:"선형대수", unit:"행렬", concept:"치환의 부호",
    difficulty:"easyMedium",
    question:"집합 $\\{1,2,3,4,5,6\\}$ 상의 다음의 치환(permutation) 중에서 짝치환(even permutation)은?",
    options:opts5("$\\begin{pmatrix}1&2&3&4&5&6\\\\4&5&6&1&2&3\\end{pmatrix}$","$\\begin{pmatrix}1&2&3&4&5&6\\\\2&4&5&1&3&6\\end{pmatrix}$","$\\begin{pmatrix}1&2&3&4&5&6\\\\2&3&4&5&6&1\\end{pmatrix}$","$\\begin{pmatrix}1&2&3&4&5&6\\\\3&2&1&6&4&5\\end{pmatrix}$","$\\begin{pmatrix}1&2&3&4&5&6\\\\2&1&4&5&6&3\\end{pmatrix}$"),
    correct:"5",
    explanation:"각 치환을 사이클 분해하여 전치 수의 홀짝을 판정.\n(1) $(1\\,4)(2\\,5)(3\\,6)$ → 3 전치 (홀).\n(2) $(1\\,2\\,4)(3\\,5)$ → $2+1=3$ (홀).\n(3) $(1\\,2\\,3\\,4\\,5\\,6)$ → 5 전치 (홀).\n(4) $(1\\,3)(4\\,6\\,5)$ → $1+2=3$ (홀).\n(5) $(1\\,2)(3\\,4\\,5\\,6)$ → $1+3=4$ (짝). 정답.",
  },
  {n:12, subject:"적분학", unit:"정적분", concept:"무게중심",
    difficulty:"medium",
    question:"두 곡선 $C_1:\\{(x,y)\\mid x=y,\\,0\\le x\\le 1\\},\\,C_2:\\{(x,y)\\mid x=t^2,\\,y=t^3,\\,0\\le t\\le 1\\}$에 의해 둘러싸인 영역을 $D$라 할 때, $D$의 무게중심(centroid, center of mass)을 $(\\bar x,\\bar y)$라 하자. $(\\bar x,\\bar y)$의 값은?",
    options:opts5("$\\!\\left(\\dfrac{10}{21},\\dfrac{10}{24}\\right)$","$\\!\\left(\\dfrac{10}{20},\\dfrac{10}{24}\\right)$","$\\!\\left(\\dfrac{10}{21},\\dfrac{10}{23}\\right)$","$\\!\\left(\\dfrac{10}{20},\\dfrac{10}{22}\\right)$","$\\!\\left(\\dfrac{10}{22},\\dfrac{10}{23}\\right)$"),
    correct:"1",
    explanation:"$C_2$는 $y=x^{3/2}$. $D=\\{x^{3/2}\\le y\\le x,\\,0\\le x\\le 1\\}$.\n$A=\\displaystyle\\int_0^1(x-x^{3/2})\\,dx=\\dfrac{1}{2}-\\dfrac{2}{5}=\\dfrac{1}{10}$.\n$\\bar x=\\dfrac{1}{A}\\!\\displaystyle\\int_0^1\\!x(x-x^{3/2})dx=10\\!\\left(\\dfrac{1}{3}-\\dfrac{2}{7}\\right)=\\dfrac{10}{21}$.\n$\\bar y=\\dfrac{1}{A}\\!\\displaystyle\\int_0^1\\dfrac{1}{2}(x^2-x^3)dx=10\\cdot\\dfrac{1}{2}\\!\\left(\\dfrac{1}{3}-\\dfrac{1}{4}\\right)=\\dfrac{10}{24}$.",
  },
  {n:13, subject:"적분학", unit:"정적분", concept:"매개변수 적분 미분",
    difficulty:"medium",
    question:"$f(x)=\\displaystyle\\int_x^1 e^{t^2+xt}\\,dt$일 때, $f'(0)$은?",
    options:opts5("$e\\cos(1)-2$","$-2+e$","$\\dfrac{e}{2}-\\dfrac{3}{2}$","$\\dfrac{e}{2}+\\dfrac{1}{2}$","$\\dfrac{e}{2}-\\dfrac{1}{2}$"),
    correct:"3",
    explanation:"라이프니츠: $f'(x)=-e^{x^2+x\\cdot x}+\\displaystyle\\int_x^1 t\\,e^{t^2+xt}\\,dt$.\n$x=0$: $f'(0)=-e^0+\\displaystyle\\int_0^1 t\\,e^{t^2}dt=-1+\\!\\left[\\dfrac{e^{t^2}}{2}\\right]_0^1=-1+\\dfrac{e-1}{2}=\\dfrac{e}{2}-\\dfrac{3}{2}$.",
  },
  {n:14, subject:"선형대수", unit:"고유치와 대각화", concept:"rank 1 대각화",
    difficulty:"medium",
    question:"행렬 $A=\\begin{pmatrix}1&1&1\\\\1&1&1\\\\1&1&1\\end{pmatrix}$에 관한 다음 <보기> 중 옳은 것을 모두 고르면?\n(가) $A$의 모든 고윳값(eigenvalue)의 합은 $3$이다.\n(나) $A$의 모든 고유벡터(eigenvector)에 의해 생성되는 벡터공간은 $\\mathbb R^3$이다.\n(다) $A$는 대각화가능(diagonalizable)하다.",
    options:opts5("(가)","(가),(나)","(가),(다)","(나),(다)","(가),(나),(다)"),
    correct:"5",
    explanation:"$A$는 rank $1$ 대칭행렬. 고유값 $3,0,0$.\n(가) 합 $=\\mathrm{tr}\\,A=3$. 참.\n(나) $\\lambda=3$ 고유벡터 $(1,1,1)$, $\\lambda=0$ 고유벡터 $(1,-1,0),(1,0,-1)$ → $\\mathbb R^3$ 생성. 참.\n(다) 대칭행렬은 항상 대각화 가능. 참.",
  },
  {n:15, subject:"공학수학", unit:"Laplace변환", concept:"적분의 라플라스",
    difficulty:"easyMedium",
    question:"$f(t)=\\displaystyle\\int_0^t\\sin(2v)\\,dv$의 라플라스 변환을 $F(s)$라고 할 때, $F(2)$를 구하면?",
    options:opts5("$1$","$\\dfrac{7}{28}$","$-\\dfrac{1}{4}$","$\\dfrac{1}{8}$","$-\\dfrac{2}{3}$"),
    correct:"4",
    explanation:"$\\mathcal L\\!\\left[\\int_0^t g(v)\\,dv\\right]=\\dfrac{G(s)}{s}$.\n$\\mathcal L[\\sin 2t]=\\dfrac{2}{s^2+4}$ → $F(s)=\\dfrac{2}{s(s^2+4)}$.\n$F(2)=\\dfrac{2}{2\\cdot 8}=\\dfrac{1}{8}$.",
  },
  {n:16, subject:"선형대수", unit:"행렬", concept:"4차 행렬식",
    difficulty:"hard",
    question:"행렬식(determinant) $\\begin{vmatrix}1&1&1&9^3\\\\1&2&2^2&8^3\\\\1&3&3^2&7^3\\\\1&4&4^2&6^3\\end{vmatrix}$의 값은?",
    options:opts5("$-12$","$-11$","$-10$","$-9$","$-8$"),
    correct:"1",
    explanation:"각 행에서 1행을 빼서 1열에 0을 만든다.\n$R_2\\!-\\!R_1\\!=\\!(0,1,3,-217),\\,R_3\\!-\\!R_1\\!=\\!(0,2,8,-386),\\,R_4\\!-\\!R_1\\!=\\!(0,3,15,-513)$.\n$\\det=\\begin{vmatrix}1&3&-217\\\\2&8&-386\\\\3&15&-513\\end{vmatrix}$.\n$=1\\cdot(8\\cdot(-513)-(-386)\\cdot 15)-3\\cdot(2\\cdot(-513)-(-386)\\cdot 3)-217(2\\cdot 15-8\\cdot 3)$.\n$=1686-3\\cdot 132-217\\cdot 6=1686-396-1302=-12$.",
  },
  {n:17, subject:"다변수함수", unit:"선적분과 면적분", concept:"보존장과 발산정리",
    difficulty:"medium",
    question:"다음 <보기> 중 참인 것을 모두 고른 것은?\n(가) $\\nabla f=(y+x^3)\\mathbf i+(x+z\\sin y)\\mathbf j-\\cos y\\,\\mathbf k$를 만족하는 함수 $f:\\mathbb R^3\\to\\mathbb R$가 존재한다.\n(나) $\\mathrm{curl}\\,F=y^2\\mathbf i+x^3\\mathbf j+z\\mathbf k$을 만족하는 $\\mathbb R^3$ 상의 벡터장 $F$가 존재한다.\n(다) $S$가 구면 $x^2+y^2+z^2=z$이고 $F$가 상수벡터장(constant vector field)이면, 이때 $\\displaystyle\\iint_S F\\cdot dS=0$이다.",
    options:opts5("(가),(나),(다)","(나),(다)","(가),(다)","(가),(나)","(가)"),
    correct:"3",
    explanation:"(가) 혼합편미분 검사: $f_{xy}=1=f_{yx}$, $f_{xz}=0=f_{zx}$, $f_{yz}=\\sin y=f_{zy}$ → 보존장. 참.\n(나) $\\mathrm{div}(\\mathrm{curl}\\,F)\\equiv 0$이어야 하나 $\\mathrm{div}(y^2,x^3,z)=1\\ne 0$. 거짓.\n(다) $S$는 닫힌 구면, 상수벡터장 $F$는 $\\mathrm{div}\\,F=0$. 발산정리: $\\iint_S F\\cdot dS=0$. 참.",
  },
  {n:18, subject:"선형대수", unit:"선형변환", concept:"기저 표현 선형변환",
    difficulty:"medium",
    question:"벡터공간 $\\mathbb R^3$ 상의 기저(basis) $\\{v_1,v_2,v_3\\}$와 선형변환 $T:\\mathbb R^3\\to\\mathbb R^3$가\n$T(v_1+v_2)=v_1-v_3,\\,T(v_2-v_3)=v_1+v_2,\\,T(v_1-v_3)=v_2+v_3$\n을 만족할 때, $T(4v_1+3v_2-5v_3)$의 값은?",
    options:opts5("$3v_1-5v_2-2v_3$","$-3v_1+5v_2-2v_3$","$3v_1-5v_2+2v_3$","$-3v_1-5v_2+2v_3$","$3v_1+5v_2+2v_3$"),
    correct:"5",
    explanation:"$4v_1+3v_2-5v_3=a(v_1+v_2)+b(v_2-v_3)+c(v_1-v_3)$로 표현.\n계수 비교: $a+c=4,\\,a+b=3,\\,-b-c=-5$. 풀면 $a=1,\\,b=2,\\,c=3$.\n$T(\\cdots)=1\\cdot(v_1-v_3)+2\\cdot(v_1+v_2)+3\\cdot(v_2+v_3)=3v_1+5v_2+2v_3$.",
  },
  {n:19, subject:"공학수학", unit:"미분방정식", concept:"자율방정식 점근거동",
    difficulty:"medium",
    question:"$y=y(t)$가 미분방정식 $y'=(y^2-1)e^{2023y+1},\\,y(0)=\\dfrac{1}{2}$의 해 일 때, 다음 <보기> 중 참인 것을 모두 고른 것은?\n(가) $\\displaystyle\\lim_{t\\to\\infty}y(t)=-\\infty$\n(나) $\\displaystyle\\lim_{t\\to\\infty}y(t)=1$\n(다) $\\displaystyle\\lim_{t\\to\\infty}y(t)=-1$\n(라) 모든 $t$에 대하여 $-1<y(t)<1$.\n(마) 모든 $t$에 대하여 $|y(t)|>1$.",
    options:opts5("(가)","(가),(마)","(나),(라)","(다),(라)","(다),(마)"),
    correct:"4",
    explanation:"평형해 $y=\\pm 1$. $y(0)=1/2\\in(-1,1)$이고 이 구간에서는 $y^2-1<0$, $e^{2023y+1}>0$이므로 $y'<0$. $y$가 단조감소.\n해는 평형선 $y=\\pm 1$을 가로지를 수 없으므로 $-1<y(t)<1$이 유지되고, $t\\to\\infty$에서 안정 평형 $y=-1$로 수렴.\n(다), (라) 참.",
  },
  {n:20, subject:"다변수함수", unit:"선적분과 면적분", concept:"스토크스 정리",
    difficulty:"hard",
    question:"곡면 $S$는 평면 $z=1$ 위쪽에 놓여있는 곡면 $z=10-x^2-y^2$의 부분이고, $S$의 방향(orientation)은 위쪽을 향한다고 하자. 이 때, 벡터장 $F(x,y,z)=\\!\\left(e^{y+z}-2y\\right)\\mathbf i+\\!\\left(xe^{y+z}+y\\right)\\mathbf j+e^{x+y}\\mathbf k$에 대하여 $\\displaystyle\\iint_S\\mathrm{curl}\\,F\\cdot dS$를 계산하면?",
    options:opts5("$\\dfrac{27}{5}\\pi$","$9\\pi$","$12\\pi$","$\\dfrac{95}{7}\\pi$","$18\\pi$"),
    correct:"5",
    explanation:"스토크스: $\\iint_S\\mathrm{curl}\\,F\\cdot dS=\\oint_C F\\cdot d\\mathbf r$, $C:z=1\\cap z=10-x^2-y^2$ → $x^2+y^2=9$.\n$\\mathbf r(t)=(3\\cos t,3\\sin t,1)$, $d\\mathbf r=(-3\\sin t,3\\cos t,0)dt$.\n$(e^{y+z},xe^{y+z},0)=\\nabla(xe^{y+z})$는 보존장 → 적분 0.\n남은 $F'=(-2y,y,e^{x+y})\\cdot d\\mathbf r$의 $\\mathbf k$ 성분은 0.\n$\\oint(-2y\\cdot(-3\\sin t)+y\\cdot 3\\cos t)dt=\\!\\int_0^{2\\pi}(18\\sin^2 t+9\\sin t\\cos t)dt=18\\pi$.",
  },
];

if (PROBLEMS.length !== 20) { console.error(`PROBLEMS length=${PROBLEMS.length} (expect 20)`); process.exit(1); }
let okCount=0,failCount=0;
for (const p of PROBLEMS) {
  const num=String(p.n).padStart(2,"0");
  const id=`q-${YEAR}-${SCHOOL_EN}-${num}`;
  const tags=[YEAR,SCHOOL_KO,p.subject,p.unit,p.concept].filter(Boolean);
  const row={id,subject:p.subject,unit:p.unit,concept:p.concept,difficulty:p.difficulty,
    source_type:"imported",pool:"general",
    question:p.question,content_type:"latex",question_image:null,
    options:p.options,correct_option_id:p.correct,
    explanation:p.explanation,explanation_content_type:"latex",explanation_image:null,
    tags,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};
  const{error}=await sb.from("questions").upsert(row,{onConflict:"id"});
  if(error){console.error(`❌ ${id}:`,error.message);failCount++;}
  else{console.log(`✓ ${id}`);okCount++;}
}
console.log(`\n총 ${okCount}건 업로드, ${failCount}건 실패 (대상 ${PROBLEMS.length}건)`);
