// 2022년 단국대 오전 편입수학 객관식 20문항 (4지선다, 문항 번호 31~50)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR_ID="2022am", YEAR_KO="2022", SESSION_KO="오전", SCHOOL_KO="단국대", SCHOOL_EN="dankook";
const opts4 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:31, subject:"미분학", unit:"극한과 연속", concept:"로피탈 (쌍곡함수)",
    difficulty:"easy",
    question:"$\\displaystyle\\lim_{x\\to 0}\\dfrac{\\sinh x}{e^x-1}$의 값은?",
    options:opts4("$0$","$\\dfrac{1}{2}$","$1$","$2$"),
    correct:"3",
    explanation:"로피탈: $\\!\\lim_{x\\to 0}\\dfrac{\\cosh x}{e^x}=\\dfrac{1}{1}=1$.",
  },
  {n:32, subject:"미분학", unit:"도함수 응용", concept:"폐구간 최대·최솟값",
    difficulty:"easy",
    question:"구간 $[1,4]$에서 함수 $f(x)=x^2+\\dfrac{16}{x}$의 최솟값과 최댓값의 합은?",
    options:opts4("$29$","$32$","$\\dfrac{103}{3}$","$39$"),
    correct:"2",
    explanation:"$f'(x)=2x-\\dfrac{16}{x^2}=\\dfrac{2(x^3-8)}{x^2}=0\\Rightarrow x=2$.\n$f(1)=17,\\,f(2)=12,\\,f(4)=20$.\n최소 $12$, 최대 $20$. 합 $32$.",
  },
  {n:33, subject:"적분학", unit:"정적분의 응용", concept:"두 곡선 둘러싼 면적",
    difficulty:"medium",
    question:"두 곡선 $y=\\cos x,\\,y=\\sin 2x$와 두 직선 $x=0,\\,x=\\dfrac{\\pi}{2}$로 둘러싸인 영역의 넓이는?",
    options:opts4("$\\dfrac{1}{2}$","$1$","$\\dfrac{3}{2}$","$2$"),
    correct:"1",
    explanation:"$\\cos x=\\sin 2x=2\\sin x\\cos x\\Rightarrow\\sin x=1/2,\\,x=\\pi/6$.\n$\\!\\int_0^{\\pi/6}(\\cos x-\\sin 2x)dx+\\!\\int_{\\pi/6}^{\\pi/2}(\\sin 2x-\\cos x)dx=\\dfrac{1}{4}+\\dfrac{1}{4}=\\dfrac{1}{2}$.",
  },
  {n:34, subject:"적분학", unit:"급수의 수렴/발산", concept:"멱급수 수렴 정수 개수",
    difficulty:"medium",
    question:"멱급수 $\\displaystyle\\sum_{n=1}^{\\infty}(-1)^n\\dfrac{(x+3)^n}{n3^n}$이 수렴하는 모든 정수 $x$의 개수는?",
    options:opts4("$3$","$4$","$5$","$6$"),
    correct:"4",
    explanation:"수렴반경 $R=3$, 중심 $-3$. $|x+3|<3\\Rightarrow-6<x<0$. 끝점: $x=-6$ 발산($\\sum 1/n$), $x=0$ 수렴(교대).\n수렴 범위 $-6<x\\le 0$. 정수 $x=-5,-4,-3,-2,-1,0$ 6개.",
  },
  {n:35, subject:"적분학", unit:"이상적분", concept:"이상적분 수렴 식별",
    difficulty:"medium",
    question:"다음 중 수렴하는 특이적분의 개수는?\n\nㄱ. $\\displaystyle\\int_1^{\\infty}\\dfrac{\\ln x}{x^2}\\,dx$\nㄴ. $\\displaystyle\\int_2^{\\infty}\\dfrac{2+e^{-x}}{x}\\,dx$\nㄷ. $\\displaystyle\\int_1^2\\dfrac{x}{1-x^2}\\,dx$\nㄹ. $\\displaystyle\\int_1^3\\dfrac{1}{\\sqrt{x-1}}\\,dx$",
    options:opts4("$0$","$1$","$2$","$3$"),
    correct:"3",
    explanation:"ㄱ [수렴] $\\!\\int\\dfrac{\\ln x}{x^2}\\sim\\!\\int 1/x^2$ 수렴.\nㄴ [발산] $\\sim\\!\\int 2/x$ 발산.\nㄷ [발산] $x=1$ 특이점, $\\sim 1/(1-x)$ 발산 (대수).\nㄹ [수렴] $1/\\sqrt{x-1}$ 적분가능.\n수렴: ㄱ, ㄹ → 2개.",
  },
  {n:36, subject:"다변수함수", unit:"극좌표와 극곡선", concept:"극곡선 접선 기울기 0",
    difficulty:"medium",
    question:"극 곡선 $r=1+\\sin\\theta$에 대하여 $\\theta=\\theta_0$일 때의 접선의 기울기가 $0$인 $\\theta_0$의 값을 모두 더하면? (단, $-\\pi\\le\\theta\\le\\pi$이다.)",
    options:opts4("$-\\pi$","$-\\dfrac{\\pi}{2}$","$\\dfrac{\\pi}{2}$","$\\pi$"),
    correct:"2",
    explanation:"$y=r\\sin\\theta=(1+\\sin\\theta)\\sin\\theta$. $dy/d\\theta=\\cos\\theta(1+2\\sin\\theta)=0$.\n$\\cos\\theta=0$: $\\theta=\\pm\\pi/2$. $\\sin\\theta=-1/2$: $\\theta=-\\pi/6,-5\\pi/6$.\n$dx/d\\theta\\ne 0$ 점만 유효. $\\theta=\\pi/2$에서 $r=2$, $\\theta=-\\pi/2$에서 $r=0$ (접선 정의 ?).\n실제 분석으로 합 $=\\pi/2-\\pi/6-5\\pi/6=-\\pi/2$.",
  },
  {n:37, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"사면체 부피 (스칼라삼중적)",
    difficulty:"easy",
    question:"3차원 공간에서 네 점 $P(-3,1,0),\\,Q(-2,2,1),\\,R(2,3,-2),\\,S(2,5,-1)$을 꼭짓점으로 하는 사면체의 부피는?",
    options:opts4("$11$","$\\dfrac{11}{6}$","$\\dfrac{11}{4}$","$\\dfrac{11}{3}$"),
    correct:"2",
    explanation:"$\\vec{PQ}=(1,1,1),\\,\\vec{PR}=(5,2,-2),\\,\\vec{PS}=(5,4,-1)$.\n$V=\\dfrac{1}{6}|\\vec{PQ}\\cdot(\\vec{PR}\\times\\vec{PS})|=\\dfrac{1}{6}\\!\\left|\\det\\begin{pmatrix}1&1&1\\\\5&2&-2\\\\5&4&-1\\end{pmatrix}\\right|=\\dfrac{1}{6}\\cdot 11=\\dfrac{11}{6}$.",
  },
  {n:38, subject:"다변수함수", unit:"편미분", concept:"방향도함수 (상수 결정)",
    difficulty:"medium",
    question:"함수 $f(x,y,z)=kxy^2\\sin z$에 대하여 점 $(1,1,0)$에서 벡터 $\\vec{v}=\\langle 1,2,-1\\rangle$ 방향으로 함수 $f$의 방향 도함수가 $\\sqrt{6}$일 때, 상수 $k$의 값은?",
    options:opts4("$-6$","$-\\sqrt{6}$","$\\sqrt{6}$","$6$"),
    correct:"1",
    explanation:"$\\nabla f=(ky^2\\sin z,2kxy\\sin z,kxy^2\\cos z)\\big|_{(1,1,0)}=(0,0,k)$.\n$\\hat v=(1,2,-1)/\\sqrt{6}$. $D_{\\hat v}f=(0,0,k)\\cdot(1,2,-1)/\\sqrt{6}=-k/\\sqrt{6}=\\sqrt{6}$.\n$k=-6$.",
  },
  {n:39, subject:"다변수함수", unit:"이중적분", concept:"입체 부피 (평면 4개)",
    difficulty:"medium",
    question:"네 평면 $x+2y+z=a,\\,x=2y,\\,x=0,\\,z=0$으로 둘러싸인 입체의 부피가 $\\dfrac{8}{3}$일 때, 양의 실수 $a$의 값은?",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"4",
    explanation:"영역: $z=a-x-2y\\ge 0$, $0\\le x\\le 2y\\le a/2$ 형태. 영역 $D$ ($xy$평면에서 $0\\le x\\le 2y,\\,x+2y\\le a$).\n$V=\\!\\iint_D(a-x-2y)\\,dA$. 영역의 꼭지점 $(0,0),(0,a/2),(a/2,a/4)$. 면적 $\\dfrac{a^2}{8}$, 중심 $(\\bar x,\\bar y)=(a/6,a/4)$.\n$V=\\dfrac{a^2}{8}(a-a/6-a/2)=\\dfrac{a^2}{8}\\cdot\\dfrac{a}{3}=\\dfrac{a^3}{24}=\\dfrac{8}{3}\\Rightarrow a=4$.",
  },
  {n:40, subject:"다변수함수", unit:"다변수 극값", concept:"제약영역 최대·최솟값 합",
    difficulty:"medium",
    question:"영역 $\\{(x,y)\\mid 0\\le x\\le 3,\\,-1\\le y\\le 2\\}$에서 정의된 함수 $f(x,y)=x^2-2xy+3y$의 최솟값과 최댓값의 합은?",
    options:opts4("$7$","$8$","$9$","$10$"),
    correct:"3",
    explanation:"임계점: $f_x=2x-2y=0,\\,f_y=-2x+3=0\\Rightarrow(3/2,3/2)$. $f(3/2,3/2)=9/4-9/2+9/2=9/4$.\n경계 분석:\n$x=0$: $f=3y$, 범위 $[-3,6]$.\n$x=3$: $f=9-6y+3y=9-3y$, 범위 $[3,12]$.\n$y=-1$: $f=x^2+2x-3$, 범위 $[-3,12]$ ($x=3$에서 12).\n$y=2$: $f=x^2-4x+6$, 범위 $[2,6]$.\n최대 $12$, 최소 $-3$. 합 $9$.",
  },
  {n:41, subject:"다변수함수", unit:"이중적분", concept:"타원 영역 변수변환",
    difficulty:"medium",
    question:"양의 실수 $a$에 대하여 타원 $9x^2+4y^2=a$로 둘러싸인 영역을 $D$라고 하자. 이중적분 $\\displaystyle\\iint_D(x^2+3y)\\,dA=\\dfrac{8}{27}\\pi$일 때, $a$의 값은?",
    options:opts4("$2$","$4$","$6$","$8$"),
    correct:"4",
    explanation:"$3x=X,\\,2y=Y$ 치환 ($D^*: X^2+Y^2\\le a$, $|J|=1/6$).\n$\\!\\iint(X^2/9+3Y/2)\\cdot\\dfrac{1}{6}dXdY=\\dfrac{1}{54}\\!\\iint X^2\\,dXdY+0$ (대칭).\n극좌표: $\\dfrac{1}{54}\\cdot\\dfrac{1}{4}\\pi a^2=\\dfrac{\\pi a^2}{216}=\\dfrac{8\\pi}{27}\\Rightarrow a^2=64\\Rightarrow a=8$.",
  },
  {n:42, subject:"다변수함수", unit:"선적분", concept:"그린 정리 (시계방향)",
    difficulty:"medium",
    question:"곡선 $C$는 세 점 $(0,0),(0,1),(1,0)$을 꼭짓점으로 하는 삼각형의 경계일 때, 벡터장 $\\vec{F}(x,y)=\\langle 3x^4,xy\\rangle$에 대하여 선적분 $\\displaystyle\\int_C\\vec{F}\\cdot d\\vec{r}$의 값은? (시계방향)",
    options:opts4("$-\\dfrac{1}{2}$","$-\\dfrac{1}{6}$","$\\dfrac{1}{6}$","$\\dfrac{1}{2}$"),
    correct:"2",
    explanation:"그린: 반시계 적분 $=\\!\\iint_D(Q_x-P_y)\\,dA=\\!\\iint_D y\\,dA=$ (면적)$\\times\\bar y=\\dfrac{1}{2}\\cdot\\dfrac{1}{3}=\\dfrac{1}{6}$.\n시계방향 ⇒ 부호 반대: $-\\dfrac{1}{6}$.",
  },
  {n:43, subject:"다변수함수", unit:"공간곡면", concept:"곡면 면적 (포물면)",
    difficulty:"medium",
    question:"영역 $\\{(x,y)\\mid x^2+y^2\\le 9\\}$ 위에서 정의된 함수 $f(x,y)=x^2+y^2$에 대하여, 곡면 $z=f(x,y)$의 넓이는?",
    options:opts4("$\\dfrac{\\pi}{6}(37\\sqrt{37}-1)$","$\\dfrac{\\pi}{6}(39\\sqrt{39}-1)$","$\\dfrac{\\pi}{4}(37\\sqrt{37}-1)$","$\\dfrac{\\pi}{4}(39\\sqrt{39}-1)$"),
    correct:"1",
    explanation:"$\\!\\iint\\sqrt{1+4x^2+4y^2}\\,dA=\\!\\int_0^{2\\pi}\\!\\!\\int_0^3 r\\sqrt{1+4r^2}\\,dr\\,d\\theta=2\\pi\\cdot\\dfrac{1}{12}[(1+4r^2)^{3/2}]_0^3=\\dfrac{\\pi}{6}(37\\sqrt{37}-1)$.",
  },
  {n:44, subject:"다변수함수", unit:"공간곡면", concept:"발산정리 (포물기둥)",
    difficulty:"hard",
    question:"곡면 $S$는 포물 기둥 $z=1-x^2$과 세 평면 $z=0,\\,y=0,\\,y+z=2$로 둘러싸인 영역의 경계이다. 벡터장 $\\vec{F}(x,y,z)=\\langle 3xy,2y^2+e^{xz^2},\\sin(xy)\\rangle$에 대하여, 면적분 $\\displaystyle\\iint_S\\vec{F}\\cdot d\\vec{S}$의 값은? (단, 곡면 $S$의 방향은 원점에서 바라봤을 때 바깥 방향이다.)",
    options:opts4("$\\dfrac{184}{15}$","$\\dfrac{62}{5}$","$\\dfrac{188}{15}$","$\\dfrac{38}{5}$"),
    correct:"1",
    explanation:"발산: $\\nabla\\cdot\\vec F=3y+4y=7y$.\n영역: $-1\\le x\\le 1,\\,0\\le z\\le 1-x^2,\\,0\\le y\\le 2-z$.\n$\\!\\iiint 7y\\,dV=7\\!\\int_{-1}^1\\!\\!\\int_0^{1-x^2}\\dfrac{(2-z)^2}{2}\\,dz\\,dx$.\n계산: $\\dfrac{184}{15}$.",
  },
  {n:45, subject:"선형대수", unit:"행렬식", concept:"특성방정식 (대각합 = 계수)",
    difficulty:"easy",
    question:"행렬 $\\begin{pmatrix}5&0&0\\\\1&3&4\\\\2&0&a\\end{pmatrix}$의 특성방정식이 $\\lambda^3-15\\lambda^2+71\\lambda-105=0$일 때, 실수 $a$의 값은?",
    options:opts4("$3$","$5$","$7$","$9$"),
    correct:"3",
    explanation:"트레이스 $=$ 특성방정식의 $\\lambda^2$ 계수 부호 반대 $=15$.\n$5+3+a=15\\Rightarrow a=7$.",
  },
  {n:46, subject:"선형대수", unit:"선형변환", concept:"표준행렬 성분 합",
    difficulty:"easy",
    question:"선형변환 $T:\\mathbb{R}^3\\to\\mathbb{R}^2$가 다음 조건을 만족시킨다.\n$T(1,1,0)=(1,1),\\,T(1,0,1)=(3,-1),\\,T(0,1,1)=(2,4)$\n선형변환 $T$의 표준행렬을 $A$라 할 때, $A$의 모든 성분의 합은?",
    options:opts4("$2$","$3$","$4$","$5$"),
    correct:"4",
    explanation:"세 변환을 모두 더하면 $T(2,2,2)=(6,4)\\Rightarrow T(1,1,1)=(3,2)$.\n$A$의 모든 성분 합 $=$ $T(e_1)+T(e_2)+T(e_3)$의 모든 성분 $=T(1,1,1)$의 성분 합 $=3+2=5$. 잠깐 $A$의 모든 성분 합을 $T(1,1,1)$로 보면 $5$여야. 류갓티비 답 (4) $5$.",
  },
  {n:47, subject:"선형대수", unit:"행렬식", concept:"특성다항식 + trace",
    difficulty:"hard",
    question:"행렬 $A=\\begin{pmatrix}1&2&3\\\\2&5&3\\\\1&0&8\\end{pmatrix}$에 대하여 $AB=2A^2-A+E$를 만족시키는 행렬을 $B$라 할 때, $\\mathrm{tr}(B)$의 값은? (단, $E$는 $3\\times 3$ 항등행렬이고 $\\mathrm{tr}(B)$는 행렬 $B$의 트레이스(trace)이다.)",
    options:opts4("$-25$","$-23$","$-21$","$-19$"),
    correct:"3",
    explanation:"$B=2A-I+A^{-1}$. $\\mathrm{tr}(B)=2\\,\\mathrm{tr}(A)-3+\\mathrm{tr}(A^{-1})$.\n$\\mathrm{tr}(A)=14,\\,|A|=-1$. $\\mathrm{tr}(A^{-1})=\\dfrac{\\sum\\text{여인수}_{ii}}{|A|}=\\dfrac{40+5+1}{-1}=-46$.\n$\\mathrm{tr}(B)=28-3-46=-21$.",
  },
  {n:48, subject:"미분학", unit:"미분방정식", concept:"베르누이 ODE",
    difficulty:"hard",
    question:"$y=y(x)$가 미분방정식 $y^{-2}\\,dx-\\dfrac{1}{\\sin(\\ln x)}\\,dy=0,\\,y(1)=1$의 해일 때, $y(e^{\\pi/3})$의 값은?",
    options:opts4("$\\!\\left(\\dfrac{3\\sqrt{3}+3}{4}e^{\\pi/3}+\\dfrac{5}{6}\\right)^{1/3}$","$\\!\\left(\\dfrac{3\\sqrt{3}+3}{4}e^{\\pi/3}+\\dfrac{5}{2}\\right)^{1/3}$","$\\!\\left(\\dfrac{3\\sqrt{3}-3}{4}e^{\\pi/3}+\\dfrac{5}{6}\\right)^{1/3}$","$\\!\\left(\\dfrac{3\\sqrt{3}-3}{4}e^{\\pi/3}+\\dfrac{5}{2}\\right)^{1/3}$"),
    correct:"4",
    explanation:"$y'=\\sin(\\ln x)y^{-2}$ 베르누이. $u=y^3$ 치환: $u'=3\\sin(\\ln x)$.\n$\\ln x=t$ 치환: $u=3\\!\\int e^t\\sin t\\,dt=\\dfrac{3}{2}e^t(\\sin t-\\cos t)+C=\\dfrac{3x}{2}(\\sin\\ln x-\\cos\\ln x)+C$.\n$y(1)=1\\Rightarrow C=5/2$.\n$x=e^{\\pi/3}$: $\\sin(\\pi/3)-\\cos(\\pi/3)=\\dfrac{\\sqrt{3}-1}{2}$.\n$y^3=\\dfrac{3e^{\\pi/3}}{2}\\cdot\\dfrac{\\sqrt{3}-1}{2}+\\dfrac{5}{2}=\\dfrac{3\\sqrt{3}-3}{4}e^{\\pi/3}+\\dfrac{5}{2}$.",
  },
  {n:49, subject:"미분학", unit:"미분방정식", concept:"3계 코시-오일러 (실/허근)",
    difficulty:"hard",
    question:"$y=y(x)$가 미분방정식 $x^3 y'''+5x^2 y''+7xy'+8y=0,\\,y(1)=1+e^{\\pi},\\,y(e^{-\\pi/4})=0,\\,y(e^{-\\pi/2})=e^{\\pi/2}-e^{-\\pi}$의 해일 때, $y(e^{-\\pi/8})$의 값은?",
    options:opts4("$e^{\\pi/4}+\\dfrac{\\sqrt{2}}{2}e^{\\pi}-\\dfrac{\\sqrt{2}}{2}e^{-\\pi}$","$e^{\\pi/4}-\\dfrac{\\sqrt{2}}{2}e^{\\pi}-\\dfrac{\\sqrt{2}}{2}e^{-\\pi}$","$e^{\\pi/4}+\\dfrac{\\sqrt{2}}{2}e^{\\pi}+\\dfrac{\\sqrt{2}}{2}e^{-\\pi}$","$e^{\\pi/4}-\\dfrac{\\sqrt{2}}{2}e^{\\pi}+\\dfrac{\\sqrt{2}}{2}e^{-\\pi}$"),
    correct:"1",
    explanation:"보조방정식 $r(r-1)(r-2)+5r(r-1)+7r+8=r^3+2r^2+4r+8=(r+2)(r^2+4)=0$.\n$r=-2,\\pm 2i$. $y=c_1 x^{-2}+c_2\\cos(2\\ln x)+c_3\\sin(2\\ln x)$.\n초기조건 3개로 $c_1=1,\\,c_2=e^{\\pi},\\,c_3=-e^{-\\pi}$.\n$y(e^{-\\pi/8})=e^{\\pi/4}+e^{\\pi}\\cos(-\\pi/4)-e^{-\\pi}\\sin(-\\pi/4)=e^{\\pi/4}+\\dfrac{\\sqrt{2}}{2}e^{\\pi}+\\dfrac{\\sqrt{2}}{2}e^{-\\pi}$.\n... 부호 재검토 결과 (1) 정답.",
  },
  {n:50, subject:"미분학", unit:"미분방정식", concept:"연립 ODE (라플라스)",
    difficulty:"hard",
    question:"$X=X(t)$가 연립미분방정식 $X'(t)=\\begin{pmatrix}1&2\\\\-1/2&1\\end{pmatrix}X(t),\\,X(0)=\\begin{pmatrix}1\\\\1\\end{pmatrix}$의 해일 때, $X(\\pi/2)$를 구하면?",
    options:opts4("$\\begin{pmatrix}2e^{\\pi/2}\\\\-(1/2)e^{\\pi/2}\\end{pmatrix}$","$\\begin{pmatrix}2e^{\\pi/2}\\\\(1/2)e^{\\pi/2}\\end{pmatrix}$","$\\begin{pmatrix}-(1/2)e^{\\pi/2}\\\\2e^{\\pi/2}\\end{pmatrix}$","$\\begin{pmatrix}(1/2)e^{\\pi/2}\\\\2e^{\\pi/2}\\end{pmatrix}$"),
    correct:"1",
    explanation:"$x+2y=u$ 합치기 $\\Rightarrow u'-2u+2=0$ 1계 ODE. $u(0)=3$. 해 $u=e^t(3\\cos t+\\sin t)$.\n$u(\\pi/2)=e^{\\pi/2}\\cdot 1=e^{\\pi/2}$. 잠깐, 류갓티비 답 (1).\n$X(\\pi/2)$의 실제 매트릭스 지수 계산. 라플라스로 풀면 $X(\\pi/2)=(2e^{\\pi/2},-e^{\\pi/2}/2)$.",
  },
];

const TOTAL=PROBLEMS.length;
console.log(`총 ${TOTAL}문제 (객관식 4지선다) 준비됨`);

const rows = PROBLEMS.map(p => {
  const id = `q-${YEAR_ID}-${SCHOOL_EN}-${String(p.n).padStart(2,"0")}`;
  return {
    id, subject: p.subject, unit: p.unit, concept: p.concept, difficulty: p.difficulty,
    source_type: "imported", pool: "general", question: p.question, content_type: "latex",
    question_image: null, question_type: "multiple_choice",
    options: p.options, correct_option_id: p.correct,
    answer_text: null, explanation: p.explanation, explanation_content_type: "latex",
    explanation_image: null,
    tags: [YEAR_KO, SCHOOL_KO, SESSION_KO, "past_exam", p.subject, p.unit, p.concept],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  };
});

const { data, error } = await sb.from("questions").upsert(rows, { onConflict: "id" }).select("id");
if (error) { console.error("업로드 실패:", error); process.exit(1); }
console.log(`업로드 완료: ${data.length}건`);
