// 2023년 단국대 오전 편입수학 객관식 20문항 (4지선다, 문항 번호 31~50)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR_ID="2023am", YEAR_KO="2023", SESSION_KO="오전", SCHOOL_KO="단국대", SCHOOL_EN="dankook";
const opts4 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:31, subject:"미분학", unit:"극한과 연속", concept:"조각함수 극한·불연속",
    difficulty:"medium",
    question:"함수 $f(x)=\\begin{cases}2-x&(x<-1)\\\\x&(-1\\le x<1)\\\\0&(x=1)\\\\(x-1)^2+1&(1<x<2)\\\\e^{-x+2}+1&(x>2)\\end{cases}$이라 하자. $\\displaystyle\\lim_{x\\to a}f(x)$가 존재하지 않는 $a$의 개수를 $A$, 함수 $f(x)$가 $x=b$에서 불연속인 점 $b$의 개수를 $B$라 할 때, $A+B$의 값은?",
    options:opts4("$3$","$4$","$5$","$6$"),
    correct:"2",
    explanation:"$x=-1$: 좌극한 $3$, 우극한 $-1$ ⇒ 극한 X, 불연속.\n$x=1$: 좌·우극한 $1$ 같지만 $f(1)=0$ ⇒ 극한 O, 불연속.\n$x=2$: 좌·우극한 $2$, $f(2)$ 미정의 ⇒ 극한 O, 불연속.\n$A=1$ (극한 없는 점: $x=-1$), $B=3$ (불연속 3점). $A+B=4$.",
  },
  {n:32, subject:"미분학", unit:"도함수", concept:"역함수 미분",
    difficulty:"easy",
    question:"$f(x)=x+e^x$일 때, $f(0)=1$이다. $(f^{-1})'(1)$의 값은?",
    options:opts4("$\\dfrac{1}{4}$","$\\dfrac{1}{3}$","$\\dfrac{1}{2}$","$1$"),
    correct:"3",
    explanation:"$(f^{-1})'(1)=\\dfrac{1}{f'(0)}=\\dfrac{1}{1+e^0}=\\dfrac{1}{2}$.",
  },
  {n:33, subject:"적분학", unit:"이상적분", concept:"가우스 적분 (모멘트)",
    difficulty:"medium",
    question:"$\\displaystyle\\int_{-\\infty}^{\\infty}x^2 e^{-x^2}\\,dx$의 값은?",
    options:opts4("$\\dfrac{\\sqrt{\\pi}}{2}$","$\\dfrac{\\sqrt{2\\pi}}{2}$","$\\sqrt{\\pi}$","$2\\sqrt{\\pi}$"),
    correct:"1",
    explanation:"표준 결과 $\\!\\int_0^{\\infty}x^2 e^{-x^2}\\,dx=\\dfrac{\\sqrt{\\pi}}{4}$.\n대칭이므로 $\\!\\int_{-\\infty}^{\\infty}=2\\cdot\\dfrac{\\sqrt{\\pi}}{4}=\\dfrac{\\sqrt{\\pi}}{2}$.",
  },
  {n:34, subject:"적분학", unit:"정적분의 응용", concept:"곡선 길이",
    difficulty:"medium",
    question:"함수 $f(x)=x^2-\\dfrac{1}{8}\\ln x$의 그래프 위의 두 점 $(1,f(1))$과 $(e^4,f(e^4))$ 사이의 곡선의 길이는?",
    options:opts4("$e^4-\\dfrac{1}{2}$","$e^4+\\dfrac{1}{2}$","$e^8-\\dfrac{1}{2}$","$e^8+\\dfrac{1}{2}$"),
    correct:"3",
    explanation:"$f'(x)=2x-\\dfrac{1}{8x}$. $1+(f')^2=4x^2+\\dfrac{1}{2}+\\dfrac{1}{64x^2}=\\!\\left(2x+\\dfrac{1}{8x}\\right)^2$.\n$L=\\!\\int_1^{e^4}\\!\\left(2x+\\dfrac{1}{8x}\\right)dx=\\!\\left[x^2+\\dfrac{\\ln x}{8}\\right]_1^{e^4}=e^8+\\dfrac{1}{2}-1=e^8-\\dfrac{1}{2}$.",
  },
  {n:35, subject:"적분학", unit:"급수의 수렴/발산", concept:"급수 진위 (3보기)",
    difficulty:"medium",
    question:"다음 중 옳은 것을 있는 대로 모두 고른 것은?\n\n㉠ 급수 $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{1}{n\\sqrt{n^2+3}}$은 수렴한다.\n㉡ 급수 $\\displaystyle\\sum_{n=4}^{\\infty}(-1)^{n+1}\\sin\\dfrac{\\pi}{\\sqrt{n}}$는 발산한다.\n㉢ 멱급수 $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{(-1)^n}{2^n}(x+1)^n$이 수렴하게 되는 정수 $x$의 개수는 $4$이다.",
    options:opts4("㉠","㉠, ㉡","㉠, ㉢","㉡, ㉢"),
    correct:"1",
    explanation:"㉠ [참] $\\sim 1/n^2$ 수렴.\n㉡ [거짓] 교대급수, $\\sin(\\pi/\\sqrt{n})\\to 0$ 단조감소 ⇒ 수렴.\n㉢ [거짓] 수렴반경 $2$, 중심 $-1$, 수렴구간 $|x+1|<2\\Leftrightarrow-3<x<1$. $x=-3,1$ 끝점도 발산. 정수 $x=-2,-1,0$ 3개.",
  },
  {n:36, subject:"다변수함수", unit:"극좌표와 극곡선", concept:"극곡선 접선 기울기",
    difficulty:"medium",
    question:"극 곡선 $r=1+\\sin\\theta$에 대하여 $\\theta=\\dfrac{\\pi}{4}$일 때의 접선의 기울기는?",
    options:opts4("$-1-\\sqrt{2}$","$1-\\sqrt{2}$","$-1+\\sqrt{2}$","$1+\\sqrt{2}$"),
    correct:"1",
    explanation:"$\\tan\\alpha=\\tan(\\theta+\\phi)$, $\\tan\\theta=1$, $\\tan\\phi=r/r'=\\dfrac{1+\\sin\\theta}{\\cos\\theta}\\big|_{\\pi/4}=\\sqrt{2}+1$.\n$\\tan\\alpha=\\dfrac{1+\\sqrt{2}+1}{1-(\\sqrt{2}+1)}=\\dfrac{2+\\sqrt{2}}{-\\sqrt{2}}=-(\\sqrt{2}+1)=-1-\\sqrt{2}$.",
  },
  {n:37, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"두 점 직선과 xy평면 교점",
    difficulty:"medium",
    question:"두 점 $(2,4,-3),\\,(3,-7,-17)$을 지나는 직선이 $xy$ 평면과 만나는 점을 $(a,b,0)$이라 할 때, $4a-b$의 값은? (단, $a,b$는 상수)",
    options:opts4("$-\\dfrac{25}{14}$","$-\\dfrac{11}{14}$","$\\dfrac{11}{14}$","$\\dfrac{25}{14}$"),
    correct:"3",
    explanation:"방향벡터 $(1,-11,-14)$, 점 $(2,4,-3)$. $z=0\\Rightarrow t=-3/-14\\cdot$... 직선 $\\dfrac{x-2}{1}=\\dfrac{y-4}{-11}=\\dfrac{z+3}{-14}$.\n$z=0$: $t=3/14$. $a=2+3/14=31/14$. 잠깐 다시: $\\dfrac{z+3}{-14}=t\\Rightarrow z=-14t-3=0\\Rightarrow t=-3/14$.\n$a=2+(-3/14)=25/14$. $b=4+(-11)(-3/14)=4+33/14=89/14$.\n$4a-b=100/14-89/14=11/14$.",
  },
  {n:38, subject:"다변수함수", unit:"편미분", concept:"방향도함수",
    difficulty:"easy",
    question:"점 $(1,-2,0)$에서 벡터 $\\vec{v}=\\langle 2,1,-2\\rangle$ 방향으로의 함수 $f(x,y,z)=x^2 y-yz^3+z$에 대한 방향도함수의 값은?",
    options:opts4("$-6$","$-5$","$-4$","$-3$"),
    correct:"4",
    explanation:"$\\nabla f=(2xy,\\,x^2-z^3,\\,-3yz^2+1)\\big|_{(1,-2,0)}=(-4,1,1)$.\n단위벡터 $\\hat v=(2/3,1/3,-2/3)$.\n방향도함수 $=\\nabla f\\cdot\\hat v=(-4)(2/3)+(1)(1/3)+(1)(-2/3)=(-8+1-2)/3=-3$.",
  },
  {n:39, subject:"다변수함수", unit:"이중적분", concept:"순서변경 + 자연수 부등식",
    difficulty:"medium",
    question:"연속함수 $f(x)$가 모든 자연수 $n$에 대하여 $\\displaystyle\\int_0^n f(t)\\,dt=\\dfrac{4}{n}$을 만족시킬 때, $\\displaystyle\\int_0^{\\sqrt{n}}\\!\\!\\int_x^{\\sqrt{n}}f(y^2)\\,dy\\,dx>\\dfrac{1}{2}$를 만족시키는 자연수 $n$의 개수는?",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"3",
    explanation:"순서 변경: $\\!\\int_0^{\\sqrt n}\\!\\!\\int_0^y f(y^2)\\,dx\\,dy=\\!\\int_0^{\\sqrt n}y f(y^2)\\,dy$.\n$y^2=t$ 치환: $\\dfrac{1}{2}\\!\\int_0^n f(t)\\,dt=\\dfrac{1}{2}\\cdot\\dfrac{4}{n}=\\dfrac{2}{n}$.\n$\\dfrac{2}{n}>\\dfrac{1}{2}\\Rightarrow n<4$. 자연수 $n=1,2,3$ ⇒ 3개.",
  },
  {n:40, subject:"다변수함수", unit:"다변수 극값", concept:"제약영역 극값/최대·최솟값",
    difficulty:"hard",
    question:"영역 $E$는 네 점 $(1,1),(1,-1),(-1,1),(-1,-1)$을 꼭짓점으로 하는 정사각형의 내부와 경계로 이루어진 영역이다. $E$에서 정의된 이변수함수 $f(x,y)=x^2+y^2-x^2 y+4$에 대한 다음 설명 중 옳은 것의 개수는?\n\n㉠ $f$는 점 $(0,0)$에서 극솟값을 갖는다.\n㉡ $\\nabla f\\!\\left(\\dfrac{1}{2},\\dfrac{1}{2}\\right)=\\vec{0}$\n㉢ $f$의 최댓값은 $7$이다.\n㉣ $f$의 최솟값은 $\\dfrac{13}{4}$이다.",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"2",
    explanation:"임계점: $f_x=2x-2xy=2x(1-y)=0,\\,f_y=2y-x^2=0$. $(0,0)$에서 극소 ($\\Delta>0,\\,f_{xx}>0$). ㉠ [참]\n$\\nabla f(1/2,1/2)=(2\\cdot 1/2(1-1/2),\\,1-1/4)=(1/2,3/4)\\ne\\vec 0$. ㉡ [거짓]\n경계 분석: 최댓값은 $f(\\pm 1,-1)=1+1+1+4=7$. ㉢ [참]\n최솟값: 임계점 $f(0,0)=4$, 경계 최솟값과 비교 ⇒ 4 (계산상). $13/4$ 아님. ㉣ [거짓]\n참 2개: ㉠, ㉢.",
  },
  {n:41, subject:"다변수함수", unit:"이중적분", concept:"평행사변형 영역 변수변환",
    difficulty:"hard",
    question:"네 직선 $y=-2x+4,\\,y=-2x+7,\\,y=x-2,\\,y=x+1$로 둘러싸인 영역을 $D$라 하자. 이중적분 $\\displaystyle\\iint_D(6x^2-3xy-3y^2)e^{3x}\\,dA$의 값은?",
    options:opts4("$6e^9-12e^6-4e^3$","$6e^9+12e^6-4e^3$","$6e^9-9e^6-6e^3$","$6e^9+9e^6-6e^3$"),
    correct:"4",
    explanation:"$2x+y=u,\\,x-y=v$ 치환: $4\\le u\\le 7,\\,-1\\le v\\le 2$. $u+v=3x$, $|J|=1/3$.\n$6x^2-3xy-3y^2=3(2x+y)(x-y)=3uv$. $e^{3x}=e^{u+v}$.\n적분 $=3\\!\\iint uv e^{u+v}\\cdot\\dfrac{1}{3}\\,du\\,dv=\\!\\int_4^7 ue^u du\\cdot\\!\\int_{-1}^2 ve^v dv$\n$=(7e^7-e^7-(4e^4-e^4))\\cdot(2e^2-e^2-(-e^{-1}-e^{-1}))=(6e^7-3e^4)(e^2+2e^{-1})=6e^9+9e^6-6e^3$.",
  },
  {n:42, subject:"다변수함수", unit:"공간곡면", concept:"발산정리 (반구 면적분)",
    difficulty:"hard",
    question:"곡면 $S=\\{(x,y,z)\\mid x^2+y^2+z^2=a^2,\\,z>0\\}$ 위에서 정의된 벡터장 $\\vec{F}(x,y,z)=\\langle x+y,z^2,x^2\\rangle$에 대하여 면적분이 $\\displaystyle\\iint_S\\vec{F}\\cdot d\\vec{S}=\\dfrac{a^2}{12}\\pi$일 때, $\\dfrac{1}{a}-3a$의 값은? (단, $a$는 양의 실수이고 곡면 $S$의 방향은 점 $(0,0,a)$에서 $\\vec{k}=\\langle 0,0,1\\rangle$ 방향)",
    options:opts4("$8$","$10$","$12$","$14$"),
    correct:"1",
    explanation:"발산정리로 닫힌 반구체에서 $\\!\\iiint\\nabla\\cdot\\vec{F}\\,dV=\\!\\iiint 1\\,dV=\\dfrac{2\\pi a^3}{3}$.\n바닥 원판 $S_1$ (하향): $\\!\\iint_{S_1}\\vec{F}\\cdot(0,0,-1)\\,dA=-\\!\\iint x^2\\,dA=-\\dfrac{\\pi a^4}{4}$.\n$S$의 면적분 $=\\dfrac{2\\pi a^3}{3}-\\!\\left(-\\dfrac{\\pi a^4}{4}\\right)=\\dfrac{2\\pi a^3}{3}+\\dfrac{\\pi a^4}{4}$. 잠깐 류갓티비 정리에 따르면 $\\dfrac{2}{3}\\pi a^3+\\dfrac{1}{4}\\pi a^4=\\dfrac{a^2}{12}\\pi$ → $8a+3a^2=1$, $\\dfrac{1}{a}-3a=8$.",
  },
  {n:43, subject:"다변수함수", unit:"선적분", concept:"보존벡터장 + 선적분 기본정리",
    difficulty:"medium",
    question:"곡선 $C_1,C_2$와 $C$는 다음과 같다.\n(1) $C_1$은 시점 $(0,0)$에서 종점 $(\\pi,1)$까지 곡선 $y=\\sin\\dfrac{x}{2}$\n(2) $C_2$는 시점 $(\\pi,1)$에서 종점 $(2\\pi,0)$까지 곡선 $y=\\dfrac{1}{\\pi^2}(x-2\\pi)^2$\n(3) $C=C_1\\cup C_2$\n벡터장 $\\vec{F}(x,y)=\\langle 3+2xy,\\,x^2-3y^2+\\tan y^2\\rangle$에 대하여, 선적분 $\\displaystyle\\int_C\\vec{F}\\cdot d\\vec{r}$의 값은?",
    options:opts4("$-6\\pi$","$-3\\pi$","$3\\pi$","$6\\pi$"),
    correct:"4",
    explanation:"보존성 검증: $P_y=2x=Q_x$ ✓. 포텐셜 $\\phi=3x+x^2 y-y^3+\\!\\int\\tan y^2 dy$.\n$\\!\\int_C\\vec F\\cdot d\\vec r=\\phi(2\\pi,0)-\\phi(0,0)=3\\cdot 2\\pi-0=6\\pi$ (다른 항들 모두 $y=0$에서 0).",
  },
  {n:44, subject:"다변수함수", unit:"공간곡선", concept:"매개·외적·div curl 진위",
    difficulty:"medium",
    question:"다음 중 옳지 $\\textbf{않은}$ 것의 개수는?\n\n㉠ 매개방정식 $\\begin{cases}x=2\\tan\\theta\\\\y=3\\sec\\theta\\end{cases}$ ($-\\pi/2<\\theta<\\pi/2$)은 타원의 일부분을 나타낸다.\n㉡ 곡선 $\\vec{r}(t)$에 대해서 $|\\vec{r}(t)|=1$이면 $\\vec{r}(t)$와 $\\vec{r}'(t)$는 직교한다.\n㉢ $|\\vec{u}\\times\\vec{v}|^2=|\\vec{u}|^2|\\vec{v}|^2-(\\vec{u}\\cdot\\vec{v})^2$\n㉣ $\\mathrm{div}(\\mathrm{curl}\\vec{F})=0$",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"1",
    explanation:"㉠ [거짓] $1+\\tan^2\\theta=\\sec^2\\theta\\Rightarrow 1+x^2/4=y^2/9\\Rightarrow y^2/9-x^2/4=1$ (쌍곡선).\n㉡ [참] $|\\vec r|^2=$상수 ⇒ 미분 시 $\\vec r\\cdot\\vec r'=0$.\n㉢ [참] 라그랑주 항등식.\n㉣ [참] 표준 항등식.\n옳지 않은 것: ㉠ 1개.",
  },
  {n:45, subject:"선형대수", unit:"고유치와 대각화", concept:"고유치 다항식 (행렬식)",
    difficulty:"medium",
    question:"$A=\\begin{pmatrix}a&1&0\\\\-1&b&0\\\\c&2&d\\end{pmatrix}$의 고윳값이 $\\lambda=-1,1,2$일 때, 행렬 $A^2-2I$의 행렬식의 값은? (단, $I$는 단위행렬이고, $a,b,c,d$는 실수)",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"2",
    explanation:"$A^2-2I$의 고윳값 $=\\lambda^2-2=-1,-1,2$.\n행렬식 $=$고윳값 곱 $=(-1)(-1)(2)=2$.",
  },
  {n:46, subject:"선형대수", unit:"선형변환", concept:"기저에 대한 행렬표현",
    difficulty:"hard",
    question:"선형변환 $T:\\mathbb{R}^3\\to\\mathbb{R}^2$가 다음을 만족시킨다.\n$T(\\langle 1,0,0\\rangle)=\\langle 1,3\\rangle,\\,T(\\langle 1,1,0\\rangle)=\\langle 2,2\\rangle,\\,T(\\langle 1,1,2\\rangle)=\\langle 6,10\\rangle$\n$\\mathbb{R}^3$의 기저 $\\beta_1=\\{\\langle 1,0,0\\rangle,\\,\\langle 1,1,0\\rangle,\\,\\langle 1,1,2\\rangle\\}$와 $\\mathbb{R}^2$의 기저 $\\beta_2=\\{\\langle 1,3\\rangle,\\,\\langle 2,2\\rangle\\}$에 대한 선형변환 $T$의 행렬표현은?",
    options:opts4("$\\begin{pmatrix}1&0\\\\0&1\\\\1&3\\end{pmatrix}$","$\\begin{pmatrix}1&0\\\\0&1\\\\2&2\\end{pmatrix}$","$\\begin{pmatrix}1&0&1\\\\0&1&3\\end{pmatrix}$","$\\begin{pmatrix}1&0&2\\\\0&1&2\\end{pmatrix}$"),
    correct:"4",
    explanation:"$T(v_1)=\\langle 1,3\\rangle=1\\cdot\\langle 1,3\\rangle+0\\cdot\\langle 2,2\\rangle$ ⇒ 좌표 $(1,0)^T$.\n$T(v_2)=\\langle 2,2\\rangle=0\\cdot\\langle 1,3\\rangle+1\\cdot\\langle 2,2\\rangle$ ⇒ $(0,1)^T$.\n$T(v_3)=\\langle 6,10\\rangle=2\\cdot\\langle 1,3\\rangle+2\\cdot\\langle 2,2\\rangle$ ⇒ $(2,2)^T$.\n행렬표현 $=\\begin{pmatrix}1&0&2\\\\0&1&2\\end{pmatrix}$.",
  },
  {n:47, subject:"선형대수", unit:"고유치와 대각화", concept:"특성방정식 (행렬 추출)",
    difficulty:"medium",
    question:"$\\begin{pmatrix}1&0&0\\\\2&a^2&4\\\\3&0&2a\\end{pmatrix}$의 특성방정식이 $\\lambda^3-9\\lambda^2+24\\lambda-8a=0$일 때, 실수 $a$의 값은?",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"2",
    explanation:"$\\lambda=1$이 고윳값이므로 특성다항식에 대입: $1-9+24-8a=0\\Rightarrow 8a=16\\Rightarrow a=2$.",
  },
  {n:48, subject:"미분학", unit:"미분방정식", concept:"론스키안 + 1계 선형",
    difficulty:"medium",
    question:"미분가능한 함수 $f(x)$와 $g(x)=x$의 Wronskian이 $W(f,g)(x)=-3x^4$이다. $f(-1)=0$일 때, $f(1)$의 값은?",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"2",
    explanation:"$W=fg'-f'g=f-xf'=-3x^4$. 양변 $x^2$로 나눔: $\\dfrac{f}{x^2}\\cdot$... 또는 $\\dfrac{d}{dx}(f/x)=-(f-xf')/x^2=3x^2$.\n$f/x=x^3+C$. $f=x(x^3+C)=x^4+Cx$. $f(-1)=1-C=0\\Rightarrow C=1$. $f(1)=1+1=2$.",
  },
  {n:49, subject:"미분학", unit:"미분방정식", concept:"코시-오일러 + 매개변수 변동법",
    difficulty:"hard",
    question:"미분방정식 $x^2 y''+xy'+y=\\sec(\\ln x),\\,y(1)=3,\\,y(e^{\\pi/2})=\\dfrac{3}{2}\\pi$의 해를 $f(x)$라 할 때, $\\displaystyle\\sum_{j=1}^{2023}f(e^{2j\\pi})$의 값은?",
    options:opts4("$6069$","$2023\\pi$","$12138$","$4046\\pi$"),
    correct:"1",
    explanation:"$x=e^t$ 치환 → $y''+y=\\sec t$. 동차해 $\\cos t,\\sin t$. 매개변수 변동법: $y_p=\\cos t\\ln(\\cos t)+t\\sin t$.\n원래 변수: $y=c_1\\cos\\ln x+c_2\\sin\\ln x+\\cos\\ln x\\cdot\\ln(\\cos\\ln x)+(\\ln x)\\sin\\ln x$.\n초기조건 ⇒ $c_1=3,\\,c_2=\\pi$.\n$x=e^{2j\\pi}$: $\\cos(2j\\pi)=1,\\,\\sin(2j\\pi)=0$. $f(e^{2j\\pi})=3+0+1\\cdot\\ln 1+2j\\pi\\cdot 0=3$.\n합 $=3\\times 2023=6069$.",
  },
  {n:50, subject:"적분학", unit:"라플라스 변환", concept:"중첩 적분의 라플라스 (컨볼루션)",
    difficulty:"hard",
    question:"함수 $g(t)=\\displaystyle\\int_0^t\\!\\!\\int_0^u e^{-\\tau}\\sinh(2\\tau)\\cos(u-\\tau)\\,d\\tau\\,du$의 라플라스 변환은?",
    options:opts4("$\\dfrac{2}{(s-1)(s+3)(s^2-1)}$","$\\dfrac{2}{(s-1)(s+3)(s^2+1)}$","$\\dfrac{2s}{(s-1)(s+3)(s^2-1)}$","$\\dfrac{2s}{(s-1)(s+3)(s^2+1)}$"),
    correct:"2",
    explanation:"내적분은 컨볼루션 $f*\\cos$ ($f(\\tau)=e^{-\\tau}\\sinh 2\\tau$). $g(t)=\\!\\int_0^t f*\\cos\\,du$.\n$\\mathcal L\\{g\\}=\\dfrac{1}{s}\\mathcal L\\{f*\\cos\\}=\\dfrac{1}{s}\\cdot\\dfrac{s}{s^2+1}\\mathcal L\\{f\\}=\\dfrac{1}{s^2+1}\\mathcal L\\{e^{-t}\\sinh 2t\\}$.\n$\\mathcal L\\{e^{-t}\\sinh 2t\\}=\\dfrac{2}{(s+1)^2-4}=\\dfrac{2}{(s-1)(s+3)}$.\n총 $=\\dfrac{2}{(s-1)(s+3)(s^2+1)}$.",
  },
];

const TOTAL=PROBLEMS.length;
console.log(`총 ${TOTAL}문제 (객관식 4지선다) 준비됨`);

const rows = PROBLEMS.map(p => {
  const id = `q-${YEAR_ID}-${SCHOOL_EN}-${String(p.n).padStart(2,"0")}`;
  return {
    id, subject: p.subject, unit: p.unit, concept: p.concept, difficulty: p.difficulty,
    source_type: "imported", pool: "general", question: p.question, content_type: "latex",
    question_image: null, question_type: "multiple_choice",
    options: p.options, correct_option_id: p.correct,
    answer_text: null, explanation: p.explanation, explanation_content_type: "latex",
    explanation_image: null,
    tags: [YEAR_KO, SCHOOL_KO, SESSION_KO, "past_exam", p.subject, p.unit, p.concept],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  };
});

const { data, error } = await sb.from("questions").upsert(rows, { onConflict: "id" }).select("id");
if (error) { console.error("업로드 실패:", error); process.exit(1); }
console.log(`업로드 완료: ${data.length}건`);
