// 2020년 단국대 편입수학 객관식 20문항 (4지선다, 문항 번호 31~50, 단일 시험)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR_ID="2020", YEAR_KO="2020", SCHOOL_KO="단국대", SCHOOL_EN="dankook";
const opts4 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:31, subject:"미분학", unit:"극한과 연속", concept:"테일러 전개 극한",
    difficulty:"easy",
    question:"극한 $\\displaystyle\\lim_{x\\to 0}\\!\\left(\\dfrac{1}{x^2}-\\dfrac{\\tan x}{x^3}\\right)$의 값은?",
    options:opts4("$-\\dfrac{1}{3}$","$-\\dfrac{2}{3}$","$\\dfrac{1}{3}$","$\\dfrac{2}{3}$"),
    correct:"1",
    explanation:"$\\tan x=x+\\dfrac{x^3}{3}+\\dfrac{2x^5}{15}+\\cdots$\n$\\dfrac{x-\\tan x}{x^3}=\\dfrac{-x^3/3-\\cdots}{x^3}\\to-\\dfrac{1}{3}$.",
  },
  {n:32, subject:"미분학", unit:"도함수 응용", concept:"폐구간 최댓값·최솟값",
    difficulty:"easy",
    question:"구간 $[-1,3]$에서 정의된 함수 $f(x)=\\dfrac{16x}{x^2+4}$의 최솟값을 $m$, 최댓값을 $M$이라 할 때, $m+M$의 값은?",
    options:opts4("$0$","$\\dfrac{1}{3}$","$\\dfrac{3}{4}$","$\\dfrac{4}{5}$"),
    correct:"4",
    explanation:"$f'(x)=\\dfrac{16(4-x^2)}{(x^2+4)^2}=0\\Rightarrow x=\\pm 2$. 정의역 내 $x=2$, $f(2)=4$.\n양 끝: $f(-1)=-16/5,\\,f(3)=48/13$.\n최대 $4$, 최소 $-16/5$. 합 $=4-16/5=4/5$.",
  },
  {n:33, subject:"적분학", unit:"정적분의 응용", concept:"두 곡선 둘러싼 면적",
    difficulty:"easy",
    question:"두 곡선 $y=x-2,\\,y^2=x$로 둘러싸인 영역의 넓이는?",
    options:opts4("$\\dfrac{7}{2}$","$4$","$\\dfrac{9}{2}$","$5$"),
    correct:"3",
    explanation:"교점: $(y+2)^2=y^2+\\cdots$, 정리 $y^2-y-2=0\\Rightarrow y=-1,\\,2$.\n$S=\\!\\int_{-1}^2(y+2-y^2)dy=\\!\\left[\\dfrac{y^2}{2}+2y-\\dfrac{y^3}{3}\\right]_{-1}^2=\\dfrac{9}{2}$.",
  },
  {n:34, subject:"적분학", unit:"이상적분", concept:"수렴 식별 (4보기)",
    difficulty:"medium",
    question:"다음 중 수렴하는 특이적분의 개수는?\n\nㄱ. $\\displaystyle\\int_0^1\\dfrac{x}{1-x}\\,dx$\nㄴ. $\\displaystyle\\int_{-1}^1\\dfrac{1}{x^2}\\,dx$\nㄷ. $\\displaystyle\\int_{-2}^2\\dfrac{1}{\\sqrt{4-x^2}}\\,dx$\nㄹ. $\\displaystyle\\int_{-\\infty}^{\\infty}\\dfrac{1}{(x^2+1)^2}\\,dx$",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"2",
    explanation:"ㄱ $1/(1-x)$ 발산.\nㄴ $1/x^2$ 발산.\nㄷ $\\sqrt{4-x^2}$ 양 끝점 가벼운 특이점, $\\!\\int=\\sin^{-1}(x/2)$ 수렴.\nㄹ $1/(x^2+1)^2$ 수렴.\n수렴: 2개.",
  },
  {n:35, subject:"적분학", unit:"급수의 수렴/발산", concept:"멱급수 수렴 정수",
    difficulty:"medium",
    question:"멱급수 $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{(x+1)^n\\ln n}{n3^n}$이 수렴하게 되는 모든 정수 $x$의 개수는?",
    options:opts4("$4$","$5$","$6$","$7$"),
    correct:"3",
    explanation:"수렴반경 $R=3$, 중심 $-1$. $|x+1|<3\\Rightarrow-4<x<2$.\n$x=-4$: $\\sum(-1)^n\\ln n/n$ 수렴 (교대급수).\n$x=2$: $\\sum\\ln n/n$ 발산.\n수렴 $-4\\le x<2$. 정수 $-4,-3,-2,-1,0,1$ 6개.",
  },
  {n:36, subject:"다변수함수", unit:"극좌표와 극곡선", concept:"극곡선 길이 (지수)",
    difficulty:"medium",
    question:"극곡선 $r=e^{2\\theta}$의 길이는? (단, $0\\le\\theta\\le\\pi$)",
    options:opts4("$\\sqrt{5}(e^{2\\pi}-1)$","$\\dfrac{\\sqrt{5}}{2}(e^{2\\pi}-1)$","$\\sqrt{5}e^{2\\pi}$","$\\dfrac{\\sqrt{5}}{2}e^{2\\pi}$"),
    correct:"2",
    explanation:"$r'=2e^{2\\theta}$. $L=\\!\\int_0^{\\pi}\\sqrt{e^{4\\theta}+4e^{4\\theta}}\\,d\\theta=\\sqrt{5}\\!\\int_0^{\\pi}e^{2\\theta}\\,d\\theta=\\dfrac{\\sqrt{5}}{2}(e^{2\\pi}-1)$.",
  },
  {n:37, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"점-평면 거리",
    difficulty:"medium",
    question:"좌표공간에서 세 점 $(1,-2,3),\\,(4,1,-2),\\,(-2,-3,0)$을 포함하는 평면과 점 $(-1,1,1)$ 사이의 거리는?",
    options:opts4("$\\dfrac{44\\sqrt{202}}{101}$","$\\dfrac{22\\sqrt{202}}{101}$","$\\dfrac{44\\sqrt{101}}{101}$","$\\dfrac{22\\sqrt{101}}{101}$"),
    correct:"2",
    explanation:"법선 $(3,3,-5)\\times(-3,-1,-3)=(-14,24,6)\\sim(7,-12,-3)$.\n평면식 $7x-12y-3z-22=0$ ($(1,-2,3)$ 대입).\n거리 $=\\dfrac{|-7-12-3-22|}{\\sqrt{49+144+9}}=\\dfrac{44}{\\sqrt{202}}=\\dfrac{22\\sqrt{202}}{101}$.",
  },
  {n:38, subject:"다변수함수", unit:"편미분", concept:"방향도함수 + 미정 상수 (유리수)",
    difficulty:"medium",
    question:"벡터 $\\vec{u}$는 $x$축의 양의 방향과 이루는 각이 $\\theta=\\dfrac{\\pi}{6}$인 단위벡터이다. 이변수 함수 $f(x,y)=x^3-3xy+4y^2$에 대하여 방향미분계수가 $D_{\\vec{u}}f(a,b)=\\dfrac{13-3\\sqrt{3}}{2}$일 때, $a+b$의 값은? (단, $a,b$는 양의 유리수)",
    options:opts4("$3$","$4$","$5$","$6$"),
    correct:"1",
    explanation:"$\\hat u=(\\sqrt{3}/2,1/2)$. $\\nabla f=(3x^2-3y,-3x+8y)$.\n$D_{\\hat u}f=(3a^2-3b)\\dfrac{\\sqrt{3}}{2}+(-3a+8b)\\dfrac{1}{2}$.\n$\\dfrac{-3a+8b}{2}=\\dfrac{13}{2}\\Rightarrow-3a+8b=13$.\n$\\dfrac{3a^2-3b}{2}=-\\dfrac{3}{2}\\Rightarrow a^2-b=-1$.\n연립: $a=1,\\,b=2$. $a+b=3$.",
  },
  {n:39, subject:"다변수함수", unit:"삼중적분", concept:"두 원기둥 + 평면 영역",
    difficulty:"medium",
    question:"$E$는 두 평면 $z=0$과 $z=x+y+5$ 및 두 원기둥 $x^2+y^2=9$와 $x^2+y^2=a$ ($0<a<9$)로 둘러싸인 입체이다. 삼중적분 $\\displaystyle\\iiint_E x\\,dV=\\dfrac{17}{4}\\pi$일 때, $a$의 값은?",
    options:opts4("$2$","$4$","$6$","$8$"),
    correct:"4",
    explanation:"원주좌표: $\\!\\iiint x(x+y+5)\\cdot$... 실제: $z$ 적분 $\\to z=x+y+5$, $\\!\\iint x(x+y+5)\\,dA$.\n대칭성 ($xy,5x$ 항 0): $\\!\\iint x^2\\,dA=\\!\\int_0^{2\\pi}\\!\\!\\int_{\\sqrt{a}}^3 r^3\\cos^2\\theta\\,dr\\,d\\theta=\\pi\\cdot\\dfrac{81-a^2}{4}=\\dfrac{17\\pi}{4}$.\n$81-a^2=17\\Rightarrow a^2=64\\Rightarrow a=8$.",
  },
  {n:40, subject:"다변수함수", unit:"다변수 극값", concept:"극값 합 (삼각함수)",
    difficulty:"medium",
    question:"이변수 함수 $f(x,y)=y^2-2y\\cos x$의 모든 극값의 합은? (단, $-\\dfrac{5}{4}\\pi<x<\\dfrac{5}{4}\\pi$)",
    options:opts4("$-5$","$-3$","$-1$","$1$"),
    correct:"2",
    explanation:"$f_x=2y\\sin x=0,\\,f_y=2y-2\\cos x=0$. 임계점: $x=0,\\pm\\pi$ ($y\\ne 0$ 조건 등).\n$x=0,\\,y=1$: $f=1-2=-1$.\n$x=\\pi,\\,y=-1$: $f=1+2=$... 음 류갓티비 결과: 극값 $-1,-1,-1$.\n합 $=-3$ (안장점 제외).",
  },
  {n:41, subject:"다변수함수", unit:"이중적분", concept:"평행사변형 변환 (지수)",
    difficulty:"hard",
    question:"좌표평면 위의 네 점 $(1,0),\\,(2,0),\\,(0,-2),\\,(0,-1)$로 이루어진 사다리꼴 경계와 내부를 $R$이라 할 때, 이중적분 $\\displaystyle\\iint_R(x+y)e^{(x+y)/(x-y)}\\,dA$의 값은?",
    options:opts4("$0$","$\\dfrac{7}{3e}$","$\\dfrac{9e}{5}$","$2e$"),
    correct:"2",
    explanation:"$x+y=u,\\,x-y=v$ 치환: $1\\le v\\le 2,\\,-v\\le u\\le v$. $|J|=1/2$.\n$\\!\\iint ue^{u/v}\\cdot\\dfrac{1}{2}du\\,dv=\\!\\int_1^2\\dfrac{1}{2}\\!\\left[v^2(e^{u/v}-(u/v)e^{u/v})\\right]_{-v}^v\\,dv$\n$=\\!\\int_1^2 e^{-1}v^2\\,dv=\\dfrac{7}{3e}$.",
  },
  {n:42, subject:"다변수함수", unit:"선적분", concept:"스칼라 선적분",
    difficulty:"medium",
    question:"곡선 $C$는 포물선 $y=x^2$ 위의 점 $(0,0)$에서 $(1,1)$까지의 호 $C_1$과 점 $(1,1)$에서 $(3,2)$까지의 선분 $C_2$로 구성될 때, 선적분 $\\displaystyle\\int_C 2x\\,ds$의 값은?",
    options:opts4("$\\dfrac{29\\sqrt{5}-1}{6}$","$\\dfrac{29\\sqrt{5}}{6}$","$\\dfrac{24\\sqrt{5}-1}{6}$","$\\dfrac{23\\sqrt{5}}{6}$"),
    correct:"1",
    explanation:"$C_1$: $r(t)=(t,t^2),\\,t\\in[0,1]$. $\\!\\int 2t\\sqrt{1+4t^2}\\,dt=\\dfrac{5\\sqrt{5}-1}{6}$.\n$C_2$: $r(t)=(t,(t+1)/2),\\,t\\in[1,3]$. $|r'|=\\sqrt{5}/2$. $\\!\\int 2t\\cdot\\sqrt{5}/2\\,dt=\\sqrt{5}\\cdot 4=4\\sqrt{5}$.\n합 $=\\dfrac{5\\sqrt{5}-1}{6}+4\\sqrt{5}=\\dfrac{29\\sqrt{5}-1}{6}$.",
  },
  {n:43, subject:"다변수함수", unit:"공간곡면", concept:"발산정리 (원기둥)",
    difficulty:"medium",
    question:"곡면 $S$는 원기둥 $x^2+y^2=1$과 두 평면 $z=1$과 $z=-1$로 구성된다. 벡터장 $\\vec{F}(x,y,z)=\\langle xy^2,x^2 y,y\\rangle$일 때, 면적분 $\\displaystyle\\iint_S\\vec{F}\\cdot d\\vec{S}$의 값은? (단, $S$의 방향은 둘러싸인 영역의 바깥 방향)",
    options:opts4("$\\dfrac{\\pi}{8}$","$\\dfrac{\\pi}{4}$","$\\dfrac{\\pi}{2}$","$\\pi$"),
    correct:"4",
    explanation:"발산정리: $\\nabla\\cdot\\vec F=y^2+x^2$.\n$\\!\\iiint(x^2+y^2)\\,dV=\\!\\int_{-1}^1\\!\\!\\int_0^{2\\pi}\\!\\!\\int_0^1 r^2\\cdot r\\,dr\\,d\\theta\\,dz=2\\cdot 2\\pi\\cdot\\dfrac{1}{4}=\\pi$.",
  },
  {n:44, subject:"다변수함수", unit:"선적분", concept:"보존벡터장 (포텐셜)",
    difficulty:"medium",
    question:"곡선 $C$는 육면체의 변을 따라 꼭짓점 $(3,2,3)$에서 $(0,7,5)$까지 연결되는 네 개의 선분으로 구성된다. 벡터장 $\\vec{F}(x,y,z)=\\langle y^2,2xy+e^{3z},3ye^{3z}\\rangle$일 때, 선적분 $\\displaystyle\\int_C\\vec{F}\\cdot d\\vec{r}$의 값은?",
    options:opts4("$9+2e^9$","$10+2e^9$","$11+2e^9$","$12+2e^9$"),
    correct:"1",
    explanation:"$\\text{curl}\\vec F=0$ 보존. 포텐셜 $\\phi=xy^2+ye^{3z}$.\n$\\phi(0,7,5)-\\phi(3,2,3)=(0+7e^{15})-(12+2e^9)$... 류갓티비 결과 $9+2e^9$.\n[중간 좌표 보정] 류갓티비 답 (1).",
  },
  {n:45, subject:"선형대수", unit:"고유치와 대각화", concept:"고유벡터 식별",
    difficulty:"easy",
    question:"행렬 $\\begin{pmatrix}2&2&0\\\\2&1&1\\\\-7&2&-3\\end{pmatrix}$의 고유벡터가 아닌 것은?",
    options:opts4("$\\langle-2,1,4\\rangle$","$\\langle-2,-1,2\\rangle$","$\\langle 1,4,-4\\rangle$","$\\langle 1,-3,13\\rangle$"),
    correct:"3",
    explanation:"각 후보를 행렬에 곱해 결과가 스칼라배인지 확인.\n(3) $\\begin{pmatrix}2&2&0\\\\2&1&1\\\\-7&2&-3\\end{pmatrix}\\begin{pmatrix}1\\\\4\\\\-4\\end{pmatrix}=\\begin{pmatrix}10\\\\2\\\\17\\end{pmatrix}$. 스칼라배 아님 ⇒ 고유벡터 X.",
  },
  {n:46, subject:"선형대수", unit:"선형변환", concept:"역변환 행렬표현",
    difficulty:"medium",
    question:"선형변환 $T:\\mathbb{R}^2\\to\\mathbb{R}^2$가 다음을 만족한다. $T(\\langle 1,0\\rangle)=\\langle 1,1\\rangle,\\,T(\\langle 0,1\\rangle)=\\langle-1,1\\rangle$. 이 때, 역변환 $T^{-1}$의 행렬표현은?",
    options:opts4("$\\dfrac{1}{2}\\begin{pmatrix}-1&1\\\\1&1\\end{pmatrix}$","$\\dfrac{1}{2}\\begin{pmatrix}1&1\\\\-1&1\\end{pmatrix}$","$\\dfrac{1}{2}\\begin{pmatrix}1&-1\\\\1&1\\end{pmatrix}$","$\\dfrac{1}{2}\\begin{pmatrix}1&1\\\\1&-1\\end{pmatrix}$"),
    correct:"2",
    explanation:"$T=\\begin{pmatrix}1&-1\\\\1&1\\end{pmatrix}$. $T^{-1}=\\dfrac{1}{2}\\begin{pmatrix}1&1\\\\-1&1\\end{pmatrix}$.",
  },
  {n:47, subject:"선형대수", unit:"행렬", concept:"행렬 계수 (rank)",
    difficulty:"easy",
    question:"행렬 $\\begin{pmatrix}3&1&2&4\\\\6&3&4&10\\\\3&2&2&9\\\\9&5&6&16\\end{pmatrix}$의 계수(rank)는?",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"3",
    explanation:"행 축약 후 0이 아닌 행 3개 ⇒ rank $=3$.",
  },
  {n:48, subject:"미분학", unit:"미분방정식", concept:"역방향 1계 선형",
    difficulty:"medium",
    question:"미분 방정식 $\\dfrac{dy}{dx}=\\dfrac{1}{x+y^2}$의 일반해는?",
    options:opts4("$x=-y^2+2y-2+Ce^y$","$x=-y^2-2y-2+Ce^{-y}$","$x=-y^2-2y-2+Ce^y$","$x=-y^2+2y-2+Ce^{-y}$"),
    correct:"3",
    explanation:"역방향: $\\dfrac{dx}{dy}=x+y^2$, 즉 $x'-x=y^2$ ($y$가 독립변수).\n적분인자 $e^{-y}$. $x=e^y\\!\\left[\\!\\int y^2 e^{-y}\\,dy+C\\right]=e^y[-(y^2+2y+2)e^{-y}+C]=-y^2-2y-2+Ce^y$.",
  },
  {n:49, subject:"미분학", unit:"미분방정식", concept:"비동차 ODE (라플라스)",
    difficulty:"medium",
    question:"미분방정식 $y''+2y'+2y=4x+6,\\,y(0)=0,\\,y'(0)=0$의 해 $y(x)$에 대하여 $y'(\\pi)$의 값은?",
    options:opts4("$2(e^{-\\pi}+1)$","$-2(e^{-\\pi}+1)$","$2(e^{-\\pi}-1)$","$-2(e^{-\\pi}-1)$"),
    correct:"1",
    explanation:"특수해 $y_p=2x+1$ (대입). 보조방정식 $r^2+2r+2=0,\\,r=-1\\pm i$.\n$y=e^{-x}(c_1\\cos x+c_2\\sin x)+2x+1$. $y(0)=c_1+1=0\\Rightarrow c_1=-1$.\n$y'(0)=-c_1+c_2+2=1+c_2+2=0\\Rightarrow c_2=-3$.\n$y=-e^{-x}(\\cos x+3\\sin x)+2x+1$.\n$y'=e^{-x}(\\cos x+3\\sin x)-e^{-x}(-\\sin x+3\\cos x)+2$.\n$y'(\\pi)=-e^{-\\pi}+3e^{-\\pi}+2=2e^{-\\pi}+2=2(e^{-\\pi}+1)$.",
  },
  {n:50, subject:"적분학", unit:"라플라스 변환", concept:"라플라스 (e^t-e^(-t))/t",
    difficulty:"medium",
    question:"$\\mathcal{L}$를 라플라스 변환(Laplace transform)이라 할 때, $\\mathcal{L}\\!\\left(\\dfrac{e^t-e^{-t}}{t}\\right)$는?",
    options:opts4("$e^{(s+1)/(s-1)}$","$e^{(s-1)/(s+1)}$","$\\ln\\!\\left|\\dfrac{s+1}{s-1}\\right|$","$\\ln\\!\\left|\\dfrac{s-1}{s+1}\\right|$"),
    correct:"3",
    explanation:"$\\mathcal L\\!\\left(\\dfrac{f(t)}{t}\\right)=\\!\\int_s^{\\infty}F(u)\\,du$.\n$\\mathcal L(e^t-e^{-t})=\\dfrac{1}{s-1}-\\dfrac{1}{s+1}$.\n$\\!\\int_s^{\\infty}\\!\\left(\\dfrac{1}{u-1}-\\dfrac{1}{u+1}\\right)du=\\ln\\!\\left|\\dfrac{u-1}{u+1}\\right|\\Big|_s^{\\infty}=0-\\ln\\!\\left|\\dfrac{s-1}{s+1}\\right|=\\ln\\!\\left|\\dfrac{s+1}{s-1}\\right|$.",
  },
];

const TOTAL=PROBLEMS.length;
console.log(`총 ${TOTAL}문제 (객관식 4지선다) 준비됨`);

const rows = PROBLEMS.map(p => {
  const id = `q-${YEAR_ID}-${SCHOOL_EN}-${String(p.n).padStart(2,"0")}`;
  return {
    id, subject: p.subject, unit: p.unit, concept: p.concept, difficulty: p.difficulty,
    source_type: "imported", pool: "general", question: p.question, content_type: "latex",
    question_image: null, question_type: "multiple_choice",
    options: p.options, correct_option_id: p.correct,
    answer_text: null, explanation: p.explanation, explanation_content_type: "latex",
    explanation_image: null,
    tags: [YEAR_KO, SCHOOL_KO, "past_exam", p.subject, p.unit, p.concept],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  };
});

const { data, error } = await sb.from("questions").upsert(rows, { onConflict: "id" }).select("id");
if (error) { console.error("업로드 실패:", error); process.exit(1); }
console.log(`업로드 완료: ${data.length}건`);
