// 2023년 단국대 오후 편입수학 객관식 20문항 (4지선다, 문항 번호 31~50)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR_ID="2023pm", YEAR_KO="2023", SESSION_KO="오후", SCHOOL_KO="단국대", SCHOOL_EN="dankook";
const opts4 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:31, subject:"미분학", unit:"도함수 응용", concept:"접선 기울기 최솟값",
    difficulty:"easy",
    question:"함수 $f(x)=2x^3-18x^2+60x+2$에 대하여 곡선 $y=f(x)$에 접하는 직선의 기울기는 $x=a$일 때 최솟값을 갖고, 그 최솟값은 $b$이다. $a+b$의 값은?",
    options:opts4("$3$","$6$","$9$","$12$"),
    correct:"3",
    explanation:"접선의 기울기 $f'(x)=6x^2-36x+60=6(x-3)^2+6$.\n$x=3$에서 최솟값 $6$. $a=3,\\,b=6$. $a+b=9$.",
  },
  {n:32, subject:"미분학", unit:"도함수", concept:"역함수 미분 + 합",
    difficulty:"medium",
    question:"미분가능한 함수 $f(x)$가 다음 조건을 만족시킨다.\n\n(가) $f(x)$의 역함수가 존재한다.\n(나) 모든 자연수 $k$에 대하여 곡선 $y=f(x)$는 점 $(k,k)$에서 직선 $y=x$에 접한다.\n\n$g(x)=f(x)f^{-1}(x)$라 할 때, $\\displaystyle\\sum_{k=1}^n g'(k)=12$이다. 자연수 $n$의 값은?",
    options:opts4("$1$","$3$","$6$","$12$"),
    correct:"2",
    explanation:"$f(k)=k,\\,f'(k)=1$. $f^{-1}(k)=k,\\,(f^{-1})'(k)=1$.\n$g'(k)=f'(k)f^{-1}(k)+f(k)(f^{-1})'(k)=k+k=2k$.\n$\\sum_{k=1}^n 2k=n(n+1)=12\\Rightarrow n=3$.",
  },
  {n:33, subject:"적분학", unit:"부정적분", concept:"치환 + 부분적분",
    difficulty:"medium",
    question:"$\\displaystyle\\int_1^{e^2}(1+\\ln x)^2\\,dx$의 값은?",
    options:opts4("$e^2+1$","$e^2-1$","$5e^2+1$","$5e^2-1$"),
    correct:"4",
    explanation:"$1+\\ln x=t$ 치환. $\\ln x=t-1,\\,x=e^{t-1},\\,dx=e^{t-1}dt$.\n구간: $x=1\\Rightarrow t=1,\\,x=e^2\\Rightarrow t=3$.\n$\\!\\int_1^3 t^2 e^{t-1}\\,dt=e^{-1}\\!\\int_1^3 t^2 e^t\\,dt=e^{-1}[t^2 e^t-2te^t+2e^t]_1^3=e^{-1}(5e^3-e)=5e^2-1$.",
  },
  {n:34, subject:"적분학", unit:"정적분의 응용", concept:"곡선 길이",
    difficulty:"medium",
    question:"곡선 $y=\\dfrac{1}{3}(2x-1)^{3/2}$ 위의 두 점 $\\!\\left(\\dfrac{1}{2},0\\right)$과 $\\!\\left(1,\\dfrac{1}{3}\\right)$ 사이의 곡선의 길이는?",
    options:opts4("$\\dfrac{\\sqrt{2}-1}{3}$","$\\dfrac{2\\sqrt{2}-1}{3}$","$\\sqrt{2}-\\dfrac{1}{3}$","$\\dfrac{4\\sqrt{2}-1}{3}$"),
    correct:"2",
    explanation:"$y'=(2x-1)^{1/2}$. $1+(y')^2=1+(2x-1)=2x$.\n$L=\\!\\int_{1/2}^1\\sqrt{2x}\\,dx=\\!\\left[\\dfrac{(2x)^{3/2}}{3}\\right]_{1/2}^1=\\dfrac{2\\sqrt{2}-1}{3}$.",
  },
  {n:35, subject:"적분학", unit:"급수의 수렴/발산", concept:"멱급수 수렴 구간 (자연수 개수)",
    difficulty:"medium",
    question:"다음 중 급수가 수렴하게 되는 자연수 $x$의 개수가 가장 많은 것은?\n\n㉠ $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{(x-3)^n}{n}$\n㉡ $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{n(x+2)^n}{3^{n+1}}$\n㉢ $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{(-3)^n x^n}{\\sqrt{n+1}}$\n㉣ $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{(-2)^n(x-3)^n}{\\sqrt{n}}$",
    options:opts4("㉠","㉡","㉢","㉣"),
    correct:"1",
    explanation:"수렴 구간 자연수 $x$:\n㉠ $|x-3|<1\\Rightarrow 2\\le x<4$. 자연수 $x=2,3$ → 2개.\n㉡ $|x+2|<3\\Rightarrow-5<x<1$. 자연수 없음.\n㉢ $|3x|<1\\Rightarrow|x|<1/3$. 자연수 없음.\n㉣ $|2(x-3)|<1\\Rightarrow 5/2<x\\le 7/2$. 자연수 $x=3$ → 1개.\n가장 많은 것: ㉠ (2개).",
  },
  {n:36, subject:"다변수함수", unit:"극좌표와 극곡선", concept:"파푸스의 정리 (회전체 겉넓이)",
    difficulty:"medium",
    question:"극 곡선 $r=\\sin\\theta$ ($0\\le\\theta\\le\\pi$)를 극축을 회전축으로 하여 회전시켜 얻은 회전체의 겉넓이는?",
    options:opts4("$\\dfrac{\\pi^2}{4}$","$\\dfrac{\\pi^2}{3}$","$\\dfrac{\\pi^2}{2}$","$\\pi^2$"),
    correct:"4",
    explanation:"$r=\\sin\\theta$는 중심 $(0,1/2)$ 반지름 $1/2$인 원.\n파푸스: 겉넓이 $=$ (둘레)×(중심 이동거리) $=\\pi\\times 2\\pi(1/2)=\\pi^2$.",
  },
  {n:37, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"벡터 내적 + 수직 조건",
    difficulty:"medium",
    question:"영이 아닌 벡터 $\\vec{a},\\vec{b}$에 대하여 $k=(2\\vec{a})\\cdot\\vec{b}$라 하자. $\\vec{a}$와 $\\vec{c}=8\\vec{b}-k\\vec{a}$가 수직일 때, 벡터 $\\vec{a}$의 크기 $|\\vec{a}|$의 값은? (단, $\\vec{c}\\ne 8\\vec{b}$)",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"2",
    explanation:"$\\vec{a}\\cdot\\vec{c}=0$: $8\\vec{a}\\cdot\\vec{b}-k|\\vec{a}|^2=0$.\n$k=2\\vec{a}\\cdot\\vec{b}$ 대입: $8\\vec{a}\\cdot\\vec{b}=2(\\vec{a}\\cdot\\vec{b})|\\vec{a}|^2$.\n$\\vec{a}\\cdot\\vec{b}\\ne 0$이므로 $|\\vec{a}|^2=4\\Rightarrow|\\vec{a}|=2$.",
  },
  {n:38, subject:"다변수함수", unit:"편미분", concept:"방향도함수",
    difficulty:"easy",
    question:"점 $(1,3,0)$에서 벡터 $\\vec{v}=\\langle 1,2,-1\\rangle$ 방향으로의 함수 $f(x,y,z)=x\\sin(yz)+\\tan^{-1}(yz)$에 대한 방향도함수의 값은?",
    options:opts4("$-\\sqrt{6}$","$-\\sqrt{3}$","$-\\dfrac{\\sqrt{6}}{2}$","$-\\dfrac{\\sqrt{3}}{2}$"),
    correct:"1",
    explanation:"$f_x=\\sin yz$, $f_y=xz\\cos yz+\\dfrac{z}{1+(yz)^2}$, $f_z=xy\\cos yz+\\dfrac{y}{1+(yz)^2}$.\n$(1,3,0)$ 대입: $\\nabla f=(0,0,3+3)=(0,0,6)$. 잠깐, $f_z|_{(1,3,0)}=1\\cdot 3\\cdot 1+3=6$. $f_x=0,\\,f_y=0$.\n$|\\vec{v}|=\\sqrt{6}$. $D_{\\hat v}f=\\nabla f\\cdot\\hat v=(0,0,6)\\cdot(1,2,-1)/\\sqrt{6}=-6/\\sqrt{6}=-\\sqrt{6}$.",
  },
  {n:39, subject:"다변수함수", unit:"다변수 극값", concept:"제약영역 최솟값",
    difficulty:"medium",
    question:"영역 $D$는 세 점 $(0,0),(3,0),(0,5)$를 꼭짓점으로 하는 삼각형의 내부와 경계이다. 함수 $f:D\\to\\mathbb{R},\\,f(x,y)=3xy-6x-3y+7$의 최솟값은?",
    options:opts4("$-15$","$-11$","$-7$","$-5$"),
    correct:"2",
    explanation:"경계 분석:\n$y=0$: $f=-6x+7$, $x\\in[0,3]$, 최소 $-11$ ($x=3$).\n$x=0$: $f=-3y+7$, $y\\in[0,5]$, 최소 $-8$ ($y=5$).\n빗변 $5x+3y=15$: $f$ 매개변수 분석하면 최소 $-11$ ($x=3$ 끝점에서).\n내부 임계점: $f_x=3y-6=0,\\,f_y=3x-3=0\\Rightarrow(1,2)$, $f(1,2)=1$. 안장점 ($\\Delta=-9<0$).\n최솟값 $-11$.",
  },
  {n:40, subject:"적분학", unit:"이상적분", concept:"특이적분 (대칭)",
    difficulty:"easy",
    question:"$\\displaystyle\\int_0^2\\dfrac{1}{\\sqrt{|x-1|}}\\,dx$의 값은?",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"4",
    explanation:"$x-1\\to t$ 치환: $\\!\\int_{-1}^1\\dfrac{dt}{\\sqrt{|t|}}=2\\!\\int_0^1\\dfrac{dt}{\\sqrt{t}}=2[2\\sqrt{t}]_0^1=4$.",
  },
  {n:41, subject:"다변수함수", unit:"이중적분", concept:"적분 순서 변경",
    difficulty:"medium",
    question:"두 직선 $y=x,\\,x=\\pi$와 $x$축으로 둘러싸인 영역을 $D$라 할 때, 이중적분 $\\displaystyle\\iint_D\\dfrac{\\sin x}{x}\\,dA$의 값은?",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"2",
    explanation:"$\\!\\int_0^{\\pi}\\!\\!\\int_0^x\\dfrac{\\sin x}{x}\\,dy\\,dx=\\!\\int_0^{\\pi}\\sin x\\,dx=2$.",
  },
  {n:42, subject:"다변수함수", unit:"선적분", concept:"보존벡터장 (포텐셜)",
    difficulty:"medium",
    question:"곡선 $C$는 점 $A(0,\\pi/2,e^{18})$로부터 점 $B(2a,\\pi,3e^{18})$까지 그림과 같은 경로이다. 벡터장 $\\vec{F}(x,y,z)=\\langle ae^{ax}\\cos y,\\,-e^{ax}\\sin y,\\,1\\rangle$에 대하여 선적분이 $\\displaystyle\\int_C\\vec{F}\\cdot d\\vec{r}=e^{18}$일 때 양의 실수 $a$의 값은?",
    options:opts4("$\\sqrt{3}$","$3$","$3\\sqrt{3}$","$9$"),
    correct:"2",
    explanation:"$\\text{curl}\\vec{F}=0$ 보존. 포텐셜 $\\phi=e^{ax}\\cos y+z$.\n$\\!\\int_C\\vec F\\cdot d\\vec r=\\phi(B)-\\phi(A)=[e^{2a^2}\\cos\\pi+3e^{18}]-[e^0\\cos(\\pi/2)+e^{18}]=-e^{2a^2}+2e^{18}=e^{18}$.\n$e^{2a^2}=e^{18}\\Rightarrow 2a^2=18\\Rightarrow a=3$.",
  },
  {n:43, subject:"다변수함수", unit:"공간곡면", concept:"가우스 발산정리 (토러스)",
    difficulty:"medium",
    question:"그림과 같은 토러스(torus) $S$와 벡터장 $\\vec{F}(x,y,z)=\\langle y^2,\\,x+y,\\,z+e^y\\rangle$에 대하여 면적분이 $\\displaystyle\\iint_S\\vec{F}\\cdot d\\vec{S}=2$일 때, 토러스 내부의 부피는?",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"1",
    explanation:"발산정리: $\\!\\iiint_T\\nabla\\cdot\\vec{F}\\,dV=\\!\\iiint_T(0+1+1)\\,dV=2V=2$.\n$V=1$.",
  },
  {n:44, subject:"다변수함수", unit:"선적분", concept:"스칼라 선적분",
    difficulty:"easy",
    question:"두 점 $(0,0,0)$과 $(1,2,2)$를 양 끝점으로 하는 선분 $L$에 대하여 선적분 $\\displaystyle\\int_L xyz\\,ds$의 값은?",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"3",
    explanation:"매개변수화 $r(t)=(t,2t,2t),\\,0\\le t\\le 1$. $|r'|=\\sqrt{1+4+4}=3$.\n$\\!\\int_0^1 t\\cdot 2t\\cdot 2t\\cdot 3\\,dt=12\\!\\int_0^1 t^3\\,dt=12\\cdot\\dfrac{1}{4}=3$.",
  },
  {n:45, subject:"선형대수", unit:"고유치와 대각화", concept:"닮은행렬 고유다항식",
    difficulty:"medium",
    question:"행렬 $A=\\begin{pmatrix}0&0&-2\\\\1&a&1\\\\1&0&3\\end{pmatrix}$와 가역행렬 $P$에 대하여 $P^{-1}AP=\\begin{pmatrix}2&0&0\\\\0&b&0\\\\0&0&2\\end{pmatrix}$일 때, $a-b$의 값은? (단, $a,b$는 실수)",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"1",
    explanation:"닮은 행렬은 고유다항식 동일.\n$A$의 특성 $\\lambda^3-(a+3)\\lambda^2+(3a+2)\\lambda-2a=0$.\n$B$의 특성 $(\\lambda-2)^2(\\lambda-b)=0\\Rightarrow\\lambda^3-(4+b)\\lambda^2+(4b+4)\\lambda-4b=0$.\n계수비교: $a+3=4+b,\\,3a+2=4b+4,\\,2a=4b\\Rightarrow a=2b$. $a=2,\\,b=1$. $a-b=1$.",
  },
  {n:46, subject:"선형대수", unit:"선형변환", concept:"기저 + 핵 + 내적",
    difficulty:"hard",
    question:"벡터공간 $V$의 기저 $\\{\\vec{e_1},\\vec{e_2},\\vec{e_3}\\}$에 대하여 선형변환 $T:V\\to V$가 다음 조건을 만족시킨다.\n\n(가) $T$의 핵(kernel)은 2차원\n(나) $T(\\vec{e_1})=2\\vec{e_2}$\n(다) $\\vec{e_2}\\cdot T(\\vec{e_1})=\\vec{e_2}\\cdot T(\\vec{e_i}),\\,i=2,3$\n\n$T(\\vec{e_1}+2\\vec{e_2}-\\vec{e_3})=a\\vec{e_1}+b\\vec{e_2}+c\\vec{e_3}$일 때, $a+b-c$의 값은? (단, $a,b,c$는 실수이고, $\\vec{u}\\cdot\\vec{v}$는 $\\vec u$와 $\\vec v$의 내적이다.)",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"4",
    explanation:"$T(e_1)=(0,2,0)$. 핵 2차원 ⇒ rank 1, 상공간 1차원, 기저 $\\{(0,1,0)\\}$.\n$T(e_2),T(e_3)$의 $e_2$ 성분이 모두 2이므로 $T(e_2)=(0,2,0),\\,T(e_3)=(0,2,0)$.\n$T(e_1+2e_2-e_3)=(0,2,0)+2(0,2,0)-(0,2,0)=(0,4,0)$. $a=0,b=4,c=0$.\n$a+b-c=4$.",
  },
  {n:47, subject:"선형대수", unit:"행렬식", concept:"역행렬 행렬식 + 스칼라곱",
    difficulty:"medium",
    question:"행렬 $A=\\begin{pmatrix}1&-2&-2\\\\-2&5&1\\\\3&-4&-3\\end{pmatrix}$의 역행렬 $A^{-1}$에 대하여 $2A^{-1}$의 행렬식의 값은?",
    options:opts4("$\\dfrac{2}{3}$","$\\dfrac{7}{9}$","$\\dfrac{8}{9}$","$1$"),
    correct:"3",
    explanation:"$|A|=$행렬식 계산 $=9$ (1행 전개 또는 행 축약).\n$|2A^{-1}|=2^3\\cdot|A^{-1}|=8/|A|=8/9$.",
  },
  {n:48, subject:"미분학", unit:"미분방정식", concept:"완전 미분방정식",
    difficulty:"medium",
    question:"곡선 $f(x,y)=0$이 미분방정식 $(6x+4y+1)\\,dx+(4x+2y+2)\\,dy=0,\\,y(1/3)=1$을 만족시킨다. 곡선 $f(x,y)=0$ 위의 점 $(1,\\alpha)$에 대하여 $\\alpha^2+6\\alpha$의 값은? (단, $\\alpha$는 실수)",
    options:opts4("$-1$","$0$","$1$","$2$"),
    correct:"3",
    explanation:"완미 검증: $\\partial(6x+4y+1)/\\partial y=4=\\partial(4x+2y+2)/\\partial x$ ✓.\n해 $\\phi=3x^2+4xy+y^2+x+2y=C$. $(1/3,1)$ 대입: $1/3+4/3+1+1/3+2=5\\Rightarrow C=5$.\n$(1,\\alpha)$ 대입: $3+4\\alpha+\\alpha^2+1+2\\alpha=5\\Rightarrow\\alpha^2+6\\alpha=1$.",
  },
  {n:49, subject:"미분학", unit:"미분방정식", concept:"비동차 ODE (특수해)",
    difficulty:"medium",
    question:"미분방정식 $\\dfrac{d^2 y}{dx^2}-3\\dfrac{dy}{dx}-4y=6e^x,\\,y(0)=y'(0)=-1$의 해를 $f(x)$라 할 때, $f(1)\\times f'(-1)$의 값은?",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"1",
    explanation:"보조방정식 $r^2-3r-4=(r-4)(r+1)=0$, $y_h=c_1 e^{4x}+c_2 e^{-x}$.\n특수해: $y_p=Ae^x$ 대입 $A-3A-4A=6\\Rightarrow A=-1$. $y_p=-e^x$.\n초기조건으로 $c_1=c_2=0$. $f(x)=-e^x$.\n$f(1)\\cdot f'(-1)=(-e)\\cdot(-e^{-1})=1$.",
  },
  {n:50, subject:"적분학", unit:"라플라스 변환", concept:"부분분수 + 역라플라스 평가",
    difficulty:"hard",
    question:"함수 $f(t)$의 라플라스변환 $\\mathcal{L}(f)=F$가 $F(s)=\\dfrac{s+1}{s^4+4s^3+4s^2}$일 때, $f(4)$의 값은?",
    options:opts4("$1-e^{-8}$","$2-e^{-8}$","$1-e^{-4}$","$2-e^{-4}$"),
    correct:"1",
    explanation:"$F(s)=\\dfrac{s+1}{s^2(s+2)^2}$. 부분분수 (혹은 컨볼루션):\n$F=\\dfrac{1}{4(s+1)}\\!\\left(\\dfrac{1}{s^2}-\\dfrac{1}{(s+2)^2}\\right)$ 형태로 분해.\n$\\mathcal L^{-1}\\{F\\}=\\dfrac{1}{4}(t-te^{-2t})$ (계산).\n$f(4)=\\dfrac{1}{4}(4-4e^{-8})=1-e^{-8}$.",
  },
];

const TOTAL=PROBLEMS.length;
console.log(`총 ${TOTAL}문제 (객관식 4지선다) 준비됨`);

const rows = PROBLEMS.map(p => {
  const id = `q-${YEAR_ID}-${SCHOOL_EN}-${String(p.n).padStart(2,"0")}`;
  return {
    id, subject: p.subject, unit: p.unit, concept: p.concept, difficulty: p.difficulty,
    source_type: "imported", pool: "general", question: p.question, content_type: "latex",
    question_image: null, question_type: "multiple_choice",
    options: p.options, correct_option_id: p.correct,
    answer_text: null, explanation: p.explanation, explanation_content_type: "latex",
    explanation_image: null,
    tags: [YEAR_KO, SCHOOL_KO, SESSION_KO, "past_exam", p.subject, p.unit, p.concept],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  };
});

const { data, error } = await sb.from("questions").upsert(rows, { onConflict: "id" }).select("id");
if (error) { console.error("업로드 실패:", error); process.exit(1); }
console.log(`업로드 완료: ${data.length}건`);
