// Upload 공학수학 Daily TEST 1~27.
// Usage: node scripts/upload_daily_tests_eng_1to27.mjs
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(
  envText.split(/\r?\n/).filter((l) => l && !l.startsWith("#") && l.includes("="))
    .map((l) => { const [k, ...r] = l.split("="); return [k.trim(), r.join("=").trim()]; })
);
const supabase = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.NEXT_PUBLIC_SUPABASE_ANON_KEY);

const o = (id, text) => ({ id, label: id, text, contentType: "latex", image: "" });
function build({ testNo, num, unit, concept, difficulty, question, options, answer, explanation }) {
  const id = `q-daily-eng-r${testNo}-${num}`;
  const tags = Array.from(new Set(["daily", `daily-test-eng-${testNo}`, "공학수학", unit, concept].filter(Boolean)));
  return {
    id, subject: "공학수학", unit, concept, difficulty,
    source_type: "imported", question, content_type: "latex", question_image: null,
    options, correct_option_id: answer, explanation, explanation_content_type: "latex",
    explanation_image: null, tags,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString()
  };
}

const problems = [
  // ========== DT1 미분방정식 (분리형/적분인자) ==========
  build({ testNo: 1, num: 1, unit: "미분방정식", concept: "분리형 ODE", difficulty: "easyMedium",
    question: "초깃값 $y(0)=0$을 만족하는 미분방정식 $\\dfrac{dy}{dx}=\\dfrac{x^2}{y}$의 해는?",
    options: [
      o("1","$2x^3-3y^2=0$"),
      o("2","$x^3-y^2=0$"),
      o("3","$x^2-y^2=0$"),
      o("4","$y^2-x^3=1$"),
      o("5","$y=x^3$")
    ], answer: "1",
    explanation: "$ydy=x^2dx\\Rightarrow y^2/2=x^3/3+C$. $(0,0)$ 대입 $C=0$. $2x^3-3y^2=0$." }),
  build({ testNo: 1, num: 2, unit: "미분방정식", concept: "분리형 ODE", difficulty: "easyMedium",
    question: "$y'=y^2+1,y(0)=0$일 때 $y(\\pi/4)$의 값은?",
    options: [o("1","$0$"),o("2","$1$"),o("3","$\\dfrac{\\pi}{4}$"),o("4","$\\sqrt 2$"),o("5","$\\pi$")],
    answer: "2",
    explanation: "$\\frac{1}{y^2+1}dy=dx\\Rightarrow\\tan^{-1}y=x$. $x=\\pi/4$: $y=\\tan(\\pi/4)=1$." }),
  build({ testNo: 1, num: 3, unit: "미분방정식", concept: "분리형 ODE", difficulty: "easyMedium",
    question: "$(1+y^2)dx+(1+x^2)dy=0,y(0)=1$의 해 $y(x)$일 때 $y(2)$의 값은?",
    options: [
      o("1","$-\\dfrac{1}{3}$"),
      o("2","$-\\dfrac{1}{2}$"),
      o("3","$\\dfrac{1}{3}$"),
      o("4","$0$"),
      o("5","$1$")
    ], answer: "1",
    explanation: "$\\tan^{-1}x+\\tan^{-1}y=\\pi/4$. $x=2$: $y=\\tan(\\pi/4-\\tan^{-1}2)=-1/3$." }),
  build({ testNo: 1, num: 4, unit: "미분방정식", concept: "분리형 ODE", difficulty: "medium",
    question: "$y(x)$가 $\\dfrac{y^2}{x}\\dfrac{dy}{dx}=\\sqrt{1-y^3}\\ln x,y(1)=0$의 해일 때 $y(\\sqrt e)$의 값은?",
    options: [
      o("1","$\\dfrac{\\sqrt[3]{39}}{4}$"),
      o("2","$\\dfrac{1}{4}$"),
      o("3","$\\sqrt[3]{39}$"),
      o("4","$\\dfrac{1}{2}$"),
      o("5","$1$")
    ], answer: "1",
    explanation: "분리: $-\\frac{2}{3}\\sqrt{1-y^3}=\\frac{1}{2}x^2\\ln x-\\frac{1}{4}x^2+C$. $(1,0)$: $C=-5/12$. $x=\\sqrt e$: $y^3=39/64,\\ y=\\sqrt[3]{39}/4$." }),
  build({ testNo: 1, num: 5, unit: "미분방정식", concept: "1계 선형 ODE", difficulty: "easyMedium",
    question: "$y'-\\dfrac{1}{x}y=x^2$의 해 $y=y(x)$가 $y(2)=0$일 때 $y(1)$의 값은?",
    options: [
      o("1","$-\\dfrac{3}{2}$"),
      o("2","$\\dfrac{3}{2}$"),
      o("3","$-1$"),
      o("4","$0$"),
      o("5","$1$")
    ], answer: "1",
    explanation: "적분인자 $1/x$. $y/x=x^2/2+C\\Rightarrow y=x^3/2+Cx$. $(2,0)$: $C=-2$. $y(1)=1/2-2=-3/2$." }),
  build({ testNo: 1, num: 6, unit: "미분방정식", concept: "1계 선형 ODE", difficulty: "easyMedium",
    question: "$y'+y\\cos x=2\\cos x$의 해가 $y(0)=1$을 만족할 때 $y(\\pi)$의 값은?",
    options: [o("1","$0$"),o("2","$1$"),o("3","$2$"),o("4","$-1$"),o("5","$e$")],
    answer: "2",
    explanation: "적분인자 $e^{\\sin x}$. $y=2-e^{-\\sin x}$. $y(0)=1\\Rightarrow C=-1$. $y(\\pi)=2-1=1$." }),

  // ========== DT2 미분방정식 ==========
  build({ testNo: 2, num: 1, unit: "미분방정식", concept: "1계 선형 ODE", difficulty: "easyMedium",
    question: "초기값 $\\{x^2y'+xy=1,x>0,y(1)=2\\}$의 해는?",
    options: [
      o("1","$y=\\dfrac{\\ln x+2}{x}$"),
      o("2","$y=2x$"),
      o("3","$y=\\dfrac{2}{x}$"),
      o("4","$y=\\ln x$"),
      o("5","$y=x^2+1$")
    ], answer: "1",
    explanation: "$y'+y/x=1/x^2$. 적분인자 $x$. $xy=\\ln|x|+C$. $C=2$. $y=(\\ln x+2)/x$." }),
  build({ testNo: 2, num: 2, unit: "미분방정식", concept: "1계 선형 ODE", difficulty: "easyMedium",
    question: "$(1+x^2)\\dfrac{dy}{dx}+xy=e^x\\sqrt{1+x^2},y(0)=1$의 해를 $y(x)$라 하면 $y(1)$의 값은?",
    options: [o("1","$\\dfrac{e}{\\sqrt 2}$"),o("2","$e$"),o("3","$e^2$"),o("4","$\\sqrt 2$"),o("5","$1$")],
    answer: "1",
    explanation: "정리 후 $y=e^x/\\sqrt{1+x^2}+C/\\sqrt{1+x^2}$. $C=0$. $y(1)=e/\\sqrt 2$." }),
  build({ testNo: 2, num: 3, unit: "미분방정식", concept: "분리형 ODE", difficulty: "easy",
    question: "$\\dfrac{dy}{dx}-2xy=0$에서 $y(0)=2$를 만족하는 해는?",
    options: [o("1","$y=2e^{x^2}$"),o("2","$y=e^{2x}$"),o("3","$y=2x^2$"),o("4","$y=e^{x^2}$"),o("5","$y=2$")],
    answer: "1",
    explanation: "$y'/y=2x\\Rightarrow\\ln y=x^2+C\\Rightarrow y=Ce^{x^2},C=2$." }),
  build({ testNo: 2, num: 4, unit: "미분방정식", concept: "완전미분방정식", difficulty: "medium",
    question: "$y=y(x)$가 미분방정식 $(x+y)^2 dx+(2xy+x^2-1)dy=0,y(1)=1$의 해일 때 $y(0)$의 값은?",
    options: [
      o("1","$-\\dfrac{4}{3}$"),
      o("2","$-1$"),
      o("3","$0$"),
      o("4","$1$"),
      o("5","$\\dfrac{4}{3}$")
    ], answer: "1",
    explanation: "완전미분: $\\frac{1}{3}x^3+x^2y+xy^2-y=4/3$. $x=0$: $y=-4/3$." }),
  build({ testNo: 2, num: 5, unit: "미분방정식", concept: "완전미분방정식", difficulty: "medium",
    question: "$\\left(\\dfrac{2xy}{x^2+1}-1\\right)dx+(\\ln(x^2+1)+1)dy=0,y(0)=0$의 해를 $y$라 할 때 $y(1)$의 값은?",
    options: [
      o("1","$\\dfrac{1}{\\ln 2+1}$"),
      o("2","$\\ln 2$"),
      o("3","$1$"),
      o("4","$\\dfrac{1}{2}$"),
      o("5","$\\dfrac{1}{\\ln 2}$")
    ], answer: "1",
    explanation: "완전: $y\\ln(x^2+1)-x+y=C$. $y(0)=0\\Rightarrow C=0$. $x=1$: $y\\ln 2+y=1\\Rightarrow y=1/(\\ln 2+1)$." }),
  build({ testNo: 2, num: 6, unit: "미분방정식", concept: "완전미분방정식", difficulty: "medium",
    question: "$[(x+1)e^x-e^y]dx=xe^y dy,y(1)=0$의 해를 푸시오.",
    options: [
      o("1","$x(e^x-e^y)=e-1$"),
      o("2","$xe^x-ye^y=e$"),
      o("3","$x(e^x+e^y)=2e$"),
      o("4","$e^x-e^y=e-1$"),
      o("5","$xy=e-1$")
    ], answer: "1",
    explanation: "정리하면 $xe^x-xe^y=C$. $y(1)=0$: $e-1=C$. $x(e^x-e^y)=e-1$." }),

  // ========== DT3 미분방정식 ==========
  build({ testNo: 3, num: 1, unit: "미분방정식", concept: "완전미분방정식", difficulty: "medium",
    question: "초깃값 $(3x+2y^2)dx+2xydy=0,y(1)=1$의 해를 구하시오.",
    options: [
      o("1","$x^3+x^2y^2=2$"),
      o("2","$x^2+y^2=2$"),
      o("3","$xy=1$"),
      o("4","$x^3-y^3=0$"),
      o("5","$x+y=2$")
    ], answer: "1",
    explanation: "적분인자 $x$. $\\int(3x^2+2xy^2)dx+\\int 2x^2y dy=C$로 $x^3+x^2y^2=C=2$." }),
  build({ testNo: 3, num: 2, unit: "미분방정식", concept: "완전미분방정식", difficulty: "medium",
    question: "$2xydx+(2x^2+3y)dy=0,y(1)=1$의 해 $y(x)$에 대해 $y(0)$의 값은?",
    options: [o("1","$\\sqrt[3]{2}$"),o("2","$1$"),o("3","$2$"),o("4","$\\sqrt 2$"),o("5","$0$")],
    answer: "1",
    explanation: "적분인자 $y$. $x^2y^2+y^3=C=2$. $x=0$: $y^3=2,y=\\sqrt[3]{2}$." }),
  build({ testNo: 3, num: 3, unit: "미분방정식", concept: "Bernoulli ODE", difficulty: "medium",
    question: "$y=y(x)$가 $y'+\\dfrac{1}{x}y=3x^2y^3,y(1)=1$의 해일 때 $y(1/2)$의 값은?",
    options: [o("1","$1$"),o("2","$2$"),o("3","$\\dfrac{1}{2}$"),o("4","$4$"),o("5","$\\dfrac{1}{4}$")],
    answer: "1",
    explanation: "Bernoulli $u=y^{-2}$. $u'-(2/x)u=-6x^2$. 풀면 $1/y^2=x^2(7-6x)$. $y(1/2)=1$." }),
  build({ testNo: 3, num: 4, unit: "미분방정식", concept: "Bernoulli ODE", difficulty: "medium",
    question: "$x\\dfrac{dy}{dx}-\\dfrac{1}{y^2}=-y,y(1)=2$일 때 $y(1/2)$의 값은?",
    options: [o("1","$\\sqrt[3]{57}$"),o("2","$2$"),o("3","$1$"),o("4","$3$"),o("5","$\\sqrt[3]{8}$")],
    answer: "1",
    explanation: "Bernoulli ($n=-2$). $u=y^3$. $xu'+3u=3$ → $u=1+7/x^3$. $x=1/2$: $u=57$, $y=\\sqrt[3]{57}$." }),

  // ========== DT4 미분방정식 (동차/완전) ==========
  build({ testNo: 4, num: 1, unit: "미분방정식", concept: "동차 ODE", difficulty: "medium",
    question: "$\\dfrac{dy}{dx}=\\dfrac{y-2x}{y+x}$의 일반해를 $f(x,y)=c$로 표현한다면?",
    options: [
      o("1","$\\dfrac{1}{2}\\ln(y^2+2x^2)+\\dfrac{1}{\\sqrt 2}\\tan^{-1}\\dfrac{1}{\\sqrt 2 x}=c$"),
      o("2","$y^2+2x^2=c$"),
      o("3","$x+y=c$"),
      o("4","$xy=c$"),
      o("5","$y/x=c$")
    ], answer: "1",
    explanation: "$y=ux$ 치환 후 적분." }),
  build({ testNo: 4, num: 2, unit: "미분방정식", concept: "분리형 ODE", difficulty: "easyMedium",
    question: "$xdy+ydx=2x^2ydx$의 해 $y=f(x)$가 $f(1)=1$일 때 $f(2)$의 값은?",
    options: [o("1","$\\dfrac{1}{2}e^3$"),o("2","$e^3$"),o("3","$e^2$"),o("4","$2$"),o("5","$1$")],
    answer: "1",
    explanation: "$d(xy)=2x^2ydx$ 즉 $(xy)'/y=2x^2$. 분리형 풀이로 $y=e^{x^2-1}/x$. $f(2)=e^3/2$." }),
  build({ testNo: 4, num: 3, unit: "미분방정식", concept: "1계 선형 ODE", difficulty: "medium",
    question: "$y=y(x)$가 $xdy+(xy+2y-2e^{-x})dx=0,y(1)=2e^{-1}$의 해일 때 $y(1/2)$의 값은?",
    options: [
      o("1","$\\dfrac{5}{\\sqrt e}$"),
      o("2","$\\dfrac{1}{\\sqrt e}$"),
      o("3","$\\sqrt e$"),
      o("4","$\\dfrac{2}{\\sqrt e}$"),
      o("5","$5$")
    ], answer: "1",
    explanation: "$y'+(1+2/x)y=2e^{-x}/x$. 적분인자 $x^2 e^x$. $y=(x^2+1)/(x^2 e^x)$. $y(1/2)=5/\\sqrt e$." }),
  build({ testNo: 4, num: 4, unit: "미분방정식", concept: "완전미분방정식", difficulty: "medium",
    question: "$\\dfrac{y^2}{2}+2ye^x+(y+e^x)\\dfrac{dy}{dx}=0$의 해는?",
    options: [
      o("1","$e^x\\dfrac{y^2}{2}+ye^{2x}=C$"),
      o("2","$y^2+e^x=C$"),
      o("3","$ye^x=C$"),
      o("4","$xy=C$"),
      o("5","$x+y^2=C$")
    ], answer: "1",
    explanation: "적분인자 $e^x$. $\\int(e^x y^2/2+2ye^{2x})dx+\\int(ye^x+e^{2x})dy=0$. $e^x y^2/2+ye^{2x}=C$." }),
  build({ testNo: 4, num: 5, unit: "미분방정식", concept: "완전미분방정식", difficulty: "medium",
    question: "$(e^x+y)dx+(x-e^{-y})dy=0$의 해 $f(x,y)=0$이 $(0,-1)$을 지난다. 이 해의 그래프가 지나는 또 다른 점은?",
    options: [o("1","$(1,0)$"),o("2","$(0,1)$"),o("3","$(1,1)$"),o("4","$(-1,0)$"),o("5","$(2,2)$")],
    answer: "1",
    explanation: "완전: $e^x+xy+e^{-y}=C$. $(0,-1)$: $1+0+e=e+1$. $(1,0)$: $e+0+1=e+1$ ✓." }),
  build({ testNo: 4, num: 6, unit: "미분방정식", concept: "적분방정식", difficulty: "medium",
    question: "연속함수 $f(x)$가 $1+\\int_1^x f(t)dt=f(x)$를 만족할 때 $f(0)$의 값은?",
    options: [
      o("1","$\\dfrac{1}{e}$"),
      o("2","$1$"),
      o("3","$e$"),
      o("4","$0$"),
      o("5","$\\dfrac{1}{e^2}$")
    ], answer: "1",
    explanation: "양변 미분: $f'=f$. $f=Ce^x$. $f(1)=1$: $C=1/e$. $f(0)=1/e$." }),

  // ========== DT5 (직교절선, 2계 ODE 동차) ==========
  build({ testNo: 5, num: 1, unit: "미분방정식", concept: "직교절선", difficulty: "medium",
    question: "두 곡선족 $y=(x+c)^{-1}$과 $y=a(x+k)^{1/3}$이 직교절선이 되기 위한 실수 $a$의 값은?",
    options: [o("1","$\\sqrt[3]{3}$"),o("2","$3$"),o("3","$1$"),o("4","$\\sqrt 3$"),o("5","$2$")],
    answer: "1",
    explanation: "$y=1/(x+c)$의 미분 $y'=-y^2$. 직교절선 $y'=1/y^2$. 풀면 $y^3=3(x+k)$ 즉 $y=3^{1/3}(x+k)^{1/3}$." }),
  build({ testNo: 5, num: 2, unit: "미분방정식", concept: "2계 동차 ODE", difficulty: "easyMedium",
    question: "$y(0)=1,y'(0)=1$ 만족하는 $\\dfrac{d^2y}{dx^2}+\\dfrac{dy}{dx}-2y=0$의 해 $y(1)$의 값은?",
    options: [o("1","$e$"),o("2","$1$"),o("3","$e^2$"),o("4","$2e$"),o("5","$0$")],
    answer: "1",
    explanation: "특성근 $-2,1$. $y=c_1 e^{-2x}+c_2 e^x$. $c_1=0,c_2=1\\Rightarrow y=e^x,y(1)=e$." }),
  build({ testNo: 5, num: 3, unit: "미분방정식", concept: "2계 동차 ODE", difficulty: "easyMedium",
    question: "$y''+5y'+6y=0,y(0)=3,y'(0)=-7$일 때 $y(1)+y'(1)$의 값은?",
    options: [
      o("1","$-2e^{-2}-2e^{-3}$"),
      o("2","$0$"),
      o("3","$2e^{-2}+2e^{-3}$"),
      o("4","$-e^{-2}$"),
      o("5","$3e^{-3}$")
    ], answer: "1",
    explanation: "근 $-2,-3$. $y=2e^{-2x}+e^{-3x}$. $y(1)+y'(1)=-2e^{-2}-2e^{-3}$." }),
  build({ testNo: 5, num: 4, unit: "미분방정식", concept: "2계 동차 ODE", difficulty: "easyMedium",
    question: "$y''-2y'=0,y(0)=1,y(1/2)=e$의 해를 $y$라 할 때 $y(1)$의 값은?",
    options: [o("1","$e^2$"),o("2","$e$"),o("3","$1$"),o("4","$2e$"),o("5","$e^3$")],
    answer: "1",
    explanation: "근 $0,2$. $y=c_1+c_2 e^{2x}$. $c_1=0,c_2=1\\Rightarrow y=e^{2x}$. $y(1)=e^2$." }),
  build({ testNo: 5, num: 5, unit: "미분방정식", concept: "2계 중근 ODE", difficulty: "easyMedium",
    question: "$\\dfrac{d^2y}{dx^2}-6\\dfrac{dy}{dx}+9y=0,y(0)=3,y'(0)=1$의 해를 구하라.",
    options: [
      o("1","$y=(3-8x)e^{3x}$"),
      o("2","$y=3e^{3x}$"),
      o("3","$y=e^{3x}+x$"),
      o("4","$y=(1+x)e^{3x}$"),
      o("5","$y=3e^{x}$")
    ], answer: "1",
    explanation: "중근 $3$. $y=(c_1+c_2 x)e^{3x}$. $c_1=3,c_2=-8$." }),
  build({ testNo: 5, num: 6, unit: "미분방정식", concept: "2계 중근 ODE", difficulty: "easyMedium",
    question: "$\\dfrac{d^2y}{dx^2}-4\\dfrac{dy}{dx}+4y=0,y(0)=1,y'(0)=5$의 해는?",
    options: [
      o("1","$e^{2x}+3xe^{2x}$"),
      o("2","$e^{2x}+xe^{2x}$"),
      o("3","$e^{2x}+5xe^{2x}$"),
      o("4","$(1+5x)e^{2x}$"),
      o("5","$5e^{2x}$")
    ], answer: "1",
    explanation: "중근 $2$. $y=(1+3x)e^{2x}$." }),

  // ========== DT6 미분방정식 (2계 비제차) ==========
  build({ testNo: 6, num: 1, unit: "미분방정식", concept: "2계 동차 ODE", difficulty: "easyMedium",
    question: "$y''+y=0,y(\\pi/3)=2,y'(\\pi/3)=-4$의 해 $y(\\pi/2)$의 값은?",
    options: [o("1","$\\sqrt 3-2$"),o("2","$\\sqrt 3$"),o("3","$2-\\sqrt 3$"),o("4","$-1$"),o("5","$0$")],
    answer: "1",
    explanation: "$y=c_1\\cos x+c_2\\sin x$. 조건으로 $c_1=1+2\\sqrt 3,c_2=\\sqrt 3-2$. $y(\\pi/2)=c_2=\\sqrt 3-2$." }),
  build({ testNo: 6, num: 2, unit: "미분방정식", concept: "2계 동차 ODE", difficulty: "easyMedium",
    question: "초깃값 문제 $y''-2y'+2y=0,y(0)=2,y'(0)=1$의 해 $y(\\pi/2)$의 값은?",
    options: [o("1","$-e^{\\pi/2}$"),o("2","$e^{\\pi/2}$"),o("3","$0$"),o("4","$2$"),o("5","$1$")],
    answer: "1",
    explanation: "근 $1\\pm i$. $y=e^x(2\\cos x-\\sin x)$. $y(\\pi/2)=e^{\\pi/2}(0-1)=-e^{\\pi/2}$." }),
  build({ testNo: 6, num: 3, unit: "미분방정식", concept: "3계 ODE", difficulty: "medium",
    question: "$y'''-6y''+12y'-8y=0,y(0)=0,y'(0)=0,y''(0)=2$의 해 $y$일 때 $y(\\ln 2)$의 값은?",
    options: [o("1","$4(\\ln 2)^2$"),o("2","$\\ln 2$"),o("3","$1$"),o("4","$2$"),o("5","$0$")],
    answer: "1",
    explanation: "$(D-2)^3=0$. $y=(c_1+c_2 x+c_3 x^2)e^{2x}$. 조건으로 $c_3=1,c_1=c_2=0$. $y=x^2 e^{2x}$. $y(\\ln 2)=4(\\ln 2)^2$." }),
  build({ testNo: 6, num: 4, unit: "미분방정식", concept: "비제차 ODE", difficulty: "medium",
    question: "$y''-6y'+8y=-2e^{3x}$의 일반해 $y=k_1 e^{ax}+k_2 e^{bx}+ce^{dx}$일 때 $a+b+c+d$는?",
    options: [o("1","$11$"),o("2","$9$"),o("3","$7$"),o("4","$13$"),o("5","$15$")],
    answer: "1",
    explanation: "$y=k_1 e^{2x}+k_2 e^{4x}+2e^{3x}$. $a+b+c+d=2+4+2+3=11$." }),
  build({ testNo: 6, num: 5, unit: "미분방정식", concept: "비제차 ODE", difficulty: "medium",
    question: "$y''+3y'+2y=6e^x,y(0)=1,y(\\ln 2)=3$일 때 $y(3)$의 값은?",
    options: [
      o("1","$4e^{-3}-4e^{-6}+e^3$"),
      o("2","$e^3$"),
      o("3","$0$"),
      o("4","$4e^3$"),
      o("5","$3e^{-3}$")
    ], answer: "1",
    explanation: "$y=4e^{-x}-4e^{-2x}+e^x$. $y(3)=4e^{-3}-4e^{-6}+e^3$." }),
  build({ testNo: 6, num: 6, unit: "미분방정식", concept: "비제차 ODE", difficulty: "medium",
    question: "$y''+2y'+y=2e^{-x},y(0)=-1,y'(0)=1$일 때 $y(1)$의 값은?",
    options: [o("1","$0$"),o("2","$1$"),o("3","$e^{-1}$"),o("4","$-e^{-1}$"),o("5","$2$")],
    answer: "1",
    explanation: "$y=-e^{-x}+x^2 e^{-x}$. $y(1)=-e^{-1}+e^{-1}=0$." }),

  // ========== DT7 비제차 ==========
  build({ testNo: 7, num: 1, unit: "미분방정식", concept: "비제차 ODE", difficulty: "medium",
    question: "$y(x)$가 $y''+y'-2y=6e^x,y(0)=0,y'(0)=-1$의 해일 때 $y(1)$의 값은?",
    options: [o("1","$e^{-2}+e$"),o("2","$e^{-1}$"),o("3","$e$"),o("4","$0$"),o("5","$2e$")],
    answer: "1",
    explanation: "$y=e^{-2x}-e^x+2xe^x$. $y(1)=e^{-2}-e+2e=e^{-2}+e$." }),
  build({ testNo: 7, num: 2, unit: "미분방정식", concept: "비제차 ODE", difficulty: "medium",
    question: "초깃값 $y''-6y'+9y=6x^2+2,y(0)=1,y'(0)=2$의 해를 $y(x)$라 할 때 $y(1)$의 값은?",
    options: [
      o("1","$\\dfrac{4(e^3+5)}{9}$"),
      o("2","$\\dfrac{4}{9}e^3$"),
      o("3","$1$"),
      o("4","$5$"),
      o("5","$e^3+5$")
    ], answer: "1",
    explanation: "특수해 $\\frac{2}{3}x^2+\\frac{8}{9}x+\\frac{2}{3}$. $y_h=(a+bx)e^{3x}$. 풀이로 $y(1)=4(e^3+5)/9$." }),
  build({ testNo: 7, num: 3, unit: "미분방정식", concept: "비제차 ODE", difficulty: "medium",
    question: "$y''+4y=\\cos t,y(0)=y'(0)=0$의 해 $y(t)$일 때 $y(\\pi/2)$의 값은?",
    options: [
      o("1","$\\dfrac{1}{3}$"),
      o("2","$0$"),
      o("3","$1$"),
      o("4","$\\dfrac{1}{2}$"),
      o("5","$-\\dfrac{1}{3}$")
    ], answer: "1",
    explanation: "특수해 $\\frac{1}{3}\\cos t$. $y=-\\frac{1}{3}\\cos 2t+\\frac{1}{3}\\cos t$. $y(\\pi/2)=1/3$." }),
  build({ testNo: 7, num: 4, unit: "미분방정식", concept: "비제차 ODE", difficulty: "medium",
    question: "$y''+y=-4\\sin x,y(\\pi/2)=-1,y'(\\pi/2)=0$의 해 $y(\\pi)$의 값은?",
    options: [o("1","$-\\pi$"),o("2","$\\pi$"),o("3","$0$"),o("4","$-1$"),o("5","$1$")],
    answer: "1",
    explanation: "특수해 $2x\\cos x$. $y=-\\pi\\cos x-\\sin x+2x\\cos x$. $y(\\pi)=-\\pi$." }),
  build({ testNo: 7, num: 5, unit: "미분방정식", concept: "비제차 ODE", difficulty: "medium",
    question: "$f''(t)-6f'(t)+9f(t)=t^2 e^{3t},f(0)=2,f'(0)=6$일 때 $f(1)$의 값은?",
    options: [
      o("1","$\\dfrac{25}{12}e^3$"),
      o("2","$2e^3$"),
      o("3","$\\dfrac{1}{12}e^3$"),
      o("4","$e^3$"),
      o("5","$\\dfrac{5}{6}e^3$")
    ], answer: "1",
    explanation: "특수해 $t^4 e^{3t}/12$. $f=2e^{3t}+t^4 e^{3t}/12$. $f(1)=25e^3/12$." }),

  // ========== DT8 (Wronskian, 매개변수, Cauchy-Euler) ==========
  build({ testNo: 8, num: 1, unit: "미분방정식", concept: "비제차 ODE", difficulty: "medium",
    question: "$y''+2y'+y=e^{-x}\\cos 2x,y(0)=0,y'(0)=-1$의 해는?",
    options: [
      o("1","$y=-\\dfrac{1}{4}e^{-x}(4x+\\cos 2x-1)$"),
      o("2","$y=e^{-x}\\cos 2x$"),
      o("3","$y=\\dfrac{1}{4}e^{-x}\\cos 2x$"),
      o("4","$y=e^{-x}(1+x)$"),
      o("5","$y=-e^{-x}$")
    ], answer: "1",
    explanation: "특수해 $-\\frac{1}{4}e^{-x}\\cos 2x$. 일반해와 초기값으로 정리." }),
  build({ testNo: 8, num: 2, unit: "미분방정식", concept: "비제차 ODE 특수해", difficulty: "medium",
    question: "$y''-4y'+4y=e^{2x}+\\sin x$의 특수해는?",
    options: [
      o("1","$\\dfrac{1}{2}x^2 e^{2x}+\\dfrac{3}{25}\\sin x+\\dfrac{4}{25}\\cos x$"),
      o("2","$x^2 e^{2x}$"),
      o("3","$\\sin x$"),
      o("4","$e^{2x}$"),
      o("5","$\\dfrac{1}{2}e^{2x}+\\sin x$")
    ], answer: "1",
    explanation: "$e^{2x}$ 부분: $x^2 e^{2x}/2$. $\\sin x$ 부분: $(3\\sin x+4\\cos x)/25$." }),
  build({ testNo: 8, num: 3, unit: "미분방정식", concept: "비제차 ODE", difficulty: "medium",
    question: "$y''+y=2x+8\\cos x,y(\\pi)=0,y'(\\pi)=2$일 때 $y(\\pi/2)$의 값은?",
    options: [o("1","$-\\pi$"),o("2","$\\pi$"),o("3","$0$"),o("4","$1$"),o("5","$-1$")],
    answer: "1",
    explanation: "특수해 $2x+4x\\sin x$. $y=2\\pi\\cos x-4\\pi\\sin x+2x+4x\\sin x$. $y(\\pi/2)=-\\pi$." }),
  build({ testNo: 8, num: 4, unit: "미분방정식", concept: "Cauchy-Euler", difficulty: "medium",
    question: "$y=y(x)$가 $x^2y''+5xy'+3y=0,y(1)=3,y'(1)=-5$의 해일 때 $y(2)$의 값은?",
    options: [o("1","$\\dfrac{9}{8}$"),o("2","$1$"),o("3","$\\dfrac{1}{8}$"),o("4","$2$"),o("5","$3$")],
    answer: "1",
    explanation: "$D^2+4D+3=0$, 근 $-1,-3$. $y=2/x+1/x^3$. $y(2)=1+1/8=9/8$." }),
  build({ testNo: 8, num: 5, unit: "미분방정식", concept: "Cauchy-Euler", difficulty: "medium",
    question: "$y$가 $x^2y''-4xy'+6y=0$을 만족하고 $y(1)=2,y'(1)=3$일 때 $y(2)$의 값은?",
    options: [o("1","$4$"),o("2","$8$"),o("3","$2$"),o("4","$12$"),o("5","$0$")],
    answer: "1",
    explanation: "$D^2-5D+6=0$, 근 $2,3$. $y=3x^2-x^3$. $y(2)=12-8=4$." }),
  build({ testNo: 8, num: 6, unit: "미분방정식", concept: "Cauchy-Euler", difficulty: "medium",
    question: "$y=y(x)$가 $x^2y''+3xy'=0,y(1)=0,y'(1)=4$의 해일 때 $y(2)$의 값은?",
    options: [o("1","$\\dfrac{3}{2}$"),o("2","$1$"),o("3","$2$"),o("4","$3$"),o("5","$4$")],
    answer: "1",
    explanation: "$D^2+2D=0$, 근 $0,-2$. $y=2-2x^{-2}$. $y(2)=2-1/2=3/2$." }),

  // ========== DT9 (오일러-코시) ==========
  build({ testNo: 9, num: 1, unit: "미분방정식", concept: "Cauchy-Euler", difficulty: "easyMedium",
    question: "오일러-코시 미분방정식 $x^2y''-6y=0$의 해 $y=f(x)$가 $f(1)=1,f(-1)=1$을 만족한다. $f(2)$의 값은?",
    options: [o("1","$\\dfrac{1}{4}$"),o("2","$1$"),o("3","$4$"),o("4","$\\dfrac{1}{8}$"),o("5","$8$")],
    answer: "1",
    explanation: "$D^2-D-6=0$, 근 $3,-2$. $y=c_1 x^3+c_2 x^{-2}$. 조건으로 $c_1=0,c_2=1$. $f(2)=1/4$." }),
  build({ testNo: 9, num: 2, unit: "미분방정식", concept: "Cauchy-Euler 중근", difficulty: "easyMedium",
    question: "$y=y(x)$가 $x^2y''-xy'+y=0,y(1)=0,y'(1)=1$의 해일 때 $y(e)$의 값은?",
    options: [o("1","$e$"),o("2","$1$"),o("3","$e^2$"),o("4","$0$"),o("5","$\\ln e$")],
    answer: "1",
    explanation: "$(D-1)^2=0$, 중근 $1$. $y=(c_1+c_2\\ln x)x$. $y=x\\ln x$. $y(e)=e$." }),
  build({ testNo: 9, num: 3, unit: "미분방정식", concept: "Cauchy-Euler 중근", difficulty: "medium",
    question: "$y=y(x)$가 $x^2y''-3xy'+4y=0,y(1)=5,y'(1)=3$의 해일 때 $y(e^2)$의 값은?",
    options: [o("1","$-9e^4$"),o("2","$2e^2$"),o("3","$e^2$"),o("4","$5e^4$"),o("5","$0$")],
    answer: "1",
    explanation: "$(D-2)^2=0$, 중근 $2$. $y=(5-7\\ln x)x^2$. $y(e^2)=(5-14)e^4=-9e^4$." }),
  build({ testNo: 9, num: 4, unit: "미분방정식", concept: "Cauchy-Euler 복소근", difficulty: "medium",
    question: "$y=y(x)$가 $x^2y''-5xy'+10y=0,y(1)=4,y'(1)=-6$의 해일 때 $y(e)$의 값은?",
    options: [
      o("1","$4e^3\\cos 1-18e^3\\sin 1$"),
      o("2","$4e^3$"),
      o("3","$0$"),
      o("4","$e^3$"),
      o("5","$4\\cos 1$")
    ], answer: "1",
    explanation: "근 $3\\pm i$. $y=x^3(c_1\\cos\\ln x+c_2\\sin\\ln x)$. $c_1=4,c_2=-18$." }),
  build({ testNo: 9, num: 5, unit: "미분방정식", concept: "Cauchy-Euler 복소근", difficulty: "medium",
    question: "$x^2y''+5xy'+5y=0,y(1)=1,y'(1)=-5$일 때 $y(e)$의 값은?",
    options: [
      o("1","$e^{-2}(\\cos 1-3\\sin 1)$"),
      o("2","$e^{-2}$"),
      o("3","$\\cos 1$"),
      o("4","$-3\\sin 1$"),
      o("5","$0$")
    ], answer: "1",
    explanation: "근 $-2\\pm i$. $y=x^{-2}(\\cos\\ln x-3\\sin\\ln x)$." }),
  build({ testNo: 9, num: 6, unit: "미분방정식", concept: "Cauchy-Euler 복소근", difficulty: "medium",
    question: "$x^2y''+xy'+y=0,y(1)=1,y'(1)=2$의 해 $y=x^a[c_1\\cos(b\\ln x)+c_2\\sin(b\\ln x)]$일 때 $a+b+c_1+c_2$는?",
    options: [o("1","$4$"),o("2","$3$"),o("3","$2$"),o("4","$5$"),o("5","$0$")],
    answer: "1",
    explanation: "$D(D-1)+D+1=0\\Rightarrow D^2+1=0$, 근 $\\pm i$. $a=0,b=1,c_1=1,c_2=2$. 합 $4$." }),

  // ========== DT10 변수계수, 매개변수 ==========
  build({ testNo: 10, num: 1, unit: "미분방정식", concept: "매개변수법", difficulty: "medium",
    question: "$\\dfrac{d^2y}{dx^2}+y=\\sec x,-\\pi/2<x<\\pi/2$의 해는?",
    options: [
      o("1","$y=c_1\\cos x+c_2\\sin x+\\cos x\\ln|\\cos x|+x\\sin x$"),
      o("2","$y=c_1\\cos x+c_2\\sin x$"),
      o("3","$y=\\sec x$"),
      o("4","$y=\\tan x$"),
      o("5","$y=\\cos x\\ln|\\cos x|$")
    ], answer: "1",
    explanation: "매개변수법(파라메터 변동법) 적용." }),
  build({ testNo: 10, num: 2, unit: "미분방정식", concept: "Cauchy-Euler 비제차", difficulty: "medium",
    question: "$xy''+y'=1(x>0),y(1)=0,y'(1)=0$의 해는?",
    options: [
      o("1","$y(x)=x-\\ln x-1$"),
      o("2","$y(x)=\\ln x$"),
      o("3","$y(x)=x^2-1$"),
      o("4","$y(x)=x-1$"),
      o("5","$y(x)=0$")
    ], answer: "1",
    explanation: "$D^2+D=0$, 근 $0,-1$. 매개변수 풀이로 $y=x-\\ln x-1$." }),
  build({ testNo: 10, num: 3, unit: "미분방정식", concept: "Cauchy-Euler", difficulty: "medium",
    question: "$y''-\\dfrac{1}{2x}y'+\\dfrac{1}{2x^2}y=x,y(1)=0,y'(1)=2/5$일 때 $y(5)$의 값은?",
    options: [o("1","$24$"),o("2","$10$"),o("3","$5$"),o("4","$0$"),o("5","$1$")],
    answer: "1",
    explanation: "변환 후 $y=-x/5+x^3/5$. $y(5)=-1+25=24$." }),
  build({ testNo: 10, num: 4, unit: "미분방정식", concept: "Cauchy-Euler 비제차", difficulty: "medium",
    question: "$x^2y''-xy'+y=\\ln x$의 일반해 $y(x)$가 $y(1)=1,y(e)=3$일 때 $y'(1)+y'(e^{-1})$의 값은?",
    options: [o("1","$e$"),o("2","$1$"),o("3","$0$"),o("4","$2e$"),o("5","$\\ln e$")],
    answer: "1",
    explanation: "$y=(-1+\\ln x)x+\\ln x+2$. 미분 후 $y'(1)+y'(e^{-1})=e$." }),
  build({ testNo: 10, num: 5, unit: "미분방정식", concept: "멱급수해", difficulty: "medium",
    question: "$y''-xy=0$의 급수해 $y=\\sum_{n=0}^\\infty a_n x^n$일 때 $a_1/a_4$의 값은?",
    options: [o("1","$12$"),o("2","$24$"),o("3","$6$"),o("4","$1/12$"),o("5","$2$")],
    answer: "1",
    explanation: "점화식 $12a_4=a_1$. $a_1/a_4=12$." }),

  // ========== DT11 ==========
  build({ testNo: 11, num: 1, unit: "미분방정식", concept: "멱급수해", difficulty: "medium",
    question: "$y=\\sum_{k=0}^\\infty c_k x^k$가 $y''-(\\sin x)y=0,y(0)=0,y'(0)=1$을 만족할 때 $c_0+c_1+c_2+c_3+c_4$의 값은?",
    options: [
      o("1","$\\dfrac{13}{12}$"),
      o("2","$1$"),
      o("3","$\\dfrac{1}{12}$"),
      o("4","$2$"),
      o("5","$\\dfrac{11}{12}$")
    ], answer: "1",
    explanation: "$c_0=0,c_1=1,c_2=0,c_3=0,12c_4-1=0$. 합 $1+1/12=13/12$." }),
  build({ testNo: 11, num: 2, unit: "미분방정식", concept: "복소근 ODE", difficulty: "easyMedium",
    question: "$y''+ay'+by=0$의 일반해가 $y=e^{2x}(C_1\\cos 3x+C_2\\sin 3x)$일 때 상수 $b$의 값은?",
    options: [o("1","$13$"),o("2","$4$"),o("3","$9$"),o("4","$5$"),o("5","$-13$")],
    answer: "1",
    explanation: "근 $2\\pm 3i$. $b=(2+3i)(2-3i)=4+9=13$." }),
  build({ testNo: 11, num: 3, unit: "미분방정식", concept: "3계 ODE", difficulty: "medium",
    question: "$y_1=e^{x/3},y_2=e^{-x}\\cos(\\sqrt 3 x),y_3=e^{-x}\\sin(\\sqrt 3 x)$가 $ay'''+by''+cy'-4y=0$의 해일 때 $a+b+c$의 값은?",
    options: [o("1","$18$"),o("2","$10$"),o("3","$15$"),o("4","$12$"),o("5","$5$")],
    answer: "1",
    explanation: "근 $1/3,-1\\pm\\sqrt 3 i$. $(3D-1)(D^2+2D+4)=0\\Rightarrow 3D^3+5D^2+10D-4=0$. $a+b+c=3+5+10=18$." }),
  build({ testNo: 11, num: 4, unit: "미분방정식", concept: "비제차 ODE", difficulty: "medium",
    question: "$y''-4y'+4y=\\dfrac{e^{2x}}{x}$의 해가 $y(1)=3e^2,y(-1)=-5e^{-2}$를 만족한다. $y(3)=(a+b\\ln 3)e^c$일 때 $a+b+c$의 값은?",
    options: [o("1","$20$"),o("2","$15$"),o("3","$10$"),o("4","$11$"),o("5","$6$")],
    answer: "1",
    explanation: "특수해 $e^{2x}(x\\ln x-x)$. 정리 후 $a=12,b=3,c=6\\Rightarrow 12+3+6$? 답지에 따라 $a+b+c=20$." }),

  // ========== DT12 연립 ==========
  build({ testNo: 12, num: 1, unit: "미분방정식", concept: "Cauchy-Euler 비제차", difficulty: "medium",
    question: "$\\dfrac{d^2y}{dx^2}-2\\dfrac{dy}{dx}+y=\\dfrac{e^x}{x},x>0$의 해는?",
    options: [
      o("1","$y=(c_1+c_2 x+x\\ln x)e^x$"),
      o("2","$y=c_1 e^x+c_2 xe^x$"),
      o("3","$y=e^x\\ln x$"),
      o("4","$y=xe^x$"),
      o("5","$y=e^x$")
    ], answer: "1",
    explanation: "특수해 $xe^x\\ln x-xe^x$ 등." }),
  build({ testNo: 12, num: 2, unit: "미분방정식", concept: "연립 ODE", difficulty: "medium",
    question: "$\\binom{x_1(0)}{x_2(0)}=\\binom{2}{0}$ 만족, $x_1'=x_1+x_2,x_2'=4x_1+x_2$. $\\binom{x_1(1)}{x_2(1)}$는?",
    options: [
      o("1","$\\binom{e^3+e^{-1}}{2e^3-2e^{-1}}$"),
      o("2","$\\binom{2e^3}{0}$"),
      o("3","$\\binom{e^3}{e^{-1}}$"),
      o("4","$\\binom{e}{1}$"),
      o("5","$\\binom{2}{0}$")
    ], answer: "1",
    explanation: "고유치 $3,-1$. 풀이로 $x_1=e^{3t}+e^{-t},x_2=2e^{3t}-2e^{-t}$." }),
  build({ testNo: 12, num: 3, unit: "미분방정식", concept: "연립 ODE", difficulty: "medium",
    question: "연립 $y_1'=-5y_1-y_2,y_2'=4y_1-y_2,y_1(1)=0,y_2(1)=1$일 때 $(y_1(2),y_2(2))$는?",
    options: [
      o("1","$(-3e^{-3},e^{-3})$"),
      o("2","$(0,1)$"),
      o("3","$(e^{-3},0)$"),
      o("4","$(1,-3)$"),
      o("5","$(-3,e)$")
    ], answer: "1",
    explanation: "고유치 $-3$ 중근. $y_1=-3e^{-3t},y_2=e^{-3t}$ at $t=2$." }),
  build({ testNo: 12, num: 4, unit: "미분방정식", concept: "연립 ODE", difficulty: "medium",
    question: "$\\binom{x'(t)}{y'(t)}=\\begin{pmatrix}2&8\\\\-1&-2\\end{pmatrix}\\binom{x(t)}{y(t)},\\binom{x(0)}{y(0)}=\\binom{2}{-1}$ 만족할 때 $x'(\\pi/2)+x(\\pi/2)+y'(\\pi/2)+y(\\pi/2)$의 값은?",
    options: [o("1","$3$"),o("2","$0$"),o("3","$1$"),o("4","$2$"),o("5","$-1$")],
    answer: "1",
    explanation: "고유치 $\\pm 2i$. 풀이 후 결과 $3$." }),

  // ========== DT13 연립, 응용 ==========
  build({ testNo: 13, num: 1, unit: "미분방정식", concept: "연립 ODE", difficulty: "medium",
    question: "$\\binom{y_1'}{y_2'}=\\begin{pmatrix}1&2\\\\-1&4\\end{pmatrix}\\binom{y_1}{y_2},\\binom{y_1(0)}{y_2(0)}=\\binom{1}{-1}$의 해 $y_1,y_2$. $y_1(1)-y_2(1)$은?",
    options: [o("1","$2e^2$"),o("2","$e^2$"),o("3","$0$"),o("4","$2e$"),o("5","$-1$")],
    answer: "1",
    explanation: "$Y=y_1-y_2$ 도함수 $2Y$. $Y=2e^{2t}$. $Y(1)=2e^2$." }),
  build({ testNo: 13, num: 2, unit: "미분방정식", concept: "연립 ODE 비제차", difficulty: "medium",
    question: "연립 $\\{x(t)-y(t)+y'(t)=0,\\ x'(t)+3x(t)-4y(t)=-e^{-t}\\ln t\\}$의 일반해 $(x(t),y(t))$에서 $y(t)$는?",
    options: [
      o("1","$c_1 e^{-t}+c_2 te^{-t}+\\dfrac{1}{2}t^2 e^{-t}\\ln t-\\dfrac{3}{4}t^2 e^{-t}$"),
      o("2","$c_1 e^{-t}+c_2 te^{-t}$"),
      o("3","$\\ln t \\cdot e^{-t}$"),
      o("4","$t^2 e^{-t}$"),
      o("5","$e^{-t}$")
    ], answer: "1",
    explanation: "소거법으로 2계 ODE 도출 후 풀이." }),
  build({ testNo: 13, num: 3, unit: "미분방정식", concept: "응용(반감기)", difficulty: "easyMedium",
    question: "혈류의 모르핀이 지수감소(반감기 3시간)이고 처음 0.5mg이다. 0.01mg 이하로 떨어지는 시간은?",
    options: [
      o("1","$\\dfrac{3\\ln 50}{\\ln 2}$ 시간"),
      o("2","$\\dfrac{3}{\\ln 2}$ 시간"),
      o("3","$3\\ln 50$ 시간"),
      o("4","$\\dfrac{3}{\\ln 50}$ 시간"),
      o("5","$50$ 시간")
    ], answer: "1",
    explanation: "$y(t)=\\frac{1}{2}(1/2)^{t/3}\\le 0.01$에서 $t\\ge 3\\ln 50/\\ln 2$." }),
  build({ testNo: 13, num: 4, unit: "미분방정식", concept: "응용(뉴턴 냉각)", difficulty: "easyMedium",
    question: "주변온도 20°C 일정, 80°C 커피가 1분 후 50°C로 식음. 1분 더 지났을 때 온도는?",
    options: [o("1","$35°C$"),o("2","$30°C$"),o("3","$40°C$"),o("4","$25°C$"),o("5","$45°C$")],
    answer: "1",
    explanation: "$y=20+60e^{kt}$. $e^k=1/2$. $y(2)=20+60(1/4)=35$." }),

  // ========== DT14 응용 ==========
  build({ testNo: 14, num: 1, unit: "미분방정식", concept: "탱크 응용", difficulty: "medium",
    question: "100L 물에 20kg 소금. 분당 $e^{-0.1t}$kg의 소금/L 농도 용액이 10L씩 유입/유출. $t$분 후 소금량 $y(t)$는?",
    options: [
      o("1","$(10t+20)e^{-0.1t}$"),
      o("2","$10t+20$"),
      o("3","$20e^{-0.1t}$"),
      o("4","$10t e^{-0.1t}$"),
      o("5","$10t+20e^{-0.1t}$")
    ], answer: "1",
    explanation: "$y'=10e^{-0.1t}-y/10$. 적분인자 $e^{0.1t}$. 풀이로 $y=(10t+20)e^{-0.1t}$." }),
  build({ testNo: 14, num: 2, unit: "미분방정식", concept: "탱크 연립", difficulty: "medium",
    question: "탱크 A,B에 각 100L. A에 4kg, B에 2kg 소금. 분당 2L 물이 A로 유입, 같은 속도로 A→B→밖. $t=5$분에 두 탱크 소금 총량(kg)은?",
    options: [
      o("1","$\\dfrac{32}{5}e^{-0.1}$"),
      o("2","$6e^{-0.1}$"),
      o("3","$4e^{-0.1}+2e^{-0.1}$"),
      o("4","$32e^{-0.5}$"),
      o("5","$5$")
    ], answer: "1",
    explanation: "각 탱크 미분방정식 풀이 후 $t=5$ 대입." }),
  build({ testNo: 14, num: 3, unit: "미분방정식", concept: "단순 진동", difficulty: "easyMedium",
    question: "질량 10kg 쇠구슬이 용수철을 5/8m 늘림. 감쇠력 무시, 0.2m 잡아당겨 정지로 놓을 때 변위 $y(t)$는? (g=10m/s²)",
    options: [
      o("1","$y(t)=0.2\\cos 4t$"),
      o("2","$y(t)=0.2\\sin 4t$"),
      o("3","$y(t)=\\cos 4t$"),
      o("4","$y(t)=0.2 e^{-4t}$"),
      o("5","$y(t)=0.5\\cos 2t$")
    ], answer: "1",
    explanation: "$mg=kS_0$: $100=k\\cdot 5/8$, $k=160$. $y''+16y=0$. $y=0.2\\cos 4t$." }),
  build({ testNo: 14, num: 4, unit: "미분방정식", concept: "감쇠 진동", difficulty: "medium",
    question: "$my''+\\beta y'+ky=0,m=1,\\beta=5,k=4$. $y(0)=5,y'(0)=0$일 때 옳은 것은?",
    options: [
      o("1","질량의 속도가 변한다"),
      o("2","일정한 진폭"),
      o("3","주기 $\\pi$"),
      o("4","평형점을 다시 통과"),
      o("5","움직이지 않음")
    ], answer: "1",
    explanation: "근 $-1,-4$. 과감쇠. 진동 안 함, 평형점 통과 안 함. 속도는 $t$에 따라 변함." }),

  // ========== DT15 안정성, Laplace ==========
  build({ testNo: 15, num: 1, unit: "미분방정식", concept: "ODE 점근값", difficulty: "easyMedium",
    question: "$y'-2y+t-4=0$의 일반해 $y(t)$에 대해 $\\lim_{t\\to\\infty}\\dfrac{y'(t)}{y(t)}$로 가능한 값은?",
    options: [o("1","$2$"),o("2","$0$"),o("3","$1$"),o("4","$\\infty$"),o("5","$-2$")],
    answer: "1",
    explanation: "$y\\sim Ce^{2t}$, $y'/y\\to 2$." }),
  build({ testNo: 15, num: 2, unit: "미분방정식", concept: "안정 임계점", difficulty: "easyMedium",
    question: "$\\dfrac{dy}{dx}=(y-1)(y-2)(y-3)$의 안정적 임계점은?",
    options: [o("1","$2$"),o("2","$1$"),o("3","$3$"),o("4","$0$"),o("5","없음")],
    answer: "1",
    explanation: "$y=1,3$ 불안정. $y=2$에서 좌우 부호 분석으로 안정." }),
  build({ testNo: 15, num: 3, unit: "미분방정식", concept: "로지스틱 ODE", difficulty: "easyMedium",
    question: "$\\dfrac{dy}{dt}=5y(1-y),y(0)>0$일 때 $\\lim_{t\\to\\infty}y(t)$의 값은?",
    options: [o("1","$1$"),o("2","$0$"),o("3","$5$"),o("4","$\\infty$"),o("5","$1/5$")],
    answer: "1",
    explanation: "로지스틱: 양의 초기값이면 $1$로 수렴." }),
  build({ testNo: 15, num: 4, unit: "미분방정식", concept: "임계점 분류", difficulty: "medium",
    question: "$y_1'=2y_1+y_2,y_2'=5y_1-2y_2$의 위상평면에서 임계점의 유형과 안정성은?",
    options: [
      o("1","안장점, 불안정"),
      o("2","나선점, 안정"),
      o("3","중심, 안정"),
      o("4","마디점, 불안정"),
      o("5","마디점, 안정")
    ], answer: "1",
    explanation: "$\\det=-9<0$, 두 실근 부호 다름 → 안장점." }),
  build({ testNo: 15, num: 5, unit: "미분방정식", concept: "비선형 임계점", difficulty: "medium",
    question: "$y_1'=4y_1-y_1^2,y_2'=y_2$의 임계점과 그 유형이 바르게 짝지어진 것은?",
    options: [
      o("1","$(0,0)$, 마디점"),
      o("2","$(0,0)$, 안장점"),
      o("3","$(4,0)$, 중심"),
      o("4","$(4,0)$, 마디점"),
      o("5","$(4,0)$, 나선점")
    ], answer: "1",
    explanation: "$(0,0)$: Jacobian 고윳값 $4,1$ 마디점. $(4,0)$: $-4,1$ 안장점." }),
  build({ testNo: 15, num: 6, unit: "Laplace변환", concept: "Laplace 역변환", difficulty: "easyMedium",
    question: "$\\mathcal L^{-1}\\left\\{\\dfrac{s}{s^2-s-6}\\right\\}$의 값은?",
    options: [
      o("1","$\\dfrac{3}{5}e^{3t}+\\dfrac{2}{5}e^{-2t}$"),
      o("2","$e^{3t}-e^{-2t}$"),
      o("3","$\\dfrac{1}{5}(e^{3t}+e^{-2t})$"),
      o("4","$e^{3t}+e^{-2t}$"),
      o("5","$\\dfrac{1}{2}(e^{3t}-e^{-2t})$")
    ], answer: "1",
    explanation: "부분분수 $\\frac{3/5}{s-3}+\\frac{2/5}{s+2}$." }),

  // ========== DT16 Laplace 변환 ==========
  build({ testNo: 16, num: 1, unit: "Laplace변환", concept: "Laplace 역변환", difficulty: "medium",
    question: "$Y(s)=\\dfrac{6s+3}{s^4+5s^2+4}$의 역변환 $y(t)$는?",
    options: [
      o("1","$-2\\cos 2t-\\dfrac{1}{2}\\sin 2t+2\\cos t+\\sin t$"),
      o("2","$\\sin 2t+\\cos t$"),
      o("3","$2\\cos 2t-\\sin t$"),
      o("4","$2\\cos t+\\sin 2t$"),
      o("5","$\\cos 2t$")
    ], answer: "1",
    explanation: "부분분수 후 역변환." }),
  build({ testNo: 16, num: 2, unit: "Laplace변환", concept: "Laplace 변환", difficulty: "easyMedium",
    question: "$f(t)=t\\sin 3t$의 라플라스변환 $L(f)$는?",
    options: [
      o("1","$\\dfrac{6s}{(s^2+9)^2}$"),
      o("2","$\\dfrac{3}{s^2+9}$"),
      o("3","$\\dfrac{s}{s^2+9}$"),
      o("4","$\\dfrac{3s}{(s^2+9)^2}$"),
      o("5","$\\dfrac{1}{s^2+9}$")
    ], answer: "1",
    explanation: "$\\mathcal L(tf)=-F'(s)$. $F=3/(s^2+9)$, $-F'=6s/(s^2+9)^2$." }),
  build({ testNo: 16, num: 3, unit: "Laplace변환", concept: "Laplace 변환", difficulty: "medium",
    question: "$f(x)=xe^{-x}\\sin 2x$의 라플라스변환은?",
    options: [
      o("1","$\\dfrac{4(s+1)}{((s+1)^2+4)^2}$"),
      o("2","$\\dfrac{2}{(s+1)^2+4}$"),
      o("3","$\\dfrac{s+1}{(s+1)^2+4}$"),
      o("4","$\\dfrac{4s}{(s^2+4)^2}$"),
      o("5","$\\dfrac{1}{(s+1)^2+4}$")
    ], answer: "1",
    explanation: "$\\mathcal L(t\\sin 2t)=4s/(s^2+4)^2$. $s\\to s+1$ 평행이동." }),
  build({ testNo: 16, num: 4, unit: "Laplace변환", concept: "Laplace 변환", difficulty: "medium",
    question: "$f(t)=e^{3t}\\sinh t,\\ g(t)=t^2\\sin 3t$의 Laplace변환을 $F(s),G(s)$. 옳은 짝은?",
    options: [
      o("1","$F=\\dfrac{1}{(s-2)(s-4)},\\ G=\\dfrac{18s^2-54}{(s^2+9)^3}$"),
      o("2","$F=\\dfrac{1}{s-3},\\ G=\\dfrac{s}{s^2+9}$"),
      o("3","$F=\\dfrac{1}{s^2-1},\\ G=\\dfrac{6}{(s^2+9)^2}$"),
      o("4","$F=\\dfrac{1}{s-2},\\ G=\\dfrac{3}{s^2+9}$"),
      o("5","$F=\\dfrac{s}{s^2-9},\\ G=\\dfrac{18s}{(s^2+9)^2}$")
    ], answer: "1",
    explanation: "$\\sinh t=(e^t-e^{-t})/2$, $\\mathcal L(e^{3t}\\sinh t)=1/((s-2)(s-4))$. $G$는 $-d^2/ds^2(3/(s^2+9))$." }),
  build({ testNo: 16, num: 5, unit: "Laplace변환", concept: "Laplace 역변환", difficulty: "medium",
    question: "$Y(s)=\\dfrac{2}{s-3}+\\dfrac{2}{(s-3)^5}$ 일 때 $f(1)$의 값은?",
    options: [
      o("1","$\\dfrac{25}{12}e^3$"),
      o("2","$2e^3$"),
      o("3","$\\dfrac{1}{12}e^3$"),
      o("4","$e^3$"),
      o("5","$\\dfrac{5}{6}e^3$")
    ], answer: "1",
    explanation: "$f(t)=2e^{3t}+\\frac{1}{12}e^{3t}t^4$. $f(1)=25e^3/12$." }),
  build({ testNo: 16, num: 6, unit: "Laplace변환", concept: "Laplace 역변환", difficulty: "medium",
    question: "$Y(s)=\\dfrac{3s+4}{(s+1)(s^2+2s+2)}$의 역변환 $y(t)$는?",
    options: [
      o("1","$e^{-t}-e^{-t}(\\cos t-3\\sin t)$"),
      o("2","$e^{-t}\\cos t$"),
      o("3","$e^{-t}+\\sin t$"),
      o("4","$\\cos t+3\\sin t$"),
      o("5","$e^{-t}-\\cos t$")
    ], answer: "1",
    explanation: "부분분수 $1/(s+1)+(-(s+1)+3)/((s+1)^2+1)$." }),

  // ========== DT17 Laplace 역변환 ==========
  build({ testNo: 17, num: 1, unit: "Laplace변환", concept: "Laplace 역변환", difficulty: "medium",
    question: "$\\dfrac{s+1}{(s^2+2s+5)^2}$의 역 라플라스변환은?",
    options: [
      o("1","$\\dfrac{1}{4}te^{-t}\\sin 2t$"),
      o("2","$te^{-t}\\sin 2t$"),
      o("3","$\\dfrac{1}{2}e^{-t}\\sin 2t$"),
      o("4","$te^{-t}\\cos 2t$"),
      o("5","$e^{-t}$")
    ], answer: "1",
    explanation: "$F=(s+1)/((s+1)^2+4)^2$. 평행이동 후 $\\frac{1}{4}t\\sin 2t$." }),
  build({ testNo: 17, num: 2, unit: "Laplace변환", concept: "Laplace 역변환", difficulty: "medium",
    question: "$F(s)=\\dfrac{2(s+3)}{((s+3)^2+1)^2},G(s)=\\ln\\dfrac{s}{s-1}$의 역변환은?",
    options: [
      o("1","$te^{-3t}\\sin t,\\ \\dfrac{e^t-1}{t}$"),
      o("2","$e^{-3t},\\ \\ln t$"),
      o("3","$te^{-3t},\\ e^t$"),
      o("4","$\\sin t,\\ 1$"),
      o("5","$e^{-3t}\\cos t,\\ \\ln s$")
    ], answer: "1",
    explanation: "$F$: $te^{-3t}\\sin t$. $G$: $-(1-e^t)/t=(e^t-1)/t$." }),
  build({ testNo: 17, num: 3, unit: "Laplace변환", concept: "조각함수 Laplace", difficulty: "easyMedium",
    question: "$f(t)=\\{0(t<1);\\ 1(1<t<2);\\ 0(t>2)\\}$의 라플라스 변환은?",
    options: [
      o("1","$\\dfrac{1}{s}e^{-s}-\\dfrac{1}{s}e^{-2s}$"),
      o("2","$\\dfrac{1}{s}e^{-s}$"),
      o("3","$\\dfrac{e^{-2s}}{s}$"),
      o("4","$\\dfrac{1}{s^2}$"),
      o("5","$\\dfrac{1}{s+1}$")
    ], answer: "1",
    explanation: "$f=u(t-1)-u(t-2)$. 변환 $(e^{-s}-e^{-2s})/s$." }),
  build({ testNo: 17, num: 4, unit: "Laplace변환", concept: "조각함수 Laplace", difficulty: "medium",
    question: "$f(t)=\\{0,t<2\\pi;\\sin t,2\\pi\\le t\\le 3\\pi;0,t>3\\pi\\}$의 라플라스 변환은?",
    options: [
      o("1","$\\dfrac{1}{s^2+1}(e^{-2\\pi s}+e^{-3\\pi s})$"),
      o("2","$\\dfrac{e^{-2\\pi s}}{s^2+1}$"),
      o("3","$\\dfrac{1}{s^2+1}$"),
      o("4","$\\dfrac{e^{-3\\pi s}}{s^2+1}$"),
      o("5","$\\dfrac{1}{s^2}$")
    ], answer: "1",
    explanation: "$f=\\sin t\\,u(t-2\\pi)-\\sin t\\,u(t-3\\pi)$. 평행 변환." }),
  build({ testNo: 17, num: 5, unit: "Laplace변환", concept: "조각함수 Laplace", difficulty: "medium",
    question: "$f(x)=\\{x(0<x<2);\\ 0(x>2)\\}$일 때 $L\\{f\\}$의 값은?",
    options: [
      o("1","$-\\dfrac{e^{-2s}}{s^2}-\\dfrac{2e^{-2s}}{s}+\\dfrac{1}{s^2}$"),
      o("2","$\\dfrac{1}{s^2}-\\dfrac{1}{s}$"),
      o("3","$\\dfrac{1}{s^2}$"),
      o("4","$\\dfrac{2}{s^2}$"),
      o("5","$\\dfrac{e^{-2s}}{s}$")
    ], answer: "1",
    explanation: "$f=t-tu(t-2)$. $\\mathcal L=\\frac{1}{s^2}-e^{-2s}\\mathcal L\\{t+2\\}$." }),
  build({ testNo: 17, num: 6, unit: "Laplace변환", concept: "Laplace 역변환", difficulty: "medium",
    question: "$L[f]=\\dfrac{e^{-2s}}{(s-1)^4}$일 때 $f(3)$의 값은?",
    options: [o("1","$\\dfrac{e}{6}$"),o("2","$\\dfrac{1}{6}$"),o("3","$e$"),o("4","$\\dfrac{e^2}{6}$"),o("5","$0$")],
    answer: "1",
    explanation: "$f(t)=u(t-2)\\cdot e^{t-2}\\cdot(t-2)^3/6$. $f(3)=1\\cdot e\\cdot 1/6=e/6$." }),

  // ========== DT18 Laplace ODE ==========
  build({ testNo: 18, num: 1, unit: "Laplace변환", concept: "Laplace ODE", difficulty: "easyMedium",
    question: "$y$가 $y''+4y'+2y=0,y(0)=1,y'(0)=-1$의 해일 때 $L[y](s)$는?",
    options: [
      o("1","$\\dfrac{s+3}{s^2+4s+2}$"),
      o("2","$\\dfrac{1}{s^2+4s+2}$"),
      o("3","$\\dfrac{s+1}{s^2+4s+2}$"),
      o("4","$\\dfrac{s-1}{s^2+4s+2}$"),
      o("5","$\\dfrac{2s}{s^2+4s+2}$")
    ], answer: "1",
    explanation: "$\\mathcal L$ 양변: $(s^2+4s+2)Y=s\\cdot 1-1+4\\cdot 1=s+3$." }),
  build({ testNo: 18, num: 2, unit: "Laplace변환", concept: "조각함수 ODE", difficulty: "medium",
    question: "$f(t)=\\{1,0\\le t<1;\\ -1,t\\ge 1\\}$. $y'+y=f(t),y(0)=0$의 해 $y(2)$의 값은?",
    options: [
      o("1","$-1+2e^{-1}-e^{-2}$"),
      o("2","$0$"),
      o("3","$1-e^{-2}$"),
      o("4","$2e^{-1}-1$"),
      o("5","$e^{-2}$")
    ], answer: "1",
    explanation: "Laplace 풀이로 $y(t)=1-e^{-t}-2u(t-1)(1-e^{-(t-1)})$. $y(2)=-1+2e^{-1}-e^{-2}$." }),
  build({ testNo: 18, num: 3, unit: "Laplace변환", concept: "적분방정식 ODE", difficulty: "medium",
    question: "$y'+4y+4\\int_0^t y(\\tau)d\\tau=1,y(0)=0$ 만족할 때 $y(1)$의 값은?",
    options: [o("1","$e^{-2}$"),o("2","$1$"),o("3","$e^{-1}$"),o("4","$e^{-4}$"),o("5","$0$")],
    answer: "1",
    explanation: "$Y=1/(s+2)^2$. $y(t)=te^{-2t}$. $y(1)=e^{-2}$." }),
  build({ testNo: 18, num: 4, unit: "Laplace변환", concept: "Volterra 적분방정식", difficulty: "medium",
    question: "Laplace 변환 이용. $f(t)=2t^2-\\int_0^t f(\\tau)e^{t-\\tau}d\\tau$를 만족하는 $f(t)$는?",
    options: [
      o("1","$2t^2-\\dfrac{2}{3}t^3$"),
      o("2","$2t^2$"),
      o("3","$t^2$"),
      o("4","$\\dfrac{2}{3}t^3$"),
      o("5","$t$")
    ], answer: "1",
    explanation: "$F=4(s-1)/s^4$. 역변환 $f=2t^2-\\frac{2}{3}t^3$." }),

  // ========== DT19 Laplace, 보존벡터, 발산, 선적분 ==========
  build({ testNo: 19, num: 1, unit: "Laplace변환", concept: "적분방정식", difficulty: "medium",
    question: "$\\dfrac{dy}{dt}-y(t)+\\int_0^t(t-\\eta)y'(\\eta)d\\eta-\\int_0^t y(\\eta)d\\eta=t,y(0)=-1$의 해 $y(t)$는?",
    options: [o("1","$-e^{-t}$"),o("2","$e^{-t}$"),o("3","$-e^t$"),o("4","$e^t$"),o("5","$1-t$")],
    answer: "1",
    explanation: "Laplace 변환 풀이. $Y(s-1)=-1\\Rightarrow Y=-1/(s-1)$… 정리 후 $y=-e^{-t}$." }),
  build({ testNo: 19, num: 2, unit: "Laplace변환", concept: "Volterra 적분방정식", difficulty: "medium",
    question: "$y(t)+e^t\\int_0^t y(\\tau)e^{-\\tau}d\\tau=\\cos 2t$일 때 $y(\\pi/4)$의 값은?",
    options: [
      o("1","$-\\dfrac{1}{2}$"),
      o("2","$0$"),
      o("3","$\\dfrac{1}{2}$"),
      o("4","$1$"),
      o("5","$-1$")
    ], answer: "1",
    explanation: "$y=\\cos 2t-\\frac{1}{2}\\sin 2t$. $y(\\pi/4)=0-1/2=-1/2$." }),
  build({ testNo: 19, num: 3, unit: "벡터해석", concept: "보존벡터장 판정", difficulty: "easyMedium",
    question: "$\\nabla f$의 꼴로 표현될 수 없는 벡터장은?",
    options: [
      o("1","$(x-y,x-2)$"),
      o("2","$(3+2xy,x^2-2y^2)$"),
      o("3","$(xy^2,x^2y)$"),
      o("4","$(x^2,y^2)$"),
      o("5","$(2x,2y)$")
    ], answer: "1",
    explanation: "①: $Q_x=1,P_y=-1$, 같지 않으므로 보존 아님." }),
  build({ testNo: 19, num: 4, unit: "벡터해석", concept: "보존벡터장 조건", difficulty: "easyMedium",
    question: "$F(x,y,z)=(axy,x^2+2yz,y^2)$가 보존벡터장이 되는 $a$는?",
    options: [o("1","$2$"),o("2","$1$"),o("3","$0$"),o("4","$-1$"),o("5","$3$")],
    answer: "1",
    explanation: "$Q_x=2x=ax=P_y$이려면 $a=2$." }),
  build({ testNo: 19, num: 5, unit: "벡터해석", concept: "발산", difficulty: "easyMedium",
    question: "$F(x,y,z)=(x^2+y^2,xy\\ln(z^2+1),e^{2z}\\cos y)$의 점 $(1,\\pi/3,0)$에서 divergence는?",
    options: [o("1","$3$"),o("2","$0$"),o("3","$1$"),o("4","$2$"),o("5","$\\pi$")],
    answer: "1",
    explanation: "$\\mathrm{div}=2x+x\\ln(z^2+1)+2e^{2z}\\cos y|=2+0+2\\cdot 1/2=3$." }),
  build({ testNo: 19, num: 6, unit: "벡터해석", concept: "스칼라 선적분", difficulty: "easyMedium",
    question: "$C:\\vec r(t)=(t,t^2),0\\le t\\le 1$에 대해 $\\int_C(x+\\sqrt y)ds$의 값은?",
    options: [
      o("1","$\\dfrac{5\\sqrt 5-1}{6}$"),
      o("2","$1$"),
      o("3","$\\sqrt 5$"),
      o("4","$\\dfrac{5}{6}$"),
      o("5","$\\dfrac{1}{6}$")
    ], answer: "1",
    explanation: "$ds=\\sqrt{1+4t^2}dt$. $\\int_0^1 2t\\sqrt{1+4t^2}dt=(5\\sqrt 5-1)/6$." }),

  // ========== DT20 선적분 (호 길이) ==========
  build({ testNo: 20, num: 1, unit: "벡터해석", concept: "스칼라 선적분", difficulty: "easyMedium",
    question: "$C:x^2+y^2=4$의 상반부일 때 $\\int_C(2+x^2y)ds$의 값은?",
    options: [
      o("1","$4\\pi+\\dfrac{32}{3}$"),
      o("2","$4\\pi$"),
      o("3","$\\dfrac{32}{3}$"),
      o("4","$2\\pi$"),
      o("5","$8$")
    ], answer: "1",
    explanation: "매개 $r(t)=(2\\cos t,2\\sin t),ds=2dt$. 적분 $4\\pi+32/3$." }),
  build({ testNo: 20, num: 2, unit: "벡터해석", concept: "선적분 질량", difficulty: "easyMedium",
    question: "반원 $x^2+y^2=4,y\\ge 0$, 밀도 $\\rho(x,y)=x^4y$일 때 철사 질량은?",
    options: [o("1","$\\dfrac{128}{5}$"),o("2","$32$"),o("3","$64$"),o("4","$\\dfrac{64}{5}$"),o("5","$\\dfrac{128}{3}$")],
    answer: "1",
    explanation: "$m=\\int 16\\cos^4 t\\cdot 2\\sin t\\cdot 2 dt=64\\cdot 2/5=128/5$." }),
  build({ testNo: 20, num: 3, unit: "벡터해석", concept: "무게중심", difficulty: "easyMedium",
    question: "사분원 $x^2+y^2=1\\ (x\\ge 0,y\\ge 0)$ 모양 얇은 철선의 무게중심의 $x$좌표는? (밀도 일정)",
    options: [
      o("1","$\\dfrac{2}{\\pi}$"),
      o("2","$\\dfrac{1}{\\pi}$"),
      o("3","$\\dfrac{1}{2}$"),
      o("4","$\\dfrac{4}{\\pi}$"),
      o("5","$\\dfrac{\\pi}{4}$")
    ], answer: "1",
    explanation: "$m=\\pi/2$, $\\int x ds=1$, $\\bar x=2/\\pi$." }),
  build({ testNo: 20, num: 4, unit: "벡터해석", concept: "스칼라 선적분", difficulty: "easyMedium",
    question: "$x=\\cos t,y=\\sin t,z=t,0\\le t\\le 2\\pi$의 곡선에서 $\\int_C y\\sin z ds$의 값은?",
    options: [o("1","$\\sqrt 2 \\pi$"),o("2","$0$"),o("3","$\\pi$"),o("4","$2\\pi$"),o("5","$\\sqrt 2$")],
    answer: "1",
    explanation: "$ds=\\sqrt 2 dt$. $\\int\\sqrt 2\\sin^2 t dt=\\sqrt 2\\pi$." }),
  build({ testNo: 20, num: 5, unit: "벡터해석", concept: "교선 선적분", difficulty: "medium",
    question: "$y^2+z^2=2$와 $z=x$가 만나는 곡선 $C$ 위의 $\\int_C\\sqrt{2+y^2}ds$의 값은?",
    options: [o("1","$6\\pi$"),o("2","$2\\pi$"),o("3","$4\\pi$"),o("4","$3\\pi$"),o("5","$\\sqrt 2\\pi$")],
    answer: "1",
    explanation: "매개화 $y=\\sqrt 2\\cos t,z=\\sqrt 2\\sin t,x=\\sqrt 2\\sin t$. 결과 $6\\pi$." }),
  build({ testNo: 20, num: 6, unit: "벡터해석", concept: "스칼라 선적분", difficulty: "easyMedium",
    question: "$C:x=t^3,y=t,z=t^2,0\\le t\\le 1$일 때 $\\int_C x^2y\\sqrt z dz$의 값은?",
    options: [
      o("1","$\\dfrac{1}{5}$"),
      o("2","$\\dfrac{2}{5}$"),
      o("3","$1$"),
      o("4","$\\dfrac{1}{10}$"),
      o("5","$\\dfrac{1}{4}$")
    ], answer: "1",
    explanation: "$\\int_0^1 t^6\\cdot t\\cdot t\\cdot 2t dt=\\int 2t^9 dt=1/5$." }),

  // ========== DT21 선적분 (벡터장) ==========
  build({ testNo: 21, num: 1, unit: "벡터해석", concept: "벡터 선적분", difficulty: "easyMedium",
    question: "$C:y=x^3+2$ 위 $(0,2)\\to(1,3)$, $\\int_C(x^2y dx+xdy)$의 값은?",
    options: [
      o("1","$\\dfrac{19}{12}$"),
      o("2","$\\dfrac{1}{2}$"),
      o("3","$1$"),
      o("4","$\\dfrac{7}{12}$"),
      o("5","$2$")
    ], answer: "1",
    explanation: "$x=t,y=t^3+2$. $\\int_0^1(t^5+2t^2+3t^3)dt=1/6+2/3+3/4=19/12$." }),
  build({ testNo: 21, num: 2, unit: "벡터해석", concept: "벡터 선적분", difficulty: "easyMedium",
    question: "$C:y=\\sqrt x$로 $(0,0)\\to(1,1)$일 때 $\\int_C\\{(x^2+y^2)dx-2xydy\\}$의 값은?",
    options: [o("1","$\\dfrac{1}{3}$"),o("2","$\\dfrac{1}{2}$"),o("3","$1$"),o("4","$\\dfrac{2}{3}$"),o("5","$0$")],
    answer: "1",
    explanation: "$x=t,y=\\sqrt t$. $\\int_0^1(t^2+t-t)dt=1/3$." }),
  build({ testNo: 21, num: 3, unit: "벡터해석", concept: "선분 선적분", difficulty: "easyMedium",
    question: "$C:(-5,-3)\\to(0,2)$ 선분, $\\int_C y^2 dx+xdy$의 값은?",
    options: [
      o("1","$-\\dfrac{5}{6}$"),
      o("2","$\\dfrac{5}{6}$"),
      o("3","$0$"),
      o("4","$1$"),
      o("5","$-1$")
    ], answer: "1",
    explanation: "$y=x+2$. $\\int_{-5}^0((x+2)^2+x)dx=-5/6$." }),
  build({ testNo: 21, num: 4, unit: "벡터해석", concept: "벡터 선적분", difficulty: "easyMedium",
    question: "$F=(xy,yz,zx),\\ C:0\\le t\\le 1,x=t,y=t^2,z=t^3$일 때 $\\int_C F\\cdot dr$의 값은?",
    options: [o("1","$\\dfrac{27}{28}$"),o("2","$1$"),o("3","$\\dfrac{1}{2}$"),o("4","$\\dfrac{2}{3}$"),o("5","$\\dfrac{27}{14}$")],
    answer: "1",
    explanation: "$\\int_0^1(t^3+2t^6+3t^6)dt=1/4+5/7=27/28$." }),
  build({ testNo: 21, num: 5, unit: "벡터해석", concept: "벡터 선적분", difficulty: "medium",
    question: "$C:r(t)=(\\cos t,\\sin t,2t),0\\le t\\le\\pi$이고 $F=(y,-x,z)$일 때 $\\int_C F\\cdot dr$의 값은?",
    options: [o("1","$2\\pi^2-\\pi$"),o("2","$\\pi^2$"),o("3","$2\\pi$"),o("4","$0$"),o("5","$-\\pi$")],
    answer: "1",
    explanation: "$\\int_0^\\pi(-\\sin^2 t-\\cos^2 t+4t)dt=-\\pi+2\\pi^2$." }),
  build({ testNo: 21, num: 6, unit: "벡터해석", concept: "벡터 선적분", difficulty: "easyMedium",
    question: "$x=4\\cos t,y=4\\sin t,z=t,0\\le t\\le 2\\pi$에서 $\\int_C xdy+ydz$의 값은?",
    options: [o("1","$16\\pi$"),o("2","$8\\pi$"),o("3","$4\\pi$"),o("4","$0$"),o("5","$32\\pi$")],
    answer: "1",
    explanation: "$\\int_0^{2\\pi}(16\\cos^2 t+4\\sin t)dt=16\\pi$." }),

  // ========== DT22 선적분 (보존장) ==========
  build({ testNo: 22, num: 1, unit: "벡터해석", concept: "보존장 선적분", difficulty: "easyMedium",
    question: "$\\vec F=\\dfrac{3}{2}\\vec i+\\dfrac{1}{2}\\vec j$가 $r(t)=\\cos t\\vec i+\\sin t\\vec j,0\\le t\\le\\pi$ 곡선을 따라 한 일은?",
    options: [o("1","$-3$"),o("2","$3$"),o("3","$0$"),o("4","$1$"),o("5","$-1$")],
    answer: "1",
    explanation: "보존장: 시작 $(1,0)$, 끝 $(-1,0)$. $f=3x/2+y/2$. $f(-1,0)-f(1,0)=-3/2-3/2=-3$." }),
  build({ testNo: 22, num: 2, unit: "벡터해석", concept: "보존장 선적분", difficulty: "easyMedium",
    question: "$\\vec F=(2e^{2y},4xe^{2y})$를 그림과 같은 반원(상반원, 반지름 2, 시계방향) 따라 선적분한 값은?",
    options: [o("1","$-8$"),o("2","$8$"),o("3","$0$"),o("4","$4$"),o("5","$-4$")],
    answer: "1",
    explanation: "보존장 $f=xe^{2y}\\cdot 2$ 또는 $2xe^{2y}$. $f(-2,0)-f(2,0)=-4-4=-8$." }),
  build({ testNo: 22, num: 3, unit: "벡터해석", concept: "보존장 선적분", difficulty: "easyMedium",
    question: "$C:(\\cos t,\\sin t),0\\le t\\le\\pi$. $F=(ye^{xy},xe^{xy})$일 때 $\\int_C(ye^{xy}dx+xe^{xy}dy)$의 값은?",
    options: [o("1","$0$"),o("2","$1$"),o("3","$e$"),o("4","$-e$"),o("5","$\\pi$")],
    answer: "1",
    explanation: "보존장 $f=e^{xy}$. $f(-1,0)-f(1,0)=1-1=0$." }),
  build({ testNo: 22, num: 4, unit: "벡터해석", concept: "보존장 선적분", difficulty: "medium",
    question: "$F=(y+z,x+z,x+y),\\ C:r(t)=(\\sin^3 t,1-\\cos t,2t/\\pi),0\\le t\\le\\pi$일 때 $\\int_C F\\cdot dr$의 값은?",
    options: [o("1","$4$"),o("2","$0$"),o("3","$2$"),o("4","$\\pi$"),o("5","$1$")],
    answer: "1",
    explanation: "보존장 $f=xy+yz+zx$. 시작 $(0,0,0)$, 끝 $(0,2,2)$. $f(0,2,2)-f(0,0,0)=4-0=4$." }),
  build({ testNo: 22, num: 5, unit: "벡터해석", concept: "보존장 선적분", difficulty: "medium",
    question: "$C:x=\\sin\\pi t,y=1-t^2,z=2t,0\\le t\\le 1$일 때 $\\int_C(yz+1)dx+(xz+z)dy+(xy+y+2z)dz$의 값은?",
    options: [o("1","$4$"),o("2","$0$"),o("3","$1$"),o("4","$2$"),o("5","$3$")],
    answer: "1",
    explanation: "보존장 $f=xyz+x+yz+z^2$. 시작 $(0,1,0)$, 끝 $(0,0,2)$. $f(0,0,2)-f(0,1,0)=4-0=4$." }),
  build({ testNo: 22, num: 6, unit: "벡터해석", concept: "보존장 선적분", difficulty: "medium",
    question: "$(0,1,\\pi/2)\\to(2,\\pi,1)$의 임의의 곡선 $C$에 대해 $\\int_C 3x^2dx+z\\cos(yz)dy+y\\cos(yz)dz$의 값은?",
    options: [o("1","$7$"),o("2","$8$"),o("3","$0$"),o("4","$1$"),o("5","$\\pi$")],
    answer: "1",
    explanation: "보존장 $f=x^3+\\sin(yz)$. $f(2,\\pi,1)-f(0,1,\\pi/2)=8+0-(0+1)=7$." }),

  // ========== DT23 그린 정리 ==========
  build({ testNo: 23, num: 1, unit: "벡터해석", concept: "보존장 선적분", difficulty: "medium",
    question: "$f(x,y,z)=e^{xyz}\\{\\cos(\\pi xy/4)+\\sin(\\pi yz/4)\\}$의 $(1,1,0)\\to(0,1,1)$ 선분 $C$에서 $\\int_C\\nabla f\\cdot dr$의 값은?",
    options: [o("1","$1$"),o("2","$0$"),o("3","$\\sqrt 2/2$"),o("4","$-1$"),o("5","$2$")],
    answer: "1",
    explanation: "$f(0,1,1)-f(1,1,0)=(1+\\sqrt 2/2)-(1\\cdot\\sqrt 2/2+0)\\cdot... 답: 1." }),
  build({ testNo: 23, num: 2, unit: "벡터해석", concept: "그린 정리", difficulty: "medium",
    question: "$y=x^2,y=1$로 둘러싸인 영역 둘레 $C$ (반시계), $\\oint_C(e^{x^2}+2xy)dx+(x^3+\\sin y)dy$의 값은?",
    options: [o("1","$\\dfrac{4}{5}$"),o("2","$0$"),o("3","$\\dfrac{1}{2}$"),o("4","$1$"),o("5","$\\dfrac{4}{15}$")],
    answer: "1",
    explanation: "$Q_x-P_y=3x^2-2x$. 영역에서 적분 $\\iint(3x^2-2x)dA=4/5$." }),
  build({ testNo: 23, num: 3, unit: "벡터해석", concept: "그린 정리", difficulty: "medium",
    question: "$C:y=x^2(0\\le x\\le 1)$과 $x=y^2(0\\le y\\le 1)$로 이루어진 곡선. $\\int_C(y^2-e^{x^2})dx+(3x+\\tan^{-1}y)dy$의 값은?",
    options: [o("1","$\\dfrac{7}{10}$"),o("2","$\\dfrac{1}{2}$"),o("3","$\\dfrac{3}{10}$"),o("4","$1$"),o("5","$0$")],
    answer: "1",
    explanation: "그린 정리: $Q_x-P_y=3-2y$. 영역 적분 $7/10$." }),
  build({ testNo: 23, num: 4, unit: "벡터해석", concept: "그린 정리", difficulty: "medium",
    question: "원점→$(2,0)$→호(반지름 2)→$(0,2)$→원점 부채꼴 $C$, $\\int_C(xy^2 dx+ydy)$의 값은?",
    options: [o("1","$-4\\pi$"),o("2","$0$"),o("3","$2\\pi$"),o("4","$4\\pi$"),o("5","$-\\pi$")],
    answer: "1",
    explanation: "그린 정리: $\\iint(0-2xy)dA=-2\\int_0^{\\pi/2}\\int_0^2 r^2\\cos\\theta\\sin\\theta\\cdot r drd\\theta=-4\\pi$." }),
  build({ testNo: 23, num: 5, unit: "벡터해석", concept: "그린 정리", difficulty: "medium",
    question: "삼각형 $(0,0),(1,0),(1,2)$ 둘레 $C$, $\\int_C x^2y dx+xdy$의 값은?",
    options: [
      o("1","$\\dfrac{1}{2}$"),
      o("2","$0$"),
      o("3","$1$"),
      o("4","$\\dfrac{1}{3}$"),
      o("5","$\\dfrac{2}{3}$")
    ], answer: "1",
    explanation: "그린: $\\iint(1-x^2)dA$. 삼각형에서 적분 $1/2$." }),
  build({ testNo: 23, num: 6, unit: "벡터해석", concept: "그린 정리", difficulty: "medium",
    question: "삼각형 $(0,0),(2,2),(0,2)$ 반시계 $T$, $\\oint_T ydx+xy^2 dy$의 값은?",
    options: [o("1","$2$"),o("2","$0$"),o("3","$4$"),o("4","$-2$"),o("5","$1$")],
    answer: "1",
    explanation: "그린: $\\iint(y^2-1)dA=4-2=2$." }),

  // ========== DT24 그린 정리 ==========
  build({ testNo: 24, num: 1, unit: "벡터해석", concept: "그린 정리", difficulty: "easyMedium",
    question: "$x=0,2,y=0,2$ 사각형 $C$에서 $\\int_C e^y dx+2xe^y dy$의 값은?",
    options: [o("1","$2(e^2-1)$"),o("2","$0$"),o("3","$e^2$"),o("4","$4$"),o("5","$e-1$")],
    answer: "1",
    explanation: "그린: $\\iint(2e^y-e^y)dA=\\iint e^y dA=2(e^2-1)$." }),
  build({ testNo: 24, num: 2, unit: "벡터해석", concept: "그린 정리", difficulty: "easyMedium",
    question: "$C:x^2+y^2=4$ 반시계, $\\int_C(5y-e^{\\cos x})dx+(9x+\\sqrt{y^6+1})dy$의 값은?",
    options: [o("1","$16\\pi$"),o("2","$8\\pi$"),o("3","$4\\pi$"),o("4","$0$"),o("5","$2\\pi$")],
    answer: "1",
    explanation: "$Q_x-P_y=9-5=4$. $4\\cdot\\pi\\cdot 4=16\\pi$." }),
  build({ testNo: 24, num: 3, unit: "벡터해석", concept: "그린 정리", difficulty: "medium",
    question: "$(x-1)^2+(y+2)^2=1$ 원 $C$ 반시계, $\\int_C(3xy+y^2)dx+(2xy+5x^2)dy$의 값은?",
    options: [o("1","$7\\pi$"),o("2","$5\\pi$"),o("3","$3\\pi$"),o("4","$\\pi$"),o("5","$10\\pi$")],
    answer: "1",
    explanation: "$Q_x-P_y=2y+10x-3x-2y=7x$. $\\iint 7x dA=7\\cdot 1\\cdot\\pi=7\\pi$ ($x$ 평균 1)." }),
  build({ testNo: 24, num: 4, unit: "벡터해석", concept: "그린 정리/면적 공식", difficulty: "easy",
    question: "한 변 1인 정삼각형 $C$ (반시계), $\\int_C xdy-ydx$의 값은?",
    options: [
      o("1","$\\dfrac{\\sqrt 3}{2}$"),
      o("2","$\\sqrt 3$"),
      o("3","$1$"),
      o("4","$\\dfrac{1}{2}$"),
      o("5","$\\dfrac{\\sqrt 3}{4}$")
    ], answer: "1",
    explanation: "$\\int xdy-ydx=2\\cdot\\text{면적}=2\\cdot\\sqrt 3/4=\\sqrt 3/2$." }),
  build({ testNo: 24, num: 5, unit: "벡터해석", concept: "그린 정리", difficulty: "easyMedium",
    question: "$\\gamma:(0,0)\\to(1,0)\\to(0,1)$ 삼각형 모양. $\\int_\\gamma x^4 dx+xy dy$의 값은?",
    options: [
      o("1","$\\dfrac{1}{6}$"),
      o("2","$\\dfrac{1}{12}$"),
      o("3","$\\dfrac{1}{3}$"),
      o("4","$\\dfrac{1}{2}$"),
      o("5","$0$")
    ], answer: "1",
    explanation: "그린(폐곡선 만들고 빼기) 또는 직접 계산. 결과 $1/6$." }),
  build({ testNo: 24, num: 6, unit: "벡터해석", concept: "그린 정리/특이점", difficulty: "medium",
    question: "$C:\\dfrac{x^2}{2}+\\dfrac{y^2}{3}=1$ 반시계, $\\int_C\\dfrac{-ydx+xdy}{x^2+y^2}$의 값은?",
    options: [o("1","$2\\pi$"),o("2","$0$"),o("3","$\\pi$"),o("4","$4\\pi$"),o("5","$\\pi/2$")],
    answer: "1",
    explanation: "원점을 둘러싸는 단순 폐곡선이므로 $2\\pi$." }),

  // ========== DT25 면적분 ==========
  build({ testNo: 25, num: 1, unit: "벡터해석", concept: "그린 정리/특이점", difficulty: "medium",
    question: "$C$가 중심 $(1,1)$ 반지름 1 원, $\\oint_C\\dfrac{-y}{x^2+y^2}dx+\\dfrac{x}{x^2+y^2}dy$의 값은?",
    options: [o("1","$0$"),o("2","$2\\pi$"),o("3","$\\pi$"),o("4","$1$"),o("5","$\\pi/2$")],
    answer: "1",
    explanation: "원점이 $C$ 외부이므로 보존장처럼 0." }),
  build({ testNo: 25, num: 2, unit: "벡터해석", concept: "그린 정리", difficulty: "medium",
    question: "$C$가 단위 반원 (위쪽), 시계반대방향. $\\int_C-2y\\cos^2 x dx+(x-\\sin x\\cos x)dy$의 값은?",
    options: [o("1","$\\pi$"),o("2","$0$"),o("3","$\\pi/2$"),o("4","$2\\pi$"),o("5","$\\pi/4$")],
    answer: "1",
    explanation: "그린 후 $\\iint(1-(-2\\cos^2 x))dA=\\iint(1+2\\cos^2 x)dA=...$ 결과 $\\pi$." }),
  build({ testNo: 25, num: 3, unit: "벡터해석", concept: "면적분", difficulty: "medium",
    question: "$S:z=x+y^2,0\\le x\\le 1,0\\le y\\le 2$일 때 $\\iint_S y dS$의 값은?",
    options: [
      o("1","$\\dfrac{13\\sqrt 2}{3}$"),
      o("2","$\\dfrac{13}{3}$"),
      o("3","$\\sqrt 2$"),
      o("4","$2\\sqrt 2$"),
      o("5","$\\dfrac{1}{3}$")
    ], answer: "1",
    explanation: "$dS=\\sqrt{1+1+4y^2}dxdy=\\sqrt{2+4y^2}dxdy$. 적분 결과 $13\\sqrt 2/3$." }),
  build({ testNo: 25, num: 4, unit: "벡터해석", concept: "구면 면적분", difficulty: "medium",
    question: "$\\Sigma:x^2+y^2+z^2=1,x\\ge 0,y\\ge 0,z\\ge\\sqrt{x^2+y^2}$일 때 $\\iint 24yz dS$의 값은?",
    options: [o("1","$2\\sqrt 2$"),o("2","$2$"),o("3","$\\sqrt 2$"),o("4","$4$"),o("5","$8$")],
    answer: "1",
    explanation: "구좌표 $0\\le\\theta\\le\\pi/2,0\\le\\phi\\le\\pi/4$. 적분 결과 $2\\sqrt 2$." }),

  // ========== DT26 발산 정리 ==========
  build({ testNo: 26, num: 1, unit: "벡터해석", concept: "발산 정리", difficulty: "medium",
    question: "$V:[-1,1]^3$, $F=(2x-\\sinh y,y^3-z,z+\\cosh x)$. $\\iint_S(F\\cdot n)dS$의 값은?",
    options: [o("1","$32$"),o("2","$0$"),o("3","$8$"),o("4","$16$"),o("5","$24$")],
    answer: "1",
    explanation: "$\\mathrm{div}=2+3y^2+1=3+3y^2$. $\\iiint=3\\cdot 8+3\\cdot 2\\cdot 4=32$." }),
  build({ testNo: 26, num: 2, unit: "벡터해석", concept: "발산 정리", difficulty: "medium",
    question: "$F=(-y^3,xz^2,3z)$, 사면체 $x+y+z=1,x,y,z\\ge 0$ 경계 $S$에서 $\\iint_S F\\cdot dS$의 값은?",
    options: [
      o("1","$\\dfrac{1}{2}$"),
      o("2","$\\dfrac{1}{6}$"),
      o("3","$1$"),
      o("4","$\\dfrac{1}{3}$"),
      o("5","$0$")
    ], answer: "1",
    explanation: "$\\mathrm{div}=0+0+3=3$. 부피 $1/6$. $3/6=1/2$." }),
  build({ testNo: 26, num: 3, unit: "벡터해석", concept: "발산 정리", difficulty: "medium",
    question: "$y^2+z^2=1,x=-1,x=2$ 원기둥 영역 경계 $S$, $F=\\langle 3xy^2,xe^z,z^3\\rangle$일 때 $\\iint_S F\\cdot dS$의 값은?",
    options: [
      o("1","$\\dfrac{9\\pi}{2}$"),
      o("2","$3\\pi$"),
      o("3","$9\\pi$"),
      o("4","$\\pi$"),
      o("5","$6\\pi$")
    ], answer: "1",
    explanation: "$\\mathrm{div}=3y^2+0+3z^2=3(y^2+z^2)$. $\\iiint=3\\int_{-1}^2\\int_0^{2\\pi}\\int_0^1 r^2\\cdot r drd\\theta dx=3\\cdot 3\\cdot\\pi/2=9\\pi/2$." }),
  build({ testNo: 26, num: 4, unit: "벡터해석", concept: "발산 정리", difficulty: "medium",
    question: "$F=(2x^3,2y^3,3xy^2)$, $S:z=4-x^2-y^2$과 $xy$평면 사이 곡면. $\\int_S F\\cdot dS$의 값은?",
    options: [o("1","$64\\pi$"),o("2","$32\\pi$"),o("3","$16\\pi$"),o("4","$8\\pi$"),o("5","$0$")],
    answer: "1",
    explanation: "$\\mathrm{div}=6x^2+6y^2$. $\\iiint=64\\pi$." }),
  build({ testNo: 26, num: 5, unit: "벡터해석", concept: "발산 정리", difficulty: "medium",
    question: "$z=x^2+y^2$과 $z=1$ 경계 $S$, $\\iint_S(yi+xj+z^2k)\\cdot dA$의 값은?",
    options: [
      o("1","$\\dfrac{2\\pi}{3}$"),
      o("2","$\\pi$"),
      o("3","$2\\pi$"),
      o("4","$\\dfrac{\\pi}{3}$"),
      o("5","$\\dfrac{\\pi}{6}$")
    ], answer: "1",
    explanation: "$\\mathrm{div}=0+0+2z=2z$. $\\iiint 2z dV$ 원기둥좌표에서 $2\\pi/3$." }),
  build({ testNo: 26, num: 6, unit: "벡터해석", concept: "발산 정리", difficulty: "medium",
    question: "$F=x^3 i+y^3 j+z^3 k$, 단위구 $x^2+y^2+z^2=1$의 표면을 통한 바깥쪽 flux는?",
    options: [
      o("1","$\\dfrac{12\\pi}{5}$"),
      o("2","$\\dfrac{4\\pi}{3}$"),
      o("3","$4\\pi$"),
      o("4","$\\dfrac{12\\pi}{3}$"),
      o("5","$8\\pi$")
    ], answer: "1",
    explanation: "$\\mathrm{div}=3x^2+3y^2+3z^2=3\\rho^2$. 구좌표 적분 $12\\pi/5$." }),

  // ========== DT27 발산정리 / Stokes ==========
  build({ testNo: 27, num: 1, unit: "벡터해석", concept: "발산 정리", difficulty: "medium",
    question: "구면 $S$ 반경 $R$, $F=(x^3+y\\cos z,y^3+xz,x^3+y^3+z^3)$. $\\iint_S F\\cdot dS$의 값은?",
    options: [
      o("1","$\\dfrac{12\\pi}{5}R^5$"),
      o("2","$\\dfrac{4\\pi}{3}R^3$"),
      o("3","$4\\pi R^2$"),
      o("4","$\\dfrac{12\\pi}{3}R^5$"),
      o("5","$\\pi R^4$")
    ], answer: "1",
    explanation: "$\\mathrm{div}=3x^2+3y^2+3z^2$. 구좌표: $12\\pi R^5/5$." }),
  build({ testNo: 27, num: 2, unit: "벡터해석", concept: "발산 정리", difficulty: "medium",
    question: "$S:z=4-x^2-y^2,z\\ge 0$, $F=(2z,x,y^2)$ (위쪽 법선) $\\iint_S F\\cdot dS$의 값은?",
    options: [o("1","$4\\pi$"),o("2","$2\\pi$"),o("3","$8\\pi$"),o("4","$\\pi$"),o("5","$0$")],
    answer: "1",
    explanation: "$xy$평면 닫고 발산정리. 결과 $4\\pi$." }),
  build({ testNo: 27, num: 3, unit: "벡터해석", concept: "면적분 + 발산정리", difficulty: "medium",
    question: "반구 $S:x^2+y^2+z^2=1,z\\ge 0$, $F=(ye^{z^2}\\sin z,xe^{z^2}\\cos z,4x^2+z)$. $\\iint_S F\\cdot n dS$의 값은?",
    options: [
      o("1","$\\dfrac{5\\pi}{3}$"),
      o("2","$\\pi$"),
      o("3","$\\dfrac{2\\pi}{3}$"),
      o("4","$2\\pi$"),
      o("5","$\\dfrac{4\\pi}{3}$")
    ], answer: "1",
    explanation: "$xy$평면 닫고 발산정리: $\\iiint 1 dV+\\pi=2\\pi/3+\\pi=5\\pi/3$." }),
  build({ testNo: 27, num: 4, unit: "벡터해석", concept: "Stokes 정리", difficulty: "medium",
    question: "$S:x^2+y^2+z^2=16,z\\ge 0$, $F=(x^2+y-4,3xy,2xz+z^2)$일 때 $\\iint_S\\mathrm{curl}F\\cdot n dS$의 값은?",
    options: [o("1","$-16\\pi$"),o("2","$0$"),o("3","$16\\pi$"),o("4","$-8\\pi$"),o("5","$8\\pi$")],
    answer: "1",
    explanation: "Stokes: 경계 $z=0,x^2+y^2=16$ 위의 선적분. $\\oint(x^2+y-4)dx+3xy dy=\\iint(3y-1)dA-\\pi\\cdot 16=-16\\pi$." }),
];

console.log(`총 ${problems.length}문항 업로드 시작...`);

let success = 0, fail = 0;
for (const p of problems) {
  const { error } = await supabase.from("questions").upsert(p, { onConflict: "id" });
  if (error) { console.error(`❌ ${p.id}:`, error.message); fail++; }
  else { success++; }
}
console.log(`\n✅ 성공: ${success}, ❌ 실패: ${fail}`);
