// 2021년 광운대 편입수학 객관식 30문항 (5지선다)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR="2021", SCHOOL_KO="광운대", SCHOOL_EN="kwangwoon";
const opts5 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:1, subject:"미분학", unit:"미분가능성", concept:"미분가능성 진위판단",
    difficulty:"medium",
    question:"다음 함수 중에서 점 $x=0$에서 미분 가능한 것은? (단, $\\mathbb{Q}$는 유리수의 집합)\n\nⓐ $f(x)=\\sqrt[3]{x}$\nⓑ $g(x)=x|x|$\nⓒ $h(x)=\\begin{cases}x&(x\\in\\mathbb{Q})\\\\0&(x\\notin\\mathbb{Q})\\end{cases}$\nⓓ $k(x)=\\begin{cases}x\\cos\\dfrac{1}{x}&(x\\ne 0)\\\\0&(x=0)\\end{cases}$",
    options:opts5("ⓐ","ⓑ","ⓐ, ⓑ","ⓐ, ⓒ","ⓑ, ⓓ"),
    correct:"2",
    explanation:"ⓐ $\\sqrt[3]{x}=x^{1/3}$, $1/3<1$이므로 미분 불가.\nⓑ $g(x)=\\begin{cases}-x^2&(x<0)\\\\x^2&(x\\ge 0)\\end{cases}$, $g'(0)=0$ (양쪽 일치) ⇒ 미분 가능.\nⓒ $h'(0)=\\lim_{a\\to 0}h(a)/a$: $a\\in\\mathbb{Q}$면 $1$, $a\\notin\\mathbb{Q}$면 $0$ ⇒ 미분 불가.\nⓓ $x\\cos(1/x)$ 형태는 $\\alpha>1$인 $x^\\alpha$ 필요. $\\alpha=1$이라 미분 불가.\n옳은 것은 ⓑ.",
  },
  {n:2, subject:"미분학", unit:"도함수 응용", concept:"로그함수 단조성",
    difficulty:"medium",
    question:"$a>1$일 때 다음 함수에 대한 설명 중 옳은 것은?\n$$f(x)=\\log_a(\\log_{a^2}x)-\\log_{a^2}(\\log_a x)$$",
    options:opts5("증가함수이다.","감소함수이다.","극솟값만 갖는다.","극댓값만 갖는다.","정의역은 $x>a$이다."),
    correct:"1",
    explanation:"정의역: $\\log_a x>0\\Leftrightarrow x>1$.\n$f(x)=\\dfrac{\\ln(\\frac{\\ln x}{2\\ln a})}{\\ln a}-\\dfrac{\\ln(\\ln x/\\ln a)}{2\\ln a}$. 정리하면 $f(x)=\\dfrac{1}{2}\\ln(\\ln x)+\\text{상수}$.\n$f'(x)=\\dfrac{1}{2x\\ln a\\cdot\\ln x}>0$ (정의역 $x>1$)이므로 단조 증가. 임계점 없음.",
  },
  {n:3, subject:"다변수함수", unit:"음함수와 편미분", concept:"음함수 2계 도함수",
    difficulty:"medium",
    question:"방정식 $x^4+y^4=2$가 변수 $y$를 $x$의 음함수로 정의할 때, 점 $(1,1)$에서 이계도함수 $y''$의 값은?",
    options:opts5("$-13$","$-11$","$-6$","$0$","$3$"),
    correct:"3",
    explanation:"1계: $y'=-\\dfrac{x^3}{y^3}\\bigg|_{(1,1)}=-1$.\n2계: $y''=-\\dfrac{3x^2 y^3-x^3\\cdot 3y^2 y'}{y^6}\\bigg|_{(1,1)}=-\\dfrac{3-3\\cdot(-1)}{1}=-6$.",
  },
  {n:4, subject:"미분학", unit:"도함수", concept:"분수함수 거듭제곱 미분",
    difficulty:"medium",
    question:"양의 실수 $m$에 대하여 함수 $f(x)=\\!\\left(\\dfrac{1+x}{1-x}\\right)^m$의 도함수가 $f'(x)=ax^b(1+x)^c(1-x)^d$일 때, 실수 $a+b+c+d$의 합은?",
    options:opts5("$0$","$-2m-2$","$-2m-1$","$2m-2$","$4m$"),
    correct:"4",
    explanation:"$m=2$ 검증: $f(x)=(1+x)^2(1-x)^{-2}$. $f'(x)=2(1+x)(1-x)^{-2}+(1+x)^2\\cdot 2(1-x)^{-3}$\n$=2(1+x)(1-x)^{-3}[(1-x)+(1+x)]=4(1+x)(1-x)^{-3}=4x^0(1+x)^1(1-x)^{-3}$.\n$a=4,\\,b=0,\\,c=1,\\,d=-3$. $a+b+c+d=2=2m-2$ ✓.",
  },
  {n:5, subject:"다변수함수", unit:"극좌표와 극곡선", concept:"극곡선 접선의 방정식",
    difficulty:"medium",
    question:"극좌표로 정의된 곡선 $r=1+2\\sin\\theta$에 있는 점 $\\!\\left(2,\\dfrac{\\pi}{6}\\right)$에서의 접선의 방정식은?",
    options:opts5("$y=3\\sqrt{3}\\,x-8$","$y=3\\sqrt{3}\\,x+\\dfrac{\\pi}{6}-9$","$y=\\dfrac{\\sqrt{3}}{4}x-\\dfrac{5}{2}$","$y=\\dfrac{3\\sqrt{3}}{2}x-\\dfrac{7}{2}$","$y=\\dfrac{3\\sqrt{3}}{2}x+\\dfrac{\\pi}{6}-3\\sqrt{3}$"),
    correct:"1",
    explanation:"한 점: $x=r\\cos\\theta=2\\cos(\\pi/6)=\\sqrt{3}$, $y=r\\sin\\theta=2\\sin(\\pi/6)=1$.\n극좌표 접선: $\\tan\\alpha=\\dfrac{\\tan\\theta+\\tan\\phi}{1-\\tan\\theta\\tan\\phi}$, $\\tan\\phi=r/r'$.\n$\\theta=\\pi/6$: $\\tan\\theta=1/\\sqrt{3}$. $r'=2\\cos\\theta$, $\\tan\\phi=\\dfrac{1+2\\sin\\theta}{2\\cos\\theta}\\big|_{\\pi/6}=\\dfrac{2}{\\sqrt{3}}$.\n$\\tan\\alpha=\\dfrac{1/\\sqrt{3}+2/\\sqrt{3}}{1-(1/\\sqrt{3})(2/\\sqrt{3})}=\\dfrac{3/\\sqrt{3}}{1/3}=3\\sqrt{3}$.\n접선: $y-1=3\\sqrt{3}(x-\\sqrt{3})\\Rightarrow y=3\\sqrt{3}\\,x-8$.",
  },
  {n:6, subject:"적분학", unit:"테일러급수", concept:"선형근사 오차 한계",
    difficulty:"medium",
    question:"닫힌 구간 $[1,1.1]$에서 함수 $f(x)=\\sqrt{1+x^2}$의 근삿값을 $x=1$에서의 선형 근사 함수를 이용하여 찾을 때, 근삿값의 오차 한계는?",
    options:opts5("$\\dfrac{\\sqrt{2}}{1600}$","$\\dfrac{1}{1200}$","$\\dfrac{\\sqrt{2}}{1000}$","$\\dfrac{1}{900}$","$\\dfrac{\\sqrt{2}}{800}$"),
    correct:"5",
    explanation:"오차한계 $|R_2(x)|=\\!\\left|\\dfrac{1}{2!}f''(k)(x-1)^2\\right|$ ($1\\le k\\le 1.1$).\n$f'(x)=x(1+x^2)^{-1/2}$, $f''(x)=(1+x^2)^{-3/2}$. 최대 $k=1$, $x=1.1$: $\\dfrac{1}{2}\\cdot\\dfrac{1}{2\\sqrt{2}}\\cdot(0.1)^2=\\dfrac{\\sqrt{2}}{800}$.",
  },
  {n:7, subject:"미분학", unit:"도함수 응용", concept:"중간값 정리 + 코사인 합",
    difficulty:"medium",
    question:"열린 구간 $(0,1)$에서 다음 방정식의 실수해가 적어도 한 개 있도록 하는 자연수 $k$의 최솟값과 최댓값의 합은?\n$$\\sum_{n=0}^{2021}\\cos\\dfrac{n\\pi x}{2}-k=0$$",
    options:opts5("$2019$","$2020$","$2021$","$2022$","$2023$"),
    correct:"5",
    explanation:"$f(x)=\\sum_{n=0}^{2021}\\cos\\dfrac{n\\pi x}{2}-k$.\n$f(0)=2022-k$, $f(1)=\\sum_{n=0}^{2021}\\cos(n\\pi/2)-k=1-k$ (4 주기 합 $=0$, 나머지 1).\n중간값 정리: $f(0)f(1)<0\\Rightarrow(2022-k)(1-k)<0\\Rightarrow 1<k<2022$.\n자연수 $k$: 최소 $2$, 최대 $2021$. 합 $=2023$.",
  },
  {n:8, subject:"미분학", unit:"미분가능성", concept:"$x^n\\sin(1/x^k)$ 도함수 연속",
    difficulty:"medium",
    question:"다음 함수 $f(x)$의 도함수 $f'(x)$가 모든 실수에서 연속이기 위한 최소 자연수 $n$은?\n$$f(x)=\\begin{cases}x^n\\sin\\dfrac{1}{x^{2021}}&(x\\ne 0)\\\\0&(x=0)\\end{cases}$$",
    options:opts5("$2019$","$2020$","$2021$","$2022$","$2023$"),
    correct:"5",
    explanation:"$x=0$에서 미분가능 조건 $n>1$.\n$f'(x)=nx^{n-1}\\sin(1/x^{2021})-2021x^{n-2022}\\cos(1/x^{2021})$ ($x\\ne 0$), $f'(0)=0$.\n$\\lim_{x\\to 0}f'(x)$ 존재 ↔ $\\lim_{x\\to 0}x^{n-2022}\\cos(1/x^{2021})=0$ ↔ $n-2022>0$ ↔ $n>2022$.\n최소 자연수 $n=2023$.",
  },
  {n:9, subject:"적분학", unit:"정적분의 응용", concept:"성망형(astroid) 길이",
    difficulty:"easy",
    question:"$a$가 양의 실수일 때 곡선 $\\sqrt[3]{x^2}+\\sqrt[3]{y^2}=\\sqrt[3]{a^2}$의 길이는?",
    options:opts5("$a$","$\\dfrac{2}{3}a$","$4a$","$6a$","$12a$"),
    correct:"4",
    explanation:"$x^{2/3}+y^{2/3}=a^{2/3}$ (성망형/astroid). 표준 길이 공식: $L=6a$.",
  },
  {n:10, subject:"적분학", unit:"테일러급수", concept:"멱급수 합 함수의 최솟값",
    difficulty:"medium",
    question:"함수 $f(x)=\\displaystyle\\sum_{n=1}^{\\infty}n^2 x^n$ ($|x|<1$)가 최솟값을 가지는 $x$의 값은?",
    options:opts5("$1-\\sqrt{2}$","$-1+\\sqrt{2}$","$0$","$2-\\sqrt{3}$","$-2+\\sqrt{3}$"),
    correct:"5",
    explanation:"$\\sum n^2 x^n=\\dfrac{x(1+x)}{(1-x)^3}$.\n$f'(x)=\\dfrac{(1+2x)(1-x)^3+3(x+x^2)(1-x)^2}{(1-x)^6}=\\dfrac{x^2+4x+1}{(1-x)^4}$.\n$x^2+4x+1=0\\Rightarrow x=-2\\pm\\sqrt{3}$. 정의역 $|x|<1$이므로 $x=-2+\\sqrt{3}$ ⇒ 극소 (최소).",
  },
  {n:11, subject:"적분학", unit:"테일러급수", concept:"매클로린 + n계 도함수",
    difficulty:"medium",
    question:"함수 $f(x)=e^{-x}\\sin x+x\\cos x$에서 $f^{(5)}(0)$은?",
    options:opts5("$0$","$1$","$\\dfrac{1}{6}$","$\\dfrac{1}{24}$","$\\dfrac{1}{120}$"),
    correct:"2",
    explanation:"$e^{-x}\\sin x=\\!\\left(1-x+\\dfrac{x^2}{2!}-\\cdots\\right)\\!\\left(x-\\dfrac{x^3}{3!}+\\dfrac{x^5}{5!}-\\cdots\\right)$.\n$x^5$ 계수 $=\\dfrac{1}{5!}-\\dfrac{1}{2!\\cdot 3!}+\\dfrac{1}{4!}$, $x\\cos x$의 $x^5$ 계수 $=\\dfrac{1}{4!}$.\n총 $x^5$ 계수 $\\times 5!=\\!\\left(\\dfrac{1}{120}-\\dfrac{1}{12}+\\dfrac{1}{24}+\\dfrac{1}{24}\\right)\\cdot 120=1-10+5+5=1$.",
  },
  {n:12, subject:"미분학", unit:"미분방정식", concept:"연립 ODE",
    difficulty:"medium",
    question:"두 함수 $f(x)$와 $g(x)$가 다음 관계를 만족시킬 때, $f(\\ln 2)g(\\ln 2)$의 값은?\n$$f'(x)=-g(x),\\quad g'(x)=-f(x),\\quad f(0)=3,\\,g(0)=1$$",
    options:opts5("$-3$","$1$","$3$","$2e^{-1}+e$","$4e^{-2}-e^2$"),
    correct:"1",
    explanation:"$f''(x)=-g'(x)=f(x)\\Rightarrow f''-f=0$. $f(x)=Ae^x+Be^{-x}$.\n$f(0)=A+B=3$, $f'(0)=-g(0)=-1=A-B$. $A=1,\\,B=2$. $f(x)=e^x+2e^{-x}$.\n$g(x)=-f'(x)=-e^x+2e^{-x}$.\n$f(\\ln 2)=2+1=3$, $g(\\ln 2)=-2+1=-1$. 곱 $=-3$.",
  },
  {n:13, subject:"다변수함수", unit:"공간곡선", concept:"사이클로이드 (곡률·접선·길이)",
    difficulty:"medium",
    question:"$a>0$에 대하여 매개변수 $\\theta$로 나타낸 곡선 $x=a(\\theta-\\sin\\theta),\\,y=a(1-\\cos\\theta)$에 대한 다음 설명 중 옳은 것을 모두 고르면?\n\nⓐ $\\theta=\\dfrac{\\pi}{3}$에서 $\\dfrac{dy}{dx}=\\dfrac{\\sqrt{3}}{3}$이다.\nⓑ $\\theta=\\dfrac{\\pi}{3}$에서 곡률은 $\\dfrac{1}{2a}$이다.\nⓒ $\\theta=\\dfrac{\\pi}{2}$에 대응하는 점에서 접선방정식은 $y=x+a\\!\\left(2-\\dfrac{\\pi}{2}\\right)$이다.\nⓓ $\\theta=0$에서 $\\theta=\\dfrac{\\pi}{2}$까지의 길이는 $2a$이다.",
    options:opts5("ⓐ, ⓑ","ⓐ, ⓒ","ⓑ, ⓒ","ⓒ, ⓓ","ⓑ, ⓒ, ⓓ"),
    correct:"3",
    explanation:"ⓐ [거짓] $\\dfrac{dy}{dx}=\\dfrac{\\sin\\theta}{1-\\cos\\theta}\\big|_{\\pi/3}=\\sqrt{3}$.\nⓑ [참] $\\kappa=\\dfrac{1}{2a\\sqrt{2-2\\cos\\theta}}\\big|_{\\pi/3}=\\dfrac{1}{2a}$.\nⓒ [참] $\\theta=\\pi/2$: 점 $(a(\\pi/2-1),a)$, 기울기 $1$ ⇒ $y=x+a(2-\\pi/2)$.\nⓓ [거짓] $L=\\!\\int_0^{\\pi/2}a\\sqrt{2-2\\cos\\theta}\\,d\\theta=4a(1-\\sqrt{2}/2)$.\n옳은 것: ⓑ, ⓒ.",
  },
  {n:14, subject:"적분학", unit:"급수의 수렴/발산", concept:"멱급수 수렴반경 비교",
    difficulty:"medium",
    question:"다음 멱급수 중에서 수렴 반지름이 가장 작은 것은?",
    options:opts5("$\\displaystyle\\sum_{n=0}^{\\infty}(-1)^n x^{2n}$","$\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{(-2)^n}{\\sqrt{n}}x^n$","$\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{(2n)!}{(n!)^2}x^n$","$\\displaystyle\\sum_{n=1}^{\\infty}\\tan\\!\\left(\\dfrac{1}{n}\\right)x^n$","$\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{(-1)^{n+1}}{n}(x-1)^n$"),
    correct:"3",
    explanation:"수렴반경: (1) $1$, (2) $1/2$, (3) $\\dfrac{1}{2^2}=1/4$ (∵ 비율 $\\dfrac{(2n+2)(2n+1)}{(n+1)^2}\\to 4$), (4) $1$ (∵ $\\tan(1/n)\\sim 1/n$), (5) $1$.\n가장 작음: (3) $R=1/4$.",
  },
  {n:15, subject:"적분학", unit:"부정적분", concept:"적분식 만족 함수 (부분적분)",
    difficulty:"medium",
    question:"함수 $f(x)$가 다음 식을 만족시킬 때 $f(e)$의 값은?\n$$\\int_1^x(t+1)e^t\\ln t\\,dt=e^x f(x)+e$$",
    options:opts5("$e+2$","$e+1$","$e$","$e-1$","$e-2$"),
    correct:"4",
    explanation:"부분적분 ($u=\\ln t,\\,dv=(t+1)e^t dt$): $v=te^t$이므로 좌변 $=[te^t\\ln t]_1^x-\\!\\int_1^x e^t\\,dt=xe^x\\ln x-e^x+e$.\n$xe^x\\ln x-e^x+e=e^x f(x)+e\\Rightarrow f(x)=x\\ln x-1$.\n$f(e)=e\\cdot 1-1=e-1$.",
  },
  {n:16, subject:"적분학", unit:"이상적분", concept:"적분 부등식 (자연수 a, b)",
    difficulty:"medium",
    question:"다음 조건을 만족하는 두 자연수 $a$와 $b$의 곱은?\n\nⓐ $a$는 $\\displaystyle\\lim_{t\\to\\infty}t^2\\!\\int_0^1\\dfrac{dx}{x^3+t^a}=0$을 만족하는 최소 자연수이다.\nⓑ $b$는 부등식 $\\displaystyle\\int_0^1\\sqrt{1-x^4}\\,dx\\le b\\!\\int_0^1\\sqrt{1-x^2}\\,dx$를 만족하는 최소 자연수이다.",
    options:opts5("$4$","$5$","$6$","$8$","$12$"),
    correct:"3",
    explanation:"ⓐ 극한 $\\sim\\!\\int_0^1\\dfrac{t^2}{x^3+t^a}dx$. $a=2$: $\\!\\int_0^1\\dfrac{t^2}{x^3+t^2}dx\\to 1$ (발산). $a=3$: $\\!\\int_0^1\\dfrac{t^2}{x^3+t^3}dx\\to 0$. ⇒ $a=3$.\nⓑ $\\sqrt{1-x^4}\\le\\sqrt{2}\\sqrt{1-x^2}$이지만 자연수 $b\\ge\\sqrt{2}$ 최소 $b=2$.\n$ab=6$.",
  },
  {n:17, subject:"미분학", unit:"도함수", concept:"$\\ln x/x$의 n계 도함수",
    difficulty:"hard",
    question:"함수 $f(x)=\\dfrac{\\ln x}{x}$의 $n$계 도함수가 $f^{(n)}(x)=\\dfrac{a_n+b_n\\ln x}{x^{n+1}}$일 때, $a_{n+1}+b_{n+1}+(n+1)(a_n+b_n)$의 값은? (단, 모든 자연수 $n$에 대해 $a_n$과 $b_n$은 실수)",
    options:opts5("$n!$","$(-1)^n n!$","$1$","$(n+1)!$","$(-1)^{n+1}(n+1)!$"),
    correct:"2",
    explanation:"$n=1$: $f'(x)=\\dfrac{1-\\ln x}{x^2}$. $a_1=1,\\,b_1=-1$.\n$n=2$: $f''(x)=\\dfrac{-3+2\\ln x}{x^3}$. $a_2=-3,\\,b_2=2$.\n목표 $n=1$: $a_2+b_2+2(a_1+b_1)=-3+2+2(0)=-1=(-1)^1\\cdot 1!$. \n선택지에서 $n=1$을 만족: (2) $(-1)^n n!=-1$ ✓.",
  },
  {n:18, subject:"적분학", unit:"급수의 수렴/발산", concept:"급수 수렴/발산 진위판단",
    difficulty:"medium",
    question:"다음 중 수렴하는 것을 모두 고르면?\n\nⓐ $\\displaystyle\\sum_{n=1}^{\\infty}(-1)^n\\dfrac{n}{1+n^2}$\nⓑ $\\displaystyle\\sum_{n=2}^{\\infty}\\dfrac{1}{n\\sqrt{\\ln n}}$\nⓒ $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{n!}{n^n}$",
    options:opts5("ⓒ","ⓐ, ⓑ","ⓐ, ⓒ","ⓑ, ⓒ","ⓐ, ⓑ, ⓒ"),
    correct:"3",
    explanation:"ⓐ [수렴] 교대급수, $n/(1+n^2)\\to 0$ 단조감소.\nⓑ [발산] 적분판정법: $\\!\\int\\dfrac{dx}{x\\sqrt{\\ln x}}=2\\sqrt{\\ln x}\\to\\infty$.\nⓒ [수렴] $\\dfrac{n!}{n^n}\\sim\\dfrac{1}{n^n}\\cdot n!\\le\\dfrac{1}{n^2}$ (실은 $n!/n^n\\le n!/n^2$가 아니지만 비율 판정 $\\dfrac{(n+1)!/(n+1)^{n+1}}{n!/n^n}=\\!\\left(\\dfrac{n}{n+1}\\right)^n\\to 1/e<1$ ⇒ 수렴).\n수렴: ⓐ, ⓒ.",
  },
  {n:19, subject:"다변수함수", unit:"공간곡면", concept:"곡면-평면 최단거리 (그래디언트)",
    difficulty:"medium",
    question:"다음 곡면과 평면 사이의 최단 거리는?\n$$3x^2+2y^2-6z=0,\\quad 2x+2y-z-6=0$$",
    options:opts5("$1$","$\\dfrac{1}{2}$","$\\dfrac{1}{3}$","$\\dfrac{1}{4}$","$\\dfrac{1}{5}$"),
    correct:"3",
    explanation:"곡면 위 평면과 평행한 접점: $\\nabla F=(6x,4y,-6)\\parallel(2,2,-1)$.\n$(6x,4y,-6)=t(2,2,-1)\\Rightarrow t=6,\\,x=2,\\,y=3$. 곡면식에 대입: $z=(12+18)/6=5$. 점 $(2,3,5)$.\n평면과의 거리: $\\dfrac{|4+6-5-6|}{\\sqrt{4+4+1}}=\\dfrac{1}{3}$.",
  },
  {n:20, subject:"다변수함수", unit:"다변수 극값", concept:"제약영역 최대·최솟값",
    difficulty:"medium",
    question:"세 직선 $x=0,\\,y=0,\\,y=-x+6$으로 둘러싸인 $xy$ 평면도형에서 함수 $f(x,y)=3+4x+2y-x^2-y^2$의 최댓값과 최솟값의 차는?",
    options:opts5("$12$","$16$","$17$","$28$","$29$"),
    correct:"5",
    explanation:"$f(x,y)=3+4x+2y-x^2-y^2$. $-x^2+4x-y^2+2y+3=-(x-2)^2-(y-1)^2+8$.\n원 $(x-2)^2+(y-1)^2=r^2$로 두면 $f=8-r^2$. 영역 내 $f$: $r$ 작을수록 큼.\n최댓값: 중심 $(2,1)$이 영역 내부에 있으므로 $f_{\\max}=8$.\n최솟값: 영역 꼭짓점 $(0,6)$에서 $r=\\sqrt{4+25}=\\sqrt{29}$가 최대, $f_{\\min}=8-29=-21$.\n차 $=8-(-21)=29$.",
  },
  {n:21, subject:"다변수함수", unit:"편미분", concept:"분수형 편미분 진위",
    difficulty:"medium",
    question:"다음 함수에 대한 설명으로 옳은 것은?\n$$f(x,y)=\\begin{cases}\\dfrac{xy(x^2-y^2)}{x^2+y^2}&((x,y)\\ne(0,0))\\\\0&((x,y)=(0,0))\\end{cases}$$",
    options:opts5("원점에서 불연속이다.","원점에서 미분 불가능이다.","$f_x(0,y)=y$","$f_y(x,0)=x$","$f_{xy}(0,0)=f_{yx}(0,0)$"),
    correct:"4",
    explanation:"(1) [거짓] 4차/2차 비율 ⇒ $f\\to 0$, 연속.\n(2) [거짓] $|f|\\le|xy|\\sqrt{x^2+y^2}$로 미분가능.\n(3) [거짓] $f_x(0,y)=\\!\\lim_{h\\to 0}\\dfrac{hy(h^2-y^2)/(h^2+y^2)}{h}=\\dfrac{-y^3}{y^2}=-y$.\n(4) [참] $f_y(x,0)=\\!\\lim_{h\\to 0}\\dfrac{xh(x^2-h^2)/(x^2+h^2)}{h}=\\dfrac{x^3}{x^2}=x$.\n(5) [거짓] $f_{xy}(0,0)=-1,\\,f_{yx}(0,0)=1$.",
  },
  {n:22, subject:"미분학", unit:"역삼각·역쌍곡함수", concept:"역삼각·역쌍곡 항등식 진위",
    difficulty:"medium",
    question:"다음 중 옳은 것은 모두 몇 개인가?\n\nⓐ $\\dfrac{d}{dx}\\sec^{-1}x=\\dfrac{1}{x\\sqrt{x^2+1}}$\nⓑ $\\sin^{-1}x+\\cos^{-1}x=\\pi$\nⓒ $\\tan^{-1}\\!\\left(\\dfrac{1}{2}\\right)+\\tan^{-1}\\!\\left(-\\dfrac{1}{3}\\right)=\\tan^{-1}\\!\\left(\\dfrac{1}{6}\\right)$\nⓓ $\\displaystyle\\lim_{h\\to 0}\\dfrac{\\sinh^{-1}h}{h}=0$",
    options:opts5("$0$개","$1$개","$2$개","$3$개","$4$개"),
    correct:"1",
    explanation:"ⓐ [거짓] $\\dfrac{d}{dx}\\sec^{-1}x=\\dfrac{1}{|x|\\sqrt{x^2-1}}$.\nⓑ [거짓] 합 $=\\pi/2$.\nⓒ [거짓] $\\tan^{-1}(1/2)+\\tan^{-1}(-1/3)=\\tan^{-1}\\!\\dfrac{1/2-1/3}{1+(1/2)(1/3)\\cdot(-1)}$... 실제 $\\tan^{-1}\\!\\left(\\dfrac{1}{2}-\\dfrac{1}{3}\\right)\\!\\!\\!$... 합공식: $\\tan^{-1}(1/7)\\ne\\tan^{-1}(1/6)$.\nⓓ [거짓] 극한 $=1$.\n참 0개.",
  },
  {n:23, subject:"다변수함수", unit:"이중적분", concept:"매개변수 적분 (n=3 대입)",
    difficulty:"hard",
    question:"함수 $f(x,y)=n(n-1)(y-x)^{n-2}$ ($n>2$)에 대해 다음 이중 적분의 값은?\n$$\\iint_\\Omega(x+y)f(x,y)\\,dxdy,\\quad\\Omega=\\{(x,y)\\mid 0\\le x\\le y\\le 1\\}$$",
    options:opts5("$\\dfrac{1}{n+1}$","$\\dfrac{1}{n-1}$","$\\dfrac{1}{n(n-1)}$","$1$","$n(n-1)$"),
    correct:"4",
    explanation:"$n=3$ 대입: $f=6(y-x)$. $\\!\\iint_\\Omega 6(x+y)(y-x)\\,dA=6\\!\\iint_\\Omega(y^2-x^2)\\,dA$.\n$=6\\!\\int_0^1\\!\\!\\int_x^1(y^2-x^2)\\,dy\\,dx=6\\!\\int_0^1\\!\\!\\left[\\dfrac{1}{3}-x^2-\\dfrac{x^3}{3}+x^3\\right]dx$\n$=6\\!\\left[\\dfrac{1}{3}-\\dfrac{1}{3}+\\dfrac{2}{12}\\right]=6\\cdot\\dfrac{1}{6}=1$.",
  },
  {n:24, subject:"적분학", unit:"정적분", concept:"극한 + 적분 (균등수렴)",
    difficulty:"medium",
    question:"$\\displaystyle\\lim_{n\\to\\infty}\\!\\int_0^1\\dfrac{dx}{1+x^n}$의 값은?",
    options:opts5("$0$","$1$","$2$","$\\dfrac{1}{e}$","$e^2$"),
    correct:"2",
    explanation:"$0<x<1$이면 $x^n\\to 0$ ⇒ $1/(1+x^n)\\to 1$ (균등수렴).\n$\\!\\int_0^1 1\\,dx=1$.",
  },
  {n:25, subject:"선형대수", unit:"선형변환", concept:"선형변환 (선형결합)",
    difficulty:"easy",
    question:"일차 변환 $T:\\mathbb{R}^3\\to\\mathbb{R}$이 $T(1,1,1)=3,\\,T(-2,1,0)=1,\\,T(1,0,0)=-2$를 만족시킬 때 $T(1,2,2)$는?",
    options:opts5("$-6$","$-2$","$2$","$4$","$8$"),
    correct:"5",
    explanation:"$(1,2,2)=2(1,1,1)-(1,0,0)$: $2-1=1$, $2-0=2$, $2-0=2$ ✓.\n$T(1,2,2)=2T(1,1,1)-T(1,0,0)=2\\cdot 3-(-2)=8$.",
  },
  {n:26, subject:"미분학", unit:"도함수 응용", concept:"임계점 + 정적분 (출제오류)",
    difficulty:"hard",
    question:"함수 $f(x)=\\dfrac{(x-e^x)x}{e^{2x}}$가 $x=a$에서 최솟값을 가질 때, $\\displaystyle\\int_0^a f(x)e^x\\,dx$의 값은?",
    options:opts5("$1-\\dfrac{2}{e}$","$\\dfrac{1}{2}-\\dfrac{2}{e}$","$1$","$\\dfrac{2}{e}-\\dfrac{1}{2}$","$\\dfrac{2}{e}-1$"),
    correct:"5",
    explanation:"$f'(x)=\\dfrac{(x-1)(e^x-2x)}{e^{2x}}$. $e^x>2x$ 항상 ⇒ 임계점 $x=1$ (극소). $a=1$.\n$\\!\\int_0^1 f(x)e^x\\,dx=\\!\\int_0^1\\dfrac{(x-e^x)x}{e^x}\\,dx=\\!\\int_0^1(x^2 e^{-x}-x)\\,dx=\\!\\left[-(x^2+2x+2)e^{-x}\\right]_0^1-\\dfrac{1}{2}=2-\\dfrac{5}{e}-\\dfrac{1}{2}=\\dfrac{3}{2}-\\dfrac{5}{e}$.\n[주의] 계산값 $\\dfrac{3}{2}-\\dfrac{5}{e}\\approx-0.34$가 객관식 어디에도 없음 (출제 오류). 가장 가까운 (5) $\\dfrac{2}{e}-1\\approx-0.26$로 처리.",
  },
  {n:27, subject:"선형대수", unit:"행렬식", concept:"역행렬 행렬식",
    difficulty:"medium",
    question:"다음 행렬 $A$의 역행렬 $A^{-1}$의 행렬식 $\\det(A^{-1})$은?\n$$A=\\begin{pmatrix}1&-1&-1&1\\\\-1&1&3&1\\\\-3&1&-1&1\\\\1&3&1&-1\\end{pmatrix}$$",
    options:opts5("$\\dfrac{1}{48}$","$\\dfrac{1}{24}$","$\\dfrac{1}{8}$","$-24$","$-48$"),
    correct:"1",
    explanation:"행축약으로 $|A|=48$.\n$\\det(A^{-1})=\\dfrac{1}{|A|}=\\dfrac{1}{48}$.",
  },
  {n:28, subject:"선형대수", unit:"고유치와 대각화", concept:"행렬 거듭제곱 (M=A³)",
    difficulty:"hard",
    question:"다음 행렬 $M$에 대하여 $M=A^3$을 만족하는 행렬 $A$의 모든 성분의 합은?\n$$M=\\begin{pmatrix}8&24&0\\\\0&8&12\\\\0&0&8\\end{pmatrix}$$",
    options:opts5("$6$","$8$","$10$","$12$","$24$"),
    correct:"2",
    explanation:"$M$이 상삼각, 대각이 모두 $8$. $A$도 상삼각, 대각 모두 $2$ (∵ $2^3=8$).\n$A=\\begin{pmatrix}2&a&b\\\\0&2&c\\\\0&0&2\\end{pmatrix}$. $A^2=\\begin{pmatrix}4&4a&4b+ac\\\\0&4&4c\\\\0&0&4\\end{pmatrix}$.\n$A^3=A^2 A=\\begin{pmatrix}8&12a&12b+6ac\\\\0&8&12c\\\\0&0&8\\end{pmatrix}=M$.\n$12a=24\\Rightarrow a=2$. $12c=12\\Rightarrow c=1$. $12b+6\\cdot 2\\cdot 1=0\\Rightarrow b=-1$.\n성분 합 $=2\\cdot 3+a+b+c=6+2-1+1=8$.",
  },
  {n:29, subject:"다변수함수", unit:"이중적분", concept:"변수변환 (자코비안)",
    difficulty:"medium",
    question:"$\\Omega=\\!\\left\\{(x,y)\\mid\\sqrt{x/a}+\\sqrt{y/b}\\le 1,\\,x\\ge 0,\\,y\\ge 0\\right\\}$ ($a>0,\\,b>0$)에 대하여 $\\displaystyle\\iint_\\Omega x\\,dxdy$의 값은?",
    options:opts5("$\\dfrac{a^2 b}{30}$","$\\dfrac{ab^2}{30}$","$\\dfrac{a^2 b}{20}$","$\\dfrac{ab^2}{20}$","$\\dfrac{ab}{10}$"),
    correct:"1",
    explanation:"$\\sqrt{x}=\\sqrt{a}X,\\,\\sqrt{y}=\\sqrt{b}Y$로 치환: $x=aX^2,\\,y=bY^2$, $\\Omega^*=\\{X+Y\\le 1,\\,X,Y\\ge 0\\}$. $dxdy=4abXY\\,dXdY$.\n$\\!\\iint x\\,dA=\\!\\iint aX^2\\cdot 4abXY\\,dXdY=4a^2 b\\!\\iint X^3 Y\\,dXdY$.\n$=4a^2 b\\!\\int_0^1\\!\\!\\int_0^{1-X}X^3 Y\\,dY\\,dX=2a^2 b\\!\\int_0^1 X^3(1-X)^2\\,dX=2a^2 b\\!\\left(\\dfrac{1}{4}-\\dfrac{2}{5}+\\dfrac{1}{6}\\right)=\\dfrac{a^2 b}{30}$.",
  },
  {n:30, subject:"다변수함수", unit:"삼중적분", concept:"구면 대칭 (구면좌표)",
    difficulty:"medium",
    question:"집합 $Q=\\{(x,y,z)\\mid x^2+y^2+z^2\\le 1\\}$에 대하여 $\\displaystyle\\iiint_Q(2x^2+4y^2+3z^2)\\,dxdydz$의 값은?",
    options:opts5("$\\dfrac{\\pi}{5}$","$\\dfrac{8\\pi}{5}$","$2\\pi$","$\\dfrac{12\\pi}{5}$","$\\dfrac{14\\pi}{5}$"),
    correct:"4",
    explanation:"대칭성: $\\!\\iiint x^2=\\!\\iiint y^2=\\!\\iiint z^2$.\n준식 $=(2+4+3)\\!\\iiint z^2\\,dV=9\\!\\int_0^{2\\pi}\\!\\!\\int_0^{\\pi}\\!\\!\\int_0^1\\rho^4\\cos^2\\phi\\sin\\phi\\,d\\rho\\,d\\phi\\,d\\theta$\n$=9\\cdot 2\\pi\\cdot\\dfrac{2}{3}\\cdot\\dfrac{1}{5}=\\dfrac{12\\pi}{5}$.",
  },
];

const TOTAL=PROBLEMS.length;
console.log(`총 ${TOTAL}문제 (객관식) 준비됨`);

const rows = PROBLEMS.map(p => {
  const id = `q-${YEAR}-${SCHOOL_EN}-${String(p.n).padStart(2,"0")}`;
  return {
    id, subject: p.subject, unit: p.unit, concept: p.concept, difficulty: p.difficulty,
    source_type: "imported", pool: "general", question: p.question, content_type: "latex",
    question_image: null, question_type: "multiple_choice",
    options: p.options, correct_option_id: p.correct,
    answer_text: null, explanation: p.explanation, explanation_content_type: "latex",
    explanation_image: null,
    tags: [YEAR, SCHOOL_KO, "past_exam", p.subject, p.unit, p.concept],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  };
});

const { data, error } = await sb.from("questions").upsert(rows, { onConflict: "id" }).select("id");
if (error) { console.error("업로드 실패:", error); process.exit(1); }
console.log(`업로드 완료: ${data.length}건`);
