// 2021년 성균관대 편입수학 객관식 20문항 (원 26~45번을 1~20으로 매핑, 5지선다)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR="2021", SCHOOL_KO="성균관대", SCHOOL_EN="skku";
const opts5 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:1, subject:"적분학", unit:"극좌표와 응용", concept:"극곡선 면적",
    difficulty:"medium",
    question:"곡선 $r=2\\cos\\theta$의 내부와 곡선 $r=1$의 외부의 공통부분 면적은?",
    options:opts5("$\\dfrac{\\sqrt 3}{4}+\\dfrac{\\pi}{6}$","$\\dfrac{1}{2}+\\dfrac{\\pi}{6}$","$\\dfrac{\\sqrt 3}{2}+\\dfrac{\\pi}{6}$","$\\dfrac{1}{2}+\\dfrac{\\pi}{3}$","$\\dfrac{\\sqrt 3}{2}+\\dfrac{\\pi}{3}$"),
    correct:"5",
    explanation:"교점: $2\\cos\\theta=1\\Rightarrow\\theta=\\pm\\pi/3$. 공통부분 = (큰 원호 영역) - (작은 원호 영역) 분할.\n$A=2\\!\\left[\\dfrac{1}{2}\\!\\int_0^{\\pi/3}(2\\cos\\theta)^2 d\\theta-\\dfrac{1}{2}\\!\\int_0^{\\pi/3}1\\,d\\theta\\right]\\cdot$ (대칭). 정확히 계산하면 $\\dfrac{\\sqrt 3}{2}+\\dfrac{\\pi}{3}$.",
  },
  {n:2, subject:"선형대수", unit:"고유치와 대각화", concept:"확률행렬 극한",
    difficulty:"medium",
    question:"행렬 $A=\\begin{bmatrix}0.9&0.2\\\\0.1&0.8\\end{bmatrix}$에 대해 $\\displaystyle\\lim_{k\\to\\infty}A^k$를 구하면?",
    options:opts5("$\\dfrac{1}{6}\\begin{bmatrix}0&0\\\\1&2\\end{bmatrix}$","$\\dfrac{1}{5}\\begin{bmatrix}2&1\\\\1&2\\end{bmatrix}$","$\\dfrac{1}{4}\\begin{bmatrix}0&0\\\\1&2\\end{bmatrix}$","$\\dfrac{1}{3}\\begin{bmatrix}2&2\\\\1&1\\end{bmatrix}$","$\\dfrac{1}{2}\\begin{bmatrix}0&1\\\\0&2\\end{bmatrix}$"),
    correct:"4",
    explanation:"$A$는 확률행렬, 고윳값 $1,\\,0.7$. 극한은 $\\lambda=1$ 고유공간으로의 정사영.\n정상상태 벡터 $v=(2/3,1/3)^T$ 기준으로 $A^{\\infty}=\\dfrac{1}{3}\\begin{bmatrix}2&2\\\\1&1\\end{bmatrix}$.",
  },
  {n:3, subject:"다변수함수", unit:"중적분", concept:"적분 순서 변경",
    difficulty:"medium",
    question:"$\\displaystyle\\int_{-2}^{0}\\!\\!\\int_{-x}^{2}e^{y^2}\\,dy\\,dx$의 값은?",
    options:opts5("$\\dfrac{1}{2}(e^4-1)$","$\\dfrac{1}{3}(e^4-1)$","$\\dfrac{1}{4}(e^4-1)$","$e^4-2$","$e^4-1$"),
    correct:"1",
    explanation:"순서 변경. 영역 $\\{-2\\le x\\le 0,\\,-x\\le y\\le 2\\}=\\{0\\le y\\le 2,\\,-y\\le x\\le 0\\}$.\n$\\displaystyle\\int_0^2\\!\\!\\int_{-y}^0 e^{y^2}dx\\,dy=\\int_0^2 y e^{y^2}dy=\\dfrac{1}{2}(e^4-1)$.",
  },
  {n:4, subject:"공학수학", unit:"미분방정식", concept:"방향장(가우시안 해)",
    difficulty:"easy",
    question:"다음 미분방정식의 해의 형태로 적합한 것은?\n$\\dfrac{dy}{dx}=-2xy$",
    options:opts5("진동하는 함수","증가하는 단조함수","두 봉우리가 있는 함수","종모양(가우시안)의 함수","위로 열린 포물선"),
    correct:"4",
    explanation:"분리: $\\dfrac{dy}{y}=-2x\\,dx\\Rightarrow\\ln|y|=-x^2+C\\Rightarrow y=Ae^{-x^2}$. 가우시안 종 모양.",
  },
  {n:5, subject:"선형대수", unit:"행렬", concept:"행렬 성질 진위",
    difficulty:"medium",
    question:"실수 성분을 갖는 $n\\times n$ 행렬 $A$ ($n\\ge 2$)에 대하여 다음 중 옳지 <u>않은</u> 것은?\n(1) $A$가 대칭행렬일 때 $A$의 고윳값은 항상 실수이다.\n(2) $A=\\begin{bmatrix}1&2&3\\\\0&0&0\\\\0&0&0\\end{bmatrix}$의 영공간(Null Space)은 1차원이다.\n(3) $A$가 대칭행렬일 때 $A$는 항상 대각화 가능하다.\n(4) 방정식 $Ax=b$가 해를 가진다고 할 때 $b$는 $A$의 열공간(Column Space)에 속하는 벡터이다.\n(5) $A$가 가역행렬일 때 방정식 $Ax=0$은 자명해(Trivial Solution)만을 가진다.",
    options:opts5("(1)","(2)","(3)","(4)","(5)"),
    correct:"2",
    explanation:"(2) 거짓: rank=1이므로 nullity=$3-1=2$차원, 1차원이 아님.\n(1)(3) 대칭행렬 스펙트럼 정리. (4) 정의. (5) 가역 ⇔ $\\ker=\\{0\\}$.",
  },
  {n:6, subject:"선형대수", unit:"벡터공간", concept:"정사영 표준행렬 고유값",
    difficulty:"medium",
    question:"벡터공간 $\\mathbb R^2$에서 벡터 $a\\in\\mathbb R^2$에 의해 생성되는 부분공간을 $W$라고 하자. 선형변환 $T:\\mathbb R^2\\to\\mathbb R^2$가 $W$로의 직교 사영(orthogonal projection)일 때 $T$의 표준행렬(standard matrix)의 고윳값(eigenvalue)에 대한 설명으로 옳은 것은?",
    options:opts5("고윳값은 $1$로 대수적중복도(algebraic multiplicity)는 $2$이다.","고윳값은 $0$으로 대수적중복도는 $2$이다.","고윳값은 $1$과 $0$이다.","고윳값은 $1$과 $2$이다.","고윳값은 $T$에 따라 다르다."),
    correct:"3",
    explanation:"정사영 $T$는 $W$ 위에서 항등 (고윳값 1), $W^{\\perp}$ 위에서 영 (고윳값 0). 고윳값 $1,\\,0$.",
  },
  {n:7, subject:"다변수함수", unit:"삼중적분과 극좌표계", concept:"구면좌표",
    difficulty:"medium",
    question:"$\\displaystyle\\int_0^2\\!\\!\\int_0^{\\sqrt{4-x^2}}\\!\\!\\int_0^{\\sqrt{4-x^2-y^2}}\\dfrac{1}{\\sqrt{x^2+y^2+z^2}}\\,dz\\,dy\\,dx$의 값은?",
    options:opts5("$\\dfrac{1}{2}\\pi$","$\\pi$","$\\dfrac{3}{2}\\pi$","$2\\pi$","$\\dfrac{5}{2}\\pi$"),
    correct:"2",
    explanation:"영역은 1팔분 단위 8개 중 1개 (반지름 2 구). 구면좌표:\n$\\displaystyle\\int_0^{\\pi/2}\\!\\!\\int_0^{\\pi/2}\\!\\!\\int_0^{2}\\dfrac{1}{\\rho}\\rho^2\\sin\\phi\\,d\\rho\\,d\\phi\\,d\\theta=\\dfrac{\\pi}{2}\\cdot 1\\cdot\\dfrac{4}{2}\\cdot\\dfrac{1}{2}\\cdot... $\n계산: $\\dfrac{\\pi}{2}\\cdot 1\\cdot 2=\\pi$.",
  },
  {n:8, subject:"적분학", unit:"Maclaurin급수의 응용", concept:"푸리에 계수",
    difficulty:"medium",
    question:"닫힌 구간 $[0,\\pi]$에서 연속인 함수 $f(x)$를 사인 함수의 합 $\\displaystyle\\sum_{n=1}^{10}A_n\\sin nx$으로 근사하려고 한다. 이 때, 다음과 같이 주어진 오차 $E$를 최소화 하는 $A_n$의 값을 구하면?\n$E=\\dfrac{1}{2}\\!\\displaystyle\\int_0^{\\pi}\\!\\!\\left(f(x)-\\sum_{n=1}^{10}A_n\\sin nx\\right)^2 dx$",
    options:opts5("$A_n=\\dfrac{2}{\\pi}\\!\\int_0^{\\pi}f(x)\\sin nx\\,dx$","$A_n=\\dfrac{1}{\\pi}\\!\\int_0^{\\pi}f(x)\\sin nx\\,dx$","$A_n=\\dfrac{1}{\\pi}\\!\\int_{-\\pi}^{\\pi}f(x)\\sin nx\\,dx$","$A_n=\\dfrac{\\pi}{2}\\!\\int_0^{\\pi}f(x)\\sin nx\\,dx$","$A_n=\\dfrac{2}{\\pi}\\!\\int_{-\\pi}^{\\pi}f(x)\\sin nx\\,dx$"),
    correct:"1",
    explanation:"$\\sin nx$는 $[0,\\pi]$에서 $\\langle\\sin mx,\\sin nx\\rangle=\\dfrac{\\pi}{2}\\delta_{mn}$. 정사영 계수 $A_n=\\dfrac{2}{\\pi}\\!\\int_0^{\\pi}f(x)\\sin nx\\,dx$.",
  },
  {n:9, subject:"적분학", unit:"급수의 수렴/발산", concept:"수렴반경(중심이동)",
    difficulty:"medium",
    question:"멱급수 $\\displaystyle\\sum_{n=0}^{\\infty}a_n(x+2)^n$의 수렴구간을 $[-9,5]$라 할 때, 멱급수 $\\displaystyle\\sum_{n=0}^{\\infty}3^n a_n(x-4)^n$의 수렴반경은?",
    options:opts5("$\\dfrac{1}{2}$","$1$","$\\dfrac{3}{2}$","$\\dfrac{7}{3}$","$3$"),
    correct:"4",
    explanation:"첫 멱급수의 수렴반경 $R=7$. 즉 $|a_n|^{1/n}\\to 1/7$.\n둘째: $|3^n a_n|^{1/n}\\to 3/7$. 수렴반경 $=7/3$.",
  },
  {n:10, subject:"적분학", unit:"정적분의 응용", concept:"적분 변화량 근사",
    difficulty:"easyMedium",
    question:"$y=\\displaystyle\\int_0^{2x}\\dfrac{1}{\\sqrt{t^3+1}}dt$라 하자. $x$의 값이 $1$에서 $1.03$으로 증가할 때 $y$의 값의 변화량 $\\Delta y$를 가장 정확히 근사한 값은?",
    options:opts5("$0.01$","$0.02$","$0.03$","$0.04$","$0.05$"),
    correct:"2",
    explanation:"$\\dfrac{dy}{dx}=\\dfrac{2}{\\sqrt{(2x)^3+1}}$. $x=1$에서 $\\dfrac{2}{\\sqrt 9}=\\dfrac{2}{3}$.\n$\\Delta y\\approx\\dfrac{2}{3}\\cdot 0.03=0.02$.",
  },
  {n:11, subject:"다변수함수", unit:"편도함수", concept:"교선 위 접선 기울기",
    difficulty:"medium",
    question:"평면 $y=\\dfrac{1}{2}$과 곡면 $z=\\tan^{-1}(xy)$의 교선을 $C$라 할 때, 곡선 $C$ 위의 점 $\\!\\left(2,\\dfrac{1}{2},\\dfrac{\\pi}{4}\\right)$에서의 접선의 기울기는?",
    options:opts5("$\\dfrac{1}{8}$","$-\\dfrac{1}{8}$","$\\dfrac{1}{6}$","$-\\dfrac{1}{6}$","$\\dfrac{1}{4}$"),
    correct:"5",
    explanation:"$y=1/2$ 고정, $z=\\tan^{-1}(x/2)$. $\\dfrac{dz}{dx}=\\dfrac{1/2}{1+x^2/4}=\\dfrac{2}{4+x^2}$.\n$x=2$: $\\dfrac{2}{8}=\\dfrac{1}{4}$.",
  },
  {n:12, subject:"공학수학", unit:"미분방정식", concept:"방향장에 맞는 ODE",
    difficulty:"medium",
    question:"미분방정식 $\\dfrac{dx}{dt}=f(x)$의 몇 개의 해(굵은 실선)가 그림과 같을 때 $f(x)$의 식으로 타당한 것은? (해는 $x=0,1$ 사이에서 감소·발산, $x>1$에서 발산)",
    options:opts5("$-x(x-1)$","$x^2(x-1)$","$2x(x-1)$","$x(x-1)^2$","$-2x(x-1)^2$"),
    correct:"3",
    explanation:"평형점 $x=0$ (불안정), $x=1$ (불안정). 사이에서 $f<0$ (감소). $x>1$에서 $f>0$.\n$f(x)=2x(x-1)$ 이면 $x<0$: 양수 (증가), $0<x<1$: 음수 (감소), $x>1$: 양수 (증가). 불안정 평형점 $0,1$. 그래프에 부합.",
  },
  {n:13, subject:"적분학", unit:"정적분과 무한급수", concept:"리만합",
    difficulty:"medium",
    question:"극한 $\\displaystyle\\lim_{n\\to\\infty}\\sum_{i=1}^{n}\\dfrac{i}{n^2}e^{-2i/n}$의 값은?",
    options:opts5("$\\dfrac{1}{4}-\\dfrac{3}{8}e^{-1}$","$\\dfrac{3}{8}-\\dfrac{1}{8}e^{-1}$","$\\dfrac{1}{8}-\\dfrac{3}{8}e^{-2}$","$\\dfrac{3}{4}-\\dfrac{1}{4}e^{-2}$","$\\dfrac{1}{4}-\\dfrac{3}{4}e^{-2}$"),
    correct:"5",
    explanation:"리만합 $\\to\\displaystyle\\int_0^1 x e^{-2x}dx$. 부분적분: $\\!\\left[-\\dfrac{xe^{-2x}}{2}\\right]_0^1+\\!\\int_0^1\\dfrac{e^{-2x}}{2}dx=-\\dfrac{e^{-2}}{2}+\\!\\left[-\\dfrac{e^{-2x}}{4}\\right]_0^1=-\\dfrac{e^{-2}}{2}-\\dfrac{e^{-2}}{4}+\\dfrac{1}{4}=\\dfrac{1}{4}-\\dfrac{3e^{-2}}{4}$.",
  },
  {n:14, subject:"공학수학", unit:"미분방정식", concept:"연립 ODE 점근",
    difficulty:"medium",
    question:"$x(t)$를 연립 미분방정식 $x'(t)=\\begin{bmatrix}-2&2\\\\1&-1\\end{bmatrix}x(t),\\,x(0)=\\begin{bmatrix}1\\\\0\\end{bmatrix}$의 해라고 할 때 $\\displaystyle\\lim_{t\\to\\infty}x(t)$는?",
    options:opts5("$\\begin{bmatrix}2/3\\\\-1/3\\end{bmatrix}$","$\\begin{bmatrix}1/3\\\\1/3\\end{bmatrix}$","$\\begin{bmatrix}1/2\\\\-1/3\\end{bmatrix}$","$\\begin{bmatrix}1\\\\2\\end{bmatrix}$","$\\begin{bmatrix}2\\\\1\\end{bmatrix}$"),
    correct:"2",
    explanation:"행렬 $A$의 고윳값: $\\det(A-\\lambda I)=\\lambda^2+3\\lambda=0$, $\\lambda=0,-3$.\n$\\lambda=-3$항은 사라지고 $\\lambda=0$ 고유벡터 방향만 남음. $(A)v=0\\Rightarrow v=(2,1)^T$ 비례.\n초기벡터를 분해 후 점근하면 $(1/3,1/3)^T$.",
  },
  {n:15, subject:"다변수함수", unit:"선적분과 면적분", concept:"발산정리",
    difficulty:"hard",
    question:"곡면 $S$는 평면 $z=1$ 위쪽에 놓여있는 원추면 $z=2-\\sqrt{x^2+y^2}$의 부분이고 $S$의 방향은 위쪽을 향한다. 곡면 $S$를 통과하는 벡터장 $F(x,y,z)=(xy^2+\\tan^2 z)\\mathbf i+(e^{x^2}+x\\sin^3 z)\\mathbf j+(x^2 z+y^2)\\mathbf k$의 유량은?",
    options:opts5("$\\dfrac{1}{5}\\pi$","$\\dfrac{3}{5}\\pi$","$\\pi$","$\\dfrac{8}{7}\\pi$","$\\dfrac{11}{7}\\pi$"),
    correct:"2",
    explanation:"발산정리: 상측 원추+밑디스크 닫힌 면. div F=$y^2+0+x^2$.\n원추 영역 $z=1$~$2$, $r\\le 2-z$. $\\iiint(x^2+y^2)dV=\\!\\int_1^2\\!\\!\\int_0^{2-z}r^2\\cdot 2\\pi r\\,dr\\,dz=2\\pi\\!\\int_1^2\\dfrac{(2-z)^4}{4}dz=\\dfrac{\\pi}{10}$.\n디스크 ($z=1$, $\\hat n=-\\hat k$): $\\iint(x^2+y^2)\\cdot(-1)\\,dA=-\\dfrac{\\pi}{2}$ ($r\\le 1$ 디스크).\n원추 flux $=\\dfrac{\\pi}{10}+\\dfrac{\\pi}{2}=\\dfrac{3\\pi}{5}$.",
  },
  {n:16, subject:"공학수학", unit:"미분방정식", concept:"감쇠 진동 분류",
    difficulty:"medium",
    question:"다음은 서로 다른 $a$ 값에 대해 초기값 문제 $y''+ay'+y=0,\\,y(0)=1,\\,y'(0)=0$의 해의 움직임(Behavior)을 설명한 것이다. 이 중 옳지 <u>않은</u> 것은?\n(1) $a=1$: 진동하며 감소한다.\n(2) $a=0$: 감소하거나 증가하지 않으며 계속 진동한다.\n(3) $a=-1$: 진동하며 증가한다.\n(4) $a=2$: 진동 없이 증가한다.\n(5) $a=2\\sqrt 2$: 진동없이 감소한다.",
    options:opts5("(1)","(2)","(3)","(4)","(5)"),
    correct:"4",
    explanation:"$a=2$: 특성방정식 $\\lambda^2+2\\lambda+1=(\\lambda+1)^2$, 중근 $-1$.\n$y=(c_1+c_2 t)e^{-t}$. 초기조건 $c_1=1,\\,c_2=1$이므로 $y=(1+t)e^{-t}$. 진동 없이 감소 (증가 아님).",
  },
  {n:17, subject:"적분학", unit:"정적분의 응용", concept:"회전체 부피(셸)",
    difficulty:"medium",
    question:"좌표평면 위에 곡선 $y=\\dfrac{1}{2\\pi}x\\sin(x^2)$과 두 개의 직선 $y=0,\\,x=1$에 의해 둘러싸인 영역을 $y$축 둘레로 회전시켜 생기는 입체의 부피를 소수점 아래 둘째자리까지 정확하게 근사한 값은?",
    options:opts5("$\\dfrac{19}{270}$","$\\dfrac{29}{270}$","$\\dfrac{49}{270}$","$\\dfrac{57}{270}$","$\\dfrac{67}{270}$"),
    correct:"3",
    explanation:"셸법: $V=\\!\\int_0^1 2\\pi x\\cdot\\dfrac{x\\sin(x^2)}{2\\pi}dx=\\!\\int_0^1 x^2\\sin(x^2)dx$.\n급수전개 또는 수치적분 후 $\\dfrac{49}{270}\\approx 0.181$ 가까움.",
  },
  {n:18, subject:"공학수학", unit:"Laplace변환", concept:"부분분수 역변환",
    difficulty:"easy",
    question:"함수 $F(s)=\\dfrac{2s}{s^2+3s+2}$의 라플라스 역변환은?",
    options:opts5("$4e^{-2t}-2e^{-t}$","$4e^{-2t}+2e^{-t}$","$e^{-2t}-2e^{-t}$","$4e^{-t}+e^{-2t}$","$4te^{-t}-2e^{-t}$"),
    correct:"1",
    explanation:"$s^2+3s+2=(s+1)(s+2)$. $\\dfrac{2s}{(s+1)(s+2)}=\\dfrac{A}{s+1}+\\dfrac{B}{s+2}$.\n$2s=A(s+2)+B(s+1)$. $s=-1$: $-2=A$. $s=-2$: $-4=-B\\Rightarrow B=4$.\n$F=\\dfrac{-2}{s+1}+\\dfrac{4}{s+2}$. 역변환 $-2e^{-t}+4e^{-2t}=4e^{-2t}-2e^{-t}$.",
  },
  {n:19, subject:"다변수함수", unit:"선적분과 면적분", concept:"보존장 선적분",
    difficulty:"medium",
    question:"벡터장 $F(x,y)=(4x^3 y+e^{x^2})\\mathbf i+(x^4+2y\\cos(y^2))\\mathbf j$이고 $C$는 $r(t)=(e^{t^3-t^2}-\\cos(2\\pi t))\\mathbf i+(3\\sin(\\pi t^3/2)-2t^7)\\mathbf j,\\,0\\le t\\le 1$로 주어진 곡선일 때 선적분 $\\displaystyle\\int_C F\\cdot dr$의 값은?",
    options:opts5("$\\sin 1$","$\\cos 1$","$0$","$\\dfrac{11}{26}$","$\\dfrac{7}{25}$"),
    correct:"1",
    explanation:"$M_y=4x^3=N_x$이므로 보존장이다. 포텐셜을 $\\Phi(x,y)=x^4y+H(x)+\\sin(y^2)$로 두면 $H'(x)=e^{x^2}$이다. 경로의 양 끝점은 $r(0)=(0,0)$, $r(1)=(0,1)$이므로 $H(x)$ 항과 $x^4y$ 항은 양 끝에서 모두 같다. 따라서 $\\int_C F\\cdot dr=\\Phi(0,1)-\\Phi(0,0)=\\sin1$이다.",
  },
  {n:20, subject:"공학수학", unit:"미분방정식", concept:"비제차 ODE 특수해",
    difficulty:"medium",
    question:"$y_p(t)$를 미분방정식 $y''-y'-2y=-8e^t\\cos 2t$의 특수해(particular solution)라고 할 때 $y_p\\!\\left(\\dfrac{\\pi}{2}\\right)$의 값은?",
    options:opts5("$\\dfrac{8}{5}$","$-\\dfrac{6}{5}e^{\\pi/2}$","$\\dfrac{6}{5}e^{-\\pi/2}+\\dfrac{2}{5}$","$\\dfrac{2}{5}e^{\\pi/2}+\\dfrac{6}{5}$","$\\dfrac{2}{5}e^{\\pi/2}$"),
    correct:"2",
    explanation:"$y_p=e^t(A\\cos 2t+B\\sin 2t)$로 두고 대입하면 $y_p''-y_p'-2y_p=e^t[(-6A-2B)\\cos2t+(2A-6B)\\sin2t]$이다. 우변 $-8e^t\\cos2t$와 비교하면 $A=\\dfrac65,\\ B=-\\dfrac25$이다. 따라서 $y_p(\\pi/2)=e^{\\pi/2}\\left(A\\cos\\pi+B\\sin\\pi\\right)=-\\dfrac65e^{\\pi/2}$이다.",
  },
];

let okCount=0,failCount=0;
for (const p of PROBLEMS) {
  const num=String(p.n).padStart(2,"0");
  const id=`q-${YEAR}-${SCHOOL_EN}-${num}`;
  const tags=[YEAR,SCHOOL_KO,p.subject,p.unit,p.concept].filter(Boolean);
  const row={id,subject:p.subject,unit:p.unit,concept:p.concept,difficulty:p.difficulty,
    source_type:"imported",pool:"general",
    question:p.question,content_type:"latex",question_image:null,
    options:p.options,correct_option_id:p.correct,
    explanation:p.explanation,explanation_content_type:"latex",explanation_image:null,
    tags,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};
  const{error}=await sb.from("questions").upsert(row,{onConflict:"id"});
  if(error){console.error(`❌ ${id}:`,error.message);failCount++;}
  else{console.log(`✓ ${id}`);okCount++;}
}
console.log(`\n총 ${okCount}건 업로드, ${failCount}건 실패 (대상 ${PROBLEMS.length}건)`);
