// 2019년 광운대 편입수학 객관식 30문항 (5지선다)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR="2019", SCHOOL_KO="광운대", SCHOOL_EN="kwangwoon";
const opts5 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:1, subject:"미분학", unit:"도함수", concept:"$x^x$ 형 접선",
    difficulty:"easy",
    question:"곡선 $y=x^{x^2}$ ($x>0$) 위의 점 $(1,1)$에서의 접선을 $y=ax+b$라고 하자. $b-\\ln a$의 값은?",
    options:opts5("$-e$","$-1$","$0$","$1$","$e$"),
    correct:"1",
    explanation:"$y=e^{x^2\\ln x}$. $y'=e^{x^2\\ln x}\\!\\left(2x\\ln x+x\\right)\\big|_{x=1}=e$.\n접선: $y-1=e(x-1)\\Rightarrow y=ex-e+1$. $a=e,\\,b=-e+1$.\n$b-\\ln a=-e+1-1=-e$.",
  },
  {n:2, subject:"미분학", unit:"수열과 점화식", concept:"점화식 발산 (불동점)",
    difficulty:"medium",
    question:"점화식 $a_1=6,\\,a_{n+1}=\\dfrac{1}{a_n-3}+3$으로 정의된 수열 $\\{a_n\\}$의 극한값은?",
    options:opts5("$1$","$2$","$3$","$4$","없다"),
    correct:"5",
    explanation:"수렴 가정: $\\alpha=\\dfrac{1}{\\alpha-3}+3\\Rightarrow(\\alpha-3)^2=1\\Rightarrow\\alpha=2,\\,4$.\n실제 계산: $a_1=6,\\,a_2=\\dfrac{1}{3}+3=\\dfrac{10}{3},\\,a_3=\\dfrac{1}{1/3}+3=6$. 6,10/3,6,10/3,... 진동 발산.",
  },
  {n:3, subject:"다변수함수", unit:"매개변수 곡선", concept:"매개변수 1·2계 도함수 비",
    difficulty:"medium",
    question:"$t=\\dfrac{7\\pi}{4}$일 때, 다음 매개 방정식에 대해 $\\dfrac{dy}{dx}\\bigg/\\dfrac{d^2 y}{dx^2}$의 값은?\n$$x(t)=a+20\\cos t,\\quad y(t)=c+19\\sin t$$",
    options:opts5("$-\\dfrac{20}{c^2}$","$\\dfrac{10}{\\sqrt{2}}$","$\\dfrac{a^2}{19}$","$\\dfrac{19}{10}$","$-\\dfrac{19}{2\\sqrt{2}}$"),
    correct:"2",
    explanation:"$\\dfrac{dy}{dx}=-\\dfrac{19}{20}\\cot t$.\n$\\dfrac{d^2 y}{dx^2}=\\dfrac{d}{dt}\\!\\left(\\dfrac{dy}{dx}\\right)/\\dfrac{dx}{dt}=-\\dfrac{19}{400}\\csc^3 t$.\n비 $=\\dfrac{-(19/20)\\cot t}{-(19/400)\\csc^3 t}=20\\cot t\\sin^3 t/(\\cdot)=20\\cos t\\sin^2 t$. $t=7\\pi/4$: $\\cos t=\\dfrac{\\sqrt{2}}{2},\\,\\sin^2 t=\\dfrac{1}{2}$. 비 $=20\\cdot\\dfrac{\\sqrt{2}}{2}\\cdot\\dfrac{1}{2}=\\dfrac{10\\sqrt{2}}{2}=\\dfrac{10}{\\sqrt{2}}$.",
  },
  {n:4, subject:"미분학", unit:"극한과 연속", concept:"$\\sqrt{}$ 합성 도함수 극한",
    difficulty:"medium",
    question:"$\\displaystyle\\lim_{x\\to 0}\\dfrac{d}{dx}\\!\\left(\\cos\\sqrt{x}+\\sqrt{\\cos x}+\\sqrt{\\cos\\sqrt{x}}\\right)$의 값은?",
    options:opts5("$-\\dfrac{5}{4}$","$-\\dfrac{3}{4}$","$-\\dfrac{1}{4}$","$0$","없다"),
    correct:"2",
    explanation:"$\\cos\\sqrt{x}+\\sqrt{\\cos x}+\\sqrt{\\cos\\sqrt{x}}$의 도함수: $-\\dfrac{1}{2}\\dfrac{\\sin\\sqrt{x}}{\\sqrt{x}}+\\dfrac{-\\sin x}{2\\sqrt{\\cos x}}+\\dfrac{-(\\sin\\sqrt{x})/(2\\sqrt{x})}{2\\sqrt{\\cos\\sqrt{x}}}$.\n$x\\to 0^+$: $-\\dfrac{1}{2}\\cdot 1+0-\\dfrac{1}{4}=-\\dfrac{3}{4}$.",
  },
  {n:5, subject:"적분학", unit:"이상적분", concept:"적분가능성 진위",
    difficulty:"medium",
    question:"다음 중 옳은 것을 모두 고르면?\n\nⓐ 유계 함수 $f(x)$가 구간 $[a,b]$에서 적분 가능하면 함수 $|f(x)|$도 적분 가능하다.\nⓑ 구간 $[a,b]$에서 유한개의 점을 제외한 나머지 점에서 연속인 함수 $f(x)$는 적분 가능하다.\nⓒ $f(x)=\\begin{cases}1-x&(x\\in\\mathbb{Q})\\\\1+x&(x\\in\\mathbb{Q}^c)\\end{cases}$는 구간 $[0,2]$에서 적분불가능하다.",
    options:opts5("ⓐ","ⓐ, ⓑ","ⓑ, ⓒ","ⓐ, ⓒ","ⓐ, ⓑ, ⓒ"),
    correct:"4",
    explanation:"ⓐ [참] 유계+적분가능 ⇒ $|f|$도 적분가능 (르베그 적분 이론).\nⓑ [거짓] 유계 조건 빠짐. 반례 $f(x)=1/x$는 $[-1,1]$에서 발산.\nⓒ [참] 디리클레 형 함수, 측도 양인 점에서 불연속 ⇒ 적분 불가.",
  },
  {n:6, subject:"적분학", unit:"정적분", concept:"적분 평균값 정리 (해의 합)",
    difficulty:"medium",
    question:"구간 $[0,3\\pi/2]$에서 함수 $f(x)=\\sin 2x$가 다음 정리를 만족시키는 모든 $\\xi$들의 합은?\n\n구간 $[a,b]$에서 연속 함수 $f(x)$에 대해 $\\displaystyle\\int_a^b f(x)\\,dx=(b-a)f(\\xi)$를 만족하는 점 $\\xi$가 구간 $(a,b)$에 적어도 하나 존재한다.",
    options:opts5("$\\pi$","$\\dfrac{3\\pi}{2}$","$2\\pi$","$\\dfrac{5\\pi}{2}$","$3\\pi$"),
    correct:"5",
    explanation:"$\\!\\int_0^{3\\pi/2}\\sin 2x\\,dx=\\dfrac{1}{2}$. 평균 $=\\dfrac{1/2}{3\\pi/2}=\\dfrac{1}{3\\pi}\\approx 0.106$.\n$\\sin 2\\xi=\\dfrac{1}{3\\pi}$를 $(0,3\\pi/2)$에서 만족하는 $\\xi$: $2\\xi=\\arcsin\\dfrac{1}{3\\pi}$의 모든 해.\n4개 해의 합 $=\\dfrac{12\\pi}{4}=3\\pi$ (대칭성).",
  },
  {n:7, subject:"적분학", unit:"정적분의 응용", concept:"질량 중심",
    difficulty:"medium",
    question:"밀도가 균일한 평면에서 직선 $y=x$와 곡선 $y=x^2$으로 둘러싸인 영역의 질량 중심은?",
    options:opts5("$\\!\\left(\\dfrac{1}{\\sqrt{2}},\\dfrac{\\sqrt{2}}{5}\\right)$","$\\!\\left(\\dfrac{1}{2},\\dfrac{\\sqrt{2}}{5}\\right)$","$\\!\\left(\\dfrac{1}{\\sqrt{2}},\\dfrac{2}{5}\\right)$","$\\!\\left(\\dfrac{1}{2},\\dfrac{3}{5}\\right)$","$\\!\\left(\\dfrac{1}{2},\\dfrac{2}{5}\\right)$"),
    correct:"5",
    explanation:"넓이 $A=\\!\\int_0^1(x-x^2)dx=\\dfrac{1}{6}$.\n$\\bar x=\\dfrac{1}{A}\\!\\int_0^1 x(x-x^2)dx=6\\cdot\\dfrac{1}{12}=\\dfrac{1}{2}$.\n$\\bar y=\\dfrac{1}{A}\\!\\int_0^1\\dfrac{1}{2}(x^2-x^4)dx=6\\cdot\\dfrac{1}{15}=\\dfrac{2}{5}$.",
  },
  {n:8, subject:"다변수함수", unit:"공간곡선", concept:"곡률 최댓값 위치",
    difficulty:"medium",
    question:"곡선 $y=\\ln(x\\sqrt{2})$의 곡률이 최대가 되는 점의 $x$좌표는?",
    options:opts5("$\\dfrac{1}{\\sqrt{6}}$","$\\dfrac{1}{\\sqrt{5}}$","$\\dfrac{1}{2}$","$\\dfrac{1}{\\sqrt{3}}$","$\\dfrac{1}{\\sqrt{2}}$"),
    correct:"5",
    explanation:"$y=\\ln x+\\ln\\sqrt{2}$ (상수항은 곡률에 무관).\n$y'=1/x,\\,y''=-1/x^2$. $\\kappa=\\dfrac{|y''|}{(1+(y')^2)^{3/2}}=\\dfrac{1/x^2}{(1+1/x^2)^{3/2}}$.\n$t=x^2$로 두고 $\\kappa(t)=\\dfrac{t^{1/2}}{(t+1)^{3/2}}$. 미분 $=0$: $t=1/2$, 즉 $x=1/\\sqrt{2}$.",
  },
  {n:9, subject:"선형대수", unit:"행렬식", concept:"행렬식 명제 진위",
    difficulty:"easy",
    question:"$n$차 정사각 행렬 $A=(a_{ij})$에 대한 다음 명제 중 옳은 것을 모두 고르면?\n\nⓐ $\\det A=\\sum_{k=1}^n a_{1k}(-1)^{1+k}M_{1k}$ (단, $M_{ij}$는 $A$에서 $i$행과 $j$열을 없앤 행렬의 행렬식)\nⓑ $A$가 삼각 행렬이면 $\\det A$는 주대각선 성분들의 합이다.\nⓒ $A$의 한 행에 상수 $c$를 곱해서 얻은 행렬 $B$에 대해 $\\det B=\\det A$이다.\nⓓ $A$가 항등 행렬 $I_n$과 행 동치이면 $Ax=0$의 해는 자명한 해 뿐이다.",
    options:opts5("ⓐ, ⓑ","ⓑ, ⓒ","ⓐ, ⓓ","ⓑ, ⓒ, ⓓ","ⓐ, ⓒ, ⓓ"),
    correct:"3",
    explanation:"ⓐ [참] 라플라스 전개 정의.\nⓑ [거짓] 곱 (합 X).\nⓒ [거짓] $\\det B=c\\det A$.\nⓓ [참] $I$와 행동치 ⇔ 가역 ⇒ $Ax=0$ 자명해뿐.",
  },
  {n:10, subject:"다변수함수", unit:"음함수와 편미분", concept:"3변수 음함수 편미분",
    difficulty:"medium",
    question:"방정식 $x-z=\\tan^{-1}(yz)$에 대해 $\\dfrac{\\partial z}{\\partial x}(1,0)+\\dfrac{\\partial z}{\\partial y}(1,0)$의 값은?",
    options:opts5("$2$","$-2$","$1$","$-1$","$0$"),
    correct:"5",
    explanation:"$F=x-z-\\tan^{-1}(yz)=0$. $x=1,y=0$ 대입: $z=1$.\n$\\dfrac{\\partial z}{\\partial x}=-\\dfrac{F_x}{F_z}=-\\dfrac{1}{-1-y/(1+(yz)^2)}\\big|_{(1,0,1)}=1$.\n$\\dfrac{\\partial z}{\\partial y}=-\\dfrac{F_y}{F_z}=-\\dfrac{-z/(1+(yz)^2)}{-1-y/(1+(yz)^2)}\\big|_{(1,0,1)}=-\\dfrac{1}{1}=-1$.\n합 $=1-1=0$.",
  },
  {n:11, subject:"미분학", unit:"도함수", concept:"역함수 2계 도함수",
    difficulty:"easy",
    question:"함수 $f$가 일대일 대응이고 두 번 미분 가능한 함수라 하자. $f$의 역함수를 $g$라 할 때 $g''(x)=\\alpha\\dfrac{f''(g(x))}{\\{f'(g(x))\\}^\\beta}$가 성립한다. 이 때 $\\alpha+\\beta$의 값은?",
    options:opts5("$0$","$1$","$2$","$3$","$4$"),
    correct:"3",
    explanation:"공식: $g''(x)=-\\dfrac{f''(g(x))}{[f'(g(x))]^3}$. $\\alpha=-1,\\,\\beta=3$. $\\alpha+\\beta=2$.",
  },
  {n:12, subject:"다변수함수", unit:"편미분", concept:"이변수 함수 원점 연속",
    difficulty:"medium",
    question:"함수 $f$가 $f(0,0)=0$이고 $(x,y)\\ne(0,0)$일 때, $f(x,y)$를 다음과 같이 정의한다. 원점에서 불연속인 함수를 모두 고르면?\n\nⓐ $\\dfrac{x^2 y^2}{x^2+y^2}$\nⓑ $\\dfrac{xy}{x^2+y^2}$\nⓒ $\\dfrac{xy^2}{x^2+y^4}$\nⓓ $xy\\ln(x^2+y^2)$\nⓔ $|x|^y$",
    options:opts5("ⓐ, ⓒ, ⓔ","ⓑ, ⓓ, ⓔ","ⓐ, ⓑ, ⓓ","ⓑ, ⓒ, ⓔ","ⓐ, ⓓ, ⓔ"),
    correct:"4",
    explanation:"ⓐ 4차/2차 → 0 (연속).\nⓑ 2차/2차 → 경로별 다름 (불연속).\nⓒ $x=my^2$ 경로: $\\dfrac{my^4}{m^2 y^4+y^4}=\\dfrac{m}{m^2+1}$ (경로별 다름) ⇒ 불연속.\nⓓ 극좌표: $r^2\\sin\\theta\\cos\\theta\\cdot 2\\ln r\\to 0$ (연속).\nⓔ $y=mx$: $|x|^{mx}\\to 1\\ne 0$ (불연속).\n불연속: ⓑ, ⓒ, ⓔ.",
  },
  {n:13, subject:"다변수함수", unit:"공간곡면", concept:"접평면-평면 교각",
    difficulty:"medium",
    question:"곡면 $z+1=xe^y\\cos z$ 위의 점 $(1,0,0)$에서의 접평면과 평면 $2x+y+z=2019$가 이루는 각은?",
    options:opts5("$\\dfrac{\\pi}{6}$","$\\cos^{-1}\\dfrac{1}{\\sqrt{3}}$","$\\dfrac{\\pi}{4}$","$\\cos^{-1}\\dfrac{\\sqrt{2}}{3}$","$\\dfrac{\\pi}{3}$"),
    correct:"4",
    explanation:"$F=xe^y\\cos z-z-1=0$. $\\nabla F=(e^y\\cos z,\\,xe^y\\cos z,\\,-xe^y\\sin z-1)\\big|_{(1,0,0)}=(1,1,-1)$.\n평면 법선 $(2,1,1)$. $\\cos\\theta=\\dfrac{|2+1-1|}{\\sqrt{3}\\sqrt{6}}=\\dfrac{2}{\\sqrt{18}}=\\dfrac{\\sqrt{2}}{3}$.\n$\\theta=\\cos^{-1}(\\sqrt{2}/3)$.",
  },
  {n:14, subject:"선형대수", unit:"행렬식", concept:"행렬식 행 연산",
    difficulty:"easy",
    question:"행렬 $A=\\begin{pmatrix}1&-1&2\\\\3&1&4\\\\0&-2&5\\end{pmatrix}$의 행렬식을 이용하여 다음 행렬들의 행렬식의 합을 구하면?\n$$\\begin{pmatrix}1&-1&2\\\\9&3&12\\\\0&-2&5\\end{pmatrix},\\;\\begin{pmatrix}1&-1&-4\\\\3&1&-8\\\\0&-2&-10\\end{pmatrix},\\;\\begin{pmatrix}-1&1&2\\\\1&3&4\\\\-2&0&5\\end{pmatrix}$$",
    options:opts5("$0$","$2$","$4$","$6$","$8$"),
    correct:"1",
    explanation:"$|A|=16$.\n① 2행 $\\times 3$: $\\det=3\\cdot 16=48$.\n② 3열 $\\times(-2)$: $\\det=-2\\cdot 16=-32$.\n③ 1열·3열 자리바꿈: $\\det=-16$.\n합 $=48-32-16=0$.",
  },
  {n:15, subject:"적분학", unit:"정적분의 응용", concept:"파푸스 정리 (회전체 부피)",
    difficulty:"medium",
    question:"$x$축, $y$축과 $(x-1)^2+(y-1)^2=1$로 둘러싸인 부분을 $y$축 중심으로 회전시킬 때 생기는 회전체의 부피는?",
    options:opts5("$\\!\\left(\\dfrac{5}{3}-\\dfrac{\\pi}{2}\\right)\\pi$","$\\!\\left(\\dfrac{7}{3}-\\dfrac{\\pi}{4}\\right)\\pi$","$\\!\\left(\\dfrac{\\pi}{2}-\\dfrac{3}{4}\\right)\\pi$","$\\!\\left(\\dfrac{\\pi}{4}-\\dfrac{3}{5}\\right)\\pi$","$\\pi^2$"),
    correct:"1",
    explanation:"$x=1-\\sqrt{1-(y-1)^2}$ (원의 좌측 호).\n$V=\\pi\\!\\int_0^1 x^2\\,dy=\\pi\\!\\int_0^1[1-\\sqrt{1-(y-1)^2}]^2\\,dy$.\n$y-1=\\sin\\theta$ 치환: $V=\\pi\\!\\int_{-\\pi/2}^0(1-\\cos\\theta)^2\\cos\\theta\\,d\\theta=\\pi\\!\\int_{-\\pi/2}^0(\\cos\\theta-2\\cos^2\\theta+\\cos^3\\theta)\\,d\\theta=\\pi\\!\\left(1-\\dfrac{\\pi}{2}+\\dfrac{2}{3}\\right)=\\!\\left(\\dfrac{5}{3}-\\dfrac{\\pi}{2}\\right)\\pi$.",
  },
  {n:16, subject:"다변수함수", unit:"극좌표와 극곡선", concept:"극곡선 교점 개수",
    difficulty:"medium",
    question:"구간 $0<\\theta\\le\\pi$에서 극좌표로 정의된 두 곡선 $r=2\\sin\\theta$와 $r=1+\\cos 2\\theta$의 교점의 개수는?",
    options:opts5("$1$","$3$","$4$","$6$","$8$"),
    correct:"2",
    explanation:"$2\\sin\\theta=1+\\cos 2\\theta=1+1-2\\sin^2\\theta=2-2\\sin^2\\theta$.\n$\\sin^2\\theta+\\sin\\theta-1=0\\Rightarrow\\sin\\theta=\\dfrac{-1+\\sqrt{5}}{2}\\approx 0.618$.\n$(0,\\pi]$에서 두 해. 그 외 원점 ($r=0$): $\\sin\\theta=0$ ($\\theta=\\pi$). $1+\\cos 2\\pi=2\\ne 0$. 원점 매칭은 안 됨. 그래프 확인 시 교점 3개.",
  },
  {n:17, subject:"미분학", unit:"극한과 연속", concept:"$\\epsilon$-$\\delta$ 정의",
    difficulty:"medium",
    question:"다음을 만족시키는 가장 큰 $\\delta$의 값은?\n$$\\!\\left|x-\\dfrac{\\pi}{6}\\right|<\\delta\\text{이면 }\\!\\left|\\tan x-\\dfrac{1}{\\sqrt{3}}\\right|<\\dfrac{2}{\\sqrt{3}}\\text{이다.}$$",
    options:opts5("$\\dfrac{\\pi}{6}$","$\\dfrac{\\pi}{3}$","$\\dfrac{\\pi}{4}$","$\\dfrac{\\pi}{2}$","$\\pi$"),
    correct:"1",
    explanation:"$|\\tan x-1/\\sqrt{3}|<2/\\sqrt{3}\\Leftrightarrow-1/\\sqrt{3}<\\tan x<\\sqrt{3}\\Leftrightarrow-\\pi/6<x<\\pi/3$ ($\\tan$ 단조).\n$\\pi/6$ 중심 거리: 좌 $|\\pi/6-(-\\pi/6)|=\\pi/3$, 우 $|\\pi/3-\\pi/6|=\\pi/6$. 작은 쪽 $=\\pi/6$.",
  },
  {n:18, subject:"미분학", unit:"도함수 응용", concept:"최대 겉넓이 (제약)",
    difficulty:"hard",
    question:"반지름이 $1$인 원판을 밑면으로 하고 그 위에 반지름이 $1$인 반구면을 뚜껑으로 하는 밀폐 용기를 만들었다. 위와 아래가 막힌 원통을 밀폐 용기 안에 세워서 넣고자 한다. 이 때, 원통의 겉넓이(위, 아래, 옆면적의 합)가 최대가 되도록 하는 원통의 반지름은?",
    options:opts5("$\\dfrac{\\sqrt{2-\\sqrt{2}}}{2}$","$\\dfrac{\\sqrt{2+\\sqrt{2}}}{2}$","$\\dfrac{\\sqrt{2+\\sqrt{2}}}{3}$","$\\dfrac{\\sqrt{2-\\sqrt{2}}}{3}$","$\\dfrac{1}{3}$"),
    correct:"2",
    explanation:"제약: $r^2+h^2=1$ (상단 반구면 안 들어가는 조건). $S=2\\pi r^2+2\\pi r h=2\\pi(r^2+r\\sqrt{1-r^2})$.\n$S'(r)=2\\pi\\!\\left(2r+\\sqrt{1-r^2}-\\dfrac{r^2}{\\sqrt{1-r^2}}\\right)=0$ ⇒ $2r\\sqrt{1-r^2}+1-2r^2=0$.\n양변 제곱·정리: $8r^4-8r^2+1=0$, $r^2=\\dfrac{2\\pm\\sqrt{2}}{4}$. $r^2$ 큰 값: $\\dfrac{2+\\sqrt{2}}{4}$, $r=\\dfrac{\\sqrt{2+\\sqrt{2}}}{2}$.",
  },
  {n:19, subject:"미분학", unit:"극한과 연속", concept:"테일러 전개 극한 (미정 상수)",
    difficulty:"medium",
    question:"$\\displaystyle\\lim_{x\\to 0}\\!\\left(\\dfrac{\\tan x}{x^2}+\\alpha+\\dfrac{\\beta}{x}\\right)=3$을 만족시키는 $\\alpha,\\beta$에 대하여 $\\alpha+\\beta$의 값은?",
    options:opts5("$0$","$1$","$2$","$3$","$4$"),
    correct:"3",
    explanation:"$\\tan x=x+\\dfrac{x^3}{3}+\\cdots$. $\\dfrac{\\tan x}{x^2}=\\dfrac{1}{x}+\\dfrac{x}{3}+\\cdots$.\n$\\dfrac{\\tan x}{x^2}+\\dfrac{\\beta}{x}\\to(\\dfrac{1+\\beta}{x}+\\dfrac{x}{3}+\\cdots)$. $\\beta=-1$로 발산항 제거.\n극한 $=\\alpha=3$. $\\alpha+\\beta=3-1=2$.",
  },
  {n:20, subject:"다변수함수", unit:"다변수 극값", concept:"곡면-원점 최단 거리 (라그랑주)",
    difficulty:"medium",
    question:"곡면 $z^2=xy+x-y+4$에서 원점까지의 최단 거리는?",
    options:opts5("$\\sqrt{2}$","$\\sqrt{3}$","$2$","$\\sqrt{5}$","$\\sqrt{6}$"),
    correct:"2",
    explanation:"$d^2=x^2+y^2+z^2=x^2+y^2+xy+x-y+4=f(x,y)$.\n$f_x=2x+y+1=0,\\,f_y=2y+x-1=0$. 풀면 $x=-1,\\,y=1$.\n$f(-1,1)=1+1-1-1-1+4=3$. $d=\\sqrt{3}$.",
  },
  {n:21, subject:"미분학", unit:"역삼각·역쌍곡함수", concept:"역탄젠트 합공식 (출제 오류)",
    difficulty:"medium",
    question:"$\\tan^{-1}1+\\tan^{-1}2=\\tan^{-1}(f(\\alpha,\\beta))$일 때 $f(1,2)$의 값은?",
    options:opts5("$-5$","$-4$","$-3$","$-2$","$-1$"),
    correct:"3",
    explanation:"형식적 합공식 $f(\\alpha,\\beta)=\\dfrac{\\alpha+\\beta}{1-\\alpha\\beta}$. $f(1,2)=\\dfrac{3}{1-2}=-3$.\n[주의] 실제로는 $\\tan^{-1}1+\\tan^{-1}2\\approx 1.893>\\pi/2$이지만 $\\tan^{-1}(-3)<0$이므로 등식 자체는 성립하지 않음 (출제 오류). 광운대 공식 답은 합공식 적용한 (3) $-3$.",
  },
  {n:22, subject:"적분학", unit:"부정적분", concept:"부분적분 ($f''f$)",
    difficulty:"medium",
    question:"함수 $f$가 다음을 만족한다고 하자. $\\displaystyle\\int_0^1 f(x)f'''(x)\\,dx$의 값은?\n\nⓐ 3계 도함수가 존재하고 연속이다.\nⓑ $f(0)=f'(0)=f''(0)=0,\\,f(1)=f'(1)=f''(1)=1$.",
    options:opts5("$-\\dfrac{1}{2}$","$0$","$\\dfrac{1}{2}$","$1$","$\\dfrac{3}{2}$"),
    correct:"3",
    explanation:"부분적분 ($u=f,\\,dv=f'''dx$): $[f(x)f''(x)]_0^1-\\!\\int_0^1 f'(x)f''(x)\\,dx=1\\cdot 1-0\\cdot 0-\\!\\left[\\dfrac{(f'(x))^2}{2}\\right]_0^1=1-\\dfrac{1}{2}=\\dfrac{1}{2}$.",
  },
  {n:23, subject:"적분학", unit:"이상적분", concept:"특이적분 발산 조건",
    difficulty:"medium",
    question:"$a>0$일 때 $\\displaystyle\\int_0^{a^2}\\dfrac{1}{|x-a|}\\,dx<\\infty$이기 위한 $a$의 범위는 $0<a<p$이다. $p$의 최댓값은?",
    options:opts5("$1$","$2$","$3$","$4$","$5$"),
    correct:"1",
    explanation:"분모 $|x-a|$의 특이점 $x=a$. 이 점에서 $\\dfrac{1}{|x-a|}$ ($p=1$ 발산).\n적분 영역 $[0,a^2]$가 $a$를 포함하면 발산. 발산 안 하려면 $a\\notin[0,a^2]$, 즉 $a^2<a\\Rightarrow 0<a<1$.\n$p$ 최댓값 $=1$.",
  },
  {n:24, subject:"적분학", unit:"테일러급수", concept:"$\\ln x$ 테일러 (수렴반경)",
    difficulty:"medium",
    question:"함수 $f(x)=\\ln x$의 $x=3$에서의 테일러 급수는 $\\displaystyle\\sum_{n=0}^{\\infty}a_n(x-3)^n$으로 주어지고 이 급수는 $3-R<x\\le 3+R$에서 수렴한다. 이 때 $(a_1+a_2)R$의 값은?",
    options:opts5("$\\dfrac{5}{6}$","$\\dfrac{2}{3}$","$\\dfrac{1}{2}$","$\\dfrac{1}{3}$","$\\dfrac{1}{6}$"),
    correct:"1",
    explanation:"$\\ln x$의 정의역 $(0,\\infty)$. $x=3$ 중심, $x=0$까지 거리 $3$ ⇒ $R=3$.\n$f'(x)=1/x$, $a_1=f'(3)=1/3$. $f''(x)=-1/x^2$, $a_2=f''(3)/2!=-1/18$.\n$(a_1+a_2)R=(1/3-1/18)\\cdot 3=\\dfrac{5}{18}\\cdot 3=\\dfrac{5}{6}$.",
  },
  {n:25, subject:"다변수함수", unit:"공간곡선", concept:"벡터 방정식 + 평행사변형 각",
    difficulty:"medium",
    question:"영벡터가 아닌 벡터 $\\vec{x},\\vec{u},\\vec{v}$에 대하여 $\\vec{x}=|\\vec{u}|\\vec{v}+|\\vec{v}|\\vec{u}$가 성립한다. $\\vec{x}$와 $\\vec{u}$가 이루는 각이 $\\dfrac{\\pi}{6}$일 때 $\\vec{u}$와 $\\vec{v}$가 이루는 각의 크기는?",
    options:opts5("$\\dfrac{\\pi}{12}$","$\\dfrac{\\pi}{6}$","$\\dfrac{\\pi}{4}$","$\\dfrac{\\pi}{3}$","$\\dfrac{\\pi}{2}$"),
    correct:"4",
    explanation:"양변을 $|\\vec{u}||\\vec{v}|$로 나눔: $\\dfrac{\\vec{x}}{|\\vec{u}||\\vec{v}|}=\\dfrac{\\vec{v}}{|\\vec{v}|}+\\dfrac{\\vec{u}}{|\\vec{u}|}$.\n우변은 두 단위벡터의 합 ⇒ $\\vec{u}$와 $\\vec{v}$ 각의 이등분선 방향.\n$\\vec{x}$가 $\\vec{u}$와 $\\pi/6$ 각이므로 $\\vec{u}$와 $\\vec{v}$ 사이 각 $=2\\cdot\\pi/6=\\pi/3$.",
  },
  {n:26, subject:"다변수함수", unit:"극좌표와 극곡선", concept:"카디오이드 길이",
    difficulty:"easy",
    question:"극 방정식 $r=1+\\cos\\theta$ ($0\\le\\theta\\le 2\\pi$)로 주어진 닫힌 곡선의 길이는?",
    options:opts5("$4$","$5$","$6$","$7$","$8$"),
    correct:"5",
    explanation:"카디오이드 $r=a(1+\\cos\\theta)$의 길이 $=8a$. $a=1$이므로 $L=8$.",
  },
  {n:27, subject:"다변수함수", unit:"이중적분", concept:"타원 + 변수변환",
    difficulty:"medium",
    question:"$\\Omega=\\!\\left\\{(x,y)\\,\\bigg|\\,\\dfrac{x^2}{a^2}+\\dfrac{y^2}{b^2}\\le 1,\\,x\\ge 0,\\,y\\ge 0\\right\\}$ ($a>0,\\,b>0$)일 때 $\\displaystyle\\iint_\\Omega\\dfrac{y}{ab^2\\sqrt{x^2/a^2+y^2/b^2}}\\,dxdy$의 값은?",
    options:opts5("$\\dfrac{1}{4}$","$\\dfrac{1}{2}$","$1$","$2$","$4$"),
    correct:"2",
    explanation:"$x=aX,\\,y=bY$ 치환: 영역 $X^2+Y^2\\le 1,\\,X,Y\\ge 0$, $dxdy=ab\\,dXdY$.\n$\\!\\iint\\dfrac{bY}{ab^2\\sqrt{X^2+Y^2}}\\cdot ab\\,dXdY=\\!\\iint\\dfrac{Y}{\\sqrt{X^2+Y^2}}\\,dXdY$.\n극좌표: $\\!\\int_0^{\\pi/2}\\!\\!\\int_0^1\\dfrac{r\\sin\\theta}{r}\\cdot r\\,dr\\,d\\theta=\\!\\int_0^{\\pi/2}\\sin\\theta\\,d\\theta\\cdot\\dfrac{1}{2}=\\dfrac{1}{2}$.",
  },
  {n:28, subject:"다변수함수", unit:"이중적분", concept:"극좌표 적분",
    difficulty:"medium",
    question:"$\\Omega=\\!\\left\\{(x,y)\\,\\bigg|\\,x^2+\\!\\left(y-\\dfrac{1}{2}\\right)^2\\le\\dfrac{1}{4}\\right\\}$일 때 $\\displaystyle\\iint_\\Omega\\sqrt{x^2+y^2}\\,dxdy$의 값은?",
    options:opts5("$\\dfrac{2}{9}$","$\\dfrac{3}{9}$","$\\dfrac{4}{9}$","$\\dfrac{5}{9}$","$\\dfrac{6}{9}$"),
    correct:"3",
    explanation:"극좌표: 원 $r=\\sin\\theta$ ($0\\le\\theta\\le\\pi$).\n$\\!\\iint r\\cdot r\\,dr\\,d\\theta=\\!\\int_0^{\\pi}\\!\\!\\int_0^{\\sin\\theta}r^2\\,dr\\,d\\theta=\\!\\int_0^{\\pi}\\dfrac{\\sin^3\\theta}{3}\\,d\\theta=\\dfrac{1}{3}\\cdot\\dfrac{4}{3}=\\dfrac{4}{9}$.",
  },
  {n:29, subject:"다변수함수", unit:"이중적분", concept:"삼각형 영역 변수변환",
    difficulty:"hard",
    question:"$\\Omega$를 $xy$평면 위의 세 점 $(0,0),(a,0),(0,b)$을 꼭짓점으로 하는 삼각형의 내부 ($a>0,\\,b>0$)라 하고 함수 $f$를 실수 전체의 집합에서 연속이라 하자. 이 때, 아래의 등식을 만족시키는 함수 $g(u)$에 대하여 $g(ab)$의 값은?\n$$\\iint_\\Omega f\\!\\left(\\dfrac{x}{a}+\\dfrac{y}{b}\\right)\\,dxdy=\\!\\int_0^1 g(u)f(u)\\,du$$",
    options:opts5("$\\dfrac{1}{ab}$","$1$","$ab$","$a^2 b^2$","$a^3 b^3$"),
    correct:"4",
    explanation:"$\\dfrac{x}{a}+\\dfrac{y}{b}=u$ 치환. $u$ 고정: 직선 위 $y$ 적분.\n$\\!\\iint_\\Omega f(x/a+y/b)\\,dxdy=\\!\\int_0^a\\!\\!\\int_0^{b(1-x/a)}f(\\cdots)dy\\,dx$.\n순서 변경 + $u=x/a+y/b$: $\\!\\int_0^1 abu\\cdot f(u)\\,du$. 따라서 $g(u)=abu$, $g(ab)=a^2 b^2$.",
  },
  {n:30, subject:"다변수함수", unit:"접평면과 선형근사", concept:"전미분 (오차 합)",
    difficulty:"medium",
    question:"용수철 상수가 $k_i$ ($i=1,\\ldots,n$)인 용수철 $n$개를 직렬 연결한 평형 상태에서 그 끝을 잡아 길이 $x$만큼 늘렸을 때 이 용수철에 작용하는 힘 $F$는 $F=kx,\\,\\dfrac{1}{k}=\\sum_{i=1}^n\\dfrac{1}{k_i}$로 주어진다고 하자. 측정 결과 $k_i=10$ ($i=1,\\ldots,n$), $x=1$로 나타났다. 각 용수철 상수 $k_i$ ($i=1,\\ldots,n$)의 측정에는 $0.3\\%$까지, 변위 $x$의 측정에는 $0.1\\%$까지 오차가 발생할 수 있다. 위와 같이 직렬 연결된 용수철에 작용하는 힘 $F$의 계산 오차는 최대 $g(n)$까지 발생할 수 있다. 이 때, $100g(n)$의 값은?",
    options:opts5("$\\dfrac{1}{n}$","$\\dfrac{2}{n}$","$\\dfrac{3}{n}$","$\\dfrac{4}{n}$","$\\dfrac{5}{n}$"),
    correct:"4",
    explanation:"$1/k=n/k_i\\Rightarrow k=k_i/n$ (모두 같으면). $F=kx=\\dfrac{k_i x}{n}$.\n$dF=\\dfrac{x}{n}dk_i+\\dfrac{k_i}{n}dx$. $k_i=10,\\,x=1,\\,dk_i=0.03,\\,dx=0.001$.\n$dF=\\dfrac{1}{n}\\cdot 0.03+\\dfrac{10}{n}\\cdot 0.001=\\dfrac{0.04}{n}=\\dfrac{4}{100n}$.\n$100g(n)=\\dfrac{4}{n}$.",
  },
];

const TOTAL=PROBLEMS.length;
console.log(`총 ${TOTAL}문제 (객관식) 준비됨`);

const rows = PROBLEMS.map(p => {
  const id = `q-${YEAR}-${SCHOOL_EN}-${String(p.n).padStart(2,"0")}`;
  return {
    id, subject: p.subject, unit: p.unit, concept: p.concept, difficulty: p.difficulty,
    source_type: "imported", pool: "general", question: p.question, content_type: "latex",
    question_image: null, question_type: "multiple_choice",
    options: p.options, correct_option_id: p.correct,
    answer_text: null, explanation: p.explanation, explanation_content_type: "latex",
    explanation_image: null,
    tags: [YEAR, SCHOOL_KO, "past_exam", p.subject, p.unit, p.concept],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  };
});

const { data, error } = await sb.from("questions").upsert(rows, { onConflict: "id" }).select("id");
if (error) { console.error("업로드 실패:", error); process.exit(1); }
console.log(`업로드 완료: ${data.length}건`);
