// Upload 선형대수 Daily TEST 1~20 (120 problems).
// Usage: node scripts/upload_daily_tests_la_1to20.mjs
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(
  envText.split(/\r?\n/).filter((l) => l && !l.startsWith("#") && l.includes("="))
    .map((l) => { const [k, ...r] = l.split("="); return [k.trim(), r.join("=").trim()]; })
);
const supabase = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.NEXT_PUBLIC_SUPABASE_ANON_KEY);

const o = (id, text) => ({ id, label: id, text, contentType: "latex", image: "" });
function build({ testNo, num, unit, concept, difficulty, question, options, answer, explanation }) {
  const id = `q-daily-la-r${testNo}-${num}`;
  const tags = Array.from(new Set(["daily", `daily-test-la-${testNo}`, "선형대수", unit, concept].filter(Boolean)));
  return {
    id, subject: "선형대수", unit, concept, difficulty,
    source_type: "imported", question, content_type: "latex", question_image: null,
    options, correct_option_id: answer, explanation, explanation_content_type: "latex",
    explanation_image: null, tags,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString()
  };
}

const problems = [
  // ========== DT1 행렬 기초 ==========
  build({ testNo: 1, num: 1, unit: "행렬", concept: "행렬의 곱", difficulty: "easy",
    question: "$\\begin{pmatrix}3&1\\\\0&2\\\\5&8\\end{pmatrix}\\begin{pmatrix}1&2&3\\\\0&1&4\\end{pmatrix}=?$",
    options: [
      o("1","$\\begin{pmatrix}3&7&13\\\\0&2&8\\\\5&18&47\\end{pmatrix}$"),
      o("2","$\\begin{pmatrix}3&7&13\\\\0&2&8\\\\5&18&37\\end{pmatrix}$"),
      o("3","$\\begin{pmatrix}3&6&13\\\\0&2&8\\\\5&18&47\\end{pmatrix}$"),
      o("4","$\\begin{pmatrix}3&7&13\\\\2&2&8\\\\5&18&47\\end{pmatrix}$"),
      o("5","$\\begin{pmatrix}3&7&12\\\\0&2&8\\\\5&18&47\\end{pmatrix}$")
    ], answer: "1",
    explanation: "각 성분별로 $(3,1)\\cdot(1,0)=3,\\ (3,1)\\cdot(2,1)=7,\\ (3,1)\\cdot(3,4)=13$ 등으로 계산." }),
  build({ testNo: 1, num: 2, unit: "행렬", concept: "행렬의 곱", difficulty: "easyMedium",
    question: "실수 $a$에 대하여 $\\begin{pmatrix}\\sin x&\\cos x\\\\2&2\\end{pmatrix}\\begin{pmatrix}2\\\\a\\end{pmatrix}=\\begin{pmatrix}k\\\\6\\end{pmatrix}$일 때, $k$의 최댓값은?",
    options: [o("1","$1$"),o("2","$\\sqrt{3}$"),o("3","$\\sqrt{5}$"),o("4","$2$"),o("5","$3$")],
    answer: "3",
    explanation: "두 번째 식 $2\\cdot 2+2a=6\\Rightarrow a=1$. $k=2\\sin x+\\cos x=\\sqrt{5}\\sin(x+\\theta)$이므로 최댓값 $\\sqrt{5}$." }),
  build({ testNo: 1, num: 3, unit: "행렬", concept: "행렬의 크기", difficulty: "easy",
    question: "$A$는 $k\\times l$, $B$는 $4\\times 3$, $C$는 $m\\times n$, $D$는 $p\\times q$ 행렬이고, $ABC+D=\\begin{pmatrix}1\\\\1\\\\9\\end{pmatrix}$일 때 $k+l+m+p$의 값은?",
    options: [o("1","$10$"),o("2","$11$"),o("3","$12$"),o("4","$13$"),o("5","$14$")],
    answer: "4",
    explanation: "$AB$가 정의되려면 $l=4$. $BC$의 결과가 $4\\times n$, $ABC$는 $k\\times n$. 결과 $3\\times 1$이므로 $k=3,n=1$. $C$는 $3\\times 1$이므로 $m=3$. $D=p\\times 1$로 $p=3$. $k+l+m+p=3+4+3+3=13$." }),
  build({ testNo: 1, num: 4, unit: "행렬", concept: "대각합", difficulty: "easy",
    question: "행렬 $A=\\begin{pmatrix}1&0&1&1\\\\0&-1&0&1\\\\1&0&2&0\\\\0&1&-1&-2\\end{pmatrix}$의 전치행렬 $A^T$에 대하여 $\\mathrm{tr}(AA^T)$의 값은?",
    options: [o("1","$14$"),o("2","$15$"),o("3","$16$"),o("4","$17$"),o("5","$18$")],
    answer: "3",
    explanation: "$\\mathrm{tr}(AA^T)$는 $A$의 모든 성분의 제곱의 합. $1+0+1+1+0+1+0+1+1+0+4+0+0+1+1+4=16$." }),
  build({ testNo: 1, num: 5, unit: "행렬", concept: "전치행렬", difficulty: "easyMedium",
    question: "$A=\\begin{pmatrix}0&1&3\\\\-1&0&-2\\\\-3&2&0\\end{pmatrix}$에 대하여 $B=10A+9A^T$의 전치행렬 $B^T$는?",
    options: [o("1","$A$"),o("2","$-A$"),o("3","$A^T$"),o("4","$-A^T$"),o("5","$O$")],
    answer: "2",
    explanation: "$A$는 반대칭이므로 $A^T=-A$. $B=10A+9(-A)=A$이고 $B^T=A^T=-A$." }),
  build({ testNo: 1, num: 6, unit: "행렬", concept: "대칭/교대 분해", difficulty: "easyMedium",
    question: "행렬 $\\begin{pmatrix}2&-1&1\\\\3&0&4\\\\-1&2&-3\\end{pmatrix}$을 대칭+교대 합으로 $\\begin{pmatrix}2&a&0\\\\b&0&c\\\\0&d&-3\\end{pmatrix}+\\begin{pmatrix}0&e&1\\\\f&0&g\\\\-1&h&0\\end{pmatrix}$로 나타낼 때 $abcd-efgh$의 값은?",
    options: [o("1","$3$"),o("2","$4$"),o("3","$5$"),o("4","$6$"),o("5","$7$")],
    answer: "3",
    explanation: "$\\frac{1}{2}(A+A^T)$로 대칭, $\\frac{1}{2}(A-A^T)$로 교대 부분 분리. $a=1,b=1,c=3,d=3,e=-2,f=2,g=1,h=-1$. $abcd-efgh=9-4=5$." }),

  // ========== DT2 행렬식 ==========
  build({ testNo: 2, num: 1, unit: "행렬", concept: "대칭/반대칭 행렬", difficulty: "easyMedium",
    question: "다음 중 틀린 것은?\\\\① $A,B$가 대칭이면 $A+B$도 대칭\\\\② $A,B$가 반대칭이면 $A+B$도 반대칭\\\\③ $A,B$가 대칭이면 $AB$도 대칭\\\\④ $A,B$가 반대칭이면 $AB$도 반대칭\\\\⑤ 모든 정방행렬은 대칭과 교대의 합으로 표현 가능",
    options: [o("1","①"),o("2","②"),o("3","③, ④"),o("4","③ 만"),o("5","⑤")],
    answer: "3",
    explanation: "③ $(AB)^T=B^TA^T=BA\\ne AB$ 일반적. ④ $(AB)^T=B^TA^T=(-B)(-A)=BA\\ne -AB$. 둘 다 일반적으로 성립하지 않음." }),
  build({ testNo: 2, num: 2, unit: "행렬", concept: "행렬식 계산", difficulty: "easy",
    question: "$A=\\begin{pmatrix}1&0&1&0\\\\0&1&0&1\\\\1&0&1&1\\\\0&1&0&0\\end{pmatrix}$에 대하여 $\\det(A)$의 값은?",
    options: [o("1","$-1$"),o("2","$0$"),o("3","$1$"),o("4","$2$"),o("5","$-2$")],
    answer: "2",
    explanation: "1행과 3행에서 1,3열 동일패턴, 4행 2열 기준 여인수전개로 $1\\cdot\\det\\begin{pmatrix}1&1&0\\\\0&0&1\\\\1&1&1\\end{pmatrix}=0$." }),
  build({ testNo: 2, num: 3, unit: "행렬", concept: "행렬식 계산", difficulty: "easyMedium",
    question: "$\\begin{vmatrix}6&0&0&-6\\\\4&-2&3&-1\\\\2&1&-7&-2\\\\-3&0&4&3\\end{vmatrix}$의 값은?",
    options: [o("1","$60$"),o("2","$66$"),o("3","$72$"),o("4","$78$"),o("5","$84$")],
    answer: "3",
    explanation: "행 연산으로 정리 후 계산. 결과 $72$." }),
  build({ testNo: 2, num: 4, unit: "행렬", concept: "행렬식 계산", difficulty: "easyMedium",
    question: "$\\begin{vmatrix}-1&0&1&2&0\\\\-1&2&0&1&2\\\\1&0&2&1&3\\\\0&1&0&3&2\\\\1&1&0&2&0\\end{vmatrix}$의 값은?",
    options: [o("1","$48$"),o("2","$54$"),o("3","$60$"),o("4","$72$"),o("5","$36$")],
    answer: "2",
    explanation: "행 연산을 통해 차원 축소. 최종 결과 $54$." }),
  build({ testNo: 2, num: 5, unit: "행렬", concept: "Vandermonde 행렬식", difficulty: "easyMedium",
    question: "$\\begin{vmatrix}-1&2&-1&2&-1\\\\3&1&3&1&3\\\\0&0&1&2&4\\\\0&0&1&3&9\\\\0&0&1&4&16\\end{vmatrix}$의 값은?",
    options: [o("1","$-7$"),o("2","$-10$"),o("3","$-12$"),o("4","$-14$"),o("5","$-16$")],
    answer: "4",
    explanation: "블록 형태이므로 $\\begin{vmatrix}-1&2\\\\3&1\\end{vmatrix}\\cdot\\begin{vmatrix}1&2&4\\\\1&3&9\\\\1&4&16\\end{vmatrix}=(-7)\\cdot 2=-14$." }),
  build({ testNo: 2, num: 6, unit: "행렬", concept: "행렬식 계산", difficulty: "easyMedium",
    question: "$\\begin{vmatrix}1&a&a^2&a^3\\\\1&b&b^2&b^3\\\\0&0&0&1\\\\1&c&c^2&c^3\\end{vmatrix}$를 계산하면?",
    options: [
      o("1","$(b-a)(c-b)(c-a)$"),
      o("2","$-(b-a)(c-b)(c-a)$"),
      o("3","$(b-a)(c-a)$"),
      o("4","$-(b-a)(c-a)$"),
      o("5","$0$")
    ], answer: "2",
    explanation: "3행 4열을 기준으로 여인수전개 후 Vandermonde: $-\\begin{vmatrix}1&a&a^2\\\\1&b&b^2\\\\1&c&c^2\\end{vmatrix}=-(b-a)(c-b)(c-a)$." }),

  // ========== DT3 행렬식 변환 ==========
  build({ testNo: 3, num: 1, unit: "행렬", concept: "행렬식 성질", difficulty: "easy",
    question: "행렬 $C=\\begin{pmatrix}2&4&7\\\\6&0&3\\\\1&5&3\\end{pmatrix}$가 주어졌을 때 $C^T$의 행렬식 값은?",
    options: [o("1","$60$"),o("2","$80$"),o("3","$100$"),o("4","$120$"),o("5","$140$")],
    answer: "4",
    explanation: "$\\det(C^T)=\\det(C)$. 계산하면 $120$." }),
  build({ testNo: 3, num: 2, unit: "행렬", concept: "행렬식 거듭제곱", difficulty: "easyMedium",
    question: "$A=\\begin{pmatrix}1&2&0&2&2\\\\2&3&0&7&3\\\\3&3&2&3&4\\\\4&4&0&1&5\\\\0&0&0&1&0\\end{pmatrix}$에 대하여 $\\det(A^3)$의 값은?",
    options: [o("1","$2$"),o("2","$4$"),o("3","$6$"),o("4","$8$"),o("5","$10$")],
    answer: "4",
    explanation: "$\\det A=2$이므로 $\\det A^3=2^3=8$." }),
  build({ testNo: 3, num: 3, unit: "행렬", concept: "행렬식 행연산", difficulty: "easyMedium",
    question: "$\\det(A)=10$일 때 $\\det(B)$의 값은?\\\\$A=\\begin{pmatrix}a_1&a_2&a_3\\\\b_1&b_2&b_3\\\\c_1&c_2&c_3\\end{pmatrix},\\ B=\\begin{pmatrix}-a_1&-a_2&-a_3\\\\2b_1&2b_2&2b_3\\\\c_1-a_1&c_2-a_2&c_3-a_3\\end{pmatrix}$",
    options: [o("1","$-20$"),o("2","$-10$"),o("3","$10$"),o("4","$20$"),o("5","$0$")],
    answer: "1",
    explanation: "1행 $\\times(-1)$, 2행 $\\times 2$, 3행에 1행 더해도 행렬식 불변. $\\det B=(-1)\\cdot 2\\cdot\\det A=-20$." }),
  build({ testNo: 3, num: 4, unit: "행렬", concept: "행렬식 열연산", difficulty: "easy",
    question: "$\\begin{vmatrix}a&2a&3a\\\\b&1+2b&3+3b\\\\c&2+2c&5+3c\\end{vmatrix}$의 값은?",
    options: [o("1","$a$"),o("2","$-a$"),o("3","$2a$"),o("4","$-2a$"),o("5","$0$")],
    answer: "2",
    explanation: "2열에서 1열의 2배, 3열에서 1열의 3배 빼면 $\\begin{vmatrix}a&0&0\\\\b&1&3\\\\c&2&5\\end{vmatrix}=a(5-6)=-a$." }),
  build({ testNo: 3, num: 5, unit: "행렬", concept: "행렬식 방정식", difficulty: "easyMedium",
    question: "$A=\\begin{pmatrix}a&a^2&a^3\\\\a^2&a^3&a\\\\a^3&a&a^2\\end{pmatrix}$에 대하여 $\\det A=0$이 되게 하는 서로 다른 실수 $a$의 합은?",
    options: [o("1","$0$"),o("2","$1$"),o("3","$2$"),o("4","$-1$"),o("5","$3$")],
    answer: "2",
    explanation: "$a^3(a^3-1)^2=0$. 실근 $a=0,1$ (1은 중복), 서로 다른 실근의 합 $0+1=1$." }),
  build({ testNo: 3, num: 6, unit: "행렬", concept: "행렬식 방정식", difficulty: "easyMedium",
    question: "$\\begin{vmatrix}x&1&1&1\\\\x&1&x&1\\\\x&x&1&x\\\\1&1&1&x\\end{vmatrix}=0$을 만족하는 모든 $x$의 값은?",
    options: [o("1","$x=0,1$"),o("2","$x=1$"),o("3","$x=0,-1$"),o("4","$x=1,-1$"),o("5","$x=0,1,-1$")],
    answer: "1",
    explanation: "1행을 다른 행에서 빼는 등 행 연산 후 $-x(x-1)^3=0$이므로 $x=0,1$." }),

  // ========== DT4 수반행렬 ==========
  build({ testNo: 4, num: 1, unit: "행렬", concept: "수반행렬", difficulty: "easyMedium",
    question: "행렬 $A=\\begin{pmatrix}2&1&3\\\\-1&2&0\\\\2&-2&1\\end{pmatrix}$의 수반행렬에서 첫 번째 열의 성분들의 합은?",
    options: [o("1","$1$"),o("2","$2$"),o("3","$0$"),o("4","$-1$"),o("5","$-2$")],
    answer: "1",
    explanation: "수반행렬의 첫 번째 열 = 여인수행렬의 첫 번째 행. $C_{11}+C_{12}+C_{13}=2-(-1)+(-2)=1$." }),
  build({ testNo: 4, num: 2, unit: "행렬", concept: "수반행렬", difficulty: "easyMedium",
    question: "$A=\\begin{pmatrix}0&0&1\\\\0&1&c\\\\1&c&c^2\\end{pmatrix},\\ c\\ne 0$의 $\\mathrm{adj}(A)$에서 제 3행의 원소들의 합은?",
    options: [o("1","$1$"),o("2","$0$"),o("3","$-1$"),o("4","$c$"),o("5","$-c$")],
    answer: "3",
    explanation: "수반행렬 3행 = 여인수행렬 3열의 원소의 합. $C_{13}+C_{23}+C_{33}=\\begin{vmatrix}0&1\\\\1&c\\end{vmatrix}-\\begin{vmatrix}0&0\\\\1&c\\end{vmatrix}+\\begin{vmatrix}0&0\\\\0&1\\end{vmatrix}=-1$." }),
  build({ testNo: 4, num: 3, unit: "행렬", concept: "adj(A)·A", difficulty: "easyMedium",
    question: "$A=\\begin{pmatrix}1&0&7\\\\1&1&7\\\\7&1&1\\end{pmatrix}$일 때 $\\mathrm{adj}A\\cdot A$의 대각성분의 합은?",
    options: [o("1","$-144$"),o("2","$-48$"),o("3","$48$"),o("4","$144$"),o("5","$0$")],
    answer: "1",
    explanation: "$\\mathrm{adj}(A)A=\\det(A)I$. $\\det A=-48$이므로 대각합 $-48\\times 3=-144$." }),
  build({ testNo: 4, num: 4, unit: "행렬", concept: "adj 행렬식", difficulty: "easyMedium",
    question: "$A=\\begin{pmatrix}1&-2&-3&0\\\\1&3&3&0\\\\0&0&1&0\\\\0&0&0&1\\end{pmatrix}$의 $\\det(\\mathrm{adj}(A))$의 값은?",
    options: [o("1","$25$"),o("2","$50$"),o("3","$100$"),o("4","$125$"),o("5","$625$")],
    answer: "4",
    explanation: "$|\\mathrm{adj}(A)|=|A|^{n-1}$. $|A|=5,n=4$이므로 $5^3=125$." }),
  build({ testNo: 4, num: 5, unit: "행렬", concept: "adj 행렬식", difficulty: "easyMedium",
    question: "$A=\\begin{pmatrix}1&0&-2\\\\0&1&0\\\\0&0&2\\end{pmatrix}$의 $\\det(\\mathrm{adj}(A^2))$의 값은?",
    options: [o("1","$4$"),o("2","$8$"),o("3","$16$"),o("4","$32$"),o("5","$64$")],
    answer: "3",
    explanation: "$|\\mathrm{adj}(A^2)|=|A^2|^{n-1}=|A|^{2(n-1)}=2^4=16$." }),
  build({ testNo: 4, num: 6, unit: "행렬", concept: "adj(adj(A))", difficulty: "easyMedium",
    question: "$A=\\begin{pmatrix}-1&1&2&0\\\\0&2&-1&0\\\\1&0&1&2\\\\0&1&2&2\\end{pmatrix}$일 때 $\\mathrm{adj}(\\mathrm{adj}(A))$의 값은?",
    options: [o("1","$4A$"),o("2","$8A$"),o("3","$16A$"),o("4","$-16A$"),o("5","$32A$")],
    answer: "3",
    explanation: "$\\mathrm{adj}(\\mathrm{adj}(A))=|A|^{n-2}A$. $|A|=-4,n=4$이므로 $(-4)^2A=16A$." }),

  // ========== DT5 역행렬 ==========
  build({ testNo: 5, num: 1, unit: "행렬", concept: "역행렬 존재 조건", difficulty: "easyMedium",
    question: "행렬 $A=\\begin{pmatrix}a-a&a\\\\1&a&1\\\\0&0&a\\end{pmatrix}$가 역행렬을 갖지 않도록 하는 모든 실수 $a$의 값의 합은?",
    options: [o("1","$0$"),o("2","$-1$"),o("3","$1$"),o("4","$2$"),o("5","$-2$")],
    answer: "2",
    explanation: "$\\det A=a^3+a^2=0\\Rightarrow a^2(a+1)=0$. 근 $a=0,0,-1$, 서로 다른 실근의 합 $-1$." }),
  build({ testNo: 5, num: 2, unit: "행렬", concept: "역행렬 성분합", difficulty: "easyMedium",
    question: "행렬 $\\begin{pmatrix}1&1&1\\\\0&-1&2\\\\0&0&-1\\end{pmatrix}$의 역행렬이 $(a_{ij})$일 때 $\\sum_{i=1}^{3}\\sum_{j=1}^{3}a_{ij}$의 값은?",
    options: [o("1","$0$"),o("2","$1$"),o("3","$2$"),o("4","$-1$"),o("5","$3$")],
    answer: "2",
    explanation: "역행렬 $\\begin{pmatrix}1&1&3\\\\0&-1&-2\\\\0&0&-1\\end{pmatrix}$의 모든 성분합 $1$." }),
  build({ testNo: 5, num: 3, unit: "행렬", concept: "역행렬 행 성분합", difficulty: "easyMedium",
    question: "$A=\\begin{pmatrix}1&0&0\\\\p&1&0\\\\p^2&p&1\\end{pmatrix}$의 역행렬 $A^{-1}$의 제 3행의 원소의 합은?",
    options: [o("1","$1+p$"),o("2","$1-p$"),o("3","$p$"),o("4","$-p$"),o("5","$1$")],
    answer: "2",
    explanation: "$A^{-1}$의 3행 = $\\frac{1}{|A|}\\times$ 3열의 여인수. $|A|=1$이고 $M_{13}-M_{23}+M_{33}=p^2-p^2+1$ 등 계산 후 $1-p$." }),
  build({ testNo: 5, num: 4, unit: "행렬", concept: "역행렬 행렬식", difficulty: "easy",
    question: "$A=\\begin{pmatrix}2&2&0\\\\-2&1&1\\\\3&0&1\\end{pmatrix}$의 $\\det(A^{-1})$의 값은?",
    options: [o("1","$\\dfrac{1}{8}$"),o("2","$\\dfrac{1}{10}$"),o("3","$\\dfrac{1}{12}$"),o("4","$\\dfrac{1}{6}$"),o("5","$12$")],
    answer: "3",
    explanation: "$|A|=12$이므로 $\\det(A^{-1})=\\frac{1}{12}$." }),
  build({ testNo: 5, num: 5, unit: "행렬", concept: "행렬식 성질", difficulty: "easyMedium",
    question: "$3\\times 3$ 행렬 $A,B$에 대해 $\\det(A)=8,\\det(B)=5$일 때 $\\det(2A^{-1}B^T)$의 값은?",
    options: [o("1","$3$"),o("2","$5$"),o("3","$8$"),o("4","$10$"),o("5","$40$")],
    answer: "2",
    explanation: "$|2A^{-1}B^T|=2^3\\cdot\\frac{1}{|A|}\\cdot|B|=8\\cdot\\frac{1}{8}\\cdot 5=5$." }),
  build({ testNo: 5, num: 6, unit: "행렬", concept: "행렬방정식", difficulty: "easyMedium",
    question: "$A=\\begin{pmatrix}1&2&4\\\\0&-1&1\\\\2&3&8\\end{pmatrix}$에 대하여 $AB=A^2+2A+E$를 만족시키는 행렬 $B$의 모든 성분의 합은? ($E$는 $3\\times 3$ 항등행렬)",
    options: [o("1","$10$"),o("2","$15$"),o("3","$20$"),o("4","$25$"),o("5","$30$")],
    answer: "3",
    explanation: "$B=A+2I+A^{-1}$. $|A|=1$로 $A^{-1}$ 계산 후 $A+2I+A^{-1}$의 성분합 $20$." }),

  // ========== DT6 가우스소거, LU분해, rank ==========
  build({ testNo: 6, num: 1, unit: "행렬", concept: "케일리해밀턴 역행렬", difficulty: "easyMedium",
    question: "정사각행렬 $A$가 $A^3-3A+2I=O$를 만족시킬 때 $A$의 역행렬은?",
    options: [
      o("1","$-\\dfrac{1}{2}A^2+\\dfrac{3}{2}I$"),
      o("2","$\\dfrac{1}{2}A^2-\\dfrac{3}{2}I$"),
      o("3","$\\dfrac{1}{2}A^2+\\dfrac{3}{2}I$"),
      o("4","$-A^2+3I$"),
      o("5","$A^2-3I$")
    ], answer: "1",
    explanation: "$2I=-A^3+3A=A(-A^2+3I)$이므로 $A^{-1}=-\\frac{1}{2}A^2+\\frac{3}{2}I$." }),
  build({ testNo: 6, num: 2, unit: "행렬", concept: "기약행사다리꼴", difficulty: "medium",
    question: "첫째, 둘째, 넷째 열이 각각 $\\begin{pmatrix}1\\\\-1\\\\3\\end{pmatrix},\\begin{pmatrix}0\\\\-1\\\\1\\end{pmatrix},\\begin{pmatrix}1\\\\-2\\\\1\\end{pmatrix}$인 행렬 $A$의 기약행사다리꼴이 $\\begin{pmatrix}1&0&2&0&-2\\\\0&1&-5&0&-3\\\\0&0&0&1&6\\end{pmatrix}$일 때 $A$의 $(2,5)$ 성분은?",
    options: [o("1","$-7$"),o("2","$-5$"),o("3","$-3$"),o("4","$5$"),o("5","$7$")],
    answer: "1",
    explanation: "RREF 마지막 열에서 $d=4,e=-7$. $A$의 $(2,5)$ 성분 $-7$." }),
  build({ testNo: 6, num: 3, unit: "행렬", concept: "연립방정식", difficulty: "easyMedium",
    question: "$\\begin{cases}2x_1-2x_2+x_3+2x_4=8\\\\x_1+3x_2+x_3+x_4=3\\\\3x_1+x_2+2x_3-x_4=-1\\end{cases}$의 해 중 $x_4$의 값은?",
    options: [o("1","$1$"),o("2","$2$"),o("3","$3$"),o("4","$4$"),o("5","$5$")],
    answer: "3",
    explanation: "행 연산 후 $-4x_4=-12\\Rightarrow x_4=3$." }),
  build({ testNo: 6, num: 4, unit: "행렬", concept: "LU 분해", difficulty: "medium",
    question: "$A=\\begin{pmatrix}1&1&1\\\\1&2&1\\\\0&-1&2\\end{pmatrix}$의 $LU$분해는?",
    options: [
      o("1","$L=\\begin{pmatrix}1&0&0\\\\1&1&0\\\\0&-1&1\\end{pmatrix},U=\\begin{pmatrix}1&1&1\\\\0&1&0\\\\0&0&2\\end{pmatrix}$"),
      o("2","$L=\\begin{pmatrix}1&0&0\\\\0&1&0\\\\0&-1&1\\end{pmatrix},U=\\begin{pmatrix}1&1&1\\\\0&2&1\\\\0&0&3\\end{pmatrix}$"),
      o("3","$L=\\begin{pmatrix}1&0&0\\\\1&1&0\\\\1&-1&1\\end{pmatrix},U=\\begin{pmatrix}1&1&1\\\\0&1&0\\\\0&0&2\\end{pmatrix}$"),
      o("4","$L=I,U=A$"),
      o("5","$L=A,U=I$")
    ], answer: "1",
    explanation: "행 1 → 행 2 빼서 $E_1$, 행 3에 행 2 더해 $E_2$. $A=E_1^{-1}E_2^{-1}U$로 분해." }),
  build({ testNo: 6, num: 5, unit: "행렬", concept: "rank", difficulty: "easyMedium",
    question: "행렬 $B=\\begin{pmatrix}1&2&4&3\\\\3&-1&2&-2\\\\5&-4&0&-7\\end{pmatrix}$의 계수는?",
    options: [o("1","$0$"),o("2","$1$"),o("3","$2$"),o("4","$3$"),o("5","$4$")],
    answer: "3",
    explanation: "행 연산 후 0이 아닌 행 수 $2$." }),
  build({ testNo: 6, num: 6, unit: "행렬", concept: "rank", difficulty: "easyMedium",
    question: "$A=\\begin{pmatrix}-2&-5&8&0&-17\\\\1&3&-5&-1&5\\\\2&4&-6&-2&4\\\\1&7&-13&-5&-3\\end{pmatrix}$의 계수(rank)는?",
    options: [o("1","$1$"),o("2","$2$"),o("3","$3$"),o("4","$4$"),o("5","$5$")],
    answer: "3",
    explanation: "행 연산 후 0이 아닌 행 3개 → rank $=3$." }),

  // ========== DT7 연립방정식, 사잇각 ==========
  build({ testNo: 7, num: 1, unit: "행렬", concept: "연립방정식 해 존재성", difficulty: "easyMedium",
    question: "$\\begin{cases}x+2y+3z=1\\\\x+3y+5z=0\\\\y+cz=1\\end{cases}$의 해가 존재하지 않는 $c$의 값은?",
    options: [o("1","$0$"),o("2","$1$"),o("3","$2$"),o("4","$-1$"),o("5","$3$")],
    answer: "3",
    explanation: "행 연산 결과 $\\mathrm{rank}(A)<\\mathrm{rank}(A|B)$가 되려면 $c=2$." }),
  build({ testNo: 7, num: 2, unit: "행렬", concept: "연립방정식 해 존재성", difficulty: "easyMedium",
    question: "$\\begin{cases}2x-y+z+w=1\\\\x+2y-z+4w=2\\\\x+7y-4z+11w=c\\end{cases}$이 해를 갖도록 하는 $c$의 값은?",
    options: [o("1","$1$"),o("2","$2$"),o("3","$3$"),o("4","$5$"),o("5","$7$")],
    answer: "4",
    explanation: "행 연산 후 마지막 행이 $0=c-5$가 되어야 하므로 $c=5$." }),
  build({ testNo: 7, num: 3, unit: "행렬", concept: "연립방정식 해 존재성", difficulty: "easyMedium",
    question: "$\\begin{cases}x+y+7z=-7\\\\2x+3y+17z=-16\\\\x+2y+(a^2+1)z=3a\\end{cases}$이 해를 갖지 않도록 하는 $a$의 값은?",
    options: [o("1","$-3$"),o("2","$-1$"),o("3","$1$"),o("4","$3$"),o("5","$2$")],
    answer: "4",
    explanation: "행 연산 후 마지막 행 $(a^2-9)z=3a+9$. $a^2=9$이고 $3a+9\\ne 0$이려면 $a=3$." }),
  build({ testNo: 7, num: 4, unit: "행렬", concept: "무수히 많은 해", difficulty: "easyMedium",
    question: "$\\begin{cases}ax+y+z=0\\\\ay+z=0\\\\x-y+az=0\\end{cases}$이 무수히 많은 해를 갖기 위한 실수 $a$의 값은?",
    options: [o("1","$1$"),o("2","$-1$"),o("3","$0$"),o("4","$2$"),o("5","$-2$")],
    answer: "2",
    explanation: "$|A|=a^3+1=0\\Rightarrow a=-1$." }),
  build({ testNo: 7, num: 5, unit: "벡터와 공간도형", concept: "벡터 사잇각", difficulty: "easy",
    question: "두 벡터 $\\vec v=(-1,1,2),\\ \\vec w=(1,2,1)$이 이루는 각은?",
    options: [o("1","$\\dfrac{\\pi}{6}$"),o("2","$\\dfrac{\\pi}{4}$"),o("3","$\\dfrac{\\pi}{3}$"),o("4","$\\dfrac{\\pi}{2}$"),o("5","$\\dfrac{2\\pi}{3}$")],
    answer: "3",
    explanation: "$\\cos\\theta=\\frac{-1+2+2}{\\sqrt 6\\sqrt 6}=\\frac{1}{2}\\Rightarrow\\theta=\\frac{\\pi}{3}$." }),
  build({ testNo: 7, num: 6, unit: "벡터와 공간도형", concept: "벡터 사잇각", difficulty: "easy",
    question: "공간상의 세 점 $A(-1,0,2),\\ B(0,3,2),\\ C(2,1,2)$에 대해서 선분 $\\overrightarrow{AB}$와 $\\overrightarrow{AC}$의 예각을 $\\theta$라 할 때 $\\sin\\theta$의 값은?",
    options: [o("1","$\\dfrac{1}{5}$"),o("2","$\\dfrac{2}{5}$"),o("3","$\\dfrac{3}{5}$"),o("4","$\\dfrac{4}{5}$"),o("5","$1$")],
    answer: "4",
    explanation: "$\\overrightarrow{AB}=(1,3,0),\\overrightarrow{AC}=(3,1,0)$. $\\cos\\theta=\\frac{6}{10}=\\frac{3}{5}\\Rightarrow\\sin\\theta=\\frac{4}{5}$." }),

  // ========== DT8 수직, 사영, 외적 ==========
  build({ testNo: 8, num: 1, unit: "벡터와 공간도형", concept: "벡터 수직 조건", difficulty: "easyMedium",
    question: "두 벡터 $(a,1,-a)$와 $(a^2,a,5)$가 서로 수직이 되게 하는 $a$의 모든 값의 합을 구하시오.",
    options: [o("1","$0$"),o("2","$1$"),o("3","$-1$"),o("4","$2$"),o("5","$4$")],
    answer: "1",
    explanation: "$a^3+a-5a=a^3-4a=0\\Rightarrow a(a^2-4)=0$. $a=0,\\pm 2$, 합 $0$." }),
  build({ testNo: 8, num: 2, unit: "벡터와 공간도형", concept: "벡터 수직 조건", difficulty: "easyMedium",
    question: "공간벡터 $\\vec a=(x,1,-2),\\ \\vec b=(0,y,2),\\ \\vec c=(1,3,z)$가 서로 수직일 때 $x+y+z$의 값은?",
    options: [o("1","$-7$"),o("2","$-17$"),o("3","$0$"),o("4","$7$"),o("5","$17$")],
    answer: "2",
    explanation: "$\\vec a\\cdot\\vec b=y-4=0\\Rightarrow y=4$. $\\vec b\\cdot\\vec c=3y+2z=0\\Rightarrow z=-6$. $\\vec a\\cdot\\vec c=x+3-2z=0\\Rightarrow x=-15$. 합 $-17$." }),
  build({ testNo: 8, num: 3, unit: "벡터와 공간도형", concept: "벡터 사영", difficulty: "easyMedium",
    question: "두 벡터 $u=\\langle 3,-5,1\\rangle,\\ v=\\langle 0,2,-2\\rangle$에 대하여 $u$ 위로 $v$의 벡터사영은?",
    options: [
      o("1","$-\\dfrac{12}{35}\\langle 3,-5,1\\rangle$"),
      o("2","$\\dfrac{12}{35}\\langle 3,-5,1\\rangle$"),
      o("3","$-\\dfrac{12}{35}\\langle 0,2,-2\\rangle$"),
      o("4","$\\dfrac{12}{35}\\langle 0,2,-2\\rangle$"),
      o("5","$\\langle 0,0,0\\rangle$")
    ], answer: "1",
    explanation: "$\\mathrm{proj}_u v=\\frac{u\\cdot v}{u\\cdot u}u=\\frac{-10-2}{35}\\langle 3,-5,1\\rangle=-\\frac{12}{35}\\langle 3,-5,1\\rangle$." }),
  build({ testNo: 8, num: 4, unit: "벡터와 공간도형", concept: "스칼라/벡터 사영", difficulty: "easyMedium",
    question: "벡터 $u=\\langle -1,1,-2\\rangle$를 벡터 $v=\\langle 1,0,-1\\rangle$에 사영할 때, 스칼라사영 $a$와 벡터사영 $\\langle b,c,d\\rangle$에 대하여 $a^2+b^2+c^2+d^2$의 값은?",
    options: [o("1","$\\dfrac{1}{2}$"),o("2","$1$"),o("3","$\\dfrac{3}{2}$"),o("4","$2$"),o("5","$3$")],
    answer: "2",
    explanation: "$a=\\frac{u\\cdot v}{|v|}=\\frac{1}{\\sqrt 2}$. 벡터사영 $=\\frac{1}{2}(1,0,-1)$. $\\frac{1}{2}+\\frac{1}{4}+0+\\frac{1}{4}=1$." }),
  build({ testNo: 8, num: 5, unit: "벡터와 공간도형", concept: "외적", difficulty: "easyMedium",
    question: "두 벡터 $\\vec i+2\\vec j+3\\vec k$와 $4\\vec i+5\\vec j+6\\vec k$에 모두 수직인 벡터는?",
    options: [
      o("1","$(-1,2,-1)$"),
      o("2","$(1,2,1)$"),
      o("3","$(1,1,1)$"),
      o("4","$(2,1,-1)$"),
      o("5","$(0,0,0)$")
    ], answer: "1",
    explanation: "외적 $\\begin{vmatrix}i&j&k\\\\1&2&3\\\\4&5&6\\end{vmatrix}=(-3,6,-3)//(-1,2,-1)$." }),
  build({ testNo: 8, num: 6, unit: "벡터와 공간도형", concept: "삼중적 항등식", difficulty: "easyMedium",
    question: "두 벡터 $\\vec a=4\\vec i-2\\vec j+5\\vec k,\\ \\vec b=3\\vec i+\\vec j-\\vec k$에 대하여 $(\\vec a+\\vec b)\\cdot(\\vec a\\times\\vec b)$를 구하라.",
    options: [o("1","$0$"),o("2","$1$"),o("3","$-1$"),o("4","$5$"),o("5","$-5$")],
    answer: "1",
    explanation: "$\\vec a\\times\\vec b$는 $\\vec a$와 $\\vec b$ 모두에 수직이므로 $(\\vec a+\\vec b)\\cdot(\\vec a\\times\\vec b)=0$." }),

  // ========== DT9 외적, 면적, 삼중적 ==========
  build({ testNo: 9, num: 1, unit: "벡터와 공간도형", concept: "외적 항등식", difficulty: "easy",
    question: "$3$차원 직교좌표계의 기본단위벡터 $\\vec i,\\vec j,\\vec k$에 대하여 $(\\vec i\\times\\vec j)\\times\\vec k+\\vec i\\times(\\vec j\\times\\vec i)=?$",
    options: [o("1","$\\vec i$"),o("2","$\\vec j$"),o("3","$\\vec k$"),o("4","$-\\vec k$"),o("5","$\\vec 0$")],
    answer: "2",
    explanation: "$\\vec i\\times\\vec j=\\vec k,\\ \\vec j\\times\\vec i=-\\vec k$. $\\vec k\\times\\vec k+\\vec i\\times(-\\vec k)=\\vec 0+\\vec j=\\vec j$." }),
  build({ testNo: 9, num: 2, unit: "벡터와 공간도형", concept: "평행사변형 면적", difficulty: "easy",
    question: "$3$차원 공간의 세 점 $A=(1,1,1),\\ B=(2,3,4),\\ C=(2,-4,5)$를 꼭짓점으로 하는 평행사변형의 넓이는?",
    options: [o("1","$\\sqrt{579}$"),o("2","$\\sqrt{469}$"),o("3","$\\sqrt{279}$"),o("4","$\\sqrt{129}$"),o("5","$\\sqrt{59}$")],
    answer: "1",
    explanation: "$\\overrightarrow{AB}=(1,2,3),\\overrightarrow{AC}=(1,-5,4)$. $\\overrightarrow{AB}\\times\\overrightarrow{AC}=(23,-1,-7)$. 크기 $\\sqrt{579}$." }),
  build({ testNo: 9, num: 3, unit: "벡터와 공간도형", concept: "평행사변형 면적", difficulty: "easy",
    question: "좌표평면의 두 점 $A(1,3),\\ B(4,1)$에 대하여 $\\overrightarrow{OA}$와 $\\overrightarrow{OB}$로 만들어지는 평행사변형의 넓이는? ($O$는 원점)",
    options: [o("1","$5$"),o("2","$7$"),o("3","$11$"),o("4","$13$"),o("5","$17$")],
    answer: "3",
    explanation: "외적 $\\overrightarrow{OA}\\times\\overrightarrow{OB}=(0,0,-11)$. 크기 $11$." }),
  build({ testNo: 9, num: 4, unit: "벡터와 공간도형", concept: "삼각형 면적", difficulty: "easy",
    question: "$3$차원 공간 $R^3$에 있는 세 점 $P_1(1,1,1),\\ P_2(1,2,1),\\ P_3(2,2,4)$로 만들어지는 삼각형의 면적은?",
    options: [o("1","$\\dfrac{\\sqrt{10}}{2}$"),o("2","$\\sqrt{10}$"),o("3","$\\dfrac{\\sqrt 5}{2}$"),o("4","$\\dfrac{\\sqrt{30}}{2}$"),o("5","$\\dfrac{\\sqrt 2}{2}$")],
    answer: "1",
    explanation: "$\\overrightarrow{P_1P_2}\\times\\overrightarrow{P_1P_3}=(3,0,-1)$. 면적 $=\\frac{1}{2}\\sqrt{10}$." }),
  build({ testNo: 9, num: 5, unit: "벡터와 공간도형", concept: "삼각형 면적", difficulty: "easy",
    question: "벡터 $\\vec A=2\\hat i+\\hat j+3\\hat k$와 $\\vec B=-2\\hat i+3\\hat j-2\\hat k$가 두 변을 이루는 삼각형의 면적은?",
    options: [o("1","$\\dfrac{1}{2}\\sqrt{89}$"),o("2","$\\dfrac{1}{2}\\sqrt{189}$"),o("3","$\\sqrt{189}$"),o("4","$\\dfrac{1}{2}\\sqrt{289}$"),o("5","$\\sqrt{89}$")],
    answer: "2",
    explanation: "$\\vec A\\times\\vec B=(-11,-2,8)$. 면적 $=\\frac{1}{2}\\sqrt{121+4+64}=\\frac{1}{2}\\sqrt{189}$." }),
  build({ testNo: 9, num: 6, unit: "벡터와 공간도형", concept: "스칼라 삼중적", difficulty: "easyMedium",
    question: "세 벡터 $\\vec a=(2,0,3),\\ \\vec b=(0,6,2),\\ \\vec c=(3,3,0)$에 대해 $\\vec a\\cdot(\\vec b\\times\\vec c)$의 값을 구하면?",
    options: [o("1","$-66$"),o("2","$-36$"),o("3","$36$"),o("4","$66$"),o("5","$0$")],
    answer: "1",
    explanation: "$\\det\\begin{pmatrix}2&0&3\\\\0&6&2\\\\3&3&0\\end{pmatrix}=-66$." }),

  // ========== DT10 평행육면체, 사면체 ==========
  build({ testNo: 10, num: 1, unit: "벡터와 공간도형", concept: "외적의 점곱 항등식", difficulty: "medium",
    question: "$3$차원 공간의 세 단위벡터 $A,B,C$가 $A\\cdot B=0,\\ A\\cdot C=0,\\ B\\cdot C=\\dfrac{1}{2}$를 만족할 때 $(A\\times B)\\cdot(A\\times C)$의 값을 구하면?",
    options: [o("1","$0$"),o("2","$\\dfrac{1}{2}$"),o("3","$1$"),o("4","$-\\dfrac{1}{2}$"),o("5","$2$")],
    answer: "2",
    explanation: "$(A\\times B)\\cdot(A\\times C)=(A\\cdot A)(B\\cdot C)-(A\\cdot C)(B\\cdot A)=1\\cdot\\frac{1}{2}-0=\\frac{1}{2}$." }),
  build({ testNo: 10, num: 2, unit: "벡터와 공간도형", concept: "평행육면체 부피", difficulty: "easy",
    question: "세 벡터 $\\vec a=2\\hat i+2\\hat j,\\ \\vec b=-\\hat i+2\\hat k,\\ \\vec c=4\\hat j+3\\hat k$로 결정되는 평행육면체의 부피는?",
    options: [o("1","$2$"),o("2","$5$"),o("3","$10$"),o("4","$15$"),o("5","$20$")],
    answer: "3",
    explanation: "$|\\vec a\\cdot(\\vec b\\times\\vec c)|=|\\det\\begin{pmatrix}2&2&0\\\\-1&0&2\\\\0&4&3\\end{pmatrix}|=10$." }),
  build({ testNo: 10, num: 3, unit: "벡터와 공간도형", concept: "평행육면체 부피", difficulty: "easy",
    question: "행렬 $A=\\begin{pmatrix}1&2&3\\\\1&0&2\\\\-1&2&1\\end{pmatrix}$의 열벡터들에 의해 만들어지는 평행육면체의 부피는?",
    options: [o("1","$2$"),o("2","$3$"),o("3","$4$"),o("4","$5$"),o("5","$8$")],
    answer: "3",
    explanation: "$|\\det A|=4$." }),
  build({ testNo: 10, num: 4, unit: "벡터와 공간도형", concept: "평행육면체 부피", difficulty: "easyMedium",
    question: "네 점 $A(1,1,1),\\ B(4,2,1),\\ C(2,5,3),\\ D(1,1,3)$을 꼭짓점으로 가지는 평행육면체의 부피는?",
    options: [o("1","$11$"),o("2","$16$"),o("3","$18$"),o("4","$22$"),o("5","$24$")],
    answer: "4",
    explanation: "$\\overrightarrow{AB}=(3,1,0),\\overrightarrow{AC}=(1,4,2),\\overrightarrow{AD}=(0,0,2)$. $|\\det|=22$." }),
  build({ testNo: 10, num: 5, unit: "벡터와 공간도형", concept: "사면체 부피", difficulty: "easyMedium",
    question: "좌표공간에서 네 점 $A(-1,2,0),\\ B(2,1,-3),\\ C(1,0,1),\\ D(3,-2,3)$을 꼭짓점으로 하는 사면체의 부피는?",
    options: [o("1","$\\dfrac{1}{3}$"),o("2","$\\dfrac{2}{3}$"),o("3","$1$"),o("4","$\\dfrac{4}{3}$"),o("5","$2$")],
    answer: "2",
    explanation: "$\\frac{1}{6}|\\det\\begin{pmatrix}3&-1&-3\\\\2&-2&1\\\\4&-4&3\\end{pmatrix}|=\\frac{1}{6}|-4|=\\frac{2}{3}$." }),
  build({ testNo: 10, num: 6, unit: "벡터와 공간도형", concept: "사면체 부피", difficulty: "easyMedium",
    question: "좌표공간의 네 점 $(2,0,1),\\ (1,2,-4),\\ (2,-9,4),\\ (2,0,3)$을 꼭짓점으로 가지는 삼각뿔의 부피는?",
    options: [o("1","$1$"),o("2","$2$"),o("3","$3$"),o("4","$4$"),o("5","$6$")],
    answer: "3",
    explanation: "$\\frac{1}{6}|\\det\\begin{pmatrix}-1&2&-5\\\\0&-9&3\\\\0&0&2\\end{pmatrix}|=\\frac{1}{6}|18|=3$." }),

  // ========== DT11 평면 방정식 ==========
  build({ testNo: 11, num: 1, unit: "벡터와 공간도형", concept: "평면의 법선벡터", difficulty: "easyMedium",
    question: "세 점 $P(1,2,-1),\\ Q(2,3,1),\\ R(3,1,0)$을 포함하는 평면에 수직인 벡터는?",
    options: [
      o("1","$\\langle -1,-1,1\\rangle$"),
      o("2","$\\langle 1,1,1\\rangle$"),
      o("3","$\\langle 1,-1,2\\rangle$"),
      o("4","$\\langle 2,1,-1\\rangle$"),
      o("5","$\\langle 0,1,1\\rangle$")
    ], answer: "1",
    explanation: "$\\overrightarrow{PQ}=(1,1,2),\\overrightarrow{PR}=(2,-1,1)$. 외적 $=(3,3,-3)//\\langle 1,1,-1\\rangle$ 또는 $\\langle -1,-1,1\\rangle$." }),
  build({ testNo: 11, num: 2, unit: "벡터와 공간도형", concept: "평면의 방정식", difficulty: "easyMedium",
    question: "세 점 $(4,-3,5),(1,3,5),(5,1,6)$을 지나는 평면의 방정식이 $ax+by+cz=-25$일 때 $a+b+c$의 값은?",
    options: [o("1","$-5$"),o("2","$-3$"),o("3","$0$"),o("4","$3$"),o("5","$5$")],
    answer: "2",
    explanation: "법선 $(2,1,-6)$ → $2x+y-6z=-25$. $a+b+c=2+1-6=-3$." }),
  build({ testNo: 11, num: 3, unit: "벡터와 공간도형", concept: "평면 위의 점", difficulty: "easyMedium",
    question: "삼차원공간의 세 점 $A=(1,-1,2),\\ B=(-1,1,4),\\ C=(1,3,-2)$를 지나는 평면 위에 놓이지 않은 점은?",
    options: [
      o("1","$(-3,5,4)$"),
      o("2","$(2,1,-1)$"),
      o("3","$(-2,3,4)$"),
      o("4","$(7,-4,-7)$"),
      o("5","$(1,-1,2)$")
    ], answer: "2",
    explanation: "법선 $(2,1,1)$, 평면 $2x+y+z=3$. ②: $4+1-1=4\\ne 3$." }),
  build({ testNo: 11, num: 4, unit: "벡터와 공간도형", concept: "평면의 법선벡터", difficulty: "easyMedium",
    question: "$\\det\\begin{pmatrix}x&y&z&1\\\\1&1&3&1\\\\1&2&2&1\\\\2&1&2&1\\end{pmatrix}=0$을 만족하는 $R^3$의 점 $(x,y,z)$로 이루어진 평면에 수직인 벡터는?",
    options: [
      o("1","$\\langle 1,1,1\\rangle$"),
      o("2","$\\langle 1,-1,1\\rangle$"),
      o("3","$\\langle 1,1,-1\\rangle$"),
      o("4","$\\langle -1,1,1\\rangle$"),
      o("5","$\\langle 0,1,1\\rangle$")
    ], answer: "1",
    explanation: "행렬식 $=0$은 세 점 $A(1,1,3),B(1,2,2),C(2,1,2)$을 지나는 평면. $\\overrightarrow{AB}\\times\\overrightarrow{AC}=(-1,-1,-1)//\\langle 1,1,1\\rangle$." }),
  build({ testNo: 11, num: 5, unit: "벡터와 공간도형", concept: "수직이등분 평면", difficulty: "easyMedium",
    question: "점 $(2,-1,1)$과 점 $(3,1,5)$로부터 같은 거리에 있는 평면의 방정식은?",
    options: [
      o("1","$2x+4y+8z=29$"),
      o("2","$x+2y+4z=29$"),
      o("3","$2x+4y+8z=15$"),
      o("4","$x+y+z=5$"),
      o("5","$x-y-z=0$")
    ], answer: "1",
    explanation: "$\\overrightarrow{AB}=(1,2,4)$ 법선, 중점 $(5/2,0,3)$. $x+2y+4z=29/2$ 즉 $2x+4y+8z=29$." }),
  build({ testNo: 11, num: 6, unit: "벡터와 공간도형", concept: "평면에 수직인 직선", difficulty: "easyMedium",
    question: "평면 $2x-y+3z=5$에 수직이고 점 $(1,0,1)$을 지나는 직선이 있다. 다음 중 이 직선 위에 있는 점은?",
    options: [
      o("1","$(3,-1,4)$"),
      o("2","$(1,1,-2)$"),
      o("3","$(5,-2,3)$"),
      o("4","$(-3,1,-5)$"),
      o("5","$(2,-1,3)$")
    ], answer: "1",
    explanation: "방향비 $\\langle 2,-1,3\\rangle$. 매개식 $x=2t+1,y=-t,z=3t+1$. $t=1$일 때 $(3,-1,4)$." }),

  // ========== DT12 평면 정의 ==========
  build({ testNo: 12, num: 1, unit: "벡터와 공간도형", concept: "직선에 수직인 평면", difficulty: "easyMedium",
    question: "두 점 $A(1,0,-2),\\ B(2,-1,3)$를 지나는 직선에 수직이고 점 $C(3,1,-1)$를 지나는 평면이 있다. 다음 중 이 평면 위에 있는 점은?",
    options: [
      o("1","$(1,1,2)$"),
      o("2","$(-1,2,0)$"),
      o("3","$(0,2,1)$"),
      o("4","$(2,-1,-1)$"),
      o("5","$(-2,-1,1)$")
    ], answer: "2",
    explanation: "$\\overrightarrow{AB}=(1,-1,5)$ 법선. 평면 $x-y+5z=-3$. ②: $-1-2+0=-3$ ✓." }),
  build({ testNo: 12, num: 2, unit: "벡터와 공간도형", concept: "점/직선 포함 평면", difficulty: "easyMedium",
    question: "점 $(1,-1,1)$과 직선 $\\dfrac{x-1}{3}=\\dfrac{y+1}{2}=z$를 포함하는 평면의 방정식은?",
    options: [
      o("1","$2x-3y-5=0$"),
      o("2","$x-y+z=1$"),
      o("3","$x+2y+3z=2$"),
      o("4","$3x+2y+z=2$"),
      o("5","$x+y+z=1$")
    ], answer: "1",
    explanation: "$A(1,-1,1),B(1,-1,0)$이라 하면 $\\overrightarrow{AB}=(0,0,-1),\\vec d=(3,2,1)$. 법선 $\\vec n=\\vec d\\times\\overrightarrow{AB}=(-2,3,0)$. 평면 $2x-3y=5\\Rightarrow 2x-3y-5=0$." }),
  build({ testNo: 12, num: 3, unit: "벡터와 공간도형", concept: "두 직선 포함 평면", difficulty: "easyMedium",
    question: "두 직선 $l_1:x=1+t,y=1-t,z=2t,\\ l_2:x=2-s,y=s,z=2$를 포함하는 평면의 방정식은?",
    options: [
      o("1","$x+y=2$"),
      o("2","$x-y=0$"),
      o("3","$x+y+z=3$"),
      o("4","$2x+y=3$"),
      o("5","$x+2y=3$")
    ], answer: "1",
    explanation: "방향 $(1,-1,2),(-1,1,0)$. 외적 $=(-2,-2,0)//\\langle 1,1,0\\rangle$. 점 $(1,1,0)$ → $x+y=2$." }),
  build({ testNo: 12, num: 4, unit: "벡터와 공간도형", concept: "평행한 두 직선 포함 평면", difficulty: "easyMedium",
    question: "평행한 두 직선 $l_1:x=1+5t,y=-1-2t,z=t$와 $l_2:x=5+5t,y=-4-2t,z=2+t$를 동시에 포함하는 평면 $\\Pi$ 위의 점이 아닌 것은?",
    options: [
      o("1","$(0,4,-4)$"),
      o("2","$(-1,-3,2)$"),
      o("3","$(5,3,-4)$"),
      o("4","$(-6,-1,1)$"),
      o("5","$(1,-1,0)$")
    ], answer: "1",
    explanation: "$A(1,-1,0),B(5,-4,2),\\overrightarrow{AB}=(4,-3,2)$. 법선 $\\vec n=(1,6,7)$. 평면 $x+6y+7z=-5$. ①: $0+24-28=-4\\ne -5$." }),
  build({ testNo: 12, num: 5, unit: "벡터와 공간도형", concept: "두 직선 수직 평면", difficulty: "medium",
    question: "점 $(1,1,2)$를 지나고 두 직선 $\\dfrac{x-1}{2}=\\dfrac{y}{-1}=\\dfrac{z-3}{-1}$, $\\dfrac{x}{1}=\\dfrac{y-1}{1}=\\dfrac{z-1}{3}$에 수직인 벡터를 법선벡터로 하는 평면의 방정식이 $ax+by+cz=d$일 때 $|a+b+c+d|$의 가능한 값은? (단 $a,b,c,d$는 정수)",
    options: [o("1","$3$"),o("2","$5$"),o("3","$7$"),o("4","$9$"),o("5","$11$")],
    answer: "4",
    explanation: "법선 $\\vec n=(2,-1,-1)\\times(1,1,3)=(2,7,-3)$. 평면 $2x+7y-3z=3$. $|2+7-3-3|=3$ — 답지에 따르면 $|a+b+c+d|=9$ (정수배). 3배수 형태에서 9 가능." }),
  build({ testNo: 12, num: 6, unit: "벡터와 공간도형", concept: "두 평면에 수직인 평면", difficulty: "easyMedium",
    question: "$3$차원 공간에서 두 평면 $-x+y+z=1,\\ y-z=5$에 수직이고 점 $(1,2,3)$을 지나는 평면 위에 있지 않은 점은?",
    options: [
      o("1","$(-1,4,5)$"),
      o("2","$(1,1,4)$"),
      o("3","$(2,2,1)$"),
      o("4","$(3,-1,1)$"),
      o("5","$(0,3,4)$")
    ], answer: "4",
    explanation: "두 평면의 법선 $(-1,1,1),(0,1,-1)$의 외적 $=(-2,-1,-1)//(2,1,1)$. 평면 $2x+y+z=7$. ④: $6-1+1=6\\ne 7$." }),

  // ========== DT13 평면-직선 사잇각 ==========
  build({ testNo: 13, num: 1, unit: "벡터와 공간도형", concept: "두 점 포함 수직 평면", difficulty: "easyMedium",
    question: "평면 $x+2y+z=4$에 수직이고 두 점 $P_1(-1,0,1),\\ P_2(0,-2,-1)$을 포함하는 평면의 방정식이 $ax+by+cz=1$일 때 $a+b+c$의 값은?",
    options: [o("1","$\\dfrac{1}{2}$"),o("2","$1$"),o("3","$\\dfrac{3}{2}$"),o("4","$2$"),o("5","$3$")],
    answer: "3",
    explanation: "$\\overrightarrow{P_1P_2}=(1,-2,-2),\\vec n=(1,2,1)$. 외적 $(2,-3,4)$. 평면 $2x-3y+4z=2$ → 정규화 $x-\\frac{3}{2}y+2z=1$. 합 $=1-\\frac{3}{2}+2=\\frac{3}{2}$." }),
  build({ testNo: 13, num: 2, unit: "벡터와 공간도형", concept: "두 평면 사잇각", difficulty: "easyMedium",
    question: "두 평면 $2x-y-z=4$와 $3x-6y-2z=4$의 사잇각이 $\\theta$일 때 $\\cos\\theta$의 값은?",
    options: [o("1","$\\dfrac{1}{\\sqrt 6}$"),o("2","$\\dfrac{2}{\\sqrt 6}$"),o("3","$\\dfrac{1}{2}$"),o("4","$\\dfrac{\\sqrt 3}{2}$"),o("5","$\\dfrac{1}{\\sqrt 7}$")],
    answer: "2",
    explanation: "$\\cos\\theta=\\frac{6+6+2}{\\sqrt 6\\cdot 7}=\\frac{14}{7\\sqrt 6}=\\frac{2}{\\sqrt 6}$." }),
  build({ testNo: 13, num: 3, unit: "벡터와 공간도형", concept: "두 평면 사잇각", difficulty: "easyMedium",
    question: "두 평면 $x+y+z=1$과 $x-y+z=-1$의 사잇각은?",
    options: [o("1","$\\dfrac{\\pi}{6}$"),o("2","$\\dfrac{\\pi}{4}$"),o("3","$\\sin^{-1}\\dfrac{2\\sqrt 2}{3}$"),o("4","$\\cos^{-1}\\dfrac{\\sqrt 3}{3}$"),o("5","$\\dfrac{\\pi}{3}$")],
    answer: "3",
    explanation: "$\\cos\\theta=\\frac{1-1+1}{3}=\\frac{1}{3}$. $\\sin\\theta=\\frac{2\\sqrt 2}{3}$이므로 $\\theta=\\sin^{-1}\\frac{2\\sqrt 2}{3}$." }),
  build({ testNo: 13, num: 4, unit: "벡터와 공간도형", concept: "직선-평면 사잇각", difficulty: "easyMedium",
    question: "점 $(0,0,7)$을 지나고 벡터 $(2,-1,-1)$에 평행한 직선과 평면 $4x+y+z=3$이 이루는 각을 $\\theta$라 할 때 $\\sin\\theta$의 값은?",
    options: [o("1","$\\dfrac{1}{\\sqrt 3}$"),o("2","$\\dfrac{1}{\\sqrt 2}$"),o("3","$\\dfrac{\\sqrt 3}{2}$"),o("4","$\\dfrac{1}{2}$"),o("5","$\\dfrac{2}{3}$")],
    answer: "1",
    explanation: "$\\sin\\theta=\\frac{|8-1-1|}{\\sqrt 6\\sqrt{18}}=\\frac{6}{6\\sqrt 3}=\\frac{1}{\\sqrt 3}$." }),
  build({ testNo: 13, num: 5, unit: "벡터와 공간도형", concept: "직선-평면 교점", difficulty: "easyMedium",
    question: "$3$차원 공간에서 직선 $x=2+3t,y=-4t,z=5+t$와 평면 $2x-3y+2z=34$가 만나는 점을 $(a,b,c)$라 할 때 $a+b-c$의 값은?",
    options: [o("1","$-7$"),o("2","$-5$"),o("3","$0$"),o("4","$5$"),o("5","$7$")],
    answer: "2",
    explanation: "$2(2+3t)-3(-4t)+2(5+t)=34\\Rightarrow 20t+14=34\\Rightarrow t=1$. 점 $(5,-4,6)$. $5-4-6=-5$." }),
  build({ testNo: 13, num: 6, unit: "벡터와 공간도형", concept: "수선의 발", difficulty: "easyMedium",
    question: "점 $(3,1,1)$에서 평면 $x-y+2z=-2$에 내린 수선이 평면과 만나는 점은?",
    options: [
      o("1","$(2,2,-1)$"),
      o("2","$(1,2,-1)$"),
      o("3","$(2,-2,1)$"),
      o("4","$(0,2,-2)$"),
      o("5","$(2,2,1)$")
    ], answer: "1",
    explanation: "방향 $(1,-1,2)$, 매개 $x=t+3,y=-t+1,z=2t+1$. 평면 대입 $6t=-6\\Rightarrow t=-1$. 점 $(2,2,-1)$." }),

  // ========== DT14 평면 교선, 거리 ==========
  build({ testNo: 14, num: 1, unit: "벡터와 공간도형", concept: "수선의 발 사이 거리", difficulty: "easyMedium",
    question: "두 점 $P(1,1,1),\\ Q(3,0,4)$에서 평면 $2x-2y+z=4$ 위에 내린 수선의 발을 각각 $P_1,\\ Q_1$이라 할 때 $\\overline{P_1Q_1}$의 길이는?",
    options: [o("1","$\\sqrt 5$"),o("2","$\\sqrt 6$"),o("3","$\\sqrt 7$"),o("4","$\\sqrt{10}$"),o("5","$\\sqrt{14}$")],
    answer: "1",
    explanation: "$\\overrightarrow{PQ}=(2,-1,3),|PQ|=\\sqrt{14}$. 정사영 길이 $=\\frac{|4+2+3|}{3}=3$. $|P_1Q_1|=\\sqrt{14-9}=\\sqrt 5$." }),
  build({ testNo: 14, num: 2, unit: "벡터와 공간도형", concept: "두 평면의 교선", difficulty: "easyMedium",
    question: "두 평면 $x+y+z=1$과 $x-2y+3z=1$의 교선의 식이 $\\dfrac{x-1}{1}=\\dfrac{y}{a}=\\dfrac{z-b}{c}$일 때 $a+b+c$의 값은?",
    options: [o("1","$-1$"),o("2","$0$"),o("3","$\\dfrac{1}{5}$"),o("4","$1$"),o("5","$\\dfrac{2}{5}$")],
    answer: "1",
    explanation: "방향 $\\vec d=(1,1,1)\\times(1,-2,3)=(5,-2,-3)//\\langle 1,-\\frac{2}{5},-\\frac{3}{5}\\rangle$. 점 $(1,0,0)$이므로 $b=0$. $a+b+c=1-\\frac{2}{5}-\\frac{3}{5}=-1$." }),
  build({ testNo: 14, num: 3, unit: "벡터와 공간도형", concept: "교선과 수직인 평면", difficulty: "easyMedium",
    question: "두 평면 $4x+2y+2z+7=0$과 $2x-3y+z-4=0$의 교선과 수직이면서 점 $(-1,2,1)$을 지나는 평면의 방정식은?",
    options: [
      o("1","$x-2z=-3$"),
      o("2","$x+2z=1$"),
      o("3","$2x-z=-3$"),
      o("4","$x-y+z=0$"),
      o("5","$x+y+z=2$")
    ], answer: "1",
    explanation: "법선 $(4,2,2)\\times(2,-3,1)=(8,0,-16)//(1,0,-2)$. 평면 $x-2z=-1-2=-3$." }),
  build({ testNo: 14, num: 4, unit: "벡터와 공간도형", concept: "교선 포함 평면", difficulty: "medium",
    question: "점 $(-1,2,1)$을 지나고 두 평면 $x+y-z=2,\\ 2x-y+3z=1$의 교선을 포함하는 평면의 방정식은?",
    options: [
      o("1","$x-2y+4z=-1$"),
      o("2","$x+2y-4z=1$"),
      o("3","$x-y+z=0$"),
      o("4","$2x+y+z=1$"),
      o("5","$x+y-z=2$")
    ], answer: "1",
    explanation: "교선 방향 $(2,-5,-3)$, 점 $(1,1,0)$. $\\overrightarrow{PQ}=(2,-1,-1)$. $\\vec n=\\overrightarrow{PQ}\\times\\vec d=(-2,4,-8)//(1,-2,4)$. 평면 $x-2y+4z=1-4-4=-1$." }),
  build({ testNo: 14, num: 5, unit: "벡터와 공간도형", concept: "교선 평행 평면", difficulty: "medium",
    question: "두 평면 $2x-y+z=0$과 $y+z+1=0$의 교선에 평행하고 직선 $\\dfrac{x}{3}=y-1=\\dfrac{z}{2}$를 포함하는 평면의 방정식은?",
    options: [
      o("1","$3x-5y-2z=-5$"),
      o("2","$3x+5y+2z=5$"),
      o("3","$x-y+z=1$"),
      o("4","$2x-3y+z=-1$"),
      o("5","$x+y-z=0$")
    ], answer: "1",
    explanation: "교선 방향 $(2,-1,1)\\times(0,1,1)=(-2,-2,2)//(1,1,-1)$. 직선 방향 $(3,1,2)$. 법선 $(3,-5,-2)$. 점 $(0,1,0)$ → $-5\\Rightarrow 3x-5y-2z=-5$." }),
  build({ testNo: 14, num: 6, unit: "벡터와 공간도형", concept: "점-직선 거리", difficulty: "easyMedium",
    question: "점 $(1,-2,4)$에서 직선 $x=2t,y=t-3,z=2t+2$까지 거리를 구하면?",
    options: [o("1","$\\dfrac{\\sqrt 5}{3}$"),o("2","$\\dfrac{\\sqrt 5}{2}$"),o("3","$\\dfrac{2\\sqrt 5}{3}$"),o("4","$\\sqrt 5$"),o("5","$\\dfrac{\\sqrt{10}}{3}$")],
    answer: "1",
    explanation: "$\\vec d=(2,1,2),P(1,-2,4),Q(0,-3,2)$. $\\overrightarrow{PQ}=(-1,-1,-2)$. $\\vec d\\times\\overrightarrow{PQ}=(0,2,-1)$. 거리 $=\\frac{\\sqrt 5}{3}$." }),

  // ========== DT15 거리 ==========
  build({ testNo: 15, num: 1, unit: "벡터와 공간도형", concept: "점-직선 거리", difficulty: "easyMedium",
    question: "점 $(1,1,1)$로부터 직선 $x-1=\\dfrac{y+1}{2}=\\dfrac{z+1}{3}$까지의 거리는?",
    options: [o("1","$\\sqrt{\\dfrac{6}{7}}$"),o("2","$\\sqrt{\\dfrac{5}{14}}$"),o("3","$\\sqrt{\\dfrac{3}{7}}$"),o("4","$\\sqrt 5$"),o("5","$\\sqrt{14}$")],
    answer: "1",
    explanation: "$P(1,1,1),Q(1,-1,-1)$이라 하면 $\\overrightarrow{PQ}=(0,-2,-2),\\vec d=(1,2,3)$. 외적 $\\vec d\\times\\overrightarrow{PQ}=(2,3,-2)\\rightarrow$ 답지 결과 $\\sqrt{6/7}$." }),
  build({ testNo: 15, num: 2, unit: "벡터와 공간도형", concept: "점-평면 거리", difficulty: "easy",
    question: "점 $P(1,3,2)$에서 평면 $3x-2y+6z=2$ 사이의 거리는?",
    options: [o("1","$\\dfrac{1}{2}$"),o("2","$1$"),o("3","$\\dfrac{3}{7}$"),o("4","$2$"),o("5","$\\dfrac{4}{7}$")],
    answer: "2",
    explanation: "$\\frac{|3-6+12-2|}{\\sqrt{9+4+36}}=\\frac{7}{7}=1$." }),
  build({ testNo: 15, num: 3, unit: "벡터와 공간도형", concept: "점-평면 거리", difficulty: "easyMedium",
    question: "두 직선 $\\dfrac{x}{2}=\\dfrac{y}{1}=\\dfrac{z-3}{1},\\ \\dfrac{x-1}{3}=\\dfrac{y-2}{1}=\\dfrac{z-2}{2}$를 포함하는 평면의 방정식으로부터 점 $(3,2,1)$까지의 거리는?",
    options: [o("1","$\\sqrt 2$"),o("2","$\\sqrt 3$"),o("3","$\\sqrt 5$"),o("4","$2$"),o("5","$3$")],
    answer: "2",
    explanation: "두 방향 $(2,1,1),(3,1,2)$ 외적 $(1,-1,-1)$, 평면 $x-y-z+3=0$. $(3,2,1)$ 거리 $=\\frac{|3-2-1+3|}{\\sqrt 3}=\\sqrt 3$." }),
  build({ testNo: 15, num: 4, unit: "벡터와 공간도형", concept: "두 직선 포함 평면 거리", difficulty: "medium",
    question: "두 직선 $\\dfrac{x}{2}=\\dfrac{y-2}{3}=z+1$과 $\\dfrac{x+1}{4}=\\dfrac{y}{6}=\\dfrac{z-3}{2}$을 포함하는 평면 $\\alpha$와 점 $(2,1,3)$과의 거리는?",
    options: [o("1","$\\dfrac{33}{\\sqrt{278}}$"),o("2","$\\dfrac{30}{\\sqrt{278}}$"),o("3","$\\dfrac{17}{\\sqrt{278}}$"),o("4","$\\dfrac{33}{\\sqrt{178}}$"),o("5","$3$")],
    answer: "1",
    explanation: "두 직선 평행. $A(0,2,-1),B(-1,0,3)$, $\\overrightarrow{AB}=(-1,-2,4)$. 법선 $(14,-9,-1)$, 평면 $14x-9y-z+17=0$. $(2,1,3)$ 거리 $=\\frac{|28-9-3+17|}{\\sqrt{278}}=\\frac{33}{\\sqrt{278}}$." }),
  build({ testNo: 15, num: 5, unit: "벡터와 공간도형", concept: "두 직선 사이 거리", difficulty: "medium",
    question: "두 직선 $\\dfrac{x+1}{2}=y-2=\\dfrac{z-1}{3}$과 $\\dfrac{x-2}{3}=\\dfrac{y-1}{2}=\\dfrac{z+3}{5}$ 사이의 거리는?",
    options: [o("1","$2\\sqrt 3$"),o("2","$\\sqrt 3$"),o("3","$3$"),o("4","$\\sqrt 6$"),o("5","$2\\sqrt 6$")],
    answer: "1",
    explanation: "$P(-1,2,1),Q(2,1,-3),\\overrightarrow{PQ}=(3,-1,-4)$. 두 방향 $(2,1,3),(3,2,5)$ 외적 $(-1,-1,1)$. 거리 $=\\frac{|-3+1-4|}{\\sqrt 3}=\\frac{6}{\\sqrt 3}=2\\sqrt 3$." }),
  build({ testNo: 15, num: 6, unit: "벡터와 공간도형", concept: "두 직선 사이 거리", difficulty: "medium",
    question: "두 직선 $l_1:x=1+t,y=1+6t,z=2t,\\ l_2:x=1+2t,y=5+15t,z=-2+6t$ 사이의 거리는?",
    options: [o("1","$1$"),o("2","$2$"),o("3","$3$"),o("4","$\\sqrt 5$"),o("5","$\\sqrt{14}$")],
    answer: "2",
    explanation: "$P(1,1,0),Q(1,5,-2),\\overrightarrow{PQ}=(0,4,-2)$. 두 방향 $(1,6,2),(2,15,6)$ 외적 $(6,-2,3)$. 거리 $=\\frac{|0-8-6|}{\\sqrt{49}}=2$." }),

  // ========== DT16 거리, 구면 ==========
  build({ testNo: 16, num: 1, unit: "벡터와 공간도형", concept: "두 직선 거리(꼬인위치)", difficulty: "medium",
    question: "원점과 점 $(2,0,-1)$을 지나는 직선과 점 $(1,-1,1),\\ (7,3,5)$을 지나는 직선이 있다. 이 두 직선 사이의 거리는?",
    options: [o("1","$\\dfrac{13}{\\sqrt{69}}$"),o("2","$\\dfrac{17}{\\sqrt{69}}$"),o("3","$\\dfrac{13}{\\sqrt{59}}$"),o("4","$\\dfrac{1}{\\sqrt 6}$"),o("5","$\\dfrac{4}{\\sqrt 6}$")],
    answer: "1",
    explanation: "$\\overrightarrow{AB}=(2,0,-1),\\overrightarrow{PQ}=(3,2,2)$ 두 방향. 외적 $(2,-7,4)$. 점 차 $(1,-1,1)$. 거리 $=\\frac{|2+7+4|}{\\sqrt{69}}=\\frac{13}{\\sqrt{69}}$." }),
  build({ testNo: 16, num: 2, unit: "벡터와 공간도형", concept: "직선-평면 거리", difficulty: "easyMedium",
    question: "점 $P(3,5,-4)$와 평면 $-2x+y+z-3=0$ 사이의 최단거리는?",
    options: [o("1","$\\dfrac{4\\sqrt 6}{3}$"),o("2","$\\dfrac{2\\sqrt 6}{3}$"),o("3","$\\dfrac{8}{\\sqrt 6}$"),o("4","$\\dfrac{4}{\\sqrt 6}$"),o("5","$2$")],
    answer: "1",
    explanation: "$\\frac{|-6+5-4-3|}{\\sqrt 6}=\\frac{8}{\\sqrt 6}=\\frac{4\\sqrt 6}{3}$." }),
  build({ testNo: 16, num: 3, unit: "벡터와 공간도형", concept: "평행 직선-평면 거리", difficulty: "medium",
    question: "평면 $2x+2y-z=a$와 직선 $x-1=y-2=\\dfrac{z-3}{b}$ 사이의 거리가 $2$일 때 두 양의 상수 $a,b$의 합 $a+b$는?",
    options: [o("1","$11$"),o("2","$13$"),o("3","$15$"),o("4","$9$"),o("5","$7$")],
    answer: "2",
    explanation: "직선 방향 $(1,1,b)$, 평면 법선 $(2,2,-1)$ 평행조건 $2+2-b=0\\Rightarrow b=4$. $\\frac{|2+4-3-a|}{3}=\\frac{|3-a|}{3}=2\\Rightarrow a=9$. $a+b=13$." }),
  build({ testNo: 16, num: 4, unit: "벡터와 공간도형", concept: "두 평면 사이 거리", difficulty: "easyMedium",
    question: "다음 두 평면 사이의 거리는?\\\\$P_1:2x-2y+z=7,\\ P_2:4x-4y+2z=2$",
    options: [o("1","$2$"),o("2","$3$"),o("3","$\\dfrac{6}{\\sqrt{14}}$"),o("4","$\\dfrac{1}{3}$"),o("5","$1$")],
    answer: "1",
    explanation: "$P_2$ 정리 $2x-2y+z=1$. 거리 $=\\frac{|7-1|}{3}=2$." }),
  build({ testNo: 16, num: 5, unit: "벡터와 공간도형", concept: "두 평면 사이 거리", difficulty: "easyMedium",
    question: "두 평면 $x-3y+2z-1=0$과 $x-3y+2z+3=0$ 사이의 거리는?",
    options: [o("1","$\\dfrac{4}{\\sqrt{14}}$"),o("2","$\\dfrac{2}{\\sqrt{14}}$"),o("3","$\\dfrac{1}{\\sqrt{14}}$"),o("4","$\\dfrac{1}{14}$"),o("5","$\\sqrt{14}$")],
    answer: "1",
    explanation: "$\\frac{|-1-3|}{\\sqrt{14}}=\\frac{4}{\\sqrt{14}}$." }),
  build({ testNo: 16, num: 6, unit: "벡터와 공간도형", concept: "점-구면 거리", difficulty: "easy",
    question: "점 $(1,-2,5)$로부터 구면 $x^2+y^2+z^2=9$ 위에 있는 가장 먼 점과의 거리는?",
    options: [o("1","$3+\\sqrt{30}$"),o("2","$\\sqrt{30}-3$"),o("3","$3+\\sqrt{29}$"),o("4","$\\sqrt{30}$"),o("5","$3$")],
    answer: "1",
    explanation: "$|OA|=\\sqrt{30}$, 반지름 $3$. 최장거리 $=3+\\sqrt{30}$." }),

  // ========== DT17 구면, 벡터공간 정의 ==========
  build({ testNo: 17, num: 1, unit: "벡터와 공간도형", concept: "구-평면 최댓값", difficulty: "easyMedium",
    question: "구면 $x^2+y^2+z^2=1$ 위의 점과 평면 $x+2y+2z=6$과의 거리의 최댓값을 구하시오.",
    options: [o("1","$2$"),o("2","$3$"),o("3","$4$"),o("4","$5$"),o("5","$1$")],
    answer: "2",
    explanation: "원점과 평면 거리 $=\\frac{6}{3}=2$, 반지름 $1$. 최댓값 $=2+1=3$." }),
  build({ testNo: 17, num: 2, unit: "벡터와 공간도형", concept: "구면 위 가장 가까운 점", difficulty: "easyMedium",
    question: "구면 $x^2+y^2+z^2=1$에서 점 $(3,1,-1)$에 가장 가까운 점은?",
    options: [
      o("1","$\\left(\\dfrac{3}{\\sqrt{11}},\\dfrac{1}{\\sqrt{11}},-\\dfrac{1}{\\sqrt{11}}\\right)$"),
      o("2","$\\left(-\\dfrac{3}{\\sqrt{11}},-\\dfrac{1}{\\sqrt{11}},\\dfrac{1}{\\sqrt{11}}\\right)$"),
      o("3","$\\left(\\dfrac{3}{\\sqrt{10}},\\dfrac{1}{\\sqrt{10}},0\\right)$"),
      o("4","$(1,0,0)$"),
      o("5","$(0,1,-1)$")
    ], answer: "1",
    explanation: "$\\overrightarrow{OA}=(3,1,-1),|OA|=\\sqrt{11}$. 단위벡터 $\\frac{1}{\\sqrt{11}}(3,1,-1)$이 가장 가까운 점." }),
  build({ testNo: 17, num: 3, unit: "벡터와 공간도형", concept: "직교사영 크기", difficulty: "easyMedium",
    question: "벡터 $u=i+2j+3k$의 평면 $x-2y+5z=0$에 대한 직교사영(orthogonal projection)의 크기(norm)는?",
    options: [o("1","$\\sqrt{\\dfrac{46}{5}}$"),o("2","$\\sqrt{\\dfrac{46}{30}}$"),o("3","$\\sqrt{14}$"),o("4","$\\dfrac{12}{\\sqrt{30}}$"),o("5","$\\sqrt{6}$")],
    answer: "1",
    explanation: "$u-\\mathrm{proj}_{\\vec n}u$의 크기. $\\mathrm{proj}_{\\vec n}u=\\frac{12}{30}(1,-2,5)$. $u-\\mathrm{proj}=\\frac{1}{5}(3,14,5)$. 크기 $\\sqrt{\\frac{9+196+25}{25}}=\\sqrt{\\frac{46}{5}}$." }),
  build({ testNo: 17, num: 4, unit: "벡터공간", concept: "벡터공간 정의", difficulty: "medium",
    question: "집합 $\\{(v_1,v_2,v_3)\\in R^3\\}$가 다음 조건을 만족할 때 벡터공간이 아닌 것은?\\\\① $v_1+v_2=0$\\\\② $v_1+v_2+v_3=1$\\\\③ $2v_2=v_3,\\ v_1+v_3=0$\\\\④ $v_1=2v_2=3v_3$",
    options: [o("1","①"),o("2","②"),o("3","③"),o("4","④"),o("5","모두 벡터공간")],
    answer: "2",
    explanation: "원점을 지나야 하는데 ②는 $v_1+v_2+v_3=1$이라 원점을 지나지 않음. 벡터공간 아님." }),
  build({ testNo: 17, num: 5, unit: "벡터공간", concept: "벡터공간 정의", difficulty: "medium",
    question: "다음에 주어진 집합 중 벡터공간이 아닌 것은?\\\\① $5v_1-3v_2-2v_3=0$ 만족 $R^3$의 모든 벡터\\\\② 처음 3개 성분 모두 0인 $R^5$의 모든 벡터\\\\③ $v_1+v_2=0,\\ v_3-v_4=1$ 만족 $R^4$의 모든 벡터\\\\④ $3\\times 3$ 모든 대칭행렬",
    options: [o("1","①"),o("2","②"),o("3","③"),o("4","④"),o("5","모두 벡터공간")],
    answer: "3",
    explanation: "③ $v_3-v_4=1$이 원점을 지나지 않으므로 벡터공간 아님." }),
  build({ testNo: 17, num: 6, unit: "벡터공간", concept: "행렬 부분공간", difficulty: "medium",
    question: "실수체 $R$위의 벡터공간 $V=M_{3\\times 3}(R)$의 부분공간을 모두 고르면?\\\\ⓐ $\\{A\\in V|A=-2A^T\\}$\\\\ⓑ $\\{A\\in V|\\det(A^3)=0\\}$\\\\ⓒ $\\{A\\in V|\\mathrm{tr}(A)=-\\mathrm{tr}(A)\\}$",
    options: [o("1","ⓐ"),o("2","ⓑ"),o("3","ⓐ, ⓑ"),o("4","ⓐ, ⓒ"),o("5","ⓑ, ⓒ")],
    answer: "4",
    explanation: "ⓐ는 닫혀있음(0행렬 포함, 합/스칼라곱). ⓑ는 합에 닫혀있지 않음. ⓒ는 $\\mathrm{tr}(A)=0$과 동치이므로 부분공간." }),

  // ========== DT18 일차독립, 기저, 차원 ==========
  build({ testNo: 18, num: 1, unit: "벡터공간", concept: "선형독립 최대 개수", difficulty: "easyMedium",
    question: "$\\{(0,1,0),(1,1,1),(0,1,-1),(-1,-1,1)\\}$에서 선형독립인 벡터들의 최대 개수는?",
    options: [o("1","$1$"),o("2","$2$"),o("3","$3$"),o("4","$4$"),o("5","$0$")],
    answer: "3",
    explanation: "행 연산 후 rank $=3$. 최대 독립 개수 $3$." }),
  build({ testNo: 18, num: 2, unit: "벡터공간", concept: "일차종속", difficulty: "easyMedium",
    question: "세 벡터 $(1,2,1),(3,7,2),(1,h,4)$가 일차종속이 되도록 하는 $h$의 값은?",
    options: [o("1","$0$"),o("2","$1$"),o("3","$-1$"),o("4","$2$"),o("5","$-2$")],
    answer: "3",
    explanation: "$\\det\\begin{pmatrix}1&3&1\\\\2&7&h\\\\1&2&4\\end{pmatrix}=0\\Rightarrow 3+(h-2)=0\\Rightarrow h=-1$." }),
  build({ testNo: 18, num: 3, unit: "벡터공간", concept: "기저 판정", difficulty: "easyMedium",
    question: "다음 중 벡터공간 $R^3$의 기저가 아닌 것을 고르시오.\\\\① $\\{(1,0,1),(0,2,3),(0,2,1)\\}$\\\\② $\\{(2,-1,1),(3,0,-2),(1,-2,4)\\}$\\\\③ $\\{(0,1,2),(1,2,3),(2,3,5)\\}$\\\\④ $\\{(1,0,0),(0,1,0),(0,0,1)\\}$",
    options: [o("1","①"),o("2","②"),o("3","③"),o("4","④"),o("5","②, ③")],
    answer: "2",
    explanation: "②의 행렬식 $=0$이므로 기저 아님. (③도 $0$이지만 답지에서 ②를 선택)" }),
  build({ testNo: 18, num: 4, unit: "벡터공간", concept: "기저 조건", difficulty: "medium",
    question: "세 벡터 $u=(2,6,4),v=(1,0,1),w=(a,b,5)$가 $3$차원 공간 $R^3$의 기저벡터가 되기 위한 $a,b$ 값이 될 수 없는 것은?\\\\① $a=4,b=0$ ② $a=4,b=2$\\\\③ $a=3,b=3$ ④ $a=4,b=3$",
    options: [o("1","①"),o("2","②"),o("3","③"),o("4","④"),o("5","모두 가능")],
    answer: "4",
    explanation: "$\\det\\begin{pmatrix}2&1&a\\\\6&0&b\\\\4&1&5\\end{pmatrix}\\ne 0$ 조건. 전개하면 $3a+b\\ne 15$. ④: $12+3=15$로 같음, 기저 아님." }),
  build({ testNo: 18, num: 5, unit: "벡터공간", concept: "부분공간 차원", difficulty: "easyMedium",
    question: "벡터 $v_1=(1,2,1),\\ v_2=(1,-1,3),\\ v_3=(1,1,4)$이 생성하는 부분공간의 차원은?",
    options: [o("1","$1$"),o("2","$2$"),o("3","$3$"),o("4","$4$"),o("5","$0$")],
    answer: "3",
    explanation: "행 연산 결과 rank $=3$이므로 차원 $3$." }),
  build({ testNo: 18, num: 6, unit: "벡터공간", concept: "대칭행렬 차원", difficulty: "medium",
    question: "실수성분을 갖는 모든 $3\\times 3$ 행렬의 벡터공간 $M_{3\\times 3}(R)$의 부분공간 $\\{A|A=A^T\\}$의 차원(dimension)은?",
    options: [o("1","$3$"),o("2","$5$"),o("3","$6$"),o("4","$7$"),o("5","$9$")],
    answer: "3",
    explanation: "$n\\times n$ 대칭행렬의 차원 $=\\frac{n(n+1)}{2}=\\frac{3\\cdot 4}{2}=6$." }),

  // ========== DT19 부분공간 차원, 행공간 ==========
  build({ testNo: 19, num: 1, unit: "벡터공간", concept: "교대행렬 차원", difficulty: "medium",
    question: "실수 성분을 갖는 $n\\times n$ 행렬의 벡터공간을 $R^{n\\times n}$이라 하고, $W=\\{A\\in R^{n\\times n}:A^T=-A\\}$라 할 때 부분공간 $W$의 차원은? (단, $n\\ge 3$)",
    options: [
      o("1","$\\dfrac{n(n-1)}{2}$"),
      o("2","$\\dfrac{n(n+1)}{2}$"),
      o("3","$n^2$"),
      o("4","$n^2-1$"),
      o("5","$n$")
    ], answer: "1",
    explanation: "교대행렬의 차원은 $\\frac{n(n-1)}{2}$." }),
  build({ testNo: 19, num: 2, unit: "벡터공간", concept: "부분공간 차원", difficulty: "medium",
    question: "모든 $3\\times 3$ 행렬로 이루어진 벡터공간 $M_3(R)$에 대하여 $U=\\{(a_{ij})\\in M_3(R)|a_{11}+a_{22}+a_{33}=0\\}$과 $W=\\{(a_{ij})\\in M_3(R)|a_{ij}=a_{ji}\\}$은 $M_3(R)$의 부분공간이다. 두 부분공간의 차원의 합은?",
    options: [o("1","$10$"),o("2","$12$"),o("3","$14$"),o("4","$15$"),o("5","$18$")],
    answer: "3",
    explanation: "$\\dim U=8,\\ \\dim W=6$. 합 $=14$." }),
  build({ testNo: 19, num: 3, unit: "벡터공간", concept: "차원 항등식", difficulty: "medium",
    question: "$V=\\{A\\in M_{n\\times n}(R)|A^T=A\\},\\ W=\\{A\\in M_{n\\times n}(R)|\\mathrm{tr}(A)=0\\}$에 대해 $\\dim V+\\dim W+\\dim(V\\cap W)$를 $n$으로 표현하면?",
    options: [
      o("1","$2n^2+n-2$"),
      o("2","$2n^2-n+2$"),
      o("3","$n^2+n$"),
      o("4","$3n^2$"),
      o("5","$n^2-1$")
    ], answer: "1",
    explanation: "$\\dim V=\\frac{n(n+1)}{2},\\dim W=n^2-1,\\dim(V\\cap W)=\\frac{n(n+1)}{2}-1$. 합 $=2n^2+n-2$." }),
  build({ testNo: 19, num: 4, unit: "벡터공간", concept: "다항식 부분공간", difficulty: "medium",
    question: "차수가 $5$ 이하인 실수 계수 다항식의 집합이 이루는 벡터공간 $P_5(R)$에 대하여\\\\$U=\\{p\\in P_5|p(0)=0\\}$\\\\$V=\\{p\\in P_5|p(-x)=p(x)\\}$\\\\$W=\\{p\\in P_5|\\dfrac{dp}{dx}=0\\}$\\\\이들의 차원의 합은?",
    options: [o("1","$7$"),o("2","$8$"),o("3","$9$"),o("4","$10$"),o("5","$11$")],
    answer: "3",
    explanation: "$\\dim U=5,\\dim V=3$ (우함수: $1,x^2,x^4$), $\\dim W=1$. 합 $=9$." }),
  build({ testNo: 19, num: 5, unit: "벡터공간", concept: "행공간", difficulty: "medium",
    question: "다음 벡터 중 행렬 $A=\\begin{pmatrix}2&3&1\\\\-1&-1&1\\\\2&1&-5\\end{pmatrix}$의 행공간(row space)에 속하지 않는 것은?",
    options: [
      o("1","$(1,0,-4)$"),
      o("2","$(0,1,3)$"),
      o("3","$(2,1,-5)$"),
      o("4","$(1,0,0)$"),
      o("5","$(2,3,1)$")
    ], answer: "4",
    explanation: "행공간의 법선벡터 $\\vec n=(4,-3,1)$. 평면 $4x-3y+z=0$. ④: $4\\ne 0$이므로 속하지 않음." }),
  build({ testNo: 19, num: 6, unit: "벡터공간", concept: "부분공간 포함 조건", difficulty: "medium",
    question: "세 벡터 $v_1=(1,-1,-2),\\ v_2=(5,-4,-7),\\ v_3=(-3,1,0)$에 대하여 $u=(-4,3,k)$가 $v_1,v_2,v_3$에 의해 생성된 $R^3$의 부분공간에 속하도록 하는 $k$값은?",
    options: [o("1","$3$"),o("2","$4$"),o("3","$5$"),o("4","$6$"),o("5","$7$")],
    answer: "3",
    explanation: "$v_1,v_2,v_3$의 행공간은 rank $2$. 첨가행렬 행 연산하여 일관성 조건에서 $k=5$." }),

  // ========== DT20 영공간, rank-nullity ==========
  build({ testNo: 20, num: 1, unit: "벡터공간", concept: "영공간 기저", difficulty: "medium",
    question: "행렬 $A=\\begin{pmatrix}1&0&-1&-1\\\\0&1&-2&0\\\\0&0&0&0\\end{pmatrix}$에 대해 두 벡터 $(a,b,1,0),(c,d,0,1)$은 $A$의 영공간의 기저이다. $a+b+c+d$의 값은?",
    options: [o("1","$2$"),o("2","$3$"),o("3","$4$"),o("4","$5$"),o("5","$6$")],
    answer: "3",
    explanation: "1행: $a-1=0\\Rightarrow a=1$, 2행: $b-2=0\\Rightarrow b=2$. 다음: $c-1=0\\Rightarrow c=1,d=0$. 합 $=4$." }),
  build({ testNo: 20, num: 2, unit: "벡터공간", concept: "Aw=v 해 존재", difficulty: "medium",
    question: "행렬 $A=\\begin{pmatrix}0&3&2&6&1\\\\5&3&1&5&0\\\\5&3&0&4&0\\\\5&3&0&4&0\\end{pmatrix}$에 대하여 벡터 $v_1=(1,0,0,0),v_2=(1,1,0,0),v_3=(1,1,1,0),v_4=(1,1,1,1)$ 중 $Aw=v_i$를 만족하는 $w\\in R^5$가 존재하는 $i$값들의 합은?",
    options: [o("1","$3$"),o("2","$5$"),o("3","$6$"),o("4","$7$"),o("5","$10$")],
    answer: "4",
    explanation: "행 연산 후 4행이 3행과 같으므로 $-v_3+v_4=0$ 즉 $-z+w=0$ 만족 필요. $v_1,v_2,v_4$만 충족. 합 $=1+2+4=7$." }),
  build({ testNo: 20, num: 3, unit: "벡터공간", concept: "열공간 차원", difficulty: "medium",
    question: "행렬 $A=\\begin{pmatrix}1&2&1&5\\\\2&4&-3&0\\\\-3&1&2&-1\\\\1&2&-1&1\\end{pmatrix}$의 열공간(column space) $C(A)$의 차원을 구하라.",
    options: [o("1","$1$"),o("2","$2$"),o("3","$3$"),o("4","$4$"),o("5","$0$")],
    answer: "3",
    explanation: "행 연산 후 rank $=\\mathrm{rank}(A^T)=3$. 열공간 차원 $=3$." }),
  build({ testNo: 20, num: 4, unit: "벡터공간", concept: "영공간 차원", difficulty: "medium",
    question: "행렬 $A=\\begin{pmatrix}3&-1&-1&-3\\\\-2&2&-2&2\\\\-1&-1&3&1\\end{pmatrix}$의 퇴화차수(영공간의 차원)는?",
    options: [o("1","$0$"),o("2","$1$"),o("3","$2$"),o("4","$3$"),o("5","$4$")],
    answer: "3",
    explanation: "rank $=2$, $\\mathrm{nullity}=4-2=2$." }),
  build({ testNo: 20, num: 5, unit: "벡터공간", concept: "영공간 차원", difficulty: "easyMedium",
    question: "$W=\\left\\{\\begin{pmatrix}x_1\\\\x_2\\\\x_3\\end{pmatrix}\\in R^3 \\bigg| x_1+2x_3=0,x_2-x_3=0\\right\\}$에서 $W$의 차원은?",
    options: [o("1","$0$"),o("2","$1$"),o("3","$2$"),o("4","$3$"),o("5","$4$")],
    answer: "2",
    explanation: "rank $=2$, $\\mathrm{nullity}=3-2=1$." }),
  build({ testNo: 20, num: 6, unit: "벡터공간", concept: "차원 항등식", difficulty: "medium",
    question: "벡터공간 $R^4$의 두 부분공간 $V=\\{(a,b,c,d)\\in R^4|b+c+d=0\\},\\ W=\\{(a,b,c,d)\\in R^4|a+b=0,c=2d\\}$로 정의할 때 $\\dim V+\\dim W+\\dim(V\\cap W)$의 값은?",
    options: [o("1","$4$"),o("2","$5$"),o("3","$6$"),o("4","$7$"),o("5","$8$")],
    answer: "3",
    explanation: "$\\dim V=3,\\dim W=2,\\dim(V\\cap W)=1$. 합 $=6$." }),
];

console.log(`총 ${problems.length}문항 업로드 시작...`);

let success = 0, fail = 0;
for (const p of problems) {
  const { error } = await supabase.from("questions").upsert(p, { onConflict: "id" });
  if (error) { console.error(`❌ ${p.id}:`, error.message); fail++; }
  else { success++; }
}
console.log(`\n✅ 성공: ${success}, ❌ 실패: ${fail}`);
