// 2024년 광운대 편입수학 객관식 30문항 (5지선다)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR="2024", SCHOOL_KO="광운대", SCHOOL_EN="kwangwoon";
const opts5 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:1, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"제약 조건 최댓값",
    difficulty:"medium",
    question:"평면 $x+z=1$과 원기둥 $x^2+y^2=3$의 교선에서 함수 $f(x,y,z)=x+3y+2z$의 최댓값은?",
    options:opts5("$2\\sqrt{30}$","$\\sqrt{30}-2$","$\\sqrt{30}+2$","$\\sqrt{30}$","$\\sqrt{30}-1$"),
    correct:"3",
    explanation:"매개변수화: $x=\\sqrt{3}\\cos\\theta,\\,y=\\sqrt{3}\\sin\\theta,\\,z=1-\\sqrt{3}\\cos\\theta$ ($0\\le\\theta\\le 2\\pi$).\n$f=3\\sqrt{3}\\sin\\theta-\\sqrt{3}\\cos\\theta+2=\\sqrt{30}\\sin(\\theta+\\alpha)+2$ (삼각함수 합성).\n최댓값 $\\sqrt{30}+2$.",
  },
  {n:2, subject:"선형대수", unit:"행렬", concept:"역행렬 (여인수)",
    difficulty:"medium",
    question:"행렬 $A=\\begin{pmatrix}1&2&2\\\\1&-1&2\\\\0&-2&5\\end{pmatrix}$의 역행렬을 $A^{-1}=\\begin{pmatrix}a&b&c\\\\d&e&f\\\\g&h&i\\end{pmatrix}$라고 할 때, $c+d+h$의 값은?",
    options:opts5("$0$","$-\\dfrac{1}{5}$","$\\dfrac{1}{3}$","$\\dfrac{16}{15}$","$-\\dfrac{13}{15}$"),
    correct:"2",
    explanation:"$|A|=-15$ (스칼라 삼중적).\n$c=A^{-1}_{(1,3)}=\\dfrac{C_{31}}{|A|}=\\dfrac{1}{-15}\\det\\!\\begin{vmatrix}2&2\\\\-1&2\\end{vmatrix}=-\\dfrac{6}{15}$.\n$d=A^{-1}_{(2,1)}=\\dfrac{C_{12}}{|A|}=\\dfrac{1}{-15}\\cdot(-1)\\det\\!\\begin{vmatrix}1&2\\\\0&5\\end{vmatrix}=\\dfrac{5}{15}=\\dfrac{1}{3}$.\n$h=A^{-1}_{(3,2)}=\\dfrac{C_{23}}{|A|}=\\dfrac{1}{-15}\\cdot(-1)\\det\\!\\begin{vmatrix}1&2\\\\0&-2\\end{vmatrix}=-\\dfrac{2}{15}$.\n$c+d+h=-\\dfrac{6}{15}+\\dfrac{5}{15}-\\dfrac{2}{15}=-\\dfrac{3}{15}=-\\dfrac{1}{5}$.",
  },
  {n:3, subject:"적분학", unit:"적분의 정의", concept:"상적분과 하적분",
    difficulty:"medium",
    question:"구간 $\\left[-\\dfrac{\\pi}{2},\\dfrac{\\pi}{2}\\right]$에서 다음 함수 $f$의 상적분과 하적분의 차는?\n$$f(x)=\\begin{cases}\\sin x&\\!\\left(x\\in\\!\\left[-\\dfrac{\\pi}{2},\\dfrac{\\pi}{2}\\right]\\cap\\mathbb{Q}\\right)\\\\\\cos x&\\!\\left(x\\in\\!\\left[-\\dfrac{\\pi}{2},\\dfrac{\\pi}{2}\\right]\\cap\\mathbb{Q}^c\\right)\\end{cases}$$",
    options:opts5("$0$","$\\sqrt{2}$","$2\\sqrt{2}$","$\\sqrt{2}+1$","$2\\sqrt{2}-2$"),
    correct:"3",
    explanation:"각 구간에서 두 값 중 큰 쪽이 상값, 작은 쪽이 하값.\n상적분 $a=\\!\\int_{-\\pi/2}^{\\pi/4}\\cos x\\,dx+\\!\\int_{\\pi/4}^{\\pi/2}\\sin x\\,dx=\\!\\left(1+\\dfrac{1}{\\sqrt{2}}\\right)+\\dfrac{1}{\\sqrt{2}}=1+\\sqrt{2}$.\n하적분 $b=\\!\\int_{-\\pi/2}^{\\pi/4}\\sin x\\,dx+\\!\\int_{\\pi/4}^{\\pi/2}\\cos x\\,dx=\\!\\left(-\\dfrac{1}{\\sqrt{2}}\\right)+\\!\\left(1-\\dfrac{1}{\\sqrt{2}}\\right)=1-\\sqrt{2}$.\n차 $|a-b|=2\\sqrt{2}$.",
  },
  {n:4, subject:"다변수함수", unit:"극좌표와 극곡선", concept:"극곡선 교점 개수",
    difficulty:"medium",
    question:"극 방정식으로 표현된 곡선 $r=5\\cos 2\\theta$와 원 $r=3$의 교점의 개수는? (단, $-\\pi\\le\\theta\\le\\pi$)",
    options:opts5("$8$","$4$","$2$","$1$","$0$"),
    correct:"1",
    explanation:"$r=5\\cos 2\\theta$는 4잎 장미곡선이고 원 $r=3$은 반지름 3 원.\n각 잎에서 $5\\cos 2\\theta=3$은 두 번 성립하므로 한 잎당 교점 2개.\n4잎 $\\times$ 2 $=$ 8개.",
  },
  {n:5, subject:"다변수함수", unit:"음함수와 편미분", concept:"음함수 편미분",
    difficulty:"medium",
    question:"곡면 $(x+3)yz=1$과 $yz$ 평면의 교선 $C$에 대해, 점 $\\left(0,3,\\dfrac{1}{9}\\right)$에서 곡선 $C$의 접선의 기울기를 $\\alpha$라 할 때 $|\\alpha|$의 값은?",
    options:opts5("$\\dfrac{1}{3}$","$\\dfrac{1}{6}$","$\\dfrac{1}{9}$","$\\dfrac{1}{18}$","$\\dfrac{1}{27}$"),
    correct:"5",
    explanation:"$F(x,y,z)=xyz+3yz-1=0$. 교선은 $x=0$ 평면 위 곡선이므로 $y$축 방향 미분 $\\dfrac{\\partial z}{\\partial y}$를 구한다.\n$\\dfrac{\\partial z}{\\partial y}=-\\dfrac{F_y}{F_z}=-\\dfrac{xz+3z}{xy+3y}\\bigg|_{(0,3,1/9)}=-\\dfrac{1/3}{9}=-\\dfrac{1}{27}$.\n$|\\alpha|=\\dfrac{1}{27}$.",
  },
  {n:6, subject:"다변수함수", unit:"편미분", concept:"연쇄법칙",
    difficulty:"easy",
    question:"$x=\\tan^{-1}2t$이고 $y=\\sec t$이며 $z=xy^2+3x^2 y$일 때, $t=0$에서 $\\dfrac{dz}{dt}$의 값은?",
    options:opts5("$-1$","$0$","$1$","$2$","$\\dfrac{1}{2}$"),
    correct:"4",
    explanation:"$\\dfrac{dz}{dt}=z_x\\dfrac{dx}{dt}+z_y\\dfrac{dy}{dt}=(y^2+6xy)\\cdot\\dfrac{2}{1+4t^2}+(2xy+3x^2)\\cdot\\sec t\\tan t$.\n$t=0$일 때 $x=0,\\,y=1$이므로 $=(1)\\cdot 2+(0)\\cdot 0=2$.",
  },
  {n:7, subject:"미분학", unit:"미분가능성", concept:"진위판단 (미분·infsup)",
    difficulty:"medium",
    question:"다음 중 옳은 것을 모두 고르면?\n\nⓐ 함수 $f(x)=xe^{|x|}$는 $x=0$에서 미분가능하다.\nⓑ 미분 가능한 함수의 도함수는 연속이다.\nⓒ 유계 집합 $A,B\\subset\\mathbb{R}$에 대해 $A\\subset B$이면 $\\inf A<\\inf B$이다.\nⓓ 공집합이 아닌 유계 집합 $A\\subset\\mathbb{R}$에 대해 $\\sup A$는 반드시 존재한다.",
    options:opts5("ⓐ","ⓑ,ⓒ","ⓑ,ⓓ","ⓐ,ⓓ","ⓐ,ⓒ,ⓓ"),
    correct:"4",
    explanation:"ⓐ [참] $f'(x)=(x+1)e^x$ ($x\\ge 0$), $(-x+1)e^{-x}$ ($x<0$). 양 끝 일치하므로 $x=0$에서 미분가능.\nⓑ [거짓] 반례: $f(x)=x^2\\sin(1/x)$ ($x\\ne 0$), $f(0)=0$. 미분가능하나 $f'$이 0에서 불연속.\nⓒ [거짓] 반례: $A=\\{1,2,3\\},\\,B=\\{-1,1,2,3\\}$. $A\\subset B$이지만 $\\inf A=1>\\inf B=-1$.\nⓓ [참] 유계 집합의 상한은 완비성 공리에 의해 항상 존재.\n옳은 것은 ⓐ,ⓓ.",
  },
  {n:8, subject:"다변수함수", unit:"음함수와 편미분", concept:"음함수 2계 도함수",
    difficulty:"hard",
    question:"$x^4+y^4=2$일 때, $y''=ax^b y^c$이라면, $a+b-c$의 값은?",
    options:opts5("$3$","$-3$","$1$","$-1$","$2$"),
    correct:"1",
    explanation:"음함수 2계 도함수 공식: $\\dfrac{d^2 y}{dx^2}=-\\dfrac{f_{xx}f_y^2-2f_x f_y f_{xy}+f_{yy}f_x^2}{f_y^3}$.\n$f=x^4+y^4-2$: $f_x=4x^3,\\,f_y=4y^3,\\,f_{xx}=12x^2,\\,f_{yy}=12y^2,\\,f_{xy}=0$.\n$y''=-\\dfrac{12x^2\\cdot 16y^6+12y^2\\cdot 16x^6}{64y^9}=-\\dfrac{192(x^2y^6+x^6 y^2)}{64y^9}=-\\dfrac{3x^2(x^4+y^4)}{y^7}=-\\dfrac{6x^2}{y^7}=-6x^2 y^{-7}$.\n$a=-6,\\,b=2,\\,c=-7$. $a+b-c=-6+2+7=3$.",
  },
  {n:9, subject:"적분학", unit:"정적분의 응용", concept:"회전체 부피 (셸법)",
    difficulty:"easy",
    question:"$y=x-x^2$와 $y=0$으로 둘러싸인 영역을 $y$축을 중심으로 회전시켜 얻은 입체의 부피는?",
    options:opts5("$\\pi$","$\\dfrac{\\pi}{2}$","$\\dfrac{\\pi}{6}$","$\\dfrac{\\pi}{4}$","$\\dfrac{\\pi}{3}$"),
    correct:"3",
    explanation:"실린더 셸법: $V=2\\pi\\!\\int_0^1 x(x-x^2)\\,dx=2\\pi\\!\\int_0^1(x^2-x^3)\\,dx=2\\pi\\!\\left[\\dfrac{1}{3}-\\dfrac{1}{4}\\right]=\\dfrac{\\pi}{6}$.",
  },
  {n:10, subject:"미분학", unit:"미분방정식", concept:"변수분리형 ODE",
    difficulty:"medium",
    question:"다음 초깃값 문제의 해 $y(x)$를 $\\dfrac{(y(x))^2}{2}+e^{y(x)}=h(x)$ 꼴로 나타낼 때 $h(x)$는?\n$$y'(e^y+y)-x\\cos x=0,\\quad y(0)=0$$",
    options:opts5("$\\cos x$","$x\\sin x$","$\\cos x+x\\sin x$","$-x\\sin x$","$\\cos x\\sin x$"),
    correct:"3",
    explanation:"$(e^y+y)dy=x\\cos x\\,dx$ (변수분리).\n좌변 적분 $\\dfrac{y^2}{2}+e^y$. 우변 적분 $\\int x\\cos x\\,dx=x\\sin x+\\cos x+C$.\n$y(0)=0$: $0+1=0+1+C\\Rightarrow C=0$. $h(x)=x\\sin x+\\cos x=\\cos x+x\\sin x$.",
  },
  {n:11, subject:"적분학", unit:"정적분", concept:"극한 + 정적분 (구간 분할)",
    difficulty:"medium",
    question:"$\\displaystyle\\int_1^{2024}\\lim_{n\\to\\infty}\\dfrac{(1+\\sin\\pi x)^n-1}{(1+\\sin\\pi x)^n+1}\\,dx$의 값은?",
    options:opts5("$-1$","$0$","$1$","$2023$","$2024$"),
    correct:"1",
    explanation:"$r=1+\\sin\\pi x$. 극한값:\n• $|r|<1$ ($\\sin\\pi x<0$, 즉 $x\\in(2k+1,2k+2)$): $r^n\\to 0$, 피적분함수 $=-1$.\n• $|r|>1$ ($\\sin\\pi x>0$, 즉 $x\\in(2k,2k+1)$): $r^n\\to\\infty$, 피적분함수 $=1$.\n$\\!\\int_1^{2024}=\\sum_{k=1}^{2023}\\!\\int_k^{k+1}f\\,dx$. 음수 단위구간 $[1,2],[3,4],\\ldots,[2023,2024]$ 1012개($-1$), 양수 단위구간 $[2,3],[4,5],\\ldots,[2022,2023]$ 1011개($+1$).\n합 $=1011-1012=-1$.",
  },
  {n:12, subject:"다변수함수", unit:"공간곡선", concept:"곡률 최댓·최솟값",
    difficulty:"medium",
    question:"타원 $\\left(\\dfrac{x}{2}\\right)^2+\\left(\\dfrac{y}{3}\\right)^2=1$ 위의 점 $(x,y)$에서의 곡률을 $\\kappa(x,y)$라 할 때, $\\kappa(x,y)$의 최댓값과 최솟값의 차는?",
    options:opts5("$\\dfrac{5}{36}$","$\\dfrac{7}{36}$","$\\dfrac{15}{36}$","$\\dfrac{17}{36}$","$\\dfrac{19}{36}$"),
    correct:"5",
    explanation:"매개변수화 $r(t)=(2\\cos t,3\\sin t)$. $r'=(-2\\sin t,3\\cos t)$, $r''=(-2\\cos t,-3\\sin t)$, $r'\\times r''=6\\,\\vec{k}$.\n$\\kappa=\\dfrac{|r'\\times r''|}{|r'|^3}=\\dfrac{6}{(\\sqrt{4+5\\cos^2 t})^3}$.\n최대: $\\cos^2 t=0$일 때 $\\dfrac{6}{8}=\\dfrac{3}{4}$ (단축 끝).\n최소: $\\cos^2 t=1$일 때 $\\dfrac{6}{27}=\\dfrac{2}{9}$ (장축 끝).\n차 $\\dfrac{3}{4}-\\dfrac{2}{9}=\\dfrac{27-8}{36}=\\dfrac{19}{36}$.",
  },
  {n:13, subject:"다변수함수", unit:"편미분", concept:"이계 혼합편미분 ($f_{xy}$)",
    difficulty:"medium",
    question:"다음 함수 $f$에 대하여 $f_{xy}(0,0)$의 값은?\n$$f(x,y)=\\begin{cases}\\dfrac{xy^2}{x^2+y}&((x,y)\\ne(0,0))\\\\0&((x,y)=(0,0))\\end{cases}$$",
    options:opts5("$0$","$1$","$2$","$3$","존재하지 않는다."),
    correct:"2",
    explanation:"$(x,y)\\ne(0,0)$에서 $f_x=\\dfrac{y^2(x^2+y)-xy^2\\cdot 2x}{(x^2+y)^2}=\\dfrac{y^3-x^2 y^2}{(x^2+y)^2}$.\n$f_x(0,0)=\\lim_{h\\to 0}\\dfrac{f(h,0)-0}{h}=\\lim_{h\\to 0}\\dfrac{0}{h}=0$.\n$f_{xy}(0,0)=\\lim_{h\\to 0}\\dfrac{f_x(0,h)-f_x(0,0)}{h}=\\lim_{h\\to 0}\\dfrac{h^3/h^2}{h}=\\lim_{h\\to 0}\\dfrac{h}{h}=1$.",
  },
  {n:14, subject:"다변수함수", unit:"접평면과 선형근사", concept:"전미분 근삿값",
    difficulty:"easy",
    question:"점 $(3,5,2)$에서 함수 $z=\\sqrt{x^2-y}$의 접평면 방정식을 이용하여 $\\sqrt{(3.03)^2-(4.98)}$의 근삿값을 구하면?",
    options:opts5("$1.96$","$1.99$","$2.05$","$2.01$","$2.12$"),
    correct:"3",
    explanation:"$z=\\sqrt{x^2-y}\\big|_{(3,5)}=2$. 전미분 $dz=\\dfrac{x}{\\sqrt{x^2-y}}dx-\\dfrac{1}{2\\sqrt{x^2-y}}dy$.\n$x=3,\\,dx=0.03,\\,y=5,\\,dy=-0.02$ 대입: $dz=\\dfrac{3}{2}(0.03)-\\dfrac{1}{4}(-0.02)=0.045+0.005=0.05$.\n근삿값 $=2+0.05=2.05$.",
  },
  {n:15, subject:"미분학", unit:"미분방정식", concept:"코시-오일러 방정식",
    difficulty:"medium",
    question:"함수 $y=A\\cos(\\ln x)+B\\sin(\\ln x)$를 일반해로 가지는 미분방정식을 고르면? (단, $A,B$는 상수)",
    options:opts5("$y''+xy'+x^2 y=0$","$y''+x^2 y'+xy=0$","$xy''+x^2 y'+y=0$","$x^2 y''+y'+xy=0$","$x^2 y''+xy'+y=0$"),
    correct:"5",
    explanation:"해의 형태 $\\cos(\\ln x),\\sin(\\ln x)$는 코시-오일러 방정식 $x^2 y''+\\alpha xy'+\\beta y=0$의 해.\n특성방정식 $r(r-1)+\\alpha r+\\beta=0$에서 $r=\\pm i$이려면 $r^2+1=0$, 즉 $\\alpha=1,\\,\\beta=1$.\n선택지 중 코시-오일러 형태이면서 계수가 맞는 것은 (5) $x^2 y''+xy'+y=0$.",
  },
  {n:16, subject:"미분학", unit:"극한과 연속", concept:"극한 (지수 합)",
    difficulty:"easy",
    question:"극한 $\\displaystyle\\lim_{x\\to\\infty}\\!\\left(\\dfrac{1}{\\pi^x}+\\dfrac{1}{e^x}\\right)^{1/x}$의 값은?",
    options:opts5("$\\dfrac{1}{\\pi}$","$\\dfrac{1}{e}$","$0$","$e$","$\\pi$"),
    correct:"2",
    explanation:"$0<a<b$일 때 $\\lim_{x\\to\\infty}(a^x+b^x)^{1/x}=b$.\n$\\dfrac{1}{\\pi}<\\dfrac{1}{e}$이므로 답은 $\\dfrac{1}{e}$.",
  },
  {n:17, subject:"다변수함수", unit:"다변수 극값", concept:"헤시안 판정 (안장점)",
    difficulty:"medium",
    question:"$f(x,y)=-2x^3+3xy-\\dfrac{y^2}{2}+1$의 극값에 대한 다음 설명 중 옳은 것을 모두 고르면?\n\nⓐ $f$는 $\\left(\\dfrac{3}{2},\\dfrac{9}{2}\\right)$에서 극대이다.\nⓑ $f$는 $\\left(\\dfrac{3}{2},\\dfrac{9}{2}\\right)$에서 극소이다.\nⓒ $\\left(\\dfrac{3}{2},\\dfrac{9}{2},\\dfrac{35}{8}\\right)$는 $f$의 안장점이다.\nⓓ $f$는 $(0,0)$에서 극대이다.\nⓔ $f$는 $(0,0)$에서 극소이다.\nⓕ $(0,0,1)$은 $f$의 안장점이다.",
    options:opts5("ⓐ,ⓕ","ⓑ,ⓕ","ⓑ,ⓓ","ⓐ,ⓔ","ⓒ,ⓕ"),
    correct:"1",
    explanation:"$f_x=-6x^2+3y=0,\\,f_y=3x-y=0$. 임계점 $(0,0),\\,(3/2,9/2)$.\n$f_{xx}=-12x,\\,f_{yy}=-1,\\,f_{xy}=3$. 판별식 $\\Delta=f_{xx}f_{yy}-f_{xy}^2$.\n$(0,0)$: $\\Delta=0\\cdot(-1)-9=-9<0$ ⇒ 안장점, $f(0,0)=1$ ⇒ ⓕ 참.\n$(3/2,9/2)$: $\\Delta=(-18)(-1)-9=9>0$, $f_{xx}<0$ ⇒ 극대, $f=35/8$ ⇒ ⓐ 참.\n옳은 것: ⓐ,ⓕ.",
  },
  {n:18, subject:"미분학", unit:"역삼각함수", concept:"역삼각함수 항등식",
    difficulty:"medium",
    question:"다음 중 옳은 것을 모두 고르면?\n\nⓐ $\\tan^{-1}x=\\dfrac{\\sin^{-1}x}{\\cos^{-1}x}$\nⓑ $\\sin^{-1}(\\sin x)=x$\nⓒ $\\tan^{-1}x+\\cot^{-1}x=\\pi$\nⓓ $\\sin\\!\\left(\\cos^{-1}\\dfrac{5}{13}+\\sin^{-1}\\dfrac{4}{5}\\right)=\\dfrac{56}{65}$",
    options:opts5("없음","ⓐ","ⓑ","ⓒ","ⓓ"),
    correct:"5",
    explanation:"ⓐ [거짓] $\\tan x=\\sin x/\\cos x$와 혼동.\nⓑ [거짓] $-\\pi/2\\le x\\le\\pi/2$에서만 성립.\nⓒ [거짓] $\\tan^{-1}x+\\cot^{-1}x=\\dfrac{\\pi}{2}$.\nⓓ [참] $\\alpha=\\cos^{-1}(5/13)$이면 $\\sin\\alpha=12/13$. $\\beta=\\sin^{-1}(4/5)$이면 $\\cos\\beta=3/5$.\n$\\sin(\\alpha+\\beta)=\\sin\\alpha\\cos\\beta+\\cos\\alpha\\sin\\beta=\\dfrac{12}{13}\\cdot\\dfrac{3}{5}+\\dfrac{5}{13}\\cdot\\dfrac{4}{5}=\\dfrac{36+20}{65}=\\dfrac{56}{65}$.",
  },
  {n:19, subject:"적분학", unit:"급수의 수렴/발산", concept:"급수 판정법",
    difficulty:"medium",
    question:"다음 무한급수 중 수렴하는 급수의 개수는?\n\n(가) $\\displaystyle\\sum_{n=0}^{\\infty}\\dfrac{n!}{10^{2n+1}}$\n(나) $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{(-1)^n\\cos\\!\\left(\\dfrac{n-1}{n}\\right)}{\\sqrt{n}}$\n(다) $\\displaystyle\\sum_{n=0}^{\\infty}\\!\\left(\\sqrt{n^2+7}-n\\right)$\n(라) $\\displaystyle\\sum_{n=0}^{\\infty}\\dfrac{n+7}{\\sqrt{2024n^3+7n^2+7}}$",
    options:opts5("없음","1개","2개","3개","4개"),
    correct:"2",
    explanation:"(가) $a_n=\\dfrac{n!}{10^{2n+1}}\\to\\infty$ ⇒ 발산.\n(나) $\\dfrac{\\cos((n-1)/n)}{\\sqrt{n}}\\to 0$ 단조감소, 교대급수 판정법에 의해 수렴.\n(다) $\\sqrt{n^2+7}-n=\\dfrac{7}{\\sqrt{n^2+7}+n}\\sim\\dfrac{7}{2n}$ ⇒ 발산 (조화급수).\n(라) $\\dfrac{n+7}{\\sqrt{2024n^3+\\cdots}}\\sim\\dfrac{n}{n^{3/2}}=\\dfrac{1}{\\sqrt{n}}$ ⇒ 발산 ($p=1/2$).\n수렴은 (나) 1개.",
  },
  {n:20, subject:"미분학", unit:"극한과 연속", concept:"로피탈 정리 (지수 합)",
    difficulty:"medium",
    question:"등식 $\\displaystyle\\lim_{x\\to 0}\\dfrac{x\\!\\left(\\sum_{k=1}^n e^{2kx}\\cos k\\pi x-n\\right)}{(\\ln(x+1))^2}=12$를 만족시키는 자연수 $n$을 구하면?",
    options:opts5("$1$","$2$","$3$","$4$","$5$"),
    correct:"3",
    explanation:"$\\lim_{x\\to 0}\\dfrac{x}{\\ln(x+1)}=1$이므로 $\\lim_{x\\to 0}\\dfrac{\\sum_{k=1}^n e^{2kx}\\cos k\\pi x-n}{x}=12$ 형태로 정리.\n$0/0$이므로 로피탈 ($x$ 미분): 분자 $\\to\\sum_{k=1}^n(2k e^{2kx}\\cos k\\pi x-k\\pi e^{2kx}\\sin k\\pi x)\\big|_{x=0}=\\sum_{k=1}^n 2k=n(n+1)$.\n$n(n+1)=12\\Rightarrow n=3$.",
  },
  {n:21, subject:"적분학", unit:"급수의 수렴/발산", concept:"멱급수 수렴구간",
    difficulty:"easy",
    question:"멱급수 $\\displaystyle\\sum_{n=1}^{\\infty}\\tan\\!\\left(\\dfrac{2}{n}\\right)x^n$의 수렴 반지름과 수렴 구간을 구하면?",
    options:opts5("$1,\\,[-1,1)$","$1,\\,[-1,1]$","$1,\\,(-1,1]$","$2,\\,[-2,2)$","$2,\\,[-2,2]$"),
    correct:"1",
    explanation:"$\\tan(2/n)\\sim 2/n$이므로 $\\sum\\tan(2/n)x^n\\approx\\sum\\dfrac{2}{n}x^n$. 수렴반경 $R=1$.\n$x=-1$: $\\sum\\dfrac{(-1)^n\\cdot 2}{n}$ 교대급수 ⇒ 수렴.\n$x=1$: $\\sum\\dfrac{2}{n}$ 발산.\n수렴구간 $[-1,1)$.",
  },
  {n:22, subject:"적분학", unit:"멱급수와 적분", concept:"매클로린 급수 + 특이적분",
    difficulty:"medium",
    question:"다음 조건을 만족하는 두 실수 $a$와 $b$의 곱은?\n\n• $a$는 함수 $\\sin x\\cos x$의 매클로린 급수에서 $x^5$의 계수이다.\n• $b$는 구간 $(0,1)$에서 함수 $\\dfrac{1}{\\sqrt{x(1-x)}}$의 특이적분값이다.",
    options:opts5("$\\dfrac{2\\pi}{3}$","$\\dfrac{\\pi}{3}$","$\\dfrac{\\pi}{5}$","$\\dfrac{2\\pi}{15}$","$\\dfrac{\\pi}{15}$"),
    correct:"4",
    explanation:"(I) $\\sin x\\cos x=\\dfrac{1}{2}\\sin 2x=\\dfrac{1}{2}\\!\\left[2x-\\dfrac{(2x)^3}{3!}+\\dfrac{(2x)^5}{5!}-\\cdots\\right]$. $x^5$ 계수 $=\\dfrac{1}{2}\\cdot\\dfrac{32}{120}=\\dfrac{2}{15}$.\n(II) $\\!\\int_0^1\\dfrac{dx}{\\sqrt{x-x^2}}=\\!\\int_0^1\\dfrac{dx}{\\sqrt{(1/2)^2-(x-1/2)^2}}=[\\sin^{-1}(2x-1)]_0^1=\\dfrac{\\pi}{2}-\\!\\left(-\\dfrac{\\pi}{2}\\right)=\\pi$.\n$ab=\\dfrac{2}{15}\\cdot\\pi=\\dfrac{2\\pi}{15}$.",
  },
  {n:23, subject:"다변수함수", unit:"공간곡면", concept:"구면좌표 곡면 교선",
    difficulty:"medium",
    question:"다음과 같이 구면 좌표계로 주어진 두 곡면이 있다. 두 곡면이 만나는 곡선의 길이를 구하면? (단, $\\phi$는 천장각)\n$$\\rho-\\sec\\phi=0,\\quad\\rho\\sin^2\\phi-\\cos\\phi=0$$",
    options:opts5("$5\\pi$","$4\\pi$","$3\\pi$","$2\\pi$","$\\pi$"),
    correct:"4",
    explanation:"① $\\rho=\\sec\\phi\\Rightarrow\\rho\\cos\\phi=1\\Rightarrow z=1$.\n② $\\rho\\sin^2\\phi=\\cos\\phi$, 양변에 $\\rho$: $\\rho^2\\sin^2\\phi=\\rho\\cos\\phi\\Rightarrow x^2+y^2=z$.\n교선: $\\begin{cases}z=1\\\\z=x^2+y^2\\end{cases}\\Rightarrow x^2+y^2=1,\\,z=1$ (반지름 1 원).\n곡선의 길이 $=2\\pi$.",
  },
  {n:24, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"두 직선 사이의 거리",
    difficulty:"medium",
    question:"다음 두 직선 사이의 거리를 구하면?\n\n$l_1$: 두 평면 $x+2y-2z=1$과 $x-2y+2z=1$의 교선\n$l_2$: 점 $(1,0,6)$을 지나고 평면 $x+3y+z=5$와 수직인 직선",
    options:opts5("$\\sqrt{3}$","$2$","$\\sqrt{5}$","$\\sqrt{6}$","$\\sqrt{7}$"),
    correct:"4",
    explanation:"$l_1$ 방향벡터 $(1,2,-2)\\times(1,-2,2)=(0,-4,-4)\\sim(0,1,1)$, $z=0$ 대입 시 $(1,0,0)$. $l_1$: $(1,t,t)$.\n$l_2$ 방향 $(1,3,1)$, 점 $(1,0,6)$.\n공통수직 $\\vec{n}=(0,1,1)\\times(1,3,1)=(-2,1,-1)\\sim(2,-1,1)$, $|\\vec{n}|=\\sqrt{6}$.\n$\\vec{P_1P_2}=(0,0,6)$, $d=\\dfrac{|\\vec{P_1P_2}\\cdot\\vec{n}|}{|\\vec{n}|}=\\dfrac{|6|}{\\sqrt{6}}=\\sqrt{6}$.",
  },
  {n:25, subject:"다변수함수", unit:"공간곡선", concept:"곡률·곡선길이·삼각형 넓이",
    difficulty:"medium",
    question:"곡선 $\\vec{x}(t)=3\\sin t\\,\\vec{i}+4t\\,\\vec{j}+3\\cos t\\,\\vec{k}$에 대해 다음 조건을 만족하는 세 실수 $a,b,c$의 곱은?\n\n• $a$는 곡선 $x(t)$의 곡률이다.\n• $b$는 곡선 $x(t)$의 두 점 $x(0)$와 $x(5)$ 사이의 곡선 길이다.\n• $c$는 세 점 $x(0),\\,x'(0),\\,x''(0)$을 꼭지점으로 하는 삼각형의 넓이다.",
    options:opts5("$30$","$35$","$40$","$45$","$50$"),
    correct:"4",
    explanation:"① $r(t)=(p\\cos t,p\\sin t,qt)$ 형태의 곡률 $\\kappa=\\dfrac{p}{p^2+q^2}$ (여기서 $p=3,\\,q=4$). $a=\\dfrac{3}{25}$.\n② $|x'(t)|=\\sqrt{9\\cos^2 t+16+9\\sin^2 t}=\\sqrt{25}=5$. $b=\\!\\int_0^5 5\\,dt=25$.\n③ $x(0)=(0,0,3),\\,x'(0)=(3,4,0),\\,x''(0)=(0,0,-3)$. 변벡터 $(3,4,-3),(0,0,-6)$. 외적 $=(-24,18,0)$, $|\\cdot|=30$. 넓이 $c=15$.\n$abc=\\dfrac{3}{25}\\cdot 25\\cdot 15=45$.",
  },
  {n:26, subject:"적분학", unit:"부정적분", concept:"치환 + 부분적분",
    difficulty:"medium",
    question:"정적분 $\\displaystyle\\int_1^e x(\\ln x)^2\\,dx$의 값은?",
    options:opts5("$\\dfrac{e^2+1}{5}$","$\\dfrac{e^2-1}{4}$","$\\dfrac{e^3-1}{3}$","$\\dfrac{e^3+1}{2}$","$e^4-1$"),
    correct:"2",
    explanation:"$\\ln x=t,\\,x=e^t,\\,dx=e^t\\,dt$ (구간 $0\\to 1$). $\\displaystyle\\int_0^1 t^2 e^{2t}\\,dt$.\n부분적분 (DI 표): $=\\!\\left[\\dfrac{1}{2}t^2 e^{2t}-\\dfrac{1}{2}t e^{2t}+\\dfrac{1}{4}e^{2t}\\right]_0^1=\\dfrac{1}{2}e^2-\\dfrac{1}{2}e^2+\\dfrac{1}{4}e^2-\\dfrac{1}{4}=\\dfrac{e^2-1}{4}$.",
  },
  {n:27, subject:"다변수함수", unit:"이중적분", concept:"극좌표 이중적분",
    difficulty:"medium",
    question:"영역 $\\Omega$가 $r=4\\sin\\theta$의 내부와 $r=2$의 외부로 둘러싸인 집합의 제 1사분면에 있는 부분일 때, $\\displaystyle\\iint_\\Omega x\\,dxdy$의 값은?",
    options:opts5("$\\dfrac{15}{7}$","$\\dfrac{13}{7}$","$\\dfrac{13}{5}$","$\\dfrac{11}{5}$","$\\dfrac{11}{3}$"),
    correct:"5",
    explanation:"두 원 교점: $4\\sin\\theta=2\\Rightarrow\\theta=\\pi/6$. 제1사분면 영역: $\\theta\\in[\\pi/6,\\pi/2],\\,r\\in[2,4\\sin\\theta]$.\n$\\!\\iint x\\,dA=\\!\\int_{\\pi/6}^{\\pi/2}\\!\\!\\int_2^{4\\sin\\theta}r^2\\cos\\theta\\,dr\\,d\\theta=\\dfrac{1}{3}\\!\\int_{\\pi/6}^{\\pi/2}\\cos\\theta(64\\sin^3\\theta-8)\\,d\\theta$\n$=\\dfrac{1}{3}[16\\sin^4\\theta-8\\sin\\theta]_{\\pi/6}^{\\pi/2}=\\dfrac{1}{3}\\!\\left[(16-8)-\\!\\left(1-4\\right)\\right]=\\dfrac{1}{3}(8+3)=\\dfrac{11}{3}$.",
  },
  {n:28, subject:"다변수함수", unit:"이중적분", concept:"삼각형 영역 이중적분",
    difficulty:"medium",
    question:"영역 $\\Omega=\\{(x,y)\\mid x\\ge 0,\\,y\\ge 0,\\,ax+y-1\\le 0\\}$에서 $\\displaystyle\\iint_\\Omega(x^2+y^2)\\,dxdy=\\dfrac{1}{6}$일 때, 양수 $a$의 값은?",
    options:opts5("$1$","$2$","$3$","$4$","$5$"),
    correct:"1",
    explanation:"삼각형 영역 (밑변 $1/a$, 높이 $1$).\n$\\!\\iint x^2\\,dA=\\!\\int_0^{1/a}x^2(1-ax)\\,dx=\\dfrac{1}{3a^3}-\\dfrac{1}{4a^3}=\\dfrac{1}{12a^3}$.\n$\\!\\iint y^2\\,dA=\\dfrac{1}{a}\\!\\int_0^1 y^2(1-y)\\,dy=\\dfrac{1}{12a}$.\n합 $=\\dfrac{1}{12a^3}+\\dfrac{1}{12a}=\\dfrac{a^2+1}{12a^3}=\\dfrac{1}{6}\\Rightarrow 2a^3=a^2+1\\Rightarrow(a-1)(2a^2+a+1)=0\\Rightarrow a=1$.",
  },
  {n:29, subject:"다변수함수", unit:"삼중적분", concept:"구면좌표 + 대칭성",
    difficulty:"medium",
    question:"영역 $Q=\\{(x,y,z)\\mid x^2+y^2+z^2\\le 1\\}$에서 $\\displaystyle\\iiint_Q(4x^2+5y^2+6z^2)\\,dxdydz$의 값은?",
    options:opts5("$\\dfrac{\\pi}{2}$","$\\pi$","$2\\pi$","$3\\pi$","$4\\pi$"),
    correct:"5",
    explanation:"구의 대칭성: $\\!\\iiint x^2\\,dV=\\!\\iiint y^2\\,dV=\\!\\iiint z^2\\,dV=\\dfrac{1}{3}\\!\\iiint(x^2+y^2+z^2)\\,dV$.\n반지름 1 구에서 $\\!\\iiint(x^2+y^2+z^2)\\,dV=\\!\\int_0^{2\\pi}\\!\\!\\int_0^\\pi\\!\\!\\int_0^1\\rho^2\\cdot\\rho^2\\sin\\phi\\,d\\rho\\,d\\phi\\,d\\theta=2\\pi\\cdot 2\\cdot\\dfrac{1}{5}=\\dfrac{4\\pi}{5}$.\n준식 $=(4+5+6)\\cdot\\dfrac{1}{3}\\cdot\\dfrac{4\\pi}{5}=15\\cdot\\dfrac{4\\pi}{15}=4\\pi$.",
  },
  {n:30, subject:"미분학", unit:"종합", concept:"진위판단 (혼합)",
    difficulty:"medium",
    question:"다음 중 참인 명제의 개수는?\n\nⓐ $\\dfrac{d}{dx}\\tanh x=\\text{sech}^2 x$\nⓑ $\\sinh^{-1}x=\\ln(x+\\sqrt{x^2+1})$\nⓒ $\\displaystyle\\int(x+1)e^x\\ln x\\,dx=e^x(x\\ln x-1)+C$\nⓓ $\\displaystyle\\sum_{n=2}^{\\infty}(-1)^n\\dfrac{\\ln n}{n}$은 절대수렴한다.\nⓔ 공간의 두 벡터 $\\vec{u},\\vec{v}$에 대해 $\\vec{u}\\cdot(\\vec{u}\\times\\vec{v})=0$",
    options:opts5("5개","4개","3개","2개","1개"),
    correct:"2",
    explanation:"ⓐ [참] 쌍곡함수 미분 공식.\nⓑ [참] 역쌍곡함수 정의.\nⓒ [참] $\\dfrac{d}{dx}[e^x(x\\ln x-1)]=e^x(x\\ln x-1)+e^x(\\ln x+1)=(1+x)e^x\\ln x$.\nⓓ [거짓] $\\sum\\dfrac{\\ln n}{n}$ 발산이므로 조건부수렴 (절대수렴 아님).\nⓔ [참] $\\vec{u}\\times\\vec{v}\\perp\\vec{u}$.\n참 4개.",
  },
];

const TOTAL=PROBLEMS.length;
console.log(`총 ${TOTAL}문제 (객관식) 준비됨`);

const rows = PROBLEMS.map(p => {
  const id = `q-${YEAR}-${SCHOOL_EN}-${String(p.n).padStart(2,"0")}`;
  return {
    id, subject: p.subject, unit: p.unit, concept: p.concept, difficulty: p.difficulty,
    source_type: "imported", pool: "general", question: p.question, content_type: "latex",
    question_image: null, question_type: "multiple_choice",
    options: p.options, correct_option_id: p.correct,
    answer_text: null, explanation: p.explanation, explanation_content_type: "latex",
    explanation_image: null,
    tags: [YEAR, SCHOOL_KO, "past_exam", p.subject, p.unit, p.concept],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  };
});

const { data, error } = await sb.from("questions").upsert(rows, { onConflict: "id" }).select("id");
if (error) { console.error("업로드 실패:", error); process.exit(1); }
console.log(`업로드 완료: ${data.length}건`);
