// 2023년 중앙대(수학과) 편입수학 객관식 30문항 (4지선다)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR="2023", SCHOOL_KO="중앙대", SCHOOL_EN="cau";
const opts4 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:1, subject:"선형대수", unit:"선형변환", concept:"커널까지 거리",
    difficulty:"medium",
    question:"선형변환 $T:\\mathbb R^3\\to\\mathbb R^3$가 $T\\!\\binom{1}{0}_{\\!0}=\\!\\binom{1}{2}_{\\!2},\\,T\\!\\binom{1}{1}_{\\!0}=\\!\\binom{-4}{5}_{\\!1},\\,T\\!\\binom{1}{1}_{\\!1}=\\!\\binom{5}{-3}_{\\!1}$을 만족한다고 하자. $T$의 핵(kernel)에 속하는 점과 점 $\\binom{1}{-2}_{\\!3}$ 사이의 최소 거리는? (단, 세로벡터를 가로 표기.)",
    options:opts4("$\\sqrt 8$","$\\sqrt{10}$","$\\sqrt{12}$","$\\sqrt{14}$"),
    correct:"4",
    explanation:"$T$의 행렬 $A=\\begin{pmatrix}1&-4&5\\\\2&5&-3\\\\2&1&1\\end{pmatrix}$, $\\det A=0$ → $\\mathrm{rank}=2,\\,\\dim\\ker=1$.\n$\\ker=\\mathrm{span}\\,(-1,1,1)$. 점 $P=(1,-2,3)$의 $\\ker$ 방향 정사영: $P\\cdot d=-1-2+3=0$ → 직각.\n거리 $=|P|=\\sqrt{1+4+9}=\\sqrt{14}$.",
  },
  {n:2, subject:"적분학", unit:"정적분", concept:"astroid 1/4 영역 면적",
    difficulty:"medium",
    question:"세 부등식 $x^{2/3}+y^{2/3}\\le 1,\\,x\\ge 0,\\,y\\ge 0$에 의해서 정의되는 영역의 넓이는?",
    options:opts4("$\\dfrac{3\\pi}{16}$","$\\dfrac{3\\pi}{32}$","$\\dfrac{\\pi}{8}$","$\\dfrac{5\\pi}{64}$"),
    correct:"2",
    explanation:"전체 astroid 면적 $=\\dfrac{3\\pi}{8}$이며 $1/4$만 취하면 $\\dfrac{3\\pi}{32}$.",
  },
  {n:3, subject:"선형대수", unit:"고유치와 대각화", concept:"고유값 역수합",
    difficulty:"medium",
    question:"행렬 $\\begin{pmatrix}0.1&0.2&-0.1\\\\0.1&0&0.2\\\\0.4&0.4&0.5\\end{pmatrix}$의 고윳값 $\\alpha,\\beta,\\gamma$에 대하여 $\\dfrac{3}{\\alpha}+\\dfrac{3}{\\beta}+\\dfrac{3}{\\gamma}$의 값은?",
    options:opts4("$3$","$4$","$5$","$6$"),
    correct:"3",
    explanation:"$e_2=\\!\\sum\\lambda_i\\lambda_j=-0.01,\\,e_3=\\det A=-0.006$.\n$\\!\\sum 1/\\lambda_i=e_2/e_3=-0.01/-0.006=5/3$. $3\\cdot 5/3=5$.",
  },
  {n:4, subject:"미분학", unit:"도함수와 그래프", concept:"음함수 최단거리",
    difficulty:"medium",
    question:"곡선 $3y^2=x^3$ 위의 점과 점 $(0,\\sqrt 3)$ 사이의 최소 거리는?",
    options:opts4("$\\sqrt{\\dfrac{7}{3}}$","$\\sqrt{\\dfrac{5}{3}}$","$\\sqrt{\\dfrac{4}{3}}$","$\\sqrt{\\dfrac{2}{3}}$"),
    correct:"1",
    explanation:"라그랑주: $y(2+x)/x=\\sqrt 3$, $3y^2=x^3$. 풀면 $x=1,\\,y=1/\\sqrt 3$.\n거리$^2=1+(1/\\sqrt 3-\\sqrt 3)^2=1+4/3=7/3$.",
  },
  {n:5, subject:"다변수함수", unit:"중적분", concept:"적분순서 변경",
    difficulty:"easy",
    question:"$\\!\\displaystyle\\int_0^1\\!\\!\\int_{\\sqrt y}^1 e^{x^3}\\,dx\\,dy$의 값은?",
    options:opts4("$\\dfrac{1}{2}(e-1)$","$\\dfrac{1}{2}(e+1)$","$\\dfrac{1}{3}(e-1)$","$\\dfrac{1}{3}(e+1)$"),
    correct:"3",
    explanation:"순서 변경 $0\\le x\\le 1,\\,0\\le y\\le x^2$: $\\!\\int_0^1 x^2 e^{x^3}dx=\\dfrac{1}{3}(e-1)$.",
  },
  {n:6, subject:"선형대수", unit:"고유치와 대각화", concept:"행렬 거듭제곱 극한",
    difficulty:"medium",
    question:"$\\begin{pmatrix}1&0\\\\1.5&0.5\\end{pmatrix}^{\\!n}=\\begin{pmatrix}a_n&b_n\\\\c_n&d_n\\end{pmatrix}$이라 할 때, $\\!\\displaystyle\\lim_{n\\to\\infty}(a_n+b_n+c_n+d_n)$의 값은?",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"4",
    explanation:"고유값 $1,\\,1/2$. $A^n$ 계산하면 $\\begin{pmatrix}1&0\\\\3-3/2^n&1/2^n\\end{pmatrix}$.\n극한 $\\to\\begin{pmatrix}1&0\\\\3&0\\end{pmatrix}$, 합 $=4$.",
  },
  {n:7, subject:"적분학", unit:"정적분", concept:"두 원 교집합 영역",
    difficulty:"medium",
    question:"두 부등식 $x^2+y^2\\ge 4,\\,x^2+(y-\\sqrt 3)^2\\le 1$을 만족하는 점들이 이루는 영역의 넓이는?",
    options:opts4("$\\sqrt 3-\\dfrac{\\pi}{6}$","$\\sqrt 6-\\dfrac{\\pi}{3}$","$\\sqrt 3-\\dfrac{\\pi}{4}$","$\\sqrt 6-\\dfrac{\\pi}{4}$"),
    correct:"1",
    explanation:"두 원 교점 $(\\pm 1,\\sqrt 3)$. 작은 원 $(0,\\sqrt 3),\\,r=1$ 안에서 큰 원 $r=2$ 밖 영역.\n원호 적분과 영역 분리 후 면적 $=\\sqrt 3-\\dfrac{\\pi}{6}$.",
  },
  {n:8, subject:"미분학", unit:"도함수와 그래프", concept:"각 최대화",
    difficulty:"medium",
    question:"$x$축 위의 점 $P(t,0)$과 두 점 $A(0,2),B(5,7)$을 꼭짓점으로 가지는 삼각형 $APB$에서 각 $APB$가 가장 커지도록 하는 실수 $t$는? (단, $0\\le t\\le 5$.)",
    options:opts4("$5\\sqrt 2-7$","$7\\sqrt 2-5$","$2\\sqrt 5-2$","$2\\sqrt 7-2$"),
    correct:"4",
    explanation:"$\\tan(\\angle APB)=\\dfrac{|\\overrightarrow{PA}\\times\\overrightarrow{PB}|}{\\overrightarrow{PA}\\cdot\\overrightarrow{PB}}=\\dfrac{5t+10}{t^2-5t+14}$.\n도함수 $=0$: $t^2+4t-24=0\\Rightarrow t=-2+2\\sqrt 7=2\\sqrt 7-2$.",
  },
  {n:9, subject:"미분학", unit:"편도함수", concept:"이차함수 최솟값",
    difficulty:"medium",
    question:"$(x+3y-5)^2+(x-y-1)^2+(x+y)^2$의 최솟값은?",
    options:opts4("$2$","$3$","$6$","$12$"),
    correct:"3",
    explanation:"편미분 $=0$: $x+y=2,\\,3x+11y=14\\Rightarrow x=1,\\,y=1$.\n값 $=(1+3-5)^2+(1-1-1)^2+(1+1)^2=1+1+4=6$.",
  },
  {n:10, subject:"선형대수", unit:"선형변환", concept:"좌표 변환 후 평가",
    difficulty:"medium",
    question:"차수가 $2$이하인 다항식으로 이루어진 벡터공간 $\\mathbb P_2$에 정의된 선형사상 $T:\\mathbb P_2\\to\\mathbb P_2$가 주어져 있다. $\\mathbb P_2$의 순서기저 $B=\\{1+t^2,\\,t+t^2,\\,1+2t+t^2\\}$에 대한 $T$의 행렬표현이 $[T]_B=\\begin{pmatrix}3&4&0\\\\0&5&-1\\\\1&-2&7\\end{pmatrix}$이고 $p(t)=T(1+t+t^2)$라 할 때, $p(-1)$의 값은?",
    options:opts4("$0$","$1$","$2$","$3$"),
    correct:"4",
    explanation:"$1+t+t^2=\\dfrac{1}{2}(1+t^2)+0\\cdot(t+t^2)+\\dfrac{1}{2}(1+2t+t^2)$.\n$[T]_B(1/2,0,1/2)^T=(3/2,-1/2,4)^T$. $p(t)=\\dfrac{3}{2}(1+t^2)-\\dfrac{1}{2}(t+t^2)+4(1+2t+t^2)=\\dfrac{11}{2}+\\dfrac{15}{2}t+5t^2$.\n$p(-1)=\\dfrac{11-15}{2}+5=3$.",
  },
  {n:11, subject:"선형대수", unit:"행렬", concept:"rank-nullity 차원관계",
    difficulty:"medium",
    question:"모든 성분이 실수인 $m\\times n$ 행렬 $A$에 대하여 $A$의 영공간과 $A^T$의 영공간은 그 차원이 각각 $7,2$이고 $A^TA$는 차원이 $k$인 영공간을 갖는다고 하자. $m-n+k$의 값은? (단, $A^T$는 $A$의 전치행렬이다.)",
    options:opts4("$-5$","$-2$","$2$","$5$"),
    correct:"3",
    explanation:"$\\mathrm{rank}(A)=n-7=m-2\\Rightarrow n=m+5$. $\\ker(A^TA)=\\ker A$ → $k=7$.\n$m-n+k=m-(m+5)+7=2$.",
  },
  {n:12, subject:"미분학", unit:"도함수", concept:"역함수 미분 응용",
    difficulty:"medium",
    question:"미분가능한 두 함수 $f,g$가 $f'(x)=1+[f(x)]^2$과 $f(g(x))=x$를 만족할 때, $g'(2)$의 값은?",
    options:opts4("$\\dfrac{1}{12}$","$\\dfrac{1}{10}$","$\\dfrac{1}{5}$","$\\dfrac{1}{2}$"),
    correct:"3",
    explanation:"$f'(y)=1+f(y)^2\\Rightarrow f(y)=\\tan y$ (적분 후). $g=f^{-1}=\\arctan x$.\n$g'(x)=\\dfrac{1}{1+x^2}$, $g'(2)=\\dfrac{1}{5}$.",
  },
  {n:13, subject:"미분학", unit:"도함수", concept:"로그미분 접선",
    difficulty:"easyMedium",
    question:"곡선 $y=x^{\\sin x}$ 위의 점 $\\!\\left(\\dfrac{\\pi}{2},\\dfrac{\\pi}{2}\\right)$에서의 접선의 기울기는?",
    options:opts4("$\\dfrac{1}{6}$","$\\dfrac{1}{3}$","$\\dfrac{1}{2}$","$1$"),
    correct:"4",
    explanation:"$\\ln y=\\sin x\\ln x$. 미분: $\\dfrac{y'}{y}=\\cos x\\ln x+\\dfrac{\\sin x}{x}$.\n$x=\\pi/2$: $y'=\\dfrac{\\pi}{2}\\!\\left(0+\\dfrac{2}{\\pi}\\right)=1$.",
  },
  {n:14, subject:"다변수함수", unit:"편도함수", concept:"접평면 z축 교점",
    difficulty:"medium",
    question:"곡면 $x^4+y^4+z^4-3x^2y^2z^2=0$ 위의 점 $(1,1,\\sqrt 2)$에서의 접평면은 $z$축과 점 $(0,0,a)$에서 만난다. $a$의 값은?",
    options:opts4("$-3\\sqrt 2$","$-\\sqrt 2$","$\\sqrt 2$","$3\\sqrt 2$"),
    correct:"1",
    explanation:"$\\nabla F=(4x^3-6xy^2z^2,\\,4y^3-6x^2yz^2,\\,4z^3-6x^2y^2z)$. $(1,1,\\sqrt 2)$: $(-8,-8,2\\sqrt 2)$.\n접평면: $-8x-8y+2\\sqrt 2 z+12=0$. $x=y=0$: $z=-3\\sqrt 2$.",
  },
  {n:15, subject:"미분학", unit:"극한과 연속", concept:"sinh 테일러 극한",
    difficulty:"easy",
    question:"극한 $\\!\\displaystyle\\lim_{x\\to 0}\\dfrac{\\sinh x-x}{x^3}$의 값은?",
    options:opts4("$\\dfrac{1}{12}$","$\\dfrac{1}{6}$","$\\dfrac{1}{4}$","$\\dfrac{1}{3}$"),
    correct:"2",
    explanation:"$\\sinh x=x+\\dfrac{x^3}{6}+\\cdots$. 차 $=\\dfrac{x^3}{6}+\\cdots$. 극한 $=\\dfrac{1}{6}$.",
  },
  {n:16, subject:"미분학", unit:"도함수와 그래프", concept:"포물선 거리 최솟값",
    difficulty:"easyMedium",
    question:"점 $(1,4)$와 곡선 $y^2=2x$ 위의 점 $(x,y)$ 사이의 거리의 최솟값은?",
    options:opts4("$\\dfrac{3\\sqrt 5}{5}$","$\\dfrac{4\\sqrt 5}{5}$","$\\sqrt 5$","$\\dfrac{6\\sqrt 5}{5}$"),
    correct:"3",
    explanation:"$y^2=2x\\Rightarrow x=y^2/2$. 거리$^2=(y^2/2-1)^2+(y-4)^2$ 미분 $=0$: $y^3-2y+2y-8=0\\Rightarrow y=2,\\,x=2$.\n거리 $=\\sqrt{1+4}=\\sqrt 5$.",
  },
  {n:17, subject:"적분학", unit:"정적분", concept:"y축 회전 부피 부분분수",
    difficulty:"medium",
    question:"곡선 $y=\\dfrac{2}{x^3-x^2-x+1}$과 세 직선 $y=0,\\,x=0,\\,x=\\dfrac{1}{2}$로 둘러싸인 영역을 $y$축을 중심으로 회전하여 얻은 회전체의 부피는?",
    options:opts4("$\\pi(2-\\ln 2)$","$\\pi(2-\\ln 3)$","$\\pi(3-\\ln 2)$","$\\pi(3-\\ln 3)$"),
    correct:"2",
    explanation:"$x^3-x^2-x+1=(x-1)^2(x+1)$. 원통껍질: $V=2\\pi\\!\\int_0^{1/2}\\dfrac{2x}{(x-1)^2(x+1)}dx$.\n부분분수 후 적분: $V=\\pi(2-\\ln 3)$.",
  },
  {n:18, subject:"미분학", unit:"편도함수", concept:"타원 내접 직사각형 면적",
    difficulty:"easyMedium",
    question:"타원 $x^2+\\dfrac{y^2}{4}=1$에 내접하는 직사각형의 넓이의 최댓값은?",
    options:opts4("$\\dfrac{15}{4}$","$4$","$\\dfrac{17}{4}$","$\\dfrac{9}{2}$"),
    correct:"2",
    explanation:"$x=\\cos\\theta,\\,y=2\\sin\\theta$. 면적 $=2x\\cdot 2y=4\\sin 2\\theta$. 최댓값 $=4$.",
  },
  {n:19, subject:"적분학", unit:"부정적분", concept:"바이어슈트라스 치환",
    difficulty:"medium",
    question:"$\\!\\displaystyle\\int_{\\pi/3}^{\\pi/2}\\dfrac{1}{1+\\sin x-\\cos x}\\,dx$의 값은?",
    options:opts4("$\\ln\\dfrac{1+\\sqrt 2}{2}$","$\\ln\\dfrac{1+\\sqrt 3}{2}$","$\\ln\\dfrac{2+\\sqrt 2}{2}$","$\\ln\\dfrac{2+\\sqrt 3}{2}$"),
    correct:"2",
    explanation:"$t=\\tan(x/2)$: $dx/(1+\\sin x-\\cos x)=\\dfrac{dt}{t(t+1)}=\\!\\left(\\dfrac{1}{t}-\\dfrac{1}{t+1}\\right)dt$.\n범위 $t:1/\\sqrt 3\\to 1$. 적분 $=\\ln\\dfrac{t}{t+1}\\big|=\\ln\\dfrac{1+\\sqrt 3}{2}$.",
  },
  {n:20, subject:"적분학", unit:"급수의 수렴/발산", concept:"수렴 보기 4개",
    difficulty:"medium",
    question:"다음 <보기>의 급수 중에서 수렴하는 것의 개수는?\n(가) $\\!\\displaystyle\\sum_{n=2}^{\\infty}\\dfrac{1}{n(\\ln n)^2}$\n(나) $\\!\\displaystyle\\sum_{n=1}^{\\infty}\\!\\left(\\dfrac{2n+3}{3n+2}\\right)^{\\!n}$\n(다) $\\!\\displaystyle\\sum_{n=1}^{\\infty}(-1)^n\\dfrac{\\sqrt n\\ln(1+n)}{n+1}$\n(라) $\\!\\displaystyle\\sum_{n=1}^{\\infty}\\sin\\!\\left(\\dfrac{1}{n}\\right)$",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"3",
    explanation:"(가) $p$-급수 $p=2>1$ 수렴. (나) 비율 $\\to 2/3<1$ 수렴. (다) 교대급수 $\\ln n/\\sqrt n\\to 0$ 단조감소 → 수렴. (라) $\\sim 1/n$ 발산.\n수렴 $3$개.",
  },
  {n:21, subject:"적분학", unit:"급수의 수렴/발산", concept:"로그 멱급수",
    difficulty:"easy",
    question:"함수 $f(x)=\\!\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{x^n}{n}$에 대하여 $f\\!\\left(\\dfrac{1}{2}\\right)$의 값은?",
    options:opts4("$\\ln\\dfrac{3}{2}$","$\\ln 2$","$\\ln\\dfrac{5}{2}$","$\\ln 3$"),
    correct:"2",
    explanation:"$f(x)=-\\ln(1-x)$. $f(1/2)=-\\ln(1/2)=\\ln 2$.",
  },
  {n:22, subject:"미분학", unit:"도함수", concept:"함수방정식 + 미분",
    difficulty:"medium",
    question:"미분가능한 함수 $f(x)$가 다음 두 조건을 만족한다. 이때 $f(3)$의 값은?\n(i) 모든 실수 $x,y$에 대하여 $f(x+y)=f(x)+f(y)+x^2y+xy^2$\n(ii) $\\!\\displaystyle\\lim_{x\\to 0}\\dfrac{f(x)}{x}=1$",
    options:opts4("$10$","$12$","$14$","$16$"),
    correct:"2",
    explanation:"$f(0)=0,\\,f'(x)=\\!\\lim_{h\\to 0}\\dfrac{f(h)+x^2 h+xh^2}{h}=1+x^2$.\n$f(x)=x+\\dfrac{x^3}{3}$. $f(3)=3+9=12$.",
  },
  {n:23, subject:"다변수함수", unit:"편도함수", concept:"극좌표 최댓값",
    difficulty:"medium",
    question:"영역 $x^2+y^2\\le 4$에서 함수 $f(x,y)=e^{-x^2-y^2}(x^2+2y^2)$의 최댓값은?",
    options:opts4("$\\dfrac{2}{e}$","$\\dfrac{4}{e^2}$","$\\dfrac{6}{e^3}$","$\\dfrac{8}{e^4}$"),
    correct:"1",
    explanation:"극좌표 $f=e^{-r^2}r^2(1+\\sin^2\\theta)$. $\\sin^2\\theta=1$ 최대. $g(r)=2r^2 e^{-r^2}$ 미분 $=0$: $r=1$.\n최대 $=2\\cdot 1\\cdot e^{-1}=\\dfrac{2}{e}$.",
  },
  {n:24, subject:"다변수함수", unit:"중적분", concept:"적분순서 변경",
    difficulty:"easyMedium",
    question:"$\\!\\displaystyle\\int_0^4\\!\\!\\int_{\\sqrt x}^{2}\\dfrac{1}{y^3+1}\\,dy\\,dx$의 값은?",
    options:opts4("$\\dfrac{1}{3}\\ln 2$","$\\dfrac{1}{3}\\ln 3$","$\\dfrac{2}{3}\\ln 2$","$\\dfrac{2}{3}\\ln 3$"),
    correct:"4",
    explanation:"순서 변경 $0\\le y\\le 2,\\,0\\le x\\le y^2$: $\\!\\int_0^2\\dfrac{y^2}{y^3+1}dy=\\dfrac{1}{3}\\ln(y^3+1)\\big|_0^2=\\dfrac{1}{3}\\ln 9=\\dfrac{2}{3}\\ln 3$.",
  },
  {n:25, subject:"다변수함수", unit:"선적분과 면적분", concept:"각도 함수 선적분",
    difficulty:"easyMedium",
    question:"$0\\le t\\le 1$에서 정의된 곡선 $C$는 $r(t)=(e^t\\cos t,\\,e^t\\sin t)$로 주어지고 $t=0$에서 출발하여 $t=1$에서 끝난다. 벡터장 $F(x,y)=\\dfrac{(-y,x)}{x^2+y^2}$에 대하여 선적분 $\\!\\displaystyle\\int_C F\\cdot dr$의 값은?",
    options:opts4("$1$","$\\dfrac{3}{2}$","$2$","$\\dfrac{5}{2}$"),
    correct:"1",
    explanation:"$F=\\nabla\\theta$ (각도). $\\theta(t)=\\arctan(\\sin t/\\cos t)=t$.\n적분 $=\\theta(1)-\\theta(0)=1$.",
  },
  {n:26, subject:"다변수함수", unit:"선적분과 면적분", concept:"구면 inverse-distance 적분",
    difficulty:"medium",
    question:"구면 $S:x^2+y^2+z^2=4$에 대하여 $\\!\\displaystyle\\iint_S\\dfrac{dS}{\\sqrt{x^2+y^2+(z-1)^2}}$의 값은?",
    options:opts4("$8\\pi-1$","$8\\pi$","$8\\pi+1$","$8\\pi+2$"),
    correct:"2",
    explanation:"점 $P=(0,0,1)$이 구 내부 ($|OP|=1<2=R$)이므로 $\\!\\iint_S\\dfrac{dS}{|x-P|}=\\dfrac{4\\pi R^2}{R}=4\\pi R=8\\pi$.",
  },
  {n:27, subject:"다변수함수", unit:"선적분과 면적분", concept:"발산정리",
    difficulty:"medium",
    question:"세 평면 $z=0,\\,y=0,\\,y=2$와 곡면 $z=1-x^2$으로 둘러싸인 영역 $R$의 경계를 $S$라 하자. 이때 벡터장 $F(x,y,z)=(x+\\sin y,\\,2y+\\cos x,\\,3z)$에 대하여 $\\!\\displaystyle\\iint_S F\\cdot dS$의 값은?",
    options:opts4("$13$","$14$","$15$","$16$"),
    correct:"4",
    explanation:"$\\mathrm{div}\\,F=1+2+3=6$. 부피 $V=\\!\\int_{-1}^1(1-x^2)dx\\cdot 2=\\dfrac{4}{3}\\cdot 2=\\dfrac{8}{3}$.\n적분 $=6\\cdot\\dfrac{8}{3}=16$.",
  },
  {n:28, subject:"다변수함수", unit:"중적분", concept:"구면좌표 지수 적분",
    difficulty:"easyMedium",
    question:"$B:x^2+y^2+z^2\\le 1$에 대하여 $\\!\\displaystyle\\iiint_B e^{(x^2+y^2+z^2)^{3/2}}\\,dV$의 값은?",
    options:opts4("$\\dfrac{4}{3}\\pi(e-1)$","$\\dfrac{5}{3}\\pi(e-1)$","$\\dfrac{4}{3}\\pi(e+1)$","$\\dfrac{5}{3}\\pi(e+1)$"),
    correct:"1",
    explanation:"구면좌표: $\\!\\int_0^{2\\pi}\\!\\!\\int_0^\\pi\\sin\\phi\\,d\\phi\\,d\\theta\\cdot\\!\\int_0^1 e^{\\rho^3}\\rho^2 d\\rho=4\\pi\\cdot\\dfrac{1}{3}(e-1)=\\dfrac{4}{3}\\pi(e-1)$.",
  },
  {n:29, subject:"다변수함수", unit:"편도함수", concept:"기울기 비율",
    difficulty:"medium",
    question:"$f(x,y)=xe^{x^2+y^2}\\sin(y^2)$에 대하여 $\\nabla f(1,1)=(a,b)$라 할 때, $\\dfrac{b}{a}$의 값은? (단, $\\nabla f(1,1)$은 $(1,1)$에서 $f$의 기울기 벡터이다.)",
    options:opts4("$\\dfrac{2}{3}(1+\\tan(1))$","$\\dfrac{2}{3}(2+\\tan(1))$","$\\dfrac{2}{3}(1+\\cot(1))$","$\\dfrac{2}{3}(2+\\cot(1))$"),
    correct:"3",
    explanation:"$f_x=e^{x^2+y^2}\\sin(y^2)(1+2x^2)$, $(1,1)$: $a=3e^2\\sin 1$.\n$f_y=2xy\\,e^{x^2+y^2}(\\sin y^2+\\cos y^2)$, $(1,1)$: $b=2e^2(\\sin 1+\\cos 1)$.\n$b/a=\\dfrac{2(\\sin 1+\\cos 1)}{3\\sin 1}=\\dfrac{2}{3}(1+\\cot 1)$.",
  },
  {n:30, subject:"선형대수", unit:"행렬", concept:"블록 대각 행렬식",
    difficulty:"easyMedium",
    question:"행렬 $\\begin{pmatrix}3&1&0&0&0\\\\1&2&0&0&0\\\\0&0&1&1&0\\\\0&0&1&3&1\\\\0&0&2&0&2\\end{pmatrix}$의 행렬식은?",
    options:opts4("$24$","$26$","$28$","$30$"),
    correct:"4",
    explanation:"블록 대각: $\\det\\begin{pmatrix}3&1\\\\1&2\\end{pmatrix}=5$, $\\det\\begin{pmatrix}1&1&0\\\\1&3&1\\\\2&0&2\\end{pmatrix}=6$.\n전체 $\\det=5\\cdot 6=30$.",
  },
];

if (PROBLEMS.length !== 30) { console.error(`PROBLEMS length=${PROBLEMS.length} (expect 30)`); process.exit(1); }
let okCount=0,failCount=0;
for (const p of PROBLEMS) {
  const num=String(p.n).padStart(2,"0");
  const id=`q-${YEAR}-${SCHOOL_EN}-${num}`;
  const tags=[YEAR,SCHOOL_KO,p.subject,p.unit,p.concept].filter(Boolean);
  const row={id,subject:p.subject,unit:p.unit,concept:p.concept,difficulty:p.difficulty,
    source_type:"imported",pool:"general",
    question:p.question,content_type:"latex",question_image:null,
    options:p.options,correct_option_id:p.correct,
    explanation:p.explanation,explanation_content_type:"latex",explanation_image:null,
    tags,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};
  const{error}=await sb.from("questions").upsert(row,{onConflict:"id"});
  if(error){console.error(`❌ ${id}:`,error.message);failCount++;}
  else{console.log(`✓ ${id}`);okCount++;}
}
console.log(`\n총 ${okCount}건 업로드, ${failCount}건 실패 (대상 ${PROBLEMS.length}건)`);
