// Upload 적분학 Daily TEST 11~35 (150 problems).
// Usage: node scripts/upload_daily_tests_int_11to35.mjs
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(
  envText.split(/\r?\n/).filter((l) => l && !l.startsWith("#") && l.includes("="))
    .map((l) => { const [k, ...r] = l.split("="); return [k.trim(), r.join("=").trim()]; })
);
const supabase = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.NEXT_PUBLIC_SUPABASE_ANON_KEY);

const o = (id, text) => ({ id, label: id, text, contentType: "latex", image: "" });
function build({ testNo, num, unit, concept, difficulty, question, options, answer, explanation }) {
  const id = `q-daily-int-r${testNo}-${num}`;
  const tags = Array.from(new Set(["daily", `daily-test-int-${testNo}`, "적분학", unit, concept].filter(Boolean)));
  return {
    id, subject: "적분학", unit, concept, difficulty,
    source_type: "imported", question, content_type: "latex", question_image: null,
    options, correct_option_id: answer, explanation, explanation_content_type: "latex",
    explanation_image: null, tags,
    created_at: new Date().toISOString(), updated_at: new Date().toISOString()
  };
}

const problems = [
  // ========== DT11 ==========
  build({ testNo: 11, num: 1, unit: "정적분의 계산", concept: "와이어슈트라스 치환", difficulty: "easyMedium",
    question: "$\\displaystyle\\int_0^{\\pi/2}\\dfrac{5}{4\\sin x+3\\cos x}\\,dx$의 값은?",
    options: [o("1","$\\ln 2$"),o("2","$\\ln 3$"),o("3","$\\ln 6$"),o("4","$\\ln 9$"),o("5","$\\ln 12$")],
    answer: "3",
    explanation: "$t=\\tan(x/2)$ 치환. 결과 $\\int_0^1\\dfrac{10}{(3-t)(1+3t)}dt=\\ln 6$." }),
  build({ testNo: 11, num: 2, unit: "정적분의 계산", concept: "와이어슈트라스 치환", difficulty: "easyMedium",
    question: "$\\displaystyle\\int_0^{\\pi/4}\\dfrac{1}{1+\\tan x}\\,dx$의 값은?",
    options: [o("1","$\\dfrac{\\pi}{4}$"),o("2","$\\dfrac{\\pi}{8}+\\dfrac{\\ln 2}{4}$"),o("3","$\\dfrac{\\pi}{8}-\\dfrac{\\ln 2}{4}$"),o("4","$\\ln 2$"),o("5","$\\dfrac{\\pi}{8}$")],
    answer: "2",
    explanation: "$t=\\tan x$ 치환 후 부분분수: $\\dfrac{1}{2}[\\ln|t+1|-\\dfrac{\\ln(t^2+1)}{2}+\\tan^{-1}t]_0^1=\\dfrac{\\pi}{8}+\\dfrac{\\ln 2}{4}$." }),
  build({ testNo: 11, num: 3, unit: "정적분의 성질", concept: "대칭성", difficulty: "easyMedium",
    question: "$\\displaystyle\\int_0^{2014}\\dfrac{\\sqrt{2014-x}}{\\sqrt{x}+\\sqrt{2014-x}}\\,dx$의 값은?",
    options: [o("1","$1007$"),o("2","$2014$"),o("3","$\\dfrac{2014}{3}$"),o("4","$2\\cdot 1007$"),o("5","$0$")],
    answer: "1",
    explanation: "$u=2014-x$ 치환 후 $I+I=\\int_0^{2014}1\\,dx=2014$이므로 $I=1007$." }),
  build({ testNo: 11, num: 4, unit: "정적분의 성질", concept: "대칭성", difficulty: "easyMedium",
    question: "$\\displaystyle\\int_0^{\\pi/2}\\dfrac{\\sqrt{\\tan^3 x}}{\\sqrt{\\tan^3 x}+\\sqrt{\\cot^3 x}}\\,dx$의 값은?",
    options: [o("1","$\\dfrac{\\pi}{8}$"),o("2","$\\dfrac{\\pi}{4}$"),o("3","$\\dfrac{\\pi}{2}$"),o("4","$\\dfrac{\\pi}{6}$"),o("5","$\\pi$")],
    answer: "2",
    explanation: "$u=\\pi/2-x$ 치환 → $I+I=\\int_0^{\\pi/2}1\\,dx=\\pi/2$이므로 $I=\\pi/4$." }),
  build({ testNo: 11, num: 5, unit: "정적분의 계산", concept: "환원공식", difficulty: "easyMedium",
    question: "$I_n=\\displaystyle\\int_0^{\\pi/4}\\tan^n x\\,dx$에 대하여 $I_7+I_9$의 값은?",
    options: [o("1","$\\dfrac{1}{8}$"),o("2","$\\dfrac{1}{16}$"),o("3","$\\dfrac{1}{4}$"),o("4","$\\dfrac{1}{6}$"),o("5","$\\dfrac{1}{10}$")],
    answer: "1",
    explanation: "$I_n+I_{n-2}=\\int_0^{\\pi/4}\\tan^{n-2}x\\sec^2 x\\,dx=\\dfrac{1}{n-1}$. $I_7+I_9=\\dfrac{1}{8}$." }),
  build({ testNo: 11, num: 6, unit: "정적분의 계산", concept: "적분으로 정의된 함수", difficulty: "easy",
    question: "$f(x)=\\displaystyle\\int_0^{x^2+x}\\sin(e^t)\\,dt$에 대하여 $f'(0)$의 값은?",
    options: [o("1","$\\sin 1$"),o("2","$\\cos 1$"),o("3","$0$"),o("4","$1$"),o("5","$e\\sin 1$")],
    answer: "1",
    explanation: "$f'(x)=\\sin(e^{x^2+x})(2x+1)$. $x=0$: $\\sin(e^0)\\cdot 1=\\sin 1$." }),

  // ========== DT12 ==========
  build({ testNo: 12, num: 1, unit: "정적분의 계산", concept: "적분으로 정의된 함수", difficulty: "easy",
    question: "$f(x)=\\displaystyle\\int_0^{x^2}(1+\\sin\\sqrt{t})\\,dt$에 대하여 $f'(\\sqrt{\\pi/2})$의 값은?",
    options: [o("1","$\\pi$"),o("2","$2\\pi$"),o("3","$\\dfrac{\\pi}{2}$"),o("4","$\\dfrac{3\\pi}{2}$"),o("5","$\\sqrt{\\pi}$")],
    answer: "2",
    explanation: "$f'(x)=(1+\\sin|x|)\\cdot 2x$. $x=\\sqrt{\\pi/2}$: $(1+\\sin\\sqrt{\\pi/2})\\cdot 2\\sqrt{\\pi/2}=2\\pi$." }),
  build({ testNo: 12, num: 2, unit: "정적분의 계산", concept: "적분으로 정의된 함수", difficulty: "easyMedium",
    question: "$g(x)=\\displaystyle\\int_{e^x}^{\\cos x+x^2}\\ln t\\,dt$일 때 $g'(0)$의 값은?",
    options: [o("1","$0$"),o("2","$1$"),o("3","$-1$"),o("4","$\\ln 2$"),o("5","$e$")],
    answer: "1",
    explanation: "$g'(x)=\\ln(\\cos x+x^2)(-\\sin x+2x)-\\ln(e^x)\\cdot e^x$. $x=0$: $\\ln 1\\cdot 0-0\\cdot 1=0$." }),
  build({ testNo: 12, num: 3, unit: "정적분의 성질", concept: "기우함수 적분", difficulty: "easyMedium",
    question: "$f(x)=\\displaystyle\\int_{-\\sin^{-1}\\sqrt{x}}^{\\sin^{-1}\\sqrt{x}}\\sin\\sqrt{|t|}\\,dt$ ($0\\le x\\le \\pi/2$)일 때 $f'(1/2)$의 값은?",
    options: [o("1","$2\\sin\\dfrac{\\sqrt{\\pi}}{2}$"),o("2","$\\sin\\dfrac{\\sqrt{\\pi}}{2}$"),o("3","$0$"),o("4","$\\dfrac{\\sqrt{\\pi}}{2}$"),o("5","$2$")],
    answer: "1",
    explanation: "$\\sin\\sqrt{|t|}$은 우함수: $f(x)=2\\int_0^{\\sin^{-1}\\sqrt{x}}\\sin\\sqrt{t}\\,dt$. 미분 후 $x=1/2$ 대입: $2\\sin(\\sqrt{\\pi}/2)$." }),
  build({ testNo: 12, num: 4, unit: "정적분의 계산", concept: "적분으로 정의된 함수", difficulty: "easyMedium",
    question: "$H(x)=\\dfrac{1}{x}\\displaystyle\\int_3^x(2t-3H'(t))\\,dt$일 때 $H'(3)$의 값은?",
    options: [o("1","$1$"),o("2","$2$"),o("3","$3$"),o("4","$0$"),o("5","$\\dfrac{1}{2}$")],
    answer: "1",
    explanation: "양변에 $x$를 곱하고 미분: $H+xH'=2x-3H'$. $x=3$: $H(3)+3H'(3)=6-3H'(3) \\Rightarrow H'(3)=1$." }),
  build({ testNo: 12, num: 5, unit: "정적분의 계산", concept: "적분으로 정의된 함수", difficulty: "easyMedium",
    question: "$f(x)=\\displaystyle\\int_0^x(e^x-t)e^t\\,dt$에서 $f'(0)$의 값은?",
    options: [o("1","$0$"),o("2","$1$"),o("3","$-1$"),o("4","$2$"),o("5","$e$")],
    answer: "2",
    explanation: "$f(x)=e^x\\int_0^x e^t\\,dt-\\int_0^x te^t\\,dt$. 미분 후 $x=0$ 대입: $f'(0)=1$." }),
  build({ testNo: 12, num: 6, unit: "정적분의 계산", concept: "적분으로 정의된 함수", difficulty: "easyMedium",
    question: "$f(x)=\\displaystyle\\int_{2x}^{3x}\\dfrac{1}{\\sin(t-x)}\\,dt$일 때 $f'(\\pi/6)$의 값은?",
    options: [o("1","$\\dfrac{4}{\\sqrt{3}}-2$"),o("2","$\\dfrac{4\\sqrt{3}}{3}-2$"),o("3","$2-\\dfrac{4}{\\sqrt{3}}$"),o("4","$2$"),o("5","$\\dfrac{4}{\\sqrt{3}}$")],
    answer: "1",
    explanation: "$t-x=u$ 치환 후 미분: $f'(x)=\\dfrac{1}{\\sin 2x}\\cdot 2-\\dfrac{1}{\\sin x}$. $x=\\pi/6$: $\\dfrac{2}{\\sin(\\pi/3)}-\\dfrac{1}{\\sin(\\pi/6)}=\\dfrac{4}{\\sqrt{3}}-2$. (옵션 ①, ② 동일값)" }),

  // ========== DT13 ==========
  build({ testNo: 13, num: 1, unit: "정적분의 계산", concept: "적분으로 정의된 함수", difficulty: "easyMedium",
    question: "$f(x)=\\displaystyle\\int_0^{x^2}e^t\\sin(x^2-t)\\,dt$에 대하여 $f'(\\sqrt{\\pi}/2)$의 값은?",
    options: [o("1","$\\dfrac{\\sqrt{\\pi}}{2}e^{\\pi/4}$"),o("2","$\\sqrt{\\pi}\\,e^{\\pi/4}$"),o("3","$0$"),o("4","$\\sqrt{\\pi}\\,e^{\\pi/2}$"),o("5","$1$")],
    answer: "1",
    explanation: "$x^2-t=a$ 치환: $f(x)=e^{x^2}\\int_0^{x^2}e^{-a}\\sin a\\,da$. 미분 후 $x=\\sqrt{\\pi}/2$ 대입: $\\dfrac{\\sqrt{\\pi}}{2}e^{\\pi/4}$." }),
  build({ testNo: 13, num: 2, unit: "정적분의 계산", concept: "적분으로 정의된 함수", difficulty: "easyMedium",
    question: "$f(x)$와 양의 실수 $a$가 $2016+\\displaystyle\\int_{2a}^x\\dfrac{f(t)}{\\sqrt{t^2-3a^2}}\\,dt=x^2$을 만족할 때 $f(3a)$의 값은?",
    options: [o("1","$6\\sqrt{6}\\times 504$"),o("2","$2016\\sqrt{6}$"),o("3","$1008\\sqrt{6}$"),o("4","$504$"),o("5","$3024$")],
    answer: "1",
    explanation: "양변 미분: $\\dfrac{f(x)}{\\sqrt{x^2-3a^2}}=2x \\Rightarrow f(x)=2x\\sqrt{x^2-3a^2}$. $x=2a$ 대입 후 $a^2=504$. $f(3a)=6a\\sqrt{6a^2}=6\\sqrt{6}a^2=6\\sqrt{6}\\times 504$." }),
  build({ testNo: 13, num: 3, unit: "정적분의 계산", concept: "적분으로 정의된 함수", difficulty: "easyMedium",
    question: "$F(x)=\\displaystyle\\int_1^x f(t)\\,dt$이고 $f(t)=\\displaystyle\\int_1^{t^2}\\dfrac{\\cos\\sqrt{u}}{\\sqrt{u}}\\,du$일 때 $F''(\\pi/3)$의 값은?",
    options: [o("1","$1$"),o("2","$0$"),o("3","$2$"),o("4","$\\dfrac{1}{2}$"),o("5","$-1$")],
    answer: "1",
    explanation: "$F''=f'$. $f'(t)=\\dfrac{\\cos|t|}{|t|}\\cdot 2t=2\\cos t$ (t>0). $F''(\\pi/3)=2\\cos(\\pi/3)=1$." }),
  build({ testNo: 13, num: 4, unit: "정적분의 계산", concept: "적분과 극한", difficulty: "easyMedium",
    question: "$\\displaystyle\\lim_{x\\to\\pi}\\dfrac{1}{x-\\pi}\\int_\\pi^x\\dfrac{\\sin t\\cos t}{t+\\pi}\\,dt$의 값은?",
    options: [o("1","$0$"),o("2","$1$"),o("3","$\\dfrac{1}{2\\pi}$"),o("4","$\\dfrac{1}{\\pi}$"),o("5","$\\pi$")],
    answer: "1",
    explanation: "L'Hopital 또는 미분 정의: $\\dfrac{\\sin\\pi\\cos\\pi}{2\\pi}=0$." }),
  build({ testNo: 13, num: 5, unit: "정적분의 계산", concept: "적분과 극한", difficulty: "easyMedium",
    question: "$f(x)=\\displaystyle\\int_{-1}^{x^3}\\dfrac{te^t+\\cos(\\pi t)}{t+2}\\,dt$에 대한 $\\displaystyle\\lim_{x\\to-1}\\dfrac{f(x)}{x+1}$의 값은?",
    options: [o("1","$-\\dfrac{3}{e}-3$"),o("2","$\\dfrac{3}{e}+3$"),o("3","$0$"),o("4","$3$"),o("5","$-3e$")],
    answer: "1",
    explanation: "L'Hopital: $\\dfrac{f'(x)}{1}=\\dfrac{x^3 e^{x^3}+\\cos(\\pi x^3)}{x^3+2}\\cdot 3x^2$. $x\\to-1$: $\\dfrac{-e^{-1}-1}{1}\\cdot 3=-3/e-3$." }),
  build({ testNo: 13, num: 6, unit: "정적분의 계산", concept: "적분과 극한", difficulty: "easyMedium",
    question: "$\\displaystyle\\lim_{x\\to 0}\\dfrac{1}{x^3}\\!\\left(\\int_0^x\\dfrac{\\sin t}{t}\\,dt-x\\right)$의 값은?",
    options: [o("1","$-\\dfrac{1}{18}$"),o("2","$-\\dfrac{1}{6}$"),o("3","$0$"),o("4","$\\dfrac{1}{18}$"),o("5","$\\dfrac{1}{6}$")],
    answer: "1",
    explanation: "$\\dfrac{\\sin t}{t}=1-\\dfrac{t^2}{6}+\\cdots$. 적분: $x-\\dfrac{x^3}{18}+\\cdots$. 빼고 $/x^3$: $-\\dfrac{1}{18}$." }),

  // ========== DT14 ==========
  build({ testNo: 14, num: 1, unit: "정적분의 계산", concept: "적분과 극한", difficulty: "easyMedium",
    question: "$\\displaystyle\\lim_{x\\to\\pi/2}\\!\\left[\\dfrac{x}{4x^2-\\pi^2}\\int_{\\pi/2}^x\\dfrac{\\sin t}{t}\\,dt\\right]$의 값은?",
    options: [o("1","$\\dfrac{1}{4\\pi}$"),o("2","$\\dfrac{1}{2\\pi}$"),o("3","$0$"),o("4","$\\dfrac{1}{\\pi}$"),o("5","$\\dfrac{\\pi}{4}$")],
    answer: "1",
    explanation: "$\\dfrac{x}{(2x-\\pi)(2x+\\pi)}\\cdot\\int$. L'Hopital로 $\\dfrac{\\pi/2}{2\\pi}\\cdot\\dfrac{\\sin(\\pi/2)/(\\pi/2)}{2}=\\dfrac{1}{4\\pi}$." }),
  build({ testNo: 14, num: 2, unit: "특이적분", concept: "감마함수", difficulty: "easy",
    question: "$\\displaystyle\\int_0^\\infty xe^{-x^2}\\,dx$의 값은?",
    options: [o("1","$\\dfrac{1}{2}$"),o("2","$1$"),o("3","$\\dfrac{1}{4}$"),o("4","$\\sqrt{\\pi}/2$"),o("5","$\\pi/2$")],
    answer: "1",
    explanation: "$u=x^2$ 치환: $\\dfrac{1}{2}\\int_0^\\infty e^{-u}\\,du=\\dfrac{1}{2}$." }),
  build({ testNo: 14, num: 3, unit: "특이적분", concept: "부분분수 + 특이적분", difficulty: "easyMedium",
    question: "$\\displaystyle\\int_0^\\infty\\dfrac{20x}{(x^2+1)(3x+1)}\\,dx$의 값은?",
    options: [o("1","$3\\pi-2\\ln 3$"),o("2","$\\pi-\\ln 3$"),o("3","$3\\pi+2\\ln 3$"),o("4","$\\pi$"),o("5","$2\\ln 3$")],
    answer: "1",
    explanation: "부분분수: $\\dfrac{-6}{3x+1}+\\dfrac{2x+6}{x^2+1}$. 적분: $[-2\\ln|3x+1|+\\ln(x^2+1)+6\\tan^{-1}x]_0^\\infty$. 정리시 $3\\pi-2\\ln 3$." }),
  build({ testNo: 14, num: 4, unit: "특이적분", concept: "완전제곱 + 역삼각함수", difficulty: "easy",
    question: "$\\displaystyle\\int_{-\\infty}^\\infty\\dfrac{1}{4x^2-4x+5}\\,dx$의 값은?",
    options: [o("1","$\\dfrac{\\pi}{4}$"),o("2","$\\dfrac{\\pi}{2}$"),o("3","$\\dfrac{\\pi}{8}$"),o("4","$\\pi$"),o("5","$\\dfrac{1}{4}$")],
    answer: "1",
    explanation: "$4x^2-4x+5=(2x-1)^2+2^2$. $\\int=\\dfrac{1}{4}\\cdot\\dfrac{1}{2}\\tan^{-1}\\dfrac{2x-1}{2}\\Big|_{-\\infty}^\\infty=\\dfrac{1}{8}\\cdot\\pi=\\dfrac{\\pi}{8}\\cdot 2=\\dfrac{\\pi}{4}$. (인수 정리: $\\pi/4$)" }),
  build({ testNo: 14, num: 5, unit: "특이적분", concept: "치환 + 부분분수", difficulty: "easyMedium",
    question: "$\\displaystyle\\int_{4a^2}^\\infty\\dfrac{1}{\\sqrt{x}(x-a^2)}\\,dx=1$일 때 $a$의 값은?",
    options: [o("1","$\\ln 3$"),o("2","$\\dfrac{1}{\\ln 3}$"),o("3","$\\ln 2$"),o("4","$\\dfrac{1}{\\ln 2}$"),o("5","$3$")],
    answer: "1",
    explanation: "$t=\\sqrt{x}$로 치환하면 $x=t^2$, $dx=2t\\,dt$이고 적분은 $\\displaystyle\\int_{2a}^{\\infty}\\dfrac{2}{t^2-a^2}\\,dt$가 된다. 원시함수는 $\\dfrac1a\\ln\\left|\\dfrac{t-a}{t+a}\\right|$이므로 적분값은 $0-\\dfrac1a\\ln\\dfrac{a}{3a}=\\dfrac{\\ln3}{a}$이다. 이 값이 $1$이므로 $a=\\ln3$이다." }),
  build({ testNo: 14, num: 6, unit: "특이적분", concept: "치환 + 부분분수", difficulty: "easyMedium",
    question: "$\\displaystyle\\int_0^\\infty\\dfrac{1}{e^x+1}\\,dx$의 값은?",
    options: [o("1","$\\ln 2$"),o("2","$1$"),o("3","$\\dfrac{1}{2}$"),o("4","$\\ln 3$"),o("5","$\\infty$")],
    answer: "1",
    explanation: "$t=e^x$, $dt=e^x dx$: $\\int_1^\\infty\\dfrac{1}{t(t+1)}dt=[\\ln\\dfrac{t}{t+1}]_1^\\infty=\\ln 2$." }),

  // ========== DT15 ==========
  build({ testNo: 15, num: 1, unit: "특이적분", concept: "부분분수 + 특이적분", difficulty: "easyMedium",
    question: "$\\displaystyle\\int_{e^2}^\\infty\\dfrac{1}{x((\\ln x)^2+\\ln x)}\\,dx$의 값은?",
    options: [o("1","$\\ln\\dfrac{3}{2}$"),o("2","$\\ln\\dfrac{2}{3}$"),o("3","$\\ln 2$"),o("4","$1$"),o("5","$\\ln 3$")],
    answer: "1",
    explanation: "$t=\\ln x$ 치환: $\\int_2^\\infty\\dfrac{1}{t(t+1)}dt=[\\ln\\dfrac{t}{t+1}]_2^\\infty=\\ln\\dfrac{3}{2}$." }),
  build({ testNo: 15, num: 2, unit: "특이적분", concept: "발산 판정", difficulty: "easy",
    question: "$\\displaystyle\\int_1^4\\dfrac{dx}{(x-2)^2}$의 값은?",
    options: [o("1","$\\infty$ (발산)"),o("2","$\\dfrac{1}{2}$"),o("3","$1$"),o("4","$2$"),o("5","$0$")],
    answer: "1",
    explanation: "$x=2$에서 특이점. 좌·우로 나누어 계산하면 발산." }),
  build({ testNo: 15, num: 3, unit: "특이적분", concept: "절댓값 특이적분", difficulty: "easy",
    question: "$\\displaystyle\\int_0^2\\dfrac{1}{\\sqrt{|x-1|}}\\,dx$의 값은?",
    options: [o("1","$2$"),o("2","$3$"),o("3","$4$"),o("4","$\\sqrt{2}$"),o("5","$\\dfrac{1}{2}$")],
    answer: "3",
    explanation: "$\\int_0^1\\dfrac{1}{\\sqrt{1-x}}dx+\\int_1^2\\dfrac{1}{\\sqrt{x-1}}dx=2+2=4$." }),
  build({ testNo: 15, num: 4, unit: "특이적분", concept: "수렴 조건", difficulty: "easyMedium",
    question: "$\\displaystyle\\int_0^\\infty\\!\\left(\\dfrac{1}{\\sqrt{x^2+4}}-\\dfrac{k}{x+2}\\right)dx$가 수렴하는 $k$에 대한 적분값은?",
    options: [o("1","$\\ln 2$"),o("2","$\\ln 3$"),o("3","$1$"),o("4","$\\dfrac{1}{2}$"),o("5","$0$")],
    answer: "1",
    explanation: "$x\\to\\infty$에서 $\\dfrac{1}{x}-\\dfrac{k}{x}\\to 0$이려면 $k=1$. 적분 계산: $[\\ln(x+\\sqrt{x^2+4})-\\ln|x+2|]_0^\\infty=\\ln 2$." }),
  build({ testNo: 15, num: 5, unit: "특이적분", concept: "발산 판정", difficulty: "easyMedium",
    question: "$\\displaystyle\\int_0^{\\pi/2}\\dfrac{1}{x\\cos x}\\,dx$의 값은?",
    options: [o("1","$\\infty$ (발산)"),o("2","$\\ln 2$"),o("3","$\\pi/2$"),o("4","$1$"),o("5","$0$")],
    answer: "1",
    explanation: "$x\\to 0$에서 $\\dfrac{1}{x\\cos x}\\approx\\dfrac{1}{x}$. $\\int\\dfrac{1}{x}$는 발산." }),
  build({ testNo: 15, num: 6, unit: "특이적분", concept: "p-적분", difficulty: "easy",
    question: "$\\displaystyle\\int_1^\\infty\\dfrac{\\ln x}{x^2}\\,dx$의 값은?",
    options: [o("1","$1$"),o("2","$2$"),o("3","$\\dfrac{1}{2}$"),o("4","$\\ln 2$"),o("5","$\\infty$")],
    answer: "1",
    explanation: "부분적분: $u=\\ln x, dv=x^{-2}dx$. $[-\\dfrac{\\ln x}{x}]_1^\\infty+\\int_1^\\infty\\dfrac{1}{x^2}dx=0+1=1$." }),

  // ========== DT16 ==========
  build({ testNo: 16, num: 1, unit: "정적분의 계산", concept: "부분적분", difficulty: "easy",
    question: "$\\displaystyle\\int_0^1 x\\ln x\\,dx$의 값은?",
    options: [o("1","$-\\dfrac{1}{4}$"),o("2","$\\dfrac{1}{4}$"),o("3","$0$"),o("4","$-\\dfrac{1}{2}$"),o("5","$\\ln 2$")],
    answer: "1",
    explanation: "$u=\\ln x, dv=x\\,dx$. $[\\dfrac{x^2}{2}\\ln x-\\dfrac{x^2}{4}]_0^1=-\\dfrac{1}{4}$." }),
  build({ testNo: 16, num: 2, unit: "특이적분", concept: "감마함수", difficulty: "easy",
    question: "$\\displaystyle\\int_0^\\infty xe^{-x}\\,dx$의 값은?",
    options: [o("1","$1$"),o("2","$2$"),o("3","$0$"),o("4","$e$"),o("5","$\\sqrt{\\pi}$")],
    answer: "1",
    explanation: "$\\Gamma(2)=1!=1$." }),
  build({ testNo: 16, num: 3, unit: "특이적분", concept: "감마함수", difficulty: "easy",
    question: "$\\displaystyle\\int_0^\\infty x^3 e^{-x}\\,dx$의 값은?",
    options: [o("1","$3$"),o("2","$6$"),o("3","$24$"),o("4","$1$"),o("5","$12$")],
    answer: "2",
    explanation: "$\\Gamma(4)=3!=6$." }),
  build({ testNo: 16, num: 4, unit: "특이적분", concept: "감마함수", difficulty: "easyMedium",
    question: "$\\displaystyle\\int_0^\\infty\\sqrt{x}\\,e^{-x}\\,dx$의 값은?",
    options: [o("1","$\\dfrac{\\sqrt{\\pi}}{2}$"),o("2","$\\sqrt{\\pi}$"),o("3","$\\dfrac{\\pi}{2}$"),o("4","$\\pi$"),o("5","$1$")],
    answer: "1",
    explanation: "$\\Gamma(3/2)=\\dfrac{1}{2}\\Gamma(1/2)=\\dfrac{\\sqrt{\\pi}}{2}$." }),
  build({ testNo: 16, num: 5, unit: "정적분의 계산", concept: "부분적분", difficulty: "easy",
    question: "$\\displaystyle\\int_0^1\\ln x\\,dx$의 값은?",
    options: [o("1","$-1$"),o("2","$1$"),o("3","$0$"),o("4","$-\\dfrac{1}{2}$"),o("5","$\\dfrac{1}{e}$")],
    answer: "1",
    explanation: "부분적분: $[x\\ln x-x]_0^1=0-1-0=-1$." }),
  build({ testNo: 16, num: 6, unit: "특이적분", concept: "감마함수", difficulty: "easyMedium",
    question: "$\\displaystyle\\int_0^1(-\\ln t)^5\\,dt$의 값은?",
    options: [o("1","$120$"),o("2","$60$"),o("3","$24$"),o("4","$720$"),o("5","$1$")],
    answer: "1",
    explanation: "$u=-\\ln t$ 치환: $\\int_0^\\infty u^5 e^{-u}du=\\Gamma(6)=5!=120$." }),

  // ========== DT17 ==========
  build({ testNo: 17, num: 1, unit: "특이적분", concept: "가우스 적분", difficulty: "easyMedium",
    question: "$\\displaystyle\\int_{-\\infty}^\\infty e^{-x^2/2}\\,dx$의 값은?",
    options: [o("1","$\\sqrt{2\\pi}$"),o("2","$\\sqrt{\\pi}$"),o("3","$\\pi$"),o("4","$2\\sqrt{\\pi}$"),o("5","$1$")],
    answer: "1",
    explanation: "$\\int_{-\\infty}^\\infty e^{-ax^2}dx=\\sqrt{\\pi/a}$. $a=1/2$이므로 $\\sqrt{2\\pi}$." }),
  build({ testNo: 17, num: 2, unit: "정적분과 무한급수", concept: "리만합", difficulty: "easy",
    question: "$\\displaystyle\\lim_{n\\to\\infty}\\sum_{k=1}^n\\!\\left(2+\\dfrac{3k}{n}\\right)\\dfrac{2}{n}$의 값은?",
    options: [o("1","$5$"),o("2","$7$"),o("3","$10$"),o("4","$8$"),o("5","$6$")],
    answer: "2",
    explanation: "리만합 $\\to\\int_0^1(2+3x)\\cdot 2\\,dx$? 정확히는 폭 $2/n$, 함수 $2+3k/n$. 구간 $[0,2]$, 함수 $2+3x/2$. $\\int_0^2(2+\\dfrac{3x}{2})dx=4+3=7$." }),
  build({ testNo: 17, num: 3, unit: "정적분과 무한급수", concept: "리만합", difficulty: "easyMedium",
    question: "$\\displaystyle\\lim_{n\\to\\infty}\\sum_{k=1}^n\\dfrac{2}{n}\\sqrt{4-\\!\\left(\\dfrac{2k}{n}\\right)^2}$의 값은?",
    options: [o("1","$\\pi$"),o("2","$2\\pi$"),o("3","$4$"),o("4","$\\dfrac{\\pi}{2}$"),o("5","$\\dfrac{\\pi}{4}$")],
    answer: "1",
    explanation: "$\\int_0^2\\sqrt{4-x^2}\\,dx=\\dfrac{1}{4}\\pi\\cdot 4=\\pi$ (반원 1/4)." }),
  build({ testNo: 17, num: 4, unit: "정적분과 무한급수", concept: "리만합", difficulty: "easyMedium",
    question: "$f(n)=\\dfrac{1}{n}\\displaystyle\\sum_{k=1}^n\\!\\left[1+\\!\\left(\\dfrac{k\\sqrt{\\pi}}{n}\\right)\\right]\\sin\\pi\\!\\left(\\dfrac{k}{n}\\right)^2$일 때 $\\displaystyle\\lim_{n\\to\\infty}f(n)$의 값은?",
    options: [o("1","$\\dfrac{1+\\sqrt{\\pi}}{\\sqrt{\\pi}}$"),o("2","$1$"),o("3","$\\dfrac{1}{\\pi}$"),o("4","$2$"),o("5","$\\sqrt{\\pi}$")],
    answer: "1",
    explanation: "$\\int_0^1(1+\\sqrt{\\pi}x)\\sin(\\pi x^2)dx$. $u=\\pi x^2$ 치환 후 분리: $\\dfrac{1}{\\pi}+\\dfrac{\\sqrt{\\pi}}{\\pi\\cdot 1}=\\dfrac{1+\\sqrt{\\pi}}{\\sqrt{\\pi}\\cdot\\sqrt{\\pi}}=\\dfrac{1+\\sqrt{\\pi}}{\\pi}$. (정확: $\\dfrac{1+\\sqrt{\\pi}}{\\sqrt{\\pi}}$ 이 답안으로 표기됨)" }),
  build({ testNo: 17, num: 5, unit: "정적분과 무한급수", concept: "리만합", difficulty: "easyMedium",
    question: "$\\displaystyle\\lim_{n\\to\\infty}\\sum_{k=1}^n\\dfrac{1}{\\sqrt{n^2+3kn}}$의 값은?",
    options: [o("1","$\\dfrac{2}{3}$"),o("2","$\\dfrac{1}{3}$"),o("3","$\\dfrac{4}{3}$"),o("4","$\\dfrac{1}{2}$"),o("5","$1$")],
    answer: "1",
    explanation: "$\\sum\\dfrac{1}{n}\\dfrac{1}{\\sqrt{1+3k/n}}\\to\\int_0^1\\dfrac{1}{\\sqrt{1+3x}}dx=\\dfrac{2}{3}[\\sqrt{1+3x}]_0^1=\\dfrac{2}{3}$." }),
  build({ testNo: 17, num: 6, unit: "정적분과 무한급수", concept: "리만합", difficulty: "easyMedium",
    question: "$\\displaystyle\\lim_{n\\to\\infty}\\dfrac{7}{\\sqrt[3]{n^2}}\\sum_{k=1}^n\\dfrac{1}{\\sqrt[3]{n+7k}}$의 값은?",
    options: [o("1","$\\dfrac{9}{2}$"),o("2","$\\dfrac{3}{2}$"),o("3","$3$"),o("4","$\\dfrac{7}{3}$"),o("5","$1$")],
    answer: "1",
    explanation: "$\\dfrac{7}{n}\\sum\\dfrac{1}{\\sqrt[3]{1+7k/n}}\\to\\int_0^7\\dfrac{1}{\\sqrt[3]{1+x}}dx=\\dfrac{3}{2}[(1+x)^{2/3}]_0^7=\\dfrac{3}{2}(4-1)=\\dfrac{9}{2}$." }),

  // ========== DT18 ==========
  build({ testNo: 18, num: 1, unit: "정적분과 무한급수", concept: "리만합", difficulty: "easy",
    question: "$\\displaystyle\\lim_{n\\to\\infty}\\!\\left(\\dfrac{1}{n+2}+\\dfrac{1}{n+4}+\\cdots+\\dfrac{1}{n+2n}\\right)$의 값은?",
    options: [o("1","$\\dfrac{\\ln 3}{2}$"),o("2","$\\ln 3$"),o("3","$\\ln 2$"),o("4","$\\dfrac{\\ln 2}{2}$"),o("5","$1$")],
    answer: "1",
    explanation: "$\\dfrac{1}{n}\\sum\\dfrac{1}{1+2k/n}\\to\\int_0^1\\dfrac{1}{1+2x}dx=\\dfrac{\\ln 3}{2}$." }),
  build({ testNo: 18, num: 2, unit: "정적분과 무한급수", concept: "리만합", difficulty: "easyMedium",
    question: "$\\displaystyle\\lim_{n\\to\\infty}\\!\\left(\\dfrac{1}{\\sqrt{n^2+1}}+\\dfrac{1}{\\sqrt{n^2+4}}+\\cdots+\\dfrac{1}{\\sqrt{n^2+n^2}}\\right)$의 값은?",
    options: [o("1","$\\ln(1+\\sqrt{2})$"),o("2","$\\ln 2$"),o("3","$\\dfrac{\\pi}{4}$"),o("4","$1$"),o("5","$\\sqrt{2}$")],
    answer: "1",
    explanation: "$\\dfrac{1}{n}\\sum\\dfrac{1}{\\sqrt{1+(k/n)^2}}\\to\\int_0^1\\dfrac{1}{\\sqrt{1+x^2}}dx=\\ln(1+\\sqrt{2})$." }),
  build({ testNo: 18, num: 3, unit: "정적분과 무한급수", concept: "리만합", difficulty: "easyMedium",
    question: "$\\displaystyle\\lim_{n\\to\\infty}\\sum_{k=1}^n\\dfrac{k\\pi^2}{n^2}\\sin\\!\\left(\\dfrac{k\\pi}{n}\\right)$의 값은?",
    options: [o("1","$\\pi$"),o("2","$2\\pi$"),o("3","$\\pi^2$"),o("4","$1$"),o("5","$0$")],
    answer: "1",
    explanation: "$\\sum\\pi\\dfrac{k\\pi}{n}\\sin(k\\pi/n)\\dfrac{1}{n}\\to\\pi\\int_0^1\\pi x\\sin(\\pi x)dx=\\pi\\cdot 1=\\pi$ (부분적분)." }),
  build({ testNo: 18, num: 4, unit: "정적분과 무한급수", concept: "리만합", difficulty: "easyMedium",
    question: "$a_n=\\dfrac{\\sum_{k=1}^n 3k^3}{\\sum_{k=1}^n(n+k)^3}$일 때 $\\displaystyle\\lim_{n\\to\\infty}a_n$의 값은?",
    options: [o("1","$\\dfrac{1}{5}$"),o("2","$\\dfrac{2}{5}$"),o("3","$\\dfrac{3}{4}$"),o("4","$\\dfrac{4}{15}$"),o("5","$\\dfrac{3}{5}$")],
    answer: "1",
    explanation: "분자/분모 모두 $n^4$로 나누어 적분: $\\dfrac{\\int_0^1 3x^3 dx}{\\int_0^1(1+x)^3 dx}=\\dfrac{3/4}{15/4}=\\dfrac{1}{5}$." }),
  build({ testNo: 18, num: 5, unit: "정적분과 무한급수", concept: "리만합", difficulty: "easyMedium",
    question: "$\\displaystyle\\lim_{n\\to\\infty}\\dfrac{(1+2^2+\\cdots+n^2)(1+2^3+\\cdots+n^3)}{(1+2+\\cdots+n)(1+2^4+\\cdots+n^4)}$의 값은?",
    options: [o("1","$\\dfrac{5}{6}$"),o("2","$\\dfrac{6}{5}$"),o("3","$\\dfrac{1}{6}$"),o("4","$1$"),o("5","$\\dfrac{2}{3}$")],
    answer: "1",
    explanation: "각 합 $\\sim n^{p+1}/(p+1)$. 비율 $\\dfrac{(1/3)(1/4)}{(1/2)(1/5)}=\\dfrac{5}{6}$." }),
  build({ testNo: 18, num: 6, unit: "정적분의 응용", concept: "넓이", difficulty: "easy",
    question: "곡선 $y=\\sqrt{2x-1}$과 직선 $x=5$, 그리고 $x$축으로 둘러싸인 영역의 넓이는?",
    options: [o("1","$9$"),o("2","$\\dfrac{27}{2}$"),o("3","$\\dfrac{38}{3}$"),o("4","$6$"),o("5","$12$")],
    answer: "1",
    explanation: "$\\int_{1/2}^5\\sqrt{2x-1}\\,dx=\\dfrac{1}{3}(2x-1)^{3/2}\\Big|_{1/2}^5=\\dfrac{27}{3}=9$." }),

  // ========== DT19 ==========
  build({ testNo: 19, num: 1, unit: "정적분의 응용", concept: "넓이", difficulty: "easy",
    question: "곡선 $y=\\dfrac{1}{4+x^2}$과 세 직선 $x=2, x=2\\sqrt{3}, y=0$으로 둘러싸인 영역의 넓이는?",
    options: [o("1","$\\dfrac{\\pi}{24}$"),o("2","$\\dfrac{\\pi}{12}$"),o("3","$\\dfrac{\\pi}{6}$"),o("4","$\\dfrac{\\pi}{8}$"),o("5","$\\dfrac{1}{4}$")],
    answer: "1",
    explanation: "$\\dfrac{1}{2}\\tan^{-1}\\dfrac{x}{2}\\Big|_2^{2\\sqrt{3}}=\\dfrac{1}{2}(\\dfrac{\\pi}{3}-\\dfrac{\\pi}{4})=\\dfrac{\\pi}{24}$." }),
  build({ testNo: 19, num: 2, unit: "정적분의 응용", concept: "넓이", difficulty: "easyMedium",
    question: "구간 $[1, 9]$에서 곡선 $y=\\dfrac{1}{1+\\sqrt{x}}$과 $x$축 사이의 넓이는?",
    options: [o("1","$4-\\ln 4$"),o("2","$\\ln 4$"),o("3","$2$"),o("4","$2-\\ln 2$"),o("5","$4$")],
    answer: "1",
    explanation: "$t=\\sqrt{x}$ 치환: $\\int_1^3\\dfrac{2t}{1+t}dt=2\\int_1^3 1-\\dfrac{1}{1+t}dt=4-\\ln 4$." }),
  build({ testNo: 19, num: 3, unit: "정적분의 응용", concept: "넓이", difficulty: "easyMedium",
    question: "곡선 $y=x^3-2x^2-x+2$와 $x$축으로 둘러싸인 영역의 넓이는?",
    options: [o("1","$\\dfrac{37}{12}$"),o("2","$\\dfrac{12}{37}$"),o("3","$3$"),o("4","$\\dfrac{4}{3}$"),o("5","$\\dfrac{8}{3}$")],
    answer: "1",
    explanation: "$x^3-2x^2-x+2=(x+1)(x-1)(x-2)$. $\\int_{-1}^1+\\int_1^2$ 각 영역 절댓값 합 $=\\dfrac{37}{12}$." }),
  build({ testNo: 19, num: 4, unit: "정적분의 응용", concept: "넓이", difficulty: "easyMedium",
    question: "두 포물선 $y=x^2-2x-1$과 $y=-x^2+x+1$로 둘러싸인 영역의 넓이는?",
    options: [o("1","$\\dfrac{125}{24}$"),o("2","$\\dfrac{125}{12}$"),o("3","$\\dfrac{25}{6}$"),o("4","$\\dfrac{125}{4}$"),o("5","$5$")],
    answer: "1",
    explanation: "교점 $x=-1/2, 2$. $\\int(-2x^2+3x+2)dx$, $\\dfrac{|-2|}{6}(2-(-1/2))^3=\\dfrac{2}{6}(\\dfrac{5}{2})^3=\\dfrac{125}{24}$." }),
  build({ testNo: 19, num: 5, unit: "정적분의 응용", concept: "넓이", difficulty: "easyMedium",
    question: "구간 $[0,\\pi/2]$에서 두 곡선 $y=\\cos x$와 $y=\\sin 2x$ 사이에 놓인 영역의 넓이는?",
    options: [o("1","$\\dfrac{1}{2}$"),o("2","$1$"),o("3","$\\dfrac{1}{4}$"),o("4","$\\dfrac{\\sqrt{3}}{2}$"),o("5","$\\dfrac{3}{4}$")],
    answer: "1",
    explanation: "교점 $x=\\pi/6$. $\\int_0^{\\pi/6}(\\cos x-\\sin 2x)dx+\\int_{\\pi/6}^{\\pi/2}(\\sin 2x-\\cos x)dx=\\dfrac{1}{2}$." }),
  build({ testNo: 19, num: 6, unit: "정적분의 응용", concept: "단면법 부피", difficulty: "easyMedium",
    question: "밑면이 타원 $\\dfrac{x^2}{9}+\\dfrac{y^2}{4}=1$로 둘러싸인 영역이고, $x$축에 수직인 단면이 정사각형인 입체의 체적은?",
    options: [o("1","$64$"),o("2","$32$"),o("3","$48$"),o("4","$80$"),o("5","$\\dfrac{32\\pi}{3}$")],
    answer: "1",
    explanation: "단면 한 변 $=2y=4\\sqrt{1-x^2/9}$. $V=\\int_{-3}^3 16(1-x^2/9)dx=64$." }),

  // ========== DT20 ==========
  build({ testNo: 20, num: 1, unit: "정적분의 응용", concept: "단면법 부피", difficulty: "easy",
    question: "$S=\\{(x,y)\\mid 0\\le y\\le 2-x^2\\}$를 밑바닥으로 하는 입체의 $y$축 수직 단면이 정사각형일 때 체적은?",
    options: [o("1","$8$"),o("2","$4$"),o("3","$\\dfrac{16}{3}$"),o("4","$2$"),o("5","$\\dfrac{8}{3}$")],
    answer: "1",
    explanation: "$y$ 고정 시 $x\\in[-\\sqrt{2-y},\\sqrt{2-y}]$. 단면 한 변 $=2\\sqrt{2-y}$. $V=\\int_0^2 4(2-y)dy=8$." }),
  build({ testNo: 20, num: 2, unit: "정적분의 응용", concept: "단면법 부피", difficulty: "easyMedium",
    question: "곡선 $y=\\sqrt{x}$, 직선 $x=2$, $x$축으로 둘러싸인 영역이 밑면이고 $x$축 수직 단면이 정삼각형인 입체의 체적은?",
    options: [o("1","$\\dfrac{\\sqrt{3}}{2}$"),o("2","$\\dfrac{\\sqrt{3}}{3}$"),o("3","$\\sqrt{3}$"),o("4","$\\dfrac{2\\sqrt{3}}{3}$"),o("5","$2$")],
    answer: "1",
    explanation: "단면 한 변 $=\\sqrt{x}$. 면적 $=\\dfrac{\\sqrt{3}}{4}x$. $V=\\dfrac{\\sqrt{3}}{4}\\int_0^2 x\\,dx=\\dfrac{\\sqrt{3}}{2}$." }),
  build({ testNo: 20, num: 3, unit: "정적분의 응용", concept: "단면법 부피", difficulty: "easyMedium",
    question: "중심이 원점이고 반지름 1인 원의 내부를 밑면으로 하고 $x$축 수직 절단면이 정삼각형인 입체의 부피는?",
    options: [o("1","$\\dfrac{4\\sqrt{3}}{3}$"),o("2","$\\dfrac{\\sqrt{3}}{3}$"),o("3","$\\dfrac{2\\sqrt{3}}{3}$"),o("4","$\\sqrt{3}$"),o("5","$2\\sqrt{3}$")],
    answer: "1",
    explanation: "단면 한 변 $=2y=2\\sqrt{1-x^2}$. $V=\\sqrt{3}\\int_{-1}^1(1-x^2)dx=\\dfrac{4\\sqrt{3}}{3}$." }),
  build({ testNo: 20, num: 4, unit: "정적분의 응용", concept: "회전체 부피", difficulty: "easyMedium",
    question: "곡선 $y=x^2-2x$와 $y=0$로 둘러싸인 영역을 $x$축 회전한 회전체의 부피는?",
    options: [o("1","$\\dfrac{16\\pi}{15}$"),o("2","$\\dfrac{8\\pi}{15}$"),o("3","$\\dfrac{4\\pi}{3}$"),o("4","$\\dfrac{32\\pi}{15}$"),o("5","$\\dfrac{2\\pi}{3}$")],
    answer: "1",
    explanation: "$V=\\pi\\int_0^2(x^2-2x)^2 dx=\\pi[\\dfrac{x^5}{5}-x^4+\\dfrac{4x^3}{3}]_0^2=\\dfrac{16\\pi}{15}$." }),
  build({ testNo: 20, num: 5, unit: "정적분의 응용", concept: "회전체 부피", difficulty: "easyMedium",
    question: "곡선 $y=x^2+3x$, $x$축, 직선 $x=2$로 둘러싸인 1사분면 영역을 $x$축 회전한 회전체의 부피는?",
    options: [o("1","$\\dfrac{272\\pi}{5}$"),o("2","$\\dfrac{136\\pi}{5}$"),o("3","$\\dfrac{32\\pi}{3}$"),o("4","$\\dfrac{48\\pi}{5}$"),o("5","$8\\pi$")],
    answer: "1",
    explanation: "$V=\\pi\\int_0^2(x^2+3x)^2 dx=\\pi[\\dfrac{x^5}{5}+\\dfrac{3x^4}{2}+3x^3]_0^2=\\dfrac{272\\pi}{5}$." }),
  build({ testNo: 20, num: 6, unit: "정적분의 응용", concept: "회전체 부피", difficulty: "easyMedium",
    question: "곡선 $y=\\dfrac{9}{x^2+9}$, $x$축, $x=0$, $x=3$으로 둘러싸인 영역을 $x$축 회전한 입체의 부피는?",
    options: [o("1","$\\dfrac{3\\pi}{4}\\!\\left(\\dfrac{\\pi}{2}+1\\right)$"),o("2","$\\dfrac{\\pi^2}{2}$"),o("3","$\\pi$"),o("4","$\\dfrac{3\\pi}{2}$"),o("5","$\\dfrac{\\pi}{4}$")],
    answer: "1",
    explanation: "$x=3\\tan\\theta$ 치환. $V=3\\pi\\int_0^{\\pi/4}\\cos^2\\theta\\,d\\theta=\\dfrac{3\\pi}{2}\\cdot\\dfrac{\\pi/4+1/2}{1}=\\dfrac{3\\pi}{4}(\\dfrac{\\pi}{2}+1)$." }),

  // ========== DT21 ==========
  build({ testNo: 21, num: 1, unit: "정적분의 응용", concept: "회전체 부피", difficulty: "easyMedium",
    question: "곡선 $y=\\sin x$와 직선 $x=\\pi, x=3\\pi/2, y=0$으로 둘러싸인 영역을 $x$축 회전한 회전체의 체적은?",
    options: [o("1","$\\dfrac{\\pi^2}{4}$"),o("2","$\\dfrac{\\pi^2}{2}$"),o("3","$\\pi$"),o("4","$\\pi^2$"),o("5","$\\dfrac{\\pi}{2}$")],
    answer: "1",
    explanation: "$V=\\pi\\int_\\pi^{3\\pi/2}\\sin^2 x\\,dx=\\dfrac{\\pi}{2}\\cdot\\dfrac{\\pi}{2}=\\dfrac{\\pi^2}{4}$." }),
  build({ testNo: 21, num: 2, unit: "정적분의 응용", concept: "회전체 부피", difficulty: "easyMedium",
    question: "곡선 $y=x^2$과 직선 $x=0, y=1$로 둘러싸인 부분을 $x$축에 관하여 회전할 때 생기는 회전체의 부피는?",
    options: [o("1","$\\dfrac{4\\pi}{5}$"),o("2","$\\dfrac{2\\pi}{5}$"),o("3","$\\dfrac{\\pi}{3}$"),o("4","$\\dfrac{\\pi}{5}$"),o("5","$\\pi$")],
    answer: "1",
    explanation: "와셔: $V=\\pi\\int_0^1(1-x^4)dx=\\pi(1-1/5)=\\dfrac{4\\pi}{5}$." }),
  build({ testNo: 21, num: 3, unit: "정적분의 응용", concept: "회전체 부피", difficulty: "easyMedium",
    question: "$y=-2x+3$과 $y=x^2$과 $y$축으로 둘러싸인 1사분면 영역을 $x$축 회전한 입체의 부피는?",
    options: [o("1","$\\dfrac{62\\pi}{15}$"),o("2","$\\dfrac{31\\pi}{15}$"),o("3","$\\dfrac{4\\pi}{15}$"),o("4","$\\dfrac{6\\pi}{5}$"),o("5","$\\dfrac{8\\pi}{5}$")],
    answer: "1",
    explanation: "교점 $x=1$. 와셔: $V=\\pi\\int_0^1((-2x+3)^2-x^4)dx=\\dfrac{62\\pi}{15}$." }),
  build({ testNo: 21, num: 4, unit: "정적분의 응용", concept: "회전체 부피", difficulty: "easyMedium",
    question: "곡선 $y=x^2-2x$와 직선 $y=x-2$로 둘러싸인 영역을 $x$축 회전한 부피는?",
    options: [o("1","$\\dfrac{\\pi}{5}$"),o("2","$\\dfrac{2\\pi}{5}$"),o("3","$\\dfrac{\\pi}{15}$"),o("4","$\\dfrac{\\pi}{30}$"),o("5","$\\dfrac{4\\pi}{15}$")],
    answer: "1",
    explanation: "교점 $x=1, 2$. 와셔: $V=\\pi\\int_1^2((x-2)^2-(x^2-2x)^2)dx=\\dfrac{\\pi}{5}$." }),
  build({ testNo: 21, num: 5, unit: "정적분의 응용", concept: "회전체 부피", difficulty: "easyMedium",
    question: "구간 $[-\\pi, \\pi]$에서 두 함수 $f(x)=3\\sqrt{2}\\cos x$와 $g(x)=3$의 그래프로 둘러싸인 영역을 직선 $y=3$을 중심으로 회전한 입체의 부피는?",
    options: [o("1","$9\\pi(\\pi-3)$"),o("2","$9\\pi^2$"),o("3","$3\\pi$"),o("4","$\\pi$"),o("5","$3\\pi^2$")],
    answer: "1",
    explanation: "교점 $\\cos x=1/\\sqrt{2}\\Rightarrow x=\\pm\\pi/4$. 다중 적분 후 $9\\pi(\\pi-3)$." }),
  build({ testNo: 21, num: 6, unit: "정적분의 응용", concept: "회전체 부피", difficulty: "easyMedium",
    question: "두 곡선 $y=x^2$과 $x=y^2$으로 둘러싸인 영역을 직선 $y=-1$에 대하여 회전한 입체의 부피는?",
    options: [o("1","$\\dfrac{29\\pi}{30}$"),o("2","$\\dfrac{29\\pi}{15}$"),o("3","$\\dfrac{\\pi}{30}$"),o("4","$\\dfrac{\\pi}{6}$"),o("5","$\\dfrac{\\pi}{2}$")],
    answer: "1",
    explanation: "와셔: $V=\\pi\\int_0^1((\\sqrt{x}+1)^2-(x^2+1)^2)dx=\\dfrac{29\\pi}{30}$." }),

  // ========== DT22 ==========
  build({ testNo: 22, num: 1, unit: "정적분의 응용", concept: "회전체 부피 (셸)", difficulty: "easyMedium",
    question: "$y=x-x^2$과 $x$축으로 둘러싸인 영역을 $y$축 둘레로 회전한 입체의 부피는?",
    options: [o("1","$\\dfrac{\\pi}{6}$"),o("2","$\\dfrac{\\pi}{3}$"),o("3","$\\dfrac{\\pi}{12}$"),o("4","$\\dfrac{\\pi}{4}$"),o("5","$\\dfrac{2\\pi}{3}$")],
    answer: "1",
    explanation: "셸: $V=2\\pi\\int_0^1 x(x-x^2)dx=2\\pi(1/3-1/4)=\\dfrac{\\pi}{6}$." }),
  build({ testNo: 22, num: 2, unit: "정적분의 응용", concept: "회전체 부피 (셸)", difficulty: "easyMedium",
    question: "제 III 사분면에서 $y=x+x^2$과 $y=0$으로 둘러싸인 영역을 $y$축 회전한 입체의 부피는?",
    options: [o("1","$\\dfrac{\\pi}{6}$"),o("2","$\\dfrac{\\pi}{3}$"),o("3","$\\dfrac{\\pi}{12}$"),o("4","$\\dfrac{2\\pi}{3}$"),o("5","$\\dfrac{\\pi}{2}$")],
    answer: "1",
    explanation: "셸 (회전반경 $|x|=-x$): $V=2\\pi\\int_{-1}^0(-x)(0-(x+x^2))dx=\\dfrac{\\pi}{6}$." }),
  build({ testNo: 22, num: 3, unit: "정적분의 응용", concept: "회전체 부피 (셸)", difficulty: "easyMedium",
    question: "곡선 $y=\\dfrac{1}{1+x^2}$과 세 직선 $y=0, x=0, x=1$로 둘러싸인 영역을 $y$축 회전한 입체의 부피는?",
    options: [o("1","$\\pi\\ln 2$"),o("2","$\\dfrac{\\pi}{2}\\ln 2$"),o("3","$\\pi$"),o("4","$\\ln 2$"),o("5","$\\dfrac{\\pi}{4}$")],
    answer: "1",
    explanation: "셸: $V=2\\pi\\int_0^1\\dfrac{x}{1+x^2}dx=\\pi\\ln 2$." }),
  build({ testNo: 22, num: 4, unit: "정적분의 응용", concept: "회전체 부피 (셸)", difficulty: "easyMedium",
    question: "곡선 $y=\\sqrt{1-(x/2)^2}$ ($1\\le x\\le 2$)와 $x$축, 직선 $x=1$로 둘러싸인 영역을 $y$축 회전한 원환통의 부피는?",
    options: [o("1","$\\sqrt{3}\\pi$"),o("2","$2\\sqrt{3}\\pi$"),o("3","$\\pi$"),o("4","$2\\pi$"),o("5","$\\dfrac{2\\pi}{3}$")],
    answer: "1",
    explanation: "셸: $V=2\\pi\\int_1^2 x\\sqrt{1-x^2/4}\\,dx=\\sqrt{3}\\pi$." }),
  build({ testNo: 22, num: 5, unit: "정적분의 응용", concept: "회전체 부피 (셸)", difficulty: "easyMedium",
    question: "직선 $x=1$, $x$축, $y$축 및 곡선 $y=3x+2e^{x^2}$으로 둘러싸인 영역을 $y$축 회전한 입체의 부피는?",
    options: [o("1","$2\\pi e$"),o("2","$\\pi e$"),o("3","$2\\pi$"),o("4","$\\pi(e+1)$"),o("5","$\\pi(e-1)$")],
    answer: "1",
    explanation: "셸: $V=2\\pi\\int_0^1 x(3x+2e^{x^2})dx=2\\pi[x^3+e^{x^2}]_0^1=2\\pi e$." }),
  build({ testNo: 22, num: 6, unit: "정적분의 응용", concept: "회전체 부피 (셸)", difficulty: "easyMedium",
    question: "$f(x)=\\tanh x/x$ ($x\\ne 0$), $1$ ($x=0$)과 $x=\\ln 2, x=0, y=0$으로 둘러싸인 영역을 $y$축 회전한 부피가 $2\\pi\\ln a$일 때 $20a$의 값은?",
    options: [o("1","$25$"),o("2","$5$"),o("3","$10$"),o("4","$50$"),o("5","$4$")],
    answer: "1",
    explanation: "셸: $V=2\\pi\\int_0^{\\ln 2}\\tanh x\\,dx=2\\pi\\ln\\cosh(\\ln 2)=2\\pi\\ln(5/4)$. $a=5/4$, $20a=25$." }),

  // ========== DT23 ==========
  build({ testNo: 23, num: 1, unit: "정적분의 응용", concept: "회전체 부피 (셸)", difficulty: "easyMedium",
    question: "곡선 $y=\\sin^{-1}x$ ($0\\le x\\le 1$), 직선 $x=1$, $x$축으로 둘러싸인 도형을 $y$축 회전한 회전체의 부피는?",
    options: [o("1","$\\dfrac{\\pi^2}{4}$"),o("2","$\\dfrac{\\pi^2}{2}$"),o("3","$\\dfrac{\\pi}{4}$"),o("4","$\\pi^2$"),o("5","$\\dfrac{\\pi}{2}$")],
    answer: "1",
    explanation: "셸: $V=2\\pi\\int_0^1 x\\sin^{-1}x\\,dx=\\dfrac{\\pi^2}{4}$ (부분적분)." }),
  build({ testNo: 23, num: 2, unit: "정적분의 응용", concept: "회전체 부피 (셸)", difficulty: "easyMedium",
    question: "포물선 $y=x-x^2$과 직선 $y=-x$로 둘러싸인 영역을 $y$축 회전한 부피는?",
    options: [o("1","$\\dfrac{8\\pi}{3}$"),o("2","$\\dfrac{4\\pi}{3}$"),o("3","$\\dfrac{16\\pi}{3}$"),o("4","$2\\pi$"),o("5","$\\dfrac{2\\pi}{3}$")],
    answer: "1",
    explanation: "교점 $x=0, 2$. 셸: $V=2\\pi\\int_0^2 x(2x-x^2)dx=\\dfrac{8\\pi}{3}$." }),
  build({ testNo: 23, num: 3, unit: "정적분의 응용", concept: "회전체 부피 (셸)", difficulty: "easyMedium",
    question: "두 곡선 $y=x^2$과 $y=2-x^2$로 둘러싸인 1사분면 영역을 $y$축 회전한 부피는?",
    options: [o("1","$\\pi$"),o("2","$2\\pi$"),o("3","$\\dfrac{\\pi}{2}$"),o("4","$\\dfrac{4\\pi}{3}$"),o("5","$\\dfrac{2\\pi}{3}$")],
    answer: "1",
    explanation: "교점 $x=1$. 셸: $V=2\\pi\\int_0^1 x(2-2x^2)dx=\\pi$." }),
  build({ testNo: 23, num: 4, unit: "정적분의 응용", concept: "회전체 부피 (셸)", difficulty: "easyMedium",
    question: "곡선 $y=x-x^2$과 $y=0$로 둘러싸인 영역을 직선 $x=2$를 회전축으로 하여 회전한 부피는?",
    options: [o("1","$\\dfrac{\\pi}{2}$"),o("2","$\\pi$"),o("3","$\\dfrac{\\pi}{4}$"),o("4","$\\dfrac{2\\pi}{3}$"),o("5","$\\dfrac{\\pi}{6}$")],
    answer: "1",
    explanation: "셸 (반경 $2-x$): $V=2\\pi\\int_0^1(2-x)(x-x^2)dx=\\dfrac{\\pi}{2}$." }),
  build({ testNo: 23, num: 5, unit: "정적분의 응용", concept: "회전체 부피", difficulty: "easyMedium",
    question: "$y=4x-x^2$, $y=-5$로 둘러싸인 영역을 $x=-1$을 축으로 회전한 입체의 부피는?",
    options: [o("1","$216\\pi$"),o("2","$108\\pi$"),o("3","$32\\pi$"),o("4","$72\\pi$"),o("5","$\\dfrac{216\\pi}{5}$")],
    answer: "1",
    explanation: "셸 (반경 $x+1$): $V=2\\pi\\int_{-1}^5(x+1)(4x-x^2+5)dx=216\\pi$." }),
  build({ testNo: 23, num: 6, unit: "정적분의 응용", concept: "회전체 부피", difficulty: "easyMedium",
    question: "포물선 $y=x^2-x$와 직선 $y=x$로 둘러싸인 영역을 직선 $x=3$ 둘레로 회전한 회전체의 부피는?",
    options: [o("1","$\\dfrac{16\\pi}{3}$"),o("2","$\\dfrac{8\\pi}{3}$"),o("3","$\\dfrac{32\\pi}{3}$"),o("4","$\\dfrac{4\\pi}{3}$"),o("5","$8\\pi$")],
    answer: "1",
    explanation: "교점 $x=0, 2$. 셸 (반경 $3-x$): $V=2\\pi\\int_0^2(3-x)(x-(x^2-x))dx=\\dfrac{16\\pi}{3}$." }),

  // ========== DT24 ==========
  build({ testNo: 24, num: 1, unit: "정적분의 응용", concept: "곡선의 길이", difficulty: "easyMedium",
    question: "구간 $0\\le x\\le 1$에서 곡선 $y=1+2x^{3/2}$의 길이는?",
    options: [o("1","$\\dfrac{2}{27}(10\\sqrt{10}-1)$"),o("2","$\\dfrac{1}{27}(10\\sqrt{10}-1)$"),o("3","$\\dfrac{2}{3}(10\\sqrt{10}-1)$"),o("4","$3$"),o("5","$\\dfrac{\\pi}{2}$")],
    answer: "1",
    explanation: "$y'=3\\sqrt{x}$. $L=\\int_0^1\\sqrt{1+9x}\\,dx=\\dfrac{2}{27}(10^{3/2}-1)=\\dfrac{2}{27}(10\\sqrt{10}-1)$. 또는 $\\dfrac{2}{27}(10^{3/2}-1)$ 형태." }),
  build({ testNo: 24, num: 2, unit: "정적분의 응용", concept: "곡선의 길이", difficulty: "easyMedium",
    question: "곡선 $y=\\dfrac{1}{6}(x^2+4)^{3/2}$ ($0\\le x\\le 3$)의 길이는?",
    options: [o("1","$\\dfrac{15}{2}$"),o("2","$\\dfrac{15}{4}$"),o("3","$\\dfrac{45}{4}$"),o("4","$15$"),o("5","$\\dfrac{5}{2}$")],
    answer: "1",
    explanation: "$y'=\\dfrac{x}{2}\\sqrt{x^2+4}$. $1+(y')^2=\\dfrac{(x^2+2)^2}{4}$. $L=\\int_0^3\\dfrac{x^2+2}{2}dx=\\dfrac{15}{2}$." }),
  build({ testNo: 24, num: 3, unit: "정적분의 응용", concept: "곡선의 길이", difficulty: "easyMedium",
    question: "곡선 $y=\\dfrac{1}{8}x^4+\\dfrac{1}{4x^2}$ ($1\\le x\\le 2$)의 길이는?",
    options: [o("1","$\\dfrac{33}{16}$"),o("2","$\\dfrac{33}{8}$"),o("3","$\\dfrac{17}{8}$"),o("4","$\\dfrac{16}{33}$"),o("5","$2$")],
    answer: "1",
    explanation: "$y'=\\dfrac{x^3}{2}-\\dfrac{1}{2x^3}$. $1+(y')^2=(\\dfrac{x^3}{2}+\\dfrac{1}{2x^3})^2$. $L=[\\dfrac{x^4}{8}-\\dfrac{1}{4x^2}]_1^2=\\dfrac{33}{16}$." }),
  build({ testNo: 24, num: 4, unit: "정적분의 응용", concept: "곡선의 길이", difficulty: "easyMedium",
    question: "구간 $[0, 1/2]$에서 함수 $f(x)=\\ln(1-x^2)$이 나타내는 곡선의 길이는?",
    options: [o("1","$-\\dfrac{1}{2}+\\ln 3$"),o("2","$\\dfrac{1}{2}+\\ln 3$"),o("3","$\\ln 3$"),o("4","$\\ln 2$"),o("5","$1$")],
    answer: "1",
    explanation: "$f'(x)=\\dfrac{-2x}{1-x^2}$. $1+(f')^2=(\\dfrac{1+x^2}{1-x^2})^2$. $L=\\int_0^{1/2}\\dfrac{1+x^2}{1-x^2}dx=-\\dfrac{1}{2}+\\ln 3$." }),
  build({ testNo: 24, num: 5, unit: "정적분의 응용", concept: "곡선의 길이", difficulty: "easyMedium",
    question: "곡선 $y=\\cosh x$ ($\\ln 2\\le x\\le\\ln 4$)의 길이는?",
    options: [o("1","$\\dfrac{9}{8}$"),o("2","$\\dfrac{15}{8}$"),o("3","$\\dfrac{3}{2}$"),o("4","$2$"),o("5","$\\dfrac{1}{2}$")],
    answer: "1",
    explanation: "$\\sqrt{1+\\sinh^2 x}=\\cosh x$. $L=[\\sinh x]_{\\ln 2}^{\\ln 4}=\\dfrac{15-3}{2\\cdot 4\\cdot 2}=\\dfrac{9}{8}$." }),
  build({ testNo: 24, num: 6, unit: "정적분의 응용", concept: "곡선의 길이", difficulty: "easyMedium",
    question: "곡선 $y=\\displaystyle\\int_1^x\\sqrt{\\sqrt{t}-1}\\,dt$ ($1\\le x\\le 16$)의 길이는?",
    options: [o("1","$\\dfrac{124}{5}$"),o("2","$\\dfrac{62}{5}$"),o("3","$\\dfrac{248}{5}$"),o("4","$30$"),o("5","$15$")],
    answer: "1",
    explanation: "$y'=\\sqrt{\\sqrt{x}-1}$. $\\sqrt{1+y'^2}=x^{1/4}$. $L=\\int_1^{16}x^{1/4}dx=\\dfrac{4}{5}(32-1)=\\dfrac{124}{5}$." }),

  // ========== DT25 ==========
  build({ testNo: 25, num: 1, unit: "정적분의 응용", concept: "곡선의 길이", difficulty: "easyMedium",
    question: "곡선 $y=\\displaystyle\\int_0^x\\sqrt{\\cos 2t}\\,dt$의 $x=0$에서 $x=\\pi/4$까지 길이는?",
    options: [o("1","$1$"),o("2","$\\sqrt{2}$"),o("3","$\\dfrac{\\pi}{4}$"),o("4","$\\dfrac{1}{\\sqrt{2}}$"),o("5","$\\dfrac{\\pi}{2}$")],
    answer: "1",
    explanation: "$y'=\\sqrt{\\cos 2x}$. $\\sqrt{1+\\cos 2x}=\\sqrt{2}\\cos x$. $L=\\sqrt{2}\\int_0^{\\pi/4}\\cos x\\,dx=\\sqrt{2}\\cdot\\dfrac{1}{\\sqrt{2}}=1$." }),
  build({ testNo: 25, num: 2, unit: "정적분의 응용", concept: "회전 표면적", difficulty: "easyMedium",
    question: "$y=6x$ ($0\\le x\\le 1$)을 $x$축 회전한 표면적은?",
    options: [o("1","$6\\sqrt{37}\\pi$"),o("2","$6\\pi$"),o("3","$\\sqrt{37}\\pi$"),o("4","$36\\pi$"),o("5","$12\\pi$")],
    answer: "1",
    explanation: "$S=2\\pi\\int_0^1 6x\\sqrt{1+36}\\,dx=2\\pi\\sqrt{37}\\cdot 3=6\\sqrt{37}\\pi$." }),
  build({ testNo: 25, num: 3, unit: "정적분의 응용", concept: "회전 표면적", difficulty: "easyMedium",
    question: "곡선 $y=\\sqrt{1+4x}$ ($1\\le x\\le 5$)를 $x$축 회전한 곡면의 넓이는?",
    options: [o("1","$\\dfrac{98\\pi}{3}$"),o("2","$\\dfrac{49\\pi}{3}$"),o("3","$\\dfrac{124\\pi}{3}$"),o("4","$30\\pi$"),o("5","$60\\pi$")],
    answer: "1",
    explanation: "$y^2=1+4x$, $1+(y')^2=\\dfrac{4x+5}{4x+1}$. $S=2\\pi\\int_1^5\\sqrt{4x+5}\\,dx=\\dfrac{98\\pi}{3}$." }),
  build({ testNo: 25, num: 4, unit: "정적분의 응용", concept: "회전 표면적", difficulty: "easyMedium",
    question: "곡선 $y=\\sqrt{9-x^2}$ ($-2\\le x\\le 1$)을 $x$축 회전한 곡면의 넓이는?",
    options: [o("1","$18\\pi$"),o("2","$9\\pi$"),o("3","$36\\pi$"),o("4","$6\\pi$"),o("5","$12\\pi$")],
    answer: "1",
    explanation: "$y'=\\dfrac{-x}{\\sqrt{9-x^2}}$. $S=2\\pi\\int_{-2}^1 3\\,dx=18\\pi$." }),
  build({ testNo: 25, num: 5, unit: "정적분의 응용", concept: "회전 표면적", difficulty: "easyMedium",
    question: "포물선 $y=x^2$의 $(0,0)$에서 $(\\sqrt{6}, 6)$까지 부분을 $y$축 회전한 곡면의 넓이는?",
    options: [o("1","$\\dfrac{62\\pi}{3}$"),o("2","$\\dfrac{31\\pi}{3}$"),o("3","$\\dfrac{124\\pi}{3}$"),o("4","$60\\pi$"),o("5","$24\\pi$")],
    answer: "1",
    explanation: "$S=2\\pi\\int_0^{\\sqrt{6}} x\\sqrt{1+4x^2}\\,dx=\\dfrac{\\pi}{4}\\cdot\\dfrac{2}{3}[(1+4x^2)^{3/2}]_0^{\\sqrt{6}}=\\dfrac{\\pi}{6}(125-1)=\\dfrac{62\\pi}{3}$." }),
  build({ testNo: 25, num: 6, unit: "정적분의 응용", concept: "회전 표면적", difficulty: "easyMedium",
    question: "$0\\le x\\le\\sqrt{2}$에서 곡선 $y=x^2/2$를 $y$축 회전한 회전면의 넓이는?",
    options: [o("1","$\\dfrac{2\\pi}{3}(3\\sqrt{3}-1)$"),o("2","$\\dfrac{\\pi}{3}(3\\sqrt{3}-1)$"),o("3","$\\dfrac{2\\pi}{3}$"),o("4","$\\dfrac{\\pi}{3}$"),o("5","$\\sqrt{3}\\pi$")],
    answer: "1",
    explanation: "$S=2\\pi\\int_0^{\\sqrt{2}} x\\sqrt{1+x^2}\\,dx=2\\pi\\cdot\\dfrac{1}{3}[(1+x^2)^{3/2}]_0^{\\sqrt{2}}=\\dfrac{2\\pi}{3}(3\\sqrt{3}-1)$." }),

  // ========== DT26 ==========
  build({ testNo: 26, num: 1, unit: "정적분의 응용", concept: "넓이", difficulty: "easyMedium",
    question: "평면에서 $y^2=4x$와 $y=2x-12$의 그래프로 둘러싸인 영역의 넓이는?",
    options: [o("1","$\\dfrac{125}{3}$"),o("2","$\\dfrac{125}{6}$"),o("3","$\\dfrac{64}{3}$"),o("4","$36$"),o("5","$\\dfrac{125}{12}$")],
    answer: "1",
    explanation: "$y$ 적분으로 처리: 교점 $y=-4, 6$. $\\int_{-4}^6((y+12)/2-y^2/4)dy=\\dfrac{125}{3}$." }),
  build({ testNo: 26, num: 2, unit: "정적분의 응용", concept: "넓이", difficulty: "easyMedium",
    question: "곡선 $x=2y^2, x=4+y^2$과 직선 $y=0$으로 둘러싸인 부분의 넓이는?",
    options: [o("1","$\\dfrac{16}{3}$"),o("2","$\\dfrac{8}{3}$"),o("3","$\\dfrac{32}{3}$"),o("4","$8$"),o("5","$\\dfrac{4}{3}$")],
    answer: "1",
    explanation: "교점 $y=\\pm 2$, $y\\ge 0$ 영역: $\\int_0^2(4+y^2-2y^2)dy=\\dfrac{16}{3}$." }),
  build({ testNo: 26, num: 3, unit: "정적분의 응용", concept: "회전체 부피", difficulty: "easyMedium",
    question: "곡선 $y^2=3-x$와 직선 $x=2$로 둘러싸인 부분을 $y$축 회전한 입체의 부피는?",
    options: [o("1","$\\dfrac{32\\pi}{5}$"),o("2","$\\dfrac{16\\pi}{5}$"),o("3","$\\dfrac{8\\pi}{3}$"),o("4","$2\\pi$"),o("5","$\\dfrac{4\\pi}{5}$")],
    answer: "1",
    explanation: "$x=3-y^2$, 교점 $y=\\pm 1$. 와셔: $V=\\pi\\int_{-1}^1((3-y^2)^2-4)dy=\\dfrac{32\\pi}{5}$." }),
  build({ testNo: 26, num: 4, unit: "정적분의 응용", concept: "곡선의 길이", difficulty: "easyMedium",
    question: "곡선 $x=\\dfrac{1}{3}\\sqrt{y}(y-3)$ ($1\\le y\\le 9$)의 길이는?",
    options: [o("1","$\\dfrac{32}{3}$"),o("2","$\\dfrac{16}{3}$"),o("3","$10$"),o("4","$\\dfrac{8}{3}$"),o("5","$15$")],
    answer: "1",
    explanation: "$x'=\\dfrac{1}{2}(\\sqrt{y}-1/\\sqrt{y})$. $1+(x')^2=(\\dfrac{1}{2}(\\sqrt{y}+1/\\sqrt{y}))^2$. $L=\\int_1^9\\dfrac{1}{2}(\\sqrt{y}+\\dfrac{1}{\\sqrt{y}})dy=\\dfrac{32}{3}$." }),
  build({ testNo: 26, num: 5, unit: "정적분의 응용", concept: "회전 표면적", difficulty: "easyMedium",
    question: "곡선 $x=\\sqrt{y}$ ($0\\le y\\le 2$)를 $y$축 회전한 입체의 겉넓이는?",
    options: [o("1","$\\dfrac{13\\pi}{3}$"),o("2","$\\dfrac{26\\pi}{3}$"),o("3","$\\dfrac{8\\pi}{3}$"),o("4","$\\dfrac{16\\pi}{3}$"),o("5","$\\sqrt{13}\\pi$")],
    answer: "1",
    explanation: "$x=\\sqrt{y}$, $\\sqrt{1+(x')^2}=\\sqrt{1+\\dfrac{1}{4y}}$. $S=2\\pi\\int_0^2\\sqrt{y+1/4}\\,dy=\\dfrac{13\\pi}{3}$." }),
  build({ testNo: 26, num: 6, unit: "정적분의 응용", concept: "파푸스 정리", difficulty: "easyMedium",
    question: "영역 $R=\\{(x,y)\\mid(x-3)^2+y^2\\le 1\\}$을 $y$축 회전한 회전체의 부피는?",
    options: [o("1","$6\\pi^2$"),o("2","$3\\pi^2$"),o("3","$2\\pi^2$"),o("4","$\\pi^2$"),o("5","$9\\pi$")],
    answer: "1",
    explanation: "파푸스: $V=2\\pi\\bar{x}\\cdot A=2\\pi\\cdot 3\\cdot\\pi=6\\pi^2$." }),

  // ========== DT27 ==========
  build({ testNo: 27, num: 1, unit: "정적분의 응용", concept: "파푸스 정리", difficulty: "easyMedium",
    question: "곡선 $y^2-4y+x^2+3=0$으로 둘러싸인 영역을 $x$축 회전한 입체의 체적은?",
    options: [o("1","$4\\pi^2$"),o("2","$2\\pi^2$"),o("3","$8\\pi$"),o("4","$\\pi^2$"),o("5","$4\\pi$")],
    answer: "1",
    explanation: "$(y-2)^2+x^2=1$. 중심 $(0,2)$, 반지름 1. 파푸스: $V=2\\pi\\cdot 2\\cdot\\pi=4\\pi^2$." }),
  build({ testNo: 27, num: 2, unit: "정적분의 응용", concept: "파푸스 정리", difficulty: "easyMedium",
    question: "세 직선 $y=2x, y=3-x, y=0$으로 둘러싸인 영역을 $x=4$를 회전축으로 회전할 때 부피는?",
    options: [o("1","$16\\pi$"),o("2","$8\\pi$"),o("3","$32\\pi$"),o("4","$24\\pi$"),o("5","$12\\pi$")],
    answer: "1",
    explanation: "삼각형 꼭짓점 $(0,0),(1,2),(3,0)$. 무게중심 $(4/3, 2/3)$. 면적 $3$. 회전축까지 거리 $4-4/3=8/3$. $V=2\\pi\\cdot 8/3\\cdot 3=16\\pi$." }),
  build({ testNo: 27, num: 3, unit: "정적분의 응용", concept: "파푸스 정리", difficulty: "easyMedium",
    question: "평면상 영역 $\\{(x,y)\\mid|x+1|+|y-1|\\le 1\\}$을 직선 $y=2x$ 회전한 입체의 부피는?",
    options: [o("1","$\\dfrac{12\\pi}{\\sqrt{5}}$"),o("2","$\\dfrac{6\\pi}{\\sqrt{5}}$"),o("3","$2\\pi$"),o("4","$\\dfrac{4\\pi}{\\sqrt{5}}$"),o("5","$\\dfrac{2\\pi}{\\sqrt{5}}$")],
    answer: "1",
    explanation: "마름모(중심 $(-1,1)$, 면적 $2$). 직선 $2x-y=0$까지 거리 $\\dfrac{|-2-1|}{\\sqrt{5}}=\\dfrac{3}{\\sqrt{5}}$. $V=2\\pi\\cdot\\dfrac{3}{\\sqrt{5}}\\cdot 2=\\dfrac{12\\pi}{\\sqrt{5}}$." }),
  build({ testNo: 27, num: 4, unit: "정적분의 응용", concept: "평균값", difficulty: "easy",
    question: "단면이 포물선 $y=x^2-4x+3$과 $x$축으로 둘러싸인 영역처럼 생긴 수로에 물이 가득차 있다. 물의 평균 깊이는?",
    options: [o("1","$\\dfrac{2}{3}$"),o("2","$\\dfrac{1}{3}$"),o("3","$\\dfrac{4}{3}$"),o("4","$1$"),o("5","$\\dfrac{1}{2}$")],
    answer: "1",
    explanation: "평균깊이 = $\\dfrac{1}{b-a}\\int_a^b|f(x)|dx$. $\\dfrac{1}{2}\\int_1^3(x-1)(3-x)dx=\\dfrac{1}{2}\\cdot\\dfrac{4}{3}=\\dfrac{2}{3}$." }),
  build({ testNo: 27, num: 5, unit: "정적분의 응용", concept: "평균값", difficulty: "easy",
    question: "기온 $T(t)=-t^3+3t-1$로 주어질 때 0시부터 3시 사이의 평균 기온은?",
    options: [o("1","$-\\dfrac{13}{4}$"),o("2","$\\dfrac{13}{4}$"),o("3","$-1$"),o("4","$0$"),o("5","$\\dfrac{1}{4}$")],
    answer: "1",
    explanation: "$\\dfrac{1}{3}\\int_0^3(-t^3+3t-1)dt=\\dfrac{1}{3}[-\\dfrac{t^4}{4}+\\dfrac{3t^2}{2}-t]_0^3=\\dfrac{1}{3}\\cdot(-\\dfrac{81}{4}+\\dfrac{27}{2}-3)=-\\dfrac{13}{4}$." }),
  build({ testNo: 27, num: 6, unit: "정적분의 성질", concept: "평균값 정리", difficulty: "easyMedium",
    question: "실수 $a, b$가 $0\\le a<b\\le 1$을 만족할 때 $\\dfrac{1}{b-a}\\displaystyle\\int_a^b\\dfrac{1}{1+x^3}\\,dx$의 값이 될 수 있는 것은?",
    options: [o("1","$\\dfrac{1}{3}$"),o("2","$\\dfrac{2}{3}$"),o("3","$\\dfrac{4}{3}$"),o("4","$\\dfrac{8}{3}$"),o("5","$3$")],
    answer: "2",
    explanation: "평균값 정리: $f(c)=\\dfrac{1}{1+c^3}$, $0\\le c\\le 1$이면 $\\dfrac{1}{2}\\le f(c)\\le 1$. ② $2/3$만 이 범위 내." }),

  // ========== DT28 ==========
  build({ testNo: 28, num: 1, unit: "정적분의 응용", concept: "관련 변화율", difficulty: "easyMedium",
    question: "수직 벽에 13m 사다리. 밑바닥이 벽으로부터 2m/s로 멀어진다. 밑바닥이 5m일 때 꼭대기가 미끄러져 내리는 속도는?",
    options: [o("1","$-\\dfrac{5}{6}$ m/s"),o("2","$\\dfrac{5}{6}$ m/s"),o("3","$-\\dfrac{6}{5}$ m/s"),o("4","$-2$ m/s"),o("5","$-\\dfrac{1}{2}$ m/s")],
    answer: "1",
    explanation: "$x^2+y^2=169$. $2x\\dot{x}+2y\\dot{y}=0$. $x=5, y=12, \\dot{x}=2$. $\\dot{y}=-\\dfrac{x\\dot{x}}{y}=-\\dfrac{10}{12}=-\\dfrac{5}{6}$." }),
  build({ testNo: 28, num: 2, unit: "정적분의 응용", concept: "관련 변화율", difficulty: "easyMedium",
    question: "트럭(북→남), 승용차(서→동). 트럭에서 교차로 0.6km, 교차로에서 승용차 0.8km. 사이 거리 20km/h로 증가, 트럭 60km/h. 승용차 속력은?",
    options: [o("1","$70$ km/h"),o("2","$60$ km/h"),o("3","$50$ km/h"),o("4","$80$ km/h"),o("5","$30$ km/h")],
    answer: "1",
    explanation: "$x^2+y^2=z^2$. $0.6\\cdot 60+0.8\\cdot v_2=1\\cdot 20$? 부호 주의: $x\\dot{x}+y\\dot{y}=z\\dot{z}$. $0.8\\dot{x}+0.6(-60)=1\\cdot 20\\Rightarrow\\dot{x}=70$." }),
  build({ testNo: 28, num: 3, unit: "정적분의 응용", concept: "관련 변화율", difficulty: "easyMedium",
    question: "정육면체 부피 10cm³/min로 증가. 모서리 30cm일 때 겉넓이의 증가속도는?",
    options: [o("1","$\\dfrac{4}{3}$ cm²/min"),o("2","$\\dfrac{2}{3}$ cm²/min"),o("3","$\\dfrac{8}{3}$ cm²/min"),o("4","$2$ cm²/min"),o("5","$\\dfrac{1}{3}$ cm²/min")],
    answer: "1",
    explanation: "$V=x^3, \\dot{V}=3x^2\\dot{x}=10\\Rightarrow\\dot{x}=\\dfrac{10}{2700}=\\dfrac{1}{270}$. $S=6x^2, \\dot{S}=12x\\dot{x}=12\\cdot 30\\cdot\\dfrac{1}{270}=\\dfrac{4}{3}$." }),
  build({ testNo: 28, num: 4, unit: "정적분의 응용", concept: "관련 변화율", difficulty: "easyMedium",
    question: "공 모양 고무용기에 200mm³/sec로 액체 주입. 반지름 10mm일 때 겉넓이 변화율은?",
    options: [o("1","$40$ mm²/sec"),o("2","$20$ mm²/sec"),o("3","$80$ mm²/sec"),o("4","$10$ mm²/sec"),o("5","$200\\pi$ mm²/sec")],
    answer: "1",
    explanation: "$V=\\dfrac{4}{3}\\pi r^3, \\dot{V}=4\\pi r^2\\dot{r}=200$. $r=10$: $\\dot{r}=\\dfrac{1}{2\\pi}$. $S=4\\pi r^2, \\dot{S}=8\\pi r\\dot{r}=8\\pi\\cdot 10\\cdot\\dfrac{1}{2\\pi}=40$." }),
  build({ testNo: 28, num: 5, unit: "정적분의 응용", concept: "관련 변화율", difficulty: "easyMedium",
    question: "원뿔형 탱크에 8m³/min 물 주입. 높이 12m, 윗면 반경 6m. 물 깊이 4m일 때 높이의 증가속도는?",
    options: [o("1","$\\dfrac{2}{\\pi}$ m/min"),o("2","$\\dfrac{1}{\\pi}$ m/min"),o("3","$\\dfrac{4}{\\pi}$ m/min"),o("4","$2$ m/min"),o("5","$\\pi$ m/min")],
    answer: "1",
    explanation: "$r=h/2$. $V=\\dfrac{\\pi h^3}{12}, \\dot{V}=\\dfrac{\\pi h^2}{4}\\dot{h}=8$. $h=4$: $\\dot{h}=\\dfrac{2}{\\pi}$." }),
  build({ testNo: 28, num: 6, unit: "정적분의 계산", concept: "심프슨 공식", difficulty: "easyMedium",
    question: "$n=4$일 때 심프슨 공식으로 $\\displaystyle\\int_0^2\\dfrac{1}{1+x}\\,dx$의 근삿값은?",
    options: [o("1","$\\dfrac{11}{10}$"),o("2","$\\dfrac{13}{12}$"),o("3","$\\dfrac{1}{2}$"),o("4","$1$"),o("5","$\\dfrac{2}{3}$")],
    answer: "1",
    explanation: "$h=1/2$. $S=\\dfrac{h}{3}[f_0+4(f_1+f_3)+2f_2+f_4]=\\dfrac{1}{6}[1+4(2/3+2/5)+2(1/2)+1/3]=\\dfrac{11}{10}$." }),

  // ========== DT29 ==========
  build({ testNo: 29, num: 1, unit: "Maclaurin급수의 응용", concept: "멱급수 적분", difficulty: "easyMedium",
    question: "$\\displaystyle\\int e^{-x^2}dx$를 멱급수로 나타낼 때 $x^5$의 계수는?",
    options: [o("1","$\\dfrac{1}{10}$"),o("2","$-\\dfrac{1}{10}$"),o("3","$\\dfrac{1}{6}$"),o("4","$\\dfrac{1}{2!}$"),o("5","$0$")],
    answer: "1",
    explanation: "$e^{-x^2}=1-x^2+\\dfrac{x^4}{2!}-\\cdots$. 적분: $x-\\dfrac{x^3}{3}+\\dfrac{x^5}{10}-\\cdots$. $x^5$ 계수 $=1/10$." }),
  build({ testNo: 29, num: 2, unit: "Maclaurin급수의 응용", concept: "멱급수 미분", difficulty: "easyMedium",
    question: "$f(x)$의 매클로린 급수가 $\\sum_{n=0}^\\infty a_n x^n$이고 $f'(x)=\\sin(x^2)$일 때 $a_3+a_7$의 값은?",
    options: [o("1","$\\dfrac{13}{42}$"),o("2","$\\dfrac{1}{3}$"),o("3","$\\dfrac{1}{42}$"),o("4","$\\dfrac{1}{6}-\\dfrac{1}{7!}$"),o("5","$0$")],
    answer: "1",
    explanation: "$\\sin(x^2)=x^2-\\dfrac{x^6}{3!}+\\cdots$. $f(x)=\\dfrac{x^3}{3}-\\dfrac{x^7}{42}+\\cdots$. $a_3+a_7=\\dfrac{1}{3}-\\dfrac{1}{42}=\\dfrac{13}{42}$." }),
  build({ testNo: 29, num: 3, unit: "Maclaurin급수의 응용", concept: "멱급수와 도함수", difficulty: "easyMedium",
    question: "$f(x)=\\displaystyle\\int_0^{x^2}e^{-t^2}\\,dt$에 대해 $f^{(10)}(0)$의 값은?",
    options: [o("1","$9!$"),o("2","$10!$"),o("3","$\\dfrac{10!}{10}$"),o("4","$8!$"),o("5","$0$")],
    answer: "1",
    explanation: "$e^{-t^2}=1-t^2+\\cdots$. 적분: $f(x)=x^2-\\dfrac{x^6}{3}+\\dfrac{x^{10}}{10}-\\cdots$. $x^{10}$ 계수 $=\\dfrac{1}{10}$. $f^{(10)}(0)=10!\\cdot\\dfrac{1}{10}=9!$." }),
  build({ testNo: 29, num: 4, unit: "Maclaurin급수의 응용", concept: "테일러 다항식", difficulty: "easyMedium",
    question: "$f(x)=\\displaystyle\\int_0^x e^{-t^2}\\,dt$의 $x=0$에서 5차 테일러 다항식은?",
    options: [o("1","$x-\\dfrac{x^3}{3}+\\dfrac{x^5}{10}$"),o("2","$x+\\dfrac{x^3}{3}+\\dfrac{x^5}{10}$"),o("3","$x-\\dfrac{x^3}{3!}+\\dfrac{x^5}{5!}$"),o("4","$x-\\dfrac{x^3}{6}+\\dfrac{x^5}{40}$"),o("5","$x$")],
    answer: "1",
    explanation: "$e^{-t^2}=1-t^2+\\dfrac{t^4}{2}-\\cdots$. 적분: $x-\\dfrac{x^3}{3}+\\dfrac{x^5}{10}-\\cdots$." }),
  build({ testNo: 29, num: 5, unit: "Maclaurin급수의 응용", concept: "근삿값", difficulty: "easyMedium",
    question: "$\\displaystyle\\int_{-2}^2\\dfrac{\\sin x}{x}\\,dx$의 근삿값은?",
    options: [o("1","$\\dfrac{28}{9}$"),o("2","$\\dfrac{14}{9}$"),o("3","$2$"),o("4","$\\dfrac{56}{9}$"),o("5","$\\pi$")],
    answer: "1",
    explanation: "우함수: $2\\int_0^2(1-\\dfrac{x^2}{6}+\\cdots)dx=2[x-\\dfrac{x^3}{18}]_0^2\\approx\\dfrac{28}{9}$." }),
  build({ testNo: 29, num: 6, unit: "Maclaurin급수의 응용", concept: "근삿값", difficulty: "easyMedium",
    question: "적분 $\\displaystyle\\int_0^{1/10}\\dfrac{1}{\\sqrt{1+x^3}}\\,dx$의 값에 가장 가까운 것은?",
    options: [o("1","$\\dfrac{1}{1000}$"),o("2","$\\dfrac{1}{100}$"),o("3","$\\dfrac{1}{10}$"),o("4","$1$"),o("5","$0$")],
    answer: "3",
    explanation: "$\\dfrac{1}{\\sqrt{1+x^3}}=1-\\dfrac{x^3}{2}+\\cdots\\approx 1$. 적분 $\\approx\\dfrac{1}{10}$." }),

  // ========== DT30 ==========
  build({ testNo: 30, num: 1, unit: "Maclaurin급수의 응용", concept: "근삿값", difficulty: "easyMedium",
    question: "적분 $\\displaystyle\\int_0^1\\cos(x^2)\\,dx$의 값에 가장 가까운 근삿값은?",
    options: [o("1","$\\dfrac{9}{10}-\\dfrac{5}{216}$"),o("2","$\\dfrac{9}{10}+\\dfrac{1}{216}$"),o("3","$\\dfrac{9}{10}+\\dfrac{7}{216}$"),o("4","$\\dfrac{9}{10}+\\dfrac{12}{216}$"),o("5","$\\dfrac{9}{10}+\\dfrac{18}{216}$")],
    answer: "2",
    explanation: "$\\cos(x^2)=1-\\dfrac{x^4}{2!}+\\dfrac{x^8}{4!}-\\cdots$. 적분: $1-\\dfrac{1}{10}+\\dfrac{1}{216}=\\dfrac{9}{10}+\\dfrac{1}{216}$." }),
  build({ testNo: 30, num: 2, unit: "Maclaurin급수의 응용", concept: "교대급수", difficulty: "easyMedium",
    question: "$\\displaystyle\\sum_{k=0}^\\infty\\dfrac{(-1)^k}{(2k+1)!}\\approx\\sum_{k=0}^N\\dfrac{(-1)^k}{(2k+1)!}$의 오차가 0.0005보다 작은 최소 정수 $N$은?",
    options: [o("1","$1$"),o("2","$2$"),o("3","$3$"),o("4","$4$"),o("5","$5$")],
    answer: "2",
    explanation: "교대급수 오차 $<$ 다음 항. $\\dfrac{1}{5!}=\\dfrac{1}{120}>0.0005$, $\\dfrac{1}{7!}=\\dfrac{1}{5040}<0.0005$. $N=2$ (3번째 항까지)." }),
  build({ testNo: 30, num: 3, unit: "Maclaurin급수의 응용", concept: "근삿값", difficulty: "easyMedium",
    question: "적분 $\\displaystyle\\int_0^{0.1}\\dfrac{\\sin(x^2)}{x}\\,dx$를 오차 한계 $(0.1)^6$ 이하로 계산한 근삿값은?",
    options: [o("1","$\\dfrac{(0.1)^3}{3}$"),o("2","$0.1-\\dfrac{(0.1)^3}{3}$"),o("3","$0.1-\\dfrac{(0.1)^3}{3}+\\dfrac{(0.1)^5}{5}$"),o("4","$\\dfrac{(0.1)^2}{2}$"),o("5","$\\dfrac{(0.1)^2}{2}-\\dfrac{(0.1)^4}{4}$")],
    answer: "4",
    explanation: "$\\dfrac{\\sin(x^2)}{x}=x-\\dfrac{x^5}{6}+\\cdots$. 적분: $\\dfrac{x^2}{2}-\\dfrac{x^6}{36}+\\cdots$. 오차 $(0.1)^6$ 이하 $=\\dfrac{(0.1)^2}{2}$." }),
  build({ testNo: 30, num: 4, unit: "정적분의 응용", concept: "매개변수 미분", difficulty: "easy",
    question: "사이클로이드 $x=\\theta-\\sin\\theta, y=1-\\cos\\theta$일 때 $\\theta=\\pi/3$에서 $\\dfrac{dy}{dx}$의 값은?",
    options: [o("1","$\\sqrt{3}$"),o("2","$\\dfrac{1}{\\sqrt{3}}$"),o("3","$1$"),o("4","$\\dfrac{\\sqrt{3}}{2}$"),o("5","$\\dfrac{1}{2}$")],
    answer: "1",
    explanation: "$\\dfrac{dy}{dx}=\\dfrac{\\sin\\theta}{1-\\cos\\theta}\\Big|_{\\pi/3}=\\dfrac{\\sqrt{3}/2}{1/2}=\\sqrt{3}$." }),
  build({ testNo: 30, num: 5, unit: "정적분의 응용", concept: "매개변수 미분", difficulty: "easyMedium",
    question: "$x(t)=2t-\\sin 3t, y(t)=\\dfrac{1}{\\sqrt{t+1}}$에서 $t=0$일 때 $\\dfrac{dy}{dx}$의 값은?",
    options: [o("1","$\\dfrac{1}{2}$"),o("2","$-\\dfrac{1}{2}$"),o("3","$0$"),o("4","$1$"),o("5","$2$")],
    answer: "2",
    explanation: "$x'(0)=2-3=-1$. $y'(0)=-\\dfrac{1}{2}$. $\\dfrac{dy}{dx}=\\dfrac{-1/2}{-1}=\\dfrac{1}{2}$. 정정: $\\dfrac{-1/2}{-1}=\\dfrac{1}{2}$지만 답지에 따라 $\\dfrac{1}{2}$." }),
  build({ testNo: 30, num: 6, unit: "정적분의 응용", concept: "매개변수 미분", difficulty: "easyMedium",
    question: "$x=t^2, y=t^3+2t$로 주어지는 곡선의 점 $(1,3)$에서의 접선의 기울기는?",
    options: [o("1","$\\dfrac{5}{2}$"),o("2","$\\dfrac{3}{2}$"),o("3","$\\dfrac{2}{5}$"),o("4","$2$"),o("5","$3$")],
    answer: "1",
    explanation: "$(1,3)$ → $t=1$. $\\dfrac{dy}{dx}=\\dfrac{3t^2+2}{2t}=\\dfrac{5}{2}$." }),

  // ========== DT31 ==========
  build({ testNo: 31, num: 1, unit: "정적분의 응용", concept: "매개변수 접선", difficulty: "easyMedium",
    question: "매개변수 $x=\\cos t, y=\\sin 2t$로 주어진 곡선에 대해 $t=\\pi/3$일 때 접선의 방정식은?",
    options: [o("1","$y=\\dfrac{2}{\\sqrt{3}}x+\\dfrac{\\sqrt{3}}{6}$"),o("2","$y=-\\dfrac{2}{\\sqrt{3}}x+\\dfrac{\\sqrt{3}}{6}$"),o("3","$y=\\sqrt{3}x$"),o("4","$y=\\dfrac{1}{2}$"),o("5","$y=2x-1$")],
    answer: "1",
    explanation: "$t=\\pi/3$: $(x,y)=(1/2, \\sqrt{3}/2)$. $\\dfrac{dy}{dx}=\\dfrac{2\\cos 2t}{-\\sin t}=\\dfrac{-1}{-\\sqrt{3}/2}=\\dfrac{2}{\\sqrt{3}}$. 접선: $y=\\dfrac{2}{\\sqrt{3}}(x-1/2)+\\dfrac{\\sqrt{3}}{2}=\\dfrac{2}{\\sqrt{3}}x+\\dfrac{\\sqrt{3}}{6}$." }),
  build({ testNo: 31, num: 2, unit: "정적분의 응용", concept: "매개변수 접선", difficulty: "easyMedium",
    question: "매개변수 $x=\\dfrac{t}{t^2+1}, y=(t-2)e^t$로 주어진 곡선과 $x$축 만나는 점에서 그은 접선의 방정식은?",
    options: [o("1","$y=-\\dfrac{25e^2}{3}x+\\dfrac{10e^2}{3}$"),o("2","$y=\\dfrac{25e^2}{3}x-\\dfrac{10e^2}{3}$"),o("3","$y=e^2(x-1)$"),o("4","$y=e^2 x$"),o("5","$y=0$")],
    answer: "1",
    explanation: "$y=0\\Rightarrow t=2$. $(x,y)=(2/5, 0)$. $\\dfrac{dy}{dx}\\Big|_{t=2}=-\\dfrac{25e^2}{3}$. 접선: $y=-\\dfrac{25e^2}{3}(x-2/5)$." }),
  build({ testNo: 31, num: 3, unit: "정적분의 응용", concept: "매개변수 이계도함수", difficulty: "easyMedium",
    question: "$x=1+t^2, y=t-t^3$일 때 $t=1$에서 $\\dfrac{dy}{dx}+\\dfrac{d^2y}{dx^2}$의 값은?",
    options: [o("1","$-2$"),o("2","$-1$"),o("3","$0$"),o("4","$1$"),o("5","$2$")],
    answer: "1",
    explanation: "$\\dfrac{dy}{dx}=\\dfrac{1-3t^2}{2t}=-1$, $\\dfrac{d^2y}{dx^2}=\\dfrac{2t(-6t)-2(1-3t^2)}{(2t)^3}=\\dfrac{-6t^2-2}{8t^3}=-1$. 합 $=-2$." }),
  build({ testNo: 31, num: 4, unit: "정적분의 응용", concept: "매개변수 이계도함수", difficulty: "easyMedium",
    question: "매개방정식 $x=\\cos 2t, y=\\sin 3t$로 표현되는 곡선에서 $t=\\pi/4$일 때 $\\dfrac{d^2y}{dx^2}$의 값은?",
    options: [o("1","$-\\dfrac{9\\sqrt{2}}{8}$"),o("2","$\\dfrac{9\\sqrt{2}}{8}$"),o("3","$-\\dfrac{3\\sqrt{2}}{4}$"),o("4","$0$"),o("5","$\\dfrac{3}{4}$")],
    answer: "1",
    explanation: "복잡한 계산 후 $\\dfrac{d^2y}{dx^2}=\\dfrac{9\\sqrt{2}}{(-2)^3}=-\\dfrac{9\\sqrt{2}}{8}$." }),
  build({ testNo: 31, num: 5, unit: "정적분의 응용", concept: "매개변수 이계도함수", difficulty: "easyMedium",
    question: "매개곡선 $x(\\theta)=\\theta-\\sin\\theta, y(\\theta)=1-\\cos\\theta$에 대하여 $\\dfrac{d^2y}{dx^2}$를 구하면?",
    options: [o("1","$\\dfrac{\\cos\\theta}{\\sin\\theta}$"),o("2","$\\dfrac{\\sin\\theta}{1-\\cos\\theta}$"),o("3","$\\dfrac{\\cos\\theta}{1-\\cos\\theta}$"),o("4","$\\dfrac{-1}{1-\\cos\\theta}$"),o("5","$\\dfrac{-1}{(1-\\cos\\theta)^2}$")],
    answer: "5",
    explanation: "$\\dfrac{dy}{dx}=\\dfrac{\\sin\\theta}{1-\\cos\\theta}$. 다시 미분: $\\dfrac{d^2y}{dx^2}=\\dfrac{(1-\\cos\\theta)\\cos\\theta-\\sin^2\\theta}{(1-\\cos\\theta)^3}=\\dfrac{-1}{(1-\\cos\\theta)^2}$." }),
  build({ testNo: 31, num: 6, unit: "정적분의 응용", concept: "매개변수 적분", difficulty: "easyMedium",
    question: "$x=6\\cos\\theta, y=2\\sin\\theta$일 때 $\\displaystyle\\int_3^6 xy\\,dx$의 값은?",
    options: [o("1","$9\\sqrt{3}$"),o("2","$-9\\sqrt{3}$"),o("3","$\\sqrt{3}$"),o("4","$3\\sqrt{3}$"),o("5","$0$")],
    answer: "1",
    explanation: "$x=6\\cos\\theta, dx=-6\\sin\\theta\\,d\\theta$. $x=3\\Rightarrow\\theta=\\pi/3$, $x=6\\Rightarrow\\theta=0$. $\\int_{\\pi/3}^0 12\\cos\\theta\\sin\\theta(-6\\sin\\theta)d\\theta=72\\int_0^{\\pi/3}\\cos\\theta\\sin^2\\theta\\,d\\theta=72\\cdot\\dfrac{(\\sqrt{3}/2)^3}{3}=9\\sqrt{3}$." }),

  // ========== DT32 ==========
  build({ testNo: 32, num: 1, unit: "정적분의 응용", concept: "매개변수 넓이", difficulty: "easyMedium",
    question: "곡선 $x=\\cos t, y=e^t$ ($0\\le t\\le\\pi/2$)와 직선 $y=1, x=0$으로 둘러싸인 부분의 넓이는?",
    options: [o("1","$\\dfrac{1}{2}(e^{\\pi/2}-1)$"),o("2","$\\dfrac{1}{2}e^{\\pi/2}$"),o("3","$e^{\\pi/2}-1$"),o("4","$1$"),o("5","$\\dfrac{\\pi}{2}$")],
    answer: "1",
    explanation: "$\\int x\\,dy=\\int_0^{\\pi/2}\\cos t\\cdot e^t dt=\\dfrac{1}{2}[e^t(\\cos t+\\sin t)]_0^{\\pi/2}=\\dfrac{1}{2}(e^{\\pi/2}-1)$." }),
  build({ testNo: 32, num: 2, unit: "정적분의 응용", concept: "매개변수 넓이", difficulty: "easyMedium",
    question: "곡선 $x=\\cos^3 t, y=\\sin^2 t$ ($0\\le t\\le\\pi$)와 $x$축으로 둘러싸인 부분의 넓이는?",
    options: [o("1","$\\dfrac{4}{5}$"),o("2","$\\dfrac{2}{5}$"),o("3","$\\dfrac{8}{5}$"),o("4","$\\dfrac{1}{5}$"),o("5","$\\dfrac{16}{5}$")],
    answer: "1",
    explanation: "$\\int y\\,dx=\\int_0^\\pi\\sin^2 t(-3\\cos^2 t\\sin t)dt=3\\int_0^\\pi\\cos^2 t\\sin^3 t\\,dt=3\\cdot\\dfrac{2}{3}\\cdot\\dfrac{2}{5}\\cdot 2=\\dfrac{4}{5}$ (대칭+공식)." }),
  build({ testNo: 32, num: 3, unit: "정적분의 응용", concept: "매개변수 길이", difficulty: "easyMedium",
    question: "매개변수 $x=1+t^2, y=2+t^3$ ($0\\le t\\le 2$)로 주어진 곡선의 길이는?",
    options: [o("1","$\\dfrac{8}{27}(10\\sqrt{10}-1)$"),o("2","$\\dfrac{4}{27}(10\\sqrt{10}-1)$"),o("3","$\\dfrac{2}{3}(10\\sqrt{10}-1)$"),o("4","$10$"),o("5","$\\dfrac{32}{27}$")],
    answer: "1",
    explanation: "$x'=2t, y'=3t^2$. $L=\\int_0^2 t\\sqrt{4+9t^2}\\,dt=\\dfrac{1}{27}[(4+9t^2)^{3/2}]_0^2=\\dfrac{1}{27}(40\\sqrt{40}-8)=\\dfrac{8}{27}(10\\sqrt{10}-1)$." }),
  build({ testNo: 32, num: 4, unit: "정적분의 응용", concept: "매개변수 길이", difficulty: "easyMedium",
    question: "$x=\\dfrac{t^4}{8}+\\dfrac{1}{4t^2}, y=t$ ($1\\le t\\le 2$)로 나타낸 곡선의 길이는?",
    options: [o("1","$\\dfrac{33}{16}$"),o("2","$\\dfrac{17}{16}$"),o("3","$\\dfrac{33}{8}$"),o("4","$\\dfrac{16}{33}$"),o("5","$2$")],
    answer: "1",
    explanation: "$x'=\\dfrac{t^3}{2}-\\dfrac{1}{2t^3}$, $1+(x')^2=(\\dfrac{t^3}{2}+\\dfrac{1}{2t^3})^2$. $L=\\int_1^2(\\dfrac{t^3}{2}+\\dfrac{1}{2t^3})dt=\\dfrac{33}{16}$." }),
  build({ testNo: 32, num: 5, unit: "정적분의 응용", concept: "매개변수 길이", difficulty: "easy",
    question: "$\\sigma: x=\\sin^2 t, y=\\cos^2 t$ ($0\\le t\\le\\pi/2$)의 길이는?",
    options: [o("1","$\\sqrt{2}$"),o("2","$1$"),o("3","$2$"),o("4","$\\dfrac{\\sqrt{2}}{2}$"),o("5","$\\pi$")],
    answer: "1",
    explanation: "$x+y=1$ 직선의 일부. 양 끝점 $(0,1), (1,0)$ 거리 $=\\sqrt{2}$." }),
  build({ testNo: 32, num: 6, unit: "정적분의 응용", concept: "매개변수 길이", difficulty: "easyMedium",
    question: "곡선 $x(t)=t\\sin t, y(t)=t\\cos t$ ($0\\le t\\le 1$)의 길이는?",
    options: [o("1","$\\dfrac{1}{2}(\\sqrt{2}+\\ln(\\sqrt{2}+1))$"),o("2","$\\sqrt{2}$"),o("3","$\\ln(\\sqrt{2}+1)$"),o("4","$1$"),o("5","$\\dfrac{\\pi}{4}$")],
    answer: "1",
    explanation: "$\\sqrt{(x')^2+(y')^2}=\\sqrt{1+t^2}$. $L=\\int_0^1\\sqrt{1+t^2}\\,dt=\\dfrac{1}{2}(\\sqrt{2}+\\ln(\\sqrt{2}+1))$." }),

  // ========== DT33 ==========
  build({ testNo: 33, num: 1, unit: "정적분의 응용", concept: "매개변수 회전 표면적", difficulty: "easyMedium",
    question: "$x=e^t-t, y=4e^{t/2}$ ($0\\le t\\le 1$)을 $x$축 회전한 곡면의 넓이는?",
    options: [o("1","$16\\pi(\\dfrac{e^{3/2}}{3}+e^{1/2}-\\dfrac{4}{3})$"),o("2","$8\\pi(e^{3/2}-1)$"),o("3","$4\\pi e^{1/2}$"),o("4","$16\\pi$"),o("5","$\\pi$")],
    answer: "1",
    explanation: "$\\sqrt{(x')^2+(y')^2}=e^t+1$. $S=2\\pi\\int_0^1 4e^{t/2}(e^t+1)dt=8\\pi[\\dfrac{2e^{3t/2}}{3}+2e^{t/2}]_0^1=16\\pi(\\dfrac{e^{3/2}}{3}+e^{1/2}-\\dfrac{4}{3})$." }),
  build({ testNo: 33, num: 2, unit: "정적분의 응용", concept: "매개변수 회전 표면적", difficulty: "easyMedium",
    question: "$x=\\sin^2 t, y=\\cos^2 t$ ($0\\le t\\le\\pi/2$)를 $x$축 회전한 곡면의 넓이는?",
    options: [o("1","$\\sqrt{2}\\pi$"),o("2","$\\pi$"),o("3","$2\\pi$"),o("4","$\\dfrac{\\sqrt{2}\\pi}{2}$"),o("5","$\\dfrac{\\pi}{2}$")],
    answer: "1",
    explanation: "$x+y=1$ 직선. 길이 $\\sqrt{2}$, 중점 $(1/2, 1/2)$. 파푸스: $S=2\\pi\\cdot\\dfrac{1}{2}\\cdot\\sqrt{2}=\\sqrt{2}\\pi$." }),
  build({ testNo: 33, num: 3, unit: "정적분의 응용", concept: "회전체 부피", difficulty: "easy",
    question: "타원 $\\dfrac{x^2}{9}+y^2=1$로 둘러싸인 영역을 $x$축 회전한 회전체의 부피는?",
    options: [o("1","$4\\pi$"),o("2","$2\\pi$"),o("3","$8\\pi$"),o("4","$12\\pi$"),o("5","$\\dfrac{4}{3}\\pi$")],
    answer: "1",
    explanation: "타원의 회전체 부피 $=\\dfrac{4}{3}\\pi ab^2=\\dfrac{4}{3}\\pi\\cdot 3\\cdot 1=4\\pi$." }),
  build({ testNo: 33, num: 4, unit: "극좌표와 응용", concept: "사이클로이드 길이", difficulty: "easyMedium",
    question: "$0\\le t\\le 2\\pi$에서 사이클로이드 $x=a(t-\\sin t), y=a(1-\\cos t)$의 길이는?",
    options: [o("1","$8a$"),o("2","$4a$"),o("3","$16a$"),o("4","$2\\pi a$"),o("5","$\\pi a$")],
    answer: "1",
    explanation: "$\\sqrt{(x')^2+(y')^2}=2a\\sin(t/2)$. $L=2a\\int_0^{2\\pi}\\sin(t/2)dt=8a$." }),
  build({ testNo: 33, num: 5, unit: "극좌표와 응용", concept: "사이클로이드 넓이", difficulty: "easyMedium",
    question: "$x=r(\\theta-\\sin\\theta), y=r(1-\\cos\\theta)$로 정의된 사이클로이드의 $0\\le\\theta\\le 2\\pi$ 부분과 $x$축으로 둘러싸인 영역의 넓이는?",
    options: [o("1","$3\\pi r^2$"),o("2","$2\\pi r^2$"),o("3","$\\pi r^2$"),o("4","$6\\pi r^2$"),o("5","$\\pi r$")],
    answer: "1",
    explanation: "$A=\\int_0^{2\\pi}r(1-\\cos\\theta)\\cdot r(1-\\cos\\theta)d\\theta=r^2\\int_0^{2\\pi}(1-\\cos\\theta)^2 d\\theta=3\\pi r^2$." }),
  build({ testNo: 33, num: 6, unit: "극좌표와 응용", concept: "별모양 곡선 길이", difficulty: "easyMedium",
    question: "방정식 $x^{2/3}+y^{2/3}=1$의 그래프(아스트로이드)의 총 길이는?",
    options: [o("1","$6$"),o("2","$8$"),o("3","$4$"),o("4","$3\\pi$"),o("5","$2\\pi$")],
    answer: "1",
    explanation: "$x=\\cos^3\\theta, y=\\sin^3\\theta$. $L=\\int_0^{2\\pi}3|\\sin\\theta\\cos\\theta|d\\theta=4\\cdot\\int_0^{\\pi/2}3\\sin\\theta\\cos\\theta\\,d\\theta=6$." }),

  // ========== DT34 ==========
  build({ testNo: 34, num: 1, unit: "극좌표와 응용", concept: "극방정식 원", difficulty: "easyMedium",
    question: "다음 원의 방정식 중 반지름이 가장 작은 것은?",
    options: [o("1","$r=-1$"),o("2","$x^2+y^2=1$"),o("3","$r=3\\sin\\dfrac{\\theta}{2}\\cos\\dfrac{\\theta}{2}$"),o("4","$r=-2\\cos\\theta$"),o("5","모두 같음")],
    answer: "3",
    explanation: "①반지름 1 ②반지름 1 ③$r=\\dfrac{3}{2}\\sin\\theta$ → 반지름 3/4 ④반지름 1. 가장 작은 것 ③ (3/4)." }),
  build({ testNo: 34, num: 2, unit: "극좌표와 응용", concept: "극방정식 교점", difficulty: "easyMedium",
    question: "$xy$ 평면에 두 극방정식 $r=2\\cos\\theta$와 $r=\\theta$의 그래프가 만나는 점의 개수는?",
    options: [o("1","$1$"),o("2","$2$"),o("3","$3$"),o("4","$0$"),o("5","무한히 많다")],
    answer: "2",
    explanation: "그래프: 원과 나선이 2개 점에서 만남." }),
  build({ testNo: 34, num: 3, unit: "극좌표와 응용", concept: "극곡선 접선", difficulty: "easyMedium",
    question: "극좌표 $r=1+\\cos\\theta$로 표시되는 곡선이 있다. $\\theta=\\pi/6$에서 접선의 기울기는?",
    options: [o("1","$-1$"),o("2","$1$"),o("3","$\\sqrt{3}$"),o("4","$\\dfrac{1}{\\sqrt{3}}$"),o("5","$0$")],
    answer: "1",
    explanation: "$\\dfrac{dy}{dx}=\\dfrac{r'\\sin\\theta+r\\cos\\theta}{r'\\cos\\theta-r\\sin\\theta}\\Big|_{\\pi/6}$. 계산: $=-1$." }),
  build({ testNo: 34, num: 4, unit: "극좌표와 응용", concept: "극곡선 접선", difficulty: "easyMedium",
    question: "극좌표 $(r,\\theta)$에 대하여 $r=\\tan\\theta$로 나타나는 곡선 위의 점 $\\theta=\\pi/6$에서 접선의 방정식은?",
    options: [o("1","$7x-3\\sqrt{3}y=2$"),o("2","$7x+3\\sqrt{3}y=2$"),o("3","$x-y=1$"),o("4","$y=x$"),o("5","$y=2x$")],
    answer: "1",
    explanation: "복잡한 계산 후 직선 방정식: $7x-3\\sqrt{3}y=2$." }),
  build({ testNo: 34, num: 5, unit: "극좌표와 응용", concept: "극곡선 동경각", difficulty: "easyMedium",
    question: "극곡선 $r=2\\sin\\theta$ 위에서 동경과 접선 사이의 각이 $\\pi/6$인 점의 극좌표는?",
    options: [o("1","$(1, \\pi/6)$"),o("2","$(2, \\pi/3)$"),o("3","$(\\sqrt{2}, \\pi/4)$"),o("4","$(1, \\pi/3)$"),o("5","$(2, \\pi/6)$")],
    answer: "1",
    explanation: "$\\tan\\phi=\\dfrac{r}{r'}=\\dfrac{2\\sin\\theta}{2\\cos\\theta}=\\tan\\theta$. $\\phi=\\theta=\\pi/6$. $r=2\\sin(\\pi/6)=1$. $(1, \\pi/6)$." }),
  build({ testNo: 34, num: 6, unit: "극좌표와 응용", concept: "극곡선 넓이", difficulty: "easyMedium",
    question: "극곡선 $r=\\sqrt{1+\\cos\\theta}$로 둘러싸인 영역의 넓이는?",
    options: [o("1","$\\pi$"),o("2","$2\\pi$"),o("3","$\\dfrac{\\pi}{2}$"),o("4","$\\dfrac{3\\pi}{2}$"),o("5","$3\\pi$")],
    answer: "1",
    explanation: "$A=\\dfrac{1}{2}\\int_0^{2\\pi}(1+\\cos\\theta)d\\theta=\\dfrac{1}{2}\\cdot 2\\pi=\\pi$." }),

  // ========== DT35 ==========
  build({ testNo: 35, num: 1, unit: "극좌표와 응용", concept: "극곡선 넓이", difficulty: "easyMedium",
    question: "극곡선 $r=2\\cos\\theta+3$으로 둘러싸인 영역의 넓이는?",
    options: [o("1","$11\\pi$"),o("2","$9\\pi$"),o("3","$13\\pi$"),o("4","$\\pi$"),o("5","$3\\pi$")],
    answer: "1",
    explanation: "$A=\\dfrac{1}{2}\\int_0^{2\\pi}(2\\cos\\theta+3)^2 d\\theta=\\dfrac{1}{2}(4\\pi+18\\pi)=11\\pi$." }),
  build({ testNo: 35, num: 2, unit: "극좌표와 응용", concept: "극곡선 넓이", difficulty: "easyMedium",
    question: "극방정식 $r=1-2\\sin\\theta$의 내부곡선과 외부곡선으로 둘러싸인 부분의 면적은?",
    options: [o("1","$\\pi+3\\sqrt{3}$"),o("2","$\\pi-3\\sqrt{3}$"),o("3","$2\\pi$"),o("4","$3\\sqrt{3}$"),o("5","$\\pi$")],
    answer: "1",
    explanation: "리마송 (limaçon) 영역. 적분으로 $\\pi+3\\sqrt{3}$." }),
  build({ testNo: 35, num: 3, unit: "극좌표와 응용", concept: "극곡선 넓이", difficulty: "easyMedium",
    question: "극방정식 $r=4\\cos\\theta$의 내부와 $r=2$의 외부로 이루어진 부분의 면적은?",
    options: [o("1","$\\dfrac{4\\pi}{3}+2\\sqrt{3}$"),o("2","$\\dfrac{2\\pi}{3}+\\sqrt{3}$"),o("3","$\\dfrac{4\\pi}{3}$"),o("4","$2\\sqrt{3}$"),o("5","$\\pi+\\sqrt{3}$")],
    answer: "1",
    explanation: "교점 $\\cos\\theta=1/2$. 적분 후 $\\dfrac{4\\pi}{3}+2\\sqrt{3}$." }),
  build({ testNo: 35, num: 4, unit: "극좌표와 응용", concept: "극곡선 넓이", difficulty: "easyMedium",
    question: "$r=2-2\\cos\\theta$의 외부와 $r=2$의 내부의 공통부분의 면적은?",
    options: [o("1","$8-\\pi$"),o("2","$8+\\pi$"),o("3","$\\pi-8$"),o("4","$\\pi$"),o("5","$4-\\pi$")],
    answer: "1",
    explanation: "원 $r=2$ 내부에서 카디오이드 $r=2-2\\cos\\theta$를 뺀 영역. $A=2\\pi-(8-\\pi)=\\dots$. 답안 따라 $8-\\pi$." }),
  build({ testNo: 35, num: 5, unit: "극좌표와 응용", concept: "극곡선 길이", difficulty: "easyMedium",
    question: "구간 $-\\pi/4\\le\\theta\\le\\pi/4$에서 극방정식 $r=2\\sec\\theta$의 호의 길이는?",
    options: [o("1","$4$"),o("2","$2\\pi$"),o("3","$\\sqrt{2}$"),o("4","$\\pi$"),o("5","$2$")],
    answer: "1",
    explanation: "$r=2\\sec\\theta$는 직선 $x=2$. $\\theta=\\pm\\pi/4$에서 $y=\\pm 2$. 길이 $=4$." }),
  build({ testNo: 35, num: 6, unit: "극좌표와 응용", concept: "극곡선 길이", difficulty: "easyMedium",
    question: "극방정식 $r=\\theta^2$ ($0\\le\\theta\\le 1$)의 곡선의 길이는?",
    options: [o("1","$\\dfrac{1}{3}(5\\sqrt{5}-8)$"),o("2","$\\dfrac{2}{3}(5\\sqrt{5}-1)$"),o("3","$\\dfrac{1}{3}(5\\sqrt{5}+8)$"),o("4","$\\dfrac{5\\sqrt{5}}{3}$"),o("5","$\\sqrt{5}$")],
    answer: "1",
    explanation: "$L=\\int_0^1\\sqrt{r^2+(r')^2}\\,d\\theta=\\int_0^1\\theta\\sqrt{\\theta^2+4}\\,d\\theta=\\dfrac{1}{3}[(\\theta^2+4)^{3/2}]_0^1=\\dfrac{1}{3}(5\\sqrt{5}-8)$." })
];

console.log(`Inserting ${problems.length} 적분학 daily-test problems (DT11~DT35)...`);
const { error } = await supabase.from("questions").insert(problems);
if (error) { console.error("Insert error:", error); process.exit(1); }
console.log(`Done. ${problems.length} inserted.`);
const byTest = {};
for (const p of problems) {
  const m = p.id.match(/^q-daily-int-r(\d+)/);
  const k = m ? `DT${m[1]}` : "?";
  byTest[k] = (byTest[k] || 0) + 1;
}
console.log("By test:", byTest);
