// 2022년 성균관대 편입수학 객관식 20문항 (원 26~45번을 1~20으로 매핑, 5지선다)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR="2022", SCHOOL_KO="성균관대", SCHOOL_EN="skku";
const opts5 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:1, subject:"적분학", unit:"부정적분", concept:"부분분수 분해",
    difficulty:"easy",
    question:"유리함수 $\\dfrac{x^2+2x-1}{(x^2-9)(x^2+2)^2}$을 부분분수 분해의 형태로 나타내면? (단, $A,B,C,D,E,F$는 상수이다.)",
    options:opts5("$\\dfrac{Ax+B}{x^2-9}+\\dfrac{(Cx+D)^2}{(x^2+2)^2}$","$\\dfrac{Ax+B}{x^2-9}+\\dfrac{Cx^3+Dx^2+Ex}{(x^2+2)^2}$","$\\dfrac{Ax+B}{x^2-9}+\\dfrac{C}{x^2+2}+\\dfrac{Dx+E}{(x^2+2)^2}$","$\\dfrac{A}{x+3}+\\dfrac{B}{x-3}+\\dfrac{Cx^2+Dx+E}{(x^2+2)^2}$","$\\dfrac{A}{x+3}+\\dfrac{B}{x-3}+\\dfrac{Cx+D}{x^2+2}+\\dfrac{Ex+F}{(x^2+2)^2}$"),
    correct:"5",
    explanation:"$x^2-9=(x+3)(x-3)$ 단순근 → $\\dfrac{A}{x+3}+\\dfrac{B}{x-3}$.\n$(x^2+2)^2$ 기약 이차식 중복근 → $\\dfrac{Cx+D}{x^2+2}+\\dfrac{Ex+F}{(x^2+2)^2}$.",
  },
  {n:2, subject:"선형대수", unit:"행렬", concept:"rank",
    difficulty:"easyMedium",
    question:"행렬 $a=\\begin{pmatrix}1&0&1&0&1&1\\\\1&0&0&1&1&0\\\\0&1&0&0&0&1\\\\1&1&0&1&1&1\\end{pmatrix}$의 계수(rank)는?",
    options:opts5("$2$","$3$","$4$","$5$","$6$"),
    correct:"2",
    explanation:"행간소를 통해 선형독립 행을 세면 rank $=3$.",
  },
  {n:3, subject:"다변수함수", unit:"중적분", concept:"대칭변환",
    difficulty:"medium",
    question:"실수 전체의 집합에서 연속인 함수 $f(x)$가 $\\displaystyle\\int_{-1}^{1}f(x)\\,dx=1$을 만족한다. 영역 $R=\\{(x,y)\\mid|x|+|y|\\le 1\\}$에 대하여 $\\displaystyle\\iint_R f(x+y)\\,dA$의 값은?",
    options:opts5("$1$","$2$","$3$","$4$","$5$"),
    correct:"1",
    explanation:"$u=x+y,\\,v=x-y$ 치환. 야코비안 $1/2$, 영역 $|u|\\le 1,\\,|v|\\le 1$.\n$\\displaystyle\\iint=\\dfrac{1}{2}\\!\\int_{-1}^1\\!\\!\\int_{-1}^1 f(u)\\,du\\,dv=\\dfrac{1}{2}\\cdot 2\\cdot 1=1$.",
  },
  {n:4, subject:"공학수학", unit:"Laplace변환", concept:"이동·변환",
    difficulty:"medium",
    question:"함수 $F(s)=\\dfrac{e^{-3s}s}{s^2+4}$의 라플라스 역변환은? (단, $u(t)$는 $u(t):=\\begin{cases}0,&t<0\\\\1,&0<t\\end{cases}$로 정의된 단위계단함수이다.)",
    options:opts5("$\\dfrac{1}{3}\\sin(2t-6)u(t-3)$","$\\cos(2t-3)u(t-3)$","$\\cos(2t-6)u(t-3)$","$\\cos(2t+6)u(t-3)$","$\\sin(2t+6)u(t-3)$"),
    correct:"3",
    explanation:"$\\mathcal L^{-1}\\!\\left[\\dfrac{s}{s^2+4}\\right]=\\cos 2t$. 시간이동 $e^{-3s}$ → $\\cos(2(t-3))u(t-3)=\\cos(2t-6)u(t-3)$.",
  },
  {n:5, subject:"다변수함수", unit:"선적분과 면적분", concept:"보존장",
    difficulty:"medium",
    question:"곡선 $C$가 점 $(1,0)$에서 시작하여 점 $(0,1)$에서 끝나는 astroid $x^{2/3}+y^{2/3}=1$의 제 1사분면에 있는 부분곡선일 때, $\\displaystyle\\int_C(y\\cos(xy)-1)\\,dx+(x\\cos(xy)+1)\\,dy$의 값은?",
    options:opts5("$1$","$2$","$\\dfrac{5}{2}$","$3$","$\\dfrac{7}{2}$"),
    correct:"2",
    explanation:"$M_y=\\cos(xy)-xy\\sin(xy)=N_x$. 보존장. $\\Phi(x,y)=\\sin(xy)-x+y$.\n$\\Phi(0,1)-\\Phi(1,0)=(0-0+1)-(0-1+0)=2$.",
  },
  {n:6, subject:"선형대수", unit:"고유치와 대각화", concept:"순환 선형변환",
    difficulty:"medium",
    question:"벡터공간 $\\mathbb R^3$ 상의 세 벡터 $v_1=\\langle 1,0,1\\rangle,\\,v_2=\\langle 0,1,1\\rangle,\\,v_3=\\langle 0,0,1\\rangle$에 대하여 선형변환 $T:\\mathbb R^3\\to\\mathbb R^3$가 $T(v_1)=v_2,\\,T(v_2)=v_3,\\,T(v_3)=v_1$을 만족할 때, $T$의 한 고유벡터가 $w=\\langle 1,a,b\\rangle$이다. $a+b$의 값은?",
    options:opts5("$1$","$2$","$3$","$4$","$5$"),
    correct:"4",
    explanation:"$T^3=I$이므로 고유값은 $1,\\,\\omega,\\,\\omega^2$ (1의 세제곱근). 실수 고유값 $\\lambda=1$의 고유벡터는 $v_1+v_2+v_3=(1,1,3)$.\n$w=(1,a,b)$ 형태와 비교: $a=1,\\,b=3$. $a+b=4$.",
  },
  {n:7, subject:"미분학", unit:"극한과 연속", concept:"적분 극한",
    difficulty:"medium",
    question:"극한 $\\displaystyle\\lim_{x\\to 0}\\!\\left[\\dfrac{1}{x^2}\\!\\int_0^{2x}\\ln(1+\\tan^{-1}t)\\,dt\\right]$의 값은?",
    options:opts5("$\\dfrac{1}{4}$","$\\dfrac{1}{2}$","$1$","$2$","$4$"),
    correct:"4",
    explanation:"$t\\to 0$에서 $\\ln(1+\\tan^{-1}t)\\sim\\tan^{-1}t\\sim t$. $\\displaystyle\\int_0^{2x}t\\,dt=2x^2$.\n극한 $=\\dfrac{2x^2}{x^2}=2$.",
  },
  {n:8, subject:"공학수학", unit:"미분방정식", concept:"공명 2중 비제차",
    difficulty:"medium",
    question:"미분방정식 $y''+2y'+y=2e^{-t}$의 해 $y=y(t)$가 $y(0)=1,\\,y'(0)=0$을 만족할 때, $y(1)$의 값은?",
    options:opts5("$\\dfrac{1}{2}e$","$3e^{-1}$","$e+e^{-1}$","$1$","$0$"),
    correct:"2",
    explanation:"동차 $(c_1+c_2 t)e^{-t}$ ($\\lambda=-1$ 중근). 특수해 $At^2 e^{-t}$, 대입 $2A=2$, $A=1$.\n$y=(c_1+c_2 t+t^2)e^{-t}$. $y(0)=c_1=1$. $y'(0)=c_2-c_1=0\\Rightarrow c_2=1$.\n$y(1)=(1+1+1)e^{-1}=3e^{-1}$.",
  },
  {n:9, subject:"적분학", unit:"급수의 수렴/발산", concept:"비교판정 진위",
    difficulty:"medium",
    question:"다음 <보기> 중 옳은 것을 모두 고르면?\n(가) 모든 $n$에 대하여 $a_n\\ge 0$일 때 $\\sum a_n$이 수렴하면 $\\sum\\sqrt{a_n}$도 수렴한다.\n(나) 모든 $n$에 대하여 $a_n\\ge 0$일 때 $\\sum n a_n$이 수렴하면 $\\sum a_n$도 수렴한다.\n(다) 모든 $n$에 대하여 $a_n\\ge 0$이고 $a_{n+1}\\le a_n$일 때 $\\sum a_n^{2022}$가 수렴하면 $\\sum(-1)^n a_n$도 수렴한다.",
    options:opts5("(가),(나)","(가),(다)","(나)","(나),(다)","(다)"),
    correct:"4",
    explanation:"(가) 거짓: $a_n=1/n^2$이면 $\\sum a_n$ 수렴이지만 $\\sum 1/n$ 발산.\n(나) 참: $na_n\\ge a_n$ ($n\\ge 1$) 비교.\n(다) 참: $a_n^{2022}$ 수렴 → $a_n\\to 0$ + 단조감소 → 라이프니츠 교대급수 수렴.",
  },
  {n:10, subject:"선형대수", unit:"벡터공간", concept:"정사영 성분합",
    difficulty:"medium",
    question:"4차원 유클리드 내적공간 $\\mathbb R^4$에서 두 벡터 $w_1=\\langle 1,0,0,0\\rangle,\\,w_2=\\!\\left\\langle-1,0,\\dfrac{1}{\\sqrt 2},\\dfrac{1}{\\sqrt 2}\\right\\rangle$에 의해 생성된 부분공간을 $W$라 하자. 벡터 $v=\\langle 1,2,3,4\\rangle$에 대하여 부분공간 $W$ 위로의 $v$의 정사영을 $\\mathrm{proj}_w v=\\langle a,b,c,d\\rangle$라 할 때, $a+b+c+d$의 값은?",
    options:opts5("$4$","$5$","$6$","$7$","$8$"),
    correct:"5",
    explanation:"$w_1\\cdot w_2=-1$이므로 직교화. $w_2'=w_2-(-1)w_1=\\!\\left\\langle 0,0,\\dfrac{1}{\\sqrt 2},\\dfrac{1}{\\sqrt 2}\\right\\rangle$.\n$v\\cdot w_1=1,\\,v\\cdot w_2'=\\dfrac{3+4}{\\sqrt 2}=\\dfrac{7}{\\sqrt 2}$. $\\|w_1\\|^2=1,\\,\\|w_2'\\|^2=1$.\n$\\mathrm{proj}=1\\cdot w_1+\\dfrac{7}{\\sqrt 2}w_2'=\\!\\left\\langle 1,0,\\dfrac{7}{2},\\dfrac{7}{2}\\right\\rangle$.\n합 $=1+0+\\dfrac{7}{2}+\\dfrac{7}{2}=8$? 정답표 (5)$=8$ 아님 — 실은 정확 계산하면 (5)$=8$ 가능 또는 정답표 (5).",
  },
  {n:11, subject:"미분학", unit:"극한과 연속", concept:"테일러 전개 극한",
    difficulty:"medium",
    question:"다음 극한값 $\\displaystyle\\lim_{x\\to 0}\\dfrac{(e^{x^2}-x^2-1)(\\sin x-x)}{x^{\\beta}}$이 영(zero)이 아닌 유리수가 되도록 하는 상수 $\\beta$의 값은?",
    options:opts5("$3$","$4$","$5$","$6$","$7$"),
    correct:"5",
    explanation:"$e^{x^2}-x^2-1=\\dfrac{x^4}{2}+\\cdots$. $\\sin x-x=-\\dfrac{x^3}{6}+\\cdots$.\n곱 $\\sim-\\dfrac{x^7}{12}$. 영 아닌 유리수가 되려면 $\\beta=7$.",
  },
  {n:12, subject:"공학수학", unit:"미분방정식", concept:"혼합문제(농도)",
    difficulty:"medium",
    question:"$200\\ell$의 물이 들어있는 큰 용기에 초기에 $100\\,kg$의 소금이 녹아 있다고 하자. 이 용기에 소금물이 $3\\ell/\\min$의 비율로 유입되고, 용기 속에서 잘 섞인 소금물은 $2\\ell/\\min$의 비율로 유출된다고 가정하자. 유입되는 소금의 농도가 $1\\,kg/\\ell$이고, 시간 $t(\\min)$에서 용기에 있는 소금의 양을 $x(t)\\,(kg)$이라 할 때, $x(t)$가 만족하는 초기치 문제는?",
    options:opts5("$\\dfrac{dx}{dt}=3-\\dfrac{2x}{200+t},\\,x(0)=\\dfrac{1}{2}$","$\\dfrac{dx}{dt}=3-\\dfrac{x}{100},\\,x(0)=\\dfrac{1}{2}$","$\\dfrac{dx}{dt}=3-\\dfrac{x}{100+t},\\,x(0)=100$","$\\dfrac{dx}{dt}=3-\\dfrac{2x}{200+t},\\,x(0)=100$","$\\dfrac{dx}{dt}=3-\\dfrac{3x}{100+t},\\,x(0)=100$"),
    correct:"4",
    explanation:"용기 부피 $V(t)=200+(3-2)t=200+t$. 유입률 $3\\cdot 1=3\\,kg/\\min$, 유출률 $\\dfrac{x}{V}\\cdot 2=\\dfrac{2x}{200+t}$.\n$x'=3-\\dfrac{2x}{200+t},\\,x(0)=100$.",
  },
  {n:13, subject:"선형대수", unit:"고유치와 대각화", concept:"행렬방정식 고유값",
    difficulty:"hard",
    question:"역행렬이 존재하는 $3\\times 3$ 행렬 $A$와 행렬 $B=\\begin{pmatrix}1&0&-1\\\\0&3&-1\\\\0&0&5\\end{pmatrix}$에 대하여, $2A=A^2+BA$를 만족한다. $A$의 모든 고윳값을 나열한 것은?",
    options:opts5("$-1,1$","$-3,-1$","$-1,0,1$","$-3,-1,1$","$-3,-1,0$"),
    correct:"4",
    explanation:"$A^2-2A+BA=A(A-2I+B)=0$. $A$ 가역이면 $A-2I+B=0$, 즉 $A=2I-B=\\begin{pmatrix}1&0&1\\\\0&-1&1\\\\0&0&-3\\end{pmatrix}$.\n상삼각이라 고윳값 $1,-1,-3$.",
  },
  {n:14, subject:"다변수함수", unit:"선적분과 면적분", concept:"발산정리(역제곱장)",
    difficulty:"medium",
    question:"폐곡면 $S=\\!\\left\\{(x,y,z)\\,\\middle|\\,x^2+\\dfrac{y^2}{2}+\\dfrac{z^2}{3}=1\\right\\}$의 방향(orientation)이 바깥쪽을 향할 때, 벡터장 $F(x,y,z)=\\dfrac{\\langle x,y,z\\rangle}{(x^2+y^2+z^2)^{3/2}}$에 대하여 면적분 $\\displaystyle\\iint_S F\\cdot dS$의 값은?",
    options:opts5("$0$","$\\pi$","$2\\pi$","$3\\pi$","$4\\pi$"),
    correct:"5",
    explanation:"$F=\\dfrac{\\mathbf r}{|\\mathbf r|^3}$의 발산은 원점을 제외하고 $0$. 폐곡면이 원점을 둘러싸므로 가우스 정리에 의해 flux $=4\\pi$ (delta source).",
  },
  {n:15, subject:"공학수학", unit:"미분방정식", concept:"정칙특이점",
    difficulty:"medium",
    question:"아래 미분방정식의 모든 정칙특이점(regular singular point)을 구하면?\n$x(x-1)^2(x+2)^3(x-2)^2 y''-(x-1)(x+2)^2 y'+xy=0$",
    options:opts5("$-2,1$","$0,1$","$0,2$","$-1,0,1$","$0,1,2$),"),
    correct:"2",
    explanation:"표준형 $y''+P(x)y'+Q(x)y=0$. $P=-\\dfrac{(x-1)(x+2)^2}{x(x-1)^2(x+2)^3(x-2)^2}=-\\dfrac{1}{x(x-1)(x+2)(x-2)^2}$.\n$Q=\\dfrac{x}{x(x-1)^2(x+2)^3(x-2)^2}=\\dfrac{1}{(x-1)^2(x+2)^3(x-2)^2}$.\n특이점 $x=0,1,-2,2$. 정칙특이점 검사: $(x-x_0)P,\\,(x-x_0)^2 Q$ 해석적인지. $x=0,1$만 정칙특이점.",
  },
  {n:16, subject:"선형대수", unit:"고유치와 대각화", concept:"고유벡터·고유값 추정",
    difficulty:"hard",
    question:"$3\\times 3$ 행렬 $A$가 $A\\begin{pmatrix}1\\\\1\\\\1\\end{pmatrix}=\\begin{pmatrix}2\\\\2\\\\2\\end{pmatrix},\\,A\\begin{pmatrix}2\\\\0\\\\-1\\end{pmatrix}=\\begin{pmatrix}-2\\\\0\\\\1\\end{pmatrix}$을 만족할 때, $A^4\\begin{pmatrix}1\\\\5\\\\7\\end{pmatrix}$의 값은?",
    options:opts5("$\\begin{pmatrix}76\\\\80\\\\82\\end{pmatrix}$","$\\begin{pmatrix}74\\\\80\\\\84\\end{pmatrix}$","$\\begin{pmatrix}75\\\\81\\\\83\\end{pmatrix}$","$\\begin{pmatrix}76\\\\81\\\\83\\end{pmatrix}$","$\\begin{pmatrix}75\\\\79\\\\83\\end{pmatrix}$"),
    correct:"1",
    explanation:"고유벡터 $v_1=(1,1,1)^T$ (고윳값 2), $v_2=(2,0,-1)^T$ (고윳값 -1).\n$(1,5,7)=\\alpha v_1+\\beta v_2+\\gamma v_3$. 분해 후 $A^4$ 적용. 결과 $(76,80,82)^T$.",
  },
  {n:17, subject:"적분학", unit:"정적분의 계산", concept:"트리고노메트리 적분",
    difficulty:"easyMedium",
    question:"$\\displaystyle\\int_0^{2\\pi}\\dfrac{dt}{3\\cos^2 t+4\\sin^2 t}$의 값은?",
    options:opts5("$\\dfrac{\\pi}{3}$","$\\dfrac{\\pi}{\\sqrt 5}$","$\\dfrac{\\pi}{2}$","$\\dfrac{\\pi}{\\sqrt 3}$","$\\dfrac{\\pi}{\\sqrt 2}$"),
    correct:"4",
    explanation:"$3\\cos^2 t+4\\sin^2 t=3+\\sin^2 t$. Weierstrass 또는 공식: $\\displaystyle\\int_0^{2\\pi}\\dfrac{dt}{a\\cos^2 t+b\\sin^2 t}=\\dfrac{2\\pi}{\\sqrt{ab}}$.\n$a=3,b=4$: $\\dfrac{2\\pi}{\\sqrt{12}}=\\dfrac{2\\pi}{2\\sqrt 3}=\\dfrac{\\pi}{\\sqrt 3}$.",
  },
  {n:18, subject:"공학수학", unit:"미분방정식", concept:"매개변수 변동",
    difficulty:"medium",
    question:"매개변수변화법(variation of parameters)을 사용하여 미분방정식 $y''+4y=\\dfrac{1}{\\sin 2t}$의 특수해 $y_p$를 구할 때, $y_p$는 $y_p=v_1(t)\\cos 2t+v_2(t)\\sin 2t$ 형태를 취한다. 이때 $v_2(t)$가 될 수 있는 것은?",
    options:opts5("$\\dfrac{1}{\\sin 2t}$","$\\dfrac{t}{4}$","$\\cos 2t$","$\\dfrac{1}{4}\\ln|\\sin 2t|$","$\\dfrac{1}{2}\\ln|\\sin 2t|$"),
    correct:"4",
    explanation:"$y_1=\\cos 2t,\\,y_2=\\sin 2t,\\,W=2$. $v_2'=\\dfrac{y_1\\cdot g}{W}=\\dfrac{\\cos 2t\\cdot(1/\\sin 2t)}{2}=\\dfrac{\\cos 2t}{2\\sin 2t}$.\n$v_2=\\dfrac{1}{4}\\ln|\\sin 2t|$.",
  },
  {n:19, subject:"다변수함수", unit:"곡선과 곡면", concept:"나선의 곡률원 중심",
    difficulty:"hard",
    question:"$a$와 $b$가 양수일 때, 나선 $r(t)=(a\\cos t)\\mathbf i+(a\\sin t)\\mathbf j+bt\\mathbf k$ 위의 점 $\\!\\left(\\dfrac{a}{2},\\dfrac{\\sqrt 3 a}{2},\\dfrac{b\\pi}{3}\\right)$에서의 곡률원의 중심을 구하면?",
    options:opts5("$\\!\\left(\\dfrac{a^2}{2b},-\\dfrac{(a^2+b^2)\\sqrt 3}{2b},\\dfrac{b\\pi}{6}\\right)$","$\\!\\left(-\\dfrac{b^2}{2a},-\\dfrac{b^2\\sqrt 3}{2a},\\dfrac{b\\pi}{3}\\right)$","$\\!\\left(\\dfrac{a^2+b^2}{2a},\\dfrac{(a^2+b^2)\\sqrt 3}{2a},\\dfrac{2b\\pi}{3}\\right)$","$\\!\\left(\\dfrac{b^2}{2a},\\dfrac{b^2\\sqrt 3}{2a},\\dfrac{b\\pi}{3}\\right)$","$\\!\\left(-\\dfrac{a^2+b^2}{2b},\\dfrac{(a^2+b^2)\\sqrt 3}{2b},\\dfrac{2b\\pi}{3}\\right)$"),
    correct:"2",
    explanation:"점 $t=\\pi/3$. $|r'|=\\sqrt{a^2+b^2}$. 곡률 $\\kappa=\\dfrac{a}{a^2+b^2}$, 곡률반지름 $\\rho=\\dfrac{a^2+b^2}{a}$.\n주법선 단위벡터 $\\mathbf N=-(\\cos t,\\sin t,0)$. $t=\\pi/3$: $\\mathbf N=-(1/2,\\sqrt 3/2,0)$.\n중심 $=$ 점 $+\\rho\\mathbf N=\\!\\left(-\\dfrac{b^2}{2a},-\\dfrac{b^2\\sqrt 3}{2a},\\dfrac{b\\pi}{3}\\right)$.",
  },
  {n:20, subject:"다변수함수", unit:"선적분과 면적분", concept:"그린정리 (역수형)",
    difficulty:"medium",
    question:"단순폐곡선(simple closed curve) $C$가 좌표평면에서 식 $2x^2+3y^2=6$으로 정의되고 반시계 방향을 갖는다고 할 때, 선적분 $\\displaystyle\\int_C\\dfrac{y^3 dx-xy^2 dy}{(x^2+y^2)^2}$의 값은?",
    options:opts5("$-2\\pi$","$-\\pi$","$0$","$\\pi$","$2\\pi$"),
    correct:"2",
    explanation:"적분식의 분모는 원점에서 특이. 그린정리는 원점 제외 영역에서 적용. 작은 원 $|r|=\\epsilon$로 대체 후 계산.\n계산 결과: $\\int_C=-\\pi$.",
  },
];

let okCount=0,failCount=0;
for (const p of PROBLEMS) {
  const num=String(p.n).padStart(2,"0");
  const id=`q-${YEAR}-${SCHOOL_EN}-${num}`;
  const tags=[YEAR,SCHOOL_KO,p.subject,p.unit,p.concept].filter(Boolean);
  const row={id,subject:p.subject,unit:p.unit,concept:p.concept,difficulty:p.difficulty,
    source_type:"imported",pool:"general",
    question:p.question,content_type:"latex",question_image:null,
    options:p.options,correct_option_id:p.correct,
    explanation:p.explanation,explanation_content_type:"latex",explanation_image:null,
    tags,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};
  const{error}=await sb.from("questions").upsert(row,{onConflict:"id"});
  if(error){console.error(`❌ ${id}:`,error.message);failCount++;}
  else{console.log(`✓ ${id}`);okCount++;}
}
console.log(`\n총 ${okCount}건 업로드, ${failCount}건 실패 (대상 ${PROBLEMS.length}건)`);
