// 2019년 단국대 편입수학 객관식 20문항 (4지선다, 문항 번호 31~50, 단일 시험)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR_ID="2019", YEAR_KO="2019", SCHOOL_KO="단국대", SCHOOL_EN="dankook";
const opts4 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:31, subject:"미분학", unit:"도함수", concept:"접선 y절편",
    difficulty:"easy",
    question:"곡선 $y=\\tan\\!\\left(\\dfrac{\\pi x^2}{4}\\right)$ 위의 점 $(1,1)$에서의 접선의 $y$절편은?",
    options:opts4("$-\\pi-1$","$-\\pi$","$-\\pi+1$","$-\\pi+2$"),
    correct:"3",
    explanation:"$y'=\\sec^2(\\pi x^2/4)\\cdot(\\pi x/2)|_{x=1}=2\\cdot\\pi/2=\\pi$.\n접선: $y-1=\\pi(x-1)\\Rightarrow y=\\pi x-\\pi+1$. $x=0$: $y=-\\pi+1$.",
  },
  {n:32, subject:"적분학", unit:"부정적분", concept:"치환 + 부분적분",
    difficulty:"easy",
    question:"$\\displaystyle\\int_1^e(\\ln x)^2\\,dx$의 값은?",
    options:opts4("$e-2$","$e-\\dfrac{3}{2}$","$e-1$","$e-\\dfrac{1}{2}$"),
    correct:"1",
    explanation:"$\\ln x=t$ 치환: $x=e^t,\\,dx=e^t dt$, 구간 $0\\to 1$.\n$\\!\\int_0^1 t^2 e^t\\,dt=[t^2 e^t-2te^t+2e^t]_0^1=e-2$.",
  },
  {n:33, subject:"미분학", unit:"극한과 연속", concept:"진위판단 (4보기)",
    difficulty:"medium",
    question:"다음의 설명 중 옳은 것의 개수는? (단, $[x]$는 $x$보다 크지 않은 최대의 정수이다.)\n\nㄱ. 직선 $y=2x+3$은 곡선 $y=\\dfrac{-2x^3-3x^2+x+5}{1-x^2}$의 경사점근선이다.\nㄴ. 함수 $f$와 $g$가 연속이 아니면 $f+g$ 또는 $fg$는 연속함수가 아니다.\nㄷ. $f(x)=-x^2+x,\\,g(x)=x-[x]$에 대하여 $(f\\circ g)(x)$는 연속함수이다.\nㄹ. 함수 $f(x)=3x-2\\cos x+1$에 대하여 $(f^{-1})'(-1)=\\dfrac{1}{3}$이다.",
    options:opts4("$1$개","$2$개","$3$개","$4$개"),
    correct:"3",
    explanation:"ㄱ [참] 사점근선 검증.\nㄴ [거짓] 반례: $f,g$ 모두 불연속이지만 $f+g,\\,fg$ 연속 가능.\nㄷ [참] $g$의 점프 불연속점에서 $f$가 합성으로 연속.\nㄹ [참] $f^{-1}(-1)$ 계산 후 $1/f'$ 적용.\n참 3개.",
  },
  {n:34, subject:"적분학", unit:"이상적분", concept:"이상적분 + 미정 상수",
    difficulty:"medium",
    question:"두 실수 $a,k$가 $a=\\displaystyle\\int_0^{\\infty}\\!\\left(\\dfrac{1}{\\sqrt{x^2+4}}-\\dfrac{k}{x+2}\\right)dx$를 만족시킬 때 $a\\times k$의 값은?",
    options:opts4("$\\ln 2$","$\\ln 3$","$2\\ln 2$","$\\ln 5$"),
    correct:"1",
    explanation:"수렴 조건: 두 항의 무한대 거동 상쇄 → $k=1$.\n$a=[\\ln(x+\\sqrt{x^2+4})-\\ln(x+2)]_0^{\\infty}=\\!\\left[\\ln\\dfrac{x+\\sqrt{x^2+4}}{x+2}\\right]_0^{\\infty}$\n$=0-\\ln\\dfrac{2}{2}\\cdots$. 류갓티비 결과 $a=\\ln 2$.\n$a\\times k=\\ln 2$.",
  },
  {n:35, subject:"다변수함수", unit:"극좌표와 극곡선", concept:"카디오이드 영역 넓이",
    difficulty:"easy",
    question:"심장선 $r=1+\\sin\\theta$로 둘러싸인 영역의 넓이는?",
    options:opts4("$\\dfrac{11\\pi}{8}$","$\\dfrac{3\\pi}{2}$","$\\dfrac{13\\pi}{8}$","$\\dfrac{7\\pi}{4}$"),
    correct:"2",
    explanation:"카디오이드 $r=a(1+\\sin\\theta)$의 면적 $=\\dfrac{3\\pi a^2}{2}$. $a=1$이므로 $\\dfrac{3\\pi}{2}$.",
  },
  {n:36, subject:"적분학", unit:"급수의 수렴/발산", concept:"멱급수 수렴 정수 합",
    difficulty:"medium",
    question:"멱급수 $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{n^n(x-2)^n}{3\\times 7\\times 11\\times\\cdots\\times(4n-1)}$이 수렴하게 되는 모든 정수 $x$의 값의 합은?",
    options:opts4("$6$","$10$","$15$","$21$"),
    correct:"1",
    explanation:"비율판정: $\\dfrac{a_{n+1}}{a_n}=\\!\\left(\\dfrac{n+1}{n}\\right)^n\\cdot\\dfrac{n+1}{4n+3}\\to\\dfrac{e}{4}$.\n수렴반경 $R=4/e\\approx 1.47$. $|x-2|<4/e$ ⇒ $-4/e+2<x<4/e+2$, 즉 약 $0.53<x<3.47$.\n정수 $x=1,2,3$ ⇒ 합 $6$.",
  },
  {n:37, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"평면 + 직선 교점, 두 벡터 사이 각",
    difficulty:"medium",
    question:"세 점 $P_1(2,1,-1),\\,P_2(-1,3,0),\\,P_3(3,2,-5)$는 평면 $\\alpha$ 위에 있고 점 $A(-2,2,-6)$을 지나고 벡터 $\\vec{u}=\\langle 1,1,-2\\rangle$에 평행한 직선이 평면 $\\alpha$와 만나는 점을 $B$라 하자. 두 벡터 $\\vec{BA}$와 $\\overrightarrow{BP_2}$ 사이의 각을 $\\theta$라 할 때 $\\cos\\theta$의 값은?",
    options:opts4("$-\\dfrac{5}{9}\\sqrt{3}$","$-\\dfrac{2}{9}\\sqrt{3}$","$\\dfrac{2}{9}\\sqrt{3}$","$\\dfrac{5}{9}\\sqrt{3}$"),
    correct:"4",
    explanation:"평면 법선 $\\vec{P_1P_2}\\times\\vec{P_1P_3}=(-9,-11,-5)$. 평면식 $9x+11y+5z=24$.\n직선 $r=(t-2,t+2,-2t-6)$. 평면 대입: $t=5$. 교점 $B(3,7,-16)$.\n$\\vec{BA}=(-5,-5,10),\\,\\vec{BP_2}=(-4,-4,16)$.\n$\\cos\\theta=\\dfrac{20+20+160}{5\\sqrt{6}\\cdot 4\\sqrt{18}}=\\dfrac{200}{120\\sqrt{3}}=\\dfrac{5\\sqrt{3}}{9}$.",
  },
  {n:38, subject:"다변수함수", unit:"편미분", concept:"방향도함수",
    difficulty:"easy",
    question:"점 $(2,1,\\pi)$에서 함수 $f(x,y,z)=y^2+x\\cos(yz)$의 벡터 $\\vec{v}=\\langle 2,3,-6\\rangle$ 방향으로의 방향도함수는?",
    options:opts4("$-\\dfrac{6}{7}$","$-\\dfrac{3}{7}$","$\\dfrac{2}{7}$","$\\dfrac{4}{7}$"),
    correct:"4",
    explanation:"$\\nabla f=(\\cos(yz),\\,2y-xz\\sin(yz),\\,-xy\\sin(yz))\\big|_{(2,1,\\pi)}=(-1,2,0)$.\n$\\hat v=(2,3,-6)/7$. $D_{\\hat v}f=\\dfrac{(-1)(2)+(2)(3)+(0)(-6)}{7}=\\dfrac{4}{7}$.",
  },
  {n:39, subject:"다변수함수", unit:"이중적분", concept:"두 포물선 영역 적분",
    difficulty:"medium",
    question:"두 포물선 $y^2=1-x,\\,y^2=1+x$로 둘러싸인 부분 중에서 $y\\ge 0$인 영역을 $R$이라 할 때 이중적분 $\\displaystyle\\iint_R y\\,dA$의 값은?",
    options:opts4("$\\dfrac{1}{4}$","$\\dfrac{1}{2}$","$1$","$2$"),
    correct:"2",
    explanation:"$\\!\\int_0^1\\!\\!\\int_{y^2-1}^{1-y^2}y\\,dx\\,dy=\\!\\int_0^1 y[(1-y^2)-(y^2-1)]dy=\\!\\int_0^1(2y-2y^3)dy=1-\\dfrac{1}{2}=\\dfrac{1}{2}$.",
  },
  {n:40, subject:"다변수함수", unit:"다변수 극값", concept:"극값 합 (미정 상수)",
    difficulty:"medium",
    question:"이변수함수 $f(x,y)=x^4+y^4-4xy+a$의 모든 극값의 합이 $-2$일 때 실수 $a$의 값은?",
    options:opts4("$1$","$\\dfrac{4}{3}$","$\\dfrac{5}{3}$","$2$"),
    correct:"1",
    explanation:"$f_x=4x^3-4y=0,\\,f_y=4y^3-4x=0$. 임계점: $(0,0),(1,1),(-1,-1)$.\n$\\Delta(0,0)<0$ 안장점.\n$\\Delta(1,1)>0,\\,f_{xx}>0$ ⇒ 극소 $-2+a$.\n$\\Delta(-1,-1)>0,\\,f_{xx}>0$ ⇒ 극소 $-2+a$.\n극값 합 $=2(-2+a)=-2\\Rightarrow a=1$.",
  },
  {n:41, subject:"다변수함수", unit:"삼중적분", concept:"피적분함수 양수 조건 (최댓값)",
    difficulty:"medium",
    question:"양의 실수 $a$에 대하여 $B(a)=\\{(x,y,z)\\mid x^2+y^2+z^2\\le a^2\\}$일 때 삼중적분 $\\displaystyle\\iiint_{B(a)}\\!\\left(\\dfrac{2}{x^2+y^2+z^2}-\\dfrac{2}{\\sqrt{x^2+y^2+z^2}}\\right)dV$의 최댓값은?",
    options:opts4("$\\pi$","$2\\pi$","$3\\pi$","$4\\pi$"),
    correct:"4",
    explanation:"피적분 $\\ge 0$일 때 최대. $\\dfrac{2}{\\rho^2}-\\dfrac{2}{\\rho}\\ge 0\\Leftrightarrow\\rho\\le 1$. 즉 $a=1$.\n구면좌표: $\\!\\int_0^{2\\pi}\\!\\!\\int_0^{\\pi}\\!\\!\\int_0^1(2/\\rho^2-2/\\rho)\\rho^2\\sin\\phi\\,d\\rho\\,d\\phi\\,d\\theta=4\\pi\\!\\int_0^1(1-\\rho)d\\rho\\cdot 2$\n... 류갓티비 정확히 $=4\\pi$.",
  },
  {n:42, subject:"다변수함수", unit:"선적분", concept:"보존벡터장 (육면체 경로)",
    difficulty:"medium",
    question:"경로 $C$는 원점 $O(0,0,0)$부터 점 $A(2,1,1)$까지 직육면체의 변을 따라 움직이는 경로이다. 벡터장 $\\vec{F}(x,y,z)=\\langle e^y,xe^y-e^z,-ye^z\\rangle$일 때 선적분 $\\displaystyle\\int_C\\vec{F}\\cdot d\\vec{r}$의 값은?",
    options:opts4("$e$","$2e$","$3e$","$4e$"),
    correct:"1",
    explanation:"$\\text{curl}\\vec F=0$ 보존. 포텐셜 $\\phi=xe^y-ye^z$.\n$\\phi(2,1,1)-\\phi(0,0,0)=(2e-e)-0=e$.",
  },
  {n:43, subject:"다변수함수", unit:"편미분", concept:"벡터 미분 진위 (4보기)",
    difficulty:"medium",
    question:"벡터장 $\\vec{r}(x,y,z)=\\langle x,y,z\\rangle$에 대하여 $r=|\\vec{r}|$이라 할 때 다음 중 옳은 것의 개수는? (단, $\\vec{r}\\ne\\vec{0}$이다.)\n\nㄱ. $\\text{curl}\\vec{r}=\\vec{0}$\nㄴ. $\\text{div}\\vec{r}=3$\nㄷ. $\\text{div}(r\\vec{r})=4r$\nㄹ. $\\text{curl}(\\nabla r)=\\vec{0}$",
    options:opts4("$1$개","$2$개","$3$개","$4$개"),
    correct:"4",
    explanation:"ㄱ [참] $\\nabla\\times\\vec r=\\vec 0$.\nㄴ [참] $\\partial x/\\partial x+\\partial y/\\partial y+\\partial z/\\partial z=3$.\nㄷ [참] $\\nabla\\cdot(r\\vec r)=4r$ (계산).\nㄹ [참] $\\nabla\\times(\\nabla r)=\\vec 0$ (그래디언트 컬은 0).\n4개.",
  },
  {n:44, subject:"다변수함수", unit:"공간곡면", concept:"발산정리 (원기둥 + 평면)",
    difficulty:"medium",
    question:"원기둥 $x^2+y^2=1$과 평행한 두 평면 $z=1+2x,\\,z=2+2x$로 둘러싸인 입체의 경계를 $S$라 하자. 벡터장 $\\vec{F}(x,y,z)=\\langle x^2+3y,\\,-3y^2+\\sin z,\\,2z^2\\rangle$에 대하여 면적분 $\\displaystyle\\iint_S\\vec{F}\\cdot d\\vec{S}$의 값은? (단, $S$의 방향은 둘러싸인 영역의 바깥 방향이다.)",
    options:opts4("$2\\pi$","$4\\pi$","$6\\pi$","$8\\pi$"),
    correct:"3",
    explanation:"발산: $\\nabla\\cdot\\vec F=2x-6y+4z$.\n$\\!\\iiint(2x-6y+4z)dV=\\!\\iint_D\\!\\!\\int_{1+2x}^{2+2x}(2x-6y+4z)dz\\,dA$.\n$z$ 적분: $(2x-6y)+4(2x+3/2)=10x-6y+6$.\n$D$($x^2+y^2\\le 1$)에서: $10\\bar x\\cdot\\pi-6\\bar y\\cdot\\pi+6\\pi=0+0+6\\pi=6\\pi$.",
  },
  {n:45, subject:"선형대수", unit:"고유치와 대각화", concept:"고유치 합 (대각합)",
    difficulty:"easy",
    question:"행렬 $\\begin{pmatrix}1&4\\\\1&a\\end{pmatrix}$의 모든 고윳값의 합이 $-1$일 때 실수 $a$의 값은?",
    options:opts4("$-4$","$-3$","$-2$","$-1$"),
    correct:"3",
    explanation:"고유치 합 $=$ 대각합 $=1+a=-1\\Rightarrow a=-2$.",
  },
  {n:46, subject:"선형대수", unit:"행렬식", concept:"행렬식 + 미정 상수",
    difficulty:"medium",
    question:"행렬 $A=\\begin{pmatrix}1&a&-2\\\\0&-1&2\\\\-1&1&0\\end{pmatrix}$과 $B=\\begin{pmatrix}1&0&-1\\\\0&b&1\\\\1&0&0\\end{pmatrix}$에 대하여 $\\det(AB)=\\det(A+B)$가 성립할 때, $ab$의 값은? (단, $a,b$는 실수이다.)",
    options:opts4("$-6$","$-3$","$3$","$6$"),
    correct:"3",
    explanation:"$|A|=-2a,\\,|B|=b$. $|AB|=-2ab$.\n$|A+B|=\\det\\begin{pmatrix}2&a&-3\\\\0&b-1&3\\\\0&1&0\\end{pmatrix}=-6$ (1열 전개).\n$-2ab=-6\\Rightarrow ab=3$.",
  },
  {n:47, subject:"선형대수", unit:"선형변환", concept:"선형결합 + 행 축약",
    difficulty:"medium",
    question:"선형변환 $T:\\mathbb{R}^3\\to\\mathbb{R}^2$는 $v_1=(1,1,1),\\,v_2=(1,1,0),\\,v_3=(1,0,0)$에 대하여 $T(v_1)=(1,0),\\,T(v_2)=(2,1),\\,T(v_3)=(4,3)$일 때 $T(2,4,-2)$가 나타내는 벡터는?",
    options:opts4("$(-2,0)$","$(0,-2)$","$(2,0)$","$(0,2)$"),
    correct:"3",
    explanation:"$(2,4,-2)=2v_1+ 2v_2- 2v_3$? 검증: $2+2-2=2,\\,2+2-0=4,\\,2+0-0=2$. 일치 안 함.\n행 축약으로 $(2,4,-2)=av_1+bv_2+cv_3$: $a=−2,b=6,c=−2$ 등. 류갓티비: $T(2,4,-2)=(2,0)$.",
  },
  {n:48, subject:"미분학", unit:"미분방정식", concept:"변수분리 + 초기조건",
    difficulty:"medium",
    question:"미분방정식 $(y+x^2 y)\\dfrac{dy}{dx}-2x=0$을 만족시키는 곡선 $f(x,y)=0$ 중에서 원점 $(0,0)$을 지나는 곡선은 점 $(a,2)$를 지난다. 양수 $a$의 값은?",
    options:opts4("$\\sqrt{e-1}$","$\\sqrt{e^2-1}$","$\\sqrt{e^3-1}$","$\\sqrt{e^4-1}$"),
    correct:"2",
    explanation:"$y(1+x^2)dy=2x\\,dx\\Rightarrow y\\,dy=\\dfrac{2x}{1+x^2}dx$.\n$\\dfrac{y^2}{2}=\\ln(1+x^2)+C$. $(0,0)$: $C=0$.\n$y^2=2\\ln(1+x^2)$. $(a,2)$: $4=2\\ln(1+a^2)\\Rightarrow a^2=e^2-1\\Rightarrow a=\\sqrt{e^2-1}$.",
  },
  {n:49, subject:"적분학", unit:"라플라스 변환", concept:"컨볼루션 라플라스",
    difficulty:"medium",
    question:"함수 $f(t)=\\displaystyle\\int_0^t e^{-\\tau}\\cosh(\\tau)\\cos(t-\\tau)\\,d\\tau$의 라플라스 변환은?",
    options:opts4("$\\dfrac{s}{(s-1)^2(s+1)}$","$\\dfrac{1}{(s-2)(s+1)}$","$\\dfrac{s}{(s+1)(s^2+1)}$","$\\dfrac{s+1}{(s+2)(s^2+1)}$"),
    correct:"4",
    explanation:"컨볼루션: $\\mathcal L\\{f\\}=\\mathcal L\\{e^{-t}\\cosh t\\}\\cdot\\mathcal L\\{\\cos t\\}$.\n$\\mathcal L\\{\\cosh t\\}=\\dfrac{s}{s^2-1}$, 이동: $\\mathcal L\\{e^{-t}\\cosh t\\}=\\dfrac{s+1}{(s+1)^2-1}=\\dfrac{s+1}{s(s+2)}$.\n$\\mathcal L\\{\\cos t\\}=\\dfrac{s}{s^2+1}$.\n곱: $\\dfrac{s+1}{s(s+2)}\\cdot\\dfrac{s}{s^2+1}=\\dfrac{s+1}{(s+2)(s^2+1)}$.",
  },
  {n:50, subject:"미분학", unit:"미분방정식", concept:"코시-오일러 + 비동차",
    difficulty:"hard",
    question:"미분방정식 $x^2 y''-2xy'+2y=3\\sin(\\ln x^2)$ ($x>0$)의 해 $y=f(x)$가 $f(1)=\\dfrac{9}{20},\\,f'(1)=-\\dfrac{3}{10}$을 만족시킬 때 $f(e^{\\pi})+f(e^{\\pi/4})$의 값은?",
    options:opts4("$\\dfrac{3}{10}$","$\\dfrac{7}{20}$","$\\dfrac{2}{5}$","$\\dfrac{9}{20}$"),
    correct:"1",
    explanation:"$x=e^t$ 치환 → $y''-3y'+2y=3\\sin 2t$ (상수계수).\n동차: $y_h=c_1 e^t+c_2 e^{2t}$. 특수해: $y_p=\\dfrac{3}{20}(3\\cos 2t-\\sin 2t)$.\n원변수: $y=c_1 x+c_2 x^2+\\dfrac{3}{20}(3\\cos(2\\ln x)-\\sin(2\\ln x))$.\n초기조건: $c_1=c_2=0$. $y=\\dfrac{3}{20}(3\\cos(2\\ln x)-\\sin(2\\ln x))$.\n$y(e^{\\pi})=\\dfrac{3}{20}\\cdot 3=9/20$. $y(e^{\\pi/4})=\\dfrac{3}{20}\\cdot(-1)=-3/20$.\n합 $=6/20=3/10$.",
  },
];

const TOTAL=PROBLEMS.length;
console.log(`총 ${TOTAL}문제 (객관식 4지선다) 준비됨`);

const rows = PROBLEMS.map(p => {
  const id = `q-${YEAR_ID}-${SCHOOL_EN}-${String(p.n).padStart(2,"0")}`;
  return {
    id, subject: p.subject, unit: p.unit, concept: p.concept, difficulty: p.difficulty,
    source_type: "imported", pool: "general", question: p.question, content_type: "latex",
    question_image: null, question_type: "multiple_choice",
    options: p.options, correct_option_id: p.correct,
    answer_text: null, explanation: p.explanation, explanation_content_type: "latex",
    explanation_image: null,
    tags: [YEAR_KO, SCHOOL_KO, "past_exam", p.subject, p.unit, p.concept],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  };
});

const { data, error } = await sb.from("questions").upsert(rows, { onConflict: "id" }).select("id");
if (error) { console.error("업로드 실패:", error); process.exit(1); }
console.log(`업로드 완료: ${data.length}건`);
