// 2017년 서강대 편입수학 객관식 20문항 (5지선다)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR="2017", SCHOOL_KO="서강대", SCHOOL_EN="sogang";
const opts5 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:1, subject:"미분학", unit:"극한과 연속", concept:"테일러 전개 극한",
    difficulty:"medium",
    question:"극한 $\\displaystyle\\lim_{x\\to\\infty}\\!\\left\\{x-x^2\\ln\\!\\left(\\dfrac{1+x}{x}\\right)\\right\\}$의 값은?",
    options:opts5("$0$","$\\dfrac{1}{2}$","$1$","$\\infty$","존재하지 않음."),
    correct:"2",
    explanation:"$t=\\dfrac{1}{x}$로 두면 $\\ln\\!\\left(1+\\dfrac{1}{x}\\right)=\\dfrac{1}{x}-\\dfrac{1}{2x^2}+\\dfrac{1}{3x^3}-\\cdots$.\n$x^2\\ln\\!\\left(\\dfrac{1+x}{x}\\right)=x-\\dfrac{1}{2}+\\dfrac{1}{3x}-\\cdots$이므로\n$x-x^2\\ln\\!\\left(\\dfrac{1+x}{x}\\right)=\\dfrac{1}{2}-\\dfrac{1}{3x}+\\cdots\\to\\dfrac{1}{2}$.",
  },
  {n:2, subject:"다변수함수", unit:"중적분", concept:"구면좌표 부피",
    difficulty:"medium",
    question:"구 $x^2+y^2+z^2=4$의 내부, $xy$평면의 위와 원뿔곡면 $z=\\sqrt{x^2+y^2}$의 아래에 놓여 있는 입체의 부피는?",
    options:opts5("$\\sqrt{2}\\,\\pi$","$\\dfrac{\\sqrt{2}}{2}\\,\\pi$","$\\sqrt{3}\\,\\pi$","$\\dfrac{8}{3}\\sqrt{2}\\,\\pi$","$2\\sqrt{3}\\,\\pi$"),
    correct:"4",
    explanation:"구면좌표 $(\\rho,\\varphi,\\theta)$에서 구는 $\\rho\\le 2$, 원뿔 $z=\\sqrt{x^2+y^2}$는 $\\varphi=\\dfrac{\\pi}{4}$.\n원뿔의 아래 + $xy$평면 위는 $\\dfrac{\\pi}{4}\\le\\varphi\\le\\dfrac{\\pi}{2}$, $0\\le\\theta\\le 2\\pi$, $0\\le\\rho\\le 2$.\n$V=\\!\\int_0^{2\\pi}\\!\\!\\int_{\\pi/4}^{\\pi/2}\\!\\!\\int_0^2\\rho^2\\sin\\varphi\\,d\\rho\\,d\\varphi\\,d\\theta=2\\pi\\cdot\\dfrac{\\sqrt{2}}{2}\\cdot\\dfrac{8}{3}=\\dfrac{8\\sqrt{2}}{3}\\pi$.",
  },
  {n:3, subject:"적분학", unit:"정적분", concept:"곡선 길이",
    difficulty:"medium",
    question:"곡선 $y=\\ln(\\sin x)\\;\\left(\\dfrac{\\pi}{2}\\le x\\le\\dfrac{3\\pi}{4}\\right)$의 길이는?",
    options:opts5("$\\ln(\\sqrt{2}+1)$","$\\ln(\\sqrt{2}-1)$","답 없음","$\\ln\\dfrac{\\sqrt{2}+1}{2}$","$\\ln\\dfrac{\\sqrt{2}-1}{2}$"),
    correct:"1",
    explanation:"$y'=\\cot x$, $\\sqrt{1+y'^2}=\\sqrt{1+\\cot^2 x}=|\\csc x|=\\csc x$ ($\\sin x>0$).\n$L=\\!\\int_{\\pi/2}^{3\\pi/4}\\!\\csc x\\,dx=\\big[-\\ln|\\csc x+\\cot x|\\big]_{\\pi/2}^{3\\pi/4}$.\n$x=\\dfrac{3\\pi}{4}$: $\\csc x=\\sqrt{2},\\,\\cot x=-1$이므로 $-\\ln(\\sqrt{2}-1)=\\ln(\\sqrt{2}+1)$.\n$x=\\dfrac{\\pi}{2}$: $\\csc x=1,\\,\\cot x=0$이므로 $-\\ln 1=0$.\n따라서 $L=\\ln(\\sqrt{2}+1)$.",
  },
  {n:4, subject:"다변수함수", unit:"편도함수", concept:"접평면 방정식",
    difficulty:"easyMedium",
    question:"함수 $z=f(x,y)=x^2-3xy+4y^2$의 그래프 위의 점 $(1,2,11)$에서 그 그래프에의 접평면의 방정식이 $z=ax+by+c$일 때 $a+b+c$의 값은?",
    options:opts5("$-2$","$-1$","$0$","$1$","$2$"),
    correct:"1",
    explanation:"$f_x=2x-3y$, $f_y=-3x+8y$.\n$(1,2)$에서 $f_x=2-6=-4$, $f_y=-3+16=13$, $f(1,2)=1-6+16=11$.\n접평면: $z-11=-4(x-1)+13(y-2)$, 즉 $z=-4x+13y-11$.\n$a+b+c=-4+13-11=-2$.",
  },
  {n:5, subject:"미분학", unit:"도함수의 활용", concept:"접하는 조건",
    difficulty:"hard",
    question:"방정식 $e^{2x}=k\\sqrt{x}$가 정확히 한 개의 해를 갖기 위한 $k$의 값과 이 때 방정식의 해를 $a$라 할 때 곱 $ka$의 값은?",
    options:opts5("$\\sqrt{e}$","$2\\sqrt{e}$","$\\dfrac{\\sqrt{e}}{2}$","$\\dfrac{2}{\\sqrt{e}}$","$\\dfrac{1}{2\\sqrt{e}}$"),
    correct:"3",
    explanation:"$g(x)=\\dfrac{e^{2x}}{\\sqrt{x}}=k$ ($x>0$)의 해가 한 개이려면 $g$의 최솟값에서 접해야 한다.\n$g'(x)=\\dfrac{e^{2x}(2x-1/2)}{x^{3/2}}=0\\Rightarrow x=\\dfrac{1}{4}=a$.\n$k=g(a)=\\dfrac{e^{1/2}}{1/2}=2\\sqrt{e}$.\n$ka=2\\sqrt{e}\\cdot\\dfrac{1}{4}=\\dfrac{\\sqrt{e}}{2}$.",
  },
  {n:6, subject:"미분학", unit:"도함수", concept:"역함수 미분",
    difficulty:"easy",
    question:"함수 $y=f(x)=2x+\\ln x$에 대하여 $(f^{-1})'(2)$의 값은?",
    options:opts5("$1$","$2$","$\\dfrac{1}{2}$","$3$","$\\dfrac{1}{3}$"),
    correct:"5",
    explanation:"$f(1)=2\\cdot 1+\\ln 1=2$이므로 $f^{-1}(2)=1$.\n$f'(x)=2+\\dfrac{1}{x}$, $f'(1)=3$.\n$(f^{-1})'(2)=\\dfrac{1}{f'(1)}=\\dfrac{1}{3}$.",
  },
  {n:7, subject:"적분학", unit:"급수의 수렴/발산", concept:"명제 진위 판단",
    difficulty:"hard",
    question:"다음 명제 중에서 맞는 것을 모두 고르면?\n(가) 급수 $\\displaystyle\\sum_{n=1}^{\\infty}(-1)^n\\dfrac{\\ln n}{n}$은 조건부 수렴이다.\n(나) $f_x(x,y)=x+y^2,\\,f_y(x,y)=x-y^2$을 만족하는 2계 편도함수가 모두 연속인 함수 $f$가 존재한다.\n(다) 함수 $z=f(x,y)$가 $(a,b)$에서 미분가능하고 극값을 가지면 $\\nabla f(a,b)=(0,0)$을 만족한다.\n(라) 점 $(1,2)$는 함수 $z=f(x,y)$의 임계점이고 $f_{xx}(1,2)<0,\\,f_{xx}(1,2)f_{yy}(1,2)<[f_{xy}(1,2)]^2$을 만족하면 $f$는 $(1,2)$에서 극댓값을 갖는다.\n(마) 급수 $\\displaystyle\\sum_{n=1}^{\\infty}(-1)^{n-1}\\dfrac{1}{n\\cdot 3^n}$의 합은 $\\ln\\dfrac{4}{3}$이다.",
    options:opts5("(가)(나)(라)","(가)(다)(마)","(나)(다)(라)","(나)(다)(마)","(다)(라)(마)"),
    correct:"2",
    explanation:"(가) 절대수렴 부분 $\\!\\sum\\dfrac{\\ln n}{n}$은 발산, 교대급수 $(-1)^n\\dfrac{\\ln n}{n}$은 $\\ln n/n\\downarrow 0$ ($n\\ge 3$)로 수렴 ⇒ 조건부 수렴. **참**.\n(나) $f_{xy}=2y$, $f_{yx}=1$로 다르므로 2계 편도함수 모두 연속인 $f$는 존재 X. **거짓**.\n(다) 페르마 정리. 미분가능한 점에서 극값 ⇒ $\\nabla f=0$. **참**.\n(라) 조건은 판별식 $D=f_{xx}f_{yy}-f_{xy}^2<0$, 즉 안장점이므로 극값 X. **거짓**.\n(마) $\\ln(1+x)=\\!\\sum(-1)^{n-1}\\dfrac{x^n}{n}$에 $x=\\dfrac{1}{3}$ 대입 $=\\ln\\dfrac{4}{3}$. **참**.\n따라서 (가)(다)(마).",
  },
  {n:8, subject:"미분학", unit:"평균값정리", concept:"평균값정리 부등식",
    difficulty:"easyMedium",
    question:"구간 $[0,4]$에서 연속인 함수 $y=f(x)$가 $f(0)=1$이고 모든 $x\\in(0,4)$에 대하여 $2\\le f'(x)\\le 5$를 만족하면 $a\\le f(4)\\le b$를 만족한다. 이 때 $(a,b)$의 값은?",
    options:opts5("$(6,18)$","$(7,19)$","$(8,20)$","$(9,21)$","$(10,22)$"),
    correct:"4",
    explanation:"평균값정리(또는 미적분학 기본정리)에 의해\n$f(4)=f(0)+\\!\\int_0^4 f'(x)\\,dx=1+\\!\\int_0^4 f'(x)\\,dx$.\n$2\\le f'\\le 5$이므로 $8\\le\\!\\int_0^4 f'\\le 20$.\n$9\\le f(4)\\le 21$. $(a,b)=(9,21)$.",
  },
  {n:9, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"직선과 평면이 이루는 각",
    difficulty:"medium",
    question:"평면 $\\vec{r}=\\vec{i}-3\\vec{j}+\\vec{k}+\\lambda(-\\vec{i}-3\\vec{j}+2\\vec{k})+\\mu(2\\vec{i}+\\vec{j}-3\\vec{k})\\;(\\lambda,\\mu\\text{는 임의의 실수})$와 직선 $\\vec{r}=3\\vec{i}-\\vec{k}+t(\\vec{i}-\\vec{j}-\\vec{k})\\;(t\\text{는 임의의 실수})$가 이루는 각을 $\\theta$라 할 때 $\\cos\\theta$의 값은?",
    options:opts5("$\\dfrac{\\sqrt{14}}{15}$","$\\dfrac{\\sqrt{211}}{15}$","$\\dfrac{1}{15}$","$\\dfrac{4\\sqrt{14}}{15}$","$\\dfrac{\\sqrt{13}}{15}$"),
    correct:"4",
    explanation:"평면의 법선 $\\vec{n}=(-1,-3,2)\\times(2,1,-3)=(7,1,5)$, $|\\vec{n}|=5\\sqrt{3}$.\n직선의 방향 $\\vec{d}=(1,-1,-1)$, $|\\vec{d}|=\\sqrt{3}$.\n$\\sin\\theta=\\dfrac{|\\vec{n}\\cdot\\vec{d}|}{|\\vec{n}||\\vec{d}|}=\\dfrac{|7-1-5|}{5\\sqrt{3}\\cdot\\sqrt{3}}=\\dfrac{1}{15}$.\n$\\cos\\theta=\\sqrt{1-\\dfrac{1}{225}}=\\dfrac{\\sqrt{224}}{15}=\\dfrac{4\\sqrt{14}}{15}$.",
  },
  {n:10, subject:"미분학", unit:"도함수의 활용", concept:"포물선 운동",
    difficulty:"easy",
    question:"한 발사체가 초기속력 $9.8\\,m/s$, 상승각 $30^\\circ$로 지상 $9.8\\,m$의 위치에서 발사되었다. 공기저항은 무시하고 외부의 힘은 오직 중력만이 작용한다고 할 때 이 발사체가 지상에 도달하는데 걸리는 시간은? (단, 중력 상수는 $g=9.8\\,m/s^2$이다.)",
    options:opts5("$1$","$1.5$","$2$","$2.5$","$3$"),
    correct:"3",
    explanation:"수직속도 $v_y(0)=9.8\\sin 30^\\circ=4.9\\,m/s$.\n높이 $y(t)=9.8+4.9t-\\dfrac{1}{2}(9.8)t^2=9.8+4.9t-4.9t^2$.\n$y(t)=0\\Rightarrow t^2-t-2=0\\Rightarrow(t-2)(t+1)=0\\Rightarrow t=2$.",
  },
  {n:11, subject:"다변수함수", unit:"편도함수의 응용", concept:"라그랑주 승수",
    difficulty:"medium",
    question:"함수 $f(x,y,z)=x-2y+3z$의 곡면 $x^2+(y-1)^2+2z^2=19$ 위에서의 극댓값을 $\\alpha$, 극솟값을 $\\beta$라 할 때 $\\alpha-\\beta$의 값은?",
    options:opts5("$19\\sqrt{2}$","$\\dfrac{19}{\\sqrt{2}}-2$","$19-2\\sqrt{2}$","$19-4\\sqrt{2}$","$38-4\\sqrt{2}$"),
    correct:"1",
    explanation:"라그랑주: $\\nabla f=\\lambda\\nabla g$로부터 $1=2\\lambda x,\\,-2=2\\lambda(y-1),\\,3=4\\lambda z$.\n$x=\\dfrac{1}{2\\lambda},\\,y-1=-\\dfrac{1}{\\lambda},\\,z=\\dfrac{3}{4\\lambda}$.\n곡면 대입: $\\dfrac{1}{4\\lambda^2}+\\dfrac{1}{\\lambda^2}+\\dfrac{9}{8\\lambda^2}=\\dfrac{19}{8\\lambda^2}=19\\Rightarrow\\lambda=\\pm\\dfrac{1}{2\\sqrt{2}}$.\n$f=x-2(y-1)+3z-2=\\dfrac{19}{4\\lambda}-2$.\n$\\alpha-\\beta=\\dfrac{19}{4\\lambda_+}-\\dfrac{19}{4\\lambda_-}=\\dfrac{19}{4}\\!\\left(2\\sqrt{2}-(-2\\sqrt{2})\\right)=19\\sqrt{2}$.",
  },
  {n:12, subject:"다변수함수", unit:"중적분", concept:"변수변환 자코비안",
    difficulty:"medium",
    question:"선형변환 $T:\\mathbb{R}^2\\to\\mathbb{R}^2$이 $T(u,v)=\\left(4u,\\,2u+\\dfrac{3}{8}v\\right)$로 주어졌다. 2차원 영역 $D^*=\\{(u,v):0\\le u\\le 1,\\,1\\le v\\le 3\\}$에 대하여 $D=T(D^*)$라 할 때 $I=\\displaystyle\\iint_D\\!\\left(-\\dfrac{x^2}{16}+y\\right)dx\\,dy$의 값은?",
    options:opts5("$\\dfrac{17}{8}$","$\\dfrac{6}{17}$","$\\dfrac{17}{6}$","$\\dfrac{4}{17}$","$\\dfrac{17}{4}$"),
    correct:"5",
    explanation:"자코비안 $J=\\det\\!\\begin{pmatrix}4&0\\\\2&3/8\\end{pmatrix}=\\dfrac{3}{2}$.\n$x=4u,\\,y=2u+\\dfrac{3v}{8}$이므로 $-\\dfrac{x^2}{16}+y=-u^2+2u+\\dfrac{3v}{8}$.\n$I=\\dfrac{3}{2}\\!\\int_0^1\\!\\!\\int_1^3\\!\\left(-u^2+2u+\\dfrac{3v}{8}\\right)dv\\,du$.\n안쪽 적분 $=2(-u^2+2u)+\\dfrac{3}{2}=-2u^2+4u+\\dfrac{3}{2}$.\n바깥쪽 $=\\!\\int_0^1\\!\\left(-2u^2+4u+\\dfrac{3}{2}\\right)du=-\\dfrac{2}{3}+2+\\dfrac{3}{2}=\\dfrac{17}{6}$.\n$I=\\dfrac{3}{2}\\cdot\\dfrac{17}{6}=\\dfrac{17}{4}$.",
  },
  {n:13, subject:"다변수함수", unit:"선적분과 면적분", concept:"보존벡터장 선적분",
    difficulty:"medium",
    question:"$\\vec{F}=(2xyz^2-\\cos x)\\vec{i}+(x^2z^2)\\vec{j}+(2x^2yz)\\vec{k}$로 주어진 벡터장과 곡선 $C$가 $\\vec{r}(t)=(\\cos^5 t,\\,-\\sin^3 t,\\,t^5),\\,0\\le t\\le\\dfrac{\\pi}{2}$로 주어졌다. 이 때 $I=\\displaystyle\\int_C\\vec{F}\\cdot d\\vec{r}$의 값은?",
    options:opts5("$-\\sin(1)$","$\\sin(1)$","$-\\!\\left(\\dfrac{\\pi}{2}\\right)^{10}-\\sin(1)$","$-\\!\\left(\\dfrac{\\pi}{2}\\right)^{10}+\\sin(1)$","$\\left(\\dfrac{\\pi}{2}\\right)^{10}-\\sin(1)$"),
    correct:"2",
    explanation:"$\\nabla\\times\\vec{F}=\\vec{0}$ 확인: $P_y=Q_x=2xz^2,\\,P_z=R_x=4xyz,\\,Q_z=R_y=2x^2z$. **보존벡터장**.\n포텐셜 $\\varphi(x,y,z)=x^2yz^2-\\sin x$ ($\\varphi_x=2xyz^2-\\cos x$ 확인).\n$\\vec{r}(0)=(1,0,0),\\,\\vec{r}(\\pi/2)=(0,-1,(\\pi/2)^5)$.\n$\\varphi(\\vec{r}(\\pi/2))-\\varphi(\\vec{r}(0))=[0-0]-[0-\\sin 1]=\\sin 1$.",
  },
  {n:14, subject:"다변수함수", unit:"편도함수의 응용", concept:"이변수함수 극값",
    difficulty:"medium",
    question:"함수 $f:\\mathbb{R}^2\\to\\mathbb{R}^1$이 $f(x,y)=2x^2-2xy+x+y^2-4y+5$로 주어졌다. 이 때 함수 $f$가 극값(extreme value)을 갖는 점을 $(\\alpha,\\beta)$라 할 때 $\\alpha-\\beta$의 값, 그 점에서 함수 $f$의 극대(max)값 또는 극소(min)값 그리고 $f(\\alpha,\\beta)$의 값에 대한 순서 3쌍 $(\\alpha-\\beta,\\,\\max(\\text{or min}),\\,f(\\alpha,\\beta))$은?",
    options:opts5("$\\left(2,\\,\\max,\\,\\dfrac{5}{4}\\right)$","$\\left(-2,\\,\\max,\\,\\dfrac{5}{4}\\right)$","$\\left(-2,\\,\\min,\\,-\\dfrac{5}{4}\\right)$","$\\left(2,\\,\\min,\\,-\\dfrac{5}{4}\\right)$","$\\left(2,\\,\\max,\\,-\\dfrac{5}{4}\\right)$"),
    correct:"3",
    explanation:"$f_x=4x-2y+1=0,\\,f_y=-2x+2y-4=0$.\n두 식 더하면 $2x-3=0\\Rightarrow x=\\dfrac{3}{2},\\,y=\\dfrac{7}{2}$. 따라서 $\\alpha-\\beta=-2$.\n$f_{xx}=4,\\,f_{yy}=2,\\,f_{xy}=-2$, $D=8-4=4>0,\\,f_{xx}>0$이므로 **극소**.\n$f\\!\\left(\\dfrac{3}{2},\\dfrac{7}{2}\\right)=\\dfrac{9}{2}-\\dfrac{21}{2}+\\dfrac{3}{2}+\\dfrac{49}{4}-14+5=-\\dfrac{5}{4}$.",
  },
  {n:15, subject:"선형대수", unit:"고유치와 대각화", concept:"멱영행렬 거듭제곱",
    difficulty:"medium",
    question:"$2\\times 2$ 행렬 $A=\\begin{pmatrix}1&2\\\\-1&-2\\end{pmatrix}$와 벡터 $\\vec{u_0}=\\begin{pmatrix}-3\\\\1\\end{pmatrix}$에 대하여 $A^{16}(\\vec{u_0})=\\begin{pmatrix}u_1\\\\u_2\\end{pmatrix}$라 할 때 $u_1-u_2$의 값은?",
    options:opts5("$-2$","$2$","$0$","$-3$","$3$"),
    correct:"2",
    explanation:"$A^2=\\begin{pmatrix}1&2\\\\-1&-2\\end{pmatrix}\\!\\begin{pmatrix}1&2\\\\-1&-2\\end{pmatrix}=\\begin{pmatrix}-1&-2\\\\1&2\\end{pmatrix}=-A$.\n따라서 $A^{16}=(A^2)^8=(-A)^8=A^8=(A^2)^4=(-A)^4=A^4=(A^2)^2=A^2=-A$.\n$A^{16}\\vec{u_0}=-A\\vec{u_0}=-\\!\\begin{pmatrix}-3+2\\\\3-2\\end{pmatrix}=-\\!\\begin{pmatrix}-1\\\\1\\end{pmatrix}=\\begin{pmatrix}1\\\\-1\\end{pmatrix}$.\n$u_1-u_2=1-(-1)=2$.",
  },
  {n:16, subject:"선형대수", unit:"선형변환", concept:"영공간 정사영 trace",
    difficulty:"medium",
    question:"$2\\times 3$ 행렬 $A=\\begin{pmatrix}1&0&-1\\\\1&0&-1\\end{pmatrix}$에 대하여 $A\\vec{x}=\\vec{0}$을 만족하는 모든 $\\vec{x}$의 집합을 $N(A)$라 하자. 3차원 공간 $\\mathbb{R}^3$에서 $N(A)$으로의 정사영 행렬을 $P=(p_{jk})$라 할 때 $P$의 trace $p_{11}+p_{22}+p_{33}$의 값은?",
    options:opts5("$-4$","$4$","$-2$","$2$","$0$"),
    correct:"4",
    explanation:"$A\\vec{x}=\\vec{0}\\Leftrightarrow x_1-x_3=0$이므로 $N(A)=\\{(t,s,t):t,s\\in\\mathbb{R}\\}$, 차원 2.\n정사영 행렬 $P$의 trace는 정사영 부분공간의 차원과 같다.\n$\\mathrm{tr}(P)=\\dim N(A)=2$.",
  },
  {n:17, subject:"선형대수", unit:"고유치와 대각화", concept:"행렬 명제 진위",
    difficulty:"hard",
    question:"$n\\times n$ 행렬 $A$에 대한 아래의 명제 중에서 맞는 것을 모두 고르면? (여기서 $A^T$는 $A$의 전치행렬(transpose)이다.)\n(가) $A$의 영공간(null space)을 $N(A)$ 그리고 $A^TA$의 영공간을 $N(A^TA)$라 하면 $N(A^TA)=N(A)$이다.\n(나) $A$가 $n$개의 서로 다른 고윳값(eigenvalue)을 가지면 $A$는 대각화 가능(diagonalizable)하다.\n(다) $A$의 서로 다른 고윳값(eigenvalue)에 대응하는 고유벡터(eigenvector)는 서로 수직이다.\n(라) $A$의 서로 다른 고윳값(eigenvalue)의 개수가 $(n-1)$개 이하이면 $A$는 대각화 가능하지 않다.",
    options:opts5("(가), (나)","(나), (다)","(다), (라)","(가), (라)","(나), (라)"),
    correct:"1",
    explanation:"(가) $A^TA\\vec{x}=\\vec{0}\\Leftrightarrow\\vec{x}^TA^TA\\vec{x}=|A\\vec{x}|^2=0\\Leftrightarrow A\\vec{x}=\\vec{0}$. **참**.\n(나) $n$개 서로 다른 고윳값 ⇒ $n$개 일차독립 고유벡터 ⇒ 대각화 가능. **참**.\n(다) 대칭(자기수반)행렬일 때만 성립. 일반 행렬은 거짓. **거짓**.\n(라) 예: $A=I$는 고윳값 $1$ 한 개뿐이지만 대각화 가능. **거짓**.\n따라서 (가), (나).",
  },
  {n:18, subject:"미분학", unit:"미분방정식", concept:"매개변수변환법",
    difficulty:"hard",
    question:"이계 선형 미분방정식 $y''+ay'+by=0$ ($a,b$는 실수인 상수)의 해를 $e^x,\\,e^{-x}$라 할 때\n$$y''+ay'+by=-\\dfrac{2e^x}{e^x+1}$$\n의 해가 될 수 있는 것은?",
    options:opts5("$e^{-x}\\ln(e^x+1)-e^x\\ln(e^x+1)+1$","$e^{-x}\\ln(e^{-x}+1)-e^x\\ln(e^x+1)+1$","$e^x\\ln(e^x+1)-e^{-x}\\ln(e^{-x}+1)+1$","$e^x\\ln(e^{-x}+1)-e^{-x}\\ln(e^x+1)+1$","$-xe^x+e^x\\ln(e^x+1)+1-e^{-x}\\ln(e^x+1)$"),
    correct:"5",
    explanation:"동차해 $e^x,\\,e^{-x}$이므로 $a=0,\\,b=-1$. $y''-y=-\\dfrac{2e^x}{e^x+1}$.\n매개변수변환법: $W=\\det\\!\\begin{pmatrix}e^x&e^{-x}\\\\e^x&-e^{-x}\\end{pmatrix}=-2$.\n$u_1'=-\\dfrac{y_2 R}{W}=-\\dfrac{e^{-x}\\cdot(-2e^x/(e^x+1))}{-2}=-\\dfrac{1}{e^x+1}$.\n$u_2'=\\dfrac{y_1 R}{W}=\\dfrac{e^x\\cdot(-2e^x/(e^x+1))}{-2}=\\dfrac{e^{2x}}{e^x+1}$.\n적분: $u_1=\\ln(e^x+1)-x$, $u_2=e^x-\\ln(e^x+1)$.\n$y_p=u_1 e^x+u_2 e^{-x}=e^x\\ln(e^x+1)-xe^x+1-e^{-x}\\ln(e^x+1)$.",
  },
  {n:19, subject:"미분학", unit:"미분방정식", concept:"멱급수 해법",
    difficulty:"hard",
    question:"멱급수 형태의 함수 $y=\\displaystyle\\sum_{k=0}^{\\infty}c_k x^k$가 미분방정식\n$$y''-(\\sin x)y=0,\\;y(0)=0,\\;y'(0)=1$$\n을 만족할 때 $c_0+c_1+c_2+c_3+c_4$의 값은?",
    options:opts5("$\\dfrac{1}{12}$","$\\dfrac{25}{12}$","$-\\dfrac{11}{12}$","$-\\dfrac{23}{12}$","$\\dfrac{13}{12}$"),
    correct:"5",
    explanation:"초기조건에서 $c_0=0,\\,c_1=1$.\n$\\sin x=x-\\dfrac{x^3}{6}+\\cdots$이고 $\\sin x\\cdot y=c_0 x+c_1 x^2+(c_2-\\dfrac{c_0}{6})x^3+(c_3-\\dfrac{c_1}{6})x^4+\\cdots$.\n$y''=2c_2+6c_3 x+12c_4 x^2+\\cdots$.\n$y''=\\sin x\\cdot y$ 계수 비교:\n$x^0:\\,2c_2=0\\Rightarrow c_2=0$.\n$x^1:\\,6c_3=c_0=0\\Rightarrow c_3=0$.\n$x^2:\\,12c_4=c_1=1\\Rightarrow c_4=\\dfrac{1}{12}$.\n$c_0+c_1+c_2+c_3+c_4=0+1+0+0+\\dfrac{1}{12}=\\dfrac{13}{12}$.",
  },
  {n:20, subject:"미분학", unit:"미분방정식", concept:"라플라스 역변환",
    difficulty:"medium",
    question:"$\\mathcal{L}$을 라플라스 변환(Laplace Transformation)이라 하고 $\\mathcal{L}^{-1}$을 $\\mathcal{L}$의 역변환이라 할 때 $\\mathcal{L}^{-1}\\!\\left\\{\\dfrac{e^{-s}}{s^2(s-1)}\\right\\}\\!(t),\\,t>0$에서의 값은?",
    options:opts5("$-1+t+e^t$","$-1+t+e^{-t+1}$","$-U(t-1)$","$(-t+e^{t-1})U(t-1)$","$(1-t+e^{t-1})U(t-1)$"),
    correct:"4",
    explanation:"부분분수: $\\dfrac{1}{s^2(s-1)}=-\\dfrac{1}{s}-\\dfrac{1}{s^2}+\\dfrac{1}{s-1}$.\n$\\mathcal{L}^{-1}\\!\\left\\{\\dfrac{1}{s^2(s-1)}\\right\\}=-1-t+e^t=:f(t)$.\n시간이동: $\\mathcal{L}^{-1}\\{e^{-s}F(s)\\}=f(t-1)U(t-1)$.\n$f(t-1)=-1-(t-1)+e^{t-1}=-t+e^{t-1}$.\n결과 $=(-t+e^{t-1})U(t-1)$.",
  },
];

const TOTAL=PROBLEMS.length;
console.log(`총 ${TOTAL}문제 준비됨`);

const rows = PROBLEMS.map(p => {
  const id = `q-${YEAR}-${SCHOOL_EN}-${String(p.n).padStart(2,"0")}`;
  return {
    id,
    subject: p.subject,
    unit: p.unit,
    concept: p.concept,
    difficulty: p.difficulty,
    source_type: "imported",
    pool: "general",
    question: p.question,
    content_type: "latex",
    question_image: null,
    options: p.options,
    correct_option_id: p.correct,
    explanation: p.explanation,
    explanation_content_type: "latex",
    explanation_image: null,
    tags: [`year:${YEAR}`, `school:${SCHOOL_KO}`, `school_slug:${SCHOOL_EN}`, "past_exam"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  };
});

const { data, error } = await sb.from("questions").upsert(rows, { onConflict: "id" }).select("id");
if (error) {
  console.error("업로드 실패:", error);
  process.exit(1);
}
console.log(`업로드 완료: ${data.length}건`);
