// 2023년 광운대 편입수학 객관식 30문항 (5지선다)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR="2023", SCHOOL_KO="광운대", SCHOOL_EN="kwangwoon";
const opts5 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:1, subject:"미분학", unit:"집합과 함수", concept:"infsup 진위판단",
    difficulty:"medium",
    question:"유계 집합 $A,B\\subset\\mathbb{R}$에 대해 다음 중 참인 명제를 모두 고른 것은?\n\nⓐ $\\inf\\!\\left\\{\\dfrac{1}{n}\\,\\bigg|\\,n\\in\\mathbb{N}\\right\\}=0$\nⓑ $A\\subset B$이면 $\\inf A\\le\\inf B$\nⓒ $A,B\\ne\\varnothing$이면 $\\sup(A-B)=\\sup A-\\sup B$\nⓓ $\\varnothing\\ne A\\subset\\mathbb{R}$이면 $\\inf A\\le\\sup A$",
    options:opts5("ⓐ, ⓑ, ⓒ, ⓓ","ⓐ, ⓑ, ⓒ","ⓐ, ⓒ, ⓓ","ⓐ, ⓓ","ⓑ, ⓒ"),
    correct:"4",
    explanation:"ⓐ [참] $\\{1, 1/2, 1/3, \\ldots\\}$의 하한 $=0$.\nⓑ [거짓] 반례: $A=\\{1,2\\},\\,B=\\{0,1,2\\}$. $A\\subset B$이지만 $\\inf A=1>0=\\inf B$.\nⓒ [거짓] 반례: $A=\\{1,2\\},\\,B=\\{1\\}$. $A-B=\\{2\\}$, $\\sup(A-B)=2$, $\\sup A-\\sup B=2-1=1$.\nⓓ [참] 정의에 의해 항상 성립.\n참은 ⓐ, ⓓ.",
  },
  {n:2, subject:"적분학", unit:"급수의 수렴/발산", concept:"무한등비급수",
    difficulty:"medium",
    question:"다음 식으로 정의된 함수 $f$에 대하여 $f(0)+\\displaystyle\\lim_{x\\to 0^{+}}f(x)$의 값은?\n$$f(x)=\\sum_{k=0}^{\\infty}\\dfrac{x^{2023}}{(1+x^{2023})^k}\\quad(x\\ge 0)$$",
    options:opts5("$0$","$1$","$2$","$\\dfrac{1}{2}$","$\\dfrac{1}{3}$"),
    correct:"2",
    explanation:"$f(x)=x^{2023}\\sum_{k=0}^{\\infty}\\!\\left(\\dfrac{1}{1+x^{2023}}\\right)^k$. 공비 $r=\\dfrac{1}{1+x^{2023}}$.\n$x=0$: $r=1$이므로 $f(0)=0\\cdot\\sum 1=0\\cdot\\infty=0$ (실제로 합 자체가 $0$).\n$x>0$ ($-1<r<1$): $f(x)=x^{2023}\\cdot\\dfrac{1}{1-\\frac{1}{1+x^{2023}}}=x^{2023}\\cdot\\dfrac{1+x^{2023}}{x^{2023}}=1+x^{2023}$.\n$\\displaystyle\\lim_{x\\to 0^{+}}f(x)=1$. 합 $=0+1=1$.",
  },
  {n:3, subject:"미분학", unit:"삼각함수", concept:"삼각함수 최댓값·최솟값",
    difficulty:"medium",
    question:"실수 $x$에 대하여 정의된 다음 함수 $f(x)$의 최댓값과 최솟값의 합은?\n$$f(x)=\\sqrt{2}\\sin x+2\\cos x\\sin x-\\sqrt{2}\\cos x$$",
    options:opts5("$\\dfrac{3}{2}$","$-\\dfrac{1}{2}$","$0$","$\\dfrac{1}{2}$","$-\\dfrac{3}{2}$"),
    correct:"5",
    explanation:"$f(x)=2\\!\\left(\\dfrac{1}{\\sqrt{2}}\\sin x-\\dfrac{1}{\\sqrt{2}}\\cos x\\right)+\\sin 2x=2\\sin\\!\\left(x-\\dfrac{\\pi}{4}\\right)+\\sin 2x$.\n$x\\to x-\\pi/4$ 평행이동: $g(x)=2\\sin x+\\sin\\!\\left(\\dfrac{\\pi}{2}+2x\\right)=2\\sin x+\\cos 2x=-2\\sin^2 x+2\\sin x+1$.\n$\\sin x=t$ ($-1\\le t\\le 1$): $h(t)=-2t^2+2t+1=-2\\!\\left(t-\\dfrac{1}{2}\\right)^2+\\dfrac{3}{2}$.\n최댓값 $\\dfrac{3}{2}$ ($t=1/2$), 최솟값 $-3$ ($t=-1$). 합 $=\\dfrac{3}{2}-3=-\\dfrac{3}{2}$.",
  },
  {n:4, subject:"미분학", unit:"집합과 함수", concept:"함수의 합집합·교집합 상",
    difficulty:"easy",
    question:"함수 $f:X\\to Y$이고 $A,B\\subset X$일 때 아래 괄호에 가장 적절한 기호를 차례대로 나열한 것은?\n\nⓐ $f(A\\cup B)\\;(\\;\\;)\\;f(A)\\cup f(B)$\nⓑ $f(A\\cap B)\\;(\\;\\;)\\;f(A)\\cap f(B)$",
    options:opts5("$\\subset,\\,\\subset$","$\\subset,\\,=$","$=,\\,\\supset$","$=,\\,\\subset$","$=,\\,=$"),
    correct:"4",
    explanation:"ⓐ $f(A\\cup B)=f(A)\\cup f(B)$ (양방향 포함).\nⓑ $f(A\\cap B)\\subset f(A)\\cap f(B)$만 항상 성립. 등호는 $f$가 단사일 때만.\n반례: $X=\\{1,2,3,4\\},\\,Y=\\{1,2,3\\}$, $f(1)=1,f(2)=2,f(3)=1,f(4)=2$. $A=\\{1,2\\},\\,B=\\{3,4\\}$이면 $A\\cap B=\\varnothing$, $f(A)\\cap f(B)=\\{1,2\\}$.",
  },
  {n:5, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"제약조건 최댓값",
    difficulty:"medium",
    question:"원기둥의 내부 $x^2+y^2\\le 2$와 평면 $x+y+z=1$이 만나는 점과 원점 간의 거리 중 최댓값은?",
    options:opts5("$\\sqrt{10}$","$\\sqrt{11}$","$2\\sqrt{3}$","$\\sqrt{13}$","$\\sqrt{14}$"),
    correct:"2",
    explanation:"제약 $x^2+y^2\\le 2,\\,x+y+z=1$에서 $f=x^2+y^2+z^2=z^2+(x^2+y^2)\\le z^2+2$의 최댓값.\n$z$의 범위: $2(x^2+y^2)\\ge(x+y)^2=(1-z)^2$, 즉 $4\\ge(1-z)^2\\Rightarrow z^2-2z-3\\le 0\\Rightarrow-1\\le z\\le 3$.\n$z^2+2$의 최댓값: $z=3$일 때 $11$. 따라서 거리 최댓값 $=\\sqrt{11}$.",
  },
  {n:6, subject:"적분학", unit:"부정적분", concept:"분수함수 적분 (역미분)",
    difficulty:"hard",
    question:"$\\displaystyle\\int\\dfrac{2(x^2+1)}{x^4+x^2+1}\\,dx=\\dfrac{2\\sqrt{3}}{3}\\tan^{-1}\\!\\left(\\dfrac{\\alpha x}{1+\\beta x^2}\\right)+C$일 때 $\\alpha+\\beta$의 값은? (단, $\\alpha,\\beta$는 상수, $C$는 적분 상수)",
    options:opts5("$\\sqrt{3}+1$","$-\\sqrt{3}+1$","$\\sqrt{3}-1$","$-\\sqrt{3}-1$","$1$"),
    correct:"3",
    explanation:"분자분모를 $x^2$로 나눔: $\\dfrac{2(1+1/x^2)}{x^2+1+1/x^2}=\\dfrac{2(1+1/x^2)}{(x-1/x)^2+3}$.\n$t=x-1/x$로 치환: $dt=(1+1/x^2)dx$. 적분 $=\\!\\int\\dfrac{2}{t^2+3}dt=\\dfrac{2}{\\sqrt{3}}\\tan^{-1}\\!\\dfrac{t}{\\sqrt{3}}+C=\\dfrac{2\\sqrt{3}}{3}\\tan^{-1}\\!\\dfrac{x^2-1}{\\sqrt{3}x}+C$.\n탄젠트 항등식 $\\tan^{-1}\\!\\dfrac{x^2-1}{\\sqrt{3}x}=\\pm\\dfrac{\\pi}{2}-\\tan^{-1}\\!\\dfrac{\\sqrt{3}x}{x^2-1}$ 변형 시 $\\dfrac{2\\sqrt{3}}{3}\\tan^{-1}\\!\\dfrac{\\sqrt{3}x}{1-x^2}+C$.\n$\\alpha=\\sqrt{3},\\,\\beta=-1$. $\\alpha+\\beta=\\sqrt{3}-1$.",
  },
  {n:7, subject:"미분학", unit:"극한과 연속", concept:"미정 상수 결정",
    difficulty:"medium",
    question:"다음을 만족시키는 두 상수 $a$와 $b$의 값의 합은?\n$$\\lim_{x\\to 0}\\dfrac{\\sqrt[3]{ax+1}-b}{x}=\\dfrac{1}{2}$$",
    options:opts5("$\\dfrac{1}{2}$","$1$","$\\dfrac{3}{2}$","$2$","$\\dfrac{5}{2}$"),
    correct:"5",
    explanation:"극한이 존재하려면 $0/0$ 꼴: $b=1$.\n로피탈: $\\displaystyle\\lim_{x\\to 0}\\dfrac{1}{3}a(ax+1)^{-2/3}=\\dfrac{a}{3}=\\dfrac{1}{2}\\Rightarrow a=\\dfrac{3}{2}$.\n$a+b=\\dfrac{3}{2}+1=\\dfrac{5}{2}$.",
  },
  {n:8, subject:"적분학", unit:"정적분", concept:"리만합 → 정적분",
    difficulty:"medium",
    question:"$\\displaystyle\\lim_{n\\to\\infty}\\dfrac{\\sqrt{n}}{2}\\!\\left(\\dfrac{1}{\\sqrt{1+n}}+\\dfrac{1}{\\sqrt{2+n}}+\\cdots+\\dfrac{1}{\\sqrt{2n}}\\right)$의 값은?",
    options:opts5("$\\dfrac{\\sqrt{3}}{2}$","$\\dfrac{\\sqrt{3}}{2}-1$","$\\sqrt{3}-1$","$\\sqrt{2}$","$\\sqrt{2}-1$"),
    correct:"5",
    explanation:"$\\dfrac{1}{2}\\displaystyle\\lim_{n\\to\\infty}\\dfrac{\\sqrt{n}}{n}\\sum_{k=1}^{n}\\dfrac{1}{\\sqrt{n+k}}=\\dfrac{1}{2}\\lim_{n\\to\\infty}\\sum_{k=1}^{n}\\dfrac{1}{\\sqrt{1+k/n}}\\cdot\\dfrac{1}{n}$.\n리만합 $\\to\\dfrac{1}{2}\\!\\int_0^1\\dfrac{dx}{\\sqrt{1+x}}=\\dfrac{1}{2}[2\\sqrt{1+x}]_0^1=\\dfrac{1}{2}(2\\sqrt{2}-2)=\\sqrt{2}-1$.",
  },
  {n:9, subject:"미분학", unit:"종합", concept:"진위판단 (부등식·볼록성)",
    difficulty:"medium",
    question:"다음 중 옳은 것을 모두 고르면?\n\nⓐ 모든 실수 $x,y$에 대하여 $|\\cos x-\\cos y|\\le|x-y|$\nⓑ 함수 $f(x)=\\dfrac{x^2}{8}-\\dfrac{1}{x}$의 그래프가 위로 볼록한 구간 $I\\subset\\mathbb{R}$가 존재한다.\nⓒ 구간 $(0,\\infty)$에서 $\\dfrac{8}{x}+\\sqrt{x}>4$\nⓓ 실함수 $f(x)=|x|$의 그래프는 아래로 볼록하다.",
    options:opts5("ⓐ, ⓒ","ⓐ, ⓒ, ⓓ","ⓑ, ⓓ","ⓐ, ⓑ, ⓓ","ⓐ, ⓑ, ⓒ, ⓓ"),
    correct:"4",
    explanation:"ⓐ [참] 평균값 정리: $|\\cos x-\\cos y|=|\\sin c|\\cdot|x-y|\\le|x-y|$.\nⓑ [참] $f''(x)=\\dfrac{1}{4}-\\dfrac{2}{x^3}=\\dfrac{x^3-8}{4x^3}$. $0<x<2$에서 $f''<0$ (위로 볼록).\nⓒ [거짓] 산술기하평균: $\\dfrac{8}{x}+\\dfrac{\\sqrt{x}}{2}+\\dfrac{\\sqrt{x}}{2}\\ge 3\\sqrt[3]{2}\\approx 3.78<4$. 반례 $x=4$: $2+2=4$ ($>$ 거짓).\nⓓ [참] $|x|$는 아래로 볼록 (강의에서 표준).\n옳은 것은 ⓐ, ⓑ, ⓓ.",
  },
  {n:10, subject:"미분학", unit:"도함수 응용", concept:"적분 함수 극값",
    difficulty:"hard",
    question:"함수 $f(x)=\\tan x-ax^3-x$에 대하여 함수 $g(x)=\\displaystyle\\int_0^x(x-t)f'(t)\\,dt$가 구간 $0\\le x<\\dfrac{\\pi}{2}$에서 극값을 가지지 않게 하는 $a$의 최댓값은? (단, $a$는 양의 상수)",
    options:opts5("$1$","$\\dfrac{1}{2}$","$\\dfrac{1}{3}$","$\\dfrac{1}{4}$","$\\dfrac{1}{5}$"),
    correct:"3",
    explanation:"$\\dfrac{d}{dx}\\!\\int_0^x(x-t)f'(t)\\,dt=\\!\\int_0^x f'(t)\\,dt=f(x)-f(0)=\\tan x-ax^3-x$ (∵ $f(0)=0$).\n극값을 안 가지려면 $g'(x)\\ne 0$, 즉 $\\dfrac{\\tan x-x}{x^3}\\ne a$.\n$h(x)=\\dfrac{\\tan x-x}{x^3}=\\dfrac{1}{3}+\\dfrac{2x^2}{15}+\\cdots$. $h$는 $(0,\\pi/2)$에서 증가함수, $\\lim_{x\\to 0^+}h=\\dfrac{1}{3}$.\n$h$의 치역 $\\left(\\dfrac{1}{3},\\infty\\right)$이므로 $a$가 $\\dfrac{1}{3}$ 이하여야 $h(x)\\ne a$. $a$의 최댓값 $=\\dfrac{1}{3}$.",
  },
  {n:11, subject:"적분학", unit:"급수의 수렴/발산", concept:"멱급수 수렴반경",
    difficulty:"medium",
    question:"수열 $\\langle a_n\\rangle$이 $\\displaystyle\\lim_{n\\to\\infty}\\!\\left|\\dfrac{a_{n+1}}{a_n}\\right|=\\dfrac{1}{R}$을 만족할 때 멱급수 $\\displaystyle\\sum_{n=1}^{\\infty}a_{3n}x^n$의 수렴 반지름은? (단, 모든 자연수 $n$에 대해 $a_n\\ne 0$)",
    options:opts5("$R$","$R^3$","$\\dfrac{1}{R}$","$\\sqrt[3]{R}$","$\\sqrt[3]{\\dfrac{1}{R}}$"),
    correct:"2",
    explanation:"$a_n=(1/R)^n$ (예시)로 가정하면 $a_{3n}=(1/R)^{3n}=((1/R)^3)^n$.\n$\\sum a_{3n}x^n=\\sum((1/R)^3)^n x^n=\\sum(x/R^3)^n$의 수렴반경 $=R^3$.\n[일반화] $\\displaystyle\\lim_{n\\to\\infty}\\!\\left|\\dfrac{a_{3(n+1)}}{a_{3n}}\\right|=\\!\\left|\\dfrac{a_{n+1}}{a_n}\\cdot\\dfrac{a_{n+2}}{a_{n+1}}\\cdot\\dfrac{a_{n+3}}{a_{n+2}}\\right|\\to\\dfrac{1}{R^3}$. 수렴반경 $=R^3$.",
  },
  {n:12, subject:"적분학", unit:"정적분", concept:"적분 점화식",
    difficulty:"hard",
    question:"$I_n=\\displaystyle\\int_0^{\\pi}\\dfrac{\\sin nx}{\\sin x}\\,dx$라고 하자. $I_{n+2}-I_n$의 값을 활용하여 $I_{2023}$의 값을 구하면? (단, $n=1,2,\\ldots$)",
    options:opts5("$0$","$\\dfrac{\\pi}{2}$","$\\pi$","$\\dfrac{3\\pi}{2}$","$2\\pi$"),
    correct:"3",
    explanation:"합차공식 $\\sin nx-\\sin(n-2)x=2\\cos(n-1)x\\sin x$로부터 $\\sin nx=2\\cos(n-1)x\\sin x+\\sin(n-2)x$.\n$\\dfrac{\\sin nx}{\\sin x}=2\\cos(n-1)x+\\dfrac{\\sin(n-2)x}{\\sin x}$ ⇒ $I_n-I_{n-2}=\\!\\int_0^{\\pi}2\\cos(n-1)x\\,dx=0$.\n$I_n=I_{n-2}$. 홀수 $n$에서 $I_n=I_1=\\!\\int_0^{\\pi}1\\,dx=\\pi$. $I_{2023}=\\pi$.",
  },
  {n:13, subject:"다변수함수", unit:"이중적분", concept:"가우스 적분 (극좌표)",
    difficulty:"medium",
    question:"영역 $R_d=\\{(x,y)\\mid x^2+y^2\\le d^2\\}$에서 다음 이중 적분 $S_d$에 대해 $\\displaystyle\\lim_{d\\to\\infty}S_d$의 값은? (단, $\\alpha,\\,d$는 양의 상수)\n$$S_d=\\!\\iint_{R_d}e^{-\\alpha(x^2+y^2)}\\,dA$$",
    options:opts5("$\\dfrac{\\pi}{\\alpha}$","$\\sqrt{\\alpha}\\,\\pi$","$\\alpha\\pi$","$\\sqrt{\\alpha\\pi}$","$\\dfrac{\\sqrt{\\alpha}}{\\alpha}\\pi$"),
    correct:"1",
    explanation:"극좌표: $S_d=\\!\\int_0^{2\\pi}\\!\\!\\int_0^d e^{-\\alpha r^2}r\\,dr\\,d\\theta=2\\pi\\!\\left[-\\dfrac{1}{2\\alpha}e^{-\\alpha r^2}\\right]_0^d=\\dfrac{\\pi}{\\alpha}(1-e^{-\\alpha d^2})$.\n$d\\to\\infty$: $\\dfrac{\\pi}{\\alpha}$.",
  },
  {n:14, subject:"적분학", unit:"정적분의 응용", concept:"회전체 겉넓이",
    difficulty:"medium",
    question:"곡선 $y=\\dfrac{x^2}{4}-\\dfrac{\\ln x}{2}$ ($1\\le x\\le 4$)를 $y$축을 중심으로 회전시켜 얻은 회전체의 겉넓이는?",
    options:opts5("$24\\pi$","$20\\pi$","$16\\pi$","$12\\pi$","$8\\pi$"),
    correct:"1",
    explanation:"$S=2\\pi\\!\\int_1^4 x\\sqrt{1+(y')^2}\\,dx$. $y'=\\dfrac{x}{2}-\\dfrac{1}{2x}$.\n$1+(y')^2=1+\\dfrac{x^2}{4}-\\dfrac{1}{2}+\\dfrac{1}{4x^2}=\\dfrac{x^2}{2}+\\dfrac{1}{2}+\\dfrac{1}{4x^2}=\\!\\left(\\dfrac{x}{2}+\\dfrac{1}{2x}\\right)^2$.\n$S=2\\pi\\!\\int_1^4 x\\!\\left(\\dfrac{x}{2}+\\dfrac{1}{2x}\\right)dx=2\\pi\\!\\int_1^4\\!\\left(\\dfrac{x^2}{2}+\\dfrac{1}{2}\\right)dx=2\\pi\\!\\left[\\dfrac{x^3}{6}+\\dfrac{x}{2}\\right]_1^4=2\\pi\\cdot 12=24\\pi$.",
  },
  {n:15, subject:"적분학", unit:"테일러급수", concept:"역쌍곡함수 매클로린",
    difficulty:"medium",
    question:"함수 $f(x)=\\tanh^{-1}x$일 때 $\\displaystyle\\sum_{k=1}^{5}f^{(k)}(0)$의 값은?",
    options:opts5("$0$","$1$","$3$","$24$","$27$"),
    correct:"5",
    explanation:"$\\tanh^{-1}x=x+\\dfrac{x^3}{3}+\\dfrac{x^5}{5}+\\cdots$. $f^{(k)}(0)=k!\\cdot[x^k\\text{ 계수}]$.\n$f^{(1)}(0)=1\\cdot 1=1,\\,f^{(2)}(0)=0,\\,f^{(3)}(0)=3!\\cdot\\dfrac{1}{3}=2,\\,f^{(4)}(0)=0,\\,f^{(5)}(0)=5!\\cdot\\dfrac{1}{5}=24$.\n합 $=1+0+2+0+24=27$.",
  },
  {n:16, subject:"다변수함수", unit:"편미분", concept:"Case 함수 그래디언트",
    difficulty:"hard",
    question:"다음 함수 $f$는 정의역이 $\\mathbb{R}^2$이고 $\\nabla f(a,b)=(0,0)$일 때, $a+b+c$의 값은? (단, $a,b,c$는 상수)\n$$f(x,y)=\\begin{cases}\\dfrac{xy-x-ay+a}{2x^2-2x(y+1)+y^2+1}&((x,y)\\ne(a,b))\\\\c&((x,y)=(a,b))\\end{cases}$$",
    options:opts5("$2$","$3$","$0$","$1$","$-1$"),
    correct:"1",
    explanation:"분모 $2x^2-2x(y+1)+y^2+1=(x-y)^2+(x-1)^2$. $(x-y)^2+(x-1)^2=0$인 점이 $(a,b)$여야 하므로 $a=1,\\,b=1$.\n분자 $xy-x-y+1=(x-1)(y-1)$. $(x,y)\\ne(1,1)$에서 $f(x,y)=\\dfrac{(x-1)(y-1)}{(x-y)^2+(x-1)^2}$.\n$f_x(1,1)=\\displaystyle\\lim_{h\\to 0}\\dfrac{f(1+h,1)-c}{h}=\\lim_{h\\to 0}\\dfrac{0/(2h^2)-c}{h}=\\lim_{h\\to 0}\\dfrac{-c}{h}=0$이려면 $c=0$.\n$a+b+c=1+1+0=2$.",
  },
  {n:17, subject:"미분학", unit:"부등식", concept:"세 함수 부등식",
    difficulty:"medium",
    question:"부등식 $\\dfrac{x-1}{x}\\le\\dfrac{2\\sqrt{3}}{3}\\sqrt{2x-1}\\le\\dfrac{x}{x-1}$을 풀면 $a<x\\le b$이다. $a+b$의 값은? (단, $a,b$는 상수)",
    options:opts5("$\\dfrac{3}{2}$","$\\dfrac{5}{2}$","$3$","$\\dfrac{7}{2}$","$4$"),
    correct:"3",
    explanation:"$f(x)=\\dfrac{x-1}{x}=1-\\dfrac{1}{x}$ (대칭점 $(0,1)$), $g(x)=\\dfrac{2\\sqrt{3}}{3}\\sqrt{2x-1}$, $h(x)=\\dfrac{x}{x-1}=1+\\dfrac{1}{x-1}$ (대칭점 $(1,1)$).\n$g(x)=h(x)$: $\\dfrac{2\\sqrt{3}}{3}\\sqrt{2x-1}=\\dfrac{x}{x-1}$, 눈치 대입 $x=2$: $\\dfrac{2\\sqrt{3}}{3}\\cdot\\sqrt{3}=2$ ✓.\n그래프 분석: $f\\le g\\le h$ 구간 $1<x\\le 2$. $a=1,\\,b=2$. $a+b=3$.",
  },
  {n:18, subject:"다변수함수", unit:"공간곡선", concept:"공간곡선 길이",
    difficulty:"medium",
    question:"다음 곡선의 길이는? (단, $\\beta$는 양의 상수)\n$$P(t)=(e^t\\sin t,\\,e^t\\cos t,\\,e^t)\\quad(0\\le t\\le\\beta)$$",
    options:opts5("$e^{\\beta}-1$","$\\sqrt{2}(e^{\\beta}-1)$","$\\sqrt{3}(e^{\\beta}-1)$","$2(e^{\\beta}-1)$","$\\sqrt{5}(e^{\\beta}-1)$"),
    correct:"3",
    explanation:"$x'=e^t(\\sin t+\\cos t),\\,y'=e^t(\\cos t-\\sin t),\\,z'=e^t$.\n$(x')^2+(y')^2=e^{2t}\\cdot 2$ (전개 후 합), $(z')^2=e^{2t}$. 합 $=3e^{2t}$.\n$L=\\!\\int_0^{\\beta}\\sqrt{3e^{2t}}\\,dt=\\sqrt{3}\\!\\int_0^{\\beta}e^t\\,dt=\\sqrt{3}(e^{\\beta}-1)$.",
  },
  {n:19, subject:"선형대수", unit:"행렬식", concept:"행렬식 성질 진위판단",
    difficulty:"easy",
    question:"행렬 $A\\in M_{n\\times n}(\\mathbb{R})$의 행렬식에 대해 다음 중 옳지 $\\textbf{않은}$ 것은?\n\nⓐ $A$의 한 행 벡터에 상수 $c$를 곱해서 얻은 행렬 $B$에 대해 $\\det A=c\\det B$이다.\nⓑ $A$가 삼각행렬이면 행렬식은 주대각선 성분들의 곱이다.\nⓒ $A$의 한 열 벡터가 영 벡터이면 행렬식은 $0$이다.\nⓓ 실수 $k$에 대해 $\\det(kA)=k^n\\det A$이다.\nⓔ $A$의 한 행의 상수 배를 다른 행에 더해서 얻은 행렬의 행렬식은 $\\det A$이다.",
    options:opts5("ⓐ","ⓑ","ⓒ","ⓓ","ⓔ"),
    correct:"1",
    explanation:"ⓐ [거짓] 한 행에 $c$를 곱하면 $\\det B=c\\det A$이다 (즉 $\\det A=\\dfrac{1}{c}\\det B$).\nⓑ [참] 삼각행렬의 정의.\nⓒ [참] 영 열을 따라 라플라스 전개.\nⓓ [참] 각 행에서 $k$가 빠져나감.\nⓔ [참] 행연산 III형은 행렬식 불변.",
  },
  {n:20, subject:"다변수함수", unit:"공간곡선", concept:"두 경로 교점 (다른 매개변수)",
    difficulty:"hard",
    question:"두 입자가 다음 공간 곡선을 따라 움직일 때 충돌하지는 않지만, 경로끼리는 두 점에서 교차한다. 교차하는 두 점을 각각 $P,Q$라 할 때 두 벡터 $\\overrightarrow{OP},\\overrightarrow{OQ}$의 내적은? (단, $O$는 원점)\n$$r_1(t)=(t,t^2,t^3),\\quad r_2(t)=(1+2t,1+6t,1+14t)$$",
    options:opts5("$4$","$5$","$6$","$14$","$16$"),
    correct:"4",
    explanation:"매개변수 다르게: $r_1(t)=r_2(s)$. $t=1+2s,\\,t^2=1+6s,\\,t^3=1+14s$.\n첫 번째 식 $t=1+2s$를 둘째에 대입: $(1+2s)^2=1+6s\\Rightarrow 4s^2-2s=0\\Rightarrow s=0$ 또는 $s=1/2$.\n셋째 검증: $(1+2s)^3=1+14s$도 $s=0,\\,1/2$에서 성립.\n$s=0$: $t=1$, $P=(1,1,1)$. $s=1/2$: $t=2$, $Q=(2,4,8)$.\n$\\overrightarrow{OP}\\cdot\\overrightarrow{OQ}=2+4+8=14$.",
  },
  {n:21, subject:"다변수함수", unit:"편미분", concept:"그래디언트와 직교절선",
    difficulty:"medium",
    question:"방 바닥의 온도 분포가 $V(x,y)=20-x^2-2y^2$라고 하자. 개미 한 마리가 점 $(1,-2)$에서 출발해서 온도 $V$가 최대로 증가하는 방향으로 움직인다고 할 때, 개미의 경로는?",
    options:opts5("$y=-2x^4$","$y=-x^4-1$","$y=x^3-3$","$y=-2x^3$","$y=-2x^2$"),
    correct:"5",
    explanation:"등위곡선 $20-x^2-2y^2=c$의 접선 기울기 $\\dfrac{dy}{dx}=-\\dfrac{f_x}{f_y}=-\\dfrac{x}{2y}$.\n최대 증가 방향(직교절선)의 미분방정식: $\\dfrac{dy}{dx}=\\dfrac{2y}{x}$.\n$\\dfrac{dy}{y}=\\dfrac{2dx}{x}\\Rightarrow\\ln|y|=2\\ln|x|+C\\Rightarrow y=Cx^2$.\n$(1,-2)$ 대입: $C=-2$. $y=-2x^2$.",
  },
  {n:22, subject:"미분학", unit:"도함수 응용", concept:"지수함수 극값",
    difficulty:"medium",
    question:"$0<a<1$일 때, 함수 $f(x)=x^{2023}a^{-x}$의 극솟값은?",
    options:opts5("$\\left(\\dfrac{2023}{e\\ln a}\\right)^{2023}$","$\\left(\\dfrac{2023e}{\\ln a}\\right)^{2023}$","$\\left(\\dfrac{2023}{\\ln a}\\right)^{2023}$","$-\\left(\\dfrac{2023}{e\\ln a}\\right)^{2023}$","$-\\left(\\dfrac{2023e}{\\ln a}\\right)^{2023}$"),
    correct:"1",
    explanation:"$f'(x)=x^{2022}a^{-x}(2023-x\\ln a)$. 임계점 $x=0,\\,x=\\dfrac{2023}{\\ln a}$ ($\\ln a<0$이므로 $<0$).\n$x=2023/\\ln a$에서 극소.\n$f\\!\\left(\\dfrac{2023}{\\ln a}\\right)=\\!\\left(\\dfrac{2023}{\\ln a}\\right)^{2023}\\cdot a^{-2023/\\ln a}=\\!\\left(\\dfrac{2023}{\\ln a}\\right)^{2023}\\cdot e^{-2023}=\\!\\left(\\dfrac{2023}{e\\ln a}\\right)^{2023}$.\n($a^{-2023/\\ln a}=e^{-(2023/\\ln a)\\ln a}=e^{-2023}$.)",
  },
  {n:23, subject:"적분학", unit:"급수의 수렴/발산", concept:"급수 진위판단",
    difficulty:"medium",
    question:"다음 중 옳은 것을 모두 고르면?\n\nⓐ 모든 자연수 $n$에 대해 $a_n>0$이고 $a_n\\ge a_{n+1}$이 성립하면 교대급수 $\\displaystyle\\sum_{k=1}^{\\infty}(-1)^{k+1}a_k$는 수렴한다.\nⓑ 급수 $\\displaystyle\\sum_{k=1}^{\\infty}a_k$가 수렴하기 위한 필요충분조건은 부분합의 수열 $\\langle S_n\\rangle$이 유계인 것이다.\nⓒ 모든 자연수 $n$에 대해 $a_n\\le b_n$이고 $\\sum b_n$이 수렴하면 $\\sum a_n$도 수렴한다.\nⓓ 두 급수 $\\sum a_n,\\,\\sum b_n$이 수렴하면 $\\sum a_n b_n$도 수렴한다.",
    options:opts5("ⓐ","ⓐ, ⓑ","ⓐ, ⓑ, ⓒ","ⓐ, ⓑ, ⓒ, ⓓ","없음"),
    correct:"5",
    explanation:"ⓐ [거짓] $a_n\\to 0$ 조건이 빠짐. 반례 $a_n=3$.\nⓑ [거짓] 양항 조건 필요. 반례 $a_n=(-1)^n/n$ 부분합 유계지만 부분합 진동.\nⓒ [거짓] 양항 조건 필요. 반례 $a_n=-n,\\,b_n=0$.\nⓓ [거짓] 반례 $a_n=b_n=(-1)^n/\\sqrt{n}$. 둘 다 수렴하지만 $\\sum a_n b_n=\\sum 1/n$ 발산.\n옳은 것 없음.",
  },
  {n:24, subject:"다변수함수", unit:"이중적분", concept:"선형 변수변환",
    difficulty:"medium",
    question:"영역 $R$은 네 꼭짓점이 $(1,0),\\,(2,0),\\,(0,-2),\\,(0,-1)$인 사다리꼴일 때 다음 적분의 값은?\n$$\\iint_R\\cos\\!\\left(\\dfrac{x+y}{x-y}\\right)dA$$",
    options:opts5("$\\dfrac{1}{2}\\sin(1)$","$\\dfrac{3}{2}\\sin(1)$","$\\dfrac{2}{3}\\sin(1)$","$\\sqrt{2}\\sin(1)$","$\\dfrac{\\sqrt{2}}{2}\\sin(1)$"),
    correct:"2",
    explanation:"$u=x+y,\\,v=x-y$. 자코비안 $|\\partial(x,y)/\\partial(u,v)|=1/2$.\n사다리꼴 → $uv$평면 사다리꼴: $u\\in[-v,v],\\,v\\in[1,2]$.\n$\\!\\iint\\cos(u/v)\\cdot\\dfrac{1}{2}du\\,dv=\\dfrac{1}{2}\\!\\int_1^2[v\\sin(u/v)]_{-v}^{v}\\,dv=\\dfrac{1}{2}\\!\\int_1^2 2v\\sin 1\\,dv=\\sin 1\\cdot\\dfrac{[v^2]_1^2}{2}=\\dfrac{3}{2}\\sin 1$.",
  },
  {n:25, subject:"다변수함수", unit:"극좌표와 극곡선", concept:"극좌표 곡선의 접선 기울기",
    difficulty:"medium",
    question:"다음 두 곡선은 제1사분면에서 한 점에서 만난다. 그 교점에서 곡선 ⓑ의 접선의 기울기는?\n\nⓐ $x^2+\\!\\left(y-\\dfrac{1}{2}\\right)^2=\\dfrac{1}{4}$\nⓑ $r=\\sin 2\\theta$",
    options:opts5("$\\dfrac{\\sqrt{3}}{2}$","$\\dfrac{\\sqrt{3}}{5}$","$\\sqrt{2}$","$\\dfrac{\\sqrt{2}}{3}$","$\\dfrac{2\\sqrt{2}}{5}$"),
    correct:"2",
    explanation:"ⓐ를 극방정식으로: $r=\\sin\\theta$.\n교점: $\\sin 2\\theta=\\sin\\theta\\Rightarrow 2\\sin\\theta\\cos\\theta=\\sin\\theta\\Rightarrow\\theta=\\pi/3$ (제1사분면).\n극좌표 접선 기울기: $\\tan\\alpha=\\tan(\\theta+\\phi)=\\dfrac{\\tan\\theta+\\tan\\phi}{1-\\tan\\theta\\tan\\phi}$, $\\tan\\phi=\\dfrac{r}{r'}$.\n$\\theta=\\pi/3$, $\\tan\\theta=\\sqrt{3}$. $r'=2\\cos 2\\theta$, $\\tan\\phi=\\dfrac{\\sin 2\\theta}{2\\cos 2\\theta}=\\dfrac{1}{2}\\tan 2\\theta\\big|_{\\pi/3}=-\\dfrac{\\sqrt{3}}{2}$.\n$\\tan\\alpha=\\dfrac{\\sqrt{3}-\\sqrt{3}/2}{1+\\sqrt{3}\\cdot(\\sqrt{3}/2)}=\\dfrac{\\sqrt{3}/2}{5/2}=\\dfrac{\\sqrt{3}}{5}$.",
  },
  {n:26, subject:"다변수함수", unit:"삼중적분", concept:"구면좌표 삼중적분",
    difficulty:"medium",
    question:"구면 $\\rho=1$의 내부와 원뿔면 $\\phi=\\dfrac{\\pi}{3}$의 내부로 이루어진 영역 $Q$에서 다음 삼중 적분의 값은?\n$$\\iiint_Q\\sqrt{x^2+y^2+z^2}\\,dV$$",
    options:opts5("$\\pi$","$\\dfrac{\\pi}{2}$","$\\dfrac{\\pi}{4}$","$\\dfrac{\\pi}{5}$","$\\dfrac{\\pi}{6}$"),
    correct:"3",
    explanation:"구면좌표: $\\sqrt{x^2+y^2+z^2}=\\rho$, $dV=\\rho^2\\sin\\phi\\,d\\rho\\,d\\phi\\,d\\theta$.\n$\\!\\int_0^{2\\pi}\\!\\!\\int_0^{\\pi/3}\\!\\!\\int_0^1\\rho^3\\sin\\phi\\,d\\rho\\,d\\phi\\,d\\theta=2\\pi\\cdot[-\\cos\\phi]_0^{\\pi/3}\\cdot\\dfrac{1}{4}=2\\pi\\cdot\\dfrac{1}{2}\\cdot\\dfrac{1}{4}=\\dfrac{\\pi}{4}$.",
  },
  {n:27, subject:"적분학", unit:"부정적분", concept:"sec^n 점화식",
    difficulty:"medium",
    question:"$I_n=\\displaystyle\\int\\sec^n x\\,dx$이라 할 때 $(n-1)I_n-(n-2)I_{n-2}$를 나타내는 식은? (단, $C$는 적분 상수이고 $n=2,3,\\ldots$)",
    options:opts5("$\\sec^{n-2}x\\cdot\\tan x+C$","$\\sec^{n-1}x\\cdot\\tan x+C$","$\\sec x\\cdot\\tan^{n-1}x+C$","$\\sec x\\cdot\\tan^{n-2}x+C$","$\\tan x+C$"),
    correct:"1",
    explanation:"부분적분 ($u=\\sec^{n-2}x,\\,dv=\\sec^2 x\\,dx$):\n$I_n=\\sec^{n-2}x\\tan x-(n-2)\\!\\int\\sec^{n-2}x\\tan^2 x\\,dx=\\sec^{n-2}x\\tan x-(n-2)(I_n-I_{n-2})$.\n정리: $(n-1)I_n=\\sec^{n-2}x\\tan x+(n-2)I_{n-2}$.\n$(n-1)I_n-(n-2)I_{n-2}=\\sec^{n-2}x\\tan x+C$.",
  },
  {n:28, subject:"다변수함수", unit:"공간곡선", concept:"호의 길이 재매개화",
    difficulty:"hard",
    question:"다음 곡선 $P(t)$를 $(0,0,1)$로부터 측정한 호의 길이 $s$로 재매개화 할 때, $\\vec{i}$ 성분을 나타낸 식은?\n$$P(t)=\\sqrt{2}t^2\\,\\vec{i}+(\\sin t-t\\cos t)\\,\\vec{j}+(\\cos t+t\\sin t)\\,\\vec{k}\\quad(t\\ge 0)$$",
    options:opts5("$\\sqrt{2}\\,s$","$\\dfrac{\\sqrt{2}}{2}\\,s$","$\\dfrac{\\sqrt{6}}{3}\\,s$","$\\dfrac{2\\sqrt{2}}{3}\\,s$","$\\sqrt{3}\\,s$"),
    correct:"4",
    explanation:"$x'=2\\sqrt{2}t,\\,y'=t\\sin t,\\,z'=t\\cos t$. $|P'|^2=8t^2+t^2(\\sin^2 t+\\cos^2 t)=9t^2$. $|P'|=3t$.\n$s=\\!\\int_0^t 3u\\,du=\\dfrac{3t^2}{2}\\Rightarrow t^2=\\dfrac{2s}{3}$.\n$x(t)=\\sqrt{2}t^2=\\sqrt{2}\\cdot\\dfrac{2s}{3}=\\dfrac{2\\sqrt{2}}{3}s$.",
  },
  {n:29, subject:"선형대수", unit:"고유치와 대각화", concept:"2×2 행렬 서로 다른 고유치 조건",
    difficulty:"medium",
    question:"행렬 $\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}\\in M_{2\\times 2}(\\mathbb{R})$가 서로 다른 2개의 고윳값을 가지는 필요충분조건은?",
    options:opts5("$ad-bc>0$","$(a-d)^2+4bc>0$","$a+d>0$","$bc>0$","$ad-bc<0$"),
    correct:"2",
    explanation:"특성다항식 $\\lambda^2-(a+d)\\lambda+(ad-bc)=0$의 판별식 $D=(a+d)^2-4(ad-bc)=(a-d)^2+4bc$.\n$\\mathbb{R}$에서 서로 다른 두 실수 고유치 $\\Leftrightarrow D>0\\Leftrightarrow(a-d)^2+4bc>0$.\n[주의] 본 문제는 \"필요충분조건\"으로 출제되어 엄밀하게는 복소 고유치(서로 다른 켤레쌍, $D<0$) 경우도 포함될 수 있어 정답이 없다는 견해도 있음. 광운대 공식 정답은 (2)로 처리.",
  },
  {n:30, subject:"미분학", unit:"종합", concept:"주기함수·기함수 진위판단",
    difficulty:"medium",
    question:"다음 중 $\\textbf{참}$인 명제의 개수는?\n\nⓐ 함수 $f$와 $g$가 모두 주기함수이면 함수 $f+g$도 주기함수이다.\nⓑ 함수 $f+g$가 주기함수이면 함수 $f$와 $g$ 중 적어도 하나는 주기함수이다.\nⓒ 함수 $f$가 주기함수이면 $f$는 유계이다.\nⓓ 함수 $f+g$가 기함수이면 함수 $f$와 $g$ 중 적어도 하나는 기함수이다.\nⓔ 함수 $f$와 $g$가 모두 기함수이면 $f+g$도 기함수이다.",
    options:opts5("4개","3개","2개","1개","0개"),
    correct:"4",
    explanation:"ⓐ [거짓] 두 주기의 최소공배수가 없으면 주기함수 아님. 반례 $\\sin x+\\sin(\\pi x)$.\nⓑ [거짓] 반례 $f(x)=x,\\,g(x)=-x+\\cos x$. $f+g=\\cos x$ 주기함수, 그러나 둘 다 주기함수 아님.\nⓒ [거짓] 반례 $\\tan x$.\nⓓ [거짓] 반례 $f=x^2,\\,g=-x^2+x$. $f+g=x$ 기함수, 그러나 둘 다 기함수 아님.\nⓔ [참] $h(-x)=f(-x)+g(-x)=-f(x)-g(x)=-h(x)$.\n참 1개.",
  },
];

const TOTAL=PROBLEMS.length;
console.log(`총 ${TOTAL}문제 (객관식) 준비됨`);

const rows = PROBLEMS.map(p => {
  const id = `q-${YEAR}-${SCHOOL_EN}-${String(p.n).padStart(2,"0")}`;
  return {
    id, subject: p.subject, unit: p.unit, concept: p.concept, difficulty: p.difficulty,
    source_type: "imported", pool: "general", question: p.question, content_type: "latex",
    question_image: null, question_type: "multiple_choice",
    options: p.options, correct_option_id: p.correct,
    answer_text: null, explanation: p.explanation, explanation_content_type: "latex",
    explanation_image: null,
    tags: [YEAR, SCHOOL_KO, "past_exam", p.subject, p.unit, p.concept],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  };
});

const { data, error } = await sb.from("questions").upsert(rows, { onConflict: "id" }).select("id");
if (error) { console.error("업로드 실패:", error); process.exit(1); }
console.log(`업로드 완료: ${data.length}건`);
