// 2024년 단국대 오후 편입수학 객관식 20문항 (4지선다, 문항 번호 31~50)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR_ID="2024pm", YEAR_KO="2024", SESSION_KO="오후", SCHOOL_KO="단국대", SCHOOL_EN="dankook";
const opts4 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:31, subject:"다변수함수", unit:"음함수와 편미분", concept:"음함수 접선",
    difficulty:"easy",
    question:"곡선 $x^3+y^3=6xy$ 위의 점 $(3,3)$에 접하는 직선의 방정식은?",
    options:opts4("$x-y=0$","$x+y=6$","$3x-y=6$","$3x+y=12$"),
    correct:"2",
    explanation:"음함수 미분: $3x^2+3y^2 y'=6y+6xy'\\Rightarrow y'=\\dfrac{6y-3x^2}{3y^2-6x}\\big|_{(3,3)}=\\dfrac{18-27}{27-18}=-1$.\n접선: $y-3=-1(x-3)\\Rightarrow x+y=6$.",
  },
  {n:32, subject:"미분학", unit:"도함수 응용", concept:"폐구간 최대·최솟값",
    difficulty:"easy",
    question:"닫힌구간 $[-3,2]$에서 함수 $f(x)=x^3+3x^2-4$의 최댓값을 $a$, 최솟값을 $b$라 할 때 $a+b$의 값은?",
    options:opts4("$-12$","$-4$","$4$","$12$"),
    correct:"4",
    explanation:"양 끝점: $f(-3)=-4,\\,f(2)=16$.\n임계점: $f'(x)=3x^2+6x=3x(x+2)=0\\Rightarrow x=0,\\,-2$. $f(0)=-4,\\,f(-2)=0$.\n최대 $a=16$, 최소 $b=-4$. $a+b=12$.",
  },
  {n:33, subject:"적분학", unit:"정적분", concept:"적분 순서 변경",
    difficulty:"medium",
    question:"$f(x)=\\displaystyle\\int_0^x e^{\\sin t}\\,dt$일 때, $\\displaystyle\\int_0^{\\pi/2}f(x)\\sin x\\,dx$의 값은?",
    options:opts4("$e+1$","$e$","$e-1$","$e-2$"),
    correct:"3",
    explanation:"이중적분 변환: $\\!\\int_0^{\\pi/2}\\!\\!\\int_0^x e^{\\sin t}\\sin x\\,dt\\,dx$ → 순서 변경 → $\\!\\int_0^{\\pi/2}\\!\\!\\int_t^{\\pi/2}e^{\\sin t}\\sin x\\,dx\\,dt$\n$=\\!\\int_0^{\\pi/2}e^{\\sin t}[-\\cos x]_t^{\\pi/2}\\,dt=\\!\\int_0^{\\pi/2}\\cos t\\cdot e^{\\sin t}\\,dt=[e^{\\sin t}]_0^{\\pi/2}=e-1$.",
  },
  {n:34, subject:"적분학", unit:"정적분의 응용", concept:"회전체 부피 (평행이동)",
    difficulty:"medium",
    question:"두 곡선 $y=x$와 $y=x^2$으로 둘러싸인 영역을 직선 $y=a$ ($a>1$)를 축으로 한 바퀴 회전시켜 얻은 입체의 부피가 $\\dfrac{8\\pi}{15}$일 때, 실수 $a$의 값은?",
    options:opts4("$\\dfrac{3}{2}$","$2$","$\\dfrac{5}{2}$","$3$"),
    correct:"2",
    explanation:"$y$축으로 $-a$ 평행이동 후 $y=0$ 축으로 회전 동등.\n$V=\\pi\\!\\int_0^1[(x^2-a)^2-(x-a)^2]\\,dx=\\pi\\!\\left(\\dfrac{1}{5}-\\dfrac{2a+1}{3}+a\\right)=\\dfrac{8\\pi}{15}$.\n정리: $a=2$.",
  },
  {n:35, subject:"적분학", unit:"급수의 수렴/발산", concept:"수렴 급수 식별",
    difficulty:"medium",
    question:"다음 중 수렴하는 급수의 개수는?\n\n㉠ $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{(-1)^{n+1}n}{n^2+1}$\n㉡ $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{\\sqrt{n}}{n^2+1}$\n㉢ $\\displaystyle\\sum_{n=2}^{\\infty}\\dfrac{1}{n\\ln n}$\n㉣ $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{n2^n}{4n^3+1}$",
    options:opts4("$0$","$1$","$2$","$3$"),
    correct:"3",
    explanation:"㉠ [수렴] 교대급수, $n/(n^2+1)\\to 0$ 단조감소.\n㉡ [수렴] $\\sqrt{n}/(n^2+1)\\sim 1/n^{3/2}$, $p=3/2>1$.\n㉢ [발산] 적분판정법: $\\!\\int dt/(n\\ln n)$ 발산.\n㉣ [발산] $n2^n/(4n^3+1)\\sim 2^n/(4n^2)\\to\\infty$.\n수렴: ㉠, ㉡ 2개.",
  },
  {n:36, subject:"다변수함수", unit:"극좌표와 극곡선", concept:"극곡선 길이",
    difficulty:"medium",
    question:"극방정식으로 표현된 곡선 $r=\\theta^2$ ($0\\le\\theta\\le\\sqrt{5}$)의 길이는?",
    options:opts4("$\\dfrac{16}{3}$","$\\dfrac{19}{3}$","$\\dfrac{22}{3}$","$\\dfrac{25}{3}$"),
    correct:"2",
    explanation:"$L=\\!\\int_0^{\\sqrt{5}}\\sqrt{r^2+(r')^2}\\,d\\theta=\\!\\int_0^{\\sqrt{5}}\\theta\\sqrt{\\theta^2+4}\\,d\\theta$.\n$u=\\theta^2+4$ 치환: $L=\\dfrac{1}{2}\\!\\left[\\dfrac{2}{3}(\\theta^2+4)^{3/2}\\right]_0^{\\sqrt{5}}=\\dfrac{1}{3}(27-8)=\\dfrac{19}{3}$.",
  },
  {n:37, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"수직 직선과 평면 교점",
    difficulty:"medium",
    question:"점 $(-2,1,0)$을 지나는 직선이 세 점 $(1,1,-1),\\,(2,-1,0),\\,(3,0,2)$를 지나는 평면과 수직으로 만난다. 이 교점을 $(a,b,c)$라고 할 때, $a+b+c$의 값은?",
    options:opts4("$\\dfrac{19}{35}$","$\\dfrac{22}{35}$","$\\dfrac{5}{7}$","$\\dfrac{4}{5}$"),
    correct:"1",
    explanation:"평면 법선: $(1,-2,1)\\times(2,-1,3)=(-5,-1,3)\\sim(5,1,-3)$. 평면식: $5x+y-3z=9$ ($(2,-1,0)$ 대입).\n$(-2,1,0)$ 지나고 방향 $(5,1,-3)$인 직선: $(5t-2,t+1,-3t)$.\n평면 대입: $5(5t-2)+(t+1)-3(-3t)=9\\Rightarrow 35t-9=9\\Rightarrow t=18/35$.\n$a+b+c=(5t-2)+(t+1)+(-3t)=3t-1=3\\cdot 18/35-1=19/35$.",
  },
  {n:38, subject:"다변수함수", unit:"편미분", concept:"그래디언트 + 최대변화율",
    difficulty:"medium",
    question:"점 $(2,-1,1)$에서 함수 $f(x,y,z)=x^2+y^2-4z$가 가장 빨리 증가하는 방향은 $a\\vec{i}+b\\vec{j}+c\\vec{k}$의 방향이고 최대변화율은 $d$이다. $\\dfrac{cd}{a+b}$의 값은? (단, $a,b,c,d$는 실수)",
    options:opts4("$-6$","$-9$","$-12$","$-15$"),
    correct:"3",
    explanation:"$\\nabla f=(2x,2y,-4)\\big|_{(2,-1,1)}=(4,-2,-4)$. $(a,b,c)\\parallel(4,-2,-4)$: $a=4k,\\,b=-2k,\\,c=-4k$.\n최대변화율 $d=|\\nabla f|=\\sqrt{16+4+16}=6$.\n$\\dfrac{cd}{a+b}=\\dfrac{(-4k)\\cdot 6}{4k-2k}=\\dfrac{-24k}{2k}=-12$.",
  },
  {n:39, subject:"다변수함수", unit:"이중적분", concept:"적분 영역 상식상상",
    difficulty:"medium",
    question:"$\\displaystyle\\int_0^1\\!\\!\\int_{\\sqrt{y}}^1\\sqrt{x^3+1}\\,dx\\,dy=\\dfrac{2}{9}(a^3-1)$일 때, 실수 $a$의 값은?",
    options:opts4("$\\sqrt{2}$","$\\sqrt{3}$","$2$","$\\sqrt{5}$"),
    correct:"1",
    explanation:"순서 변경: $0\\le y\\le x^2,\\,0\\le x\\le 1$. $\\!\\int_0^1\\!\\!\\int_0^{x^2}\\sqrt{x^3+1}\\,dy\\,dx=\\!\\int_0^1 x^2\\sqrt{x^3+1}\\,dx=\\dfrac{1}{3}\\cdot\\dfrac{2}{3}[(x^3+1)^{3/2}]_0^1=\\dfrac{2}{9}(2\\sqrt{2}-1)$.\n$a^3=2\\sqrt{2}=2^{3/2}\\Rightarrow a=\\sqrt{2}$.",
  },
  {n:40, subject:"다변수함수", unit:"다변수 극값", concept:"제약영역 극값 + 최대·최솟값",
    difficulty:"hard",
    question:"다음은 꼭짓점이 $(2,0),(0,2),(0,-2)$인 삼각형과 그 내부를 정의역으로 하는 함수 $f(x,y)=x^2+y^2-2x$에 대한 설명이다. $a+b$의 값은?\n\n(가) 삼각형 내부에 있는 $f$의 극점의 개수는 $a$이다.\n(나) $f$의 최댓값과 최솟값의 차는 $b$이다.",
    options:opts4("$6$","$7$","$8$","$9$"),
    correct:"1",
    explanation:"(가) 임계점 $(1,0)$ ∈ 삼각형 내부. $f_{xx}=2,\\,f_{yy}=2,\\,f_{xy}=0$ → 극소. $a=1$.\n(나) $f=(x-1)^2+y^2-1$. 영역의 점 $(1,0)$에서의 거리² $-1$.\n최소: $(1,0)$에서 거리=0, $f=-1$.\n최대: $(0,2)$ 또는 $(0,-2)$에서 거리=$\\sqrt{5}$, $f=5-1=4$. $b=4-(-1)=5$.\n$a+b=1+5=6$.",
  },
  {n:41, subject:"다변수함수", unit:"이중적분", concept:"변수변환 (xy=u, y/x=v)",
    difficulty:"hard",
    question:"영역 $R=\\!\\left\\{(x,y)\\,\\bigg|\\,1\\le xy\\le 4,\\,\\dfrac{1}{4}\\le\\dfrac{y}{x}\\le 2,\\,x>0\\right\\}$일 때, 이중적분 $\\displaystyle\\iint_R e^{-xy/2}\\,dA$의 값은?",
    options:opts4("$(e^2-e^{1/2})\\ln 4$","$(e^{-1/2}-e^{-2})\\ln 4$","$(e^2-e^{1/2})\\ln 8$","$(e^{-1/2}-e^{-2})\\ln 8$"),
    correct:"4",
    explanation:"$xy=u,\\,y/x=v$로 치환: $1\\le u\\le 4,\\,1/4\\le v\\le 2$. 자코비안 $|J|=1/(2v)$.\n$\\!\\iint e^{-u/2}\\cdot\\dfrac{1}{2v}\\,du\\,dv=\\dfrac{1}{2}[\\ln v]_{1/4}^2[-2e^{-u/2}]_1^4=\\dfrac{1}{2}(\\ln 2+\\ln 4)\\cdot 2(e^{-1/2}-e^{-2})$\n$=(\\ln 8)(e^{-1/2}-e^{-2})$.",
  },
  {n:42, subject:"다변수함수", unit:"공간곡면", concept:"평면 위 삼각형 면적분",
    difficulty:"medium",
    question:"세 점 $A(a,0,0),\\,B(0,a,0),\\,C(0,0,a)$를 포함하는 평면에서 삼각형 $ABC$와 그 내부영역을 $T$라 하자. $\\displaystyle\\iint_T x\\,dS=\\dfrac{4\\sqrt{3}}{3}$일 때, 양의 실수 $a$의 값은?",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"2",
    explanation:"중심 $\\bar x=a/3$. 삼각형 면적 $=\\dfrac{1}{2}|\\vec{AB}\\times\\vec{AC}|=\\dfrac{1}{2}|a^2(-1,-1,-1)\\cdot$... 계산$|=\\dfrac{a^2\\sqrt{3}}{2}$.\n$\\!\\iint x\\,dS=\\bar x\\cdot$면적 $=\\dfrac{a}{3}\\cdot\\dfrac{a^2\\sqrt{3}}{2}=\\dfrac{a^3\\sqrt{3}}{6}=\\dfrac{4\\sqrt{3}}{3}\\Rightarrow a^3=8\\Rightarrow a=2$.",
  },
  {n:43, subject:"다변수함수", unit:"선적분", concept:"그린 정리",
    difficulty:"medium",
    question:"곡선 $C$는 영역 $y=e^{x^2}$, $x$축, $x=1$로 둘러싸인 부분의 경계를 점 $(0,1)$에서 출발하여 시계 반대 방향으로 한 바퀴 돈 뒤 다시 점 $(0,1)$로 돌아오는 경로이다. 벡터장 $\\vec{F}(x,y)=\\langle\\sin y,\\,x^2+x\\cos y\\rangle$에 대하여, 선적분 $\\displaystyle\\int_C\\vec{F}\\cdot d\\vec{r}$의 값은?",
    options:opts4("$\\dfrac{e}{2}-1$","$\\dfrac{e-1}{2}$","$e-1$","$e$"),
    correct:"3",
    explanation:"그린 정리: $\\!\\iint_D(Q_x-P_y)\\,dA=\\!\\iint_D(2x+\\cos y-\\cos y)\\,dA=\\!\\iint_D 2x\\,dA$.\n영역: $0\\le x\\le 1,\\,0\\le y\\le e^{x^2}$.\n$\\!\\int_0^1\\!\\!\\int_0^{e^{x^2}}2x\\,dy\\,dx=\\!\\int_0^1 2xe^{x^2}\\,dx=[e^{x^2}]_0^1=e-1$.",
  },
  {n:44, subject:"다변수함수", unit:"공간곡면", concept:"가우스 발산정리",
    difficulty:"medium",
    question:"곡면 $S$는 원기둥 $x^2+y^2=1$과 두 평면 $z=1,\\,z=-1$로 둘러싸인 입체의 경계면이다. 벡터장 $\\vec{F}(x,y,z)=(xy^2+\\sin z)\\vec{i}+x^2 y\\vec{j}+e^{x+y}\\vec{k}$일 때, $\\displaystyle\\iint_S\\vec{F}\\cdot d\\vec{S}$의 값은? (단, 곡면의 방향은 점 $(0,0,1)$에서 벡터 $\\langle 0,0,1\\rangle$의 방향)",
    options:opts4("$\\dfrac{\\pi}{4}$","$\\dfrac{\\pi}{3}$","$\\dfrac{\\pi}{2}$","$\\pi$"),
    correct:"4",
    explanation:"발산정리: $\\nabla\\cdot\\vec{F}=y^2+x^2+0=x^2+y^2$.\n$\\!\\iiint_T(x^2+y^2)\\,dV=\\!\\int_{-1}^1\\!\\!\\iint_D(x^2+y^2)\\,dA\\,dz=2\\!\\iint_D(x^2+y^2)\\,dA=2\\cdot\\dfrac{\\pi}{2}=\\pi$\n($x^2+y^2\\le 1$ 위 $\\!\\iint(x^2+y^2)dA=\\pi/2$).",
  },
  {n:45, subject:"선형대수", unit:"고유치와 대각화", concept:"대각화 + 랭크",
    difficulty:"medium",
    question:"$5$차 정사각행렬 $A$는 대각화 가능하고 두 개의 고윳값 $1$과 $2$만을 갖는다. 행렬 $A-I$의 랭크(rank)가 $4$일 때, $A-2I$의 랭크는? (단, $I$는 단위행렬)",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"1",
    explanation:"$\\text{rank}(A-I)=4\\Rightarrow$ null$(A-I)=1$ ⇒ $\\lambda=1$ 고유공간 차원 1.\n대각화 가능 + 5차이므로 $\\lambda=2$ 고유공간 차원 $=5-1=4$.\n따라서 null$(A-2I)=4$, $\\text{rank}(A-2I)=5-4=1$.",
  },
  {n:46, subject:"선형대수", unit:"선형변환", concept:"3변수 선형변환 (행 축약)",
    difficulty:"medium",
    question:"선형변환 $T:\\mathbb{R}^3\\to\\mathbb{R}^2$가 다음을 만족시킨다.\n$$T(\\langle 1,1,1\\rangle)=\\langle 1,0\\rangle,\\quad T(\\langle 1,1,0\\rangle)=\\langle 2,-1\\rangle,\\quad T(\\langle 1,0,0\\rangle)=\\langle 4,3\\rangle$$\n$T(\\langle k,-3.5\\rangle)=\\langle 9,m\\rangle$일 때, $k+m$의 값은?",
    options:opts4("$19$","$21$","$23$","$25$"),
    correct:"4",
    explanation:"행 축약으로 표준 기저의 상 결정: $T(1,0,0)=(4,3),\\,T(0,1,0)=(2,-1)-(4,3)=(-2,-4),\\,T(0,0,1)=(1,0)-(2,-1)=(-1,1)$.\n변환 행렬 $\\begin{pmatrix}4&-2&-1\\\\3&-4&1\\end{pmatrix}$.\n$T(k,-3,5)=(4k+6-5,3k+12+5)=(4k+1,3k+17)=(9,m)$.\n$4k+1=9\\Rightarrow k=2,\\,m=3\\cdot 2+17=23$. $k+m=25$.",
  },
  {n:47, subject:"선형대수", unit:"행렬", concept:"부분공간 판정 (4보기)",
    difficulty:"hard",
    question:"성분이 모두 실수인 $2$차 정사각행렬 전체의 집합을 $M(R)$이라 하자. 다음 $W_1,W_2,W_3,W_4$ 중 벡터공간 $M(R)$의 부분공간이 되는 것의 개수는?\n\n$W_1=\\{A\\in M(R)\\mid A^2=A\\}$\n$W_2=\\{A\\in M(R)\\mid\\det(A)=0\\}$\n$W_3=\\{A\\in M(R)\\mid\\mathrm{tr}(A^T A)=0\\}$\n$W_4=\\{A\\in M(R)\\mid A^T=A\\}$",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"2",
    explanation:"$W_1$ [X] $A^2=A,\\,B^2=B$이지만 $(A+B)^2\\ne A+B$ 일반.\n$W_2$ [X] $|A|=|B|=0$이어도 $|A+B|\\ne 0$ 가능.\n$W_3$ [O] $\\mathrm{tr}(A^T A)=\\sum a_{ij}^2=0\\Leftrightarrow A=O$. 영행렬만 모임 ⇒ $\\{O\\}$ 부분공간.\n$W_4$ [O] 대칭행렬 부분공간 (당연).\n2개.",
  },
  {n:48, subject:"미분학", unit:"미분방정식", concept:"1계 선형 ODE",
    difficulty:"medium",
    question:"미분방정식 $x\\,dy+(xy+2y-2e^{-x})\\,dx=0,\\,y(1)=0$의 해 $y=y(x)$에 대하여 $y(2)$의 값은?",
    options:opts4("$\\dfrac{3e^2}{4}$","$\\dfrac{3}{4e^2}$","$\\dfrac{3e^2}{2}$","$\\dfrac{3}{2e^2}$"),
    correct:"2",
    explanation:"양변 $x$로 나눔: $y'+\\!\\left(1+\\dfrac{2}{x}\\right)y=\\dfrac{2e^{-x}}{x}$. 적분인자 $e^{x}\\cdot x^2$.\n$(x^2 e^x y)'=2xe^x\\cdot e^{-x}\\cdot x... $ 실은 $\\dfrac{2e^{-x}}{x}\\cdot x^2 e^x=2x$.\n$x^2 e^x y=x^2+C$. $y(1)=0\\Rightarrow 0+C=1\\Rightarrow C=-1$.\n$y=\\dfrac{x^2-1}{x^2 e^x}\\Big|_{x=2}=\\dfrac{3}{4e^2}$.",
  },
  {n:49, subject:"미분학", unit:"미분방정식", concept:"코시-오일러 방정식",
    difficulty:"medium",
    question:"미분방정식 $x^2 y''+xy'+y=0$ ($x>0$), $y(1)=1,\\,y'(1)=2$의 해 $y=y(x)$에 대하여 $y(2)-y'(2)$의 값은?",
    options:opts4("$\\dfrac{3}{2}\\sin(\\ln 2)$","$\\dfrac{3}{2}\\cos(\\ln 2)$","$\\dfrac{5}{2}\\sin(\\ln 2)$","$\\dfrac{5}{2}\\cos(\\ln 2)$"),
    correct:"3",
    explanation:"코시-오일러 보조: $r(r-1)+r+1=r^2+1=0\\Rightarrow r=\\pm i$.\n$y=c_1\\cos(\\ln x)+c_2\\sin(\\ln x)$. $y(1)=c_1=1$. $y'=\\!\\left[-c_1\\sin+c_2\\cos\\right]/x$, $y'(1)=c_2=2$.\n$y(2)=\\cos(\\ln 2)+2\\sin(\\ln 2),\\,y'(2)=\\dfrac{-\\sin(\\ln 2)+2\\cos(\\ln 2)}{2}$.\n$y(2)-y'(2)=\\cos(\\ln 2)+2\\sin(\\ln 2)+\\dfrac{\\sin(\\ln 2)}{2}-\\cos(\\ln 2)=\\dfrac{5}{2}\\sin(\\ln 2)$.",
  },
  {n:50, subject:"적분학", unit:"라플라스 변환", concept:"부분분수 + 역라플라스",
    difficulty:"medium",
    question:"함수 $F(s)=\\dfrac{s}{(s^2+4)(s+2)}$의 역라플라스변환(inverse Laplace transform)은?",
    options:opts4("$\\cos 2t-\\sin 2t-e^{-2t}$","$\\dfrac{1}{2}(\\cos 2t+\\sin 2t-e^{-2t})$","$\\dfrac{1}{3}(\\cos 2t-\\sin 2t-e^{-2t})$","$\\dfrac{1}{4}(\\cos 2t+\\sin 2t-e^{-2t})$"),
    correct:"4",
    explanation:"부분분수: $\\dfrac{s}{(s^2+4)(s+2)}=\\dfrac{As+B}{s^2+4}+\\dfrac{C}{s+2}$.\n$s\\to-2$: $-2/8=C\\Rightarrow C=-1/4$. 비교: $A=1/4,\\,B=1/2$.\n$F=\\dfrac{1}{4}\\!\\left(\\dfrac{s}{s^2+4}+\\dfrac{2}{s^2+4}-\\dfrac{1}{s+2}\\right)$.\n$f(t)=\\dfrac{1}{4}(\\cos 2t+\\sin 2t-e^{-2t})$.",
  },
];

const TOTAL=PROBLEMS.length;
console.log(`총 ${TOTAL}문제 (객관식 4지선다) 준비됨`);

const rows = PROBLEMS.map(p => {
  const id = `q-${YEAR_ID}-${SCHOOL_EN}-${String(p.n).padStart(2,"0")}`;
  return {
    id, subject: p.subject, unit: p.unit, concept: p.concept, difficulty: p.difficulty,
    source_type: "imported", pool: "general", question: p.question, content_type: "latex",
    question_image: null, question_type: "multiple_choice",
    options: p.options, correct_option_id: p.correct,
    answer_text: null, explanation: p.explanation, explanation_content_type: "latex",
    explanation_image: null,
    tags: [YEAR_KO, SCHOOL_KO, SESSION_KO, "past_exam", p.subject, p.unit, p.concept],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  };
});

const { data, error } = await sb.from("questions").upsert(rows, { onConflict: "id" }).select("id");
if (error) { console.error("업로드 실패:", error); process.exit(1); }
console.log(`업로드 완료: ${data.length}건`);
