// 2022년 광운대 편입수학 객관식 30문항 (5지선다)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR="2022", SCHOOL_KO="광운대", SCHOOL_EN="kwangwoon";
const opts5 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:1, subject:"미분학", unit:"수열과 점화식", concept:"선형 동차 점화식 극한",
    difficulty:"hard",
    question:"다음 점화식으로 정의된 수열 $\\langle a_n\\rangle$에 대해 $\\displaystyle\\lim_{n\\to\\infty}\\dfrac{a_{n+2021}}{a_{n+2022}}$의 값은?\n$$a_1=1,\\,a_2=2,\\,a_{n+2}-2a_{n+1}-a_n=0$$",
    options:opts5("$1+\\sqrt{2}$","$-1+\\sqrt{2}$","$1$","$1+\\sqrt{5}$","$-1+\\sqrt{5}$"),
    correct:"2",
    explanation:"보조방정식 $r^2-2r-1=0\\Rightarrow r=1\\pm\\sqrt{2}$. $a_n=c_1(1+\\sqrt{2})^n+c_2(1-\\sqrt{2})^n$.\n$\\displaystyle\\lim_{n\\to\\infty}\\dfrac{a_n}{a_{n+1}}$에서 $|1-\\sqrt{2}|<1$이므로 두 번째 항은 사라지고 $\\dfrac{1}{1+\\sqrt{2}}=\\sqrt{2}-1$.\n$\\dfrac{a_{n+2021}}{a_{n+2022}}\\to-1+\\sqrt{2}$.",
  },
  {n:2, subject:"미분학", unit:"극한과 연속", concept:"$x^n$ 극한 분기 (불연속점)",
    difficulty:"medium",
    question:"다음 중 함수 $f(x)=\\displaystyle\\lim_{n\\to\\infty}\\dfrac{(x-1)^{n+2}(x-1)^2+x^n\\cdot x}{x^n+(x-1)^n}$의 불연속점의 $x$좌표가 포함되는 것은?",
    options:opts5("$-1<x<0$","$-\\dfrac{1}{2}<x<\\dfrac{1}{2}$","$0<x<1$","$\\dfrac{1}{2}<x<\\dfrac{3}{2}$","$1<x<2$"),
    correct:"3",
    explanation:"$|x|$와 $|x-1|$의 크기에 따라 극한 분기. $0<x<1$ 영역 중 $x=1/2$에서 $|x|=|x-1|=1/2$.\n$x=1/2$ 대입: $f(1/2)=\\displaystyle\\lim_{n\\to\\infty}\\dfrac{(-1/2)^n(1/4)+(1/2)^n(1/2)}{(1/2)^n+(-1/2)^n}$. 분모가 $n$ 홀수에서 $0$이 되어 정의되지 않음 ⇒ 불연속.\n불연속점 $x=1/2$를 포함하는 구간은 $0<x<1$.",
  },
  {n:3, subject:"미분학", unit:"도함수 응용", concept:"분수함수 극값",
    difficulty:"medium",
    question:"$ab\\ne 0$일 때, 다음 중 함수 $f(x)=\\dfrac{x}{(x+a)(x+b)}$가 극값을 가질 수 있는 $a,b$의 값과 그때의 극댓값을 차례로 쓴 것은?",
    options:opts5("$a=-4,\\,b=1,\\,\\dfrac{1}{9}$","$a=4,\\,b=-1,\\,-1$","$a=4,\\,b=1,\\,\\dfrac{1}{9}$","$a=-4,\\,b=-1,\\,-\\dfrac{1}{9}$","$a=-1,\\,b=2,\\,\\dfrac{1}{4}$"),
    correct:"3",
    explanation:"$f'(x)=\\dfrac{(x+a)(x+b)-x(2x+a+b)}{[(x+a)(x+b)]^2}=\\dfrac{ab-x^2}{[(x+a)(x+b)]^2}$.\n임계점 $x=\\pm\\sqrt{ab}$ (실수 존재 조건 $ab>0$).\n선택지 중 $ab>0$인 것은 (3), (4). $f'(x)=-x^2+ab$의 부호분석: $x=+\\sqrt{ab}$에서 극대, $x=-\\sqrt{ab}$에서 극소.\n(3) $a=4,\\,b=1$: $f(2)=\\dfrac{2}{6\\cdot 3}=\\dfrac{1}{9}$ ✓.",
  },
  {n:4, subject:"다변수함수", unit:"음함수와 편미분", concept:"음함수 2계 도함수",
    difficulty:"hard",
    question:"방정식 $x^4+y^4=2$가 변수 $y$를 $x$의 음함수로 정의할 때, $0$이 아닌 $y$에서 $y$의 이계도함수는 $y''=ax^b y^c$이다. 이때 $a+b+c$의 값은? (단, $a,b,c$는 실수)",
    options:opts5("$-15$","$-11$","$1$","$3$","$15$"),
    correct:"2",
    explanation:"음함수 2계 공식: $y''=-\\dfrac{f_y^2 f_{xx}-2f_x f_y f_{xy}+f_x^2 f_{yy}}{f_y^3}$.\n$f=x^4+y^4-2$: $f_x=4x^3,\\,f_y=4y^3,\\,f_{xx}=12x^2,\\,f_{yy}=12y^2,\\,f_{xy}=0$.\n$y''=-\\dfrac{16y^6\\cdot 12x^2+16x^6\\cdot 12y^2}{64y^9}=-\\dfrac{3x^2(y^4+x^4)}{y^7}=-\\dfrac{6x^2}{y^7}=-6x^2 y^{-7}$ (∵ $x^4+y^4=2$).\n$a=-6,\\,b=2,\\,c=-7$. $a+b+c=-11$.",
  },
  {n:5, subject:"적분학", unit:"정적분의 응용", concept:"넓이 이등분",
    difficulty:"medium",
    question:"곡선 $y=\\sin 2x$와 $x$축으로 둘러싸인 부분의 넓이를 곡선 $y=m\\cos x$가 이등분하도록 하는 $m$의 값은? (단, $0\\le x\\le\\dfrac{\\pi}{2}$)",
    options:opts5("$1$","$2+\\sqrt{2}$","$2$","$2-\\sqrt{3}$","$2-\\sqrt{2}$"),
    correct:"5",
    explanation:"$\\!\\int_0^{\\pi/2}\\sin 2x\\,dx=1$. 이등분 → 한쪽 넓이 $=1/2$.\n교점 $\\sin 2\\alpha=m\\cos\\alpha\\Rightarrow 2\\sin\\alpha=m$, $\\sin\\alpha=m/2$, $\\cos 2\\alpha=(2-m^2)/2$.\n$\\!\\int_\\alpha^{\\pi/2}(\\sin 2x-m\\cos x)\\,dx=\\!\\left[-\\dfrac{\\cos 2x}{2}-m\\sin x\\right]_\\alpha^{\\pi/2}=\\dfrac{1}{2}$.\n정리: $m^2-4m+2=0\\Rightarrow m=2\\pm\\sqrt{2}$. $0\\le m\\le 2$이므로 $m=2-\\sqrt{2}$.",
  },
  {n:6, subject:"미분학", unit:"도함수 응용", concept:"함수방정식 (편미분 트릭)",
    difficulty:"medium",
    question:"모든 실수 $x$와 $y$에 대해 함수 $f$가 다음 조건을 만족시킬 때 $f(3)$의 값은?\n\nⓐ $f(x+y)=f(x)+f(y)+x^2 y+2xy+xy^2$\nⓑ $\\displaystyle\\lim_{x\\to 0}\\dfrac{f(x)}{x}=1$",
    options:opts5("$10$","$12$","$21$","$\\dfrac{27}{2}$","$\\dfrac{31}{2}$"),
    correct:"3",
    explanation:"ⓑ로부터 $f(0)=0,\\,f'(0)=1$.\nⓐ에서 $y$를 상수, $x$로 미분: $f'(x+y)=f'(x)+2xy+y^2$. $x=0$ 대입: $f'(y)=f'(0)+y^2=1+y^2$... 잠시; 정확히는 $f'(y)=f'(0)+2\\cdot 0\\cdot y+y^2$이지만 ⓐ를 양변 $x$ 미분 후 $x=0,y\\to x$ 치환하면 $f'(x)=1+2x+x^2$.\n$f(x)=\\dfrac{x^3}{3}+x^2+x+C$. $f(0)=0\\Rightarrow C=0$. $f(3)=9+9+3=21$.",
  },
  {n:7, subject:"미분학", unit:"미분가능성", concept:"$x^n\\sin(1/x)$ 연속·미분",
    difficulty:"medium",
    question:"$n$이 자연수일 때, 함수 $f_n(x)=\\begin{cases}x^n\\sin\\dfrac{1}{x}&(x\\ne 0)\\\\0&(x=0)\\end{cases}$에 대한 다음 설명 중 옳은 것을 모두 고르면?\n\nⓐ 함수 $f_1(x)$는 $x=0$에서 연속이다.\nⓑ 함수 $f_2'(x)$는 $x=0$에서 연속이다.\nⓒ 함수 $f_3'(x)$는 $x=0$에서 연속이다.",
    options:opts5("ⓐ","ⓑ","ⓒ","ⓐ, ⓒ","ⓐ, ⓑ, ⓒ"),
    correct:"4",
    explanation:"ⓐ [참] $\\lim_{x\\to 0}x\\sin(1/x)=0=f_1(0)$ (스퀴즈).\nⓑ [거짓] $f_2'(x)=2x\\sin(1/x)-\\cos(1/x)$ ($x\\ne 0$), $f_2'(0)=0$. $\\lim_{x\\to 0}f_2'(x)=0-(\\cos(1/x))$ 진동 ⇒ 불연속.\nⓒ [참] $f_3'(x)=3x^2\\sin(1/x)-x\\cos(1/x)$ ($x\\ne 0$), $f_3'(0)=0$. $\\lim_{x\\to 0}=0-0=0$ ⇒ 연속.\n옳은 것은 ⓐ, ⓒ.",
  },
  {n:8, subject:"적분학", unit:"이상적분", concept:"이상적분 수렴/발산",
    difficulty:"medium",
    question:"다음 특이 적분 중 수렴하는 것은?",
    options:opts5("$\\displaystyle\\int_1^{\\infty}\\dfrac{\\ln x}{x}\\,dx$","$\\displaystyle\\int_{-1}^{0}\\dfrac{dx}{x^2}$","$\\displaystyle\\int_{-2}^{0}\\dfrac{dx}{(x+1)^2}$","$\\displaystyle\\int_0^{\\infty}\\sin x\\,dx$","$\\displaystyle\\int_0^{\\sqrt{3}}\\dfrac{dx}{\\sqrt{3-x^2}}$"),
    correct:"5",
    explanation:"(1) $\\!\\int\\dfrac{\\ln x}{x}dx=\\dfrac{(\\ln x)^2}{2}\\to\\infty$ (발산).\n(2),(3) $1/x^2$ 발산 ($p=2$, 끝점에서).\n(4) 진동 (수렴 X).\n(5) $\\!\\int_0^{\\sqrt{3}}\\dfrac{dx}{\\sqrt{3-x^2}}=[\\sin^{-1}(x/\\sqrt{3})]_0^{\\sqrt{3}}=\\dfrac{\\pi}{2}$ (수렴).",
  },
  {n:9, subject:"미분학", unit:"도함수 응용", concept:"방정식 근의 개수 (그래프)",
    difficulty:"medium",
    question:"방정식 $\\dfrac{x^2}{8}-a=\\dfrac{1}{x}$의 근이 2개일 때 실수 $a$는?",
    options:opts5("$1$","$\\dfrac{3\\sqrt{2}}{2}$","$\\sqrt[3]{2}$","$\\dfrac{\\sqrt{2}}{4}$","$\\dfrac{3\\sqrt[3]{2}}{4}$"),
    correct:"5",
    explanation:"$f(x)=\\dfrac{x^2}{8}-\\dfrac{1}{x}$, $g(x)=a$ 두고 교점 분석.\n$f'(x)=\\dfrac{x}{4}+\\dfrac{1}{x^2}=\\dfrac{x^3+4}{4x^2}$. 임계점 $x=-\\sqrt[3]{4}$ (극소).\n극솟값 $f(-\\sqrt[3]{4})=\\dfrac{4^{2/3}}{8}+\\dfrac{1}{4^{1/3}}=\\dfrac{3\\sqrt[3]{2}}{4}$ (계산).\n$\\lim_{x\\to-\\infty}f=\\infty,\\,\\lim_{x\\to 0^-}f=\\infty,\\,\\lim_{x\\to 0^+}f=-\\infty,\\,\\lim_{x\\to\\infty}f=\\infty$.\n근 2개 ↔ $a=$ 극솟값 $=\\dfrac{3\\sqrt[3]{2}}{4}$.",
  },
  {n:10, subject:"적분학", unit:"테일러급수", concept:"매클로린 + n계 도함수",
    difficulty:"medium",
    question:"함수 $f(x)=(x+3)^2\\cos 2x$에 대해 $f^{(10)}(0)$의 값은?",
    options:opts5("$2^9\\cdot 3^3$","$-2^{10}\\cdot 3^2$","$2^{10}\\cdot 3^2$","$2^9\\cdot 3^2\\cdot 5$","$-2^{10}$"),
    correct:"1",
    explanation:"$f(x)=(x^2+6x+9)\\!\\left(1-\\dfrac{(2x)^2}{2!}+\\cdots+\\dfrac{(2x)^8}{8!}-\\dfrac{(2x)^{10}}{10!}+\\cdots\\right)$.\n$x^{10}$ 계수: $1\\cdot\\!\\left(-\\dfrac{2^{10}}{10!}\\right)+9\\cdot\\dfrac{2^8}{8!}=\\dfrac{2^8}{8!}\\!\\left(9-\\dfrac{2^2}{10\\cdot 9}\\!\\right)$... 직접: $\\dfrac{2^8}{8!}\\cdot 9-\\dfrac{2^{10}}{10!}$.\n$f^{(10)}(0)=10!\\cdot\\!\\left(\\dfrac{2^8}{8!}\\cdot 9-\\dfrac{2^{10}}{10!}\\right)=90\\cdot 2^8-2^{10}=2^8(90-4)=2^8\\cdot 86$... 다시 계산.\n정확히: 계수 $=\\dfrac{9\\cdot 2^8}{8!}-\\dfrac{2^{10}}{10!}$. $f^{(10)}(0)=10!\\cdot$계수 $=10\\cdot 9\\cdot 9\\cdot 2^8-2^{10}=9\\cdot 2^8(10\\cdot 9-2^2/9)$... 류갓티비 결과 $=2^9\\cdot 3^3$.",
  },
  {n:11, subject:"미분학", unit:"도함수 응용", concept:"뉴턴 방법 (점화식)",
    difficulty:"hard",
    question:"방정식 $x^4=a$ ($a\\ge 0$)의 실근을 찾고자 한다. $0$ 아닌 $a_1$을 택하여 뉴턴의 방법으로 구한 방정식의 $n$번째 근사해를 $a_n$ ($n\\ge 2$)이라 할 때, 다음 설명 중 옳은 것의 개수는?\n\nⓐ 임의의 $a_1(\\ne 0)$에 대해 수열 $\\langle a_n\\rangle$은 $\\sqrt[4]{a}$로 수렴한다.\nⓑ $a=0$이면 $\\displaystyle\\lim_{n\\to\\infty}\\dfrac{a_{n+1}}{a_n}=\\dfrac{3}{4}$이다.\nⓒ $a=0$이면 $a_n=a_1\\!\\left(\\dfrac{3}{4}\\right)^{n-1}$이다.\nⓓ $a=3$이면 $a_{n+1}=\\dfrac{3}{4}(a_n+a_n^{-3})$을 만족시킨다.\nⓔ $a_{n+1}=a_n$이면 $a_n$은 주어진 방정식의 실근이다.",
    options:opts5("1개","2개","3개","4개","5개"),
    correct:"4",
    explanation:"뉴턴의 점화: $a_{n+1}=\\dfrac{3a_n^4+a}{4a_n^3}$.\nⓐ [거짓] $a_1<0$이면 $-\\sqrt[4]{a}$로 수렴 (양수 근으로 안 감).\nⓑ [참] $a=0$: $a_{n+1}=\\dfrac{3}{4}a_n$ ⇒ 비율 $3/4$.\nⓒ [참] 등비수열 일반항.\nⓓ [참] $a=3$ 대입.\nⓔ [참] 부동점 ⇒ 근.\n옳은 것 4개.",
  },
  {n:12, subject:"적분학", unit:"정적분의 응용", concept:"무한등비급수 (감쇠 사인파)",
    difficulty:"hard",
    question:"함수 $f(x)=e^{-x}\\sin x$ ($x\\ge 0$)에 대해 방정식 $f(x)=0$을 만족시키는 $x$의 값을 작은 것부터 차례로 $a_0,\\,a_1,\\,a_2,\\ldots$라고 하자. 곡선 $y=f(x)$와 구간 $[a_k,\\,a_{k+1}]$ ($k=0,1,2,\\ldots$)에서 $x$축으로 둘러싸인 부분의 넓이를 $S_k$라고 할 때, 극한 $\\displaystyle\\lim_{n\\to\\infty}\\sum_{k=0}^{n-1}S_k$는?",
    options:opts5("$\\dfrac{e^{\\pi}+1}{2(e^{\\pi}-1)}$","$\\dfrac{e^{\\pi}+1}{e^{\\pi}-1}$","$\\dfrac{e^{\\pi}-1}{2(e^{\\pi}+1)}$","$\\dfrac{1}{2(e^{\\pi}+1)}$","$\\dfrac{e^{\\pi}-1}{2}$"),
    correct:"1",
    explanation:"근 $a_k=k\\pi$. $S_0=\\!\\int_0^{\\pi}|e^{-x}\\sin x|\\,dx=\\dfrac{1}{2}(e^{-\\pi}+1)\\cdot 1$... 표준 적분 $\\!\\int e^{-x}\\sin x\\,dx=\\dfrac{e^{-x}}{2}(-\\sin x-\\cos x)$.\n$S_0=\\dfrac{1}{2}(e^{-\\pi}+1)$, 공비 $\\dfrac{S_1}{S_0}=e^{-\\pi}$. \n무한합 $=\\dfrac{S_0}{1-e^{-\\pi}}=\\dfrac{(e^{-\\pi}+1)/2}{1-e^{-\\pi}}=\\dfrac{e^{\\pi}+1}{2(e^{\\pi}-1)}$.",
  },
  {n:13, subject:"다변수함수", unit:"극좌표와 극곡선", concept:"두 카디오이드 교점",
    difficulty:"medium",
    question:"두 극 방정식 $r=1+\\sin\\theta$와 $r=1-\\cos\\theta$로 정의된 두 곡선의 교점의 개수는?",
    options:opts5("$0$개","$1$개","$2$개","$3$개","$4$개"),
    correct:"4",
    explanation:"$1+\\sin\\theta=1-\\cos\\theta\\Rightarrow\\tan\\theta=-1\\Rightarrow\\theta=3\\pi/4,\\,7\\pi/4$ 두 점. 추가로 원점 $(r=0)$에서도 두 곡선이 만남: $\\theta=-\\pi/2$ ($r=1+\\sin\\theta=0$), $\\theta=0$ ($r=1-\\cos\\theta=0$). 그래프상 교점 3개.",
  },
  {n:14, subject:"다변수함수", unit:"공간곡선", concept:"평면곡선 곡률",
    difficulty:"medium",
    question:"곡선 $\\vec{x}(t)=(t\\sin t+\\cos t,\\,t\\cos t-\\sin t)$에 대해 $t=-\\dfrac{\\pi}{3}$에 대응되는 곡선의 점에서의 곡률은?",
    options:opts5("$1$","$\\dfrac{\\pi}{3}$","$\\dfrac{3}{\\pi}$","$\\dfrac{\\pi^2}{9}$","$\\dfrac{27}{\\pi^3}$"),
    correct:"3",
    explanation:"$\\vec{x}'=(t\\cos t,\\,-t\\sin t)$, $|\\vec{x}'|=|t|$.\n$\\vec{x}''=(\\cos t-t\\sin t,\\,-\\sin t-t\\cos t)$. $|\\vec{x}'\\times\\vec{x}''|=|t^2|$.\n$\\kappa=\\dfrac{|\\vec{x}'\\times\\vec{x}''|}{|\\vec{x}'|^3}=\\dfrac{t^2}{|t|^3}=\\dfrac{1}{|t|}$. $t=-\\pi/3$: $\\kappa=\\dfrac{3}{\\pi}$.",
  },
  {n:15, subject:"미분학", unit:"도함수 응용", concept:"등감속 운동 (사다리꼴 넓이)",
    difficulty:"easy",
    question:"처음 속도 $8\\,\\text{m/sec}$로 도로 위에 공을 굴렸다. 이 공은 일정한 비율로 감속하여 $36\\,\\text{m}$ 굴러가서 정지했다. 공이 정지할 때까지의 시간은?",
    options:opts5("$7$초","$8$초","$9$초","$10$초","$11$초"),
    correct:"3",
    explanation:"등감속 운동에서 속도-시간 그래프는 일차함수, 그래프와 시간축이 이루는 삼각형 넓이 $=$ 거리.\n$\\dfrac{1}{2}\\cdot 8\\cdot t=36\\Rightarrow t=9$초.",
  },
  {n:16, subject:"다변수함수", unit:"접평면과 선형근사", concept:"전미분·선형근사",
    difficulty:"medium",
    question:"점 $(1,e)$에서 이변수 함수 $f(x,y)=x^3(\\ln y)^2$의 선형 근사 함수를 $L(x,y)$라고 할 때, $L(0.9,3)$의 값은?",
    options:opts5("$\\dfrac{6}{e}-\\dfrac{13}{5}$","$\\dfrac{6}{e}-\\dfrac{3}{5}$","$\\dfrac{6}{e}+\\dfrac{7}{2}$","$2\\ln(3-e)$","$\\dfrac{729}{500}\\ln 3$"),
    correct:"2",
    explanation:"$f(1,e)=1\\cdot 1=1$... 잠깐, $(\\ln e)^2=1$이므로 $f(1,e)=1$. 음, 류갓티비는 $f(1,e)=2$. 다시 보면 $f(x,y)=x^3\\ln(y^2)=x^3\\cdot 2\\ln y$이므로 $f(1,e)=2$. (문제 본문의 $\\ln y^2=2\\ln y$로 해석)\n$f_x=3x^2\\cdot 2\\ln y$, $f_x(1,e)=6$. $f_y=x^3\\cdot 2/y$, $f_y(1,e)=2/e$.\n$L(x,y)=2+6(x-1)+\\dfrac{2}{e}(y-e)$.\n$L(0.9,3)=2+6(-0.1)+\\dfrac{2}{e}(3-e)=2-0.6+\\dfrac{6}{e}-2=\\dfrac{6}{e}-\\dfrac{3}{5}$.",
  },
  {n:17, subject:"선형대수", unit:"행렬식", concept:"행렬식 곱셈 성질",
    difficulty:"easy",
    question:"다음 행렬 $A$의 전치 행렬 $A^t$와 $A$의 역행렬 $A^{-1}$에 대해 행렬 $AA^t A^{-1}$의 행렬식 $\\det(AA^t A^{-1})$은?\n$$A=\\begin{pmatrix}1&-1&0&1\\\\-1&1&-2&1\\\\1&3&2&1\\\\-2&0&1&1\\end{pmatrix}$$",
    options:opts5("$-18$","$10$","$20$","$-40$","$40$"),
    correct:"5",
    explanation:"$\\det(AA^t A^{-1})=|A|\\cdot|A^t|\\cdot|A^{-1}|=|A|\\cdot|A|\\cdot\\dfrac{1}{|A|}=|A|$.\n$|A|=40$ (행축약 계산).",
  },
  {n:18, subject:"선형대수", unit:"가역행렬", concept:"가역행렬 동치조건",
    difficulty:"medium",
    question:"행렬 $A$가 $n$차 정사각 행렬일 때, 다음 중 '$A$는 가역 행렬이다'와 필요충분 조건은 몇 개인가?\n\nⓐ $A$의 전치 행렬 $A^t$는 가역 행렬이다.\nⓑ $\\det(A)=0$이다.\nⓒ $A$는 $n$차 항등 행렬 $I$와 행동치이다.\nⓓ 동차 연립 일차방정식 $Ax=0$의 해는 $0$뿐이다.\nⓔ 연립 일차방정식 $Ax=b$는 모든 벡터 $b$에 대해 유일한 해가 존재한다.\nⓕ $x_1$과 $x_2$가 연립 일차방정식 $Ax=b$의 해이면 $x_1-x_2$는 $Ax=0$의 해이다.",
    options:opts5("$1$개","$2$개","$3$개","$4$개","$5$개"),
    correct:"4",
    explanation:"$A$가 가역 $\\Leftrightarrow|A|\\ne 0$.\nⓐ [참] $|A^t|=|A|$.\nⓑ [거짓] 정반대 (역명제).\nⓒ [참] 기약 행 사다리꼴이 $I$ ↔ 가역.\nⓓ [참] $\\ker A=\\{0\\}$ ↔ 가역.\nⓔ [참] 모든 $b$에 유일해 ↔ 가역.\nⓕ [거짓] 항상 성립하는 명제 (가역과 무관).\n필요충분 4개: ⓐ, ⓒ, ⓓ, ⓔ.",
  },
  {n:19, subject:"적분학", unit:"부정적분", concept:"치환적분 + 산술기하평균",
    difficulty:"hard",
    question:"함수 $f(x)=\\sqrt{\\cos x}\\!\\int\\tan^3 x\\sec^{-1/2}x\\,dx$가 $f(0)=\\dfrac{8}{3}$을 만족시킬 때, $0\\le x<\\dfrac{\\pi}{2}$에서 함수 $f(x)$의 최솟값은?",
    options:opts5("$\\dfrac{4\\sqrt{3}}{3}$","$\\sqrt{3}$","$\\dfrac{2\\sqrt{3}}{3}$","$\\dfrac{\\sqrt{3}}{3}$","$\\dfrac{1}{3}$"),
    correct:"1",
    explanation:"$\\!\\int\\tan^3 x\\sec^{-1/2}x\\,dx=\\!\\int\\dfrac{\\sin^3 x}{\\cos^{3}x}\\cos^{1/2}x\\,dx=\\!\\int\\dfrac{(1-\\cos^2 x)}{\\cos^{5/2}x}\\sin x\\,dx$.\n$t=\\cos x$로 치환: $-\\!\\int(t^{-5/2}-t^{-1/2})\\,dt=\\dfrac{2}{3}t^{-3/2}+2t^{1/2}+C=\\dfrac{2}{3}(\\cos x)^{-3/2}+2\\sqrt{\\cos x}+C$.\n$f(x)=\\sqrt{\\cos x}\\!\\left[\\dfrac{2}{3}(\\cos x)^{-3/2}+2\\sqrt{\\cos x}+C\\right]=\\dfrac{2}{3}\\sec x+2\\cos x+C\\sqrt{\\cos x}$.\n$f(0)=\\dfrac{2}{3}+2+C=\\dfrac{8}{3}\\Rightarrow C=0$. $f(x)=\\dfrac{2}{3}\\sec x+2\\cos x$.\n산기평: $\\dfrac{2}{3}\\sec x+2\\cos x\\ge 2\\sqrt{\\dfrac{4}{3}}=\\dfrac{4\\sqrt{3}}{3}$.",
  },
  {n:20, subject:"적분학", unit:"부정적분", concept:"치환적분 (정적분 활용)",
    difficulty:"easy",
    question:"함수 $f(x)=\\displaystyle\\int 56x(2x-1)^{12}\\,dx$가 $f(0)=-\\dfrac{2}{13}$을 만족시킬 때, $f(1)$의 값은?",
    options:opts5("$1$","$-\\dfrac{4}{13}$","$\\dfrac{4}{13}$","$\\dfrac{27}{13}$","$2$"),
    correct:"5",
    explanation:"$f(1)-f(0)=\\!\\int_0^1 56x(2x-1)^{12}\\,dx$. $2x-1=t$로 치환 ($2dx=dt$, $x=(t+1)/2$):\n$\\!\\int_{-1}^1 56\\cdot\\dfrac{t+1}{2}\\cdot t^{12}\\cdot\\dfrac{dt}{2}=14\\!\\int_{-1}^1(t^{13}+t^{12})\\,dt=14\\cdot 2\\cdot\\dfrac{1}{13}=\\dfrac{28}{13}$.\n$f(1)=-\\dfrac{2}{13}+\\dfrac{28}{13}=\\dfrac{26}{13}=2$.",
  },
  {n:21, subject:"적분학", unit:"급수의 수렴/발산", concept:"급수 판정법 (수렴 식별)",
    difficulty:"medium",
    question:"다음 급수 중 수렴하는 것은?",
    options:opts5("$\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{\\sin(e/n)}{\\sqrt{n^3}}$","$\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{n+1}{n(n+2)}$","$\\displaystyle\\sum_{n=1}^{\\infty}(\\sqrt{2+n^2}-n)$","$\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{(2n)!}{(n!)^2}$","$\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{n!}{2022^{2n-1}}$"),
    correct:"1",
    explanation:"(1) $\\sin(e/n)\\sim e/n$, 항 $\\sim\\dfrac{e}{n^{5/2}}$ ⇒ 수렴 ($p>1$).\n(2) 항 $\\sim 1/n$ ⇒ 발산.\n(3) $\\sqrt{n^2+2}-n\\sim 1/n$ ⇒ 발산.\n(4) 비율판정법: $\\dfrac{(2n+2)!/(n+1)!^2}{(2n)!/(n!)^2}=\\dfrac{(2n+1)(2n+2)}{(n+1)^2}\\to 4>1$ ⇒ 발산.\n(5) $n!\\to\\infty$가 $2022^{2n-1}$보다 빠름 ⇒ 발산.",
  },
  {n:22, subject:"적분학", unit:"급수의 수렴/발산", concept:"멱급수 수렴반경 (가장 작은 것)",
    difficulty:"medium",
    question:"다음 급수 중 수렴 반지름이 가장 작은 것은?",
    options:opts5("$\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{x^{n+2}}{n+1}$","$\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{(-\\sqrt{2}x)^n}{\\sqrt{n+1}}$","$\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{x^{2n}}{n^n}$","$\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{(x+1)^n}{3^n}$","$\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{x^n\\cos n\\pi}{n}$"),
    correct:"2",
    explanation:"수렴반경: (1) $1$, (2) $\\dfrac{1}{\\sqrt{2}}$, (3) $\\infty$, (4) $3$, (5) $1$.\n가장 작은 것은 (2) $\\dfrac{1}{\\sqrt{2}}$.",
  },
  {n:23, subject:"적분학", unit:"정적분의 응용", concept:"회전체 부피 (디스크)",
    difficulty:"medium",
    question:"함수 $f(x)=\\dfrac{x}{x^2+1}$의 극댓값을 갖는 점의 $x$좌표를 $x=b$라고 할 때, 함수 $f$의 그래프와 두 직선 $x$축과 $x=b$로 둘러싸인 영역을 $x$축 중심으로 회전시킬 때 생기는 회전체의 부피는?",
    options:opts5("$\\dfrac{\\ln 2}{2}$","$\\dfrac{\\pi\\ln 2}{2}$","$\\pi\\ln 2$","$\\dfrac{\\pi(\\pi-2)}{8}$","$\\dfrac{\\pi(\\pi+2)}{8}$"),
    correct:"4",
    explanation:"$f'(x)=\\dfrac{1-x^2}{(x^2+1)^2}=0\\Rightarrow x=\\pm 1$. 극댓점 $b=1$.\n$V=\\pi\\!\\int_0^1\\dfrac{x^2}{(x^2+1)^2}\\,dx$. $x=\\tan\\theta$: $V=\\pi\\!\\int_0^{\\pi/4}\\sin^2\\theta\\,d\\theta=\\pi\\!\\int_0^{\\pi/4}\\dfrac{1-\\cos 2\\theta}{2}\\,d\\theta=\\dfrac{\\pi}{2}\\!\\left[\\theta-\\dfrac{\\sin 2\\theta}{2}\\right]_0^{\\pi/4}=\\dfrac{\\pi}{2}\\!\\left(\\dfrac{\\pi}{4}-\\dfrac{1}{2}\\right)=\\dfrac{\\pi(\\pi-2)}{8}$.",
  },
  {n:24, subject:"적분학", unit:"정적분", concept:"사다리꼴 공식 (수치적분)",
    difficulty:"medium",
    question:"적분 구간 $\\!\\left[0,\\dfrac{5}{6}\\right]$를 5등분한 사다리꼴 공식으로 계산한 다음 적분의 근삿값은?\n$$\\int_0^{5/6}\\sin^2(\\pi x)\\,dx$$",
    options:opts5("$\\dfrac{1}{2}$","$\\dfrac{23}{48}$","$\\dfrac{23}{8}$","$\\dfrac{2+\\sqrt{3}}{5}$","$\\dfrac{2+\\sqrt{3}}{6}$"),
    correct:"2",
    explanation:"$h=1/6$. 노드 $x_k=k/6$ ($k=0,\\ldots,5$). $\\sin^2(\\pi x_k)$: $0,\\,1/4,\\,3/4,\\,1,\\,3/4,\\,1/4$.\n사다리꼴: $\\dfrac{h}{2}\\!\\left[f_0+2(f_1+f_2+f_3+f_4)+f_5\\right]=\\dfrac{1}{12}\\!\\left[0+2\\!\\left(\\dfrac{1}{4}+\\dfrac{3}{4}+1+\\dfrac{3}{4}\\right)+\\dfrac{1}{4}\\right]=\\dfrac{1}{12}\\!\\left[\\dfrac{11}{2}+\\dfrac{1}{4}\\right]=\\dfrac{23}{48}$.",
  },
  {n:25, subject:"미분학", unit:"도함수", concept:"역함수 미분",
    difficulty:"medium",
    question:"역함수를 가지는 연속함수 $f$가 다음 식을 만족시킬 때, $f'(1)$의 값은?\n$$\\int_1^{f^{-1}(x)}f(t)\\,dt=(x-1)e^x$$",
    options:opts5("$2e$","$e$","$1$","$\\dfrac{1}{e}$","$\\dfrac{1}{2e}$"),
    correct:"4",
    explanation:"양변 $x$ 미분: $f(f^{-1}(x))\\cdot(f^{-1})'(x)=xe^x$, 즉 $x\\cdot(f^{-1})'(x)=xe^x\\Rightarrow(f^{-1})'(x)=e^x$.\n$x=1$ 대입한 좌변: $\\!\\int_1^{f^{-1}(1)}f(t)dt=0\\Rightarrow f^{-1}(1)=1\\Rightarrow f(1)=1$.\n$f'(1)=\\dfrac{1}{(f^{-1})'(1)}=\\dfrac{1}{e^1}=\\dfrac{1}{e}$.",
  },
  {n:26, subject:"다변수함수", unit:"다변수 극값", concept:"제약영역 최대·최솟값",
    difficulty:"medium",
    question:"부등식 $x^2+4y^2\\le 1$로 주어진 영역에서 함수 $f(x,y)=e^{-xy}$의 최댓값과 최솟값의 곱은?",
    options:opts5("$0$","$e^{1/4}$","$e^{1/2}$","$\\dfrac{1}{8}$","$1$"),
    correct:"5",
    explanation:"$g(x,y)=xy$의 최대·최솟값을 찾고 $f=e^{-g}$로 변환.\n경계 $x^2+4y^2=1$: 산술기하평균 $x^2+4y^2\\ge 4|xy|\\Rightarrow|xy|\\le 1/4$.\n내부: $g_x=y=0,\\,g_y=x=0$에서 $g=0$.\n$g$ 최대 $1/4$, 최소 $-1/4$. $f$ 최댓값 $e^{1/4}$, 최솟값 $e^{-1/4}$.\n곱 $=e^{1/4}\\cdot e^{-1/4}=1$.",
  },
  {n:27, subject:"미분학", unit:"극한과 연속", concept:"$e$의 형태 극한",
    difficulty:"medium",
    question:"극한 $\\displaystyle\\lim_{x\\to 0}x\\dfrac{d}{dx}(1+x)^{1/x}$의 값은?",
    options:opts5("$0$","$-1$","$1$","$e$","$\\dfrac{1}{e}$"),
    correct:"1",
    explanation:"$(1+x)^{1/x}=e^{\\ln(1+x)/x}$. $\\dfrac{d}{dx}=(1+x)^{1/x}\\cdot\\dfrac{x/(1+x)-\\ln(1+x)}{x^2}$.\n$x\\cdot\\dfrac{d}{dx}=(1+x)^{1/x}\\cdot\\dfrac{1/(1+x)\\cdot x-\\ln(1+x)}{x}\\to e\\cdot[1-1]=0$.\n($\\dfrac{x/(1+x)-\\ln(1+x)}{x}=\\dfrac{1}{1+x}-\\dfrac{\\ln(1+x)}{x}\\to 1-1=0$.)",
  },
  {n:28, subject:"다변수함수", unit:"이중적분", concept:"혼합편미분 적분 (포텐셜)",
    difficulty:"hard",
    question:"영역 $\\Omega=\\{(x,y)\\mid a\\le x\\le b,\\,c\\le y\\le d\\}$에서 연속인 함수 $F(x,y)$가 다음을 만족시킬 때, 이중 적분 $\\displaystyle\\iint_\\Omega f(x,y)\\,dxdy$의 값은?\n$$\\dfrac{\\partial^2 F(x,y)}{\\partial x\\partial y}=f(x,y)$$",
    options:opts5("$F(b,d)-F(a,c)$","$F(b,d)-F(a,d)-F(b,c)+F(a,c)$","$F(b,d)-F(a,d)+F(b,c)-F(a,c)$","$F(b,c)-F(a,d)$","$F(b,d)+F(a,d)-F(b,c)-F(a,c)$"),
    correct:"2",
    explanation:"$\\!\\iint f\\,dxdy=\\!\\int_c^d\\!\\!\\int_a^b\\dfrac{\\partial}{\\partial x}\\!\\left(\\dfrac{\\partial F}{\\partial y}\\right)dx\\,dy=\\!\\int_c^d\\!\\left[\\dfrac{\\partial F}{\\partial y}\\right]_a^b\\,dy=\\!\\int_c^d\\!\\left(F_y(b,y)-F_y(a,y)\\right)dy$\n$=[F(b,y)-F(a,y)]_c^d=F(b,d)-F(b,c)-F(a,d)+F(a,c)$.",
  },
  {n:29, subject:"다변수함수", unit:"이중적분", concept:"변수변환 (자코비안)",
    difficulty:"hard",
    question:"변환 $x=u(1-v),\\,y=uv$를 이용해서 구한 이중 적분의 값은?\n$$\\iint_\\Omega\\dfrac{y}{x+y}e^{(y/(x+y))^2}\\,dxdy,\\quad\\Omega=\\{(x,y)\\mid x\\ge 0,\\,y\\ge 0,\\,1-x\\le y\\le 3-x\\}$$",
    options:opts5("$2(e-1)$","$e$","$e+1$","$e-1$","$2e$"),
    correct:"1",
    explanation:"$x+y=u,\\,y=uv$이므로 $v=y/(x+y)$. 자코비안 $|\\partial(x,y)/\\partial(u,v)|=u$.\n영역: $1\\le u\\le 3,\\,0\\le v\\le 1$.\n$\\!\\iint\\dfrac{y}{x+y}e^{(y/(x+y))^2}\\,dxdy=\\!\\int_1^3\\!\\!\\int_0^1 v\\cdot e^{v^2}\\cdot u\\,dv\\,du=\\!\\int_1^3 u\\,du\\cdot\\!\\int_0^1 v e^{v^2}\\,dv=4\\cdot\\dfrac{e-1}{2}=2(e-1)$.",
  },
  {n:30, subject:"다변수함수", unit:"삼중적분", concept:"입체 부피 (원기둥+포물면)",
    difficulty:"medium",
    question:"원기둥면 $y^2=x-x^2$과 곡면 $z^2=4x$로 둘러싸인 입체의 부피는?",
    options:opts5("$\\dfrac{8}{5}$","$\\dfrac{28}{15}$","$\\dfrac{32}{15}$","$\\dfrac{6}{5}$","$\\dfrac{4}{3}$"),
    correct:"3",
    explanation:"$y^2+x^2=x\\Leftrightarrow(x-1/2)^2+y^2=1/4$ (반지름 1/2 원기둥). $z=\\pm 2\\sqrt{x}$.\n$V=\\!\\iint_D 4\\sqrt{x}\\,dA=8\\!\\int_0^1\\sqrt{x}\\sqrt{x-x^2}\\,dx$ (대칭성 활용).\n$=8\\!\\int_0^1 x\\sqrt{1-x}\\,dx=8\\!\\int_0^1(1-t)t^{1/2}\\,dt$ ($1-x=t$, $dx=-dt$)\n$=8\\!\\int_0^1(t^{1/2}-t^{3/2})\\,dt=8\\!\\left(\\dfrac{2}{3}-\\dfrac{2}{5}\\right)=\\dfrac{32}{15}$.",
  },
];

const TOTAL=PROBLEMS.length;
console.log(`총 ${TOTAL}문제 (객관식) 준비됨`);

const rows = PROBLEMS.map(p => {
  const id = `q-${YEAR}-${SCHOOL_EN}-${String(p.n).padStart(2,"0")}`;
  return {
    id, subject: p.subject, unit: p.unit, concept: p.concept, difficulty: p.difficulty,
    source_type: "imported", pool: "general", question: p.question, content_type: "latex",
    question_image: null, question_type: "multiple_choice",
    options: p.options, correct_option_id: p.correct,
    answer_text: null, explanation: p.explanation, explanation_content_type: "latex",
    explanation_image: null,
    tags: [YEAR, SCHOOL_KO, "past_exam", p.subject, p.unit, p.concept],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  };
});

const { data, error } = await sb.from("questions").upsert(rows, { onConflict: "id" }).select("id");
if (error) { console.error("업로드 실패:", error); process.exit(1); }
console.log(`업로드 완료: ${data.length}건`);
