// 2022년 단국대 오후 편입수학 객관식 20문항 (4지선다, 문항 번호 31~50)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR_ID="2022pm", YEAR_KO="2022", SESSION_KO="오후", SCHOOL_KO="단국대", SCHOOL_EN="dankook";
const opts4 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:31, subject:"미분학", unit:"극한과 연속", concept:"삼각함수 극한 (테일러)",
    difficulty:"medium",
    question:"$\\displaystyle\\lim_{\\theta\\to 0}\\!\\left(\\dfrac{\\cot 2\\theta}{\\csc\\theta}-\\dfrac{\\sin(\\cos\\theta)}{\\sec\\theta}\\right)$의 값은?",
    options:opts4("$-\\sin 1$","$\\sin 1$","$\\dfrac{1}{2}-\\sin 1$","$\\dfrac{1}{2}+\\sin 1$"),
    correct:"3",
    explanation:"$\\dfrac{\\cot 2\\theta}{\\csc\\theta}=\\dfrac{\\sin\\theta}{\\tan 2\\theta}=\\dfrac{\\sin\\theta\\cos 2\\theta}{2\\sin\\theta\\cos\\theta}\\to\\dfrac{1}{2}$.\n$\\dfrac{\\sin(\\cos\\theta)}{\\sec\\theta}=\\sin(\\cos\\theta)\\cos\\theta\\to\\sin 1$.\n극한 $=\\dfrac{1}{2}-\\sin 1$.",
  },
  {n:32, subject:"미분학", unit:"도함수 응용", concept:"폐구간 최댓값·최솟값",
    difficulty:"medium",
    question:"구간 $[-4,1]$에서 함수 $f(x)=-xe^{-x^2/8}$의 최솟값과 최댓값의 합은?",
    options:opts4("$e^{-1/8}-2e^{-1/2}$","$2e^{-1/2}-e^{-1/8}$","$4e^{-2}-e^{-1/8}$","$e^{-1/8}-4e^{-2}$"),
    correct:"2",
    explanation:"$f'(x)=-e^{-x^2/8}\\!\\left(1-\\dfrac{x^2}{4}\\right)\\cdot$... 정확히 $f'(x)=-e^{-x^2/8}\\!\\left(\\dfrac{4-x^2}{4}\\right)$.\n임계점 $x=\\pm 2$ 중 정의역 내 $x=-2$. $f(-2)=2e^{-1/2}$.\n양 끝: $f(-4)=4e^{-2},\\,f(1)=-e^{-1/8}$.\n최대 $2e^{-1/2}$, 최소 $-e^{-1/8}$. 합 $=2e^{-1/2}-e^{-1/8}$.",
  },
  {n:33, subject:"적분학", unit:"정적분의 응용", concept:"회전체 부피",
    difficulty:"easy",
    question:"곡선 $y^2=x$와 직선 $x=2y$로 둘러싸인 영역을 $y$축을 중심으로 회전시켜 얻은 입체의 부피는?",
    options:opts4("$\\dfrac{11}{3}\\pi$","$\\dfrac{58}{15}\\pi$","$\\dfrac{61}{15}\\pi$","$\\dfrac{64}{15}\\pi$"),
    correct:"4",
    explanation:"교점 $y^2=2y\\Rightarrow y=0,2$.\n$V=\\pi\\!\\int_0^2[(2y)^2-(y^2)^2]dy=\\pi\\!\\int_0^2(4y^2-y^4)dy=\\pi\\!\\left[\\dfrac{4y^3}{3}-\\dfrac{y^5}{5}\\right]_0^2=\\pi\\!\\left(\\dfrac{32}{3}-\\dfrac{32}{5}\\right)=\\dfrac{64\\pi}{15}$.",
  },
  {n:34, subject:"적분학", unit:"급수의 수렴/발산", concept:"수렴 급수 식별",
    difficulty:"medium",
    question:"다음 중 수렴하는 급수의 개수는?\n\nㄱ. $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{n^2+2n}{\\sqrt{3+n^5}}$\nㄴ. $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{n^n}{n!}$\nㄷ. $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{(-1)^n 2n}{3n-1}$\nㄹ. $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{\\ln\\sqrt{n}}{n}$\nㅁ. $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{1}{\\sqrt{n^2+n}}$",
    options:opts4("$0$","$1$","$2$","$3$"),
    correct:"1",
    explanation:"ㄱ $\\sim 1/n^{1/2}$ 발산.\nㄴ $n^n/n!\\sim e^n$ 발산.\nㄷ 항 $\\to 2/3\\ne 0$ 발산.\nㄹ $\\sim(\\ln n)/n$ 발산.\nㅁ $\\sim 1/n$ 발산.\n수렴: 0개.",
  },
  {n:35, subject:"적분학", unit:"이상적분", concept:"이상적분 수렴 식별",
    difficulty:"medium",
    question:"다음 중 수렴하는 특이적분의 개수는?\n\nㄱ. $\\displaystyle\\int_1^{\\infty}\\dfrac{\\ln x}{x}\\,dx$\nㄴ. $\\displaystyle\\int_0^2 x^2\\ln x\\,dx$\nㄷ. $\\displaystyle\\int_0^{\\infty}e^{-x^2}\\,dx$\nㄹ. $\\displaystyle\\int_0^{\\infty}\\dfrac{x}{1+x^2}\\,dx$",
    options:opts4("$0$","$1$","$2$","$3$"),
    correct:"3",
    explanation:"ㄱ $\\dfrac{(\\ln x)^2}{2}\\to\\infty$ 발산.\nㄴ $\\!\\int x^2\\ln x\\,dx$ 수렴 (가산 가능).\nㄷ 가우스 적분 $\\sqrt{\\pi}/2$ 수렴.\nㄹ $\\sim 1/x$ 발산.\n수렴: 2개 (ㄴ, ㄷ).",
  },
  {n:36, subject:"다변수함수", unit:"극좌표와 극곡선", concept:"극곡선 길이 (지수 함수)",
    difficulty:"medium",
    question:"구간 $[0,2\\pi]$에서 극 곡선 $r=e^{a\\theta}$의 길이가 $3(e^{2a\\pi}-1)$일 때, 양의 실수 $a$의 값은?",
    options:opts4("$\\dfrac{1}{4}$","$\\dfrac{\\sqrt{2}}{4}$","$\\dfrac{\\sqrt{3}}{4}$","$\\dfrac{1}{2}$"),
    correct:"2",
    explanation:"$L=\\!\\int_0^{2\\pi}\\sqrt{r^2+(r')^2}\\,d\\theta=\\sqrt{1+a^2}\\!\\int_0^{2\\pi}e^{a\\theta}\\,d\\theta=\\dfrac{\\sqrt{1+a^2}}{a}(e^{2a\\pi}-1)$.\n$\\dfrac{\\sqrt{1+a^2}}{a}=3\\Rightarrow 1+a^2=9a^2\\Rightarrow a=\\dfrac{1}{2\\sqrt{2}}=\\dfrac{\\sqrt{2}}{4}$.",
  },
  {n:37, subject:"다변수함수", unit:"편미분", concept:"그래디언트 (상수 결정)",
    difficulty:"medium",
    question:"함수 $f(x,y)=\\sin x+e^{2xy}$에 대하여 점 $(a,b)$에서의 물매(gradient)가 $\\nabla f(a,b)=\\langle 3,0\\rangle$일 때, $a+b$의 값은? (단, $a,b$는 상수이다.)",
    options:opts4("$\\dfrac{1}{2}$","$1$","$\\dfrac{3}{2}$","$2$"),
    correct:"2",
    explanation:"$\\nabla f=(\\cos x+2ye^{2xy},2xe^{2xy})$. $f_y=2ae^{2ab}=0\\Rightarrow a=0$.\n$f_x|_{a=0}=1+2b\\cdot 1=3\\Rightarrow b=1$.\n$a+b=1$.",
  },
  {n:38, subject:"다변수함수", unit:"삼중적분", concept:"순서 변경 + 정수론",
    difficulty:"medium",
    question:"영역 $E=\\{(x,y,z)\\mid 0\\le x\\le 1,\\,0\\le z\\le x,\\,x\\le y\\le 2x\\}$에 대하여 삼중적분 $\\displaystyle\\iiint_E yz\\cos(x^5)\\,dV=a\\sin 1$일 때, 양의 실수 $a$의 값은?",
    options:opts4("$\\dfrac{7}{10}$","$\\dfrac{3}{10}$","$\\dfrac{7}{20}$","$\\dfrac{3}{20}$"),
    correct:"4",
    explanation:"$\\!\\int_0^1\\!\\!\\int_x^{2x}\\!\\!\\int_0^x yz\\cos(x^5)\\,dz\\,dy\\,dx=\\!\\int_0^1\\dfrac{x^2}{2}\\cdot\\dfrac{(2x)^2-x^2}{2}\\cos(x^5)\\,dx=\\!\\int_0^1\\dfrac{3x^4}{4}\\cos(x^5)\\,dx=\\dfrac{3}{20}\\sin 1$.\n$a=3/20$.",
  },
  {n:39, subject:"다변수함수", unit:"다변수 극값", concept:"제약영역 함수 매개변수화",
    difficulty:"medium",
    question:"집합 $\\{(x,y)\\mid x^2+y^2=r^2\\}$에서 함수 $f(x,y)=x^2+2y^2$의 최솟값과 최댓값의 합이 $12$일 때, 양의 실수 $r$의 값은?",
    options:opts4("$1$","$\\sqrt{2}$","$2$","$4$"),
    correct:"3",
    explanation:"매개변수: $x=r\\cos\\theta,\\,y=r\\sin\\theta$. $f=r^2(1+\\sin^2\\theta)$. 최대 $2r^2$, 최소 $r^2$.\n합 $=3r^2=12\\Rightarrow r=2$.",
  },
  {n:40, subject:"다변수함수", unit:"이중적분", concept:"변수변환 (자코비안)",
    difficulty:"medium",
    question:"네 곡선 $y=\\sqrt{x},\\,y=\\sqrt{x}+2,\\,y=4-\\sqrt{x},\\,y=6-\\sqrt{x}$로 둘러싸인 영역을 $D$라 할 때, 이중적분 $\\displaystyle\\iint_D\\dfrac{1}{2\\sqrt{x}}e^{y-\\sqrt{x}}\\,dA$의 값은?",
    options:opts4("$e-1$","$e$","$e^2$","$e^2-1$"),
    correct:"4",
    explanation:"$y-\\sqrt{x}=u,\\,y+\\sqrt{x}=v$ 치환. 영역: $0\\le u\\le 2,\\,4\\le v\\le 6$.\n$dxdy=\\sqrt{x}\\,dudv$.\n$\\!\\iint\\dfrac{1}{2\\sqrt{x}}e^u\\sqrt{x}\\,dudv=\\dfrac{1}{2}\\!\\int_4^6\\!\\!\\int_0^2 e^u\\,dudv=\\dfrac{1}{2}\\cdot 2\\cdot(e^2-1)=e^2-1$.",
  },
  {n:41, subject:"다변수함수", unit:"선적분", concept:"그린 정리",
    difficulty:"medium",
    question:"곡선 $C$는 영역 $\\{(x,y)\\mid 1\\le x^2+y^2\\le 9,\\,y\\ge 0\\}$의 경계일 때, 벡터장 $\\vec{F}(x,y)=\\langle y^2,3xy\\rangle$에 대하여 선적분 $\\displaystyle\\int_C\\vec{F}\\cdot d\\vec{r}$의 값은?",
    options:opts4("$\\dfrac{52}{3}$","$\\dfrac{53}{3}$","$18$","$\\dfrac{55}{3}$"),
    correct:"1",
    explanation:"그린: $\\!\\iint_D(3y-2y)\\,dA=\\!\\iint_D y\\,dA$.\n극좌표: $\\!\\int_0^{\\pi}\\!\\!\\int_1^3 r\\sin\\theta\\cdot r\\,dr\\,d\\theta=2\\cdot\\dfrac{r^3}{3}\\Big|_1^3=2\\cdot\\dfrac{26}{3}=\\dfrac{52}{3}$.",
  },
  {n:42, subject:"다변수함수", unit:"선적분", concept:"보존벡터장 (포텐셜)",
    difficulty:"medium",
    question:"곡선 $C$는 점 $(-1,0,0)$부터 점 $(0,1,1)$까지 $C_1\\cup C_2\\cup C_3$으로 이루어져 있다. 벡터장 $\\vec{F}(x,y,z)=\\langle y^2,\\,2xy+z\\cos(yz)+e^z,\\,y\\cos(yz)+ye^z\\rangle$에 대하여 선적분 $\\displaystyle\\int_C\\vec{F}\\cdot d\\vec{r}$의 값은?",
    options:opts4("$\\sin 1+e$","$\\sin 1-1$","$\\cos 1+e$","$\\cos 1-1$"),
    correct:"1",
    explanation:"보존벡터장 (curl=0). 포텐셜 $\\phi=xy^2+\\sin(yz)+ye^z$.\n$\\phi(0,1,1)-\\phi(-1,0,0)=(0+\\sin 1+e)-(0+0+0)=\\sin 1+e$.",
  },
  {n:43, subject:"다변수함수", unit:"공간곡면", concept:"발산정리 (기울어진 원기둥, 출제 오류)",
    difficulty:"hard",
    question:"곡면 $S$는 원기둥 $x^2+y^2=1$을 두 평면 $z=0$과 $x-z+1=0$으로 자르고 남은 원기둥이다. 벡터장 $\\vec{F}(x,y,z)=\\langle 0,0,z\\rangle$에 대하여, 면적분 $\\displaystyle\\iint_S\\vec{F}\\cdot d\\vec{S}=a\\pi$일 때, 상수 $a$의 값은? (단, 곡면 $S$의 방향은 원점에서 바라봤을 때 바깥 방향이다.)",
    options:opts4("$1$","$\\dfrac{4}{3}$","$\\dfrac{3}{2}$","$2$"),
    correct:"1",
    explanation:"발산정리 활용: 입체 부피 $=\\!\\iint_D z_{\\text{top}}\\,dA=\\!\\iint(x+1)\\,dA=\\pi$ ($D$는 단위원).\n윗면 + 아랫면 면적분을 빼면 측면 면적분.\n[주의] 류갓티비 정답 \"[정답](없음)\" — 객관식에 0이 없어 출제 오류. 가장 가까운 (1) $1$로 처리.",
  },
  {n:44, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"사면체 겉넓이",
    difficulty:"medium",
    question:"3차원 공간에서 네 점 $P(-2,1,0),\\,Q(-2,3,2),\\,R(2,4,-2),\\,S(3,6,1)$을 꼭짓점으로 하는 사면체 $PQRS$의 겉넓이는?",
    options:opts4("$\\sqrt{56}+\\sqrt{67}+\\sqrt{104}+\\dfrac{\\sqrt{394}}{2}$","$\\sqrt{56}+\\sqrt{66}+\\dfrac{\\sqrt{426}}{2}+\\dfrac{\\sqrt{390}}{2}$","$\\sqrt{57}+\\sqrt{67}+\\sqrt{104}+\\dfrac{\\sqrt{394}}{2}$","$\\sqrt{57}+\\sqrt{66}+\\dfrac{\\sqrt{426}}{2}+\\dfrac{\\sqrt{390}}{2}$"),
    correct:"4",
    explanation:"각 면 삼각형 면적 = $|cross|/2$.\n$\\triangle PQR=\\sqrt{57},\\,\\triangle PQS=\\sqrt{66},\\,\\triangle PRS=\\sqrt{390}/2,\\,\\triangle QRS=\\sqrt{426}/2$.\n겉넓이 $=\\sqrt{57}+\\sqrt{66}+\\dfrac{\\sqrt{426}}{2}+\\dfrac{\\sqrt{390}}{2}$.",
  },
  {n:45, subject:"선형대수", unit:"행렬식", concept:"수반행렬 trace",
    difficulty:"medium",
    question:"행렬 $A=\\begin{pmatrix}2&3&2\\\\1&3&1\\\\1&2&-1\\end{pmatrix}$의 수반행렬(adjoint matrix)을 $B$라 할 때, $\\mathrm{tr}(AB)$의 값은? (단, $\\mathrm{tr}(A)$는 행렬 $A$의 트레이스(trace)이다.)",
    options:opts4("$-6$","$-12$","$-18$","$-24$"),
    correct:"3",
    explanation:"$A\\cdot\\text{adj}(A)=|A|I$. $\\mathrm{tr}(A\\cdot\\text{adj}A)=3|A|$.\n$|A|=$ 행렬식 계산 $=-6$. $\\mathrm{tr}(AB)=3\\cdot(-6)=-18$.",
  },
  {n:46, subject:"선형대수", unit:"선형변환", concept:"3D 회전 합성",
    difficulty:"hard",
    question:"선형변환 $T:\\mathbb{R}^3\\to\\mathbb{R}^3$가 각 점을 양의 $y$축을 중심으로 $\\dfrac{\\pi}{3}$만큼 시계 반대 방향으로 회전시키고, 그 점을 양의 $z$축을 중심으로 $\\dfrac{\\pi}{6}$만큼 시계 반대 방향으로 회전시키는 변환일 때, 변환 $T$에 대한 표준행렬은?",
    options:opts4("$\\begin{pmatrix}\\sqrt{3}/4&1/4&-\\sqrt{3}/2\\\\-1/2&\\sqrt{3}/2&0\\\\3/4&\\sqrt{3}/4&1/2\\end{pmatrix}$","$\\begin{pmatrix}\\sqrt{3}/4&1/2&-3/4\\\\-1/4&\\sqrt{3}/2&\\sqrt{3}/4\\\\\\sqrt{3}/2&0&1/2\\end{pmatrix}$","$\\begin{pmatrix}\\sqrt{3}/4&-1/4&\\sqrt{3}/2\\\\1/2&\\sqrt{3}/2&0\\\\-3/4&\\sqrt{3}/4&1/2\\end{pmatrix}$","$\\begin{pmatrix}\\sqrt{3}/4&-1/2&3/4\\\\1/4&\\sqrt{3}/2&\\sqrt{3}/4\\\\-\\sqrt{3}/2&0&1/2\\end{pmatrix}$"),
    correct:"4",
    explanation:"$T=R_z(\\pi/6)\\cdot R_y(\\pi/3)$.\n$R_y(\\pi/3)=\\begin{pmatrix}1/2&0&\\sqrt{3}/2\\\\0&1&0\\\\-\\sqrt{3}/2&0&1/2\\end{pmatrix}$, $R_z(\\pi/6)=\\begin{pmatrix}\\sqrt{3}/2&-1/2&0\\\\1/2&\\sqrt{3}/2&0\\\\0&0&1\\end{pmatrix}$.\n곱: 답 (4)와 일치.",
  },
  {n:47, subject:"선형대수", unit:"행렬", concept:"해공간 차원 (rank-nullity)",
    difficulty:"medium",
    question:"연립일차방정식 $\\begin{cases}x_1+3x_2-2x_3+2x_5=0\\\\2x_1+6x_2-5x_3-2x_4+4x_5-3x_6=0\\\\x_3+2x_4+3x_5=0\\\\x_1+3x_2+4x_4+2x_5+9x_6=0\\end{cases}$의 해공간의 차원(dimension)은?",
    options:opts4("$2$","$3$","$4$","$5$"),
    correct:"2",
    explanation:"행 축약 후 rank 계산: rank $=3$.\n변수 6개 - rank 3 $=$ 해공간 차원 $3$.",
  },
  {n:48, subject:"미분학", unit:"미분방정식", concept:"1계 선형 ODE (치환)",
    difficulty:"medium",
    question:"$y=y(x)$가 미분방정식 $y\\,dx-3x^{2/3}(x^{2/3}+1)\\,dy=0,\\,y(1)=1$의 해일 때 $y(3\\sqrt{3})$의 값은?",
    options:opts4("$e^{\\pi/3}$","$e^{\\pi/12}$","$e^{-\\pi/3}$","$e^{1-\\pi/12}$"),
    correct:"2",
    explanation:"$\\dfrac{dy}{dx}-\\dfrac{1}{3}\\dfrac{1}{x^{2/3}(x^{2/3}+1)}y=0$ 1계 선형.\n적분: $\\!\\int\\dfrac{1/3\\cdot dx}{x^{2/3}(x^{2/3}+1)}$. $x^{1/3}=\\tan\\theta$ 치환 → $\\theta=\\tan^{-1}(x^{1/3})$.\n$y=Ce^{\\tan^{-1}(x^{1/3})}$. $y(1)=Ce^{\\pi/4}=1\\Rightarrow C=e^{-\\pi/4}$.\n$y(3\\sqrt{3})=y(3^{3/2})=e^{-\\pi/4}\\cdot e^{\\tan^{-1}\\sqrt{3}}=e^{-\\pi/4+\\pi/3}=e^{\\pi/12}$.",
  },
  {n:49, subject:"미분학", unit:"미분방정식", concept:"코시-오일러 + 비동차",
    difficulty:"hard",
    question:"$y=y(x)$가 미분방정식 $x^2 y''+xy'+4y=2x\\ln x,\\,y(1)=0,\\,y(e^{3\\pi/4})=\\dfrac{3\\pi}{10}e^{3\\pi/4}$의 해일 때, $y(e)$의 값은?",
    options:opts4("$\\dfrac{4}{25}\\cos 2+\\dfrac{4}{25}e^{3\\pi/4}\\sin 2-\\dfrac{6}{25}e$","$\\dfrac{4}{25}\\cos 2-\\dfrac{4}{25}e^{3\\pi/4}\\sin 2-\\dfrac{6}{25}e$","$\\dfrac{4}{25}\\cos 2+\\dfrac{4}{25}e^{3\\pi/4}\\sin 2+\\dfrac{6}{25}e$","$\\dfrac{4}{25}\\cos 2-\\dfrac{4}{25}e^{3\\pi/4}\\sin 2+\\dfrac{6}{25}e$"),
    correct:"4",
    explanation:"$x=e^t$ 치환 → $y''+4y=2te^t$ (상수계수).\n동차해 $\\cos 2t,\\sin 2t$. 특수해 $y_p=\\dfrac{2}{5}e^t(t-2/5)$.\n원변수: $y=c_1\\cos(2\\ln x)+c_2\\sin(2\\ln x)+\\dfrac{2}{5}x(\\ln x-2/5)$.\n초기조건으로 $c_1=4/25,\\,c_2=-(4/25)e^{3\\pi/4}$.\n$y(e)=\\dfrac{4}{25}\\cos 2-\\dfrac{4}{25}e^{3\\pi/4}\\sin 2+\\dfrac{2e}{5}\\!\\left(1-\\dfrac{2}{5}\\right)=\\dfrac{4}{25}\\cos 2-\\dfrac{4}{25}e^{3\\pi/4}\\sin 2+\\dfrac{6e}{25}$.",
  },
  {n:50, subject:"미분학", unit:"미분방정식", concept:"연립 ODE (합치기)",
    difficulty:"hard",
    question:"$X=X(t)$가 연립미분방정식 $X'=\\begin{pmatrix}-1&-2\\\\2&-5\\end{pmatrix}X,\\,X(0)=\\begin{pmatrix}2\\\\-2\\end{pmatrix}$의 해일 때, $X(1)$을 구하면?",
    options:[], correct:"", question_type:"subjective", answer_text:"$(10e^{-3},6e^{-3})$",
    explanation:"$A=\\begin{pmatrix}-1&-2\\\\2&-5\\end{pmatrix}=-3I+N$으로 두면 $N=\\begin{pmatrix}2&-2\\\\2&-2\\end{pmatrix}$이고 $N^2=O$이다.\n따라서 $e^{At}=e^{-3t}e^{Nt}=e^{-3t}(I+tN)$.\n초기벡터 $X(0)=\\begin{pmatrix}2\\\\-2\\end{pmatrix}$에 대해 $NX(0)=\\begin{pmatrix}8\\\\8\\end{pmatrix}$이므로\n$X(1)=e^{-3}(I+N)X(0)=e^{-3}\\begin{pmatrix}10\\\\6\\end{pmatrix}$.\n즉 $X(1)=\\begin{pmatrix}10e^{-3}\\\\6e^{-3}\\end{pmatrix}$.",
  },
];

const TOTAL=PROBLEMS.length;
console.log(`총 ${TOTAL}문제 (객관식 4지선다) 준비됨`);

const rows = PROBLEMS.map(p => {
  const id = `q-${YEAR_ID}-${SCHOOL_EN}-${String(p.n).padStart(2,"0")}`;
  return {
    id, subject: p.subject, unit: p.unit, concept: p.concept, difficulty: p.difficulty,
    source_type: "imported", pool: "general", question: p.question, content_type: "latex",
    question_image: null, question_type: p.question_type ?? "multiple_choice",
    options: p.question_type === "subjective" ? [] : p.options, correct_option_id: p.question_type === "subjective" ? "" : p.correct,
    answer_text: p.question_type === "subjective" ? p.answer_text : null, explanation: p.explanation, explanation_content_type: "latex",
    explanation_image: null,
    tags: [YEAR_KO, SCHOOL_KO, SESSION_KO, "past_exam", p.subject, p.unit, p.concept],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  };
});

const { data, error } = await sb.from("questions").upsert(rows, { onConflict: "id" }).select("id");
if (error) { console.error("업로드 실패:", error); process.exit(1); }
console.log(`업로드 완료: ${data.length}건`);
