// 2024년 중앙대 편입수학 객관식 30문항 (4지선다)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR="2024", SCHOOL_KO="중앙대", SCHOOL_EN="cau";
const opts4 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:1, subject:"미분학", unit:"극한과 연속", concept:"지수형 극한",
    difficulty:"medium",
    question:"극한 $\\!\\displaystyle\\lim_{x\\to 0+}(e^{\\sin x}+3x)^{1/\\tan x}$의 값은?",
    options:opts4("$1$","$e$","$e^4$","$\\infty$"),
    correct:"3",
    explanation:"$\\ln$ 적용: $\\dfrac{\\ln(1+(\\sin x+3x+\\cdots))}{\\tan x}\\sim\\dfrac{\\sin x+3x}{\\tan x}\\to 1+3=4$.\n극한 $=e^4$.",
  },
  {n:2, subject:"미분학", unit:"도함수와 그래프", concept:"치환 후 임계점",
    difficulty:"medium",
    question:"함수 $f(x)=-(e^x+e^{-x})^3+6(e^x+e^{-x})^2+15(e^x+e^{-x})$가 최댓값을 갖는 $x$를 $\\alpha,\\beta$ (단, $\\alpha>\\beta$)라 할 때, $e^{2\\alpha}+e^{2\\beta}$의 값은?",
    options:opts4("$2$","$14$","$23$","$34$"),
    correct:"3",
    explanation:"$y=e^x+e^{-x}\\ge 2$. $g(y)=-y^3+6y^2+15y$, $g'=0\\Rightarrow y=5$.\n$e^x+e^{-x}=5\\Rightarrow e^{2x}-5e^x+1=0\\Rightarrow e^x=\\dfrac{5\\pm\\sqrt{21}}{2}$.\n$e^{2\\alpha}+e^{2\\beta}=\\dfrac{(5+\\sqrt{21})^2+(5-\\sqrt{21})^2}{4}=\\dfrac{92}{4}=23$.",
  },
  {n:3, subject:"다변수함수", unit:"중적분", concept:"적분순서 변경",
    difficulty:"medium",
    question:"적분 $\\!\\displaystyle\\int_0^1\\!\\!\\int_x^1 x^{2022}\\sqrt{1+y^{2024}}\\,dy\\,dx$의 값은?",
    options:opts4("$\\dfrac{1}{2024\\cdot 3036}(2\\sqrt 2-1)$","$\\dfrac{1}{2023\\cdot 3036}(2\\sqrt 2-1)$","$\\dfrac{1}{2024\\cdot 3036}(\\sqrt 2-1)$","$\\dfrac{1}{2023\\cdot 3036}(\\sqrt 2-1)$"),
    correct:"2",
    explanation:"순서 변경 $0\\le y\\le 1,\\,0\\le x\\le y$: $\\!\\int_0^1\\sqrt{1+y^{2024}}\\cdot\\dfrac{y^{2023}}{2023}dy$.\n$u=1+y^{2024}$: $=\\dfrac{1}{2023\\cdot 2024}\\!\\int_1^2\\sqrt u\\,du=\\dfrac{2(2\\sqrt 2-1)}{3\\cdot 2023\\cdot 2024}=\\dfrac{2\\sqrt 2-1}{2023\\cdot 3036}$.",
  },
  {n:4, subject:"적분학", unit:"급수의 수렴/발산", concept:"수렴 보기 4개",
    difficulty:"medium",
    question:"다음 <보기>의 급수 중에서 수렴하는 것의 개수는?\n(가) $\\!\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{1}{n(\\ln(n+1))^2}$\n(나) $\\!\\displaystyle\\sum_{n=1}^{\\infty}\\arctan\\dfrac{1}{n}$\n(다) $\\!\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{\\cos(n\\pi)}{\\sqrt n}$\n(라) $\\!\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{1}{n\\!\\left(1+\\dfrac{1}{\\sqrt[3]{2^2}}+\\dfrac{1}{\\sqrt[3]{3^2}}+\\cdots+\\dfrac{1}{\\sqrt[3]{n^2}}\\right)}$",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"3",
    explanation:"(가) $p$-급수 형태 $p=2$ 수렴. (나) $\\arctan(1/n)\\sim 1/n$ 발산. (다) 교대급수 $\\sum(-1)^n/\\sqrt n$ 수렴. (라) 분모 $\\sim 3n^{1/3}$, 항 $\\sim 1/n^{4/3}$ 수렴.\n수렴 $3$개.",
  },
  {n:5, subject:"적분학", unit:"급수의 수렴/발산", concept:"테일러 계수 (복소수)",
    difficulty:"hard",
    question:"$f(x)=e^x(\\cos 2x+\\sin 2x)$를 $x=0$에서 Taylor급수 전개하였을 때, $x^5$의 계수를 $a_5$라고 하자. 이때, $5!\\times a_5$의 값은?",
    options:opts4("$3$","$5$","$7$","$9$"),
    correct:"1",
    explanation:"$e^x(\\cos 2x+\\sin 2x)=\\sqrt 2\\,\\Im\\!\\left(e^{(1+2i)x}\\cdot e^{i\\pi/4}\\right)$.\n$x^5$ 계수 $=\\dfrac{1}{5!}\\cdot\\sqrt 2\\,\\Im(e^{i\\pi/4}(1+2i)^5)$. $(1+2i)^5=41-38i$.\n$\\Im(e^{i\\pi/4}(41-38i))=\\dfrac{3\\sqrt 2}{2}$. $\\sqrt 2\\cdot\\dfrac{3\\sqrt 2}{2}=3$. $5!\\,a_5=3$.",
  },
  {n:6, subject:"미분학", unit:"도함수", concept:"수직 접선 조건",
    difficulty:"medium",
    question:"두 곡선 $y^3=x^2$과 $\\dfrac{x^2}{a^2}+\\dfrac{y^2}{b^2}=1$의 교점에서 각 곡선에 대한 접선이 서로 수직이 되는, $a$와 $b$의 일반적인 관계식은?",
    options:opts4("$3b^2=2a^2$","$2b^3=3a^2$","$3b^2=2a^3$","$2b^2=3a^2$"),
    correct:"4",
    explanation:"$y^3=x^2$: $y'=\\dfrac{2x}{3y^2}$. 타원: $y'=-\\dfrac{b^2 x}{a^2 y}$.\n수직 조건: 곱 $=-1\\Rightarrow\\dfrac{2b^2 x^2}{3a^2 y^3}=1$. $y^3=x^2$ 대입: $2b^2=3a^2$.",
  },
  {n:7, subject:"미분학", unit:"극한과 연속", concept:"역삼각함수 합",
    difficulty:"easyMedium",
    question:"$\\sin^{-1}\\!\\left(\\dfrac{4}{\\sqrt{17}}\\right)=\\theta_1$이고 $\\sin^{-1}\\!\\left(\\dfrac{1}{\\sqrt{17}}\\right)=\\theta_2$일 때, $\\theta_1+\\theta_2$의 값은? (단, $-\\pi/2\\le\\theta_i\\le\\pi/2$.)",
    options:opts4("$-\\dfrac{\\pi}{2}$","$0$","$\\dfrac{\\pi}{2}$","$\\pi$"),
    correct:"3",
    explanation:"$\\sin\\theta_1=4/\\sqrt{17},\\,\\cos\\theta_1=1/\\sqrt{17}$. $\\sin\\theta_2=1/\\sqrt{17},\\,\\cos\\theta_2=4/\\sqrt{17}$.\n$\\sin(\\theta_1+\\theta_2)=\\dfrac{4\\cdot 4+1\\cdot 1}{17}=1$. $\\theta_1+\\theta_2=\\pi/2$.",
  },
  {n:8, subject:"미분학", unit:"극한과 연속", concept:"floor 함수 불연속",
    difficulty:"hard",
    question:"함수 $f(x)=[2\\cos x-\\cos 2x]$에 대하여 구간 $0<x<3\\pi$에서 불연속인 점의 개수는? (단, $[x]$는 $x$보다 크지 않은 최대의 정수이다.)",
    options:opts4("$10$","$11$","$12$","$13$"),
    correct:"3",
    explanation:"$g(u)=-2u^2+2u+1$ ($u=\\cos x$, $u\\in[-1,1]$), 범위 $[-3,3/2]$. $g(u)=n$ ($n\\in\\{-3,-2,-1,0,1\\}$)에서 floor 변경.\n각 $n$의 $u$ 값에 대해 $0<x<3\\pi$ 안 $\\cos x=u$의 해 개수를 합산하면 $12$.",
  },
  {n:9, subject:"다변수함수", unit:"편도함수", concept:"합성함수 임계점",
    difficulty:"medium",
    question:"함수 $f(z)=\\tanh z=\\dfrac{e^z-e^{-z}}{e^z+e^{-z}},\\,g(x,y)=x^3-12xy+8y^3$이라 하자. 합성함수 $h(x,y)=(f\\circ g)(x,y)=f(g(x,y))$의 $\\mathbb R^2$에서의 임계점을 $(a,b),(c,d)$라고 하면, $a+b+c+d$의 값은? (단, $(a,b)\\ne(c,d)$.)",
    options:opts4("$-3$","$-2$","$2$","$3$"),
    correct:"4",
    explanation:"$f'>0$이므로 $\\nabla h=0\\iff\\nabla g=0$.\n$g_x=3x^2-12y=0,\\,g_y=-12x+24y^2=0$. 풀면 $(0,0),(2,1)$.\n합 $=0+0+2+1=3$.",
  },
  {n:10, subject:"다변수함수", unit:"선적분과 면적분", concept:"보존장 선적분",
    difficulty:"medium",
    question:"$\\mathbb R^3$에서 정의된 벡터장 $F(x,y,z)=(y\\cos z-yze^x,\\,x\\cos z-ze^x,\\,-xy\\sin z-ye^x)$을 다음 곡선 $C$를 따라 적분한 선적분 $\\!\\displaystyle\\int_C F\\cdot dr$의 값은? 여기서 $C:r(t)=(\\cos t,\\sin t,t),\\,0\\le t\\le\\pi/2$.",
    options:opts4("$-\\dfrac{\\pi}{2}e^{\\pi/2}$","$-\\dfrac{\\pi}{2}$","$-\\pi$","$-\\pi e^{\\pi/2}$"),
    correct:"2",
    explanation:"$F=\\nabla\\phi,\\,\\phi=xy\\cos z-yze^x$. $r(0)=(1,0,0),\\,\\phi=0$. $r(\\pi/2)=(0,1,\\pi/2),\\,\\phi=0-\\pi/2\\cdot 1=-\\pi/2$.\n적분 $=-\\pi/2$.",
  },
  {n:11, subject:"다변수함수", unit:"중적분", concept:"라이프니츠 편미분",
    difficulty:"medium",
    question:"함수 $f(x,y)=\\!\\displaystyle\\int_{2x+4y}^{3y^2}\\dfrac{1}{1+e^{-u}}\\,du$일 때, $\\dfrac{\\partial^2 f}{\\partial x\\partial y}(0,0)$의 값은?",
    options:opts4("$-2$","$2$","$-3$","$3$"),
    correct:"1",
    explanation:"$f_x=-\\dfrac{2}{1+e^{-(2x+4y)}}$. $f_{xy}=-\\dfrac{8e^{-(2x+4y)}}{(1+e^{-(2x+4y)})^2}$.\n$(0,0)$: $-8/4=-2$.",
  },
  {n:12, subject:"다변수함수", unit:"편도함수", concept:"기울기 단위벡터",
    difficulty:"medium",
    question:"함수 $f(x,y,z)=xe^{-y-z}\\cos(xy)$가 점 $(x,y,z)=(1,0,1)$에서 함숫값이 가장 빨리 증가하는 방향의 단위벡터를 구하면?",
    options:opts4("$\\!\\left(-\\dfrac{1}{\\sqrt 3},-\\dfrac{1}{\\sqrt 3},\\dfrac{1}{\\sqrt 3}\\right)$","$\\!\\left(\\dfrac{1}{\\sqrt 3},\\dfrac{1}{\\sqrt 3},-\\dfrac{1}{\\sqrt 3}\\right)$","$\\!\\left(-\\dfrac{1}{\\sqrt 3},-\\dfrac{1}{\\sqrt 3},-\\dfrac{1}{\\sqrt 3}\\right)$","$\\!\\left(\\dfrac{1}{\\sqrt 3},-\\dfrac{1}{\\sqrt 3},-\\dfrac{1}{\\sqrt 3}\\right)$"),
    correct:"4",
    explanation:"$\\nabla f=(e^{-y-z}\\cos(xy)+\\cdots,\\,-xe^{-y-z}\\cos(xy)+\\cdots,\\,-xe^{-y-z}\\cos(xy))$.\n$(1,0,1)$: $\\nabla f=(e^{-1},-e^{-1},-e^{-1})$. 단위 $(1,-1,-1)/\\sqrt 3$.",
  },
  {n:13, subject:"적분학", unit:"정적분", concept:"역함수와 사이의 영역",
    difficulty:"easyMedium",
    question:"함수 $y=\\sin\\!\\left(\\dfrac{\\pi}{2}x\\right),\\,(0\\le x\\le 1)$의 그래프와 그 역함수 그래프로 둘러싸인 영역의 넓이는?",
    options:opts4("$\\dfrac{4}{\\pi}+1$","$\\dfrac{4}{\\pi}-1$","$\\dfrac{6}{\\pi}+1$","$\\dfrac{6}{\\pi}-1$"),
    correct:"2",
    explanation:"두 그래프는 $y=x$ 대칭. 면적 $=2\\!\\int_0^1(\\sin(\\pi x/2)-x)dx=2\\!\\left[\\dfrac{2}{\\pi}-\\dfrac{1}{2}\\right]=\\dfrac{4}{\\pi}-1$.",
  },
  {n:14, subject:"적분학", unit:"부정적분", concept:"삼각치환 적분",
    difficulty:"medium",
    question:"부정적분 $\\!\\displaystyle\\int\\dfrac{\\sin^7 x}{\\cos^4 x}\\,dx$를 구하면?",
    options:opts4("$\\dfrac{1}{3\\cos^3 x}-\\dfrac{3}{\\cos x}-3\\cos x+\\dfrac{\\cos^3 x}{3}+C$","$\\dfrac{1}{3\\sin^3 x}-\\dfrac{3}{\\sin x}-3\\sin x+\\dfrac{\\sin^3 x}{3}+C$","$\\dfrac{3}{\\cos^3 x}-\\dfrac{1}{3\\cos x}-\\dfrac{\\cos x}{3}+3\\cos^3 x+C$","$\\dfrac{3}{\\sin^3 x}-\\dfrac{1}{3\\sin x}-\\dfrac{\\sin x}{3}+3\\sin^3 x+C$"),
    correct:"1",
    explanation:"$u=\\cos x$ 치환: $\\sin^7 x=\\sin x(1-u^2)^3$. 전개 후 $-\\!\\int(u^{-4}-3u^{-2}+3-u^2)du$.\n$=\\dfrac{1}{3\\cos^3 x}-\\dfrac{3}{\\cos x}-3\\cos x+\\dfrac{\\cos^3 x}{3}+C$.",
  },
  {n:15, subject:"적분학", unit:"부정적분", concept:"부분분수 + 유리함수 조건",
    difficulty:"medium",
    question:"다음 <보기> 중 두 개를 더했을 때, 유리함수로 표현할 수 있는 것은? (단, 유리함수는 분모와 분자가 다항식으로 구성된 함수이다.)\n(가) $\\!\\displaystyle\\int\\dfrac{2x}{x^2-1}dx$\n(나) $\\!\\displaystyle\\int\\dfrac{2}{x(x+1)}dx$\n(다) $\\!\\displaystyle\\int\\dfrac{x^2+1}{x^2(x+1)^2}dx$\n(라) $\\!\\displaystyle\\int\\dfrac{x^2+1}{x^2(x+1)}dx$",
    options:opts4("(가)+(나)","(나)+(다)","(가)+(다)","(나)+(라)"),
    correct:"2",
    explanation:"(나) $=2\\ln|x|-2\\ln|x+1|$, (다) $=-2\\ln|x|-1/x+2\\ln|x+1|-2/(x+1)$.\n합 $=-1/x-2/(x+1)$ → 유리함수.",
  },
  {n:16, subject:"미분학", unit:"극한과 연속", concept:"$(1+1/x)^x$ 형태",
    difficulty:"easyMedium",
    question:"다음 식을 성립하게 하는 실수 $a$의 값은?\n$$\\!\\lim_{x\\to\\infty}\\!\\left(\\dfrac{x-a}{x+2a}\\right)^{\\!x}=e^4$$",
    options:opts4("$\\dfrac{2}{3}$","$-\\dfrac{2}{3}$","$\\dfrac{4}{3}$","$-\\dfrac{4}{3}$"),
    correct:"4",
    explanation:"$x\\ln\\dfrac{x-a}{x+2a}=x\\ln\\!\\left(1+\\dfrac{-3a}{x+2a}\\right)\\to-3a=4\\Rightarrow a=-\\dfrac{4}{3}$.",
  },
  {n:17, subject:"선형대수", unit:"선형변환", concept:"치역 평면 사영",
    difficulty:"medium",
    question:"선형사상 $T:\\mathbb R^3\\to\\mathbb R^3$를 $Tv=Av,\\,A=\\begin{pmatrix}1&2&1\\\\0&2&0\\\\-1&4&-1\\end{pmatrix}$로 정의하자. $T$의 치역은 $\\mathbb R^3$에서 평면을 이룬다. 이 평면 위의 점 중에서 점 $(1,2,3)$과 거리가 최소인 점을 $(a,b,c)$라 할 때, $a+b+c$의 값은?",
    options:opts4("$6$","$\\dfrac{64}{11}$","$\\dfrac{60}{11}$","$\\dfrac{58}{11}$"),
    correct:"2",
    explanation:"치역의 법선 $\\mathbf n=(1,-3,1)$ (열공간 외적).\n$(1,2,3)$의 정사영 차감점 $=\\!\\left(\\dfrac{13}{11},\\dfrac{16}{11},\\dfrac{35}{11}\\right)$. 합 $=\\dfrac{64}{11}$.",
  },
  {n:18, subject:"선형대수", unit:"행렬", concept:"rank=2 조건",
    difficulty:"medium",
    question:"행렬 $\\begin{pmatrix}1&x&x\\\\x&x&1\\\\x&1&x\\end{pmatrix}$의 $\\mathrm{rank}$가 $2$가 되는 $x$를 모두 구하면?",
    options:opts4("$-\\dfrac{1}{2},\\,1$","$0,\\,1$","$-\\dfrac{1}{2}$","$0$"),
    correct:"3",
    explanation:"$\\det=-(x-1)^2(2x+1)=0\\Rightarrow x=1$ 또는 $x=-1/2$.\n$x=1$이면 모든 행 같음 $\\mathrm{rank}=1$. $x=-1/2$이면 $\\mathrm{rank}=2$.",
  },
  {n:19, subject:"다변수함수", unit:"중적분", concept:"평면 절단 원뿔 부피",
    difficulty:"hard",
    question:"평면 $x+y+z=1$과 구면 $x^2+y^2+(z+1)^2=4$의 교집합인 원 $C$가 있다. 평면 $x+y+z=1$에서 원 $C$의 내부를 원뿔의 밑면으로 하고, 구면 위의 점 $P$를 원뿔의 꼭짓점으로 하는 원뿔의 부피 중 최댓값은?",
    options:opts4("$\\dfrac{16}{9}\\pi\\!\\left(1+\\dfrac{1}{\\sqrt 3}\\right)$","$\\dfrac{4}{3}\\pi\\!\\left(1+\\dfrac{1}{\\sqrt 3}\\right)$","$\\dfrac{8}{9}\\pi\\!\\left(1+\\dfrac{1}{\\sqrt 3}\\right)$","$\\dfrac{8}{3}\\pi\\!\\left(1+\\dfrac{1}{\\sqrt 3}\\right)$"),
    correct:"1",
    explanation:"구 중심 $(0,0,-1)$, 평면까지 거리 $d=2/\\sqrt 3$. 원 반지름 $\\sqrt{4-4/3}=2\\sqrt 6/3$.\n밑면 면적 $8\\pi/3$. 최대 높이 $=2/\\sqrt 3+2=2(1+1/\\sqrt 3)$.\n부피 $=\\dfrac{1}{3}\\cdot\\dfrac{8\\pi}{3}\\cdot 2(1+1/\\sqrt 3)=\\dfrac{16\\pi}{9}(1+1/\\sqrt 3)$.",
  },
  {n:20, subject:"다변수함수", unit:"선적분과 면적분", concept:"발산정리 원기둥",
    difficulty:"hard",
    question:"좌표공간에서 두 평면 $z=0,\\,z=1$과 원기둥 $x^2+y^2=9$로 둘러싸인 영역 $R$의 경계를 $S$라 하자. 이때, 벡터장 $F(x,y,z)=(x(x^2+y^2+z^2)+e^{-yz},\\,y(x^2+y^2+z^2)+e^{-zx},\\,z(x^2+y^2+z^2)+e^{-xy})$의 곡면 $S$에 대한 플럭스(유량) $\\!\\displaystyle\\iint_S F\\cdot dS$를 구하면? (단, $S$의 향은 입체의 바깥쪽이다.)",
    options:opts4("$\\dfrac{345\\pi}{2}$","$\\dfrac{435\\pi}{2}$","$\\dfrac{525\\pi}{4}$","$\\dfrac{405\\pi}{4}$"),
    correct:"2",
    explanation:"$\\mathrm{div}\\,F=5(x^2+y^2+z^2)$. 원기둥 좌표 $r\\le 3,\\,z\\in[0,1]$:\n$\\!\\iiint 5(r^2+z^2)\\cdot r\\,dr\\,d\\theta\\,dz=10\\pi\\!\\left(\\dfrac{81}{4}+\\dfrac{3}{2}\\right)=\\dfrac{435\\pi}{2}$.",
  },
  {n:21, subject:"미분학", unit:"도함수", concept:"라이프니츠 곱미분",
    difficulty:"medium",
    question:"$f(x)=x^3 e^x$에서 $n\\ge 3$일 때, $f^{(n)}(1)$의 값은?",
    options:opts4("$e(n^2+n+1)$","$e(n^3+n+1)$","$e(n^2+2n+1)$","$e(n^3+2n+1)$"),
    correct:"4",
    explanation:"라이프니츠: $f^{(n)}(x)=e^x[x^3+3nx^2+3n(n-1)x+n(n-1)(n-2)]$.\n$x=1$: $f^{(n)}(1)=e[1+3n+3n(n-1)+n(n-1)(n-2)]=e(n^3+2n+1)$.",
  },
  {n:22, subject:"다변수함수", unit:"곡선과 곡면", concept:"매개곡선 자취",
    difficulty:"easyMedium",
    question:"매개변수 $t$가 $0\\le t\\le\\pi$를 만족할 때, 평면 위의 점 $P(\\sin^2 t,\\,\\cos t\\sin t)$가 만족하는 자취는 어떤 원 위에 있는가?",
    options:opts4("중심 $\\!\\left(0,\\dfrac{1}{2}\\right)$, 반지름 $\\dfrac{1}{2}$","중심 $\\!\\left(\\dfrac{1}{2},0\\right)$, 반지름 $\\dfrac{1}{2}$","중심 $\\!\\left(0,\\dfrac{1}{2}\\right)$, 반지름 $1$","중심 $\\!\\left(\\dfrac{1}{2},0\\right)$, 반지름 $1$"),
    correct:"2",
    explanation:"$x=\\sin^2 t=\\dfrac{1-\\cos 2t}{2},\\,y=\\dfrac{\\sin 2t}{2}$.\n$\\!\\left(x-\\dfrac{1}{2}\\right)^2+y^2=\\dfrac{1}{4}$ → 중심 $(1/2,0)$, 반지름 $1/2$.",
  },
  {n:23, subject:"미분학", unit:"도함수와 그래프", concept:"극값 찾기",
    difficulty:"easyMedium",
    question:"함수 $f(x)=\\dfrac{x^2-4x+4}{x-5}$가 $x=a$에서 극댓값을 가지고, $x=b$에서 극솟값을 가질 때, $2a^2+b^2$의 값은?",
    options:opts4("$72$","$114$","$132$","$153$"),
    correct:"1",
    explanation:"$f'(x)=\\dfrac{(x-2)(x-8)}{(x-5)^2}$. 부호 분석: $x=2$ 극대, $x=8$ 극소.\n$2\\cdot 4+64=72$.",
  },
  {n:24, subject:"선형대수", unit:"고유치와 대각화", concept:"trace 합",
    difficulty:"easyMedium",
    question:"행렬 $A=\\begin{pmatrix}2&0&-1\\\\1&-3&2\\\\-1&2&6\\end{pmatrix}$가 어떤 행렬 $B$에 대해 $BAB^{-1}=\\begin{pmatrix}a&0&0\\\\0&b&0\\\\0&0&c\\end{pmatrix}$를 만족할 때, $a+b+c$의 값은?",
    options:opts4("$0$","$2$","$3$","$5$"),
    correct:"4",
    explanation:"닮음변환은 trace를 보존: $a+b+c=\\mathrm{tr}(A)=2-3+6=5$.",
  },
  {n:25, subject:"다변수함수", unit:"편도함수", concept:"라그랑주 최대·최소",
    difficulty:"medium",
    question:"타원면 $x^2+2y^2+z^2=1$ 위에서 함수 $f(x,y,z)=xy+z^2$의 최댓값과 최솟값을 각각 $a,b$라 할 때, $a^2+b^2$의 값은?",
    options:opts4("$1$","$\\sqrt{\\dfrac{3}{2}}+1$","$\\dfrac{9}{8}$","$\\dfrac{5}{4}$"),
    correct:"3",
    explanation:"라그랑주 분석: $z\\ne 0$ 케이스 $\\Rightarrow z=\\pm 1,\\,f=1$ (최대). $z=0$ 케이스 $f=xy$ 극값 $\\pm 1/(2\\sqrt 2)$.\n$a=1,\\,b=-1/(2\\sqrt 2)$. $a^2+b^2=1+1/8=9/8$.",
  },
  {n:26, subject:"선형대수", unit:"고유치와 대각화", concept:"행렬 거듭제곱 trace",
    difficulty:"hard",
    question:"행렬 $A=\\begin{pmatrix}0&-1&2\\\\-2&1&2\\\\-3&-1&5\\end{pmatrix}$에 대하여 $3\\times 3$ 행렬 $B=A^{2024}\\!\\begin{pmatrix}1&1&1\\\\1&0&1\\\\1&1&2\\end{pmatrix}$라고 할 때, $B$의 주대각원소의 합 $\\mathrm{tr}(B)$를 구하면?",
    options:opts4("$1+2^{2024}+2\\cdot 3^{2024}$","$1+2^{2024}$","$2^{2024}+2\\cdot 3^{2024}$","$1+2\\cdot 3^{2024}$"),
    correct:"4",
    explanation:"$A$의 특성다항식 $\\lambda^3-6\\lambda^2+11\\lambda-6=(\\lambda-1)(\\lambda-2)(\\lambda-3)$.\n고유값 $1,2,3$. 우측 행렬과의 trace 결합 분석으로 $\\mathrm{tr}(B)=1+2\\cdot 3^{2024}$.",
  },
  {n:27, subject:"선형대수", unit:"행렬", concept:"행렬식 다항식",
    difficulty:"hard",
    question:"$4\\times 4$ 행렬 $A=\\begin{pmatrix}2&0&0&1\\\\0&0&2&1\\\\0&0&1&0\\\\0&1&2&0\\end{pmatrix}$에 대하여 행렬식 $\\det(A^4-3A^3+A^2)$을 구하면?",
    options:opts4("$-20$","$-10$","$0$","$10$"),
    correct:"1",
    explanation:"$\\det(A^4-3A^3+A^2)=\\det(A^2)\\det(A^2-3A+I)$. $A$의 고유값을 구해 $\\!\\prod\\lambda_i^2(\\lambda_i^2-3\\lambda_i+1)$ 계산하면 $-20$.",
  },
  {n:28, subject:"선형대수", unit:"고유치와 대각화", concept:"고유벡터 거듭제곱",
    difficulty:"medium",
    question:"$\\begin{pmatrix}6&-3\\\\-3&6\\end{pmatrix}^{\\!10}\\binom{1}{1}=\\binom{a}{b}$일 때, $a+b$의 값은?",
    options:opts4("$3^{10}$","$2\\cdot 3^{10}$","$3^{11}$","$4\\cdot 3^{10}$"),
    correct:"2",
    explanation:"$(1,1)^T$는 고유값 $3$의 고유벡터: $A(1,1)^T=(3,3)^T$.\n$A^{10}(1,1)^T=3^{10}(1,1)^T$, $a+b=2\\cdot 3^{10}$.",
  },
  {n:29, subject:"선형대수", unit:"행렬", concept:"역행렬 + 행렬방정식",
    difficulty:"medium",
    question:"$A$의 역행렬 $A^{-1}=\\begin{pmatrix}0&1&-1\\\\1&1&0\\\\0&-2/3&-1/3\\end{pmatrix}$일 때, $BA=A^2+A$인 행렬 $B$에 대하여 $\\det(B)$의 값은?",
    options:opts4("$0$","$\\dfrac{2}{3}$","$\\dfrac{4}{3}$","$2$"),
    correct:"3",
    explanation:"$B=(A^2+A)A^{-1}=A+I$. $\\det(A+I)=\\det A\\cdot\\det(I+A^{-1})$.\n$\\det A^{-1}=1$이므로 $\\det A=1$. $\\det(I+A^{-1})=4/3$. $\\det B=4/3$.",
  },
  {n:30, subject:"선형대수", unit:"행렬", concept:"전치행렬 조건 진위",
    difficulty:"medium",
    question:"$A^T=A^TA$이고, $A\\ne O$일 때 다음 <보기>중에서 옳은 것을 모두 고르면? (여기서, $A^T$는 $A$의 전치행렬이고, $O$는 영행렬이다.)\n(가) $A=A^T$\n(나) $A=A^{-1}$\n(다) $A^2=A$\n(라) $\\det(A)=-1$",
    options:opts4("(가),(나)","(나),(다)","(가),(다)","(가),(다),(라)"),
    correct:"3",
    explanation:"$A^T=A^TA$ → 양변 전치 $A=A^TA$ → $A=A^T$ (가). 또 $A^2=A^TA=A^T=A$ (다).\n(나)(라): $A^2=A$ idempotent에서 $\\det\\in\\{0,1\\}$, $A^{-1}$ 일반 거짓.",
  },
];

if (PROBLEMS.length !== 30) { console.error(`PROBLEMS length=${PROBLEMS.length} (expect 30)`); process.exit(1); }
let okCount=0,failCount=0;
for (const p of PROBLEMS) {
  const num=String(p.n).padStart(2,"0");
  const id=`q-${YEAR}-${SCHOOL_EN}-${num}`;
  const tags=[YEAR,SCHOOL_KO,p.subject,p.unit,p.concept].filter(Boolean);
  const row={id,subject:p.subject,unit:p.unit,concept:p.concept,difficulty:p.difficulty,
    source_type:"imported",pool:"general",
    question:p.question,content_type:"latex",question_image:null,
    options:p.options,correct_option_id:p.correct,
    explanation:p.explanation,explanation_content_type:"latex",explanation_image:null,
    tags,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};
  const{error}=await sb.from("questions").upsert(row,{onConflict:"id"});
  if(error){console.error(`❌ ${id}:`,error.message);failCount++;}
  else{console.log(`✓ ${id}`);okCount++;}
}
console.log(`\n총 ${okCount}건 업로드, ${failCount}건 실패 (대상 ${PROBLEMS.length}건)`);
