// 2018년 광운대 편입수학 객관식 30문항 (5지선다)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR="2018", SCHOOL_KO="광운대", SCHOOL_EN="kwangwoon";
const opts5 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:1, subject:"미분학", unit:"수열과 점화식", concept:"수열의 수렴",
    difficulty:"easy",
    question:"다음 수열 중에서 수렴하는 것을 모두 고르면?\n\nⓐ $\\!\\left\\langle\\dfrac{n^3}{3^n}\\right\\rangle$\nⓑ $\\langle(3^n+4^n)^{1/n}\\rangle$\nⓒ $\\!\\left\\langle\\dfrac{1}{n}\\sin\\!\\left(\\dfrac{1}{n^2}\\right)\\right\\rangle$\nⓓ $\\!\\left\\langle\\dfrac{(-1)^n n^2}{n^2+1}\\right\\rangle$",
    options:opts5("ⓐ","ⓐ, ⓑ","ⓐ, ⓑ, ⓒ","ⓐ, ⓑ, ⓒ, ⓓ","ⓑ, ⓓ"),
    correct:"3",
    explanation:"ⓐ $n^3/3^n\\to 0$ (지수가 다항보다 빠름).\nⓑ $(3^n+4^n)^{1/n}\\to 4$ (가장 큰 항의 밑).\nⓒ $\\dfrac{1}{n}\\cdot 0=0\\to 0$.\nⓓ $(-1)^n\\cdot 1$ 진동, 발산.\n수렴: ⓐ, ⓑ, ⓒ.",
  },
  {n:2, subject:"미분학", unit:"도함수", concept:"라이프니츠 공식 (계수 합)",
    difficulty:"medium",
    question:"구간 $I$에서 무한 번 미분 가능한 두 함수 $f$와 $g$의 곱 $fg$의 $10$계 도함수를 다음과 같이 쓸 때 $a_0+a_2+a_4+a_6+a_8+a_{10}$의 값은?\n$$(fg)^{(10)}(x)=\\sum_{r=0}^{10}a_r f^{(10-r)}(x)g^{(r)}(x),\\quad x\\in I$$",
    options:opts5("$512$","$511$","$1024$","$1023$","$1025$"),
    correct:"1",
    explanation:"$a_r=\\binom{10}{r}$ (라이프니츠). $(x+1)^{10}=\\sum a_r x^r$.\n$x=1$: $a_0+a_1+\\cdots+a_{10}=2^{10}$. $x=-1$: $a_0-a_1+\\cdots+a_{10}=0$.\n둘 합/2: $a_0+a_2+\\cdots+a_{10}=2^{10}/2=2^9=512$.",
  },
  {n:3, subject:"미분학", unit:"도함수 응용", concept:"거리의 제곱 합 최소 (산술평균)",
    difficulty:"easy",
    question:"수직선에 있는 $n$개의 점 $a_1,a_2,\\ldots,a_n$으로부터 거리의 제곱의 합이 최소인 수직선의 점은?",
    options:opts5("$0$","$\\displaystyle\\sum_{i=1}^n a_i$","$\\dfrac{1}{n}\\displaystyle\\sum_{i=1}^n a_i$","$\\dfrac{1}{n^2}\\displaystyle\\sum_{i=1}^n a_i^2$","$\\dfrac{1}{2n}\\displaystyle\\sum_{i=1}^n a_i$"),
    correct:"3",
    explanation:"$f(x)=\\sum(x-a_i)^2$. $f'(x)=2\\sum(x-a_i)=0\\Rightarrow x=\\dfrac{1}{n}\\sum a_i$ (산술평균).",
  },
  {n:4, subject:"적분학", unit:"급수의 수렴/발산", concept:"급수 진위 (발산정리·비교판정)",
    difficulty:"medium",
    question:"다음 중 옳은 것을 모두 고르면?\n\nⓐ 급수 $\\displaystyle\\sum_{n=1}^{\\infty}a_n$이 수렴하면 $\\displaystyle\\lim_{n\\to\\infty}a_n=0$이다.\nⓑ 급수 $\\displaystyle\\sum_{n=1}^{\\infty}n^{-2/3}$는 수렴한다.\nⓒ 두 급수 $\\displaystyle\\sum_{n=1}^{\\infty}a_n$과 $\\displaystyle\\sum_{n=1}^{\\infty}b_n$에 대하여 $\\displaystyle\\lim_{n\\to\\infty}\\dfrac{a_n}{b_n}=0$이고 $\\displaystyle\\sum_{n=1}^{\\infty}b_n$이 발산하면 $\\displaystyle\\sum_{n=1}^{\\infty}a_n$도 발산한다.",
    options:opts5("ⓐ","ⓑ","ⓒ","ⓑ, ⓒ","ⓐ, ⓒ"),
    correct:"1",
    explanation:"ⓐ [참] 발산정리.\nⓑ [거짓] $p$-급수, $p=2/3<1$ 발산.\nⓒ [거짓] 올바른 비교판정: $\\sum b_n$ 수렴 + $a_n/b_n\\to 0$이면 $\\sum a_n$ 수렴. 본 명제는 역.",
  },
  {n:5, subject:"다변수함수", unit:"다변수 극값", concept:"헤시안 판정",
    difficulty:"medium",
    question:"함수 $f(x,y)=x^6+y^6-6xy+3$의 정의역의 점 $Q(1,1)$에 대한 설명으로 옳은 것은?",
    options:opts5("점 $Q$는 극대점","점 $Q$는 극소점","점 $Q$는 변곡점","점 $Q$는 안장점","점 $Q$는 최대점"),
    correct:"2",
    explanation:"$f_x=6x^5-6y,\\,f_y=6y^5-6x$. $(1,1)$에서 $f_x=f_y=0$.\n$f_{xx}=30x^4=30,\\,f_{yy}=30y^4=30,\\,f_{xy}=-6$.\n$\\Delta=30\\cdot 30-36=864>0,\\,f_{xx}>0$ ⇒ 극소.",
  },
  {n:6, subject:"다변수함수", unit:"극좌표와 극곡선", concept:"극곡선 교각",
    difficulty:"hard",
    question:"두 곡선 $r=\\cos 2\\theta$와 $r=\\sin 2\\theta$가 극좌표 $\\!\\left(\\dfrac{\\sqrt{2}}{2},\\dfrac{\\pi}{8}\\right)$에서 만날 때, 두 곡선의 교각을 $\\alpha$라 하자. 이때 $\\tan\\alpha$의 값은?",
    options:opts5("$0$","$\\dfrac{1}{3}$","$\\dfrac{2}{3}$","$1$","$\\dfrac{4}{3}$"),
    correct:"5",
    explanation:"$\\tan\\phi_1=\\dfrac{\\cos 2\\theta}{-2\\sin 2\\theta}\\big|_{\\pi/8}=-\\dfrac{1}{2}$, $\\tan\\phi_2=\\dfrac{\\sin 2\\theta}{2\\cos 2\\theta}\\big|_{\\pi/8}=\\dfrac{1}{2}$.\n$\\tan\\alpha=\\!\\left|\\dfrac{\\tan\\phi_1-\\tan\\phi_2}{1+\\tan\\phi_1\\tan\\phi_2}\\right|=\\!\\left|\\dfrac{-1/2-1/2}{1-1/4}\\right|=\\dfrac{4}{3}$.",
  },
  {n:7, subject:"선형대수", unit:"행렬식", concept:"5×5 행렬식 + 거듭제곱",
    difficulty:"medium",
    question:"다음 행렬 $A$에 대하여 $\\det(A^3)$의 값은?\n$$A=\\begin{pmatrix}1&2&0&2&2\\\\2&3&0&7&3\\\\3&3&2&3&4\\\\4&4&0&1&5\\\\0&0&0&1&0\\end{pmatrix}$$",
    options:opts5("$1$","$-1$","$0$","$8$","$-8$"),
    correct:"4",
    explanation:"3열에 0이 많음, 3행만 0이 아님. 3열 라플라스 전개로 $|A|=2\\cdot M_{33}$ ($M_{33}$은 3행·3열 빼고).\n반복적으로 5×5→4×4→3×3 전개로 $|A|=2$ (계산).\n$\\det(A^3)=|A|^3=2^3=8$.",
  },
  {n:8, subject:"선형대수", unit:"고유치와 대각화", concept:"고유벡터 (대각화)",
    difficulty:"hard",
    question:"행렬 $A=\\begin{pmatrix}-1&0&1\\\\3&0&-3\\\\1&0&-1\\end{pmatrix}$에 대해 $P^{-1}AP=\\begin{pmatrix}0&0&0\\\\0&0&0\\\\0&0&-2\\end{pmatrix}$이다. 이때 $P=\\begin{pmatrix}a&b&c\\\\d&e&f\\\\g&h&i\\end{pmatrix}$의 3번째 열 $\\begin{pmatrix}c\\\\f\\\\i\\end{pmatrix}$가 될 수 있는 것은?",
    options:opts5("$\\begin{pmatrix}1\\\\-3\\\\-1\\end{pmatrix}$","$\\begin{pmatrix}1\\\\2\\\\-1\\end{pmatrix}$","$\\begin{pmatrix}1\\\\3\\\\-1\\end{pmatrix}$","$\\begin{pmatrix}-1\\\\2\\\\1\\end{pmatrix}$","$\\begin{pmatrix}-1\\\\0\\\\1\\end{pmatrix}$"),
    correct:"1",
    explanation:"3번째 열은 $\\lambda=-2$의 고유벡터. $A\\vec{v}=-2\\vec{v}$.\n(1) 검증: $A(1,-3,-1)^T=(-1\\cdot 1+0\\cdot(-3)+1\\cdot(-1),\\,3\\cdot 1+0+(-3)(-1),\\,1\\cdot 1+0+(-1)(-1))=(-2,6,2)=-2(1,-3,-1)^T$ ✓.",
  },
  {n:9, subject:"적분학", unit:"테일러급수", concept:"$\\ln$ 함수 매클로린",
    difficulty:"hard",
    question:"함수 $f(x)=\\ln(1+\\cos x)$ ($-\\pi<x<\\pi$)의 메클로린 급수 $\\displaystyle\\sum_{n=0}^{\\infty}a_n x^n$에 대해 $p_4(x)=\\displaystyle\\sum_{n=0}^4 a_n x^n$이라 하자. 이때 $p_4(1)$의 값은?",
    options:opts5("$\\ln 2-\\dfrac{19}{96}$","$\\ln 2-\\dfrac{7}{32}$","$\\ln 2-\\dfrac{23}{96}$","$\\ln 2-\\dfrac{25}{96}$","$\\ln 2-\\dfrac{9}{32}$"),
    correct:"4",
    explanation:"$f(x)=\\ln 2+2\\ln\\cos(x/2)$. 또는 $f'(x)=-\\sin x/(1+\\cos x)=-\\tan(x/2)=-(x/2+x^3/24+\\cdots)$.\n적분: $f(x)=\\ln 2-x^2/4-x^4/96-\\cdots$.\n$p_4(1)=\\ln 2-1/4-1/96=\\ln 2-25/96$.",
  },
  {n:10, subject:"적분학", unit:"적분의 정의", concept:"상적분 (디리클레 형)",
    difficulty:"medium",
    question:"구간 $[0,1]$에서 다음 함수의 상적분은? ($\\mathbb{Q}$는 유리수 집합)\n$$f(x)=\\begin{cases}x^2&(x\\in[0,1]\\cap\\mathbb{Q})\\\\-x^2&(x\\in[0,1]\\cap\\mathbb{Q}^c)\\end{cases}$$",
    options:opts5("$0$","$\\dfrac{1}{3}$","$\\dfrac{2}{3}$","$-\\dfrac{1}{3}$","$-\\dfrac{2}{3}$"),
    correct:"2",
    explanation:"각 구간에서 큰 값(상값)은 $x^2$ (∵ 유리수에서 정의). 상적분 $=\\!\\int_0^1 x^2 dx=\\dfrac{1}{3}$.",
  },
  {n:11, subject:"적분학", unit:"이상적분", concept:"특이적분 발산",
    difficulty:"easy",
    question:"특이 적분 $\\displaystyle\\int_0^1\\!\\left(x-\\dfrac{1}{2}\\right)^{-2}dx$의 값은?",
    options:opts5("$0$","$-1$","$-2$","$-4$","발산한다."),
    correct:"5",
    explanation:"$x=1/2$에서 $1/(x-1/2)^2$이 무한대. 적분 영역 내부 특이점이고 $p=2\\ge 1$이므로 발산.",
  },
  {n:12, subject:"적분학", unit:"정적분의 응용", concept:"$\\cosh$ 곡선 길이",
    difficulty:"easy",
    question:"곡선 $y=\\dfrac{e^x+e^{-x}}{2}$ ($-1\\le x\\le 1$)의 길이는?",
    options:opts5("$e$","$e^{-1}$","$e-e^{-1}$","$e+e^{-1}$","$e^2$"),
    correct:"3",
    explanation:"$y=\\cosh x$, $y'=\\sinh x$. $\\sqrt{1+\\sinh^2 x}=\\cosh x$.\n$L=\\!\\int_{-1}^1\\cosh x\\,dx=2\\sinh 1=e-e^{-1}$.",
  },
  {n:13, subject:"적분학", unit:"정적분의 응용", concept:"회전체 부피 (셸법)",
    difficulty:"medium",
    question:"곡선 $y=\\sqrt{1-(x/2)^2}$ ($1\\le x\\le 2$)와 $x$축, 그리고 직선 $x=1$로 둘러싸인 영역을 $y$축을 중심으로 회전시킬 때 얻어지는 원환통의 부피는?",
    options:opts5("$\\pi$","$\\sqrt{2}\\pi$","$\\sqrt{3}\\pi$","$2\\sqrt{3}\\pi$","$2\\sqrt{2}\\pi$"),
    correct:"3",
    explanation:"셸법: $V=2\\pi\\!\\int_1^2 x\\sqrt{1-x^2/4}\\,dx$. $u=1-x^2/4,\\,du=-x/2\\,dx$.\n$V=-4\\pi\\!\\int u^{1/2}\\,du=-4\\pi\\cdot\\dfrac{2}{3}u^{3/2}\\big|_{x=1}^{x=2}$\n$=-\\dfrac{8\\pi}{3}\\!\\left[0-(3/4)^{3/2}\\right]=\\dfrac{8\\pi}{3}\\cdot\\dfrac{3\\sqrt{3}}{8}=\\sqrt{3}\\pi$.",
  },
  {n:14, subject:"미분학", unit:"미분방정식", concept:"변수분리 ODE (부분분수)",
    difficulty:"medium",
    question:"다음 초깃값 문제의 해는?\n$$\\dfrac{dy}{dx}=y^2-1,\\,y(0)=2$$",
    options:opts5("$y=\\dfrac{3+e^{2x}}{3-e^{2x}}$","$y=\\dfrac{3+e^x}{3-e^x}$","$y=\\dfrac{3+e^{x/2}}{3-e^{x/2}}$","$y=\\dfrac{3+e^x}{5-3e^x}$","$y=\\dfrac{3+e^{-x}}{5-3e^{-x}}$"),
    correct:"1",
    explanation:"$\\dfrac{dy}{y^2-1}=dx$. 부분분수: $\\dfrac{1}{2}\\ln\\!\\left|\\dfrac{y-1}{y+1}\\right|=x+C$.\n$y(0)=2$: $\\dfrac{1}{2}\\ln(1/3)=C$. $\\ln\\!\\left|\\dfrac{y-1}{y+1}\\right|=2x+\\ln(1/3)$.\n$\\dfrac{y-1}{y+1}=\\dfrac{e^{2x}}{3}$ 풀면 $y=\\dfrac{3+e^{2x}}{3-e^{2x}}$.",
  },
  {n:15, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"점-직선 거리",
    difficulty:"medium",
    question:"점 $(1,1,1)$로부터 다음 직선까지의 거리는?\n$$x-1=\\dfrac{y+1}{2}=\\dfrac{z+1}{3}$$",
    options:opts5("$\\sqrt{2/7}$","$\\sqrt{3/7}$","$\\sqrt{4/7}$","$\\sqrt{5/7}$","$\\sqrt{6/7}$"),
    correct:"5",
    explanation:"직선: 점 $A(1,-1,-1)$, 방향 $\\vec{d}=(1,2,3)$.\n$\\vec{AP}=(0,2,2)$. $\\vec{AP}\\times\\vec{d}=(2,2,-2)\\sim$ 외적 모두 계산.\n$d=\\dfrac{|\\vec{AP}\\times\\vec{d}|}{|\\vec{d}|}=\\dfrac{\\sqrt{4+4+16}}{\\sqrt{14}}\\cdot$... 정확히 $=\\sqrt{6/7}$.",
  },
  {n:16, subject:"선형대수", unit:"행렬", concept:"행렬 성질 진위",
    difficulty:"medium",
    question:"$n$차 정사각행렬 $A$에 대한 다음 명제 중 옳은 것을 모두 고르면?\n\nⓐ $\\det(A^{-1})=(\\det A)^{-1}$\nⓑ $AA^T$는 대칭행렬이다.\nⓒ $\\mathrm{tr}(A^T)=(\\mathrm{tr}\\,A)^{-1}$\nⓓ $\\mathrm{tr}(A^{-1})=(\\mathrm{tr}\\,A)^{-1}$",
    options:opts5("ⓐ","ⓑ","ⓐ, ⓑ, ⓒ","ⓐ, ⓑ","ⓐ, ⓑ, ⓓ"),
    correct:"4",
    explanation:"ⓐ [참] 행렬식 곱셈성질.\nⓑ [참] $(AA^T)^T=AA^T$.\nⓒ [거짓] $\\mathrm{tr}(A^T)=\\mathrm{tr}\\,A$ (역수 X).\nⓓ [거짓] 일반적으로 성립 X.",
  },
  {n:17, subject:"선형대수", unit:"선형변환", concept:"사영 변환 행렬",
    difficulty:"easy",
    question:"$\\mathbb{R}^3$에서 $xz$평면으로의 사영 $P(x,y,z)=(x,0,z)$로 정의된 일차 변환 $P:\\mathbb{R}^3\\to\\mathbb{R}^3$에 대응하는 변환 행렬 $A_P$는?",
    options:opts5("$\\begin{pmatrix}1&0&0\\\\0&1&0\\\\0&0&1\\end{pmatrix}$","$\\begin{pmatrix}1&0&1\\\\0&1&0\\\\0&0&1\\end{pmatrix}$","$\\begin{pmatrix}1&0&0\\\\0&1&0\\\\1&0&1\\end{pmatrix}$","$\\begin{pmatrix}1&0&0\\\\0&0&0\\\\0&0&1\\end{pmatrix}$","$\\begin{pmatrix}1&0&0\\\\0&1&0\\\\0&0&0\\end{pmatrix}$"),
    correct:"4",
    explanation:"$xz$평면 사영: $y$ 성분만 $0$. $\\begin{pmatrix}x\\\\0\\\\z\\end{pmatrix}=\\begin{pmatrix}1&0&0\\\\0&0&0\\\\0&0&1\\end{pmatrix}\\begin{pmatrix}x\\\\y\\\\z\\end{pmatrix}$.",
  },
  {n:18, subject:"다변수함수", unit:"공간곡선", concept:"공간곡선 곡률",
    difficulty:"medium",
    question:"다음 곡선 $\\vec{x}(t)$에 대해 $t=0$에서의 곡률은?\n$$\\vec{x}(t)=\\!\\left(\\dfrac{1}{3}(1+t)^{3/2},\\,\\dfrac{1}{3}(1-t)^{3/2},\\,\\dfrac{1}{2}t\\right)\\quad(-1<t<1)$$",
    options:opts5("$\\dfrac{1}{3}$","$\\dfrac{\\sqrt{2}}{3}$","$\\dfrac{\\sqrt{3}}{3}$","$\\dfrac{2}{3}$","$\\dfrac{\\sqrt{5}}{3}$"),
    correct:"2",
    explanation:"$\\vec{x}'(0)=(1/2,-1/2,1/2)$, $|\\vec{x}'(0)|=\\sqrt{3}/2$.\n$\\vec{x}''(0)=(1/4,1/4,0)$. $\\vec{x}'(0)\\times\\vec{x}''(0)=(-1/8,1/8,1/4)$, $|\\cdot|=\\sqrt{6}/8$.\n$\\kappa=\\dfrac{\\sqrt{6}/8}{(\\sqrt{3}/2)^3}=\\dfrac{\\sqrt{6}/8}{3\\sqrt{3}/8}=\\dfrac{\\sqrt{6}}{3\\sqrt{3}}=\\dfrac{\\sqrt{2}}{3}$.",
  },
  {n:19, subject:"다변수함수", unit:"접평면과 선형근사", concept:"접평면 방정식",
    difficulty:"easy",
    question:"점 $(1,4,0)$에서 곡면 $z=y\\ln x$의 접평면의 방정식은?",
    options:opts5("$z=4x-4$","$z=4x+y-8$","$z=4x+2y-12$","$z=4x-y$","$z=4x-2y+4$"),
    correct:"1",
    explanation:"$F=z-y\\ln x=0$. $\\nabla F=(-y/x,-\\ln x,1)|_{(1,4,0)}=(-4,0,1)$.\n접평면: $-4(x-1)+0(y-4)+(z-0)=0\\Rightarrow z=4x-4$.",
  },
  {n:20, subject:"다변수함수", unit:"편미분", concept:"합성함수 그래디언트",
    difficulty:"medium",
    question:"다음 두 함수로부터 얻은 합성 함수 $(f\\circ\\vec{G})(x,y)$에 대해 물매(그래디언트) $\\nabla(f\\circ\\vec{G})(0,0)$은?\n$$f(u,v)=u^2+3uv-v^2,\\,(u,v)=\\vec{G}(x,y)=(\\cos x+\\sin y,\\,-\\cos x+\\sin y)$$",
    options:opts5("$(0,-4)$","$(0,4)$","$(-4,0)$","$(4,0)$","$(4,-4)$"),
    correct:"2",
    explanation:"$(0,0)$: $u=1,\\,v=-1$.\n$f_u=2u+3v=-1,\\,f_v=3u-2v=5$.\n$u_x=-\\sin x|_0=0,\\,u_y=\\cos y|_0=1$.\n$v_x=\\sin x|_0=0,\\,v_y=\\cos y|_0=1$.\n$(f\\circ G)_x=f_u u_x+f_v v_x=0$. $(f\\circ G)_y=f_u u_y+f_v v_y=-1+5=4$.\n$\\nabla=(0,4)$.",
  },
  {n:21, subject:"다변수함수", unit:"이중적분", concept:"적분 순서 변경",
    difficulty:"medium",
    question:"이중 적분 $\\displaystyle\\int_0^2\\!\\!\\int_x^2\\cos(y^2)\\,dydx$의 값은?",
    options:opts5("$\\dfrac{1}{2}\\sin 4$","$\\sin 4$","$\\dfrac{3}{2}\\sin 4$","$2\\sin 4$","$\\dfrac{5}{2}\\sin 4$"),
    correct:"1",
    explanation:"순서 변경: $0\\le x\\le y\\le 2$. $\\!\\int_0^2\\!\\!\\int_0^y\\cos(y^2)\\,dx\\,dy=\\!\\int_0^2 y\\cos(y^2)\\,dy=\\dfrac{1}{2}\\sin(y^2)\\big|_0^2=\\dfrac{\\sin 4}{2}$.",
  },
  {n:22, subject:"다변수함수", unit:"극좌표와 극곡선", concept:"극곡선 영역 넓이",
    difficulty:"medium",
    question:"극 방정식 $r=4+3\\cos\\theta$로 주어진 곡선으로 둘러싸인 영역의 넓이는?",
    options:opts5("$\\dfrac{33\\pi}{2}$","$\\dfrac{35\\pi}{2}$","$\\dfrac{37\\pi}{2}$","$\\dfrac{39\\pi}{2}$","$\\dfrac{41\\pi}{2}$"),
    correct:"5",
    explanation:"$S=\\dfrac{1}{2}\\!\\int_0^{2\\pi}(4+3\\cos\\theta)^2\\,d\\theta=\\dfrac{1}{2}\\!\\int_0^{2\\pi}(16+24\\cos\\theta+9\\cos^2\\theta)\\,d\\theta$.\n$=\\dfrac{1}{2}\\!\\left[16\\cdot 2\\pi+0+9\\cdot\\pi\\right]=\\dfrac{1}{2}(32\\pi+9\\pi)=\\dfrac{41\\pi}{2}$.",
  },
  {n:23, subject:"다변수함수", unit:"삼중적분", concept:"구면좌표 삼중적분",
    difficulty:"medium",
    question:"영역 $Q$가 원점이 중심이고 반지름이 $1$과 $2$인 구면 사이의 영역일 때 삼중 적분 $\\displaystyle\\iiint_Q\\sqrt{x^2+y^2}\\,dxdydz$의 값은?",
    options:opts5("$\\dfrac{13\\pi}{4}$","$\\dfrac{15\\pi}{4}$","$\\dfrac{13\\pi^2}{4}$","$\\dfrac{15\\pi^2}{4}$","$\\dfrac{17\\pi^2}{4}$"),
    correct:"4",
    explanation:"구면좌표: $\\sqrt{x^2+y^2}=\\rho\\sin\\phi$. $\\!\\int_0^{2\\pi}\\!\\!\\int_0^{\\pi}\\!\\!\\int_1^2\\rho\\sin\\phi\\cdot\\rho^2\\sin\\phi\\,d\\rho\\,d\\phi\\,d\\theta$.\n$=2\\pi\\cdot\\!\\int_0^{\\pi}\\sin^2\\phi\\,d\\phi\\cdot\\!\\int_1^2\\rho^3\\,d\\rho=2\\pi\\cdot\\dfrac{\\pi}{2}\\cdot\\dfrac{15}{4}=\\dfrac{15\\pi^2}{4}$.",
  },
  {n:24, subject:"다변수함수", unit:"공간곡선", concept:"스칼라 선적분",
    difficulty:"medium",
    question:"곡선 $\\vec{x}(t)=(t,t^2)$ ($0\\le t\\le 1$)에 대해 선적분 $\\displaystyle\\int_C(x+\\sqrt{y})\\,ds$의 값은?",
    options:opts5("$\\dfrac{\\sqrt{5}-1}{6}$","$\\dfrac{2\\sqrt{5}-1}{6}$","$\\dfrac{3\\sqrt{5}-1}{6}$","$\\dfrac{4\\sqrt{5}-1}{6}$","$\\dfrac{5\\sqrt{5}-1}{6}$"),
    correct:"5",
    explanation:"$ds=\\sqrt{1+4t^2}\\,dt$. $x+\\sqrt{y}=t+t=2t$.\n$\\!\\int_0^1 2t\\sqrt{1+4t^2}\\,dt=\\dfrac{1}{4}\\!\\int_0^1 8t\\sqrt{1+4t^2}\\,dt=\\dfrac{1}{4}\\cdot\\dfrac{2}{3}[(1+4t^2)^{3/2}]_0^1=\\dfrac{5\\sqrt{5}-1}{6}$.",
  },
  {n:25, subject:"다변수함수", unit:"이중적분", concept:"그린 정리",
    difficulty:"medium",
    question:"닫힌 곡선 $C$는 좌표평면에서 $y=0,\\,y=\\sqrt{x},\\,x=1$의 그래프에 의해 둘러싸인 영역의 경계이고 반시계 방향을 갖는다. 이 때 선적분 $\\displaystyle\\oint_C-y^2\\,dx+2xy\\,dy$의 값은?",
    options:opts5("$\\dfrac{1}{3}$","$\\dfrac{2}{3}$","$1$","$\\dfrac{4}{3}$","$\\dfrac{5}{3}$"),
    correct:"3",
    explanation:"그린 정리: $\\!\\iint_D(2y-(-2y))\\,dA=\\!\\iint_D 4y\\,dA$.\n$\\!\\int_0^1\\!\\!\\int_0^{\\sqrt{x}}4y\\,dy\\,dx=\\!\\int_0^1 2x\\,dx=1$.",
  },
  {n:26, subject:"적분학", unit:"급수의 수렴/발산", concept:"멱급수 수렴구간",
    difficulty:"medium",
    question:"멱급수 $\\displaystyle\\sum_{n=0}^{\\infty}\\dfrac{(-1)^n}{n+1}(x-3)^n$의 수렴구간은?",
    options:opts5("$(1,5)$","$[1,5)$","$(2,4)$","$(2,4]$","$[2,4)$"),
    correct:"4",
    explanation:"수렴반경 $R=1$, 중심 $3$. $|x-3|<1$.\n$x=2$: $\\sum 1/(n+1)$ 발산.\n$x=4$: $\\sum(-1)^n/(n+1)$ 수렴.\n$(2,4]$.",
  },
  {n:27, subject:"미분학", unit:"도함수", concept:"$\\sec x$의 2계 도함수",
    difficulty:"easy",
    question:"$f(x)=\\sec x$일 때 $f''\\!\\left(\\dfrac{\\pi}{4}\\right)$의 값은?",
    options:opts5("$0$","$1$","$\\sqrt{2}$","$2\\sqrt{2}$","$3\\sqrt{2}$"),
    correct:"5",
    explanation:"$f'=\\sec x\\tan x$. $f''=\\sec x\\tan^2 x+\\sec^3 x$.\n$x=\\pi/4$: $\\sqrt{2}\\cdot 1+(\\sqrt{2})^3=\\sqrt{2}+2\\sqrt{2}=3\\sqrt{2}$.",
  },
  {n:28, subject:"적분학", unit:"급수의 수렴/발산", concept:"부분분수 망원급수",
    difficulty:"medium",
    question:"급수 $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{2}{n(n+1)(n+2)}$의 값은?",
    options:opts5("$\\dfrac{1}{4}$","$\\dfrac{1}{2}$","$\\dfrac{3}{4}$","$1$","$\\dfrac{5}{4}$"),
    correct:"2",
    explanation:"$\\dfrac{2}{n(n+1)(n+2)}=\\dfrac{1}{n(n+1)}-\\dfrac{1}{(n+1)(n+2)}$.\n망원급수: $\\!\\left(\\dfrac{1}{1\\cdot 2}-\\dfrac{1}{2\\cdot 3}\\right)+\\!\\left(\\dfrac{1}{2\\cdot 3}-\\dfrac{1}{3\\cdot 4}\\right)+\\cdots=\\dfrac{1}{2}$.",
  },
  {n:29, subject:"다변수함수", unit:"공간곡선", concept:"공간곡선 길이",
    difficulty:"easy",
    question:"곡선 $\\vec{x}(t)=(\\cos 2t,\\sin 2t,2t)$ ($0\\le t\\le 5$)의 길이는?",
    options:opts5("$10$","$10\\sqrt{2}$","$10\\sqrt{3}$","$20$","$10\\sqrt{5}$"),
    correct:"2",
    explanation:"$|\\vec{x}'|=\\sqrt{4\\sin^2 2t+4\\cos^2 2t+4}=\\sqrt{8}=2\\sqrt{2}$.\n$L=\\!\\int_0^5 2\\sqrt{2}\\,dt=10\\sqrt{2}$.",
  },
  {n:30, subject:"다변수함수", unit:"다변수 극값", concept:"타원체 내접 직육면체 (산술기하)",
    difficulty:"hard",
    question:"타원면 $x^2+2y^2+4z^2=9$ 안에 내접하는 직육면체의 최대 부피는?",
    options:opts5("$2\\sqrt{6}$","$4\\sqrt{6}$","$6\\sqrt{6}$","$8\\sqrt{6}$","$10\\sqrt{6}$"),
    correct:"3",
    explanation:"제1팔분공간 $(x,y,z)$, $V=8xyz$. 산술기하평균: $x^2+2y^2+4z^2\\ge 3\\sqrt[3]{8x^2y^2z^2}=3(8x^2y^2z^2)^{1/3}$.\n$9\\ge 3(8x^2y^2z^2)^{1/3}\\Rightarrow(xyz)^{2/3}\\le\\dfrac{3}{2}\\Rightarrow xyz\\le\\dfrac{3\\sqrt{3}}{2\\sqrt{2}}=\\dfrac{3\\sqrt{6}}{4}$.\n$V_{\\max}=8\\cdot\\dfrac{3\\sqrt{6}}{4}=6\\sqrt{6}$.",
  },
];

const TOTAL=PROBLEMS.length;
console.log(`총 ${TOTAL}문제 (객관식) 준비됨`);

const rows = PROBLEMS.map(p => {
  const id = `q-${YEAR}-${SCHOOL_EN}-${String(p.n).padStart(2,"0")}`;
  return {
    id, subject: p.subject, unit: p.unit, concept: p.concept, difficulty: p.difficulty,
    source_type: "imported", pool: "general", question: p.question, content_type: "latex",
    question_image: null, question_type: "multiple_choice",
    options: p.options, correct_option_id: p.correct,
    answer_text: null, explanation: p.explanation, explanation_content_type: "latex",
    explanation_image: null,
    tags: [YEAR, SCHOOL_KO, "past_exam", p.subject, p.unit, p.concept],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  };
});

const { data, error } = await sb.from("questions").upsert(rows, { onConflict: "id" }).select("id");
if (error) { console.error("업로드 실패:", error); process.exit(1); }
console.log(`업로드 완료: ${data.length}건`);
