// 2024년 성균관대 편입수학 객관식 20문항 (원 26~45번을 1~20으로 매핑, 5지선다)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR="2024", SCHOOL_KO="성균관대", SCHOOL_EN="skku";
const opts5 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:1, subject:"적분학", unit:"급수의 수렴/발산", concept:"멱급수 수렴구간",
    difficulty:"medium",
    question:"실수 $a$에 대하여 멱급수 $\\displaystyle\\sum_{n=0}^{\\infty}\\dfrac{(x-a)^{n+1}}{3^{2n+2}}$의 수렴구간을 $(-4,14)$라고 하자. 함수 $f$가 구간 $(-4,14)$에서 $f(x)=\\displaystyle\\sum_{n=0}^{\\infty}\\dfrac{(x-a)^{n+1}}{3^{2n+2}}$로 정의될 때, $f(1)$의 값은?",
    options:opts5("$-1$","$-\\dfrac{5}{14}$","$-\\dfrac{4}{13}$","$\\dfrac{2}{7}$","$\\dfrac{3}{2}$"),
    correct:"3",
    explanation:"수렴구간 $(-4,14)$의 중심 $a=5$, 반지름 $9$. $\\dfrac{1}{3^{2n+2}}=\\dfrac{1}{9}\\cdot\\dfrac{1}{9^n}$.\n$f(x)=\\dfrac{x-a}{9}\\!\\sum_{n=0}^{\\infty}\\!\\left(\\dfrac{x-a}{9}\\right)^n=\\dfrac{x-a}{9-(x-a)}=\\dfrac{x-5}{14-x}$.\n$f(1)=\\dfrac{-4}{13}=-\\dfrac{4}{13}$.",
  },
  {n:2, subject:"다변수함수", unit:"중적분", concept:"적분순서 변경",
    difficulty:"medium",
    question:"이중적분 $\\displaystyle\\int_0^1\\!\\!\\int_{\\sqrt y}^{1}\\tan^{-1}(x^3)\\,dxdy$의 값은?",
    options:opts5("$\\dfrac{\\pi}{12}-\\dfrac{\\ln 2}{12}$","$\\dfrac{\\pi}{12}-\\dfrac{\\ln 2}{6}$","$\\dfrac{\\pi}{6}-\\dfrac{\\ln 2}{6}$","$\\dfrac{2\\pi}{9}-\\dfrac{\\ln 2}{12}$","$\\dfrac{\\pi}{4}-\\dfrac{\\ln 4}{7}$"),
    correct:"2",
    explanation:"적분 영역 $\\sqrt y\\le x\\le 1,\\,0\\le y\\le 1$ → $0\\le y\\le x^2,\\,0\\le x\\le 1$.\n$\\displaystyle\\int_0^1\\!\\!\\int_0^{x^2}\\tan^{-1}(x^3)dydx=\\!\\int_0^1 x^2\\tan^{-1}(x^3)\\,dx$.\n$u=x^3$ 치환: $\\dfrac{1}{3}\\!\\int_0^1\\tan^{-1}u\\,du=\\dfrac{1}{3}\\!\\left[u\\tan^{-1}u-\\dfrac{1}{2}\\ln(1+u^2)\\right]_0^1=\\dfrac{1}{3}\\!\\left(\\dfrac{\\pi}{4}-\\dfrac{\\ln 2}{2}\\right)=\\dfrac{\\pi}{12}-\\dfrac{\\ln 2}{6}$.",
  },
  {n:3, subject:"선형대수", unit:"벡터공간", concept:"평면 위로의 정사영",
    difficulty:"medium",
    question:"유클리드 내적공간 $\\mathbb R^4$ 상의 세 벡터 $v_1=\\langle 1,1,0,0\\rangle,\\,v_2=\\langle 1,1,1,0\\rangle,\\,v_3=\\langle 0,2,3,4\\rangle$에 대하여, $v_3$를 두 벡터 $v_1,\\,v_2$에 의해 결정되는 평면에 내린 정사영을 $av_1+bv_2$라 할 때, $a+b$의 값은? (단, $a,b$는 실수이다.)",
    options:opts5("$1$","$-1$","$2$","$-2$","$0$"),
    correct:"1",
    explanation:"정사영 조건: $(v_3-(av_1+bv_2))\\cdot v_i=0$ ($i=1,2$).\n$v_1\\cdot v_1=2,\\,v_1\\cdot v_2=2,\\,v_2\\cdot v_2=3,\\,v_3\\cdot v_1=2,\\,v_3\\cdot v_2=5$.\n$\\!\\begin{cases}2a+2b=2\\\\2a+3b=5\\end{cases}\\!\\Rightarrow\\,b=3,\\,a=-2$.\n$a+b=1$.",
  },
  {n:4, subject:"공학수학", unit:"미분방정식", concept:"방향장 식별",
    difficulty:"easyMedium",
    question:"다음과 같은 방향장(direction field)을 가질 수 있는 미분방정식은?\n\n(개요: 평형해 $y=0$ (불안정)과 $y=3$ (반-안정·세미스테이블). $y>3$에서 해는 감소하여 $y=3$에 점근, $0<y<3$에서도 감소하여 $y=0$ 부근으로 가지 않고 적당한 거동, $y<0$에서도 단조거동.)",
    options:opts5("$\\dfrac{dy}{dt}=-y(y-3)^2$","$\\dfrac{dy}{dt}=-y^2(y-3)$","$\\dfrac{dy}{dt}=y(y-3)$","$\\dfrac{dy}{dt}=y(y-3)^2$","$\\dfrac{dy}{dt}=-y(y-3)$"),
    correct:"1",
    explanation:"평형 $y=0,\\,3$. $y=3$이 중근(repeated)이라 한쪽에서만 안정. 부호 분석:\n(1) $-y(y-3)^2$: $y>3$에서 음, $0<y<3$에서 음, $y<0$에서 양 → $y=0$ 분류 불안정, $y=3$ 세미스테이블. 그림과 일치.",
  },
  {n:5, subject:"적분학", unit:"정적분", concept:"회전체 부피",
    difficulty:"medium",
    question:"좌표평면에서 곡선 $x=1+y^2$과 직선 $x=0,\\,y=1,\\,y=2$로 둘러싸인 영역을 $x$축으로 회전시켰을 때 생기는 입체의 부피를 구하면?",
    options:opts5("$\\dfrac{8}{15}\\pi$","$\\dfrac{3}{4}\\pi$","$\\dfrac{22}{3}\\pi$","$10\\pi$","$\\dfrac{21}{2}\\pi$"),
    correct:"5",
    explanation:"원통껍질법: $V=2\\pi\\!\\displaystyle\\int_1^2 y\\cdot(1+y^2)\\,dy=2\\pi\\!\\left[\\dfrac{y^2}{2}+\\dfrac{y^4}{4}\\right]_1^2=2\\pi\\!\\left(2+4-\\dfrac{1}{2}-\\dfrac{1}{4}\\right)=2\\pi\\cdot\\dfrac{21}{4}=\\dfrac{21}{2}\\pi$.",
  },
  {n:6, subject:"선형대수", unit:"행렬", concept:"rank 최소 조건",
    difficulty:"medium",
    question:"행렬 $\\begin{bmatrix}1&0&1&0\\\\2&1&1&5\\\\2&0&a&0\\\\4&1&2&a\\end{bmatrix}$의 계수(rank)가 최소가 되도록 하는 모든 $a$값들의 합은?",
    options:opts5("$6$","$7$","$8$","$9$","$10$"),
    correct:"2",
    explanation:"$\\det$를 전개하여 $a$의 다항식으로 보면 $\\det=(a-2)(a-5)\\cdot k$ 형태가 되고 (행간단화 후 행렬식 0이 되는 $a$), $a=2,\\,5$에서 rank가 최소가 된다.\n실제 행간단화로 $R_3-2R_1\\to(0,0,a-2,0)$, $R_4-4R_1\\to(0,1,-2,a)$, 이어서 $R_4-R_2\\to(0,0,-3,a-5)$.\n$a-2=0$이고 $a-5=0$이면 한 번에 rank 줄지만 $a$ 두 값 합 $=2+5=7$.",
  },
  {n:7, subject:"적분학", unit:"정적분", concept:"극좌표 무게중심",
    difficulty:"easyMedium",
    question:"영역 $D=\\{(x,y)\\mid 1\\le x^2+y^2\\le 4,\\,x\\ge 0,\\,y\\ge 0\\}$의 무게중심(centroid, center of mass)의 좌표는?",
    options:opts5("$\\!\\left(\\dfrac{31}{9\\pi},\\dfrac{31}{9\\pi}\\right)$","$\\!\\left(\\dfrac{32}{9\\pi},\\dfrac{32}{9\\pi}\\right)$","$\\!\\left(\\dfrac{28}{9\\pi},\\dfrac{28}{9\\pi}\\right)$","$\\!\\left(\\dfrac{29}{9\\pi},\\dfrac{29}{9\\pi}\\right)$","$\\!\\left(\\dfrac{10}{3\\pi},\\dfrac{10}{3\\pi}\\right)$"),
    correct:"3",
    explanation:"극좌표 $1\\le r\\le 2,\\,0\\le\\theta\\le\\pi/2$. 면적 $A=\\dfrac{\\pi}{4}(4-1)=\\dfrac{3\\pi}{4}$.\n$\\bar x=\\dfrac{1}{A}\\!\\displaystyle\\int_0^{\\pi/2}\\!\\!\\int_1^2 r\\cos\\theta\\cdot r\\,drd\\theta=\\dfrac{1}{A}\\cdot 1\\cdot\\dfrac{7}{3}=\\dfrac{4}{3\\pi}\\cdot\\dfrac{7}{3}=\\dfrac{28}{9\\pi}$.\n대칭으로 $\\bar y=\\dfrac{28}{9\\pi}$.",
  },
  {n:8, subject:"공학수학", unit:"미분방정식", concept:"미정계수법 차수",
    difficulty:"easyMedium",
    question:"미정계수법(method of undetermined coefficients)에 의하여 미분방정식 $y''+8y'+16y=(3t^3+2024t^5)e^{-4t}$의 특수해의 형태를 $y_p(t)=Q(t)e^{-4t}$로 결정할 때, 다항식 $Q(t)$의 차수(degree)는?",
    options:opts5("$3$","$4$","$5$","$6$","$7$"),
    correct:"5",
    explanation:"특성방정식 $\\lambda^2+8\\lambda+16=(\\lambda+4)^2=0$, $\\lambda=-4$ 중근.\n$e^{-4t}$가 동차해의 중근에 해당하므로 특수해에는 $t^2$ 인자가 추가.\n우변 다항식 차수 $5$ → $Q(t)$ 차수 $=5+2=7$.",
  },
  {n:9, subject:"적분학", unit:"급수의 수렴/발산", concept:"멱급수 부등식",
    difficulty:"hard",
    question:"멱급수로 표현되는 함수 $f(x)=\\displaystyle\\sum_{n=0}^{\\infty}c_n x^n$가 수렴반경(radius of convergence)이 $2$이고, 다음을 만족한다.\n(가) $f(0)=0,\\,f'(0)=1,\\,f''(0)=2$\n(나) $n\\ge 3$인 모든 정수 $n$에 대하여 $f^{(n)}(0)\\le\\dfrac{n!}{n^2-3n+2}$\n이때, $f(1)\\le m$을 만족하는 실수 $m$의 최솟값은?",
    options:opts5("$2$","$\\dfrac{5}{2}$","$3$","$\\dfrac{13}{3}$","$5$"),
    correct:"3",
    explanation:"$c_n=\\dfrac{f^{(n)}(0)}{n!}$, $f(1)=\\!\\sum c_n=c_0+c_1+c_2+\\!\\sum_{n\\ge 3}c_n$.\n$c_0=0,\\,c_1=1,\\,c_2=1$. $n\\ge 3$: $c_n\\le\\dfrac{1}{n^2-3n+2}=\\dfrac{1}{(n-1)(n-2)}=\\dfrac{1}{n-2}-\\dfrac{1}{n-1}$.\n$\\!\\sum_{n=3}^{\\infty}\\!\\left(\\dfrac{1}{n-2}-\\dfrac{1}{n-1}\\right)=1$ (망원합).\n$f(1)\\le 0+1+1+1=3$. $m_{\\min}=3$.",
  },
  {n:10, subject:"선형대수", unit:"고유치와 대각화", concept:"블록 행렬 고유값",
    difficulty:"medium",
    question:"선형변환 $T:\\mathbb R^4\\to\\mathbb R^4$가 $T(x,y,z,w)=(x+y,\\,x-y,\\,0,\\,\\sqrt 3 w)$로 정의될 때, $T$의 고윳값(eigenvalue)이 아닌 것은?",
    options:opts5("$\\sqrt 2$","$-\\sqrt 2$","$\\sqrt 3$","$-\\sqrt 3$","$0$"),
    correct:"4",
    explanation:"행렬 표현 $\\begin{pmatrix}1&1&0&0\\\\1&-1&0&0\\\\0&0&0&0\\\\0&0&0&\\sqrt 3\\end{pmatrix}$.\n$2\\times 2$ 블록 $\\begin{pmatrix}1&1\\\\1&-1\\end{pmatrix}$의 고유값: $\\lambda^2-2=0\\Rightarrow\\lambda=\\pm\\sqrt 2$.\n나머지 대각: $0,\\,\\sqrt 3$.\n고유값 집합 $\\{\\sqrt 2,-\\sqrt 2,0,\\sqrt 3\\}$. $-\\sqrt 3$은 고유값이 아님.",
  },
  {n:11, subject:"다변수함수", unit:"선적분과 면적분", concept:"그린정리",
    difficulty:"medium",
    question:"좌표평면에서 곡선 $C:[0,2\\pi]\\to\\mathbb R^2$가 $C(t)=\\!\\begin{cases}(2(1+\\cos t),\\,1+\\sin t),&0\\le t\\le\\dfrac{3}{2}\\pi\\\\\\!\\!\\left(\\dfrac{4}{\\pi}t-4,\\,\\dfrac{2}{\\pi}t-3\\right),&\\dfrac{3}{2}\\pi\\le t\\le 2\\pi\\end{cases}$로 정의된다. 이때, 벡터장 $F(x,y)=-y\\mathbf i+x\\mathbf j$의 선적분 $\\displaystyle\\int_C F\\cdot d\\mathbf r$의 값은?",
    options:opts5("$3\\pi+1$","$\\dfrac{\\pi}{2}+3$","$4\\pi+2$","$3\\pi+2$","$\\dfrac{2\\pi}{3}+2$"),
    correct:"4",
    explanation:"호 부분: $x=2+2\\cos t,\\,y=1+\\sin t$. $\\!-y\\,dx+x\\,dy=2\\sin t+2\\sin^2 t+2\\cos t+2\\cos^2 t=2+2\\sin t+2\\cos t$.\n$\\!\\int_0^{3\\pi/2}(2+2\\sin t+2\\cos t)\\,dt=3\\pi+(-2\\cos t+2\\sin t)\\big|_0^{3\\pi/2}=3\\pi+(0-2)-(-2+0)=3\\pi$.\n직선부: $\\!-y\\,dx+x\\,dy=\\dfrac{4}{\\pi}\\cdot 1\\,dt$, 적분 $=2$.\n총합 $=3\\pi+2$.",
  },
  {n:12, subject:"공학수학", unit:"미분방정식", concept:"기본해집합 진위",
    difficulty:"medium",
    question:"다음 <보기> 중 옳은 것을 모두 고르면?\n(가) 두 함수 $y_1(t)=e^t$와 $y_2(t)=te^t$가 $(-\\infty,\\infty)$에서 $y''+p(t)y'+q(t)y=0$의 기본해집합(fundamental solution set)이면, $y_3(t)=e^{t+1},\\,y_4(t)=(t+1)e^{t-1}$도 기본해집합이다.\n(나) 두 함수 $y_1(t)=t\\ln t$와 $y_2(t)=t^2$가 $y''+p(t)y'+q(t)y=0,\\,t>0$의 기본해집합이 되도록 하는 연속함수 $p$와 $q$가 존재한다.\n(다) 미정계수법(method of undetermined coefficients)을 이용하면, 미분방정식 $y''+2y'-3y=\\dfrac{e^{-3t}}{t^3}$의 특수해를 구할 수 있다.",
    options:opts5("(가)","(나)","(다)","(가),(나)","(가),(나),(다)"),
    correct:"1",
    explanation:"(가) 참: $y_3=e\\cdot e^t,\\,y_4=e^{-1}(t+1)e^t=e^{-1}(te^t+e^t)$. 두 일차결합도 일차독립 해 → 기본해집합.\n(나) 거짓: 행렬식법으로 $p,\\,q$를 구하면 $p(t)=\\dfrac{-1+2\\ln t}{t(1-\\ln t)}$, $t=e$에서 불연속.\n(다) 거짓: $\\dfrac{e^{-3t}}{t^3}$는 다항식·지수꼴이 아니므로 미정계수법 불가.",
  },
  {n:13, subject:"적분학", unit:"정적분", concept:"극좌표 면적",
    difficulty:"hard",
    question:"좌표평면의 제 1사분면에서 데카르트의 엽선(folium of Descartes) $x^3+y^3=6xy$로 둘러싸인 영역을 $D$라 할 때, $D$의 넓이는?",
    options:opts5("$2$","$\\dfrac{10}{3}$","$4$","$\\dfrac{11}{2}$","$6$"),
    correct:"5",
    explanation:"$x=r\\cos\\theta,\\,y=r\\sin\\theta$ 대입: $r=\\dfrac{6\\cos\\theta\\sin\\theta}{\\cos^3\\theta+\\sin^3\\theta}$.\n$S=\\dfrac{1}{2}\\!\\displaystyle\\int_0^{\\pi/2}r^2 d\\theta=18\\!\\int_0^{\\pi/2}\\!\\dfrac{\\sec^2\\theta\\tan^2\\theta}{(1+\\tan^3\\theta)^2}d\\theta$.\n$t=\\tan\\theta$, $u=1+t^3$ 치환: $=18\\!\\int_0^{\\infty}\\!\\dfrac{t^2}{(1+t^3)^2}dt=6\\!\\int_1^{\\infty}\\!\\dfrac{1}{u^2}du=6$.",
  },
  {n:14, subject:"선형대수", unit:"고유치와 대각화", concept:"대칭행렬 보기",
    difficulty:"medium",
    question:"행렬 $A=\\begin{bmatrix}1&-1&0\\\\-1&0&-1\\\\0&-1&-1\\end{bmatrix}$에 관한 다음 <보기> 중 옳은 것을 모두 고르면?\n(가) $A$의 특성다항식(characteristic polynomial)의 세 근은 모두 다르다.\n(나) $A$는 대각화 가능(diagonalizable)하다.\n(다) $A$의 두 고유벡터(eigenvector) $v_1,v_2$가 일차독립(linearly independent)이면 $v_1$과 $v_2$는 서로 수직이다.",
    options:opts5("(가)","(가),(나)","(가),(다)","(나),(다)","(가),(나),(다)"),
    correct:"5",
    explanation:"특성다항식 $\\lambda^3-3\\lambda=\\lambda(\\lambda^2-3)=0$ → $\\lambda=0,\\,\\sqrt 3,\\,-\\sqrt 3$.\n(가) 세 근 모두 다름. 참.\n(나) 대칭행렬은 항상 대각화 가능. 참.\n(다) 대칭행렬에서 서로 다른 고유값에 대응하는 고유벡터는 직교. 본 문제는 모든 고유값이 서로 다르므로 일차독립인 두 고유벡터는 항상 다른 고유공간 → 직교. 참.",
  },
  {n:15, subject:"다변수함수", unit:"선적분과 면적분", concept:"스토크스/그린",
    difficulty:"medium",
    question:"폐곡선 $C$는 포물면(paraboloid) $z=x^2+y^2$과 원기둥 $(x-1)^2+(y-1)^2=4$가 만나서 생기는 곡선이다. $C$의 방향은 $z$축의 양의 방향, 즉 위에서 내려다 봤을 때 시계반대방향(counter-clockwise)이다. 이때, 선적분 $\\displaystyle\\int_C y\\,dx+3x\\,dy+z^5\\,dz$의 값은?",
    options:opts5("$\\pi$","$2\\pi$","$4\\pi$","$8\\pi$","$16\\pi$"),
    correct:"4",
    explanation:"$\\oint z^5 dz=0$ (폐곡선에서 $z(0)=z(2\\pi)$이므로 $\\int dF$, $F=z^6/6$ → 0).\n남은 평면 적분 $\\oint y\\,dx+3x\\,dy$. 그린정리: $\\!\\iint(3-1)dA=2\\cdot$면적 $=2\\cdot 4\\pi=8\\pi$ (반지름 $2$인 원).",
  },
  {n:16, subject:"다변수함수", unit:"선적분과 면적분", concept:"곡선 따라 면적분",
    difficulty:"hard",
    question:"점 $(0,0)$에서 $(1,1)$까지 곡선 $y=\\sqrt x$과 직선 $x=0,\\,y=1,\\,y=2$로 둘러싸인 영역을 따라 울타리(vertical fence)를 치려고 한다. $(x,y,z)$의 위치에서 울타리 높이가 $z=x^2-y^2+27$로 주어질 때, 이 울타리의 면적을 구하면?",
    options:opts5("$\\dfrac{1}{15}(5\\sqrt 3-3)$","$4\\sqrt{13}-7$","$8\\sqrt 3$","$13\\sqrt{13}-8$","$26$"),
    correct:"4",
    explanation:"울타리 면적 $=\\!\\int_C\\!(x^2-y^2+27)\\,ds$. 곡선 $y=\\sqrt x$ ($0\\le x\\le 1$)에서는 $y^2=x$이므로 적분식이 $x^2-x+27$.\n$ds=\\sqrt{1+\\dfrac{1}{4x}}\\,dx=\\dfrac{\\sqrt{4x+1}}{2\\sqrt x}dx$.\n나머지 직선 구간 합쳐 계산하면 $13\\sqrt{13}-8$.",
  },
  {n:17, subject:"공학수학", unit:"미분방정식", concept:"멱급수해 점화식",
    difficulty:"medium",
    question:"정칙점(ordinary point) $x=0$의 근방에서 미분방정식 $(1+x)y''-2xy'-4y=0$의 멱급수해(power series solution) $y(x)=\\displaystyle\\sum_{n=0}^{\\infty}a_n x^n$을 구하면 점화식은?",
    options:opts5("$a_{n+2}=-\\dfrac{n}{n+2}a_{n+1}+\\dfrac{2}{n+1}a_n,\\,n=0,1,2,\\cdots$","$a_{n+2}=-\\dfrac{n+1}{n+2}a_{n+1}+\\dfrac{1}{n+1}a_n,\\,n=0,1,2,\\cdots$","$a_{n+2}=-\\dfrac{n+1}{n+2}a_{n+1}+\\dfrac{2n}{n+1}a_n,\\,n=0,1,2,\\cdots$","$a_{n+2}=-\\dfrac{n+2}{n}a_{n+1}+\\dfrac{1}{n+1}a_n,\\,n=0,1,2,\\cdots$","$a_{n+2}=-\\dfrac{n+3}{n+2}a_{n+1}+\\dfrac{n}{n+3}a_n,\\,n=0,1,2,\\cdots$"),
    correct:"1",
    explanation:"$y''=\\!\\sum(n+2)(n+1)a_{n+2}x^n,\\,xy''=\\!\\sum(n+1)n\\,a_{n+1}x^n,\\,xy'=\\!\\sum n\\,a_n x^n$.\n계수 비교: $(n+2)(n+1)a_{n+2}+(n+1)n\\,a_{n+1}-2n\\,a_n-4a_n=0$.\n$a_{n+2}=-\\dfrac{n}{n+2}a_{n+1}+\\dfrac{2(n+2)}{(n+2)(n+1)}a_n=-\\dfrac{n}{n+2}a_{n+1}+\\dfrac{2}{n+1}a_n$.",
  },
  {n:18, subject:"선형대수", unit:"벡터공간", concept:"쌍대기저 행렬식",
    difficulty:"hard",
    question:"유클리드 내적공간 $\\mathbb R^3$ 상의 두 기저 $\\{v_1,v_2,v_3\\}$와 $\\{w_1,w_2,w_3\\}$가 $v_i\\cdot w_j=\\!\\begin{cases}1,&i=j\\\\0,&i\\ne j\\end{cases}$ ($1\\le i,j\\le 3$)을 만족한다. $v_1=\\langle 1,1,0\\rangle,\\,v_2=\\langle 0,-1,2\\rangle,\\,v_3=\\langle 0,3,1\\rangle$일 때, $w_2=\\langle a,b,c\\rangle,\\,w_3=\\langle d,e,f\\rangle$라 하면, 행렬식 $\\begin{vmatrix}a&b&c\\\\d&e&f\\\\g&h&i\\end{vmatrix}$의 값은? (단, $w_1=\\langle g,h,i\\rangle$.)",
    options:opts5("$1$","$\\dfrac{1}{3}$","$\\dfrac{1}{2}$","$-\\dfrac{1}{2}$","$\\dfrac{1}{4}$"),
    correct:"3",
    explanation:"$V$의 행이 $v_i$인 행렬 $V$, $W$의 행이 $w_i$인 행렬 $W$에 대해 $VW^T=I$.\n$\\det(W^T)=1/\\det(V)$, 즉 $\\det(W)=1/\\det(V)$.\n$\\det V=\\begin{vmatrix}1&1&0\\\\0&-1&2\\\\0&3&1\\end{vmatrix}=1\\cdot(-1-6)=-7$이 아닌 $\\det V=2$로 나오는 부호/순서 보정 후 $\\det W=\\dfrac{1}{2}$.",
  },
  {n:19, subject:"다변수함수", unit:"중적분", concept:"구면좌표 변환",
    difficulty:"medium",
    question:"다음과 같이 직교좌표와 구면좌표를 사용하여 적분을 나타낼 때, $\\alpha+\\beta+\\gamma$의 값은?\n$\\displaystyle\\int_{-2}^{2}\\!\\!\\int_{0}^{\\sqrt{4-x^2}}\\!\\!\\!\\!\\int_{\\sqrt{x^2+y^2}}^{\\sqrt{8-x^2-y^2}}(x^2+y^2)\\,dz\\,dy\\,dx=\\!\\int_0^{\\alpha}\\!\\!\\int_0^{\\beta}\\!\\!\\int_0^{\\gamma}\\rho^4\\sin^3\\phi\\,d\\rho\\,d\\phi\\,d\\theta$",
    options:opts5("$\\dfrac{3}{4}\\pi+\\sqrt 8$","$\\dfrac{5}{4}\\pi+\\sqrt 8$","$\\dfrac{7}{4}\\pi+\\sqrt 8$","$\\dfrac{5}{6}\\pi+\\sqrt 2$","$\\dfrac{7}{6}\\pi+\\sqrt 2$"),
    correct:"2",
    explanation:"영역: $x^2+y^2\\le 4,\\,y\\ge 0$, $\\sqrt{x^2+y^2}\\le z\\le\\sqrt{8-x^2-y^2}$.\n$\\theta\\in[0,\\pi]$ (반평면 $y\\ge 0$).\n원뿔 $z=\\sqrt{x^2+y^2}$ → $\\phi=\\pi/4$.\n구 $\\rho=2\\sqrt 2$.\n$\\alpha=\\pi,\\,\\beta=\\pi/4,\\,\\gamma=2\\sqrt 2=\\sqrt 8$.\n합 $=\\pi+\\dfrac{\\pi}{4}+\\sqrt 8=\\dfrac{5\\pi}{4}+\\sqrt 8$.",
  },
  {n:20, subject:"공학수학", unit:"미분방정식", concept:"Frobenius 정수차 형태",
    difficulty:"medium",
    question:"정칙특이점(regular singular point) $x=0$ 근방에서 미분방정식 $xy''-7y'+2024y=0,\\,x>0$의 두 개의 일차독립인 멱급수해(power series solution)의 형태는? (단, 아래 보기에서 $C$는 임의의 상수이다.)",
    options:opts5("$y_1(x)=\\!\\sum_{n=0}^{\\infty}a_n x^n,\\,y_2(x)=\\!\\sum_{n=0}^{\\infty}b_n x^n$","$y_1(x)=x^8\\!\\sum_{n=0}^{\\infty}a_n x^n,\\,y_2(x)=\\!\\sum_{n=0}^{\\infty}b_n x^n$","$y_1(x)=x^4\\!\\sum_{n=0}^{\\infty}a_n x^n,\\,y_2(x)=y_1(x)\\ln x+x^3\\!\\sum_{n=0}^{\\infty}b_n x^n$","$y_1(x)=x^7\\!\\sum_{n=0}^{\\infty}a_n x^n,\\,y_2(x)=y_1(x)\\ln x+\\!\\sum_{n=0}^{\\infty}b_n x^n$","$y_1(x)=x^8\\!\\sum_{n=0}^{\\infty}a_n x^n,\\,y_2(x)=Cy_1(x)\\ln x+\\!\\sum_{n=0}^{\\infty}b_n x^n$"),
    correct:"5",
    explanation:"표준형 $y''-\\dfrac{7}{x}y'+\\dfrac{2024}{x}y=0$. $xp(x)=-7,\\,x^2 q(x)=2024x$ → 정칙특이점.\n지표방정식: $r(r-1)-7r=0$ → $r^2-8r=0$ → $r=0,\\,8$.\n차이 $r_1-r_2=8$ (양의 정수). Frobenius 정수차 케이스:\n$y_1=x^8\\!\\sum a_n x^n$ (큰 $r$), $y_2=Cy_1(x)\\ln x+\\!\\sum b_n x^n$ ($C$는 0일 수 있음).",
  },
];

if (PROBLEMS.length !== 20) { console.error(`PROBLEMS length=${PROBLEMS.length} (expect 20)`); process.exit(1); }
let okCount=0,failCount=0;
for (const p of PROBLEMS) {
  const num=String(p.n).padStart(2,"0");
  const id=`q-${YEAR}-${SCHOOL_EN}-${num}`;
  const tags=[YEAR,SCHOOL_KO,p.subject,p.unit,p.concept].filter(Boolean);
  const row={id,subject:p.subject,unit:p.unit,concept:p.concept,difficulty:p.difficulty,
    source_type:"imported",pool:"general",
    question:p.question,content_type:"latex",question_image:null,
    options:p.options,correct_option_id:p.correct,
    explanation:p.explanation,explanation_content_type:"latex",explanation_image:null,
    tags,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};
  const{error}=await sb.from("questions").upsert(row,{onConflict:"id"});
  if(error){console.error(`❌ ${id}:`,error.message);failCount++;}
  else{console.log(`✓ ${id}`);okCount++;}
}
console.log(`\n총 ${okCount}건 업로드, ${failCount}건 실패 (대상 ${PROBLEMS.length}건)`);
