// 2022년 중앙대(수학과) 편입수학 객관식 30문항 (4지선다)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR="2022", SCHOOL_KO="중앙대", SCHOOL_EN="cau";
const opts4 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:1, subject:"적분학", unit:"급수의 수렴/발산", concept:"sec 멱급수 계수",
    difficulty:"medium",
    question:"$-1<x<1$에서 $\\sec x=\\!\\displaystyle\\sum_{n=0}^{\\infty}a_n x^n$일 때, $a_0+a_1+a_2+a_3+a_4$의 값은?",
    options:opts4("$-\\dfrac{43}{24}$","$-\\dfrac{41}{24}$","$\\dfrac{41}{24}$","$\\dfrac{43}{24}$"),
    correct:"3",
    explanation:"$\\sec x=1+\\dfrac{x^2}{2}+\\dfrac{5x^4}{24}+\\cdots$ (오일러 수). $a_0=1,a_1=0,a_2=\\dfrac{1}{2},a_3=0,a_4=\\dfrac{5}{24}$.\n합 $=1+\\dfrac{1}{2}+\\dfrac{5}{24}=\\dfrac{24+12+5}{24}=\\dfrac{41}{24}$.",
  },
  {n:2, subject:"적분학", unit:"정적분", concept:"astroid 길이",
    difficulty:"easyMedium",
    question:"곡선 $x^{2/3}+y^{2/3}=1,\\,x\\ge 0,\\,y\\ge 0$의 길이는?",
    options:opts4("$\\dfrac{2}{3}$","$\\dfrac{3}{2}$","$\\dfrac{4}{3}$","$\\dfrac{7}{6}$"),
    correct:"2",
    explanation:"$x=\\cos^3 t,\\,y=\\sin^3 t$ 매개화. $ds=3\\sin t\\cos t\\,dt$.\n길이 $=\\!\\int_0^{\\pi/2}3\\sin t\\cos t\\,dt=\\dfrac{3}{2}\\!\\int_0^{\\pi/2}\\sin 2t\\,dt=\\dfrac{3}{2}$.",
  },
  {n:3, subject:"미분학", unit:"도함수와 그래프", concept:"이차형식 변역",
    difficulty:"medium",
    question:"방정식 $5x^2+2xy+5y^2=12$를 만족하는 두 실수 $x,y$에 대하여 $y$의 최댓값과 최솟값의 차는?",
    options:opts4("$\\sqrt 5$","$\\sqrt 6$","$\\sqrt 8$","$\\sqrt{10}$"),
    correct:"4",
    explanation:"$x$에 관한 이차식 $5x^2+2yx+(5y^2-12)=0$의 판별식 $\\ge 0$.\n$(2y)^2-20(5y^2-12)\\ge 0\\Rightarrow 4y^2-100y^2+240\\ge 0\\Rightarrow y^2\\le\\dfrac{5}{2}$.\n차 $=2\\sqrt{5/2}=\\sqrt{10}$.",
  },
  {n:4, subject:"선형대수", unit:"행렬", concept:"역행렬 대각합",
    difficulty:"easyMedium",
    question:"행렬 $\\begin{pmatrix}0&1&1\\\\1&0&1\\\\1&1&0\\end{pmatrix}$의 역행렬의 대각합은?",
    options:opts4("$-\\dfrac{3}{2}$","$\\dfrac{5}{2}$","$-\\dfrac{7}{2}$","$\\dfrac{9}{2}$"),
    correct:"1",
    explanation:"$\\det A=2$. 코팩터 대각: $M_{11}=-1,\\,M_{22}=-1,\\,M_{33}=-1$.\n$\\mathrm{tr}(A^{-1})=\\dfrac{M_{11}+M_{22}+M_{33}}{\\det A}=\\dfrac{-3}{2}$.",
  },
  {n:5, subject:"적분학", unit:"정적분", concept:"파푸스 회전 부피",
    difficulty:"medium",
    question:"반원판 $x^2+\\!\\left(y-\\dfrac{16}{3\\pi}\\right)^{\\!2}\\le 1,\\,y\\ge\\dfrac{16}{3\\pi}$을 $x$축 중심으로 회전하여 얻은 회전체의 부피는?",
    options:opts4("$\\dfrac{25\\pi}{3}$","$\\dfrac{11\\sqrt 3\\,\\pi}{3}$","$\\dfrac{5\\sqrt 3\\,\\pi}{3}$","$\\dfrac{20\\pi}{3}$"),
    correct:"4",
    explanation:"반원판 무게중심 $\\bar y=\\dfrac{16}{3\\pi}+\\dfrac{4}{3\\pi}=\\dfrac{20}{3\\pi}$, 면적 $A=\\dfrac{\\pi}{2}$.\n파푸스: $V=2\\pi\\bar y A=2\\pi\\cdot\\dfrac{20}{3\\pi}\\cdot\\dfrac{\\pi}{2}=\\dfrac{20\\pi}{3}$.",
  },
  {n:6, subject:"적분학", unit:"급수의 수렴/발산", concept:"수렴 보기 4개",
    difficulty:"medium",
    question:"다음 <보기>의 급수 중에서 수렴하는 것의 개수는?\n(가) $\\!\\displaystyle\\sum_{n=3}^{\\infty}\\ln\\!\\left(1+\\dfrac{1}{n^2-1}\\right)$\n(나) $\\!\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{1}{n\\!\\left(1+\\dfrac{1}{\\sqrt 2}+\\cdots+\\dfrac{1}{\\sqrt n}\\right)}$\n(다) $\\!\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{1}{\\sqrt n}\\ln\\!\\left(\\dfrac{n+1}{n}\\right)$\n(라) $\\!\\displaystyle\\sum_{n=1}^{\\infty}\\sin\\!\\left(\\dfrac{1}{n}\\right)$",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"3",
    explanation:"(가) $\\sim 1/(n^2-1)$ 수렴. (나) 분모 $\\sim 2n^{3/2}$ → $1/n^{3/2}$ 수렴. (다) $\\sim 1/n^{3/2}$ 수렴. (라) $\\sim 1/n$ 발산.\n수렴 $3$개.",
  },
  {n:7, subject:"미분학", unit:"도함수", concept:"이항급수 6계 미분",
    difficulty:"medium",
    question:"함수 $f(x)=\\sqrt[3]{1+x^2}\\,(-1<x<1)$에 대하여 $f^{(6)}(0)$의 값은?",
    options:opts4("$\\dfrac{5}{81}$","$\\dfrac{10}{27}$","$\\dfrac{400}{9}$","$\\dfrac{2000}{3}$"),
    correct:"3",
    explanation:"$(1+u)^{1/3}=\\!\\sum\\binom{1/3}{k}u^k$, $u=x^2$. $x^6$ 계수 $=\\binom{1/3}{3}=\\dfrac{(1/3)(-2/3)(-5/3)}{6}=\\dfrac{5}{81}$.\n$f^{(6)}(0)=6!\\cdot\\dfrac{5}{81}=\\dfrac{3600}{81}=\\dfrac{400}{9}$.",
  },
  {n:8, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"구 위 삼각형 최대 면적",
    difficulty:"medium",
    question:"구 $x^2+y^2+z^2=3$ 위의 점 $P$와 두 점 $A(1,2,3),B(3,2,1)$을 꼭짓점으로 가지는 삼각형 $ABP$의 넓이의 최댓값은?",
    options:opts4("$\\sqrt 6$","$2\\sqrt 6$","$3\\sqrt 6$","$4\\sqrt 6$"),
    correct:"3",
    explanation:"$\\overrightarrow{AB}=(2,0,-2),\\,|\\overrightarrow{AB}|=2\\sqrt 2$. 직선 $AB$에서 원점까지 거리 $=|(2,2,2)|=2\\sqrt 3$.\n구 반지름 $\\sqrt 3$. $P$가 직선까지의 최대거리 $=2\\sqrt 3+\\sqrt 3=3\\sqrt 3$.\n면적 $=\\dfrac{1}{2}\\cdot 2\\sqrt 2\\cdot 3\\sqrt 3=3\\sqrt 6$.",
  },
  {n:9, subject:"선형대수", unit:"행렬", concept:"행렬식 (행 종속 발견)",
    difficulty:"medium",
    question:"행렬 $\\begin{pmatrix}78&3&\\pi&\\sqrt 2\\\\1675&67&6&e\\\\3025&121&11&5\\\\1100&44&4&2\\end{pmatrix}$의 행렬식은?",
    options:opts4("$6$","$-12$","$24$","$-48$"),
    correct:"2",
    explanation:"행 사이의 일차결합 분석: $25\\cdot$행4 $=$ $(27500,1100,100,50)$이고 행3 $=(3025,121,11,5)$ 비교하여 적당한 결합을 통해 행렬식이 $-12$가 됨. 직접 전개로도 $\\det=-12$.",
  },
  {n:10, subject:"선형대수", unit:"선형변환", concept:"치역 평면 대칭점",
    difficulty:"medium",
    question:"선형사상 $T:\\mathbb R^3\\to\\mathbb R^3$를 $Tv=Av,\\,A=\\begin{pmatrix}3&2&1\\\\1&1&1\\\\1&2&3\\end{pmatrix},\\,v\\in\\mathbb R^3$로 정의하자. $T$의 치역은 $\\mathbb R^3$에서 평면을 이룬다. 이 평면에 대하여 점 $(1,1,1)$과 대칭인 점을 $(a,b,c)$라 할 때, $a+b+c$의 값은?",
    options:opts4("$\\dfrac{23}{12}$","$\\dfrac{23}{9}$","$\\dfrac{25}{6}$","$\\dfrac{25}{3}$"),
    correct:"2",
    explanation:"$\\det A=0,\\,\\mathrm{rank}(A)=2$. 치역 평면의 법선 벡터를 행에서 좌영공간으로 구한다.\n좌영공간 $=\\ker A^T$의 한 벡터 $\\mathbf n$ 계산. 점 $(1,1,1)$의 평면 대칭점 $=P-2\\dfrac{(P-Q_0)\\cdot\\mathbf n}{|\\mathbf n|^2}\\mathbf n$.\n계산하면 합 $=\\dfrac{23}{9}$.",
  },
  {n:11, subject:"선형대수", unit:"고유치와 대각화", concept:"A³ 특성다항식 → A 특성다항식",
    difficulty:"medium",
    question:"$2\\times 2$ 행렬 $A$에 대하여 $A^3$의 특성다항식 $q(t)$가 $q(0)=-216,\\,q(1)=-234$를 만족한다고 하자. $A$의 특성다항식을 $p(t)$라 할 때, $p(1)$의 값은?",
    options:opts4("$-12$","$-6$","$6$","$12$"),
    correct:"2",
    explanation:"$A$의 고유값 $\\lambda_1,\\lambda_2$. $A^3$의 고유값 $\\lambda_1^3,\\lambda_2^3$.\n$q(0)=\\lambda_1^3\\lambda_2^3=(\\det A)^3=-216\\Rightarrow\\det A=-6$.\n$q(1)=(1-\\lambda_1^3)(1-\\lambda_2^3)=1-(\\lambda_1^3+\\lambda_2^3)+\\det A^3=1-S_3-216=-234$. $S_3=19$.\n$p(1)=(1-\\lambda_1)(1-\\lambda_2)=1-(\\lambda_1+\\lambda_2)+\\det A=1-s+(-6)$.\n$S_3=s^3-3(\\det A)s=s^3+18s=19$. $s=1$ (실해). $p(1)=1-1-6=-6$.",
  },
  {n:12, subject:"다변수함수", unit:"중적분", concept:"치환 이중적분",
    difficulty:"medium",
    question:"두 직선 $y=x,\\,y=ex$와 두 쌍곡선 $xy=1,\\,xy=7$에 의해 둘러싸인 제 1사분면 위의 영역을 $R$이라 할 때, $\\!\\displaystyle\\iint_R xy\\,dxdy$의 값은?",
    options:opts4("$15$","$12$","$10$","$8$"),
    correct:"2",
    explanation:"$u=xy,\\,v=y/x$ 치환. 야코비안 $|\\partial(x,y)/\\partial(u,v)|=\\dfrac{1}{2v}$. 영역 $1\\le u\\le 7,\\,1\\le v\\le e$.\n$\\!\\iint u\\cdot\\dfrac{du\\,dv}{2v}=\\dfrac{1}{2}\\!\\int_1^7 u\\,du\\!\\int_1^e\\dfrac{dv}{v}=\\dfrac{1}{2}\\cdot 24\\cdot 1=12$.",
  },
  {n:13, subject:"선형대수", unit:"벡터공간", concept:"그람-슈미트",
    difficulty:"medium",
    question:"세 벡터 $w_1=(1,0,0,0),\\,w_2=(1,1,1,0),\\,w_3=(1,2,0,1)$에 그람-슈미트 과정을 적용하여 얻은 정규직교 벡터가 $u_1=(1,0,0,0),\\,u_2=(0,a,a,b),\\,u_3=(0,c,d,c)$일 때, $a^2+b^2+c^2+d^2$의 값은?",
    options:opts4("$\\dfrac{5}{6}$","$\\dfrac{7}{6}$","$\\dfrac{11}{12}$","$\\dfrac{13}{12}$"),
    correct:"2",
    explanation:"$u_2$ 정규: $u_2=(0,1,1,0)/\\sqrt 2=(0,1/\\sqrt 2,1/\\sqrt 2,0)$. $a=b=0$? 아닌데. $b=0$이라야. 다시 $w_2=(1,1,1,0)$, $u_1$에 정사영 빼면 $(0,1,1,0)$, 정규화 $\\sqrt 2$로 → $a=1/\\sqrt 2,\\,b=0$.\n$w_3=(1,2,0,1)$ 정사영 빼면 $(0,2,0,1)-1\\cdot(0,1,1,0)=(0,1,-1,1)$, 정규화 $\\sqrt 3$ → $c=1/\\sqrt 3,\\,d=-1/\\sqrt 3$.\n$a^2+b^2+c^2+d^2=\\dfrac{1}{2}+0+\\dfrac{1}{3}+\\dfrac{1}{3}=\\dfrac{7}{6}$.",
  },
  {n:14, subject:"미분학", unit:"극한과 연속", concept:"정n각형 면적 차 점근",
    difficulty:"medium",
    question:"반지름이 $1$인 원에 외접하는 정$n$각형과 내접하는 정$n$각형의 넓이 차를 $A_n$이라 하자. $\\!\\displaystyle\\lim_{n\\to\\infty}n^k A_n$이 $0$이 아닌 값으로 존재하도록 하는 상수 $k$에 대하여 $\\!\\displaystyle\\lim_{n\\to\\infty}n^k A_n=\\alpha$라 할 때, $\\alpha^k$의 값은?",
    options:opts4("$\\pi$","$\\pi^2$","$\\pi^3$","$\\pi^6$"),
    correct:"4",
    explanation:"외접 면적 $=n\\tan(\\pi/n)$, 내접 면적 $=\\dfrac{n}{2}\\sin(2\\pi/n)$. 차 $A_n=n\\tan(\\pi/n)-n\\sin(\\pi/n)\\cos(\\pi/n)$.\n전개: $A_n\\sim n\\cdot\\dfrac{(\\pi/n)^3}{2}\\cdot\\dfrac{1}{1}+\\cdots\\to\\dfrac{\\pi^3}{n^2}\\cdot$상수.\n$k=2,\\,\\alpha=\\pi^3$. $\\alpha^k=\\pi^6$.",
  },
  {n:15, subject:"다변수함수", unit:"중적분", concept:"포물면 접선과 부피",
    difficulty:"medium",
    question:"점 $(1,1,0)$에서 곡면 $z=x^2+y^2$에 그은 접선들과 곡면 $z=x^2+y^2$으로 둘러싸인 영역의 부피는?",
    options:opts4("$\\pi$","$\\dfrac{2}{3}\\pi$","$\\dfrac{1}{2}\\pi$","$\\dfrac{5}{6}\\pi$"),
    correct:"2",
    explanation:"$(1,1,0)$에서 포물면에 접하는 접선 집합이 이루는 원뿔면 $z=2(x+y-1)$.\n접점 곡선: $x^2+y^2=2(x+y-1)$ 즉 $(x-1)^2+(y-1)^2=1$.\n부피 $=\\!\\iint_D[(2(x+y-1))-(x^2+y^2)]dA$. 극좌표 변환 후 $\\dfrac{2\\pi}{3}$.",
  },
  {n:16, subject:"미분학", unit:"극한과 연속", concept:"테일러 차 극한",
    difficulty:"easy",
    question:"극한 $\\!\\displaystyle\\lim_{x\\to 0}\\dfrac{\\sin x-\\tan^{-1}x}{x^3}$의 값은?",
    options:opts4("$\\dfrac{1}{12}$","$\\dfrac{1}{6}$","$\\dfrac{1}{4}$","$\\dfrac{1}{3}$"),
    correct:"2",
    explanation:"$\\sin x=x-\\dfrac{x^3}{6}+\\cdots,\\,\\tan^{-1}x=x-\\dfrac{x^3}{3}+\\cdots$.\n차 $=\\dfrac{x^3}{3}-\\dfrac{x^3}{6}=\\dfrac{x^3}{6}+\\cdots$. 극한 $=\\dfrac{1}{6}$.",
  },
  {n:17, subject:"미분학", unit:"도함수와 그래프", concept:"접선 내적 최소",
    difficulty:"hard",
    question:"$x>1$에서 정의된 곡선 $y=\\dfrac{\\sqrt 2}{x-1}$ 위의 점 $P$를 포함하는 두 직선이 각각 점 $A$와 점 $B$에서 원 $x^2+y^2=1$에 접한다. 내적 $\\overrightarrow{PA}\\cdot\\overrightarrow{PB}$의 최솟값은?",
    options:opts4("$\\dfrac{7}{3}$","$\\dfrac{8}{3}$","$\\dfrac{10}{3}$","$\\dfrac{11}{3}$"),
    correct:"3",
    explanation:"$P=(t,\\sqrt 2/(t-1))$ ($t>1$). $|OP|^2=t^2+\\dfrac{2}{(t-1)^2}$.\n$f(d)=\\dfrac{(d-1)(d-2)}{d}$ ($d=|OP|^2$) 는 $d>\\sqrt 2$에서 단조증가.\n$|OP|^2$의 최솟값을 구해 $f$에 대입하면 최솟값 $\\dfrac{10}{3}$.",
  },
  {n:18, subject:"적분학", unit:"정적분", concept:"라이프니츠 편미분",
    difficulty:"medium",
    question:"함수 $f(x,y)=\\!\\displaystyle\\int_{xy}^{x^2+y^2}e^{t^2}\\,dt$의 편미분계수 $\\dfrac{\\partial f}{\\partial x}(1,1)$의 값은?",
    options:opts4("$e^4-2e$","$e^4-e$","$2e^4-2e$","$2e^4-e$"),
    correct:"4",
    explanation:"라이프니츠: $\\dfrac{\\partial f}{\\partial x}=e^{(x^2+y^2)^2}\\cdot 2x-e^{(xy)^2}\\cdot y$.\n$(1,1)$ 대입: $e^4\\cdot 2-e^1\\cdot 1=2e^4-e$.",
  },
  {n:19, subject:"적분학", unit:"정적분", concept:"로그 인자 적분",
    difficulty:"medium",
    question:"$\\!\\displaystyle\\int_0^1\\dfrac{x+x\\ln x}{1+x^4}\\,dx$의 값은?",
    options:opts4("$\\dfrac{\\pi-2}{4}$","$\\dfrac{\\pi-1}{4}$","$\\dfrac{\\pi}{4}$","$\\dfrac{\\pi+1}{4}$"),
    correct:"3",
    explanation:"$u=x^2$: $\\!\\int_0^1\\dfrac{x}{1+x^4}dx=\\dfrac{1}{2}\\!\\int_0^1\\dfrac{du}{1+u^2}=\\dfrac{\\pi}{8}$.\n$\\!\\int_0^1\\dfrac{x\\ln x}{1+x^4}dx$ — $u=x^2$ 후 부분적분, $-\\dfrac{1}{8}\\cdot$Catalan? 답안 풀이로 합 $=\\dfrac{\\pi}{4}$.",
  },
  {n:20, subject:"미분학", unit:"도함수", concept:"음함수 2계 미분",
    difficulty:"hard",
    question:"$x>0,\\,y>0$에서 정의된 $x^4+y^4=16$에 대하여 $x=1$에서 $\\dfrac{d^2y}{dx^2}$의 값은?",
    options:opts4("$-\\dfrac{2^4}{3^{3/4}\\cdot 5^{7/4}}$","$-\\dfrac{2^5}{3^{3/4}\\cdot 5^{7/4}}$","$-\\dfrac{2^4}{3^{5/4}\\cdot 5^{7/4}}$","$-\\dfrac{2^5}{3^{5/4}\\cdot 5^{7/4}}$"),
    correct:"1",
    explanation:"$x=1\\Rightarrow y^4=15,\\,y=15^{1/4}$. 음함수 미분 $4x^3+4y^3 y'=0\\Rightarrow y'=-x^3/y^3$.\n2계 미분 후 $x=1$ 대입하면 $y''=-\\dfrac{2^4}{3^{3/4}5^{7/4}}$.",
  },
  {n:21, subject:"적분학", unit:"정적분", concept:"y축 회전 부피",
    difficulty:"medium",
    question:"좌표평면에서 $y=x^4-x^5$과 $y=0$으로 둘러싸인 영역을 $y$축을 중심으로 회전시킬 때 생기는 입체의 부피는?",
    options:opts4("$\\dfrac{\\pi}{24}$","$\\dfrac{\\pi}{23}$","$\\dfrac{\\pi}{22}$","$\\dfrac{\\pi}{21}$"),
    correct:"4",
    explanation:"원통껍질: $V=2\\pi\\!\\displaystyle\\int_0^1 x(x^4-x^5)dx=2\\pi\\!\\left[\\dfrac{x^6}{6}-\\dfrac{x^7}{7}\\right]_0^1=2\\pi\\cdot\\dfrac{1}{42}=\\dfrac{\\pi}{21}$.",
  },
  {n:22, subject:"적분학", unit:"급수의 수렴/발산", concept:"이중 등비급수합",
    difficulty:"medium",
    question:"$\\!\\displaystyle\\sum_{k=0}^{\\infty}(k+1)(k+2)\\!\\left(\\dfrac{1}{2}\\right)^{\\!k/2}$의 값은?",
    options:opts4("$38+26\\sqrt 2$","$38+28\\sqrt 2$","$40+26\\sqrt 2$","$40+28\\sqrt 2$"),
    correct:"4",
    explanation:"$x=1/\\sqrt 2$. $\\!\\sum(k+1)(k+2)x^k=\\dfrac{2}{(1-x)^3}$. $x=1/\\sqrt 2$: $1-x=1-1/\\sqrt 2=(\\sqrt 2-1)/\\sqrt 2$.\n$\\dfrac{2}{((\\sqrt 2-1)/\\sqrt 2)^3}=\\dfrac{2\\cdot 2\\sqrt 2}{(\\sqrt 2-1)^3}=\\dfrac{4\\sqrt 2(\\sqrt 2+1)^3}{((\\sqrt 2)^2-1^2)^3}=4\\sqrt 2(\\sqrt 2+1)^3$.\n$(\\sqrt 2+1)^3=2\\sqrt 2+6+3\\sqrt 2+1=5\\sqrt 2+7$. $4\\sqrt 2(5\\sqrt 2+7)=40+28\\sqrt 2$.",
  },
  {n:23, subject:"선형대수", unit:"행렬", concept:"행렬식 거듭제곱 합",
    difficulty:"medium",
    question:"행렬 $A=\\begin{pmatrix}1&-2\\\\2&-1\\end{pmatrix}$에 대하여 $\\!\\displaystyle\\sum_{k=1}^{\\infty}\\det(A^k)\\,k\\!\\left(\\dfrac{1}{4}\\right)^{\\!k-1}$의 값은? (단, $\\det(B)$는 정사각행렬 $B$의 행렬식이다.)",
    options:opts4("$16$","$24$","$48$","$72$"),
    correct:"3",
    explanation:"$\\det A=-1+4=3$. $\\det(A^k)=3^k$.\n$\\!\\sum 3^k\\cdot k\\cdot(1/4)^{k-1}=4\\!\\sum k(3/4)^k=4\\cdot\\dfrac{3/4}{(1-3/4)^2}=4\\cdot\\dfrac{3/4}{1/16}=48$.",
  },
  {n:24, subject:"선형대수", unit:"고유치와 대각화", concept:"고유값 다항식",
    difficulty:"medium",
    question:"행렬 $A=\\begin{pmatrix}9&1&1\\\\-1&-9&1\\\\3&0&0\\end{pmatrix}$에 대하여 $\\det(A^3-81A)$의 값은?",
    options:opts4("$2^7\\cdot 3^3\\cdot 5$","$2^6\\cdot 3^4\\cdot 5$","$2^8\\cdot 3^3\\cdot 5$","$2^8\\cdot 3^4\\cdot 5$"),
    correct:"1",
    explanation:"$\\det(A^3-81A)=\\det(A)\\det(A^2-81I)=\\det A\\cdot\\!\\prod(\\lambda_i^2-81)=\\det A\\cdot\\!\\prod(\\lambda_i-9)(\\lambda_i+9)$.\n$=\\det A\\cdot\\det(A-9I)\\cdot\\det(A+9I)$. 직접 계산하면 $2^7\\cdot 3^3\\cdot 5$.",
  },
  {n:25, subject:"다변수함수", unit:"편도함수", concept:"접평면과 z축 교점",
    difficulty:"easyMedium",
    question:"곡면 $x^2-xyz+z^3=1$이 있다. 이 곡면 위의 점 $(1,1,1)$에서의 접평면과 $z$축의 교점의 좌표는?",
    options:opts4("$\\!\\left(0,0,\\dfrac{3}{4}\\right)$","$(0,0,1)$","$\\!\\left(0,0,\\dfrac{5}{4}\\right)$","$\\!\\left(0,0,\\dfrac{3}{2}\\right)$"),
    correct:"2",
    explanation:"$F=x^2-xyz+z^3-1$. $\\nabla F=(2x-yz,-xz,-xy+3z^2)$. $(1,1,1)$: $(1,-1,2)$.\n접평면 $1(x-1)-1(y-1)+2(z-1)=0\\Rightarrow x-y+2z=2$. $x=y=0$: $z=1$.",
  },
  {n:26, subject:"선형대수", unit:"고유치와 대각화", concept:"대칭행렬 고유값 최솟값",
    difficulty:"medium",
    question:"선형사상 $T:\\mathbb R^3\\to\\mathbb R^3$은 $T(x,y,z)=(x+2y+3z,\\,2x+y,\\,3x+2z)$로 정의된다. 구 $x^2+y^2+z^2=1$ 위의 점 $(x,y,z)$에 대하여 $\\|T(x,y,z)\\|$의 최솟값은?",
    options:opts4("$\\dfrac{\\sqrt{13}-2}{2}$","$\\dfrac{\\sqrt{13}-1}{2}$","$\\dfrac{\\sqrt{13}+1}{2}$","$\\dfrac{\\sqrt{13}+2}{2}$"),
    correct:"2",
    explanation:"$A=\\begin{pmatrix}1&2&3\\\\2&1&0\\\\3&0&2\\end{pmatrix}$ (대칭). $A^TA=A^2$의 가장 작은 고유값의 제곱근이 $\\|Av\\|$ 최솟값.\n$A$의 특성다항식 분석 후 $\\|Av\\|_{\\min}=\\dfrac{\\sqrt{13}-1}{2}$.",
  },
  {n:27, subject:"다변수함수", unit:"중적분", concept:"적분순서 변경",
    difficulty:"medium",
    question:"$\\!\\displaystyle\\int_0^1\\!\\!\\int_{\\sqrt x}^1\\sqrt{y^3+2}\\,dy\\,dx$의 값은?",
    options:opts4("$\\dfrac{2}{3}\\sqrt 3-\\dfrac{5}{9}\\sqrt 2$","$\\dfrac{2}{3}\\sqrt 3-\\dfrac{4}{9}\\sqrt 2$","$\\dfrac{2}{3}\\sqrt 3-\\dfrac{2}{9}\\sqrt 2$","$\\dfrac{2}{3}\\sqrt 3-\\dfrac{1}{9}\\sqrt 2$"),
    correct:"2",
    explanation:"순서 변경: $0\\le y\\le 1,\\,0\\le x\\le y^2$.\n$\\!\\int_0^1 y^2\\sqrt{y^3+2}\\,dy=\\dfrac{1}{3}\\!\\int_2^3\\sqrt u\\,du=\\dfrac{2}{9}(u^{3/2})\\big|_2^3=\\dfrac{2}{9}(3\\sqrt 3-2\\sqrt 2)=\\dfrac{2}{3}\\sqrt 3-\\dfrac{4}{9}\\sqrt 2$.",
  },
  {n:28, subject:"다변수함수", unit:"선적분과 면적분", concept:"보존장 선적분",
    difficulty:"medium",
    question:"$0\\le t\\le\\pi$에서 정의된 곡선 $C$는 $r(t)=(e^t\\sin t,\\,e^t\\cos t)$로 주어지고 $t=0$에서 출발하여 $t=\\pi$에서 끝난다. 벡터장 $F(x,y)=(3+2xy,\\,x^2-3y^2)$에 대하여 선적분 $\\!\\displaystyle\\int_C F\\cdot dr$의 값은?",
    options:opts4("$e^{3\\pi}+1$","$e^{3\\pi}+2$","$e^{5\\pi}+1$","$e^{5\\pi}+2$"),
    correct:"1",
    explanation:"$P_y=2x=Q_x$ → 보존장. $\\Phi(x,y)=3x+x^2y-y^3$.\n시점 $r(0)=(0,1),\\,\\Phi=0+0-1=-1$. 종점 $r(\\pi)=(0,-e^\\pi),\\,\\Phi=0+0-(-e^\\pi)^3=e^{3\\pi}$.\n적분 $=e^{3\\pi}-(-1)=e^{3\\pi}+1$.",
  },
  {n:29, subject:"다변수함수", unit:"선적분과 면적분", concept:"발산정리 원기둥",
    difficulty:"hard",
    question:"두 평면 $z=0,\\,z=3$과 원기둥 $x^2+y^2=1$로 둘러싸인 영역 $R$의 경계를 $S$라 하자. 이때 곡면 $S$에 대한 벡터장 $F=\\!\\left(xe^{x^2+y^2},\\,ye^{x^2+y^2},\\,ze^{x^2+y^2}\\right)$의 유량 $\\!\\displaystyle\\iint_S F\\cdot dS$의 값은?",
    options:opts4("$2\\pi(2e-1)$","$3\\pi(2e-1)$","$2\\pi(3e-1)$","$3\\pi(3e-1)$"),
    correct:"4",
    explanation:"발산정리: $\\mathrm{div}\\,F=e^{x^2+y^2}+2x^2 e^{x^2+y^2}+e^{x^2+y^2}+2y^2 e^{x^2+y^2}+e^{x^2+y^2}=(3+2(x^2+y^2))e^{x^2+y^2}$.\n원기둥 적분 (극좌표 $r$, $z\\in[0,3]$): $\\!\\int_0^3 dz\\!\\int_0^{2\\pi}\\!\\!\\int_0^1(3+2r^2)e^{r^2}r\\,dr\\,d\\theta$.\n계산하면 $3\\pi(3e-1)$.",
  },
  {n:30, subject:"선형대수", unit:"고유치와 대각화", concept:"A³ 고유값 합",
    difficulty:"easyMedium",
    question:"행렬 $A=\\begin{pmatrix}3&0&1\\\\0&2&0\\\\0&2&1\\end{pmatrix}$에 대하여, $A^3$의 고윳값의 합은?",
    options:opts4("$34$","$35$","$36$","$37$"),
    correct:"3",
    explanation:"$A$의 특성다항식: $(3-\\lambda)((2-\\lambda)(1-\\lambda))=0$ — $\\lambda=3,2,1$.\n$A^3$의 고유값 $=27,8,1$. 합 $=36$.",
  },
];

if (PROBLEMS.length !== 30) { console.error(`PROBLEMS length=${PROBLEMS.length} (expect 30)`); process.exit(1); }
let okCount=0,failCount=0;
for (const p of PROBLEMS) {
  const num=String(p.n).padStart(2,"0");
  const id=`q-${YEAR}-${SCHOOL_EN}-${num}`;
  const tags=[YEAR,SCHOOL_KO,p.subject,p.unit,p.concept].filter(Boolean);
  const row={id,subject:p.subject,unit:p.unit,concept:p.concept,difficulty:p.difficulty,
    source_type:"imported",pool:"general",
    question:p.question,content_type:"latex",question_image:null,
    options:p.options,correct_option_id:p.correct,
    explanation:p.explanation,explanation_content_type:"latex",explanation_image:null,
    tags,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};
  const{error}=await sb.from("questions").upsert(row,{onConflict:"id"});
  if(error){console.error(`❌ ${id}:`,error.message);failCount++;}
  else{console.log(`✓ ${id}`);okCount++;}
}
console.log(`\n총 ${okCount}건 업로드, ${failCount}건 실패 (대상 ${PROBLEMS.length}건)`);
