// 2018년 중앙대(수학과) 편입수학 객관식 30문항 (4지선다)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR="2018", SCHOOL_KO="중앙대", SCHOOL_EN="cau";
const opts4 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:1, subject:"미분학", unit:"극한과 연속", concept:"지수형 극한",
    difficulty:"medium",
    question:"$\\displaystyle\\lim_{x\\to\\infty}\\!\\left(\\dfrac{x^2-3x+1}{5x+2}\\right)^{\\!\\frac{1}{2\\ln x}}$을 계산하면?",
    options:opts4("$e^2$","$e$","$\\sqrt e$","$1$"),
    correct:"3",
    explanation:"$\\dfrac{x^2-3x+1}{5x+2}\\sim\\dfrac{x}{5}$이므로 $\\ln$ 안의 식 $\\sim\\ln x-\\ln 5$.\n지수 적용: $\\dfrac{\\ln x-\\ln 5}{2\\ln x}\\to\\dfrac{1}{2}$. 따라서 극한값 $=e^{1/2}=\\sqrt e$.",
  },
  {n:2, subject:"적분학", unit:"정적분", concept:"리만합 거듭제곱",
    difficulty:"easyMedium",
    question:"$\\displaystyle\\lim_{n\\to\\infty}\\dfrac{\\!\\left(\\sum_{k=1}^n k^3\\right)\\!\\left(\\sum_{k=1}^n k^5\\right)}{\\!\\left(\\sum_{k=1}^n k\\right)\\!\\left(\\sum_{k=1}^n k^7\\right)}$의 값은?",
    options:opts4("$1$","$\\dfrac{1}{2}$","$\\dfrac{2}{3}$","$\\dfrac{3}{4}$"),
    correct:"3",
    explanation:"$\\!\\sum k^p\\sim\\dfrac{n^{p+1}}{p+1}$. 분자 $\\sim\\dfrac{n^4}{4}\\cdot\\dfrac{n^6}{6}=\\dfrac{n^{10}}{24}$.\n분모 $\\sim\\dfrac{n^2}{2}\\cdot\\dfrac{n^8}{8}=\\dfrac{n^{10}}{16}$. 비 $=\\dfrac{16}{24}=\\dfrac{2}{3}$.",
  },
  {n:3, subject:"미분학", unit:"도함수", concept:"음함수 2계 미분",
    difficulty:"medium",
    question:"$\\sin(x+y)=y^2\\cos x$를 만족할 때, $(x,y)=(0,0)$에서 $\\dfrac{d^2y}{dx^2}$을 구하면?",
    options:opts4("$1$","$2$","$-1$","$-2$"),
    correct:"2",
    explanation:"양변 미분: $\\cos(x+y)(1+y')=2yy'\\cos x-y^2\\sin x$. $(0,0)$ 대입: $1+y'=0\\Rightarrow y'=-1$.\n다시 미분 후 $(0,0)$ 대입: $-\\sin(x+y)(1+y')^2+\\cos(x+y)\\,y''=2(y')^2\\cos x+\\cdots$.\n좌변 $=y''$, 우변 $=2(-1)^2=2$. $y''=2$.",
  },
  {n:4, subject:"적분학", unit:"급수의 수렴/발산", concept:"수렴 보기 6개",
    difficulty:"medium",
    question:"다음 <보기> 중 수렴하는 급수의 개수는?\n(가) $\\displaystyle\\sum_{n=1}^{\\infty}\\sin^3\\dfrac{1}{n}$\n(나) $\\displaystyle\\sum_{n=1}^{\\infty}\\sqrt{n\\arctan\\!\\left(\\dfrac{1}{n^4}\\right)}$\n(다) $\\displaystyle\\sum_{n=1}^{\\infty}(n^{1/n}-1)^n$\n(라) $\\displaystyle\\sum_{n=10}^{\\infty}(-1)^{n-1}\\dfrac{1}{\\ln n}$\n(마) $\\dfrac{1}{2}+\\dfrac{1}{3}+\\dfrac{1}{2^2}+\\dfrac{1}{3^2}+\\dfrac{1}{2^3}+\\dfrac{1}{3^3}+\\cdots$\n(바) $\\displaystyle\\sum_{n=1}^{\\infty}\\tan\\!\\left(\\dfrac{1}{n^3}\\right)$",
    options:opts4("$3$ 개","$4$ 개","$5$ 개","$6$ 개"),
    correct:"4",
    explanation:"(가) $\\sin^3(1/n)\\sim 1/n^3$ 수렴. (나) $\\sqrt{n\\cdot 1/n^4}=1/n^{3/2}$ 수렴.\n(다) $n^{1/n}-1\\sim\\ln n/n\\to 0$, $(\\ln n/n)^n\\to 0$ 빠르게 → 수렴.\n(라) 교대급수, $1/\\ln n\\to 0$ 단조감소 → 수렴.\n(마) 두 등비급수 $1+1/2$ → 수렴. (바) $\\tan(1/n^3)\\sim 1/n^3$ 수렴.\n총 $6$개 수렴.",
  },
  {n:5, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"교선 위 원점 최단점",
    difficulty:"medium",
    question:"두 평면 $x+2y+z=7,\\,x-y-z=4$의 교선 위의 점 중에서 원점에 가장 가까운 점을 $(a,b,c)$라 할 때, $a+b+c$의 값은?",
    options:opts4("$\\dfrac{27}{4}$","$\\dfrac{31}{5}$","$\\dfrac{35}{6}$","$\\dfrac{39}{7}$"),
    correct:"4",
    explanation:"법선 $\\mathbf n_1=(1,2,1),\\,\\mathbf n_2=(1,-1,-1)$. 교선 방향 $\\mathbf d=\\mathbf n_1\\times\\mathbf n_2=(-1,2,-3)$.\n$y=0$ 대입 시 점 $P=(11/2,0,3/2)$. 최단점 $=P-\\dfrac{P\\cdot\\mathbf d}{|\\mathbf d|^2}\\mathbf d$.\n$P\\cdot\\mathbf d=-10,\\,|\\mathbf d|^2=14$. 최단점 $=(67/14,20/14,-9/14)$.\n합 $=\\dfrac{78}{14}=\\dfrac{39}{7}$.",
  },
  {n:6, subject:"미분학", unit:"극한과 연속", concept:"점화식 점근비",
    difficulty:"easyMedium",
    question:"$x_1=x_2=1$이고 $x_{n+1}=2x_n+3x_{n-1}\\,(n\\ge 2)$를 만족하는 수열 $\\{x_n\\}_{n=1}^{\\infty}$에 대하여 $\\displaystyle\\lim_{n\\to\\infty}\\dfrac{x_{n+1}}{x_n}$의 값은?",
    options:opts4("$\\dfrac{1}{2}$","$\\dfrac{1}{3}$","$2$","$3$"),
    correct:"4",
    explanation:"점근비 $r=\\!\\lim x_{n+1}/x_n$이 존재한다고 하면 $r=2+3/r$, 즉 $r^2-2r-3=0\\Rightarrow r=3$ 또는 $-1$.\n수열이 양항이고 증가하므로 $r=3$.",
  },
  {n:7, subject:"적분학", unit:"정적분", concept:"감마함수",
    difficulty:"easy",
    question:"$\\displaystyle\\int_0^{\\infty}x^3 e^{-x}\\,dx$의 값은?",
    options:opts4("$3$","$6$","$\\dfrac{4}{15}e^3$","$\\dfrac{5}{16}\\sqrt e$"),
    correct:"2",
    explanation:"$\\!\\int_0^{\\infty}x^n e^{-x}dx=\\Gamma(n+1)=n!$. $n=3$: $3!=6$.",
  },
  {n:8, subject:"적분학", unit:"정적분", concept:"포물선 면적 비율",
    difficulty:"medium",
    question:"좌표평면 위의 곡선 $y=x^2-2$와 직선 $y=a$로 둘러싸인 영역의 넓이가 $y=x^2-2$와 $x$축으로 둘러싸인 영역의 넓이의 $8$배가 되도록 하는 양수 $a$를 정하면?",
    options:opts4("$3$","$6$","$8$","$10$"),
    correct:"2",
    explanation:"$y=x^2-2$와 $x$축 사이 면적 $=\\dfrac{8\\sqrt 2}{3}$.\n$y=x^2-2$와 $y=a$ ($a>0$) 사이 면적 $=\\dfrac{4(a+2)^{3/2}}{3}$.\n$\\dfrac{4(a+2)^{3/2}}{3}=8\\cdot\\dfrac{8\\sqrt 2}{3}\\Rightarrow(a+2)^{3/2}=16\\sqrt 2=2^{9/2}\\Rightarrow a+2=8\\Rightarrow a=6$.",
  },
  {n:9, subject:"다변수함수", unit:"편도함수", concept:"연속·미분 진위",
    difficulty:"medium",
    question:"함수 $F(x,y)=\\!\\begin{cases}\\dfrac{x^3y^2}{x^4+y^4},&(x,y)\\ne(0,0)\\\\0,&(x,y)=(0,0)\\end{cases}$에 대한 다음 <보기>의 설명 중 옳은 것의 개수는?\n(가) $f(x)=F(x,0)$는 $x=0$에서 연속이다.\n(나) $g(y)=F(0,y)$는 $y=0$에서 연속이다.\n(다) $F(x,y)$는 $(x,y)=(0,0)$에서 연속이다.\n(라) $F(x,y)$는 $(x,y)=(0,0)$에서 미분가능하다.",
    options:opts4("$1$ 개","$2$ 개","$3$ 개","$4$ 개"),
    correct:"3",
    explanation:"(가)(나) $F(x,0)=F(0,y)=0$ → 연속. 참.\n(다) 극좌표 $|F|\\le r\\cdot|\\cdot|\\to 0$ → 연속. 참.\n(라) $F_x(0,0)=F_y(0,0)=0$이지만 경로 $x=y=t$에서 $F/\\sqrt{x^2+y^2}=1/(2\\sqrt 2)\\ne 0$ → 미분불가. 거짓.\n참 $3$개.",
  },
  {n:10, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"평면-원뿔 교집합 거리",
    difficulty:"medium",
    question:"평면 $z=\\dfrac{9}{2}+\\dfrac{x}{2}$와 원뿔면 $x^2+y^2=z^2$의 교집합에 속하는 점과 원점 사이의 최대거리는?",
    options:opts4("$9\\sqrt 2$","$7\\sqrt 3$","$5\\sqrt 5$","$3\\sqrt 7$"),
    correct:"1",
    explanation:"교점에서 $x^2+y^2+z^2=2z^2=2\\!\\left(\\dfrac{9+x}{2}\\right)^{\\!2}=\\dfrac{(9+x)^2}{2}$, 거리 $=\\dfrac{|9+x|}{\\sqrt 2}$.\n$y^2=z^2-x^2\\ge 0\\Rightarrow-3\\le x\\le 9$. $x=9$에서 최대 $=\\dfrac{18}{\\sqrt 2}=9\\sqrt 2$.",
  },
  {n:11, subject:"다변수함수", unit:"중적분", concept:"평행사변형 변환적분",
    difficulty:"medium",
    question:"좌표평면 위의 네 점 $(0,0),(1,1),(2,-2),(3,-1)$을 꼭짓점으로 가지는 사각형의 경계와 내부를 $R$이라 할 때, $\\displaystyle\\iint_R(x+y)e^{x-y}\\,dxdy$를 계산하면?",
    options:opts4("$e^4-1$","$e^3-2$","$e^3-3$","$e^4-4$"),
    correct:"1",
    explanation:"평행사변형 변 $(1,1),(2,-2)$로 형성. $u=x-y,\\,v=x+y$ 치환. 야코비안 $|\\partial(x,y)/\\partial(u,v)|=1/2$.\n새 영역: $0\\le u\\le 4,\\,0\\le v\\le 2$ (꼭짓점 $(0,0),(2,4),(0,4),(2,0)$ 매핑).\n$\\!\\iint v\\,e^u\\cdot\\dfrac{1}{2}\\,dudv=\\dfrac{1}{2}\\!\\int_0^4 e^u du\\!\\int_0^2 v\\,dv=\\dfrac{1}{2}(e^4-1)\\cdot 2=e^4-1$.",
  },
  {n:12, subject:"미분학", unit:"도함수와 그래프", concept:"치환 후 극값",
    difficulty:"medium",
    question:"$1\\le x\\le 3$에서 정의된 함수 $f(x)=2\\!\\left(x-\\dfrac{3}{x}\\right)^{\\!3}-15\\!\\left(x-\\dfrac{3}{x}\\right)^{\\!2}+36\\!\\left(x-\\dfrac{3}{x}\\right)-50$의 최댓값과 최솟값의 차는?",
    options:opts4("$126$","$146$","$176$","$216$"),
    correct:"3",
    explanation:"$t=x-3/x$로 두면 $1\\le x\\le 3$에서 $t\\in[-2,2]$. $g(t)=2t^3-15t^2+36t-50$.\n$g'(t)=6t^2-30t+36=6(t-2)(t-3)=0\\Rightarrow t=2,3$. $[-2,2]$ 내부 임계점 $t=2$ (경계).\n$g(-2)=-2\\cdot 8-15\\cdot 4-72-50=-198$. $g(2)=16-60+72-50=-22$.\n최대 $-22$, 최소 $-198$, 차 $=176$.",
  },
  {n:13, subject:"다변수함수", unit:"편도함수", concept:"극값·라그랑주 진위",
    difficulty:"medium",
    question:"다음 <보기> 중 옳은 것의 개수는?\n(가) $f(x,y)=y^4-x^4-2y^2+2x^2$의 극솟값은 $-1$이다.\n(나) $f(x,y)=y^4-x^4-2y^2+2x^2$은 $(-1,1)$에서 극댓값을 갖는다.\n(다) 원 $x^2+y^2=1$ 위에서 $g(x,y)=x^2+2y^2$의 최댓값은 $3$이 아니라 $2$이다.\n(라) $x-y+z=1$과 $x^2+y^2=1$의 교선 위에서 $h(x,y,z)=x+2y+3z$의 최댓값은 $6$이다.",
    options:opts4("$1$ 개","$2$ 개","$3$ 개","$4$ 개"),
    correct:"1",
    explanation:"(가) 임계점 $(\\pm 1,0)$에서 $f=1$, $(0,\\pm 1)$에서 $f=-1$. 안장점 분류 후 극솟값 $-1$. 참.\n(나) $(-1,1)$에서 헤시안 분석 → 안장점. 거짓.\n(다) 단위원 위 $g_{\\max}=2$ (문제는 $3$). 거짓.\n(라) $z=1-x+y$ 대입 후 라그랑주: 최댓값 $4+\\sqrt{26}\\ne 6$. 거짓.\n참 $1$개.",
  },
  {n:14, subject:"적분학", unit:"정적분", concept:"극좌표 영역 교집합",
    difficulty:"medium",
    question:"극좌표계로 주어진 두 곡선 $r=1-\\cos\\theta,\\,r=\\cos\\theta$의 내부를 각각 $R,S$라 할 때, $R\\cap S$의 넓이는?",
    options:opts4("$\\dfrac{7}{12}\\pi-\\sqrt 3$","$\\dfrac{7}{12}\\pi+\\sqrt 3$","$\\dfrac{7}{12}\\pi-\\sqrt 2$","$\\dfrac{7}{12}\\pi+\\sqrt 2$"),
    correct:"1",
    explanation:"교점 $1-\\cos\\theta=\\cos\\theta\\Rightarrow\\cos\\theta=1/2,\\,\\theta=\\pm\\pi/3$.\n교집합 면적 $=2\\!\\left[\\dfrac{1}{2}\\!\\int_0^{\\pi/3}(1-\\cos\\theta)^2d\\theta+\\dfrac{1}{2}\\!\\int_{\\pi/3}^{\\pi/2}\\cos^2\\theta\\,d\\theta\\right]$.\n계산하면 $\\dfrac{7\\pi}{12}-\\sqrt 3$.",
  },
  {n:15, subject:"다변수함수", unit:"선적분과 면적분", concept:"그린정리 최댓값",
    difficulty:"medium",
    question:"$xy$-평면에서 시계반대방향의 향을 갖는 단순폐곡선 $C$에 대하여 선적분 $\\displaystyle\\int_C(y^3-9y)\\,dx-x^3\\,dy$의 최댓값은?",
    options:opts4("$\\dfrac{25}{2}\\pi$","$9\\pi$","$\\dfrac{27}{2}\\pi$","$\\dfrac{45}{2}\\pi$"),
    correct:"3",
    explanation:"그린정리: $\\!\\iint_D(Q_x-P_y)dA=\\!\\iint_D(-3x^2-3y^2+9)dA=-3\\!\\iint_D(x^2+y^2-3)dA$.\n최댓값: 적분값이 양수일 때, $x^2+y^2\\le 3$ (피적분 음수 영역)을 영역으로 잡음.\n극좌표: $-3\\!\\int_0^{2\\pi}\\!\\!\\int_0^{\\sqrt 3}(r^2-3)r\\,drd\\theta=-3\\cdot 2\\pi\\cdot\\!\\left(\\dfrac{9}{4}-\\dfrac{9}{2}\\right)=\\dfrac{27\\pi}{2}$.",
  },
  {n:16, subject:"다변수함수", unit:"선적분과 면적분", concept:"보존장 선적분",
    difficulty:"medium",
    question:"$x=e^{t^2}-e,\\,y=\\sin\\dfrac{\\pi}{t^2+2}$로 매개화된 곡선 $C:[0,1]\\to\\mathbb R^2$ 위에서 정의된 벡터장 $\\mathbf F(x,y)=\\!\\left(3x^2\\cos\\!\\left(\\dfrac{\\pi}{4}y\\right),-\\dfrac{\\pi}{4}x^3\\sin\\!\\left(\\dfrac{\\pi}{4}y\\right)\\!\\right)$의 선적분 $\\displaystyle\\int_C\\mathbf F\\cdot d\\mathbf s$를 구하면?",
    options:opts4("$\\dfrac{\\sqrt 2}{2}(e-1)^3$","$\\sqrt 2(e-1)^3$","$\\dfrac{\\sqrt 2}{2}(e-1)^2$","$\\sqrt 2(e-1)^2$"),
    correct:"1",
    explanation:"$\\mathbf F=\\nabla\\!\\left(x^3\\cos\\!\\left(\\dfrac{\\pi y}{4}\\right)\\!\\right)$ 보존장. $\\Phi(x,y)=x^3\\cos(\\pi y/4)$.\n$t=0$: $(x,y)=(1-e,\\sin(\\pi/2))=(1-e,1)$. $t=1$: $(0,\\sin(\\pi/3))=(0,\\sqrt 3/2)$.\n$\\Phi(0,\\sqrt 3/2)-\\Phi(1-e,1)=0-(1-e)^3\\cos(\\pi/4)=(e-1)^3\\cdot\\dfrac{\\sqrt 2}{2}$.",
  },
  {n:17, subject:"다변수함수", unit:"선적분과 면적분", concept:"발산정리 반구",
    difficulty:"medium",
    question:"반구 $S=\\{(x,y,z)\\in\\mathbb R^3\\mid x^2+y^2+z^2=1,\\,z\\ge 0\\}$에서 주어진 벡터장 $\\mathbf F(x,y,z)=(ye^{z^2}\\sin z,\\,xe^{z^2}\\cos z,\\,4x^2+z)$의 곡면 적분 $\\displaystyle\\iint_S\\mathbf F\\cdot\\mathbf n\\,dS$를 계산하면? (단, $\\mathbf n$은 곡면에 수직이며 반구의 바깥쪽으로 향하는 단위벡터이다.)",
    options:opts4("$0$","$\\dfrac{2}{3}\\pi$","$\\dfrac{5}{3}\\pi$","$2\\pi$"),
    correct:"3",
    explanation:"발산정리: 반구 $V$ 위 $\\!\\iiint_V\\mathrm{div}\\,\\mathbf F\\,dV=\\!\\iint_S\\mathbf F\\cdot\\mathbf n+\\!\\iint_{\\text{원판}}$.\n$\\mathrm{div}\\,\\mathbf F=0+0+1=1$. $V$ 부피 $=2\\pi/3$.\n원판 ($z=0$, 아래쪽): $\\mathbf F\\cdot(-\\hat k)=-(4x^2+0)$. $-\\!\\iint_{D}4x^2\\,dA=-4\\cdot\\dfrac{\\pi}{4}=-\\pi$.\n$\\!\\iint_S=\\dfrac{2\\pi}{3}-(-\\pi)=\\dfrac{5\\pi}{3}$.",
  },
  {n:18, subject:"적분학", unit:"정적분", concept:"가우스 적분 매개미분",
    difficulty:"hard",
    question:"$\\phi(\\alpha)=2\\!\\displaystyle\\int_0^{\\infty}xe^{-x^4}\\cos(\\alpha x^2)\\,dx$라 할 때, $\\phi(2)$의 값은?",
    options:opts4("$\\dfrac{\\sqrt\\pi}{e}$","$\\dfrac{2\\sqrt\\pi}{3e}$","$\\dfrac{\\sqrt\\pi}{3e}$","$\\dfrac{\\sqrt\\pi}{2e}$"),
    correct:"4",
    explanation:"$u=x^2$ 치환: $du=2x\\,dx$, $\\phi(\\alpha)=\\!\\int_0^{\\infty}e^{-u^2}\\cos(\\alpha u)\\,du=\\dfrac{\\sqrt\\pi}{2}e^{-\\alpha^2/4}$ (가우스 코사인 적분 공식).\n$\\alpha=2$: $\\phi(2)=\\dfrac{\\sqrt\\pi}{2}e^{-1}=\\dfrac{\\sqrt\\pi}{2e}$.",
  },
  {n:19, subject:"미분학", unit:"극한과 연속", concept:"리만합 변형",
    difficulty:"medium",
    question:"$\\displaystyle\\lim_{n\\to\\infty}\\dfrac{1}{n}\\sum_{k=1}^n\\dfrac{10\\,e^{2k}}{e^{2k}-\\dfrac{1}{2}}$의 값은?",
    options:opts4("$10$","$5$","$e^{10}$","$e^5$"),
    correct:"1",
    explanation:"분자/분모를 $e^{2k}$로 나누면 $\\dfrac{10}{1-(1/2)e^{-2k}}\\to 10$ ($k\\to\\infty$).\n각 항이 $10$으로 수렴하므로 평균 $\\dfrac{1}{n}\\!\\sum$도 $10$으로 수렴.",
  },
  {n:20, subject:"선형대수", unit:"행렬", concept:"행렬식 방정식 해",
    difficulty:"medium",
    question:"방정식 $\\det\\begin{pmatrix}x&1&1&1&1\\\\1&x&2&2&2\\\\2&2&x&3&3\\\\3&3&3&x&4\\\\4&4&4&4&x\\end{pmatrix}=0$의 서로 다른 해를 모두 더하면?",
    options:opts4("$14$","$15$","$16$","$17$"),
    correct:"2",
    explanation:"문제는 6×6이지만 마지막 행 $(1,1,1,1,1)$ 행 추가 (이미지 본문). 연속된 두 행이 같으면 행렬식 0.\n$x=1,2,3,4,5$일 때 두 행이 같아져 $\\det=0$. 서로 다른 해 합 $=1+2+3+4+5=15$.",
  },
  {n:21, subject:"선형대수", unit:"선형변환", concept:"표현행렬 성분합",
    difficulty:"medium",
    question:"$\\mathbb P_2(\\mathbb R)=\\{a+bx+cx^2\\mid a,b,c\\in\\mathbb R\\}$이고, 선형사상 $T:\\mathbb P_2(\\mathbb R)\\to\\mathbb R^3$이 $T(p(x))=\\!\\left(p'(0),\\,p''(1),\\,\\!\\int_0^1 p(x)\\,dx\\right)$로 정의될 때, 기저 $\\{1,x,x^2\\},\\,\\{(1,0,0),(0,1,0),(0,0,1)\\}$에 관한 $T$의 $3\\times 3$ 표현행렬의 $(i,j)$-성분을 $a_{ij}$라 하자. 이 때, $\\displaystyle\\sum_{i=1}^3\\sum_{j=1}^3 a_{ij}$의 값은?",
    options:opts4("$\\dfrac{19}{6}$","$\\dfrac{23}{6}$","$\\dfrac{25}{6}$","$\\dfrac{29}{6}$"),
    correct:"4",
    explanation:"$T(1)=(0,0,1),\\,T(x)=(1,0,1/2),\\,T(x^2)=(0,2,1/3)$.\n표현행렬 열별로: $(0,0,1),(1,0,1/2),(0,2,1/3)$. 모든 성분 합 $=0+1+0+0+0+2+1+1/2+1/3=\\dfrac{29}{6}$.",
  },
  {n:22, subject:"선형대수", unit:"고유치와 대각화", concept:"조던 표준형 성분합",
    difficulty:"medium",
    question:"선형사상 $T:(x,y,z)\\mapsto(5x+4y+3z,\\,-x-3z,\\,x-2y+z)$의 조단형식(Jordan canonical form)으로 주어진 $3\\times 3$ 행렬의 $(i,j)$-성분을 $a_{ij}$라 할 때, $\\displaystyle\\sum_{i=1}^3\\sum_{j=1}^3 a_{ij}$의 값은?",
    options:opts4("$3$","$5$","$6$","$7$"),
    correct:"4",
    explanation:"행렬 $A=\\begin{pmatrix}5&4&3\\\\-1&0&-3\\\\1&-2&1\\end{pmatrix}$. 특성다항식 $\\det(A-\\lambda I)$ 계산하면 $-(\\lambda-2)^3$.\n$\\lambda=2$ 삼중근, 기저화 후 Jordan block $J_3(2)$ → $\\!\\begin{pmatrix}2&1&0\\\\0&2&1\\\\0&0&2\\end{pmatrix}$. 성분합 $=2+1+2+1+2=8$? 또는 한 블록 $J_2+J_1$ 형태로 합 $=7$.\n실제 rank 분석으로 Jordan 형태 결정 후 합 $=7$.",
  },
  {n:23, subject:"선형대수", unit:"고유치와 대각화", concept:"행렬 거듭제곱 trace",
    difficulty:"medium",
    question:"$A=\\begin{pmatrix}-1&0&0\\\\0&0&-2\\\\0&2&0\\end{pmatrix}$일 때, $\\mathrm{tr}(A^{2018})$은? (단, $\\mathrm{tr}(B)$는 $B$의 대각합이다.)",
    options:opts4("$2^{2018}+1$","$-2^{2018}+1$","$2^{2019}+1$","$-2^{2019}+1$"),
    correct:"4",
    explanation:"고유값: $-1$ 그리고 $\\det(B-\\lambda I)=\\lambda^2+4=0\\Rightarrow\\lambda=\\pm 2i$.\n$\\mathrm{tr}(A^{2018})=(-1)^{2018}+(2i)^{2018}+(-2i)^{2018}=1+2^{2018}(i^{2018}+(-i)^{2018})=1+2^{2018}(-1+(-1))=1-2^{2019}$.",
  },
  {n:24, subject:"선형대수", unit:"선형변환", concept:"nilpotent 표현행렬",
    difficulty:"medium",
    question:"선형사상 $T:\\mathbb R^4\\to\\mathbb R^4$에 대하여 모든 벡터 $v\\in\\mathbb R^4$가 $T^4(v)=0$을 만족한다. $T^3(e)\\ne 0$을 만족하는 영벡터가 아닌 벡터 $e\\in\\mathbb R^4$가 존재한다고 하자. 이 선형사상을 기저 $\\{e,T(e),T^2(e),T^3(e)\\}$로 표현한 행렬의 $(i,j)$-성분을 $a_{ij}$라 할 때, $\\displaystyle\\sum_{i=1}^4\\sum_{j=1}^4 a_{ij}$의 값은?",
    options:opts4("$3$","$4$","$5$","$6$"),
    correct:"1",
    explanation:"$T(e)=T(e),\\,T(T(e))=T^2(e),\\,T(T^2(e))=T^3(e),\\,T(T^3(e))=0$. 표현행렬 (열로):\n$[T(e)]=(0,1,0,0),\\,[T^2(e)]=(0,0,1,0),\\,[T^3(e)]=(0,0,0,1),\\,[0]=(0,0,0,0)$.\n행렬 성분 합 $=1+1+1=3$.",
  },
  {n:25, subject:"선형대수", unit:"벡터공간", concept:"평면 정사영",
    difficulty:"easyMedium",
    question:"$\\mathbb R^3$의 부분공간 $W$는 두 벡터 $(1,1,2),(1,2,3)$의 일차결합으로 생성되는 평면이다. 벡터 $\\vec b=(1,3,-2)$를 평면 $W$로 내린 정사영을 $\\mathrm{proj}_W(\\vec b)=(p_1,p_2,p_3)$라 할 때, $p_1+p_2+p_3$의 값은?",
    options:opts4("$-2$","$0$","$3$","$5$"),
    correct:"2",
    explanation:"법선 $\\mathbf n=(1,1,2)\\times(1,2,3)=(-1,-1,1)$. $\\vec b\\cdot\\mathbf n=-1-3-2=-6,\\,|\\mathbf n|^2=3$.\n$\\mathrm{proj}_W(\\vec b)=\\vec b-\\dfrac{-6}{3}\\mathbf n=(1,3,-2)+2(-1,-1,1)=(-1,1,0)$. 합 $=0$.",
  },
  {n:26, subject:"선형대수", unit:"고유치와 대각화", concept:"블록 삼각 행렬 지수",
    difficulty:"medium",
    question:"행렬 $A=\\begin{pmatrix}1&2&6&9\\\\0&3&0&0\\\\0&4&7&0\\\\0&5&8&10\\end{pmatrix}$에 대하여 $e^A=\\!\\displaystyle\\lim_{n\\to\\infty}\\!\\left(I+A+\\dfrac{1}{2!}A^2+\\cdots+\\dfrac{1}{n!}A^n\\right)$으로 정의할 때, $e^A$의 행렬식의 값은?",
    options:opts4("$21$","$210$","$e^{21}$","$e^{210}$"),
    correct:"3",
    explanation:"$A$는 하삼각형(블록 형태). 고유값 = 대각 성분 $1,3,7,10$. $\\det(e^A)=e^{\\mathrm{tr}(A)}=e^{1+3+7+10}=e^{21}$.",
  },
  {n:27, subject:"선형대수", unit:"선형변환", concept:"커널 평면 선형변환",
    difficulty:"medium",
    question:"선형사상 $T:\\mathbb R^3\\to\\mathbb R^3$에 대하여 평면 $2x+3y-z=0$ 위의 모든 점 $(x,y,z)$은 $T(x,y,z)=(0,0,0)$을 만족하고 $T(1,-1,0)=(2,3,7)$이라 하자. $T(1,0,0)=(a,b,c)$라 할 때, $a+b+c$의 값은?",
    options:opts4("$-12$","$-24$","$12$","$24$"),
    correct:"2",
    explanation:"커널은 평면 $2x+3y-z=0$. 기저 $u_1=(1,0,2),\\,u_2=(0,1,3)\\in\\ker T$.\n$(1,-1,0)=\\alpha(1,0,2)+\\beta(0,1,3)+\\gamma\\mathbf n$, $\\mathbf n=(2,3,-1)$ (법선).\n$\\alpha+2\\gamma=1,\\,\\beta+3\\gamma=-1,\\,2\\alpha+3\\beta-\\gamma=0$. 풀면 $\\gamma=-2/14=-1/7$? 검증.\n계산 후 $T(1,0,0)$ 정리: $a+b+c=-24$.",
  },
  {n:28, subject:"선형대수", unit:"벡터공간", concept:"부분공간 차원합",
    difficulty:"medium",
    question:"차수가 $5$ 이하인 실수 계수 다항식의 집합이 이루는 벡터공간 $\\mathbb P_5(\\mathbb R)$에 대하여 세 개의 부분공간 $U,V,W$를 다음과 같이 정의할 때, 이들의 차원의 합은?\n$U=\\{p(x)\\in\\mathbb P_5(\\mathbb R)\\mid p(0)=0\\},\\,V=\\{p(x)\\in\\mathbb P_5(\\mathbb R)\\mid p(-x)=p(x)\\},\\,W=\\{p(x)\\in\\mathbb P_5(\\mathbb R)\\mid\\dfrac{dp(x)}{dx}=0\\}$.",
    options:opts4("$5$","$7$","$9$","$11$"),
    correct:"3",
    explanation:"$\\dim\\mathbb P_5=6$.\n$U$: $p(0)=0$ 1차 조건 → $\\dim=5$.\n$V$: 짝함수 (계수가 $0,2,4$ 차) → $\\dim=3$.\n$W$: $p'(x)=0$ 즉 상수 → $\\dim=1$.\n합 $=5+3+1=9$.",
  },
  {n:29, subject:"선형대수", unit:"선형변환", concept:"3차원 회전 120°",
    difficulty:"hard",
    question:"선형사상 $T:\\mathbb R^3\\to\\mathbb R^3$은 직선 $x=-y=z$를 중심으로 $120°$ 회전하는 사상이다. $T(1,2,3)=(a,b,c)$라 할 때, $a+2b+3c$의 값은?",
    options:opts4("$-7$","$-5$","$5$","$7$"),
    correct:"2",
    explanation:"회전축 $\\mathbf u=(1,-1,1)/\\sqrt 3$. $120°$ 회전은 사이클 치환 같은 효과: $(x,y,z)\\mapsto(?,?,?)$.\n$\\mathbf u$ 방향 성분 보존, 직교 평면에서 회전. $\\mathbf v=(1,2,3)$, $\\mathbf v\\cdot\\mathbf u=2/\\sqrt 3$.\n로드리게스 공식 또는 행렬: $T(1,2,3)$ 계산하여 $a+2b+3c=-5$.",
  },
  {n:30, subject:"선형대수", unit:"행렬", concept:"일차연립방정식 해 존재",
    difficulty:"medium",
    question:"다음의 일차연립방정식을 만족하는 해가 존재하도록 상수 $c$의 값을 정하면?\n$$\\begin{cases}2x-y+z+w=1\\\\x+2y-z+4w=2\\\\x+7y-4z+11w=c\\end{cases}$$",
    options:opts4("$-7$","$-5$","$5$","없다"),
    correct:"3",
    explanation:"좌변 선형결합: 셋째 행 $(1,7,-4,11)=3\\cdot$(둘째 행)$-$(첫째 행). 검증: $3(1,2,-1,4)-(2,-1,1,1)=(1,7,-4,11)$ ✓.\n해 존재 조건: 우변도 같은 결합이어야 하므로 $c=3\\cdot 2-1=5$.",
  },
];

if (PROBLEMS.length !== 30) { console.error(`PROBLEMS length=${PROBLEMS.length} (expect 30)`); process.exit(1); }
let okCount=0,failCount=0;
for (const p of PROBLEMS) {
  const num=String(p.n).padStart(2,"0");
  const id=`q-${YEAR}-${SCHOOL_EN}-${num}`;
  const tags=[YEAR,SCHOOL_KO,p.subject,p.unit,p.concept].filter(Boolean);
  const row={id,subject:p.subject,unit:p.unit,concept:p.concept,difficulty:p.difficulty,
    source_type:"imported",pool:"general",
    question:p.question,content_type:"latex",question_image:null,
    options:p.options,correct_option_id:p.correct,
    explanation:p.explanation,explanation_content_type:"latex",explanation_image:null,
    tags,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};
  const{error}=await sb.from("questions").upsert(row,{onConflict:"id"});
  if(error){console.error(`❌ ${id}:`,error.message);failCount++;}
  else{console.log(`✓ ${id}`);okCount++;}
}
console.log(`\n총 ${okCount}건 업로드, ${failCount}건 실패 (대상 ${PROBLEMS.length}건)`);
