// 2021년 중앙대(수학과) 편입수학 객관식 30문항 (4지선다)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR="2021", SCHOOL_KO="중앙대", SCHOOL_EN="cau";
const opts4 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:1, subject:"미분학", unit:"극한과 연속", concept:"테일러 급수 극한",
    difficulty:"medium",
    question:"$\\displaystyle\\lim_{x\\to 0}\\dfrac{\\sqrt{a+\\tan x}-\\sqrt{a+\\sin x}}{x^3}=\\dfrac{1}{32}$이 되도록 하는 양수 $a$의 값은?",
    options:opts4("$8$","$16$","$32$","$64$"),
    correct:"4",
    explanation:"분자 유리화: $\\dfrac{\\tan x-\\sin x}{x^3(\\sqrt{a+\\tan x}+\\sqrt{a+\\sin x})}$.\n$\\tan x-\\sin x\\sim\\dfrac{x^3}{2}$이므로 극한 $=\\dfrac{1/2}{2\\sqrt a}=\\dfrac{1}{4\\sqrt a}=\\dfrac{1}{32}$.\n$\\sqrt a=8\\Rightarrow a=64$.",
  },
  {n:2, subject:"선형대수", unit:"고유치와 대각화", concept:"trace 거듭제곱 합",
    difficulty:"medium",
    question:"행렬 $A=\\begin{pmatrix}-1&2\\\\-1&3\\end{pmatrix}$과 $x=\\dfrac{1}{4}$에 대하여 $\\displaystyle\\sum_{k=0}^{\\infty}\\mathrm{tr}(A^k)\\,x^{k-1}$의 값은? (단, $\\mathrm{tr}(B)$는 정사각행렬 $B$의 대각합이고 $A^0=\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix},\\,A^k=A^{k-1}\\cdot A$이다.)",
    options:opts4("$\\dfrac{95}{8}$","$\\dfrac{96}{7}$","$\\dfrac{97}{6}$","$\\dfrac{98}{5}$"),
    correct:"2",
    explanation:"고유값 $\\lambda^2-2\\lambda-1=0\\Rightarrow\\lambda=1\\pm\\sqrt 2$. $\\mathrm{tr}(A^k)=\\lambda_1^k+\\lambda_2^k$.\n$\\!\\sum\\mathrm{tr}(A^k)x^{k-1}=\\dfrac{1}{x}\\!\\left[\\dfrac{1}{1-\\lambda_1 x}+\\dfrac{1}{1-\\lambda_2 x}\\right]=\\dfrac{1}{x}\\cdot\\dfrac{2-(\\lambda_1+\\lambda_2)x}{1-(\\lambda_1+\\lambda_2)x+\\lambda_1\\lambda_2 x^2}$.\n$x=1/4$: 분자 $=2-2/4=3/2$, 분모 $=1-1/2-1/16=7/16$. $\\dfrac{1}{1/4}\\cdot\\dfrac{3/2}{7/16}=4\\cdot\\dfrac{24}{7}=\\dfrac{96}{7}$.",
  },
  {n:3, subject:"선형대수", unit:"행렬", concept:"행렬식 변환",
    difficulty:"medium",
    question:"정사각행렬 $A=\\begin{pmatrix}a_1&b_1&c_1&d_1\\\\a_2&b_2&c_2&d_2\\\\a_3&b_3&c_3&d_3\\\\a_4&b_4&c_4&d_4\\end{pmatrix}$에 대하여 다음의 방정식을 만족하는 상수 $k$의 값은? (단, $\\det B$는 행렬식이다.)\n$$\\det\\!\\begin{pmatrix}b_1+c_1+d_1&b_2+c_2+d_2&b_3+c_3+d_3&b_4+c_4+d_4\\\\a_1+c_1+d_1&a_2+c_2+d_2&a_3+c_3+d_3&a_4+c_4+d_4\\\\a_1+b_1+d_1&a_2+b_2+d_2&a_3+b_3+d_3&a_4+b_4+d_4\\\\a_1+b_1+c_1&a_2+b_2+c_2&a_3+b_3+c_3&a_4+b_4+c_4\\end{pmatrix}=k\\cdot\\det(A)$$",
    options:opts4("$-3$","$-1$","$1$","$3$"),
    correct:"1",
    explanation:"새 행렬은 $A^T$의 각 행에서 자기 자신을 뺀 모든 행의 합 형태. 변환행렬은 $J-I$ ($J$는 모든 성분 $1$, 크기 $4$).\n$J-I$의 고유값: $4-1=3$ (한 번), $-1$ (세 번). $\\det(J-I)=3\\cdot(-1)^3=-3$.\n$\\det A^T=\\det A$이므로 $k=-3$.",
  },
  {n:4, subject:"선형대수", unit:"행렬", concept:"무한해 조건",
    difficulty:"medium",
    question:"$x,y,z$에 대한 다음의 일차연립방정식이 무한히 많은 해를 갖도록 하는 상수 $a$의 값을 모두 곱하면?\n$$\\begin{cases}x+y+2z=-3\\\\2x+y+3z=-2a\\\\-3x+4y+z=a^2\\end{cases}$$",
    options:opts4("$14$","$6$","$-9$","$33$"),
    correct:"4",
    explanation:"행간소: $R_2-2R_1=(0,-1,-1,-2a+6)$, $R_3+3R_1=(0,7,7,a^2-9)$, $R_3+7R_2=(0,0,0,a^2-14a+33)$.\n무한해 조건: $a^2-14a+33=0\\Rightarrow a=11$ 또는 $3$. 곱 $=33$.",
  },
  {n:5, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"접선 내적 최소",
    difficulty:"hard",
    question:"직선 $\\dfrac{x}{3}+\\dfrac{y}{2}=1$ 위의 점 $P$를 통과하는 두 직선이 각각 점 $A$와 점 $B$에서 원 $x^2+y^2=1$에 접한다. 내적 $\\overrightarrow{PA}\\cdot\\overrightarrow{PB}$의 최솟값은?",
    options:opts4("$\\dfrac{115}{234}$","$\\dfrac{511}{432}$","$\\dfrac{151}{342}$","$\\dfrac{151}{324}$"),
    correct:"1",
    explanation:"$|PA|=|PB|=\\sqrt{|OP|^2-1}$, 사이각 $2\\alpha$에서 $\\sin\\alpha=1/|OP|$.\n$\\overrightarrow{PA}\\cdot\\overrightarrow{PB}=|PA|^2\\cos 2\\alpha=(d-1)(d-2)/d$ ($d=|OP|^2$).\n원점에서 직선까지 거리 $=\\dfrac{1}{\\sqrt{1/9+1/4}}=\\dfrac{6}{\\sqrt{13}}$, $d_{\\min}=\\dfrac{36}{13}$.\n$f(d)=d-3+2/d$ 단조증가 ($d>\\sqrt 2$). $f(36/13)=\\dfrac{36}{13}-3+\\dfrac{13}{18}=\\dfrac{115}{234}$.",
  },
  {n:6, subject:"선형대수", unit:"선형변환", concept:"R²→R³ 선형변환",
    difficulty:"easyMedium",
    question:"선형사상 $T:\\mathbb R^2\\to\\mathbb R^3$가 $T(-1,1)=(2,9,0),\\,T(0,1)=(3,3,4),\\,T(a,b)=(0,21,-8)$을 만족할 때, $a+b$의 값은?",
    options:opts4("$-2$","$0$","$1$","$3$"),
    correct:"1",
    explanation:"$T(1,0)=T(0,1)-T(-1,1)=(1,-6,4)$.\n$T(a,b)=a(1,-6,4)+b(3,3,4)=(a+3b,-6a+3b,4a+4b)=(0,21,-8)$.\n$a+3b=0,\\,-6a+3b=21\\Rightarrow a=-3,\\,b=1$. $a+b=-2$.",
  },
  {n:7, subject:"적분학", unit:"정적분", concept:"삼각치환 적분",
    difficulty:"medium",
    question:"$\\displaystyle\\int_0^{\\pi/6}\\dfrac{\\sin x\\cos x}{\\sin^4 x+\\cos^4 x}\\,dx=\\alpha$라 할 때, $\\sin(2\\alpha)$의 값은?",
    options:opts4("$\\dfrac{\\sqrt 2}{2}$","$\\dfrac{\\sqrt 3}{3}$","$\\dfrac{\\sqrt 5}{5}$","$\\dfrac{\\sqrt{10}}{10}$"),
    correct:"4",
    explanation:"분자 $\\dfrac{1}{2}\\sin 2x$, 분모 $\\dfrac{1}{2}(2-\\sin^2 2x)$. $u=\\cos 2x$ 치환: $\\!\\int\\dfrac{-du/2}{1+u^2}$.\n$\\alpha=\\dfrac{1}{2}(\\arctan 1-\\arctan(1/2))=\\dfrac{1}{2}(\\pi/4-\\arctan 1/2)$.\n$2\\alpha=\\pi/4-\\arctan(1/2)$. $\\sin 2\\alpha=\\dfrac{\\sqrt 2}{2}\\cdot\\dfrac{2}{\\sqrt 5}-\\dfrac{\\sqrt 2}{2}\\cdot\\dfrac{1}{\\sqrt 5}=\\dfrac{\\sqrt 2}{2\\sqrt 5}=\\dfrac{\\sqrt{10}}{10}$.",
  },
  {n:8, subject:"다변수함수", unit:"선적분과 면적분", concept:"그린정리",
    difficulty:"medium",
    question:"곡선 $C$는 점 $(0,0)$을 출발하여 점 $(0,4)$와 점 $(2,4)$를 차례로 거쳐서 점 $(0,0)$으로 돌아오도록 향(orientation)이 주어진 삼각형의 둘레이다. 선적분 $\\displaystyle\\int_C(y\\cos x-xy\\sin x)\\,dx+(xy+x\\cos x)\\,dy$의 값은?",
    options:opts4("$-\\dfrac{16}{3}$","$-\\dfrac{32}{3}$","$\\dfrac{32}{3}$","$\\dfrac{16}{3}$"),
    correct:"2",
    explanation:"$Q_x-P_y=(y+\\cos x-x\\sin x)-(\\cos x-x\\sin x)=y$.\n경로는 시계방향이므로 $-\\!\\iint_D y\\,dA$. 영역 $D=\\{(x,y):0\\le x\\le 2,\\,2x\\le y\\le 4\\}$.\n$\\!\\iint_D y\\,dA=\\!\\int_0^4\\!\\!\\int_0^{y/2}y\\,dx\\,dy=\\!\\int_0^4\\dfrac{y^2}{2}dy=\\dfrac{32}{3}$.\n결과 $=-\\dfrac{32}{3}$.",
  },
  {n:9, subject:"미분학", unit:"도함수", concept:"이항급수 계수",
    difficulty:"easy",
    question:"함수 $f(x)=(1+x^5)^{30}$에 대하여 $\\dfrac{f^{(10)}(0)}{10!}$의 값은?",
    options:opts4("$345$","$435$","$543$","$534$"),
    correct:"2",
    explanation:"$\\dfrac{f^{(10)}(0)}{10!}$은 $x^{10}$ 항의 계수.\n$(1+x^5)^{30}=\\!\\sum\\binom{30}{k}x^{5k}$. $5k=10\\Rightarrow k=2$. 계수 $=\\binom{30}{2}=435$.",
  },
  {n:10, subject:"다변수함수", unit:"곡선과 곡면", concept:"평면 자른 콘 영역",
    difficulty:"hard",
    question:"곡면 $x^2+y^2=\\dfrac{z^2}{4}$과 평면 $x+y+z=1$이 만나서 이루는 곡선이 평면 $x+y+z=1$에서 둘러싸는 영역의 넓이는?",
    options:opts4("$\\dfrac{\\pi}{\\sqrt 2}$","$\\sqrt{\\dfrac{2}{3}}\\,\\pi$","$\\pi$","$\\sqrt{\\dfrac{3}{2}}\\,\\pi$"),
    correct:"4",
    explanation:"평면 $x+y+z=1$의 매개변수화 후 콘 방정식 대입하여 ellipse 방정식을 얻는다.\n타원의 두 반축을 구해 면적 $\\pi ab$ 계산하면 $\\sqrt{3/2}\\,\\pi$가 된다.",
  },
  {n:11, subject:"적분학", unit:"급수의 수렴/발산", concept:"멱급수 수렴반경",
    difficulty:"medium",
    question:"두 급수 $\\displaystyle\\sum_{n=1}^{\\infty}c_n x^n$과 $\\displaystyle\\sum_{n=1}^{\\infty}d_n x^n$의 수렴반경이 각각 $2$와 $3$일 때 급수 $\\displaystyle\\sum_{n=1}^{\\infty}\\!\\left(\\dfrac{c_n}{5^n}+\\dfrac{d_n}{4^n}\\right)x^n$의 수렴반경은?",
    options:opts4("$10$","$20$","$25$","$50$"),
    correct:"1",
    explanation:"$\\!\\sum(c_n/5^n)x^n=\\!\\sum c_n(x/5)^n$ 수렴 $|x/5|<2\\Rightarrow|x|<10$.\n$\\!\\sum(d_n/4^n)x^n=\\!\\sum d_n(x/4)^n$ 수렴 $|x|<12$.\n합의 수렴반경 $=\\min(10,12)=10$.",
  },
  {n:12, subject:"선형대수", unit:"선형변환", concept:"커널 차원 조건",
    difficulty:"medium",
    question:"다음의 선형사상 $T:\\mathbb R^4\\to\\mathbb R^3$가 차원이 $2$인 핵(kernel)을 갖도록 $a$를 정하면?\n$$T(x,y,z,w)=(3x-3y-z-4w,\\,2x-7y-6w,\\,-x+2y+az+2w)$$",
    options:opts4("$\\dfrac{1}{3}$","$\\dfrac{2}{3}$","$\\dfrac{1}{5}$","$\\dfrac{4}{5}$"),
    correct:"3",
    explanation:"$\\dim\\ker T=2\\Rightarrow\\mathrm{rank}\\,T=4-2=2$. 행렬 $A=\\begin{pmatrix}3&-3&-1&-4\\\\2&-7&0&-6\\\\-1&2&a&2\\end{pmatrix}$의 모든 $3\\times 3$ 부분행렬식 $=0$이어야 한다.\n조건을 풀면 $a=\\dfrac{1}{5}$.",
  },
  {n:13, subject:"적분학", unit:"정적분", concept:"곡선 길이",
    difficulty:"medium",
    question:"$0\\le x\\le 1$에서 정의된 곡선 $y=\\sin^{-1}x+\\sqrt{1-x^2}$의 길이는?",
    options:opts4("$\\sqrt 2$","$2\\sqrt 2$","$2-\\sqrt 2$","$4-2\\sqrt 2$"),
    correct:"4",
    explanation:"$y'=\\dfrac{1-x}{\\sqrt{1-x^2}}=\\sqrt{\\dfrac{1-x}{1+x}}$. $1+y'^2=\\dfrac{2}{1+x}$.\n길이 $=\\!\\int_0^1\\sqrt{\\dfrac{2}{1+x}}\\,dx=\\sqrt 2\\,[2\\sqrt{1+x}]_0^1=\\sqrt 2(2\\sqrt 2-2)=4-2\\sqrt 2$.",
  },
  {n:14, subject:"적분학", unit:"부정적분", concept:"부분분수 잔차 조건",
    difficulty:"hard",
    question:"$f(0)=1,\\,f(1)=10$을 만족하는 이차함수 $f(x)$에 대하여 $\\displaystyle\\int\\dfrac{f(x)}{x^3(x+1)^2}\\,dx$가 유리함수일 때, $f(2)$의 값은?",
    options:opts4("$9$","$-9$","$-19$","$29$"),
    correct:"4",
    explanation:"$f(x)=ax^2+bx+1$, $a+b=9$. 부분분수 $\\dfrac{A}{x}+\\dfrac{B}{x^2}+\\dfrac{C}{x^3}+\\dfrac{D}{x+1}+\\dfrac{E}{(x+1)^2}$에서 유리함수 조건은 $A=D=0$.\n잔차 계산: $A=a-2b+3=0$. $a+b=9$와 연립: $b=4,\\,a=5$. $f(x)=5x^2+4x+1$.\n$f(2)=20+8+1=29$.",
  },
  {n:15, subject:"적분학", unit:"정적분", concept:"우함수·주기함수 적분",
    difficulty:"medium",
    question:"모든 실수 $x$에 대하여 $f(-x)=f(x),\\,f(x+3)=f(x)$를 만족하는 연속함수 $f(x)$에 대하여 $\\displaystyle\\int_0^2 f(x)\\,dx=5$와 $\\displaystyle\\int_0^3 f(x)\\,dx=7$이 성립한다. 이때, $\\displaystyle\\int_{-4}^9 f(x)\\,dx$의 값은?",
    options:opts4("$26$","$28$","$30$","$32$"),
    correct:"3",
    explanation:"주기 $3$이고 한 주기 적분 $7$. $9-(-4)=13=4\\cdot 3+1$이므로 $4$주기 + 자투리 $1$.\n자투리 구간 $[8,9]$ → $\\!\\int_8^9 f=\\!\\int_2^3 f=7-5=2$.\n총합 $=4\\cdot 7+2=30$.",
  },
  {n:16, subject:"다변수함수", unit:"선적분과 면적분", concept:"호 길이 선적분",
    difficulty:"easyMedium",
    question:"곡선 $C=\\{(x,y)\\in\\mathbb R^2\\mid x=\\cos t,\\,y=\\sin t,\\,0\\le t\\le\\pi/4\\}$일 때 선적분 $\\displaystyle\\int_C\\dfrac{1}{x}\\,ds$의 값은? (단, $s$는 호의 길이를 매개화한 것이다.)",
    options:opts4("$\\ln(\\sqrt 3+1)$","$\\ln(\\sqrt 2+1)$","$\\ln\\sqrt 3$","$\\ln\\sqrt 2$"),
    correct:"2",
    explanation:"$ds=dt$, $1/x=\\sec t$. $\\!\\int_0^{\\pi/4}\\sec t\\,dt=[\\ln|\\sec t+\\tan t|]_0^{\\pi/4}=\\ln(\\sqrt 2+1)$.",
  },
  {n:17, subject:"미분학", unit:"도함수와 그래프", concept:"내접 직사각형 최댓값",
    difficulty:"medium",
    question:"세 직선 $x=0,\\,y=0,\\,\\dfrac{x}{2}+y=1$로 둘러싸인 삼각형에 내접하는 직사각형 중 한 변이 직선 $\\dfrac{x}{2}+y=1$ 위에 놓인 직사각형의 넓이의 최댓값은?",
    options:opts4("$\\dfrac{1}{4}$","$\\dfrac{\\sqrt 2}{4}$","$\\dfrac{1}{2}$","$\\dfrac{\\sqrt 2}{2}$"),
    correct:"3",
    explanation:"빗변 매개화 후 직사각형 한 변 길이와 빗변에 수직 거리를 변수로 두고 면적 함수 최대화.\n계산하면 최댓값 $\\dfrac{1}{2}$.",
  },
  {n:18, subject:"적분학", unit:"정적분", concept:"이중리만합",
    difficulty:"hard",
    question:"극한 $\\displaystyle\\lim_{m,n\\to\\infty}\\sum_{k=1}^n\\sum_{j=1}^m\\dfrac{\\pi k}{n}\\sin\\!\\left(\\dfrac{\\pi jk}{4mn}\\right)\\dfrac{1}{mn}$의 값은?",
    options:opts4("$2\\!\\left(1-\\dfrac{2\\sqrt 2}{\\pi}\\right)$","$4\\!\\left(1-\\dfrac{\\sqrt 2}{\\pi}\\right)$","$4\\!\\left(1-\\dfrac{2\\sqrt 2}{\\pi}\\right)$","$2\\!\\left(1-\\dfrac{\\sqrt 2}{\\pi}\\right)$"),
    correct:"3",
    explanation:"$u=j/m,\\,v=k/n$ 리만합. $\\!\\int_0^1\\!\\!\\int_0^1\\pi v\\sin(\\pi uv/4)\\,du\\,dv$.\n$u$ 적분: $\\!\\int_0^1\\pi v\\sin(\\pi uv/4)du=4(1-\\cos(\\pi v/4))$.\n$v$ 적분: $\\!\\int_0^1 4(1-\\cos(\\pi v/4))dv=4-\\dfrac{16\\sqrt 2}{\\pi\\cdot 2}=4\\!\\left(1-\\dfrac{2\\sqrt 2}{\\pi}\\right)$.",
  },
  {n:19, subject:"미분학", unit:"극한과 연속", concept:"테일러 급수 극한",
    difficulty:"medium",
    question:"극한 $\\displaystyle\\lim_{x\\to 0}\\dfrac{6x^2\\sin x^3-6x^5+x^{11}}{x^{17}}$의 값은?",
    options:opts4("$\\dfrac{1}{10}$","$\\dfrac{1}{15}$","$\\dfrac{1}{20}$","$\\dfrac{1}{60}$"),
    correct:"3",
    explanation:"$\\sin x^3=x^3-\\dfrac{x^9}{6}+\\dfrac{x^{15}}{120}-\\cdots$.\n$6x^2\\sin x^3=6x^5-x^{11}+\\dfrac{x^{17}}{20}-\\cdots$.\n분자 $=6x^5-x^{11}+\\dfrac{x^{17}}{20}-6x^5+x^{11}=\\dfrac{x^{17}}{20}-\\cdots$.\n극한 $=\\dfrac{1}{20}$.",
  },
  {n:20, subject:"다변수함수", unit:"곡선과 곡면", concept:"비스듬한 원뿔 옆넓이",
    difficulty:"hard",
    question:"좌표공간에서 평면 $z=2-\\dfrac{x}{2}$와 곡면 $z=\\sqrt{x^2+y^2}$으로 둘러싸인 비스듬한 원뿔의 옆면의 넓이를 구하면?",
    options:opts4("$\\dfrac{32\\sqrt 6}{9}\\pi$","$\\dfrac{16\\sqrt 6}{9}\\pi$","$\\dfrac{64\\sqrt 6}{9}\\pi$","$\\dfrac{64\\sqrt 3}{9}\\pi$"),
    correct:"1",
    explanation:"콘 $z=\\sqrt{x^2+y^2}$의 옆면 면적 미적분 $dS=\\sqrt 2\\,dA$ (밑 영역 $D$).\n평면 절단 영역 $D$의 면적 + 매개화 후 적분으로 $\\dfrac{32\\sqrt 6}{9}\\pi$ 도출.",
  },
  {n:21, subject:"선형대수", unit:"고유치와 대각화", concept:"대칭행렬 합성 norm",
    difficulty:"hard",
    question:"$T:\\mathbb R^3\\to\\mathbb R^3$는 $T(x,y,z)=(3x+y+2z,\\,x+y,\\,2x+4z)$로 정의된 선형사상이다. 구 $x^2+y^2+z^2=1$ 위의 점 $(x,y,z)$에 대하여 $\\|(T\\circ T)(x,y,z)\\|$의 최댓값은? (단, $\\|(a,b,c)\\|=\\sqrt{a^2+b^2+c^2}$.)",
    options:opts4("$16$","$16+6\\sqrt 7$","$16+8\\sqrt 7$","$16+9\\sqrt 7$"),
    correct:"2",
    explanation:"행렬 $A=\\begin{pmatrix}3&1&2\\\\1&1&0\\\\2&0&4\\end{pmatrix}$ (대칭). 특성 $\\lambda^3-8\\lambda^2+14\\lambda-4=0=(\\lambda-2)(\\lambda^2-6\\lambda+2)$.\n$\\lambda=2,\\,3\\pm\\sqrt 7$. $\\lambda_{\\max}=3+\\sqrt 7$.\n$\\|A^2 v\\|_{\\max}=\\lambda_{\\max}^2=(3+\\sqrt 7)^2=16+6\\sqrt 7$.",
  },
  {n:22, subject:"적분학", unit:"정적분", concept:"표준정규 절반 모멘트",
    difficulty:"medium",
    question:"$f(x)=\\dfrac{1}{\\sqrt{2\\pi}}e^{-x^2/2}$에 대하여 $\\displaystyle\\int_0^{\\infty}\\!\\!\\int_0^{\\infty}(x+2y)^2 f(x)f(y)\\,dxdy$의 값은?",
    options:opts4("$\\dfrac{5}{4}+\\dfrac{4}{\\pi}$","$\\dfrac{5}{4}+\\dfrac{2}{\\pi}$","$\\dfrac{5}{2}+\\dfrac{4}{\\pi}$","$\\dfrac{5}{2}+\\dfrac{2}{\\pi}$"),
    correct:"2",
    explanation:"$\\!\\int_0^\\infty f=1/2,\\,\\!\\int_0^\\infty x^2 f=1/2,\\,\\!\\int_0^\\infty x f=1/\\sqrt{2\\pi}$.\n$(x+2y)^2=x^2+4xy+4y^2$. 적분 $=\\dfrac{1}{2}\\cdot\\dfrac{1}{2}+4\\cdot\\dfrac{1}{2\\pi}+4\\cdot\\dfrac{1}{2}\\cdot\\dfrac{1}{2}=\\dfrac{1}{4}+\\dfrac{2}{\\pi}+1=\\dfrac{5}{4}+\\dfrac{2}{\\pi}$.",
  },
  {n:23, subject:"선형대수", unit:"고유치와 대각화", concept:"대각화 후 거듭제곱",
    difficulty:"hard",
    question:"선형사상 $T:\\mathbb R^3\\to\\mathbb P_2(x),\\,T(e_1)=1-x^2,\\,T(e_2)=x+x^2,\\,T(e_3)=-1+x$를 $\\mathbb R^3$의 순서기저 $\\{e_1,e_2,e_3\\}$와 $\\mathbb P_2(x)$의 순서기저 $\\{1,x,x^2\\}$에 대하여 표현한 $3\\times 3$행렬을 $A$라 하자. $A^{100}\\begin{pmatrix}a_1\\\\a_2\\\\a_3\\end{pmatrix}=\\begin{pmatrix}0\\\\0\\\\1\\end{pmatrix}$이라 할 때, $a_1+a_2+a_3$의 값은?",
    options:opts4("$\\dfrac{1}{3}+\\dfrac{1}{3\\cdot 2^{99}}$","$\\dfrac{1}{3}+\\dfrac{1}{3\\cdot 2^{100}}$","$\\dfrac{2}{3}+\\dfrac{1}{3\\cdot 2^{100}}$","$\\dfrac{2}{3}+\\dfrac{1}{3\\cdot 2^{99}}$"),
    correct:"3",
    explanation:"$A=\\begin{pmatrix}1&0&-1\\\\0&1&1\\\\-1&1&0\\end{pmatrix}$, 특성다항식 $(1-\\lambda)(\\lambda-2)(\\lambda+1)=0$. 고유값 $1,2,-1$.\n고유벡터 $v_1=(1,1,0),\\,v_2=(-1,1,1),\\,v_3=(1,-1,2)$.\n$(a_1,a_2,a_3)=\\alpha v_1+\\beta v_2+\\gamma v_3$, $A^{100}(\\cdots)=\\alpha v_1+2^{100}\\beta v_2+\\gamma v_3=(0,0,1)$.\n풀면 $\\alpha=0,\\,\\beta=\\dfrac{1}{3\\cdot 2^{100}},\\,\\gamma=\\dfrac{1}{3}$.\n합 $=\\dfrac{2}{3}+\\dfrac{1}{3\\cdot 2^{100}}$.",
  },
  {n:24, subject:"선형대수", unit:"행렬", concept:"순환 행렬식",
    difficulty:"medium",
    question:"함수 $f(x)=\\det\\!\\begin{pmatrix}x&x-1&x-2&x-3\\\\x-1&x-2&x-3&x\\\\x-2&x-3&x&x-1\\\\x-3&x&x-1&x-2\\end{pmatrix}$이라 할 때, 다음 중 $f(x)=0$의 실근은?",
    options:opts4("$-3$","$3$","$-\\dfrac{3}{2}$","$\\dfrac{3}{2}$"),
    correct:"4",
    explanation:"각 행 성분의 합 $=4x-6$. 첫째 열에 다른 모든 열을 더하면 첫 열이 $(4x-6,4x-6,4x-6,4x-6)^T$.\n$\\det=0$이려면 $4x-6=0\\Rightarrow x=\\dfrac{3}{2}$이 한 실근.",
  },
  {n:25, subject:"적분학", unit:"급수의 수렴/발산", concept:"수렴 명제 진위",
    difficulty:"medium",
    question:"값이 실수인 두 수열 $a_n,b_n\\,(n=0,1,2,\\ldots)$에 대하여 다음 <보기> 중 참인 명제는 몇 개인가?\n(가) $\\!\\sum a_n,\\!\\sum b_n$이 둘 다 수렴하면 $\\!\\lim_{n\\to\\infty}a_nb_n=0$이다.\n(나) $\\!\\sum a_n,\\!\\sum b_n$이 둘 다 수렴하면 $\\!\\sum a_nb_n$도 수렴한다.\n(다) $\\!\\sum a_n,\\!\\sum b_n$이 둘 다 발산하면 $\\!\\sum a_nb_n$도 발산한다.\n(라) $\\!\\sum a_n$이 수렴하고 $\\!\\sum b_n$이 발산하며, 모든 $n$에 대하여 $b_n\\ne 0$이면 $\\!\\sum\\dfrac{a_n}{b_n}$은 수렴한다.",
    options:opts4("$0$ 개","$1$ 개","$2$ 개","$3$ 개"),
    correct:"2",
    explanation:"(가) 수렴 → $a_n,b_n\\to 0$ → 곱 $\\to 0$. 참.\n(나) 반례 $a_n=b_n=(-1)^n/\\sqrt n$: $\\!\\sum a_nb_n=\\!\\sum 1/n$ 발산. 거짓.\n(다) 반례 $a_n=1/n,\\,b_n=-1/n$ 둘 다 발산이지만 곱 $-1/n^2$ 수렴. 거짓.\n(라) 반례 $a_n=1/n^2,\\,b_n=1/n$: $a_n/b_n=1/n$ 발산. 거짓.\n참 $1$개.",
  },
  {n:26, subject:"적분학", unit:"정적분", concept:"y축 회전 부피",
    difficulty:"easyMedium",
    question:"좌표평면에서 $y=\\dfrac{x+3}{x^3},\\,x=1,\\,x=4,\\,y=0$으로 둘러싸인 영역을 $y$축을 중심으로 회전시킬 때 생기는 입체의 부피는?",
    options:opts4("$\\dfrac{69}{16}\\pi$","$\\dfrac{69}{8}\\pi$","$2\\pi\\!\\left(\\ln 4+\\dfrac{9}{4}\\right)$","$2\\pi\\!\\left(\\ln 16+\\dfrac{9}{2}\\right)$"),
    correct:"3",
    explanation:"원통껍질: $V=2\\pi\\!\\displaystyle\\int_1^4 x\\cdot\\dfrac{x+3}{x^3}\\,dx=2\\pi\\!\\int_1^4\\!\\left(\\dfrac{1}{x}+\\dfrac{3}{x^2}\\right)dx$.\n$=2\\pi[\\ln x-3/x]_1^4=2\\pi(\\ln 4-3/4+3)=2\\pi(\\ln 4+9/4)$.",
  },
  {n:27, subject:"미분학", unit:"도함수", concept:"역함수 2계 미분",
    difficulty:"easyMedium",
    question:"$f(x)=3x+2\\cos x$일 때, $(f^{-1})''(2)$의 값은?",
    options:opts4("$\\dfrac{2}{27}$","$\\dfrac{2}{9}$","$-\\dfrac{2}{9}$","$-\\dfrac{2}{27}$"),
    correct:"1",
    explanation:"$f(0)=2$. $f'(x)=3-2\\sin x$, $f'(0)=3$. $f''(x)=-2\\cos x$, $f''(0)=-2$.\n$(f^{-1})''(y)=-\\dfrac{f''(x)}{(f'(x))^3}=-\\dfrac{-2}{27}=\\dfrac{2}{27}$.",
  },
  {n:28, subject:"적분학", unit:"급수의 수렴/발산", concept:"arctan 망원합",
    difficulty:"medium",
    question:"$\\displaystyle\\sum_{n=1}^{\\infty}\\tan^{-1}\\!\\left(\\dfrac{1/(n(n+1))}{1+1/(n(n+1))}\\right)$의 값은?",
    options:opts4("$\\dfrac{\\pi}{2}$","$\\dfrac{\\pi}{3}$","$\\dfrac{\\pi}{4}$","$\\dfrac{\\pi}{6}$"),
    correct:"3",
    explanation:"분수 정리: $\\dfrac{1/(n(n+1))}{1+1/(n(n+1))}=\\dfrac{1}{n^2+n+1}=\\dfrac{(n+1)-n}{1+n(n+1)}$.\n$\\arctan$ 차 공식: $=\\arctan(n+1)-\\arctan n$. 망원합 $=\\!\\lim_{N\\to\\infty}\\arctan(N+1)-\\arctan 1=\\dfrac{\\pi}{2}-\\dfrac{\\pi}{4}=\\dfrac{\\pi}{4}$.",
  },
  {n:29, subject:"적분학", unit:"급수의 수렴/발산", concept:"기하급수·arctan 곱",
    difficulty:"medium",
    question:"$\\displaystyle\\sum_{n=0}^{\\infty}(-1)^n\\dfrac{1}{(\\sqrt 3)^{2n}}=a,\\,\\displaystyle\\sum_{n=0}^{\\infty}(-1)^n\\dfrac{1}{(2n+1)(\\sqrt 3)^{2n+1}}=b$라 할 때, $ab$의 값은?",
    options:opts4("$\\dfrac{3}{4}\\pi$","$\\dfrac{\\pi}{4}$","$\\dfrac{\\pi}{6}$","$\\dfrac{\\pi}{8}$"),
    correct:"4",
    explanation:"$a=\\!\\sum(-1/3)^n=\\dfrac{1}{1+1/3}=\\dfrac{3}{4}$.\n$b=\\dfrac{1}{\\sqrt 3}\\!\\sum\\dfrac{(-1)^n}{(2n+1)\\cdot 3^n}=\\arctan(1/\\sqrt 3)=\\dfrac{\\pi}{6}$.\n$ab=\\dfrac{3}{4}\\cdot\\dfrac{\\pi}{6}=\\dfrac{\\pi}{8}$.",
  },
  {n:30, subject:"다변수함수", unit:"선적분과 면적분", concept:"원판 유량",
    difficulty:"easyMedium",
    question:"벡터장 $F$는 $F(x,y,z)=(xy+xe^{z^2},\\,-2y^2-ye^{z^2},\\,z+x^2)$이고 $S$는 향이 $(0,0,-1)$로 주어진 원판 $S=\\{(x,y,z)\\in\\mathbb R^3\\mid x^2+y^2\\le 1,\\,z=0\\}$일 때, 유량 $\\displaystyle\\iint_S F\\cdot dS$의 값은?",
    options:opts4("$-\\dfrac{\\pi}{4}$","$-\\dfrac{\\pi}{2}$","$-\\pi$","$0$"),
    correct:"1",
    explanation:"$z=0$에서 $e^{z^2}=1$, $F\\cdot(0,0,-1)=-(z+x^2)|_{z=0}=-x^2$.\n$\\!\\iint_D(-x^2)dA=-\\!\\int_0^{2\\pi}\\!\\!\\int_0^1 r^2\\cos^2\\theta\\cdot r\\,dr\\,d\\theta=-\\pi\\cdot\\dfrac{1}{4}=-\\dfrac{\\pi}{4}$.",
  },
];

if (PROBLEMS.length !== 30) { console.error(`PROBLEMS length=${PROBLEMS.length} (expect 30)`); process.exit(1); }
let okCount=0,failCount=0;
for (const p of PROBLEMS) {
  const num=String(p.n).padStart(2,"0");
  const id=`q-${YEAR}-${SCHOOL_EN}-${num}`;
  const tags=[YEAR,SCHOOL_KO,p.subject,p.unit,p.concept].filter(Boolean);
  const row={id,subject:p.subject,unit:p.unit,concept:p.concept,difficulty:p.difficulty,
    source_type:"imported",pool:"general",
    question:p.question,content_type:"latex",question_image:null,
    options:p.options,correct_option_id:p.correct,
    explanation:p.explanation,explanation_content_type:"latex",explanation_image:null,
    tags,created_at:new Date().toISOString(),updated_at:new Date().toISOString()};
  const{error}=await sb.from("questions").upsert(row,{onConflict:"id"});
  if(error){console.error(`❌ ${id}:`,error.message);failCount++;}
  else{console.log(`✓ ${id}`);okCount++;}
}
console.log(`\n총 ${okCount}건 업로드, ${failCount}건 실패 (대상 ${PROBLEMS.length}건)`);
