// 2021년 단국대 오전 편입수학 객관식 20문항 (4지선다, 문항 번호 31~50)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR_ID="2021am", YEAR_KO="2021", SESSION_KO="오전", SCHOOL_KO="단국대", SCHOOL_EN="dankook";
const opts4 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:31, subject:"미분학", unit:"극한과 연속", concept:"극한 미정 상수",
    difficulty:"easy",
    question:"$\\displaystyle\\lim_{x\\to-2}\\dfrac{1-\\sqrt{x+a}}{x+2}=b$를 만족시키는 상수 $a,b$에 대하여 $ab$의 값은?",
    options:opts4("$-\\dfrac{3}{2}$","$-1$","$-\\dfrac{1}{2}$","$1$"),
    correct:"1",
    explanation:"분모 $\\to 0$이므로 분자도 $\\to 0$: $1-\\sqrt{-2+a}=0\\Rightarrow a=3$.\n유리화: $\\dfrac{-(x+2)}{(x+2)(1+\\sqrt{x+3})}\\to-\\dfrac{1}{2}=b$.\n$ab=3\\cdot(-1/2)=-3/2$.",
  },
  {n:32, subject:"미분학", unit:"도함수 응용", concept:"극값 + 미정 상수 (3차)",
    difficulty:"medium",
    question:"삼차함수 $f(x)$의 도함수 $f'(x)$의 영점이 $-1,1$이다. 함수 $f(x)$의 극솟값이 $-4$이고 극댓값이 $0$일 때, $f(3)$의 값은?",
    options:opts4("$-16$","$-18$","$-20$","$-22$"),
    correct:"3",
    explanation:"$f'(x)=a(x^2-1)$, $x=-1$ 극소, $x=1$ 극대.\n$f(x)=a(x^3/3-x)+c$. 조건: $f(-1)=2a/3+c=-4,\\,f(1)=-2a/3+c=0\\Rightarrow c=-2,\\,a=-3$.\n$f(x)=-x^3+3x-2$. $f(3)=-27+9-2=-20$.",
  },
  {n:33, subject:"적분학", unit:"정적분", concept:"리만합 분리",
    difficulty:"medium",
    question:"$\\displaystyle\\lim_{n\\to\\infty}\\sum_{k=n+1}^{2n}\\dfrac{3\\sqrt{k}}{n\\sqrt{n}}$의 값은?",
    options:opts4("$\\sqrt{2}-1$","$2\\sqrt{2}-1$","$2\\sqrt{2}-2$","$4\\sqrt{2}-2$"),
    correct:"4",
    explanation:"$\\sum_{k=1}^{2n}-\\sum_{k=1}^n$ 차로 분해.\n① $\\sum_{k=1}^{2n}\\dfrac{3\\sqrt{k}}{n\\sqrt{n}}=2\\sqrt{2}\\sum_{k=1}^{2n}\\dfrac{3\\sqrt{k/(2n)}}{2n}\\to 2\\sqrt{2}\\!\\int_0^1 3\\sqrt{x}\\,dx=4\\sqrt{2}$.\n② $\\sum_{k=1}^n\\to 3\\!\\int_0^1\\sqrt{x}\\,dx=2$.\n차 $=4\\sqrt{2}-2$.",
  },
  {n:34, subject:"적분학", unit:"이상적분", concept:"이상적분 수렴 식별",
    difficulty:"medium",
    question:"다음 중 수렴하는 특이적분의 개수는?\n\nㄱ. $\\displaystyle\\int_0^3\\dfrac{1}{x-3}\\,dx$\nㄴ. $\\displaystyle\\int_1^{\\infty}\\dfrac{1}{\\sqrt{x}}\\,dx$\nㄷ. $\\displaystyle\\int_1^{\\infty}\\dfrac{2+e^{-x}}{x}\\,dx$\nㄹ. $\\displaystyle\\int_0^{\\pi/2}\\sec x\\,dx$",
    options:opts4("$0$","$1$","$2$","$3$"),
    correct:"1",
    explanation:"ㄱ $\\sim\\ln$ 발산.\nㄴ $p=1/2$ 발산.\nㄷ $\\sim 2/x$ 발산.\nㄹ $\\sec x\\to\\infty$ ($x\\to\\pi/2$) 발산.\n수렴: 0개.\n[정정] 류갓티비 답 (1)이지만 보기 (1)이 0이므로 수렴 0개로 처리.",
  },
  {n:35, subject:"적분학", unit:"급수의 수렴/발산", concept:"수렴 급수 식별",
    difficulty:"medium",
    question:"다음 중 수렴하는 급수의 개수는?\n\nㄱ. $\\displaystyle\\sum_{n=2}^{\\infty}\\dfrac{1}{n\\ln n}$\nㄴ. $\\displaystyle\\sum_{n=1}^{\\infty}(-1)^n\\dfrac{3^n}{n!}$\nㄷ. $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{n^n}{n!}$\nㄹ. $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{\\ln n}{n}$\nㅁ. $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{\\cos(n!)}{n^2}$",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"2",
    explanation:"ㄱ [발산] 적분판정 $\\!\\int 1/(t\\ln t)dt=\\ln\\ln t\\to\\infty$.\nㄴ [수렴] $3^n/n!\\to 0$ + 교대급수.\nㄷ [발산] $n^n/n!\\to e^n$ 발산.\nㄹ [발산] $\\ln n/n\\sim$ 큰 항.\nㅁ [수렴] 디리클레: $|\\cos(n!)|\\le 1$, $1/n^2$ 수렴.\n수렴: ㄴ, ㅁ 2개.",
  },
  {n:36, subject:"다변수함수", unit:"극좌표와 극곡선", concept:"극곡선 영역 넓이",
    difficulty:"medium",
    question:"극곡선 $r=3\\cos\\theta$의 내부와 $r=1+\\cos\\theta$의 외부로 둘러싸인 영역의 넓이는?",
    options:opts4("$\\pi$","$2\\pi$","$3\\pi$","$4\\pi$"),
    correct:"1",
    explanation:"\"팩맨이 파이를 먹는다\" 표준 결과 $=\\pi$.\n($r=3\\cos\\theta$ 원과 $r=1+\\cos\\theta$ 카디오이드의 차이 영역).",
  },
  {n:37, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"3점 삼각형 넓이",
    difficulty:"easy",
    question:"3차원 공간에서 세 점 $P(2,8,12),\\,Q(-2,5,-2),\\,R(2,-2,2)$를 꼭짓점으로 하는 삼각형 $PQR$의 넓이는?",
    options:opts4("$12\\sqrt{17}$","$15\\sqrt{17}$","$12\\sqrt{19}$","$15\\sqrt{19}$"),
    correct:"2",
    explanation:"$\\vec{PQ}=(-4,-3,-14),\\,\\vec{PR}=(0,-10,-10)$.\n$\\vec{PQ}\\times\\vec{PR}=(-110,-40,40)=10(-11,-4,4)$.\n$|\\cdot|=10\\sqrt{121+16+16}=10\\sqrt{153}=30\\sqrt{17}$.\n넓이 $=15\\sqrt{17}$.",
  },
  {n:38, subject:"다변수함수", unit:"편미분", concept:"방향도함수 (단위벡터)",
    difficulty:"medium",
    question:"점 $(1,-1)$에서 벡터 $\\vec{v}=\\langle a,b\\rangle$ 방향으로 함수 $f(x,y)=x^2 y^4-4xy^2$의 방향도함수가 $2$일 때, $\\dfrac{b}{a}$의 값은? (단, $a,b$는 $0$이 아닌 실수이다.)",
    options:opts4("$\\dfrac{2}{3}$","$\\dfrac{3}{4}$","$\\dfrac{4}{3}$","$\\dfrac{5}{4}$"),
    correct:"3",
    explanation:"$\\nabla f=(2xy^4-4y^2,4x^2y^3-8xy)\\big|_{(1,-1)}=(-2,4)$.\n$\\hat v=(a,b)$ (단위벡터). $D_{\\hat v}f=-2a+4b=2$, $a^2+b^2=1$.\n연립: $a=3/5,\\,b=4/5$. $b/a=4/3$.",
  },
  {n:39, subject:"다변수함수", unit:"이중적분", concept:"입체 부피 ($y=\\sqrt{x}$ 평면)",
    difficulty:"medium",
    question:"곡면 $x=y^2$과 세 평면 $x=z,\\,z=0,\\,x=1$로 둘러싸인 입체의 부피는?",
    options:opts4("$\\dfrac{1}{2}$","$\\dfrac{2}{3}$","$\\dfrac{3}{4}$","$\\dfrac{4}{5}$"),
    correct:"4",
    explanation:"$y=\\pm\\sqrt{x}$. 영역 ($xz$평면): $x=z,\\,z=0,\\,x=1$ ⇒ 삼각형.\n$V=2\\!\\iint_D\\sqrt{x}\\,dA$ (대칭). $D$: $0\\le z\\le x,\\,0\\le x\\le 1$.\n$V=2\\!\\int_0^1\\!\\!\\int_0^x\\sqrt{x}\\,dz\\,dx=2\\!\\int_0^1 x^{3/2}\\,dx=\\dfrac{4}{5}$.",
  },
  {n:40, subject:"다변수함수", unit:"다변수 극값", concept:"극점·극값 진위판단",
    difficulty:"medium",
    question:"함수 $f(x,y)=e^y(y^2-x^2)$에 대한 다음 설명 중 옳은 것은 모두 몇 개인가?\n\nㄱ. 점 $(0,0),\\,(0,-2)$는 임계점이다.\nㄴ. $2$개의 극값을 갖는다.\nㄷ. 극솟값은 $0$이다.\nㄹ. 극댓값은 $4e^{-2}$이다.",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"2",
    explanation:"$f_x=-2xe^y,\\,f_y=e^y(y^2-x^2+2y)$. 임계점: $x=0,\\,y^2+2y=0\\Rightarrow y=0,-2$.\n$(0,0)$: $\\Delta=-4<0$ 안장점.\n$(0,-2)$: $f_{xx}=-2e^{-2}<0,\\,\\Delta>0$ ⇒ 극대. $f(0,-2)=4e^{-2}$.\nㄱ [참] ㄴ [거짓: 1개] ㄷ [거짓: 극소 없음] ㄹ [참].\n2개.",
  },
  {n:41, subject:"다변수함수", unit:"이중적분", concept:"평행사변형 변수변환",
    difficulty:"hard",
    question:"네 꼭짓점 $(0,0),\\,\\!\\left(1,\\dfrac{1}{3}\\right),\\,\\!\\left(\\dfrac{4}{3},\\dfrac{1}{9}\\right),\\,\\!\\left(\\dfrac{1}{3},-\\dfrac{2}{9}\\right)$로 이루어진 사각형 영역 $D$에 대하여, 이중적분 $\\displaystyle\\iint_D(x-3y-1)e^{2x+3y}\\cos(x-3y)\\,dA$의 값은?",
    options:opts4("$\\dfrac{e^2-1}{9}(\\cos 1-1)$","$\\dfrac{e^2-1}{9}\\sin 1$","$\\dfrac{e^3-1}{9}(\\cos 1-1)$","$\\dfrac{e^3-1}{9}\\sin 1$"),
    correct:"3",
    explanation:"$x-3y=u,\\,2x+3y=v$ 치환: $0\\le u\\le 1,\\,0\\le v\\le 3$. $|J|=1/9$.\n$\\!\\iint(u-1)e^v\\cos u\\cdot\\dfrac{1}{9}du\\,dv=\\dfrac{1}{9}(e^3-1)\\!\\int_0^1(u-1)\\cos u\\,du=\\dfrac{e^3-1}{9}(\\cos 1-1)$ (부분적분).",
  },
  {n:42, subject:"다변수함수", unit:"선적분", concept:"그린 정리",
    difficulty:"medium",
    question:"곡선 $C$를 직선 $y=x$와 곡선 $y=x^2$으로 둘러싸인 영역의 경계라 하자. 벡터장 $\\vec{F}(x,y)=\\langle xy^2,x+y\\rangle$에 대하여 선적분 $\\displaystyle\\int_C\\vec{F}\\cdot d\\vec{r}$의 값은? (단, 방향은 시계 반대 방향이다.)",
    options:opts4("$\\dfrac{1}{3}$","$\\dfrac{1}{6}$","$\\dfrac{1}{12}$","$\\dfrac{1}{24}$"),
    correct:"3",
    explanation:"그린: $\\!\\iint(1-2xy)\\,dA$.\n$\\!\\int_0^1\\!\\!\\int_{x^2}^x(1-2xy)\\,dy\\,dx=\\!\\int_0^1(x-x^2)-x(x^2-x^4)\\,dx=\\!\\int_0^1(x-x^2-x^3+x^5)\\,dx=\\dfrac{1}{12}$.",
  },
  {n:43, subject:"다변수함수", unit:"공간곡면", concept:"매개변수곡면 접평면",
    difficulty:"medium",
    question:"곡면 $S$의 매개변수표현이 $x=u\\cos v,\\,y=u\\sin v,\\,z=u^2+v^2$일 때, $S$ 위의 점 $(1,0,1)$에서의 접평면의 방정식은?",
    options:opts4("$x-y+2z=3$","$x-2z=-1$","$-x+y+2z=1$","$2x-z=1$"),
    correct:"4",
    explanation:"$(u,v)=(1,0)$에서 $r_u=(\\cos v,\\sin v,2u)=(1,0,2),\\,r_v=(-u\\sin v,u\\cos v,2v)=(0,1,0)$.\n법선 $r_u\\times r_v=(-2,0,1)\\sim(2,0,-1)$.\n접평면: $2(x-1)+0-(z-1)=0\\Rightarrow 2x-z=1$.",
  },
  {n:44, subject:"다변수함수", unit:"선적분", concept:"스토크스 정리",
    difficulty:"medium",
    question:"곡선 $C$는 평면 $y+z=2$와 원기둥 $x^2+y^2=1$의 교선일 때, 벡터장 $\\vec{F}(x,y,z)=\\langle-y^2,x,z^2\\rangle$에 대하여, 선적분 $\\displaystyle\\int_C\\vec{F}\\cdot d\\vec{r}$의 값은? (단, $C$의 방향은 위에서 내려다봤을 때 시계 방향이다.)",
    options:opts4("$-\\pi$","$-\\dfrac{\\pi}{2}$","$\\dfrac{\\pi}{2}$","$\\pi$"),
    correct:"1",
    explanation:"스토크스: $\\nabla\\times\\vec F=(0,0,1+2y)$. 평면 법선 $(0,1,1)/\\sqrt{2}$.\n$\\!\\iint_S\\nabla\\times F\\cdot\\vec n\\,dS=\\!\\iint_D(1+2y)\\,dA$ ($D$: $x^2+y^2\\le 1$).\n$=\\pi+0=\\pi$. 시계방향이므로 $-\\pi$.",
  },
  {n:45, subject:"선형대수", unit:"행렬", concept:"케일리-해밀턴",
    difficulty:"hard",
    question:"행렬 $A=\\begin{pmatrix}3&-4\\\\-2&4\\end{pmatrix}$에 대하여 $AB=A^2-A-4E$를 만족시키는 행렬 $B$의 모든 성분의 합은? (단, $E$는 단위행렬이다.)",
    options:opts4("$-14$","$-10$","$-6$","$-2$"),
    correct:"1",
    explanation:"$|A|=4\\ne 0$. $B=A-E-4A^{-1}$.\n케일리-해밀턴: $A^2-7A+4E=O\\Rightarrow A-7E+4A^{-1}=O\\Rightarrow 4A^{-1}=7E-A$.\n$B=A-E-(7E-A)=2A-8E=\\begin{pmatrix}-2&-8\\\\-4&0\\end{pmatrix}$.\n성분 합 $=-14$.",
  },
  {n:46, subject:"선형대수", unit:"선형변환", concept:"반사 변환 합성",
    difficulty:"medium",
    question:"선형변환 $T:\\mathbb{R}^2\\to\\mathbb{R}^2$가 각 점을 직선 $y=-x$에 대하여 반사(reflection)시키고 그 점을 $y$축에 대하여 반사시키는 변환일 때, $T$에 대한 표준행렬은?",
    options:opts4("$\\begin{pmatrix}0&-1\\\\0&1\\end{pmatrix}$","$\\begin{pmatrix}0&1\\\\-1&0\\end{pmatrix}$","$\\begin{pmatrix}0&1\\\\1&0\\end{pmatrix}$","$\\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}$"),
    correct:"2",
    explanation:"$y=-x$ 반사 $T_1=\\begin{pmatrix}0&-1\\\\-1&0\\end{pmatrix}$. $y$축 반사 $T_2=\\begin{pmatrix}-1&0\\\\0&1\\end{pmatrix}$.\n$T=T_2 T_1=\\begin{pmatrix}-1&0\\\\0&1\\end{pmatrix}\\begin{pmatrix}0&-1\\\\-1&0\\end{pmatrix}=\\begin{pmatrix}0&1\\\\-1&0\\end{pmatrix}$.",
  },
  {n:47, subject:"선형대수", unit:"행렬식", concept:"4×4 행렬식",
    difficulty:"medium",
    question:"행렬 $\\begin{pmatrix}5&0&0&-5\\\\4&-3&-3&1\\\\2&3&-1&2\\\\-2&1&0&3\\end{pmatrix}$의 행렬식(determinant)은?",
    options:opts4("$15$","$20$","$25$","$30$"),
    correct:"3",
    explanation:"1행에서 5 추출: $5\\det\\begin{pmatrix}1&0&0&-1\\\\4&-3&-3&1\\\\2&3&-1&2\\\\-2&1&0&3\\end{pmatrix}$. 1열로 행 축약: $5\\cdot 5=25$ (계산).",
  },
  {n:48, subject:"미분학", unit:"미분방정식", concept:"코시-오일러 + 비동차",
    difficulty:"hard",
    question:"$y=y(x)$가 미분방정식 $x^2 y''-5xy'+9y=2x^3,\\,y(1)=2,\\,y(e)=e^3$의 해일 때, $y(e^2)$의 값은?",
    options:opts4("$e^6$","$2e^6$","$3e^6$","$4e^6$"),
    correct:"2",
    explanation:"코시-오일러 보조 $r(r-1)-5r+9=r^2-6r+9=0\\Rightarrow r=3$ 중근.\n$y_h=c_1 x^3+c_2 x^3\\ln x$. $y_p=x^3(\\ln x)^2$ (특수해).\n$y=c_1 x^3+c_2 x^3\\ln x+x^3(\\ln x)^2$.\n$y(1)=c_1=2$. $y(e)=2e^3+c_2 e^3+e^3=e^3\\Rightarrow c_2=-2$.\n$y(e^2)=2e^6-4e^6+4e^6=2e^6$.",
  },
  {n:49, subject:"미분학", unit:"미분방정식", concept:"매개변수 변동법 (sin(e^(-x)))",
    difficulty:"hard",
    question:"$y=y(x)$가 미분방정식 $y''-y=e^{-2x}\\sin(e^{-x}),\\,y\\!\\left(-\\ln\\dfrac{\\pi}{2}\\right)=-1+\\dfrac{1}{\\pi},\\,y(-\\ln\\pi)=\\dfrac{2}{\\pi}$의 해일 때, $y(-\\ln 2\\pi)$의 값은?",
    options:opts4("$\\dfrac{4}{\\pi}$","$\\dfrac{3}{\\pi}$","$\\dfrac{2}{\\pi}$","$\\dfrac{1}{\\pi}$"),
    correct:"4",
    explanation:"보조방정식 $r^2-1=0\\Rightarrow r=\\pm 1$. $y_h=c_1 e^x+c_2 e^{-x}$.\n론스키안 + 매개변수 변동법으로 $y_p=-\\sin(e^{-x})-e^x\\cos(e^{-x})$.\n초기조건: $c_1=1/3,\\,c_2=2/(3\\pi^2)$.\n$y(-\\ln 2\\pi)=\\dfrac{1}{6\\pi}+\\dfrac{4}{3\\pi}-\\dfrac{1}{2\\pi}=\\dfrac{1}{\\pi}$.",
  },
  {n:50, subject:"적분학", unit:"라플라스 변환", concept:"역라플라스 (s+4)/(s²+4)",
    difficulty:"easy",
    question:"역라플라스변환(inverse Laplace transform) $\\mathcal{L}^{-1}\\!\\left\\{\\dfrac{s+4}{s^2+4}\\right\\}$를 $f(t)$라 할 때, $f\\!\\left(\\dfrac{\\pi}{8}\\right)$의 값은?",
    options:opts4("$\\dfrac{\\sqrt{2}}{2}$","$\\sqrt{2}$","$\\dfrac{3\\sqrt{2}}{2}$","$2\\sqrt{2}$"),
    correct:"3",
    explanation:"$\\mathcal L^{-1}\\!\\left\\{\\dfrac{s}{s^2+4}+\\dfrac{4}{s^2+4}\\right\\}=\\cos 2t+2\\sin 2t$.\n$f(\\pi/8)=\\cos(\\pi/4)+2\\sin(\\pi/4)=\\dfrac{\\sqrt{2}}{2}+\\sqrt{2}=\\dfrac{3\\sqrt{2}}{2}$.",
  },
];

const TOTAL=PROBLEMS.length;
console.log(`총 ${TOTAL}문제 (객관식 4지선다) 준비됨`);

const rows = PROBLEMS.map(p => {
  const id = `q-${YEAR_ID}-${SCHOOL_EN}-${String(p.n).padStart(2,"0")}`;
  return {
    id, subject: p.subject, unit: p.unit, concept: p.concept, difficulty: p.difficulty,
    source_type: "imported", pool: "general", question: p.question, content_type: "latex",
    question_image: null, question_type: "multiple_choice",
    options: p.options, correct_option_id: p.correct,
    answer_text: null, explanation: p.explanation, explanation_content_type: "latex",
    explanation_image: null,
    tags: [YEAR_KO, SCHOOL_KO, SESSION_KO, "past_exam", p.subject, p.unit, p.concept],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  };
});

const { data, error } = await sb.from("questions").upsert(rows, { onConflict: "id" }).select("id");
if (error) { console.error("업로드 실패:", error); process.exit(1); }
console.log(`업로드 완료: ${data.length}건`);
