// 2024년 단국대 오전 편입수학 객관식 20문항 (4지선다, 문항 번호 31~50)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR_ID="2024am", YEAR_KO="2024", SESSION_KO="오전", SCHOOL_KO="단국대", SCHOOL_EN="dankook";
const opts4 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:31, subject:"다변수함수", unit:"평면곡선", concept:"원의 접선",
    difficulty:"easy",
    question:"원 $x^2+y^2=25$ 위의 점 $(3,4)$에 접하는 직선의 방정식은?",
    options:opts4("$3x+4y=25$","$3x-4y=-7$","$4x+3y=24$","$4x-3y=0$"),
    correct:"1",
    explanation:"$x^2+y^2=r^2$ 위의 점 $(a,b)$에서의 접선의 방정식: $ax+by=r^2$.\n$3x+4y=25$.",
  },
  {n:32, subject:"미분학", unit:"도함수 응용", concept:"폐구간 최대·최솟값",
    difficulty:"easy",
    question:"닫힌구간 $[-1,2]$에서 함수 $f(x)=x^3-2x^2+x-1$의 최댓값을 $a$, 최솟값을 $b$라 할 때 $a+b$의 값은?",
    options:opts4("$-4$","$-1$","$1$","$4$"),
    correct:"1",
    explanation:"양 끝점: $f(-1)=-5,\\,f(2)=1$.\n임계점: $f'(x)=3x^2-4x+1=(3x-1)(x-1)=0\\Rightarrow x=1,\\,1/3$.\n$f(1)=-1,\\,f(1/3)=-23/27$.\n최대 $a=1$ ($x=2$), 최소 $b=-5$ ($x=-1$). $a+b=-4$.",
  },
  {n:33, subject:"적분학", unit:"정적분", concept:"절댓값 정적분",
    difficulty:"easy",
    question:"$\\displaystyle\\int_{-1}^{3}(x-a|x|)\\,dx=10$일 때, 실수 $a$의 값은?",
    options:opts4("$-\\dfrac{6}{5}$","$-\\dfrac{2}{5}$","$\\dfrac{2}{5}$","$\\dfrac{6}{5}$"),
    correct:"1",
    explanation:"$\\!\\int_{-1}^{3}x\\,dx=\\dfrac{1}{2}[x^2]_{-1}^3=4$.\n$\\!\\int_{-1}^{3}|x|\\,dx=$ 직각삼각형 두 개 $=\\dfrac{1}{2}+\\dfrac{9}{2}=5$.\n$4-5a=10\\Rightarrow a=-\\dfrac{6}{5}$.",
  },
  {n:34, subject:"적분학", unit:"정적분의 응용", concept:"두 곡선 둘러싼 면적",
    difficulty:"medium",
    question:"좌표평면에서 직선 $x=0,\\,x=2\\pi$와 곡선 $y=\\sin\\dfrac{x}{2},\\,y=\\cos x$로 둘러싸인 영역의 넓이는?",
    options:opts4("$-2+3\\sqrt{3}$","$-4+6\\sqrt{3}$","$2+3\\sqrt{3}$","$4+6\\sqrt{3}$"),
    correct:"2",
    explanation:"교점에서 $\\sin(x/2)=\\cos x$ 풀면 $x=\\pi/3,\\,5\\pi/3$.\n구간을 셋으로 나눠 적분 (대칭성 ① $=$ ③):\n①$[0,\\pi/3]$: $\\!\\int(\\cos x-\\sin(x/2))dx=\\dfrac{3\\sqrt{3}}{2}-2$.\n②$[\\pi/3,5\\pi/3]$: $\\!\\int(\\sin(x/2)-\\cos x)dx=3\\sqrt{3}$.\n총 $=2(3\\sqrt{3}/2-2)+3\\sqrt{3}=6\\sqrt{3}-4$.",
  },
  {n:35, subject:"적분학", unit:"급수의 수렴/발산", concept:"$k^{a_n}$ 수렴 조건",
    difficulty:"medium",
    question:"수열 $a_n=-\\ln n$ ($n=1,2,\\ldots$)에 대하여 급수 $\\displaystyle\\sum_{n=1}^{\\infty}k^{a_n}$이 수렴하기 위한 정수 $k$의 최솟값은?",
    options:opts4("$2$","$3$","$4$","$5$"),
    correct:"2",
    explanation:"$k^{a_n}=k^{-\\ln n}=(1/n)^{\\ln k}=\\dfrac{1}{n^{\\ln k}}$.\n$p$-급수 수렴 조건: $\\ln k>1\\Leftrightarrow k>e\\approx 2.718$.\n정수 $k$ 최솟값 $=3$.",
  },
  {n:36, subject:"다변수함수", unit:"극좌표와 극곡선", concept:"4엽 장미 영역 넓이",
    difficulty:"medium",
    question:"극방정식으로 표현된 곡선 $r=\\cos 2\\theta$ (단, $\\cos 2\\theta\\ge 0$)로 둘러싸인 영역의 넓이는?",
    options:opts4("$\\dfrac{\\pi}{8}$","$\\dfrac{\\pi}{4}$","$\\dfrac{\\pi}{2}$","$\\pi$"),
    correct:"2",
    explanation:"$\\cos 2\\theta\\ge 0$인 영역에서 4엽 장미 (각 잎이 $\\theta$ 폭 $\\pi/4$).\n전체 넓이 $=\\dfrac{1}{2}\\cdot\\dfrac{\\pi}{2}\\cdot 1^2=\\dfrac{\\pi}{4}$ (실제 류갓티비 표준 공식).\n([참고] $r^2$ 적분: $\\dfrac{1}{2}\\!\\int_0^{2\\pi}\\cos^2 2\\theta\\,d\\theta\\cdot\\!$절반 $=\\dfrac{\\pi}{4}$.)",
  },
  {n:37, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"두 평면 교선의 방향",
    difficulty:"easy",
    question:"다음 중 두 평면 $x-2y+z=0$과 $2x+3y-2z=0$이 만나서 생기는 직선에 평행한 벡터는?",
    options:opts4("$\\langle 1,-4,7\\rangle$","$\\langle 1,4,-7\\rangle$","$\\langle 1,4,7\\rangle$","$\\langle 1,-4,-7\\rangle$"),
    correct:"3",
    explanation:"교선 방향 $=$ 두 법선의 외적 $(1,-2,1)\\times(2,3,-2)=(4-3,2+2,3+4)=(1,4,7)$.",
  },
  {n:38, subject:"다변수함수", unit:"편미분", concept:"방향도함수가 가장 빠른 방향",
    difficulty:"easy",
    question:"점 $(1,2)$에서 함수 $f(x,y)=2x^2+y^2$이 가장 빨리 변화하는 방향을 $\\langle a,b\\rangle$라 할 때, $\\dfrac{b}{a}$의 값은? (단, $a,b$는 상수)",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"1",
    explanation:"가장 빠른 방향 $=$ $\\nabla f$ 방향. $\\nabla f=(4x,2y)\\big|_{(1,2)}=(4,4)$.\n$\\langle a,b\\rangle\\parallel(4,4)$이므로 $b/a=1$.",
  },
  {n:39, subject:"다변수함수", unit:"삼중적분", concept:"원주좌표 삼중적분",
    difficulty:"medium",
    question:"곡면 $y=x^2+z^2$과 평면 $y=a$ ($a>0$)로 둘러싸인 영역을 $E$라 하자. $\\displaystyle\\iiint_E\\sqrt{x^2+z^2}\\,dV=\\dfrac{128}{15}\\pi$일 때, 실수 $a$의 값은?",
    options:opts4("$1$","$4$","$9$","$16$"),
    correct:"2",
    explanation:"원주좌표 ($x=r\\cos\\theta,\\,z=r\\sin\\theta,\\,y$ 그대로): $\\!\\iiint=2\\pi\\!\\int_0^{\\sqrt{a}}r(a-r^2)\\cdot r\\,dr=2\\pi\\!\\left[\\dfrac{ar^3}{3}-\\dfrac{r^5}{5}\\right]_0^{\\sqrt{a}}=2\\pi\\cdot\\dfrac{2a^{5/2}}{15}$.\n$\\dfrac{4\\pi a^{5/2}}{15}=\\dfrac{128\\pi}{15}\\Rightarrow a^{5/2}=32=2^5\\Rightarrow a=4$.",
  },
  {n:40, subject:"다변수함수", unit:"다변수 극값", concept:"극값 + 헤시안 판정",
    difficulty:"medium",
    question:"함수 $f(x,y)=-x^3+4xy-2y^2+1$은 점 $(a,b)$에서 극값 $c$를 갖는다. $a+b+c$의 값은? (단, $a,b,c$는 상수)",
    options:opts4("$\\dfrac{20}{27}$","$\\dfrac{19}{9}$","$\\dfrac{94}{27}$","$\\dfrac{131}{27}$"),
    correct:"4",
    explanation:"$f_x=-3x^2+4y=0,\\,f_y=4x-4y=0$ ⇒ $y=x$, $4x-3x^2=0\\Rightarrow x=0,\\,4/3$.\n$(0,0)$ 안장점 ($\\Delta=-16<0$). $(4/3,4/3)$: $f_{xx}=-8<0,\\,\\Delta>0$ ⇒ 극대.\n$f(4/3,4/3)=-64/27+64/9-32/9+1=59/27$.\n$a+b+c=4/3+4/3+59/27=72/27+59/27=131/27$.",
  },
  {n:41, subject:"다변수함수", unit:"편미분", concept:"합성함수 + 그래디언트 직교",
    difficulty:"hard",
    question:"매끄러운 함수 $f:\\mathbb{R}^3\\to\\mathbb{R}$와 $r:(-1,1)\\to\\mathbb{R}^3$에 대하여 함수 $g(t)=f(r(t))$는 $t=0$에서 최솟값을 갖는다. 벡터 $\\vec{u}=(\\nabla f)(r(0))$와 $\\vec{v}=r'(0)$의 크기가 각각 $\\sqrt{3},\\,1$일 때, 벡터 $\\vec{u}-\\vec{v}$의 크기는?",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"2",
    explanation:"$g'(t)=\\nabla f(r(t))\\cdot r'(t)$. $t=0$ 극소이므로 $g'(0)=\\vec{u}\\cdot\\vec{v}=0$ (직교).\n$\\|\\vec{u}-\\vec{v}\\|^2=\\|\\vec{u}\\|^2+\\|\\vec{v}\\|^2-2\\vec{u}\\cdot\\vec{v}=3+1-0=4$.\n$\\|\\vec{u}-\\vec{v}\\|=2$.",
  },
  {n:42, subject:"다변수함수", unit:"공간곡면", concept:"단위 구면 면적분",
    difficulty:"medium",
    question:"구면 $S^2:x^2+y^2+z^2=1$에 대하여 $\\displaystyle\\iint_{S^2}\\ln(1+\\sqrt{x^2+y^2+z^2})\\,dS$의 값은?",
    options:opts4("$\\pi\\ln 2$","$2\\pi\\ln 2$","$3\\pi\\ln 2$","$4\\pi\\ln 2$"),
    correct:"4",
    explanation:"$S^2$ 위에서 $\\sqrt{x^2+y^2+z^2}=1$ 상수이므로 $\\ln(1+1)=\\ln 2$ 상수.\n$\\!\\iint_{S^2}\\ln 2\\,dS=\\ln 2\\cdot$(구면 넓이)$=\\ln 2\\cdot 4\\pi=4\\pi\\ln 2$.",
  },
  {n:43, subject:"다변수함수", unit:"선적분", concept:"스토크스 정리",
    difficulty:"hard",
    question:"유향곡선 $C$는 평면 $2x+2y+z=6$과 각 평면 $x=0,\\,y=0,\\,z=0$과의 세 교선을 변으로 하는 삼각형이고, 방향은 원점에서 바라보았을 때 시계방향이다. 벡터장 $\\vec{F}(x,y,z)=-y^2\\vec{i}+z\\vec{j}+x\\vec{k}$에 대하여 선적분 $\\displaystyle\\int_C\\vec{F}\\cdot d\\vec{r}$의 값은?",
    options:opts4("$-12$","$-9$","$-6$","$-3$"),
    correct:"2",
    explanation:"스토크스 정리: $\\!\\int_C\\vec{F}\\cdot d\\vec{r}=\\!\\iint_S\\text{curl}\\,\\vec{F}\\cdot\\vec{n}\\,dS$.\n$\\text{curl}\\vec{F}=(-1,-1,2y)$. 평면 법선 $\\vec{n}\\propto(2,2,1)/3$.\n원점 시계방향=양의방향(법선이 원점 반대쪽).\n$\\!\\iint_D\\text{curl}\\vec{F}\\cdot(2,2,1)\\,dxdy=\\!\\iint_D(2y-4)\\,dxdy$ ($D$는 $xy$평면 삼각형 $(0,0),(3,0),(0,3)$).\n$=2\\bar{y}\\cdot$면적 $-4\\cdot$면적 $=2\\cdot 1\\cdot\\dfrac{9}{2}-4\\cdot\\dfrac{9}{2}=9-18=-9$.",
  },
  {n:44, subject:"다변수함수", unit:"편미분", concept:"div(curl F) = 0",
    difficulty:"medium",
    question:"벡터장 $\\vec{F}:\\mathbb{R}^3\\to\\mathbb{R}^3$에 대하여 $\\nabla\\times\\vec{F}=\\langle P,Q,R\\rangle$이라 하자. 점 $(x_0,y_0,z_0)$에서 $\\begin{pmatrix}P_x&P_y&P_z\\\\Q_x&Q_y&Q_z\\\\R_x&R_y&R_z\\end{pmatrix}=\\begin{pmatrix}-3a&0\\\\1&0&b\\\\2&5&c\\end{pmatrix}$일 때, 실수 $c$의 값은?",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"3",
    explanation:"$\\text{div}(\\text{curl}\\vec{F})=P_x+Q_y+R_z=0$ 항상.\n$P_x+Q_y+R_z=-3+0+c=0\\Rightarrow c=3$.",
  },
  {n:45, subject:"선형대수", unit:"고유치와 대각화", concept:"고유치·대각화·직교 진위",
    difficulty:"hard",
    question:"행렬 $A=\\begin{pmatrix}0&0&-2\\\\1&2&1\\\\1&0&3\\end{pmatrix}$에 대한 다음 설명 중 옳은 것의 개수는?\n\n㉠ $A$의 고윳값은 모두 양의 실수이다.\n㉡ 행렬 $B=A^6$의 고윳값의 최댓값은 64이다.\n㉢ $A$는 대각화가능(diagonalizable)하다.\n㉣ $A$는 직교대각화가능(orthogonally diagonalizable)하지 않다.",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"4",
    explanation:"특성다항식: $\\lambda^3-5\\lambda^2+8\\lambda-4=(\\lambda-1)(\\lambda-2)^2$. $\\lambda=1,2,2$.\n㉠ [참] 모두 양수.\n㉡ [참] $A^6$ 고윳값 $1^6,2^6,2^6$, 최대 $64$.\n㉢ [참] $\\lambda=2$의 기하적 중복도 $=$대수적 $=2$ ($A-2I$의 rank=1, nullity=2). 대각화 가능.\n㉣ [참] 직교대각화는 대칭행렬에만 가능. $A$는 비대칭.\n4개 모두 참.",
  },
  {n:46, subject:"선형대수", unit:"선형변환", concept:"스케일 + 회전 합성변환",
    difficulty:"hard",
    question:"일차변환 $T:\\mathbb{R}^2\\to\\mathbb{R}^2$은 그림과 같이 단위원을 타원으로, 삼각형 $\\triangle_1$을 삼각형 $\\triangle_2$로 대응시킨다. $T\\!\\left(\\!\\left\\langle\\dfrac{1}{3},\\dfrac{2\\sqrt{2}}{3}\\right\\rangle\\!\\right)=\\langle a,b\\rangle$일 때, $a+b$의 값은?",
    options:opts4("$\\dfrac{5}{3}$","$\\dfrac{8}{3}$","$\\sqrt{2}$","$2\\sqrt{2}$"),
    correct:"3",
    explanation:"변환 순서: $x$성분 $3$배, $y$성분 $2$배, 반시계 $\\pi/4$ 회전.\n$T=R_{\\pi/4}\\cdot\\text{diag}(3,2)=\\dfrac{1}{\\sqrt{2}}\\begin{pmatrix}1&-1\\\\1&1\\end{pmatrix}\\begin{pmatrix}3&0\\\\0&2\\end{pmatrix}=\\dfrac{1}{\\sqrt{2}}\\begin{pmatrix}3&-2\\\\3&2\\end{pmatrix}$.\n$T\\!\\begin{pmatrix}1/3\\\\2\\sqrt{2}/3\\end{pmatrix}=\\dfrac{1}{3\\sqrt{2}}\\begin{pmatrix}3-4\\sqrt{2}\\\\3+4\\sqrt{2}\\end{pmatrix}$.\n$a+b=\\dfrac{6}{3\\sqrt{2}}=\\sqrt{2}$.",
  },
  {n:47, subject:"선형대수", unit:"행렬식", concept:"크래머 공식 (행렬식 = 스칼라 삼중적)",
    difficulty:"medium",
    question:"상수 $a,b,c$에 대하여 $\\det\\!\\begin{pmatrix}a&b&c\\\\3&1&2\\\\0&-1&1\\end{pmatrix}=\\langle a,b,c\\rangle\\cdot(\\langle 3,1,2\\rangle\\times\\langle 0,-1,1\\rangle)=3$이다. 방정식 $\\begin{pmatrix}a&b&c\\\\3&1&2\\\\0&-1&1\\end{pmatrix}\\!\\begin{pmatrix}x\\\\y\\\\z\\end{pmatrix}=\\begin{pmatrix}3\\\\0\\\\0\\end{pmatrix}$의 해가 $x=x_0,\\,y=y_0,\\,z=z_0$일 때 $3x_0+y_0+z_0$의 값은?",
    options:opts4("$1$","$2$","$3$","$4$"),
    correct:"3",
    explanation:"외적 $(3,1,2)\\times(0,-1,1)=(3,-3,-3)$. 그러면 $\\langle a,b,c\\rangle\\cdot(3,-3,-3)=3a-3b-3c=3\\Rightarrow a-b-c=1$.\n방정식의 두 번째·세 번째 행: $3x+y+2z=0,\\,-y+z=0$. $y=z$. $3x+3z=0\\Rightarrow x=-z$.\n따라서 $3x_0+y_0+z_0=-3z_0+z_0+z_0=-z_0$. 첫 식과 결합으로 $z_0=-3$ 등 풀면 답 $=3$.\n또는 잔DGR: $\\!\\langle 3,1,2\\rangle\\times\\langle 0,-1,1\\rangle=(3,-3,-3)$이 해이므로 $x:y:z=3:-3:-3$의 스케일. 첫 식 $ax+by+cz=3$과 $a-b-c=1$ 비교 ⇒ $x=3,\\,y=-3,\\,z=-3$. $3\\cdot 3+(-3)+(-3)=3$.",
  },
  {n:48, subject:"미분학", unit:"미분방정식", concept:"1계 선형 ODE",
    difficulty:"medium",
    question:"미분방정식 $y'+(\\tan x)y=\\cos^2 x,\\,y(0)=-1$의 해 $y=y(x)$에 대하여 $y\\!\\left(\\dfrac{\\pi}{4}\\right)$의 값은?",
    options:opts4("$1+\\sqrt{2}$","$1-\\sqrt{2}$","$\\dfrac{1+\\sqrt{2}}{2}$","$\\dfrac{1-\\sqrt{2}}{2}$"),
    correct:"4",
    explanation:"적분인자 $e^{\\int\\tan x\\,dx}=\\sec x$. $(\\sec x\\cdot y)'=\\cos^2 x\\sec x=\\cos x$.\n$\\sec x\\cdot y=\\sin x+C$ ⇒ $y=\\cos x(\\sin x+C)$. $y(0)=C=-1$.\n$y(\\pi/4)=\\dfrac{\\sqrt{2}}{2}\\!\\left(\\dfrac{\\sqrt{2}}{2}-1\\right)=\\dfrac{1-\\sqrt{2}}{2}$.",
  },
  {n:49, subject:"미분학", unit:"미분방정식", concept:"코시-오일러 방정식",
    difficulty:"medium",
    question:"미분방정식 $x^2 y''-3xy'+4y=0$ ($x>0$), $y(1)=5,\\,y'(1)=3$의 해 $y=y(x)$에 대하여 $y(2)-y'(2)$의 값은?",
    options:opts4("$14$","$16$","$18$","$20$"),
    correct:"1",
    explanation:"코시-오일러 보조식: $r(r-1)-3r+4=0\\Rightarrow(r-2)^2=0$ (중근).\n$y=x^2(c_1+c_2\\ln x)$. $y(1)=c_1=5$. $y'(x)=2x(c_1+c_2\\ln x)+x c_2$, $y'(1)=2c_1+c_2=3\\Rightarrow c_2=-7$.\n$y=5x^2-7x^2\\ln x$. $y'=10x-14x\\ln x-7x=3x-14x\\ln x$.\n$y(2)-y'(2)=(20-28\\ln 2)-(6-28\\ln 2)=14$.",
  },
  {n:50, subject:"적분학", unit:"라플라스 변환", concept:"부분분수 + 역라플라스",
    difficulty:"medium",
    question:"함수 $F(s)=\\dfrac{1}{(s^2+1)(s^2+4)}$의 역라플라스변환(inverse Laplace transform)은?",
    options:opts4("$\\dfrac{1}{3}\\!\\left(\\sin t-\\dfrac{1}{2}\\cos 2t\\right)$","$\\dfrac{1}{3}\\!\\left(\\cos t-\\dfrac{1}{2}\\sin 2t\\right)$","$\\dfrac{1}{3}\\!\\left(\\sin t-\\dfrac{1}{2}\\sin 2t\\right)$","$\\dfrac{1}{3}\\!\\left(\\cos t-\\dfrac{1}{2}\\cos 2t\\right)$"),
    correct:"3",
    explanation:"부분분수 공식 $\\dfrac{1}{AB}=\\dfrac{1}{B-A}\\!\\left(\\dfrac{1}{A}-\\dfrac{1}{B}\\right)$ 활용.\n$F(s)=\\dfrac{1}{3}\\!\\left(\\dfrac{1}{s^2+1}-\\dfrac{1}{s^2+4}\\right)$.\n$\\mathcal{L}^{-1}\\!\\left\\{\\dfrac{1}{s^2+1}\\right\\}=\\sin t,\\,\\mathcal{L}^{-1}\\!\\left\\{\\dfrac{1}{s^2+4}\\right\\}=\\dfrac{1}{2}\\sin 2t$.\n$f(t)=\\dfrac{1}{3}\\!\\left(\\sin t-\\dfrac{1}{2}\\sin 2t\\right)$.",
  },
];

const TOTAL=PROBLEMS.length;
console.log(`총 ${TOTAL}문제 (객관식 4지선다) 준비됨`);

const rows = PROBLEMS.map(p => {
  const id = `q-${YEAR_ID}-${SCHOOL_EN}-${String(p.n).padStart(2,"0")}`;
  return {
    id, subject: p.subject, unit: p.unit, concept: p.concept, difficulty: p.difficulty,
    source_type: "imported", pool: "general", question: p.question, content_type: "latex",
    question_image: null, question_type: "multiple_choice",
    options: p.options, correct_option_id: p.correct,
    answer_text: null, explanation: p.explanation, explanation_content_type: "latex",
    explanation_image: null,
    tags: [YEAR_KO, SCHOOL_KO, SESSION_KO, "past_exam", p.subject, p.unit, p.concept],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  };
});

const { data, error } = await sb.from("questions").upsert(rows, { onConflict: "id" }).select("id");
if (error) { console.error("업로드 실패:", error); process.exit(1); }
console.log(`업로드 완료: ${data.length}건`);
