// 2021년 단국대 오후 편입수학 객관식 20문항 (4지선다, 문항 번호 31~50)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR_ID="2021pm", YEAR_KO="2021", SESSION_KO="오후", SCHOOL_KO="단국대", SCHOOL_EN="dankook";
const opts4 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:31, subject:"미분학", unit:"도함수", concept:"극한 + 곱의 미분",
    difficulty:"easy",
    question:"미분가능함수 $f$와 $g$가 $\\displaystyle\\lim_{x\\to 1}\\dfrac{f(x)-3}{x-1}=1,\\,\\displaystyle\\lim_{x\\to 1}\\dfrac{g(x)+2}{x-1}=2$를 만족시킬 때, 함수 $h(x)=f(x)g(x)$에 대하여 $h'(1)$의 값은?",
    options:opts4("$0$","$1$","$2$","$4$"),
    correct:"4",
    explanation:"$f(1)=3,\\,f'(1)=1,\\,g(1)=-2,\\,g'(1)=2$.\n$h'(1)=f'(1)g(1)+f(1)g'(1)=1\\cdot(-2)+3\\cdot 2=4$.",
  },
  {n:32, subject:"미분학", unit:"도함수 응용", concept:"극값 + 미정 상수",
    difficulty:"medium",
    question:"두 상수 $a,b$에 대하여 함수 $f(x)=-2x^3+ax^2-12x+b$가 $x=2$에서 극댓값 $6$을 가질 때, $a+b$의 값은?",
    options:opts4("$19$","$20$","$21$","$22$"),
    correct:"1",
    explanation:"$f(2)=-16+4a-24+b=6\\Rightarrow 4a+b=46$.\n$f'(2)=-24+4a-12=0\\Rightarrow a=9$. $b=10$.\n$a+b=19$.",
  },
  {n:33, subject:"적분학", unit:"정적분의 응용", concept:"여러 곡선 둘러싼 면적",
    difficulty:"medium",
    question:"직선 $y=-x,\\,y=x+6$과 곡선 $y=x^3$으로 둘러싸인 영역의 넓이는?",
    options:opts4("$17$","$18$","$19$","$20$"),
    correct:"3",
    explanation:"교점 분석: $y=-x$와 $y=x^3$은 원점, $y=x+6$과 $y=x^3$은 $(2,8)$, $y=-x$와 $y=x+6$은 $(-3,3)$.\n사다리꼴 + 보정. 류갓티비: $S=\\dfrac{55}{2}-\\dfrac{9}{2}-4=19$.",
  },
  {n:34, subject:"적분학", unit:"정적분의 응용", concept:"평행이동 + 회전체 부피",
    difficulty:"medium",
    question:"곡선 $x=\\sqrt{1-y^2}$과 $y$축으로 둘러싸인 영역을 직선 $x=-1$을 중심으로 회전시켜 얻은 입체의 부피는?",
    options:opts4("$\\pi^2+\\dfrac{2}{3}\\pi$","$\\pi^2+\\dfrac{4}{3}\\pi$","$2\\pi^2+\\dfrac{2}{3}\\pi$","$2\\pi^2+\\dfrac{4}{3}\\pi$"),
    correct:"2",
    explanation:"평행이동 후 회전: $V=2\\!\\left(2\\pi\\!\\int_0^1(x+1)\\sqrt{1-x^2}\\,dx\\right)$.\n$=2\\!\\left(2\\pi\\!\\int x\\sqrt{1-x^2}+2\\pi\\!\\int\\sqrt{1-x^2}\\right)=2\\!\\left(\\dfrac{2\\pi}{3}+\\dfrac{\\pi^2}{2}\\right)=\\pi^2+\\dfrac{4\\pi}{3}$.",
  },
  {n:35, subject:"적분학", unit:"급수의 수렴/발산", concept:"멱급수 수렴 정수 개수",
    difficulty:"medium",
    question:"멱급수 $\\displaystyle\\sum_{n=1}^{\\infty}(-1)^n\\dfrac{(2x-3)^n}{7^n\\sqrt{n}}$이 수렴하는 모든 정수 $x$의 개수는?",
    options:opts4("$5$","$6$","$7$","$8$"),
    correct:"3",
    explanation:"$|2x-3|<7\\Rightarrow-2<x<5$. 끝점: $x=-2$ 발산($\\sum 1/\\sqrt{n}$), $x=5$ 수렴(교대급수).\n수렴 범위 $-2<x\\le 5$. 정수 $x=-1,0,1,2,3,4,5$ 7개.",
  },
  {n:36, subject:"다변수함수", unit:"극좌표와 극곡선", concept:"카디오이드 둘레 길이",
    difficulty:"easy",
    question:"극곡선 $r=2+2\\sin\\theta$의 둘레의 길이는?",
    options:opts4("$12$","$16$","$20$","$24$"),
    correct:"2",
    explanation:"$r=a(1+\\sin\\theta)$ (카디오이드)의 길이 $=8a$. $a=2$이므로 $L=16$.",
  },
  {n:37, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"사면체 부피 (스칼라삼중적)",
    difficulty:"easy",
    question:"3차원 공간에서 네 점 $P(-2,1,0),\\,Q(2,3,2),\\,R(2,4,-2),\\,S(3,6,0)$을 꼭짓점으로 하는 사면체 $PQRS$의 부피는?",
    options:opts4("$5$","$7$","$9$","$11$"),
    correct:"1",
    explanation:"$\\vec{PQ}=(4,2,2),\\,\\vec{PR}=(4,3,-2),\\,\\vec{PS}=(5,5,0)$.\n$V=\\dfrac{1}{6}|\\det|=\\dfrac{1}{6}|4(0+10)-2(0+10)+2(20-15)|=\\dfrac{1}{6}|40-20+10|=5$.",
  },
  {n:38, subject:"다변수함수", unit:"편미분", concept:"방향도함수 (점→점 방향)",
    difficulty:"easy",
    question:"점 $P(2,0)$에서부터 점 $Q\\!\\left(\\dfrac{1}{2},2\\right)$까지의 방향으로 점 $P(2,0)$에서 함수 $f(x,y)=xe^y$의 방향도함수는?",
    options:opts4("$\\dfrac{1}{2}$","$1$","$\\dfrac{3}{2}$","$2$"),
    correct:"2",
    explanation:"$\\vec{PQ}=(-3/2,2)$, $|\\vec{PQ}|=5/2$. $\\hat v=(-3/5,4/5)$.\n$\\nabla f=(e^y,xe^y)|_{(2,0)}=(1,2)$.\n$D_{\\hat v}f=(1,2)\\cdot(-3/5,4/5)=-3/5+8/5=1$.",
  },
  {n:39, subject:"다변수함수", unit:"삼중적분", concept:"원뿔 + 평면 영역",
    difficulty:"medium",
    question:"양의 실수 $a$에 대하여, $E$를 곡면 $z=\\sqrt{x^2+y^2}$과 평면 $z=a$로 둘러싸인 입체라 하자. 삼중적분 $\\displaystyle\\iiint_E(x^2+y^2)\\,dV$의 값이 $\\dfrac{16}{5}\\pi$일 때, $a$의 값은?",
    options:opts4("$\\dfrac{1}{2}$","$1$","$\\dfrac{3}{2}$","$2$"),
    correct:"4",
    explanation:"원주좌표: $\\!\\int_0^{2\\pi}\\!\\!\\int_0^a\\!\\!\\int_r^a r^2\\cdot r\\,dz\\,dr\\,d\\theta=2\\pi\\!\\int_0^a(a-r)r^3\\,dr=2\\pi\\!\\left(\\dfrac{a^5}{4}-\\dfrac{a^5}{5}\\right)=\\dfrac{a^5\\pi}{10}=\\dfrac{16\\pi}{5}\\Rightarrow a^5=32\\Rightarrow a=2$.",
  },
  {n:40, subject:"다변수함수", unit:"다변수 극값", concept:"제약영역 최대·최솟값 합",
    difficulty:"medium",
    question:"세 점 $(0,0),(3,3),(-3,3)$을 꼭짓점으로 하는 삼각형 영역을 $D$라 하자. $D$ 위에서 정의된 함수 $f(x,y)=4y-x^2-y^2$의 최댓값을 $M$, 최솟값을 $m$이라 할 때, $M+m$의 값은?",
    options:opts4("$-6$","$-4$","$-2$","$0$"),
    correct:"3",
    explanation:"임계점 내부: $f_x=-2x=0,\\,f_y=4-2y=0\\Rightarrow(0,2)$ ∈ $D$, $f(0,2)=4$.\n경계 분석으로 최솟값 $-6$ ($(\\pm 3,3)$). 최댓값 $4$.\n$M+m=4+(-6)=-2$.",
  },
  {n:41, subject:"다변수함수", unit:"이중적분", concept:"이차형식 변수변환",
    difficulty:"hard",
    question:"영역 $D=\\{(x,y)\\mid x^2-xy+y^2\\le 2\\}$에 대하여 이중적분 $\\displaystyle\\iint_D(x^2-xy+y^2)\\,dA$의 값은?",
    options:opts4("$\\dfrac{\\sqrt{3}}{3}\\pi$","$\\dfrac{2\\sqrt{3}}{3}\\pi$","$\\sqrt{3}\\pi$","$\\dfrac{4\\sqrt{3}}{3}\\pi$"),
    correct:"4",
    explanation:"이차형식 대각화: $x^2-xy+y^2=(3/2)X^2+(1/2)Y^2$ (적절한 회전 후).\n변수변환 $\\sqrt{3}X=a,\\,Y=b$: $a^2+b^2\\le 4$.\n$\\!\\iint=\\dfrac{1}{2\\sqrt{3}}\\!\\iint(a^2+b^2)\\,dadb=\\dfrac{1}{2\\sqrt{3}}\\cdot\\dfrac{1}{2}\\cdot 2\\pi\\cdot 2^2=\\dfrac{4\\pi}{\\sqrt{3}}=\\dfrac{4\\sqrt{3}\\pi}{3}$.",
  },
  {n:42, subject:"다변수함수", unit:"선적분", concept:"그린 정리 + 닫힌 경로",
    difficulty:"hard",
    question:"곡선 $C$는 (i) 점 $(0,0)$에서 점 $(1,e)$까지 선분 $C_1$, (ii) 곡선 $y=e^x$ 위의 점 $(1,e)$에서 점 $(2,e^2)$까지 호 $C_2$, (iii) 곡선 $y=\\dfrac{e^2}{4}(x-4)^2$ 위의 점 $(2,e^2)$에서 점 $(4,0)$까지 호 $C_3$로 이루어져 있다. 벡터장 $\\vec{F}(x,y)=\\langle 3+2xy,\\,x^2-3y^2+\\cos y^2\\rangle$에 대하여 선적분 $\\displaystyle\\int_C\\vec{F}\\cdot d\\vec{r}$의 값은?",
    options:opts4("$3e^2$","$12$","$9e^2$","$15$"),
    correct:"2",
    explanation:"$\\vec F$ 보존 ($P_y=2x=Q_x$). 포텐셜 $\\phi=3x+x^2y-y^3+\\!\\int\\cos y^2 dy$.\n$\\!\\int_C\\vec F\\cdot d\\vec r=\\phi(4,0)-\\phi(0,0)=12-0=12$.",
  },
  {n:43, subject:"다변수함수", unit:"공간곡면", concept:"매개변수 곡면 면적",
    difficulty:"hard",
    question:"곡면 $S$의 매개변수표현이 $x=r\\cos\\theta,\\,y=r\\sin\\theta,\\,z=\\theta$ ($0\\le\\theta\\le 2\\pi,\\,0\\le r\\le 1$)일 때, $S$의 넓이는?",
    options:opts4("$\\pi(1+\\ln(1+\\sqrt{2}))$","$2\\pi(1+\\ln(1+\\sqrt{2}))$","$\\pi(\\sqrt{2}+\\ln(1+\\sqrt{2}))$","$2\\pi(\\sqrt{2}+\\ln(1+\\sqrt{2}))$"),
    correct:"3",
    explanation:"$|S_r\\times S_\\theta|=\\sqrt{r^2+1}$. 면적 $=2\\pi\\!\\int_0^1\\sqrt{r^2+1}\\,dr$.\n$r=\\tan x$ 치환: $2\\pi\\!\\int_0^{\\pi/4}\\sec^3 x\\,dx=\\pi[\\sec x\\tan x+\\ln|\\sec x+\\tan x|]_0^{\\pi/4}=\\pi(\\sqrt{2}+\\ln(\\sqrt{2}+1))$.",
  },
  {n:44, subject:"다변수함수", unit:"선적분", concept:"스토크스 정리",
    difficulty:"medium",
    question:"곡선 $C$는 평면 $x+y+z=2$와 원기둥 $x^2+y^2=4$의 교선이다. 벡터장 $\\vec{F}(x,y,z)=\\langle-y^3,x^3,-z^3\\rangle$에 대하여 선적분 $\\displaystyle\\int_C\\vec{F}\\cdot d\\vec{r}$의 값은? (단, $C$의 방향은 위에서 내려다봤을 때 시계 반대 방향이다.)",
    options:opts4("$8\\pi$","$16\\pi$","$24\\pi$","$32\\pi$"),
    correct:"3",
    explanation:"스토크스: $\\nabla\\times\\vec F=(0,0,3x^2+3y^2)$. 평면 법선 $(1,1,1)/\\sqrt{3}$.\n$\\!\\iint(3x^2+3y^2)/\\sqrt{3}\\,dS$. 평면 사영 → $\\sqrt{3}$ 배.\n$=3\\!\\iint(x^2+y^2)\\,dxdy=3\\cdot 2\\pi\\cdot\\dfrac{r^4}{4}\\bigg|_0^2=24\\pi$.",
  },
  {n:45, subject:"선형대수", unit:"행렬식", concept:"케일리-해밀턴 + 행렬식",
    difficulty:"hard",
    question:"행렬 $A=\\begin{pmatrix}1&1&5\\\\0&-1&1\\\\3&4&13\\end{pmatrix}$에 대하여 $AB=A^2-3A+E$를 만족시키는 행렬 $B$의 행렬식(determinant)은? (단, $E$는 단위행렬이다.)",
    options:opts4("$1305$","$1307$","$1309$","$1311$"),
    correct:"1",
    explanation:"$|A|=1$. $|AB|=|A^2-3A+E|=|A||B|=|B|$.\n$A^2-3A+E$ 직접 계산: 각 원소 계산 후 행렬식.\n$|A^2-3A+E|=1305$ (계산).",
  },
  {n:46, subject:"선형대수", unit:"선형변환", concept:"다항식 공간 선형변환",
    difficulty:"hard",
    question:"벡터공간 $P_2=\\{ax^2+bx+c\\mid a,b,c\\in\\mathbb{R}\\}$에 대하여 선형변환 $T:P_2\\to P_2$가 $T(x^2-x)=x-2,\\,T(x-1)=x^2-x,\\,T(x^2+1)=x^2-1$을 만족시킨다. $T(x^2-5x+2)=\\alpha x^2+\\beta x+\\gamma$일 때 $\\alpha+\\beta+\\gamma$의 값은? (단, $\\alpha,\\beta,\\gamma$는 실수이다.)",
    options:opts4("$-2$","$0$","$2$","$4$"),
    correct:"1",
    explanation:"$T(x^2-5x+2)=T(x^2)-5T(x-1)-3T(1)$ 등으로 분해... 류갓티비 결과: $-4x^2+5x-3$.\n$\\alpha+\\beta+\\gamma=-4+5-3=-2$.",
  },
  {n:47, subject:"선형대수", unit:"행렬식", concept:"행렬식 + 전치 + 스칼라곱",
    difficulty:"medium",
    question:"행렬 $A=\\begin{pmatrix}1&2&1&1\\\\3&4&2&2\\\\-1&2&2&1\\\\1&2&3&-1\\end{pmatrix}$에 대하여 $2A$의 전치행렬(transpose)의 행렬식(determinant)은?",
    options:opts4("$8$","$16$","$32$","$64$"),
    correct:"4",
    explanation:"$|A|=4$ (행 축약 계산).\n$|(2A)^T|=|2A|=2^4|A|=16\\cdot 4=64$.",
  },
  {n:48, subject:"미분학", unit:"미분방정식", concept:"코시-오일러 + 비동차",
    difficulty:"hard",
    question:"$y=y(x)$가 미분방정식 $x^2 y''+xy'-y=x,\\,y(1)=\\dfrac{1}{2},\\,y(e)=e$의 해일 때, $y(e^2)$의 값은?",
    options:opts4("$\\dfrac{1}{2}e^2$","$e^2$","$\\dfrac{3}{2}e^2$","$2e^2$"),
    correct:"3",
    explanation:"보조 $r(r-1)+r-1=r^2-1=0\\Rightarrow r=\\pm 1$. $y_h=c_1 x+c_2/x$.\n특수해: $y_p=(1/2)x\\ln x$ (변수분리법 / 매개변수 변동).\n$y=c_1 x+c_2/x+(1/2)x\\ln x$.\n$y(1)=c_1+c_2=1/2$, $y(e)=c_1 e+c_2/e+e/2=e\\Rightarrow c_1=1/2,\\,c_2=0$.\n$y(e^2)=e^2/2+e^2=3e^2/2$.",
  },
  {n:49, subject:"미분학", unit:"미분방정식", concept:"비동차 ODE + 초기조건",
    difficulty:"hard",
    question:"$y=y(x)$가 미분방정식 $y''-2y'+y=xe^x\\ln x,\\,y(1)=0,\\,y'(1)=0$의 해일 때, $y(2)$의 값은?",
    options:opts4("$\\!\\left(\\dfrac{2}{3}\\ln 2-\\dfrac{13}{18}\\right)e^2$","$\\!\\left(\\dfrac{4}{3}\\ln 2-\\dfrac{13}{18}\\right)e^2$","$\\!\\left(\\dfrac{2}{3}\\ln 2-\\dfrac{11}{18}\\right)e^2$","$\\!\\left(\\dfrac{4}{3}\\ln 2-\\dfrac{11}{18}\\right)e^2$"),
    correct:"2",
    explanation:"보조방정식 $r^2-2r+1=0\\Rightarrow r=1$ 중근. $y_h=(c_1+c_2 x)e^x$.\n특수해: $y_p=e^x(x^3/6\\ln x-5x^3/36)$ (반복 부분적분).\n초기조건으로 $c_1,\\,c_2$ 결정 후: $y(2)=(\\dfrac{4}{3}\\ln 2-\\dfrac{13}{18})e^2$.",
  },
  {n:50, subject:"적분학", unit:"라플라스 변환", concept:"역라플라스 + 진폭·주기",
    difficulty:"medium",
    question:"역라플라스변환(inverse Laplace transform) $\\mathcal{L}^{-1}\\!\\left\\{\\dfrac{3s+4\\sqrt{5}}{s^2+5}\\right\\}$를 $f(t)$라 하자. $f(t)$의 최댓값을 $\\alpha$, 주기를 $\\beta$라 할 때, $\\alpha\\beta^2$의 값은?",
    options:opts4("$2\\pi^2$","$4\\pi^2$","$6\\pi^2$","$8\\pi^2$"),
    correct:"2",
    explanation:"$f(t)=3\\cos(\\sqrt{5}t)+4\\sin(\\sqrt{5}t)=5\\sin(\\sqrt{5}t+\\alpha)$.\n최댓값 $=5$, 주기 $=2\\pi/\\sqrt{5}$.\n$\\alpha\\beta^2=5\\cdot(2\\pi/\\sqrt{5})^2=5\\cdot 4\\pi^2/5=4\\pi^2$.",
  },
];

const TOTAL=PROBLEMS.length;
console.log(`총 ${TOTAL}문제 (객관식 4지선다) 준비됨`);

const rows = PROBLEMS.map(p => {
  const id = `q-${YEAR_ID}-${SCHOOL_EN}-${String(p.n).padStart(2,"0")}`;
  return {
    id, subject: p.subject, unit: p.unit, concept: p.concept, difficulty: p.difficulty,
    source_type: "imported", pool: "general", question: p.question, content_type: "latex",
    question_image: null, question_type: "multiple_choice",
    options: p.options, correct_option_id: p.correct,
    answer_text: null, explanation: p.explanation, explanation_content_type: "latex",
    explanation_image: null,
    tags: [YEAR_KO, SCHOOL_KO, SESSION_KO, "past_exam", p.subject, p.unit, p.concept],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  };
});

const { data, error } = await sb.from("questions").upsert(rows, { onConflict: "id" }).select("id");
if (error) { console.error("업로드 실패:", error); process.exit(1); }
console.log(`업로드 완료: ${data.length}건`);
