// 2018년 서강대 편입수학 객관식 20문항 (5지선다)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR="2018", SCHOOL_KO="서강대", SCHOOL_EN="sogang";
const opts5 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:1, subject:"미분학", unit:"극한과 연속", concept:"연속·미분가능 명제",
    difficulty:"medium",
    question:"다음 \\<보기\\>에서 옳은 것만을 있는 대로 고른 것은?\n(ㄱ) 함수 $f$가 닫힌 구간 $[a,b]$에서 연속이고 $f(a)f(b)<0$이면 $f(c)=0$이 되는 $c$가 열린 구간 $(a,b)$에 적어도 하나 존재한다.\n(ㄴ) 함수 $f$가 구간 $(a,b)$에서 미분가능하며 임의의 $x\\in(a,b)$에 대하여 $f'(x)\\ne 0$이면 $f$는 $(a,b)$에서 일대일 함수이다.\n(ㄷ) 함수 $g(x)=\\begin{cases}0,&(0\\le x\\le 1)\\\\1,&(1<x\\le 2)\\end{cases}$이면 임의의 $x\\in(0,2)$에 대하여 $G'(x)=g(x)$인 함수 $G$가 구간 $(0,2)$에서 존재한다.",
    options:opts5("(ㄱ)","(ㄷ)","(ㄱ), (ㄴ)","(ㄴ), (ㄷ)","(ㄱ), (ㄴ), (ㄷ)"),
    correct:"3",
    explanation:"(ㄱ) 중간값 정리. **참**.\n(ㄴ) $f'(x)\\ne 0$이고 $f'$이 다르부 성질을 가지므로 $(a,b)$에서 부호가 일정. 따라서 $f$는 단조이고 일대일. **참**.\n(ㄷ) $g$가 점프 불연속이면 다르부 성질이 없어 도함수가 될 수 없다. $G'=g$인 $G$ 존재 X. **거짓**.\n따라서 (ㄱ), (ㄴ).",
  },
  {n:2, subject:"미분학", unit:"도함수의 활용", concept:"$e^x\\cos x$ 성질",
    difficulty:"medium",
    question:"함수 $f(x)=e^x\\cos x$라고 할 때 다음 \\<보기\\>에서 옳은 것만을 있는 대로 고른 것은?\n(ㄱ) $\\displaystyle\\lim_{x\\to-\\infty}f(x)=0$.\n(ㄴ) $\\displaystyle\\int_0^{3\\pi/4}f(x)\\,dx=-\\dfrac{1}{2}$.\n(ㄷ) 임의의 자연수 $n$에 대하여 함수 $f$가 구간 $(-n\\pi,n\\pi)$에 속하는 $a_n$개의 점에서 극값을 가진다고 할 때 $\\displaystyle\\lim_{n\\to\\infty}\\dfrac{a_n}{n}=2$이다.",
    options:opts5("(ㄱ)","(ㄱ), (ㄴ)","(ㄱ), (ㄷ)","(ㄴ), (ㄷ)","(ㄱ), (ㄴ), (ㄷ)"),
    correct:"5",
    explanation:"(ㄱ) $|e^x\\cos x|\\le e^x\\to 0$ ($x\\to-\\infty$). **참**.\n(ㄴ) $\\!\\int e^x\\cos x\\,dx=\\dfrac{1}{2}e^x(\\sin x+\\cos x)+C$.\n$\\dfrac{1}{2}e^{3\\pi/4}(\\sin\\dfrac{3\\pi}{4}+\\cos\\dfrac{3\\pi}{4})-\\dfrac{1}{2}(0+1)=0-\\dfrac{1}{2}=-\\dfrac{1}{2}$. **참**.\n(ㄷ) $f'(x)=e^x(\\cos x-\\sin x)=0\\Rightarrow x=\\dfrac{\\pi}{4}+k\\pi$. $(-n\\pi,n\\pi)$에 정수 $k$가 $-n,\\cdots,n-1$로 $2n$개. $\\dfrac{a_n}{n}\\to 2$. **참**.\n모두 옳음.",
  },
  {n:3, subject:"미분학", unit:"도함수", concept:"역함수의 2계 도함수",
    difficulty:"hard",
    question:"함수 $f(x)=x^3+e^{2x}$의 역함수 $g$에 대하여 $\\{g''(1)\\}^2=\\dfrac{q}{p}$라고 할 때 $p+q$의 값은? (단, $p,q$는 서로 소인 자연수이다.)",
    options:opts5("$5$","$10$","$13$","$17$","$25$"),
    correct:"1",
    explanation:"$f(0)=1$이므로 $g(1)=0$. $f'(x)=3x^2+2e^{2x},\\,f'(0)=2$. $g'(1)=\\dfrac{1}{2}$.\n$g''(y)=-\\dfrac{f''(g(y))}{[f'(g(y))]^3}$. $f''(x)=6x+4e^{2x},\\,f''(0)=4$.\n$g''(1)=-\\dfrac{4}{8}=-\\dfrac{1}{2}$.\n$\\{g''(1)\\}^2=\\dfrac{1}{4}=\\dfrac{q}{p}\\Rightarrow p=4,\\,q=1$. $p+q=5$.",
  },
  {n:4, subject:"적분학", unit:"이상적분", concept:"이상적분 수렴판정",
    difficulty:"medium",
    question:"다음 \\<보기\\>의 이상적분(Improper Integral) 중에서 수렴하는 것만을 있는 대로 고른 것은?\n(ㄱ) $\\displaystyle\\int_{-\\infty}^{\\infty}e^{-x^2+2x}\\,dx$\n(ㄴ) $\\displaystyle\\int_1^{\\infty}\\dfrac{1+e^{-2x}}{2x}\\,dx$\n(ㄷ) $\\displaystyle\\int_0^1(x+1)\\ln x\\,dx$",
    options:opts5("(ㄱ)","(ㄴ)","(ㄱ), (ㄷ)","(ㄴ), (ㄷ)","(ㄱ), (ㄴ), (ㄷ)"),
    correct:"3",
    explanation:"(ㄱ) $e^{-x^2+2x}=e\\cdot e^{-(x-1)^2}$. 가우스 적분 $=e\\sqrt{\\pi}$. **수렴**.\n(ㄴ) $x\\to\\infty$에서 $\\dfrac{1}{2x}$와 비교, 발산. **발산**.\n(ㄷ) $x\\to 0^+$에서 $(x+1)\\ln x\\to 0\\cdot(-\\infty)$이지만 $x\\ln x\\to 0$이고 $\\!\\int_0^1\\ln x\\,dx=-1$, $\\!\\int_0^1 x\\ln x\\,dx=-1/4$로 모두 수렴. **수렴**.\n따라서 (ㄱ), (ㄷ).",
  },
  {n:5, subject:"적분학", unit:"정적분의 응용", concept:"회전체 부피와 겉넓이",
    difficulty:"hard",
    question:"곡선 $x=2-y^2$과 직선 $x=1$로 둘러싸인 영역을 $x$축을 중심으로 회전시켜 얻은 입체의 겉넓이 $S$와 부피 $V$의 비 $\\dfrac{S}{V}$의 값은?",
    options:opts5("$\\dfrac{5(\\sqrt{5}-1)}{3}$","$\\dfrac{5\\sqrt{5}-1}{3}$","$\\dfrac{5\\sqrt{5}}{3}$","$\\dfrac{5\\sqrt{5}+1}{3}$","$\\dfrac{5(\\sqrt{5}+1)}{3}$"),
    correct:"5",
    explanation:"교점 $y=\\pm 1$, 영역 $1\\le x\\le 2-y^2$.\n부피(disk): $V=\\!\\int_1^2\\pi(2-x)\\,dx=\\dfrac{\\pi}{2}$.\n겉넓이: 곡면 $S_1=\\!\\int_1^2 2\\pi y\\sqrt{1+y'^2}\\,dx$. $y=\\sqrt{2-x},\\,y'=-\\dfrac{1}{2\\sqrt{2-x}}$.\n$y\\sqrt{1+y'^2}=\\dfrac{\\sqrt{9-4x}}{2}$이므로 $S_1=\\pi\\!\\int_1^2\\sqrt{9-4x}\\,dx=\\dfrac{\\pi}{6}(5\\sqrt{5}-1)$.\n원판 $S_2=\\pi\\cdot 1^2=\\pi$. 합 $S=\\dfrac{\\pi}{6}(5\\sqrt{5}+5)=\\dfrac{5\\pi}{6}(\\sqrt{5}+1)$.\n$\\dfrac{S}{V}=\\dfrac{5(\\sqrt{5}+1)}{3}$.",
  },
  {n:6, subject:"적분학", unit:"급수의 수렴/발산", concept:"멱급수 수렴구간",
    difficulty:"medium",
    question:"다음 \\<보기\\>의 멱급수 중에서 수렴구간이 $[-1,1]$을 포함하는 것만을 있는 대로 고른 것은?\n(ㄱ) $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{x^n}{n\\ln(n+1)}$\n(ㄴ) $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{2^n x^n}{n!}$\n(ㄷ) $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{\\cos(n\\pi/2)x^n}{n^2}$",
    options:opts5("(ㄴ)","(ㄱ), (ㄴ)","(ㄱ), (ㄷ)","(ㄴ), (ㄷ)","(ㄱ), (ㄴ), (ㄷ)"),
    correct:"4",
    explanation:"(ㄱ) 수렴반경 $1$. $x=1$: $\\!\\sum\\dfrac{1}{n\\ln(n+1)}$ 적분판정으로 발산. $[-1,1]$ 포함 X.\n(ㄴ) 수렴반경 $\\infty$. 모든 $x$에서 수렴. ✓\n(ㄷ) $|a_n|\\le\\dfrac{1}{n^2}$이므로 $|x|\\le 1$에서 절대수렴. ✓\n따라서 (ㄴ), (ㄷ).",
  },
  {n:7, subject:"적분학", unit:"급수의 수렴/발산", concept:"테일러 급수 적분 근사",
    difficulty:"medium",
    question:"적분 $\\displaystyle\\int_0^1\\cos(x^2)\\,dx$의 값에 가장 가까운 근삿값은?",
    options:opts5("$\\dfrac{9}{10}-\\dfrac{5}{216}$","$\\dfrac{9}{10}+\\dfrac{1}{216}$","$\\dfrac{9}{10}+\\dfrac{7}{216}$","$\\dfrac{9}{10}+\\dfrac{12}{216}$","$\\dfrac{9}{10}+\\dfrac{18}{216}$"),
    correct:"2",
    explanation:"$\\cos(x^2)=1-\\dfrac{x^4}{2}+\\dfrac{x^8}{24}-\\dfrac{x^{12}}{720}+\\cdots$.\n$\\!\\int_0^1\\cos(x^2)\\,dx=1-\\dfrac{1}{10}+\\dfrac{1}{216}-\\dfrac{1}{9360}+\\cdots\\approx\\dfrac{9}{10}+\\dfrac{1}{216}$.\n교대급수 잔차로 다음 항이 작아 가장 가까움.",
  },
  {n:8, subject:"적분학", unit:"극좌표", concept:"극곡선 수평 접선",
    difficulty:"hard",
    question:"극좌표로 표현된 곡선 $r=\\dfrac{7}{2}+3\\sin\\theta-2\\cos^2\\theta$ 위에서 수평인 접선을 갖는 점의 $(x,y)$좌표에 해당하는 것은?",
    options:opts5("$\\left(-\\dfrac{\\sqrt{3}}{2},-\\dfrac{1}{2}\\right)$","$\\left(-\\dfrac{\\sqrt{3}}{4},-\\dfrac{1}{4}\\right)$","$\\left(-\\dfrac{\\sqrt{3}}{2},\\dfrac{1}{2}\\right)$","$\\left(-\\dfrac{\\sqrt{3}}{4},\\dfrac{1}{4}\\right)$","$\\left(\\dfrac{\\sqrt{3}}{2},\\dfrac{1}{2}\\right)$"),
    correct:"2",
    explanation:"$\\dfrac{dy}{d\\theta}=r'\\sin\\theta+r\\cos\\theta$. $r'=3\\cos\\theta+4\\cos\\theta\\sin\\theta=\\cos\\theta(3+4\\sin\\theta)$.\n계산하면 $\\dfrac{dy}{d\\theta}=\\dfrac{3}{2}\\cos\\theta(2\\sin\\theta+1)^2$.\n$\\dfrac{dy}{d\\theta}=0\\Rightarrow\\cos\\theta=0$ 또는 $\\sin\\theta=-\\dfrac{1}{2}$.\n$\\theta=\\dfrac{7\\pi}{6}$: $\\sin=-\\dfrac{1}{2},\\,\\cos=-\\dfrac{\\sqrt{3}}{2}$, $r=\\dfrac{7}{2}-\\dfrac{3}{2}-\\dfrac{3}{2}=\\dfrac{1}{2}$.\n$(x,y)=\\dfrac{1}{2}\\!\\left(-\\dfrac{\\sqrt{3}}{2},-\\dfrac{1}{2}\\right)=\\left(-\\dfrac{\\sqrt{3}}{4},-\\dfrac{1}{4}\\right)$.",
  },
  {n:9, subject:"적분학", unit:"극좌표", concept:"극곡선 호의 길이",
    difficulty:"hard",
    question:"극좌표로 표현된 곡선 $r=1-\\sin\\theta$에서 원 $r=1-\\dfrac{\\sqrt{3}}{2}$ 안에 있는 부분의 길이는?",
    options:opts5("$8-2\\sqrt{2}-2\\sqrt{6}$","$9-2\\sqrt{3}-2\\sqrt{6}$","$10-3\\sqrt{2}-2\\sqrt{6}$","$6-2\\sqrt{2}-\\sqrt{6}$","$10-4\\sqrt{3}-\\sqrt{6}$"),
    correct:"1",
    explanation:"교점 $\\sin\\theta=\\dfrac{\\sqrt{3}}{2}\\Rightarrow\\theta=\\dfrac{\\pi}{3},\\dfrac{2\\pi}{3}$. 원 안 영역 $\\dfrac{\\pi}{3}\\le\\theta\\le\\dfrac{2\\pi}{3}$.\n$r^2+r'^2=2(1-\\sin\\theta)=(\\,\\sin\\dfrac{\\theta}{2}-\\cos\\dfrac{\\theta}{2}\\,)^2\\cdot 2$.\n$L=\\sqrt{2}\\!\\int_{\\pi/3}^{2\\pi/3}\\!\\left|\\sin\\dfrac{\\theta}{2}-\\cos\\dfrac{\\theta}{2}\\right|d\\theta$.\n$\\dfrac{\\pi}{2}$에서 분할: $L=\\sqrt{2}\\cdot 2(2\\sqrt{2}-1-\\sqrt{3})=8-2\\sqrt{2}-2\\sqrt{6}$.",
  },
  {n:10, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"평행육면체 부피 최대",
    difficulty:"medium",
    question:"세 벡터 $(0,1,1),\\,(-1,1,2),\\,(x,y,1)$로 이루어진 평행육면체의 부피의 최댓값은? (단, 벡터 $(x,y,1)$의 길이는 $\\sqrt{2}$이다.)",
    options:opts5("$1+\\sqrt{2}$","$2+\\sqrt{2}$","$2-\\sqrt{2}$","$3-\\sqrt{2}$","$4-\\sqrt{2}$"),
    correct:"1",
    explanation:"부피 $=|\\det A|$, $A$의 행이 세 벡터.\n행렬식 전개: $\\det=0(1-2y)-1(-1-2x)+1(-y-x)=1+x-y$.\n제약 $x^2+y^2+1=2\\Rightarrow x^2+y^2=1$.\n$1+x-y$의 최댓값은 $1+\\sqrt{2}$ (코시-슈바르츠 또는 $(x,y)=\\!\\left(\\dfrac{1}{\\sqrt{2}},-\\dfrac{1}{\\sqrt{2}}\\right)$).",
  },
  {n:11, subject:"다변수함수", unit:"선적분과 면적분", concept:"3차원 곡선 선적분",
    difficulty:"medium",
    question:"곡선 $C$가 $\\vec{r}(t)=(\\cos t,\\sin t,3t)\\;(0\\le t\\le 2\\pi)$로 주어졌을 때 $C$ 위에서 벡터장 $\\vec{F}(x,y,z)=z\\vec{i}+x\\vec{j}+y\\vec{k}$의 선적분의 값은?",
    options:opts5("$\\pi$","$3\\pi$","$5\\pi$","$7\\pi$","$9\\pi$"),
    correct:"4",
    explanation:"$\\vec{r}\\,'(t)=(-\\sin t,\\cos t,3)$, $\\vec{F}(\\vec{r}(t))=(3t,\\cos t,\\sin t)$.\n$\\vec{F}\\cdot\\vec{r}\\,'=-3t\\sin t+\\cos^2 t+3\\sin t$.\n$\\!\\int_0^{2\\pi}-3t\\sin t\\,dt=-3[-t\\cos t+\\sin t]_0^{2\\pi}=-3(-2\\pi)=6\\pi$.\n$\\!\\int_0^{2\\pi}\\cos^2 t\\,dt=\\pi$, $\\!\\int_0^{2\\pi}3\\sin t\\,dt=0$.\n합 $=6\\pi+\\pi=7\\pi$.",
  },
  {n:12, subject:"다변수함수", unit:"편도함수", concept:"라플라스 방정식 해",
    difficulty:"medium",
    question:"다음 \\<보기\\>의 함수 중에서 라플라스 방정식 $u_{xx}+u_{yy}=0$을 만족하는 것의 개수는?\n(ㄱ) $u=x^2+y^2$\n(ㄴ) $u=x^2-y^2$\n(ㄷ) $u=x^3+3xy^2$\n(ㄹ) $u=\\ln\\sqrt{x^2+y^2}$\n(ㅁ) $u=\\sin x\\cosh y+\\cos x\\sinh y$\n(ㅂ) $u=e^{-x}\\cos y-e^{-y}\\cos x$",
    options:opts5("$1$","$2$","$3$","$4$","$5$"),
    correct:"4",
    explanation:"(ㄱ) $u_{xx}+u_{yy}=4\\ne 0$. X.\n(ㄴ) $2-2=0$. ✓\n(ㄷ) $u_{xx}=6x,\\,u_{yy}=6x$. 합 $12x\\ne 0$. X.\n(ㄹ) $\\dfrac{1}{2}\\ln(x^2+y^2)$, $u_{xx}+u_{yy}=0$ (조화). ✓\n(ㅁ) $u_{xx}=-u,\\,u_{yy}=u$, 합 $=0$. ✓\n(ㅂ) $u_{xx}=e^{-x}\\cos y+e^{-y}\\cos x,\\,u_{yy}=-e^{-x}\\cos y-e^{-y}\\cos x$, 합 $=0$. ✓\n총 4개.",
  },
  {n:13, subject:"다변수함수", unit:"중적분", concept:"적분순서 변경",
    difficulty:"medium",
    question:"반복적분 $\\displaystyle\\int_0^1\\!\\int_x^1 e^{x/y}\\,dy\\,dx$의 값은?",
    options:opts5("$\\dfrac{e+1}{2}$","$\\dfrac{e-1}{2}$","$e+1$","$\\dfrac{e-1}{3}$","$\\dfrac{e+1}{3}$"),
    correct:"2",
    explanation:"영역 $\\{(x,y):0\\le x\\le y\\le 1\\}$. 적분순서 변경: $y\\in[0,1],\\,x\\in[0,y]$.\n$\\!\\int_0^1\\!\\!\\int_0^y e^{x/y}\\,dx\\,dy=\\!\\int_0^1 y[e^{x/y}]_0^y\\,dy=\\!\\int_0^1 y(e-1)\\,dy=\\dfrac{e-1}{2}$.",
  },
  {n:14, subject:"다변수함수", unit:"중적분", concept:"극좌표 변환 부피",
    difficulty:"medium",
    question:"포물면 $z=x^2+y^2$, 평면 $z=0$, 원기둥 $x^2+y^2-2x=0$으로 둘러싸인 입체의 부피는?",
    options:opts5("$\\dfrac{\\pi}{2}$","$\\pi$","$\\dfrac{3\\pi}{2}$","$2\\pi$","$\\dfrac{5\\pi}{2}$"),
    correct:"3",
    explanation:"원기둥 $(x-1)^2+y^2=1$, 극좌표 $r=2\\cos\\theta,\\,\\theta\\in[-\\pi/2,\\pi/2]$.\n$V=\\!\\int_{-\\pi/2}^{\\pi/2}\\!\\!\\int_0^{2\\cos\\theta}r^2\\cdot r\\,dr\\,d\\theta=\\!\\int_{-\\pi/2}^{\\pi/2}\\dfrac{(2\\cos\\theta)^4}{4}\\,d\\theta=4\\!\\int_{-\\pi/2}^{\\pi/2}\\cos^4\\theta\\,d\\theta$.\n$\\!\\int_{-\\pi/2}^{\\pi/2}\\cos^4\\theta\\,d\\theta=\\dfrac{3\\pi}{8}$이므로 $V=4\\cdot\\dfrac{3\\pi}{8}=\\dfrac{3\\pi}{2}$.",
  },
  {n:15, subject:"미분학", unit:"미분방정식", concept:"적분인자",
    difficulty:"medium",
    question:"완전(Exact) 미분방정식 아닌 $(e^{x+y}+ye^y)dx=(1-xe^y)dy$를 완전 미분방정식으로 변환하는 적분인자(Integrating factor)가 될 수 있는 것은?",
    options:opts5("$e^x$","$e^{-x}$","$x$","$e^y$","$e^{-y}$"),
    correct:"5",
    explanation:"$(e^{x+y}+ye^y)dx+(xe^y-1)dy=0$.\n$M_y=e^{x+y}+e^y(1+y),\\,N_x=e^y$. $\\dfrac{N_x-M_y}{M}=\\dfrac{-e^{x+y}-ye^y}{e^{x+y}+ye^y}=-1$ ($y$만의 함수).\n적분인자 $\\mu(y)=e^{\\!\\int(-1)dy}=e^{-y}$.\n검증: $\\mu M=e^x+y$의 $y$미분 $=1$, $\\mu N=x-e^{-y}$의 $x$미분 $=1$. **완전**.",
  },
  {n:16, subject:"미분학", unit:"미분방정식", concept:"동반행렬과 고윳값",
    difficulty:"medium",
    question:"미분 방정식 $y''+2y'+\\dfrac{3}{4}y=0$을 연립 미분방정식 $\\begin{pmatrix}y'\\\\y''\\end{pmatrix}=\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}\\!\\begin{pmatrix}y\\\\y'\\end{pmatrix}$으로 나타낼 수 있다. 행렬 $\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}$의 고윳값(eigenvalue)을 $\\lambda_1,\\lambda_2$라 할 때 $a+b+c+d+\\dfrac{\\lambda_1}{\\lambda_2}$의 값은? (단, $a,b,c,d$는 상수이고 $|\\lambda_1|>|\\lambda_2|$이다.)",
    options:opts5("$\\dfrac{3}{4}$","$1$","$\\dfrac{5}{4}$","$\\dfrac{3}{2}$","$2$"),
    correct:"3",
    explanation:"$y'=y',\\,y''=-\\dfrac{3}{4}y-2y'$이므로 $a=0,\\,b=1,\\,c=-\\dfrac{3}{4},\\,d=-2$.\n특성방정식 $r^2+2r+\\dfrac{3}{4}=0\\Rightarrow r=-\\dfrac{1}{2},-\\dfrac{3}{2}$.\n$|\\lambda_1|>|\\lambda_2|\\Rightarrow\\lambda_1=-\\dfrac{3}{2},\\,\\lambda_2=-\\dfrac{1}{2}$. $\\dfrac{\\lambda_1}{\\lambda_2}=3$.\n$0+1-\\dfrac{3}{4}-2+3=\\dfrac{5}{4}$.",
  },
  {n:17, subject:"미분학", unit:"미분방정식", concept:"라플라스 역변환",
    difficulty:"medium",
    question:"$L$을 라플라스 변환(Laplace transform)이라 하고 $L^{-1}$을 라플라스 역변환이라고 할 때 $L^{-1}\\!\\left[\\dfrac{s^2}{(s^2+4)^2}\\right]$는?",
    options:opts5("$\\dfrac{\\sin 2t+2t\\cos 2t}{4}$","$\\dfrac{\\sin 2t-2t\\cos 2t}{4}$","$\\dfrac{2\\sin 2t+t\\cos 2t}{4}$","$\\dfrac{2\\sin 2t-t\\cos 2t}{4}$","$\\dfrac{2t\\sin 2t+\\cos 2t}{4}$"),
    correct:"1",
    explanation:"$\\dfrac{s^2}{(s^2+4)^2}=\\dfrac{1}{s^2+4}-\\dfrac{4}{(s^2+4)^2}$.\n$L^{-1}\\!\\left\\{\\dfrac{1}{s^2+4}\\right\\}=\\dfrac{\\sin 2t}{2}$.\n$L\\{\\sin 2t-2t\\cos 2t\\}=\\dfrac{16}{(s^2+4)^2}$이므로 $L^{-1}\\!\\left\\{\\dfrac{1}{(s^2+4)^2}\\right\\}=\\dfrac{\\sin 2t-2t\\cos 2t}{16}$.\n$L^{-1}\\!\\left\\{\\dfrac{s^2}{(s^2+4)^2}\\right\\}=\\dfrac{\\sin 2t}{2}-\\dfrac{\\sin 2t-2t\\cos 2t}{4}=\\dfrac{\\sin 2t+2t\\cos 2t}{4}$.",
  },
  {n:18, subject:"선형대수", unit:"고유치와 대각화", concept:"고유공간 정사영",
    difficulty:"hard",
    question:"행렬 $\\begin{pmatrix}1&1&2\\\\1&1&0\\\\2&-2&0\\end{pmatrix}$의 고윳값 중 가장 큰 것을 $\\lambda$라 하고 $\\lambda$에 대응하는 고유공간(eigenspace)을 $E_\\lambda$라 하자. 벡터 $b=(3,2,1)$의 $E_\\lambda$ 위로의 정사영을 $p=(p_1,p_2,p_3)$라고 할 때 $\\lambda+p_1+p_2+p_3$의 값은?",
    options:opts5("$4$","$\\dfrac{29}{7}$","$5$","$\\dfrac{31}{5}$","$7$"),
    correct:"5",
    explanation:"특성다항식 $-(\\lambda-2)^2(\\lambda+2)$. 가장 큰 고윳값 $\\lambda=2$.\n$(A-2I)v=0$: $-x+y+2z=0,\\,x-y=0,\\,2x-2y-2z=0\\Rightarrow x=y,\\,z=0$. $E_\\lambda=\\mathrm{span}\\{(1,1,0)\\}$.\n정사영 $p=\\dfrac{(3,2,1)\\cdot(1,1,0)}{(1,1,0)\\cdot(1,1,0)}(1,1,0)=\\dfrac{5}{2}(1,1,0)=\\!\\left(\\dfrac{5}{2},\\dfrac{5}{2},0\\right)$.\n$p_1+p_2+p_3=5$. $\\lambda+5=7$.",
  },
  {n:19, subject:"선형대수", unit:"행렬", concept:"계수와 영공간",
    difficulty:"medium",
    question:"계수행렬이 $A=\\begin{pmatrix}1&2&3&3\\\\5&7&8&\\alpha\\\\3&3&2&1\\end{pmatrix}$인 방정식 $A\\vec{x}=\\vec{b}$ (단, $\\alpha\\in\\mathbb{R},\\,\\vec{x}\\in\\mathbb{R}^4$)에 대하여 해를 가지지 않는 $\\vec{b}\\in\\mathbb{R}^3$가 존재한다고 하자. $A$의 영공간(Null space)의 차원을 $d$라고 할 때 $\\alpha+d$의 값은?",
    options:opts5("$7$","$8$","$9$","$10$","$11$"),
    correct:"3",
    explanation:"해가 없는 $\\vec{b}$ 존재 $\\Rightarrow\\mathrm{rank}(A)<3$.\n$3\\times 3$ 부분행렬식 모두 $0$ 조건 풀면 $\\alpha=7$.\n$\\alpha=7$일 때 $\\mathrm{rank}(A)=2$, $d=4-2=2$.\n$\\alpha+d=7+2=9$.",
  },
  {n:20, subject:"선형대수", unit:"선형변환", concept:"기저 표현",
    difficulty:"medium",
    question:"선형변환(Linear Transformation) $T:\\mathbb{R}^3\\to\\mathbb{R}^3$에 대하여 $T(1,2,3)=(1,0,0),\\,T(2,3,4)=(1,1,0),\\,T(3,5,6)=(1,1,1)$이라고 하자. $T(1,3,7)=(a,b,c)$라 할 때 $abc$의 값은?",
    options:opts5("$-12$","$-10$","$0$","$8$","$56$"),
    correct:"4",
    explanation:"$(1,3,7)=a(1,2,3)+b(2,3,4)+c(3,5,6)$로 표현. 연립하면 $a=5,\\,b=1,\\,c=-2$.\n검산: $5(1,2,3)+(2,3,4)-2(3,5,6)=(1,3,7)$ ✓.\n$T(1,3,7)=5(1,0,0)+(1,1,0)-2(1,1,1)=(4,-1,-2)$.\n$abc=4\\cdot(-1)\\cdot(-2)=8$.",
  },
];

const TOTAL=PROBLEMS.length;
console.log(`총 ${TOTAL}문제 준비됨`);

const rows = PROBLEMS.map(p => {
  const id = `q-${YEAR}-${SCHOOL_EN}-${String(p.n).padStart(2,"0")}`;
  return {
    id,
    subject: p.subject,
    unit: p.unit,
    concept: p.concept,
    difficulty: p.difficulty,
    source_type: "imported",
    pool: "general",
    question: p.question,
    content_type: "latex",
    question_image: null,
    options: p.options,
    correct_option_id: p.correct,
    explanation: p.explanation,
    explanation_content_type: "latex",
    explanation_image: null,
    tags: [`year:${YEAR}`, `school:${SCHOOL_KO}`, `school_slug:${SCHOOL_EN}`, "past_exam"],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  };
});

const { data, error } = await sb.from("questions").upsert(rows, { onConflict: "id" }).select("id");
if (error) {
  console.error("업로드 실패:", error);
  process.exit(1);
}
console.log(`업로드 완료: ${data.length}건`);
