// 2017년 광운대 편입수학 객관식 30문항 (5지선다)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR="2017", SCHOOL_KO="광운대", SCHOOL_EN="kwangwoon";
const opts5 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:1, subject:"미분학", unit:"부등식", concept:"실수·집합·부등식 진위",
    difficulty:"medium",
    question:"다음 중 옳은 것을 모두 고르면?\n\nⓐ 두 실수 $a$와 $b$에 대하여 $ab=0$이면 $a=0$이고 $b=0$이다.\nⓑ 집합 $\\!\\left\\{x\\in\\mathbb{R}\\mid x=1-\\dfrac{1}{n+1},n\\in\\mathbb{N}\\right\\}$의 최소 상계는 없다.\nⓒ $x\\ge -1$이고 $n\\ge 1$이면, $(1+x)^n\\ge 1+nx$이다.",
    options:opts5("ⓐ","ⓑ","ⓒ","ⓑ, ⓒ","ⓐ, ⓒ"),
    correct:"3",
    explanation:"ⓐ [거짓] $ab=0$ ⇒ $a=0$ 또는 $b=0$ (둘 다 X).\nⓑ [거짓] 원소 $\\{1/2,2/3,3/4,\\ldots\\}$, 최소 상계 $=1$ 존재.\nⓒ [참] 베르누이 부등식. $f(x)=(1+x)^n$의 $x=0$ 접선 $y=1+nx$, $f$가 위로 볼록 X (아래) 곡선이라 $f\\ge$ 접선.",
  },
  {n:2, subject:"미분학", unit:"극한과 연속", concept:"극한 함수의 교점 범위",
    difficulty:"medium",
    question:"다음 두 함수 $f(x),g(x)$에 대해 $f(x)=g(x)$인 $x$가 포함된 범위는?\n$$f(x)=\\displaystyle\\lim_{n\\to\\infty}\\!\\left(1-\\dfrac{3x^{2n}}{3+x^{2n+1}}\\right),\\quad g(x)=\\lim_{n\\to\\infty}\\dfrac{1}{1+n\\sin^2\\pi x}$$",
    options:opts5("$x<-2$","$-2\\le x<-1$","$-1\\le x<0$","$0\\le x<2$","$2\\le x$"),
    correct:"4",
    explanation:"$f$ 극한: $|x|>1$이면 $1-3/x$, $|x|<1$이면 $1$.\n$g$: $\\sin\\pi x=0$ ($x$ 정수)이면 $1$, 아니면 $0$.\n$f=g$ 만족하는 $x$: $x=0$ ($f=1=g$). $0\\le x<2$ 범위에 포함.",
  },
  {n:3, subject:"미분학", unit:"도함수", concept:"라이프니츠 공식 변형",
    difficulty:"medium",
    question:"집합 $I$에서 두 함수 $f$와 $g$의 $n$계 도함수가 존재할 때 다음 식의 값을 구하면?\n$$(fg)^{(n)}(x)-\\sum_{r=1}^n\\dfrac{n!}{(n-r)!r!}f^{(n-r)}(x)g^{(r)}(x),\\quad x\\in I$$",
    options:opts5("$0$","$f^{(n)}(x)g(x)$","$f(x)g^{(n)}(x)$","$1$","$-1$"),
    correct:"2",
    explanation:"라이프니츠: $(fg)^{(n)}=\\sum_{r=0}^n\\binom{n}{r}f^{(n-r)}g^{(r)}$. $r=0$ 항은 $f^{(n)}g$, 나머지가 빠지면 $f^{(n)}(x)g(x)$.",
  },
  {n:4, subject:"다변수함수", unit:"편미분", concept:"$f_{xy}\\ne f_{yx}$ 함수",
    difficulty:"hard",
    question:"다음 중 $f_{xy}(0,0)\\ne f_{yx}(0,0)$인 함수를 모두 고르면?\n\nⓐ $f(x,y)=\\begin{cases}\\dfrac{x^3 y-xy^3}{x^2+y^2}&((x,y)\\ne(0,0))\\\\0&((x,y)=(0,0))\\end{cases}$\nⓑ $f(x,y)=\\begin{cases}\\dfrac{x^3 y^2-x^2 y^3}{x^2+y^2}&((x,y)\\ne(0,0))\\\\0&((x,y)=(0,0))\\end{cases}$\nⓒ $f(x,y)=\\sin^{-1}(xy)$",
    options:opts5("ⓐ","ⓑ","ⓒ","ⓑ, ⓒ","ⓐ, ⓒ"),
    correct:"1",
    explanation:"클레로의 정리: $f_{xy}=f_{yx}$ 성립하지 않는 표준 반례가 ⓐ.\nⓐ에서 $f_{xy}(0,0)=-1,\\,f_{yx}(0,0)=1$ ⇒ 다름.\nⓑ는 동차 차수가 높아 둘 다 0.\nⓒ는 부드러운 함수라 같음.",
  },
  {n:5, subject:"미분학", unit:"부등식", concept:"젠센 부등식 (아래로 볼록)",
    difficulty:"medium",
    question:"구간 $\\!\\left(\\dfrac{\\pi}{2},\\pi\\right)$에 있는 임의의 두 점 $a$와 $b$에 대해서 $f(ta+(1-t)b)\\le tf(a)+(1-t)f(b),\\,0<t<1$을 만족하는 함수를 보기에서 모두 고르면?\n\nⓐ $\\ln(\\sin x)$\nⓑ $-e^{-x}$\nⓒ $\\tan^2\\!\\left(x-\\dfrac{\\pi}{2}\\right)$\nⓓ $\\csc^3 x$",
    options:opts5("ⓐ, ⓑ","ⓒ, ⓓ","ⓐ, ⓓ","ⓑ, ⓒ","ⓐ, ⓒ"),
    correct:"2",
    explanation:"젠센 부등식 $\\Leftrightarrow$ 아래로 볼록 ($f''\\ge 0$).\nⓐ $f''=-\\csc^2<0$ (위로 볼록).\nⓑ $f''=-e^{-x}<0$.\nⓒ $f''=2\\csc^4 x+4\\csc^2 x\\cot^2 x>0$.\nⓓ $f''>0$ (계산).\n아래로 볼록: ⓒ, ⓓ.",
  },
  {n:6, subject:"선형대수", unit:"행렬식", concept:"여인수 직교성",
    difficulty:"medium",
    question:"$n$차 정사각 행렬 $A=(a_{ij})$에 대하여 다음 식의 값은? (단, $A_{ij}=(-1)^{i+j}M_{ij}$이고 $M_{ij}$는 $i$행과 $j$열을 제거하여 만든 부분 행렬의 행렬식이다.)\n$$a_{i1}A_{j1}+a_{i2}A_{j2}+\\cdots+a_{in}A_{jn}\\quad(\\text{단, }i\\ne j)$$",
    options:opts5("$0$","$1$","$-1$","$(-1)^n$","$(-1)^{n+1}$"),
    correct:"1",
    explanation:"여인수 직교성 정리: $\\sum_k a_{ik}A_{jk}=|A|\\delta_{ij}$. $i\\ne j$이므로 $0$.",
  },
  {n:7, subject:"미분학", unit:"도함수", concept:"테일러 + 적분 함수의 미분",
    difficulty:"hard",
    question:"실수 $x$에 대해 $f(x)$는 4번 미분가능하고 그 도함수들도 연속이며 $f(0)=0$이라고 하자. 이 때, 다음과 같이 정의된 $g(x)$에 대해 옳지 $\\textbf{않은}$ 것은?\n$$g(x)=\\begin{cases}\\dfrac{f(x)}{x}&(x\\ne 0)\\\\f'(0)&(x=0)\\end{cases}$$",
    options:opts5("$g$는 연속함수","$g'(2)=\\dfrac{2f'(2)-f(2)}{4}$","$g'(0)=\\dfrac{f''(0)}{2!}$","$g''(0)=\\dfrac{f^{(3)}(0)}{3!}$","$g'$는 연속함수"),
    correct:"4",
    explanation:"$g(x)=f'(0)+\\dfrac{f''(0)}{2!}x+\\dfrac{f^{(3)}(0)}{3!}x^2+\\dfrac{f^{(4)}(0)}{4!}x^3+\\cdots$ (테일러).\n$g''(0)=2!\\cdot\\dfrac{f^{(3)}(0)}{3!}=\\dfrac{f^{(3)}(0)}{3}\\ne\\dfrac{f^{(3)}(0)}{3!}$. (4)가 잘못됨.",
  },
  {n:8, subject:"적분학", unit:"적분의 정의", concept:"상적분과 하적분의 차",
    difficulty:"medium",
    question:"다음 함수 $f$에 대하여 상적분과 하적분의 차는?\n$$f(x)=\\begin{cases}1-x&(x\\in[0,1]\\cap\\mathbb{Q})\\\\x&(x\\in[0,1]\\cap\\mathbb{Q}^c)\\end{cases}$$",
    options:opts5("$0$","$0.25$","$0.5$","$0.75$","$1$"),
    correct:"3",
    explanation:"$0\\le x<1/2$: $1-x>x$ (상값 $1-x$). $1/2<x\\le 1$: $x>1-x$ (상값 $x$).\n상적분 $=\\!\\int_0^{1/2}(1-x)dx+\\!\\int_{1/2}^1 x\\,dx=3/8+3/8=0.75$.\n하적분 $=\\!\\int_0^{1/2}x\\,dx+\\!\\int_{1/2}^1(1-x)dx=1/8+1/8=0.25$.\n차 $=0.5$.",
  },
  {n:9, subject:"미분학", unit:"미분방정식", concept:"변수치환 ODE",
    difficulty:"medium",
    question:"미분방정식 $(1-x^2)\\dfrac{d^2 y}{dx^2}-x\\dfrac{dy}{dx}=0$ ($|x|<1$)을 $x=\\sin t$를 이용하여 $t$에 관한 미분방정식으로 바꾸면?",
    options:opts5("$\\dfrac{d^2 y}{dt^2}=0$","$\\cos^2 t\\dfrac{d^2 y}{dt^2}-\\sin t\\dfrac{dy}{dt}=0$","$\\dfrac{d^2 y}{dt^2}-\\sin t\\dfrac{dy}{dt}=0$","$\\dfrac{d^2 y}{dt^2}-\\dfrac{dy}{dt}=0$","$\\dfrac{d^2 y}{dt^2}+\\dfrac{dy}{dt}=0$"),
    correct:"1",
    explanation:"$\\dfrac{dy}{dx}=\\dfrac{dy}{dt}\\sec t$. $\\dfrac{d^2 y}{dx^2}=\\dfrac{d^2 y}{dt^2}\\sec^2 t+\\dfrac{dy}{dt}\\sec t\\tan t$.\n원식 대입 후 $1-x^2=\\cos^2 t$ 이용해 정리: $\\cos^2 t\\!\\left(\\dfrac{d^2 y}{dt^2}\\sec^2 t+\\dfrac{dy}{dt}\\sec t\\tan t\\right)-\\sin t\\dfrac{dy}{dt}\\sec t=0$\n$\\Rightarrow\\dfrac{d^2 y}{dt^2}+\\tan t\\dfrac{dy}{dt}-\\tan t\\dfrac{dy}{dt}=\\dfrac{d^2 y}{dt^2}=0$.",
  },
  {n:10, subject:"적분학", unit:"정적분의 응용", concept:"회전체 겉넓이",
    difficulty:"medium",
    question:"곡선 $x=\\sqrt{y}$ ($0\\le y\\le 2$)를 $y$축을 중심으로 회전시켜 얻은 입체의 겉넓이는?",
    options:opts5("$\\dfrac{\\pi}{3}$","$\\dfrac{13\\pi}{3}$","$\\dfrac{17\\pi}{3}$","$\\dfrac{\\pi}{5}$","$\\dfrac{17\\pi}{7}$"),
    correct:"2",
    explanation:"$S=2\\pi\\!\\int_0^2 x\\sqrt{1+(x')^2}\\,dy$ ($x'=dx/dy=1/(2\\sqrt{y})$).\n$=2\\pi\\!\\int_0^2\\sqrt{y}\\sqrt{1+\\dfrac{1}{4y}}\\,dy=2\\pi\\!\\int_0^2\\sqrt{y+1/4}\\,dy=2\\pi\\cdot\\dfrac{2}{3}\\!\\left[(y+1/4)^{3/2}\\right]_0^2=\\dfrac{4\\pi}{3}\\cdot\\dfrac{13}{4}\\cdot\\sqrt{1}\\cdots=\\dfrac{13\\pi}{3}$.",
  },
  {n:11, subject:"미분학", unit:"극한과 연속", concept:"역함수 극한 (로피탈)",
    difficulty:"medium",
    question:"$f(x)=(\\tan x+1)^3$ (단, $-\\pi/2<x<\\pi/2$)의 역함수가 $g(x)$라 하자. $\\displaystyle\\lim_{x\\to 1}\\dfrac{\\sin\\pi x}{g(x)}$의 값은?",
    options:opts5("$3\\pi$","$\\pi$","$0$","$-\\pi$","$-3\\pi$"),
    correct:"5",
    explanation:"$g(1)=0$ ($f(0)=1$). $\\sin\\pi=0$, $0/0$ 꼴.\n로피탈: $\\!\\lim\\dfrac{\\pi\\cos\\pi x}{g'(x)}=\\dfrac{-\\pi}{g'(1)}$.\n$g'(1)=1/f'(0)=1/(3\\tan^0(\\sec^2 0)\\cdot 1)=1/3$ (계산: $f'(x)=3(\\tan x+1)^2\\sec^2 x$, $f'(0)=3\\cdot 1\\cdot 1=3$, $g'(1)=1/3$).\n$\\!\\lim=-\\pi/(1/3)=-3\\pi$.",
  },
  {n:12, subject:"미분학", unit:"미분방정식", concept:"르장드르 방정식",
    difficulty:"medium",
    question:"자연수 $n$에 대해 $y=\\dfrac{d^n}{dx^n}(x^2-1)^n$이 다음 미분 방정식을 만족시킨다고 할 때 $k$의 값은?\n$$(1-x^2)y''-2xy'+ky=0$$",
    options:opts5("$n$","$n+1$","$n^2$","$n(n+1)$","$(n+1)^2$"),
    correct:"4",
    explanation:"르장드르 다항식 $P_n(x)$의 미분방정식: $(1-x^2)y''-2xy'+n(n+1)y=0$. $k=n(n+1)$.",
  },
  {n:13, subject:"적분학", unit:"정적분", concept:"리만합·이상적분·로피탈 비교",
    difficulty:"medium",
    question:"다음 중 계산값이 서로 같은 것을 모두 고르면?\n\nⓐ $\\displaystyle\\lim_{n\\to\\infty}\\dfrac{2}{n^2}\\sum_{k=0}^{n-1}\\sqrt{n^2-k^2}$\nⓑ $\\displaystyle-\\int_0^2\\dfrac{\\pi\\,dx}{4(x-1)^2}$\nⓒ $\\displaystyle\\lim_{x\\to\\pi/2}\\dfrac{\\pi(\\pi/2-x)\\tan x}{2}$",
    options:opts5("ⓐ, ⓑ","ⓑ, ⓒ","ⓐ, ⓒ","ⓐ, ⓑ, ⓒ","없다"),
    correct:"3",
    explanation:"ⓐ 리만합 $\\to 2\\!\\int_0^1\\sqrt{1-x^2}\\,dx=\\pi/2$.\nⓑ $1/(x-1)^2$이 $x=1$에서 발산.\nⓒ 로피탈: $\\dfrac{\\pi}{2}\\!\\lim\\dfrac{\\pi/2-x}{\\cot x}=\\dfrac{\\pi}{2}\\!\\lim\\dfrac{-1}{-\\csc^2 x}=\\dfrac{\\pi}{2}$.\nⓐ, ⓒ 같음.",
  },
  {n:14, subject:"적분학", unit:"급수의 수렴/발산", concept:"발산 식별 (3보기)",
    difficulty:"medium",
    question:"다음 중 발산하는 무한급수를 모두 고르면?\n\nⓐ $\\displaystyle\\sum_{n=2}^{\\infty}\\dfrac{1}{n+2017(\\ln n)}$\nⓑ $\\displaystyle\\sum_{n=4}^{\\infty}\\!\\left(1-\\dfrac{3}{n}\\right)^{n^2}$\nⓒ $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{(-1)^n\\cos n\\pi}{\\sqrt{n}}$",
    options:opts5("ⓐ, ⓑ","ⓑ, ⓒ","ⓐ, ⓒ","ⓐ, ⓑ, ⓒ","없다"),
    correct:"3",
    explanation:"ⓐ 비교: $n+2017\\ln n<n+2017n=2018n$ (큰 $n$에서). $\\sum 1/(2018n)$ 발산 ⇒ 발산.\nⓑ 승근판정: $\\!\\left((1-3/n)^{n^2}\\right)^{1/n}=(1-3/n)^n\\to e^{-3}<1$ ⇒ 수렴.\nⓒ $\\cos n\\pi=(-1)^n$, $\\sum(-1)^{2n}/\\sqrt{n}=\\sum 1/\\sqrt{n}$ 발산.",
  },
  {n:15, subject:"선형대수", unit:"선형변환", concept:"선형변환 (선형 결합)",
    difficulty:"medium",
    question:"일차 변환 $T:\\mathbb{R}^3\\to\\mathbb{R}^2$에 대해 다음이 성립한다. 이때 $T(2x_1,-x_2,x_3)$는?\n$$T(1,0,0)=(2,1),\\,T(2,1,0)=(2,1),\\,T(1,-1,-1)=(5,2)$$",
    options:opts5("$(4x_1+2x_2,2x_1-x_3)$","$(2x_2-x_3,x_1+x_2)$","$(x_1-x_2+2x_3,1)$","$(4x_1-2x_2-x_3,x_1-x_3)$","$(4x_1+2x_2-x_3,2x_1+x_2)$"),
    correct:"5",
    explanation:"$(2x_1,-x_2,x_3)=(2x_1+2x_2+3x_3)(1,0,0)+(-x_2-x_3)(2,1,0)+(-x_3)(1,-1,-1)$ (계수 매칭).\n검증: $i$성분: $2x_1+2x_2+3x_3+2(-x_2-x_3)+(-x_3)=2x_1$ ✓.\n$j$성분: $0+(-x_2-x_3)+(x_3)=-x_2$ ✓.\n$k$성분: $0+0+x_3=x_3$ ✓.\n$T=(2x_1+2x_2+3x_3)(2,1)+(-x_2-x_3)(2,1)+(-x_3)(5,2)=(4x_1+2x_2-x_3,2x_1+x_2)$.",
  },
  {n:16, subject:"적분학", unit:"급수의 수렴/발산", concept:"멱급수 수렴반경 합",
    difficulty:"medium",
    question:"아래 세 멱급수의 수렴반지름을 모두 더하면?\n$$\\sum_{n=0}^{\\infty}\\dfrac{n}{3^n}(x-2)^n,\\quad\\sum_{n=0}^{\\infty}\\dfrac{(n!)^2}{(2n)!}x^n,\\quad\\sum_{n=1}^{\\infty}\\!\\left(1+\\dfrac{1}{2}+\\cdots+\\dfrac{1}{n}\\right)x^n$$",
    options:opts5("$4$","$5$","$7$","$8$","$\\infty$"),
    correct:"4",
    explanation:"① $a_n=n/3^n$: $|a_n/a_{n+1}|\\to 3$. $R_1=3$.\n② $a_n=(n!)^2/(2n)!$: $|a_n/a_{n+1}|=\\dfrac{(2n+2)(2n+1)}{(n+1)^2}\\to 4$. $R_2=4$.\n③ $a_n=H_n$: $H_{n+1}/H_n\\to 1$. $R_3=1$.\n합 $=3+4+1=8$.",
  },
  {n:17, subject:"다변수함수", unit:"편미분", concept:"야코비 행렬 대각합",
    difficulty:"medium",
    question:"벡터함수 $T:\\mathbb{R}^3\\to\\mathbb{R}^3$에 대해 $T(x,y,z)=(xyz,\\sin xy,e^{yz})$일 때, $\\mathrm{tr}(J_T(\\pi,1,-1))$의 값은? (단, $J_T$는 야코비 행렬)",
    options:opts5("$e^{-1}-\\pi-1$","$e^{-1}+\\pi-1$","$e^{-1}-\\pi+1$","$e^{-1}+\\pi+1$","$0$"),
    correct:"1",
    explanation:"$J_T=\\begin{pmatrix}yz&xz&xy\\\\y\\cos xy&x\\cos xy&0\\\\0&ze^{yz}&ye^{yz}\\end{pmatrix}$.\n대각합 $=yz+x\\cos xy+ye^{yz}$.\n$(\\pi,1,-1)$: $-1+\\pi\\cos\\pi+e^{-1}=-1-\\pi+e^{-1}$.",
  },
  {n:18, subject:"미분학", unit:"수열과 점화식", concept:"점화식 비율 극한",
    difficulty:"medium",
    question:"두 수열 $\\{a_n\\},\\{b_n\\}$에 대해 다음 관계가 성립하고 $a_1=b_1=1$일 때, $\\displaystyle\\lim_{n\\to\\infty}\\dfrac{a_n}{b_n}$의 값은?\n$$a_n=2a_{n-1}+5b_{n-1},\\quad b_n=a_{n-1}+2b_{n-1}$$",
    options:opts5("$1$","$\\sqrt{2}$","$\\sqrt{3}$","$2$","$\\sqrt{5}$"),
    correct:"5",
    explanation:"$\\dfrac{a_n}{b_n}=\\dfrac{2a_{n-1}+5b_{n-1}}{a_{n-1}+2b_{n-1}}=\\dfrac{2(a_{n-1}/b_{n-1})+5}{(a_{n-1}/b_{n-1})+2}$.\n$x=\\!\\lim$: $x=\\dfrac{2x+5}{x+2}\\Rightarrow x^2+2x=2x+5\\Rightarrow x^2=5\\Rightarrow x=\\sqrt{5}$ (양수).",
  },
  {n:19, subject:"다변수함수", unit:"편미분", concept:"$f_x,f_y$ 존재 및 미분가능",
    difficulty:"medium",
    question:"함수 $f(x,y)=\\begin{cases}\\dfrac{xy^2\\sqrt{x^2+y^2}}{x^2+y^4}&((x,y)\\ne(0,0))\\\\0&((x,y)=(0,0))\\end{cases}$에 대한 다음 설명 중 옳은 것을 모두 고르면?\n\nⓐ 원점에서 $f_x$가 존재한다.\nⓑ 원점에서 $f_y$가 존재한다.\nⓒ 원점에서 미분 가능하다.",
    options:opts5("ⓐ","ⓑ","ⓐ, ⓑ","ⓐ, ⓑ, ⓒ","없음"),
    correct:"3",
    explanation:"ⓐ $f_x(0,0)=\\!\\lim_{h\\to 0}\\dfrac{f(h,0)-0}{h}=\\!\\lim 0/h=0$. 존재.\nⓑ $f_y(0,0)=0$. 존재.\nⓒ $x=my^2$ 경로: $f$의 비율이 $\\dfrac{m|y|^5}{(m^2+1)y^4}\\to 0$이지만 $f_x$의 극한이 경로별로 달라 $f_x$가 불연속, 따라서 미분 불가능.",
  },
  {n:20, subject:"다변수함수", unit:"공간곡선", concept:"구면좌표 곡선의 접선",
    difficulty:"medium",
    question:"$\\rho=t,\\,\\theta=t,\\,\\phi=\\dfrac{\\pi}{6}$ ($0\\le t\\le\\pi$)은 구면좌표계의 매개방정식으로 주어진 곡선이다. $t=\\dfrac{\\pi}{2}$에서 접선의 방정식과 $xy$평면과의 교점은?",
    options:opts5("$\\!\\left(-\\dfrac{\\pi}{4},\\dfrac{\\pi}{2},0\\right)$","$\\!\\left(\\dfrac{\\pi^2}{8},0,0\\right)$","$\\!\\left(0,\\dfrac{\\pi^2}{4},0\\right)$","$\\!\\left(\\dfrac{\\pi^2}{4},\\dfrac{\\pi^2}{4},0\\right)$","$\\!\\left(\\dfrac{\\pi}{2},\\dfrac{\\pi}{4},0\\right)$"),
    correct:"2",
    explanation:"직교: $x=\\rho\\sin\\phi\\cos\\theta=\\dfrac{1}{2}t\\cos t,\\,y=\\dfrac{1}{2}t\\sin t,\\,z=\\rho\\cos\\phi=\\dfrac{\\sqrt{3}}{2}t$.\n$t=\\pi/2$: 점 $(0,\\pi/4,\\sqrt{3}\\pi/4)$, 방향 $(-\\pi/4,1/2,\\sqrt{3}/2)$.\n접선: $\\dfrac{x}{-\\pi/4}=\\dfrac{y-\\pi/4}{1/2}=\\dfrac{z-\\sqrt{3}\\pi/4}{\\sqrt{3}/2}$.\n$z=0$ 대입: $z-\\sqrt{3}\\pi/4=-\\sqrt{3}\\pi/4$, 비례 $-\\pi/2$. $x=(-\\pi/2)(-\\pi/4)=\\pi^2/8,\\,y=\\pi/4-\\pi/4=0$.\n교점 $(\\pi^2/8,0,0)$.",
  },
  {n:21, subject:"다변수함수", unit:"공간곡선", concept:"점-곡선 접점 거리",
    difficulty:"medium",
    question:"점 $A(4,1,3)$에서 곡선 $\\vec{x}(t)=(2t,\\ln t,t^2)$에 접선을 긋는다. 접점과 점 $A$ 사이의 거리는?",
    options:opts5("$3$","$3\\sqrt{2}$","$4\\sqrt{2}$","$5$","$5\\sqrt{2}$"),
    correct:"1",
    explanation:"접점 $B(2t,\\ln t,t^2)$, 접선 방향 $(2,1/t,2t)$. $\\vec{BA}=(4-2t,1-\\ln t,3-t^2)$.\n$\\vec{BA}\\parallel\\vec{x}'$: $\\dfrac{4-2t}{2}=\\dfrac{1-\\ln t}{1/t}=\\dfrac{3-t^2}{2t}$.\n첫 두: $2-t=t(1-\\ln t)$. 첫·셋: $4-2t=\\dfrac{3-t^2}{t}$. $t=1$로 검증 시 모두 성립.\n$B(2,0,1)$, $|BA|=\\sqrt{4+1+4}=3$.",
  },
  {n:22, subject:"다변수함수", unit:"음함수와 편미분", concept:"3변수 음함수 편미분",
    difficulty:"medium",
    question:"방정식 $x^2+y^2+z^2-3xyz=0$ (단, $z>1$)에 의해 $z$가 $x$와 $y$의 음함수로 정의된다고 할 때 $\\dfrac{\\partial z}{\\partial x}(1,1)+\\dfrac{\\partial z}{\\partial y}(1,1)$의 값은?",
    options:opts5("$0$","$2$","$4$","$6$","$8$"),
    correct:"5",
    explanation:"$x=y=1$ 대입: $z^2-3z+2=0\\Rightarrow z=1$ 또는 $2$. $z>1$이므로 $z=2$.\n$\\dfrac{\\partial z}{\\partial x}=-\\dfrac{2x-3yz}{2z-3xy}\\big|_{(1,1,2)}=-\\dfrac{2-6}{4-3}=4$.\n대칭 $\\dfrac{\\partial z}{\\partial y}=4$.\n합 $=8$.",
  },
  {n:23, subject:"다변수함수", unit:"공간곡면", concept:"곡면 면적 (제약)",
    difficulty:"medium",
    question:"$\\mathbb{R}^3$에서 원기둥 $x^2+y^2=3$과 곡면 $z=xy$이 만날 때, 원기둥 내부에 있는 곡면의 면적은?",
    options:opts5("$\\dfrac{14\\pi}{3}$","$\\dfrac{16\\pi}{3}$","$6\\pi$","$\\dfrac{20\\pi}{3}$","$\\dfrac{22\\pi}{3}$"),
    correct:"1",
    explanation:"$S=\\!\\iint_D\\sqrt{1+y^2+x^2}\\,dA=\\!\\iint_D\\sqrt{1+r^2}\\cdot r\\,dr\\,d\\theta$ (극좌표).\n$=\\!\\int_0^{2\\pi}\\!\\!\\int_0^{\\sqrt{3}}r\\sqrt{1+r^2}\\,dr\\,d\\theta=2\\pi\\cdot\\dfrac{1}{3}[(1+r^2)^{3/2}]_0^{\\sqrt{3}}=\\dfrac{2\\pi}{3}(8-1)=\\dfrac{14\\pi}{3}$.",
  },
  {n:24, subject:"다변수함수", unit:"극좌표와 극곡선", concept:"극곡선과 원의 교점",
    difficulty:"medium",
    question:"곡선 $r=2\\cos 2\\theta$ (단, $-\\pi<\\theta\\le\\pi$)와 원 $r=1$의 교점의 개수는?",
    options:opts5("$0$","$2$","$4$","$6$","$8$"),
    correct:"5",
    explanation:"$2\\cos 2\\theta=1\\Rightarrow\\cos 2\\theta=1/2\\Rightarrow 2\\theta=\\pm\\pi/3+2k\\pi$. $(-\\pi,\\pi]$에서 $\\theta=\\pm\\pi/6,\\,\\pm 5\\pi/6$ 4개.\n또 $r=-1$ 음반사도 매칭하면 $2\\cos 2\\theta=-1\\Rightarrow$ 4개 추가. 그래프 분석: 4잎 장미 + 단위원 교점 8개.",
  },
  {n:25, subject:"다변수함수", unit:"편미분", concept:"음함수 + 그래디언트 (가장 빨리 증가)",
    difficulty:"medium",
    question:"방정식 $z+1=xe^y\\cos z$에 의해 $(x,y)=(1,0)$ 근방에서 $z$가 $x$와 $y$의 음함수로 정의되는지 확인하고 만약 정의된다면 $z$가 가장 빨리 증가하는 방향은? (단, $-\\pi/2<z<\\pi/2$)",
    options:opts5("정의되지 않음","$(1,1)$","$(1,0)$","$(0,1)$","$(1,-1)$"),
    correct:"2",
    explanation:"$(1,0)$ 대입: $z+1=\\cos z$. $z=0$ 만족.\n$F=z+1-xe^y\\cos z$. $F_z=1+xe^y\\sin z\\big|_{(1,0,0)}=1\\ne 0$ ⇒ 음함수 정리 적용 가능.\n$z_x=-F_x/F_z=-(-e^y\\cos z)/1\\big|_{(1,0,0)}=1$. $z_y=-(-xe^y\\cos z)/1\\big|_{(1,0,0)}=1$.\n그래디언트 $(1,1)$ 방향이 가장 빠름.",
  },
  {n:26, subject:"다변수함수", unit:"삼중적분", concept:"사면체 영역 적분",
    difficulty:"medium",
    question:"영역 $Q:x\\ge 0,\\,y\\ge 0,\\,z\\ge 0,\\,x+y+z\\le 1$에서 $\\displaystyle\\iiint_Q x\\,dV$의 값은?",
    options:opts5("$\\dfrac{1}{12}$","$\\dfrac{1}{24}$","$\\dfrac{1}{36}$","$\\dfrac{1}{48}$","$\\dfrac{1}{60}$"),
    correct:"2",
    explanation:"$\\!\\int_0^1\\!\\!\\int_0^{1-x}\\!\\!\\int_0^{1-x-y}x\\,dz\\,dy\\,dx=\\!\\int_0^1\\!\\!\\int_0^{1-x}x(1-x-y)\\,dy\\,dx$\n$=\\!\\int_0^1 x\\!\\left[(1-x)y-\\dfrac{y^2}{2}\\right]_0^{1-x}dx=\\!\\int_0^1\\dfrac{x(1-x)^2}{2}dx=\\dfrac{1}{2}\\cdot B(2,3)=\\dfrac{1}{2}\\cdot\\dfrac{1}{12}=\\dfrac{1}{24}$.",
  },
  {n:27, subject:"다변수함수", unit:"다변수 극값", concept:"제약 조건 최대·최솟값",
    difficulty:"hard",
    question:"조건 $x^4+y^4+z^4=1$을 만족시키는 $f(x,y,z)=x^2+y^2+z^2$의 최댓값과 최솟값의 차는?",
    options:opts5("$\\sqrt{3}$","$2\\sqrt{3}$","$3\\sqrt{3}$","$\\sqrt{3}-1$","$2-\\sqrt{3}$"),
    correct:"4",
    explanation:"최댓값: $x^4+y^4+z^4=1$과 $x^2+y^2+z^2=k$ 외접점에서. $x=y=z$: $3x^4=1\\Rightarrow x^2=1/\\sqrt{3}$, $f=3/\\sqrt{3}=\\sqrt{3}$.\n최솟값: $x^2=1,\\,y=z=0$ (꼭짓점): $f=1$.\n차 $=\\sqrt{3}-1$.",
  },
  {n:28, subject:"다변수함수", unit:"이중적분", concept:"극좌표 + 적분식 표기",
    difficulty:"medium",
    question:"$\\mathbb{R}^2$에서 $y\\ge x,\\,x\\ge 0,\\,x^2+\\!\\left(y-\\dfrac{1}{2}\\right)^2\\ge\\dfrac{1}{4},\\,x^2+y^2\\le 4$로 이루어진 영역의 면적에 대해 다음 보기 중 옳은 것을 모두 고르면?\n\nⓐ $\\dfrac{7\\pi-2}{16}$\nⓑ $\\displaystyle\\int_{\\pi/4}^{\\pi/2}\\!\\!\\int_{\\sin\\theta}^2 r\\,dr\\,d\\theta$\nⓒ $\\displaystyle\\int_0^{1/2}\\!\\!\\int_{\\sqrt{1/4-x^2}+1/2}^{\\sqrt{4-x^2}}\\,dy\\,dx+\\!\\int_{1/2}^{\\sqrt{2}}\\!\\!\\int_x^{\\sqrt{4-x^2}}\\,dy\\,dx$",
    options:opts5("ⓐ, ⓑ","ⓑ, ⓒ","ⓐ, ⓑ, ⓒ","ⓑ","없다"),
    correct:"3",
    explanation:"극좌표 영역: $\\theta\\in[\\pi/4,\\pi/2]$, $r\\in[\\sin\\theta,2]$ ⇒ ⓑ ✓.\n계산: $\\!\\int_{\\pi/4}^{\\pi/2}(2-\\sin^2\\theta/2)\\,d\\theta=\\dfrac{7\\pi-2}{16}$ ⇒ ⓐ ✓.\nⓒ는 직교 좌표 등가 표현 ⇒ ✓.",
  },
  {n:29, subject:"미분학", unit:"극한과 연속", concept:"적분 함수 극한 (로피탈)",
    difficulty:"medium",
    question:"극한 $\\displaystyle\\lim_{x\\to 0}\\dfrac{1}{x}\\!\\int_x^{2x}\\dfrac{1-t^2}{1+t^2}\\,dt$의 값은?",
    options:opts5("$1$","$2$","$-1$","$-2$","$0$"),
    correct:"1",
    explanation:"$F(x)=\\!\\int_x^{2x}\\dfrac{1-t^2}{1+t^2}dt$, $F(0)=0$. $0/0$ 꼴.\n로피탈: $F'(x)=\\dfrac{1-4x^2}{1+4x^2}\\cdot 2-\\dfrac{1-x^2}{1+x^2}$. $x=0$: $2-1=1$.\n극한 $=1$.",
  },
  {n:30, subject:"다변수함수", unit:"공간곡선", concept:"타원 곡률 중심 좌표",
    difficulty:"medium",
    question:"타원 $\\dfrac{x^2}{4}+y^2=1$ 위의 점 $(2,0)$에서 곡률중심의 $x$좌표와 $y$좌표의 합은?",
    options:opts5("$0$","$1.2$","$1.4$","$1.5$","$1.7$"),
    correct:"4",
    explanation:"매개변수 $x=2\\cos t,\\,y=\\sin t$. $(2,0)$은 $t=0$.\n곡률 $\\kappa=\\dfrac{|x'y''-x''y'|}{(x'^2+y'^2)^{3/2}}\\big|_{t=0}=\\dfrac{|0-(-2)\\cdot 1|}{(0+1)^{3/2}\\cdot}\\!\\cdots=\\dfrac{2}{1}=2$.\n곡률반경 $1/\\kappa=1/2$. 곡률중심은 $(2,0)$에서 법선 방향 $1/2$ 안쪽: $(2-1/2,0)=(3/2,0)$.\n합 $=3/2=1.5$.",
  },
];

const TOTAL=PROBLEMS.length;
console.log(`총 ${TOTAL}문제 (객관식) 준비됨`);

const rows = PROBLEMS.map(p => {
  const id = `q-${YEAR}-${SCHOOL_EN}-${String(p.n).padStart(2,"0")}`;
  return {
    id, subject: p.subject, unit: p.unit, concept: p.concept, difficulty: p.difficulty,
    source_type: "imported", pool: "general", question: p.question, content_type: "latex",
    question_image: null, question_type: "multiple_choice",
    options: p.options, correct_option_id: p.correct,
    answer_text: null, explanation: p.explanation, explanation_content_type: "latex",
    explanation_image: null,
    tags: [YEAR, SCHOOL_KO, "past_exam", p.subject, p.unit, p.concept],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  };
});

const { data, error } = await sb.from("questions").upsert(rows, { onConflict: "id" }).select("id");
if (error) { console.error("업로드 실패:", error); process.exit(1); }
console.log(`업로드 완료: ${data.length}건`);
