// 2020년 광운대 편입수학 객관식 30문항 (5지선다)
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { createClient } from "@supabase/supabase-js";

const here = dirname(fileURLToPath(import.meta.url));
const envText = readFileSync(resolve(here, "..", ".env.local"), "utf8");
const env = Object.fromEntries(envText.split(/\r?\n/).filter(l=>l&&!l.startsWith("#")&&l.includes("=")).map(l=>{const[k,...r]=l.split("=");return[k.trim(),r.join("=").trim()];}));
const sb = createClient(env.NEXT_PUBLIC_SUPABASE_URL, env.SUPABASE_SERVICE_ROLE_KEY);

const YEAR="2020", SCHOOL_KO="광운대", SCHOOL_EN="kwangwoon";
const opts5 = (...t) => t.map((text,i)=>({id:String(i+1),label:String(i+1),text,contentType:"latex"}));

const PROBLEMS = [
  {n:1, subject:"미분학", unit:"미분가능성", concept:"미분가능 → 연속 증명",
    difficulty:"easy",
    question:"다음은 함수 $f$가 $a$에서 미분가능하면 $f$가 $a$에서 연속임을 증명하는 과정이다.\n\n(증명) 함수 $f$가 $a$에서 미분 가능하므로 $\\displaystyle\\lim_{h\\to 0}A$의 극한이 존재한다.\n그러므로 항등식 $f(a+h)=f(a+h)-f(a)+f(a)$를 이용해서 다음을 얻는다.\n$$\\lim_{x\\to a}f(x)=\\lim_{h\\to 0}f(a+h)=\\lim_{h\\to 0}\\{Bh+f(a)\\}=C\\lim_{h\\to 0}h+f(a)=f(a)$$\n따라서 함수 $f$는 $a$에서 연속이다.\n\n이 때, $A-B+C$의 값은?",
    options:opts5("$-1$","$0$","$1$","$f(a)$","$f'(a)$"),
    correct:"5",
    explanation:"$A=\\dfrac{f(a+h)-f(a)}{h}$, $B=\\dfrac{f(a+h)-f(a)}{h}$ (둘 다 같은 차분 식, $\\lim$ 안에서), $C=f'(a)$.\n$A-B+C=0+f'(a)=f'(a)$.",
  },
  {n:2, subject:"미분학", unit:"도함수", concept:"연쇄법칙 2계 도함수",
    difficulty:"medium",
    question:"$y=f(x),\\,x=g(z)$이고 $f$와 $g$는 모두 2계 도함수가 존재한다고 할 때, $\\dfrac{d^2 y}{dz^2}$의 값은?",
    options:opts5("$f''(x)g'(z)+f'(x)g''(z)$","$f''(x)(g'(z))^2+f'(x)g''(z)$","$f''(x)g'(z)+(f'(x))^2 g''(z)$","$2f''(x)g'(z)+f'(x)g''(z)$","$f''(x)g'(z)+2f'(x)g''(z)$"),
    correct:"2",
    explanation:"$\\dfrac{dy}{dz}=f'(g(z))g'(z)=f'(x)g'(z)$.\n$\\dfrac{d^2 y}{dz^2}=f''(x)\\cdot g'(z)\\cdot g'(z)+f'(x)g''(z)=f''(x)(g'(z))^2+f'(x)g''(z)$.",
  },
  {n:3, subject:"다변수함수", unit:"음함수와 편미분", concept:"두 곡선의 직교 조건",
    difficulty:"medium",
    question:"두 곡선 $y^2=x^3$과 $\\dfrac{x^2}{a^2}+\\dfrac{y^2}{b^2}=1$의 1사분면 위 교점을 $(x_0, y_0)$라 하자. 점 $(x_0, y_0)$에서의 두 곡선에 대한 접선이 서로 수직일 때, $a$와 $b$의 관계식으로 옳은 것은?",
    options:opts5("$3a^2=2b^2$","$2a^2=3b^2$","$a^2=b^2$","$3a^2=2b^3$","$2a^2=3b^3$"),
    correct:"2",
    explanation:"$y^2=x^3$: $y'=\\dfrac{3x^2}{2y}\\big|_{(x_0,y_0)}=\\dfrac{3x_0^2}{2y_0}$.\n타원: $y'=-\\dfrac{b^2 x}{a^2 y}\\big|_{(x_0,y_0)}=-\\dfrac{b^2 x_0}{a^2 y_0}$.\n수직 조건: $\\dfrac{3x_0^2}{2y_0}\\cdot\\!\\left(-\\dfrac{b^2 x_0}{a^2 y_0}\\right)=-1\\Rightarrow\\dfrac{3b^2 x_0^3}{2a^2 y_0^2}=1$.\n$y_0^2=x_0^3$ 대입: $\\dfrac{3b^2}{2a^2}=1\\Rightarrow 2a^2=3b^2$.",
  },
  {n:4, subject:"다변수함수", unit:"극좌표와 극곡선", concept:"극곡선 축 교점 좌표 합",
    difficulty:"medium",
    question:"극 좌표로 주어진 곡선 $r=1-\\cos\\theta$를 $xy$ 좌표평면에 나타낼 때, 이 곡선이 $x$축 또는 $y$축과 만나는 4개 점들의 $x$좌표값과 $y$좌표값을 모두 더하면?",
    options:opts5("$-2$","$-1$","$0$","$1$","$2$"),
    correct:"1",
    explanation:"카디오이드 $r=1-\\cos\\theta$. 축과 만나는 점:\n$\\theta=0$: $r=0\\Rightarrow(0,0)$.\n$\\theta=\\pi/2$: $r=1\\Rightarrow(0,1)$.\n$\\theta=\\pi$: $r=2\\Rightarrow(-2,0)$.\n$\\theta=3\\pi/2$: $r=1\\Rightarrow(0,-1)$.\n좌표 합 $=0+0+0+1-2+0+0-1=-2$.",
  },
  {n:5, subject:"다변수함수", unit:"삼중적분", concept:"회전좌표계 (구·평면 거리 적분)",
    difficulty:"hard",
    question:"집합 $Q=\\{(x,y,z)\\mid x^2+y^2+z^2\\le 1\\}$를 적분 영역이라고 하자. $\\displaystyle\\iiint_Q\\dfrac{dV}{\\sqrt{x^2+y^2+(z-4)^2}}$의 값은?",
    options:opts5("$\\dfrac{\\pi}{4}$","$\\dfrac{\\pi}{3}$","$\\dfrac{\\pi}{2}$","$\\pi$","$2\\pi$"),
    correct:"2",
    explanation:"회전좌표계 ($x=r\\cos\\theta,y=r\\sin\\theta$, $z$ 그대로): 적분 $=\\!\\int_{-1}^1\\!\\!\\int_0^{2\\pi}\\!\\!\\int_0^{\\sqrt{1-z^2}}\\dfrac{r}{\\sqrt{r^2+(z-4)^2}}\\,dr\\,d\\theta\\,dz$.\n$=2\\pi\\!\\int_{-1}^1[\\sqrt{r^2+(z-4)^2}]_0^{\\sqrt{1-z^2}}\\,dz=2\\pi\\!\\int_{-1}^1[\\sqrt{17-8z}-|z-4|]\\,dz$.\n$=2\\pi\\!\\int_{-1}^1\\!\\left(\\sqrt{17-8z}-(4-z)\\right)dz=\\dfrac{\\pi}{3}$ (계산).",
  },
  {n:6, subject:"다변수함수", unit:"매개변수 곡선", concept:"매개변수 곡선 x축 교점",
    difficulty:"medium",
    question:"다음 매개 방정식으로 정의된 곡선이 $x$축과 만나는 모든 점들의 $x$좌표값을 모두 더하면?\n$$x=-t^2+t-\\dfrac{1}{4},\\quad y=t^4-2t^3+t^2-1\\quad(\\text{단, }t\\text{는 임의의 실수})$$",
    options:opts5("$-\\dfrac{5}{4}$","$-\\dfrac{1}{2}$","$0$","$\\dfrac{3}{4}$","$1$"),
    correct:"1",
    explanation:"$y=0$: $t^4-2t^3+t^2-1=0\\Rightarrow(t^2-t)^2=1\\Rightarrow t^2-t-1=0$ (다른 인수는 허근).\n두 근 $\\alpha,\\beta$: $\\alpha+\\beta=1,\\,\\alpha\\beta=-1$.\n$x_1+x_2=-(\\alpha^2+\\beta^2)+(\\alpha+\\beta)-\\dfrac{1}{2}=-((\\alpha+\\beta)^2-2\\alpha\\beta)+1-\\dfrac{1}{2}=-3+\\dfrac{1}{2}=-\\dfrac{5}{2}$.\n$x_1=x_2$ (동일 좌표)이므로 합 $=x_1=-\\dfrac{5}{4}$.",
  },
  {n:7, subject:"적분학", unit:"정적분", concept:"적분 함수의 성질",
    difficulty:"easy",
    question:"$f>0$인 함수 $f$에 대해 함수 $F$를 다음과 같이 정의 할 때, 다음 설명 중 옳은 것은?\n$$F(x)=\\int_0^x f(t)(x-t)\\,dt,\\quad x>0$$",
    options:opts5("$F$는 증가 함수이면서 위로 볼록이다.","$F$는 증가 함수이면서 아래로 볼록이다.","$F$는 감소 함수이면서 위로 볼록이다.","$F$는 감소 함수이면서 아래로 볼록이다.","$F$는 1차 함수이다."),
    correct:"2",
    explanation:"$F(x)=x\\!\\int_0^x f(t)dt-\\!\\int_0^x t f(t)dt$.\n$F'(x)=\\!\\int_0^x f(t)dt+xf(x)-xf(x)=\\!\\int_0^x f(t)\\,dt>0$ (∵ $f>0$) ⇒ 증가.\n$F''(x)=f(x)>0$ ⇒ 아래로 볼록.",
  },
  {n:8, subject:"적분학", unit:"이상적분", concept:"적분가능성 (불연속점 측도)",
    difficulty:"medium",
    question:"다음 중 주어진 구간 $I$에서 적분 가능한 함수를 모두 고르면?\n\nⓐ $f(x)=[x],\\,I=[0,3]$ (단, $[x]$는 $x$보다 크지 않은 가장 큰 정수)\nⓑ $f(x)=\\begin{cases}1&(0<x<1)\\\\0&(x=0,1)\\end{cases},\\,I=[0,1]$\nⓒ $f(x)=\\begin{cases}1&(x\\text{는 유리수})\\\\0&(x\\text{는 무리수})\\end{cases},\\,I=[0,1]$",
    options:opts5("ⓐ","ⓑ","ⓒ","ⓐ, ⓑ","ⓑ, ⓒ"),
    correct:"4",
    explanation:"ⓐ [가능] 가산 개의 점프 불연속점 ⇒ 적분 가능.\nⓑ [가능] 두 점에서만 불연속 ⇒ 적분 가능.\nⓒ [불가능] 디리클레 함수, 모든 점에서 불연속 (측도 양) ⇒ 리만 적분 불가.\n적분 가능: ⓐ, ⓑ.",
  },
  {n:9, subject:"적분학", unit:"정적분의 응용", concept:"곡선 길이 미분식",
    difficulty:"medium",
    question:"함수 $f$와 그 도함수 $f'$가 실수의 집합 $\\mathbb{R}$에서 연속이라고 할 때, $x=a$와 $x=b$ ($a<b$) 사이의 곡선 $y=f(x)$의 길이는 임의의 $b$에 대하여 $b^2+a$라고 한다. $f'(x)f''(x)$의 값은?",
    options:opts5("$x$","$2x$","$3x$","$4x$","$5x$"),
    correct:"4",
    explanation:"$L(b)=\\!\\int_a^b\\sqrt{1+(f'(x))^2}\\,dx=b^2+a$.\n$b$ 미분: $\\sqrt{1+(f'(b))^2}=2b\\Rightarrow 1+(f'(b))^2=4b^2$.\n다시 $b$ 미분: $2f'(b)f''(b)=8b\\Rightarrow f'(b)f''(b)=4b$. $b\\to x$: $f'(x)f''(x)=4x$.",
  },
  {n:10, subject:"적분학", unit:"정적분의 응용", concept:"포물선·직선 둘러싼 넓이",
    difficulty:"easy",
    question:"포물선 $y^2=2x$와 직선 $y=x-12$로 둘러싸인 도형의 넓이는?",
    options:opts5("$\\dfrac{230}{3}$","$80$","$\\dfrac{250}{3}$","$\\dfrac{260}{3}$","$90$"),
    correct:"3",
    explanation:"교점: $(y+12)^2=2y\\cdot$... 다시: $y^2=2x,\\,y=x-12\\Rightarrow x=y+12$, $y^2=2(y+12)\\Rightarrow y^2-2y-24=0\\Rightarrow y=-4,\\,6$.\n$S=\\!\\int_{-4}^6\\!\\left[(y+12)-\\dfrac{y^2}{2}\\right]dy=\\!\\left[\\dfrac{y^2}{2}+12y-\\dfrac{y^3}{6}\\right]_{-4}^{6}=\\dfrac{250}{3}$.",
  },
  {n:11, subject:"다변수함수", unit:"접평면과 선형근사", concept:"전미분 (오차)",
    difficulty:"medium",
    question:"어떤 원뿔의 밑면이 반지름과 높이를 측정하여 각각 $10$과 $25$를 얻었다. 이 수치는 각각 $0.1$까지의 측정 오차가 발생할 수 있다고 한다. 이 원뿔의 부피를 계산할 때, 발생할 수 있는 최대 오차는?",
    options:opts5("$5\\pi$","$10\\pi$","$15\\pi$","$20\\pi$","$25\\pi$"),
    correct:"4",
    explanation:"$V=\\dfrac{\\pi}{3}r^2 h$. $dV=\\dfrac{\\pi}{3}(2rh\\,dr+r^2\\,dh)$.\n$r=10,\\,h=25,\\,dr=dh=0.1$ 대입: $dV=\\dfrac{\\pi}{3}(50+10)=20\\pi$.",
  },
  {n:12, subject:"미분학", unit:"미분방정식", concept:"1계 선형 ODE",
    difficulty:"medium",
    question:"다음 초깃값 문제의 해는?\n$$y'=x-y,\\,y(0)=0\\quad(\\text{변수 변환 }z=x-y\\text{를 이용})$$",
    options:opts5("$e^{-x}+x+1$","$e^x+x-1$","$e^{-x}-x-1$","$e^x-x-1$","$e^{-x}+x-1$"),
    correct:"5",
    explanation:"$y'+y=x$ (1계 선형). 적분인자 $e^x$.\n$y\\,e^x=\\!\\int xe^x\\,dx=xe^x-e^x+C\\Rightarrow y=x-1+Ce^{-x}$.\n$y(0)=0$: $-1+C=0\\Rightarrow C=1$. $y=e^{-x}+x-1$.",
  },
  {n:13, subject:"다변수함수", unit:"편미분", concept:"분수 + sin 함수 편미분",
    difficulty:"medium",
    question:"$f(x,y)=\\dfrac{x^2}{x-\\sin y}$일 때, $f_x\\!\\left(1,\\dfrac{3}{2}\\pi\\right)+f_y\\!\\left(1,\\dfrac{3}{2}\\pi\\right)$의 값은?",
    options:opts5("$\\dfrac{1}{4}$","$\\dfrac{1}{2}$","$\\dfrac{3}{4}$","$1$","$\\dfrac{5}{4}$"),
    correct:"3",
    explanation:"$y=3\\pi/2$에서 $\\sin y=-1$, $\\cos y=0$.\n$f(x,3\\pi/2)=\\dfrac{x^2}{x+1}$. $f_x=\\dfrac{2x(x+1)-x^2}{(x+1)^2}\\big|_{x=1}=\\dfrac{4-1}{4}=\\dfrac{3}{4}$.\n$f_y=\\dfrac{x^2\\cos y}{(x-\\sin y)^2}\\big|_{(1,3\\pi/2)}=\\dfrac{0}{4}=0$.\n합 $=\\dfrac{3}{4}$.",
  },
  {n:14, subject:"다변수함수", unit:"편미분", concept:"그래디언트 직교절선 (가파른 경로)",
    difficulty:"medium",
    question:"높이가 함수 $h(x,y)=10000-2x^2-y^2$으로 주어지는 산이 있다. 어떤 사람이 좌표 $P(30,-20)$에서 시작해 가장 가파른 방향으로 이동할 때, $xy$좌표평면에서의 이동경로는?",
    options:opts5("$x=\\dfrac{3}{80}y^2$","$x=\\dfrac{3}{70}y^2$","$x=\\dfrac{3}{60}y^2$","$x=\\dfrac{3}{50}y^2$","$x=\\dfrac{3}{40}y^2$"),
    correct:"5",
    explanation:"등위곡선 접선의 기울기 $\\dfrac{dy}{dx}=-\\dfrac{h_x}{h_y}=-\\dfrac{-4x}{-2y}=-\\dfrac{2x}{y}$.\n경로(직교절선)의 미분방정식: $\\dfrac{dy}{dx}=\\dfrac{y}{2x}$.\n$\\dfrac{dy}{y}=\\dfrac{dx}{2x}\\Rightarrow\\ln|y|=\\dfrac{1}{2}\\ln|x|+c\\Rightarrow y^2=cx$.\n$(30,-20)$ 대입: $400=30c\\Rightarrow c=\\dfrac{40}{3}$. $y^2=\\dfrac{40}{3}x\\Rightarrow x=\\dfrac{3}{40}y^2$.",
  },
  {n:15, subject:"다변수함수", unit:"다변수 극값", concept:"산술기하평균 (직육면체)",
    difficulty:"medium",
    question:"대각선의 한 끝점을 원점에 두고 $xy$평면에 놓여 있는 직육면체가 그 대각선의 다른 끝점을 평면 $ax+by+cz=abc$ ($a>0,\\,b>0,\\,c>0$)에 두고 있다. 이 직육면체의 최대 부피는?",
    options:opts5("$\\dfrac{1}{27}a^2 b^2 c^2$","$\\dfrac{1}{27}a^3 b^3 c^3$","$\\dfrac{1}{8}a^2 b^2 c^2$","$\\dfrac{1}{8}a^3 b^3 c^3$","$\\dfrac{1}{27}abc$"),
    correct:"1",
    explanation:"산술기하평균 $ax+by+cz\\ge 3\\sqrt[3]{abcxyz}$. 즉 $abc\\ge 3\\sqrt[3]{abcxyz}$.\n$\\dfrac{abc}{3}\\ge\\sqrt[3]{abcxyz}$. 양변 세제곱: $\\dfrac{(abc)^3}{27}\\ge abc\\cdot xyz$.\n$xyz\\le\\dfrac{(abc)^2}{27}=\\dfrac{a^2 b^2 c^2}{27}$.",
  },
  {n:16, subject:"미분학", unit:"극한과 연속", concept:"이중 코사인 극한 (테일러)",
    difficulty:"medium",
    question:"$\\displaystyle\\lim_{x\\to 0}\\dfrac{1-\\cos(1-\\cos x)}{x^n}=\\dfrac{1}{8}$을 만족하는 자연수 $n$의 값은?",
    options:opts5("$4$","$5$","$6$","$7$","$8$"),
    correct:"1",
    explanation:"$1-\\cos x\\sim\\dfrac{x^2}{2}$. $1-\\cos(1-\\cos x)\\sim\\dfrac{(1-\\cos x)^2}{2}\\sim\\dfrac{x^4}{8}$.\n$\\dfrac{x^4/8}{x^n}\\to\\dfrac{1}{8}$ ⇒ $n=4$.",
  },
  {n:17, subject:"미분학", unit:"극한과 연속", concept:"스퀴즈 정리 (수열)",
    difficulty:"hard",
    question:"수열 $\\{a_n\\}$이 다음을 만족할 때, $\\displaystyle\\lim_{n\\to\\infty}a_n$의 값은?\n$$(4a_n-3)2^{n+1}+a_n+4>0,\\quad 2a_n\\tan\\dfrac{1}{n}+\\sin^{-1}\\dfrac{1}{n}<\\dfrac{5}{2}\\tan\\dfrac{1}{n}$$",
    options:opts5("$0$","$\\dfrac{1}{2}$","$\\dfrac{3}{4}$","$1$","$2$"),
    correct:"3",
    explanation:"첫 식: $a_n>\\dfrac{6\\cdot 2^n-4}{8\\cdot 2^n+1}\\to\\dfrac{3}{4}$.\n둘째 식: $a_n<\\dfrac{(5/2)\\tan(1/n)-\\sin^{-1}(1/n)}{2\\tan(1/n)}$. $1/n\\to 0$일 때 $\\dfrac{5/2-1}{2}=\\dfrac{3}{4}$ (테일러 전개로).\n스퀴즈: $a_n\\to\\dfrac{3}{4}$.",
  },
  {n:18, subject:"미분학", unit:"도함수 응용", concept:"방정식 실근 개수 (그래프)",
    difficulty:"medium",
    question:"열린 구간 $(-\\pi,\\pi)$에서 방정식 $\\dfrac{2}{3}x\\sin x-1=0$이 가지는 실근의 개수는?",
    options:opts5("$6$개","$5$개","$4$개","$3$개","$2$개"),
    correct:"3",
    explanation:"$\\dfrac{2}{3}x\\sin x=1\\Rightarrow\\sin x=\\dfrac{3}{2x}$.\n$f(x)=\\sin x$, $g(x)=\\dfrac{3}{2x}$ 그래프 분석. $g(\\pi/2)=3/\\pi\\approx 0.955<1$.\n$(-\\pi,\\pi)$에서 두 그래프 교점 4개 (양쪽 대칭).",
  },
  {n:19, subject:"미분학", unit:"역삼각·역쌍곡함수", concept:"역삼각·쌍곡 항등식 진위",
    difficulty:"easy",
    question:"다음 중 옳은 것을 모두 고르면?\n\nⓐ $\\sin^{-1}x+\\cos^{-1}x=\\dfrac{\\pi}{2}$\nⓑ $\\tan(\\sin^{-1}x)=\\dfrac{x}{\\sqrt{1-x^2}}$\nⓒ $\\cosh(x+y)=\\cosh x\\cosh y+\\sinh x\\sinh y$",
    options:opts5("ⓐ","ⓐ, ⓑ","ⓑ, ⓒ","ⓐ, ⓒ","ⓐ, ⓑ, ⓒ"),
    correct:"5",
    explanation:"ⓐ [참] 표준 항등식.\nⓑ [참] $\\sin^{-1}x=\\alpha$이면 $\\sin\\alpha=x$, $\\cos\\alpha=\\sqrt{1-x^2}$, $\\tan\\alpha=\\dfrac{x}{\\sqrt{1-x^2}}$.\nⓒ [참] 쌍곡함수 덧셈공식.\n모두 참.",
  },
  {n:20, subject:"미분학", unit:"도함수 응용", concept:"$\\ln x/x$ 그래프 부등식",
    difficulty:"medium",
    question:"함수 $f(x)=\\dfrac{\\ln x}{x}$를 이용하여 다음 부등식 중 옳은 것을 모두 고르면?\n\nⓐ $e^{\\pi}>\\pi^e$\nⓑ $3^{\\pi}>\\pi^3$\nⓒ $\\sqrt{2}^{\\sqrt{3}}<\\sqrt{3}^{\\sqrt{2}}$",
    options:opts5("ⓐ","ⓐ, ⓑ","ⓑ, ⓒ","ⓐ, ⓒ","ⓐ, ⓑ, ⓒ"),
    correct:"5",
    explanation:"$f(x)=\\ln x/x$는 $x=e$에서 극대. $0<x<e$에서 증가, $x>e$에서 감소.\nⓐ $e<\\pi$이고 $f(e)>f(\\pi)$ ⇒ $\\dfrac{1}{e}>\\dfrac{\\ln\\pi}{\\pi}$ ⇒ $\\pi>e\\ln\\pi$ ⇒ $e^{\\pi}>\\pi^e$ ✓.\nⓑ $3<\\pi$이고 $f(3)>f(\\pi)$ ⇒ $\\dfrac{\\ln 3}{3}>\\dfrac{\\ln\\pi}{\\pi}$ ⇒ $\\pi\\ln 3>3\\ln\\pi$ ⇒ $3^{\\pi}>\\pi^3$ ✓.\nⓒ $\\sqrt{2}<\\sqrt{3}<e$이고 $f(\\sqrt{2})<f(\\sqrt{3})$ ⇒ $\\dfrac{\\ln\\sqrt{2}}{\\sqrt{2}}<\\dfrac{\\ln\\sqrt{3}}{\\sqrt{3}}$ ⇒ $\\sqrt{3}\\ln\\sqrt{2}<\\sqrt{2}\\ln\\sqrt{3}$ ⇒ $\\sqrt{2}^{\\sqrt{3}}<\\sqrt{3}^{\\sqrt{2}}$ ✓.",
  },
  {n:21, subject:"미분학", unit:"도함수 응용", concept:"극값 3개를 갖는 조건 (그래프)",
    difficulty:"hard",
    question:"$a>1$에 대하여 함수 $f(x)=\\dfrac{x^3+k}{a^x}$가 3개의 극값을 가지도록 하는 $k$의 범위는?",
    options:opts5("$(0,1)$","$\\!\\left(0,\\dfrac{2}{\\ln a}\\right)$","$\\!\\left(\\dfrac{2}{\\ln a},0\\right)$","$\\!\\left(0,\\dfrac{4}{(\\ln a)^3}\\right)$","$\\!\\left(1,\\dfrac{4}{(\\ln a)^3}\\right)$"),
    correct:"4",
    explanation:"$f'(x)=\\dfrac{3x^2-(x^3+k)\\ln a}{a^x}$. 분자 $3x^2-(x^3+k)\\ln a=0\\Leftrightarrow k\\ln a=3x^2-x^3\\ln a$.\n$g(x)=3x^2-x^3\\ln a$의 임계점 $x=0,\\,x=2/\\ln a$. 극댓값 $g(2/\\ln a)=\\dfrac{4}{(\\ln a)^2}$.\n3개 근 조건: $0<k\\ln a<\\dfrac{4}{(\\ln a)^2}\\Rightarrow 0<k<\\dfrac{4}{(\\ln a)^3}$.",
  },
  {n:22, subject:"적분학", unit:"테일러급수", concept:"매클로린 + 합 함수의 도함수",
    difficulty:"medium",
    question:"다음의 두 함수 $f(x)$와 $g(x)$에 대하여 $\\dfrac{(f+g)^{(2020)}(0)}{(2020)!}$의 값은?\n$$f(x)=\\sinh x,\\quad g(x)=x\\ln(1+x)$$",
    options:opts5("$-\\dfrac{1}{2019}$","$\\dfrac{1}{2019}$","$-\\dfrac{1}{2020}$","$\\dfrac{1}{2020}$","$\\dfrac{2019}{2020}$"),
    correct:"2",
    explanation:"$\\dfrac{(f+g)^{(2020)}(0)}{2020!}=$ ($f+g$의 매클로린 $x^{2020}$ 계수).\n$\\sinh x$는 홀수 차수만 ⇒ $x^{2020}$ 계수 0.\n$x\\ln(1+x)=x\\!\\left(x-\\dfrac{x^2}{2}+\\dfrac{x^3}{3}-\\cdots+\\dfrac{x^{2019}}{2019}-\\cdots\\right)=\\cdots+\\dfrac{x^{2020}}{2019}+\\cdots$.\n$x^{2020}$ 계수 $=\\dfrac{1}{2019}$.",
  },
  {n:23, subject:"적분학", unit:"급수의 수렴/발산", concept:"급수 진위판단 (5명제)",
    difficulty:"medium",
    question:"다음 중 옳은 것은 모두 몇 개인가?\n\nⓐ $\\displaystyle\\lim_{n\\to\\infty}a_n=0$이면 급수 $\\displaystyle\\sum_{n=1}^{\\infty}a_n$은 수렴한다.\nⓑ $\\displaystyle\\sum_{n=100}^{\\infty}(a_n+b_n)=\\sum_{n=100}^{\\infty}a_n+\\sum_{n=100}^{\\infty}b_n$\nⓒ 급수 $\\displaystyle\\sum_{n=1}^{\\infty}n^{-p}$는 $p\\ge 1$일 때 수렴하고 $0<p<1$일 때 발산한다.\nⓓ 임의의 자연수 $n$에 대해 $a_n<b_n$이다. 이 때 $\\displaystyle\\sum_{n=1}^{\\infty}a_n$이 발산하면 $\\displaystyle\\sum_{n=1}^{\\infty}b_n$도 발산한다.\nⓔ 절대 수렴하는 급수의 임의의 재배열 급수는 절대 수렴한다.",
    options:opts5("$5$개","$4$개","$3$개","$2$개","$1$개"),
    correct:"5",
    explanation:"ⓐ [거짓] 발산정리의 역. 반례 $\\sum 1/n$.\nⓑ [거짓] 두 급수가 모두 수렴할 때만.\nⓒ [거짓] $p$-급수: $p>1$ 수렴, $p\\le 1$ 발산. $p=1$ 발산.\nⓓ [거짓] 비교판정법은 $0<a_n<b_n$ 양항 조건 필요.\nⓔ [참] 리만 재배열 정리: 절대수렴은 재배열에 불변.\n참 1개.",
  },
  {n:24, subject:"다변수함수", unit:"공간의 직선과 평면", concept:"두 직선 사이 거리",
    difficulty:"medium",
    question:"다음 두 직선 사이의 최단 거리는?\n$$L_1:x=-y=z+1,\\quad L_2:x=y=-z$$",
    options:opts5("$\\dfrac{\\sqrt{2}}{3}$","$\\dfrac{\\sqrt{2}}{2}$","$\\sqrt{2}$","$2\\sqrt{2}$","$3\\sqrt{2}$"),
    correct:"2",
    explanation:"$L_1$: 방향 $(1,-1,1)$, 점 $(0,0,-1)$. $L_2$: 방향 $(1,1,-1)$, 점 $(0,0,0)$.\n공통수직 $\\vec{n}=(1,-1,1)\\times(1,1,-1)=(0,2,2)\\sim(0,1,1)$, $|\\vec{n}|=\\sqrt{2}$.\n점 차 $(0,0,1)$. $d=\\dfrac{|0+0+1|}{\\sqrt{2}}=\\dfrac{\\sqrt{2}}{2}$.",
  },
  {n:25, subject:"다변수함수", unit:"이중적분", concept:"극좌표 적분 (라이프니츠)",
    difficulty:"medium",
    question:"함수 $f(x,y)$가 다음 식을 만족할 때, $A$의 값은?\n$$\\iint_\\Omega f'(x^2+y^2)\\,dxdy=\\pi A,\\quad\\Omega=\\{(x,y)\\mid x^2+y^2\\le a^2,\\,a>0\\}$$",
    options:opts5("$f(a^2)-f(0)$","$f(a)-f(0)$","$f(0)-f(a)$","$f(0)-f(a^2)$","$f(0)$"),
    correct:"1",
    explanation:"극좌표: $\\!\\int_0^{2\\pi}\\!\\!\\int_0^a f'(r^2)r\\,dr\\,d\\theta=2\\pi\\!\\int_0^a f'(r^2)r\\,dr$.\n$r^2=t,\\,2r\\,dr=dt$: $2\\pi\\cdot\\dfrac{1}{2}\\!\\int_0^{a^2}f'(t)\\,dt=\\pi[f(t)]_0^{a^2}=\\pi(f(a^2)-f(0))$.\n$A=f(a^2)-f(0)$.",
  },
  {n:26, subject:"다변수함수", unit:"삼중적분", concept:"원기둥-포물면 부피",
    difficulty:"medium",
    question:"$a>0$일 때, 곡면 $z^2=4ax$와 원기둥 $y^2=ax-x^2$으로 둘러싸인 영역의 부피는?",
    options:opts5("$\\dfrac{32a^3}{15}$","$2a^3$","$\\dfrac{32a^3}{17}$","$\\dfrac{16a^3}{9}$","$\\dfrac{32a^3}{19}$"),
    correct:"1",
    explanation:"$y^2=ax-x^2\\Leftrightarrow(x-a/2)^2+y^2=(a/2)^2$ (반지름 $a/2$ 원기둥). $z=\\pm 2\\sqrt{ax}$.\n$V=4\\!\\iint_{D^*}\\sqrt{4ax}\\,dA$ (대칭, 1사분면 $\\times 4$).\n극좌표: $r=a\\cos\\theta,\\,0\\le\\theta\\le\\pi/2$. $V=4\\cdot 2\\sqrt{a}\\!\\int_0^{\\pi/2}\\!\\!\\int_0^{a\\cos\\theta}\\sqrt{r\\cos\\theta}\\,r\\,dr\\,d\\theta=\\dfrac{32 a^3}{15}$ (계산).",
  },
  {n:27, subject:"적분학", unit:"급수의 수렴/발산", concept:"급수 발산 식별 (개수)",
    difficulty:"medium",
    question:"다음 급수들 중 발산하는 것은 모두 몇 개인가?\n\nⓐ $\\displaystyle\\sum_{n=2}^{\\infty}\\dfrac{1}{n\\ln n}$\nⓑ $\\displaystyle\\sum_{n=1}^{\\infty}\\dfrac{n!}{3^{n-1}}$\nⓒ $\\displaystyle\\sum_{n=0}^{\\infty}\\dfrac{x}{1+x^n}$ (단, $0<x<1$)\nⓓ $\\displaystyle\\sum_{n=2}^{\\infty}\\dfrac{(-1)^n}{\\ln n}$",
    options:opts5("$0$개","$1$개","$2$개","$3$개","$4$개"),
    correct:"4",
    explanation:"ⓐ [발산] 적분판정법: $\\!\\int\\dfrac{dx}{x\\ln x}=\\ln(\\ln x)\\to\\infty$.\nⓑ [발산] $n!/3^{n-1}\\to\\infty$.\nⓒ [발산] $0<x<1$이면 $x^n\\to 0$, 항 $\\to x\\ne 0$.\nⓓ [수렴] 교대급수, $1/\\ln n\\to 0$ 단조감소.\n발산 3개.",
  },
  {n:28, subject:"다변수함수", unit:"공간곡선", concept:"두 공간곡선 교각",
    difficulty:"medium",
    question:"곡선 $\\vec{x_1}(t)=(t,1-t,3+t^2)$과 $\\vec{x_2}(s)=(3-s,s-2,s^2)$이 만나는 점에서 두 접선의 교각은?",
    options:opts5("$\\dfrac{\\pi}{2}$","$\\cos^{-1}\\dfrac{1}{3}$","$\\dfrac{\\pi}{4}$","$\\cos^{-1}\\dfrac{1}{\\sqrt{3}}$","$\\dfrac{\\pi}{6}$"),
    correct:"4",
    explanation:"교점: $t=3-s,\\,1-t=s-2,\\,3+t^2=s^2$. 첫 두 식 일치 ($t+s=3$). 셋째: $3+(3-s)^2=s^2\\Rightarrow s=2,\\,t=1$.\n$\\vec{x_1}'(1)=(1,-1,2)$, $\\vec{x_2}'(2)=(-1,1,4)$.\n$\\cos\\theta=\\dfrac{\\vec{x_1}'\\cdot\\vec{x_2}'}{|\\vec{x_1}'||\\vec{x_2}'|}=\\dfrac{-1-1+8}{\\sqrt{6}\\sqrt{18}}=\\dfrac{6}{\\sqrt{108}}=\\dfrac{6}{6\\sqrt{3}}=\\dfrac{1}{\\sqrt{3}}$.\n$\\theta=\\cos^{-1}(1/\\sqrt{3})$.",
  },
  {n:29, subject:"다변수함수", unit:"이중적분", concept:"기함수 + 변수변환",
    difficulty:"medium",
    question:"$\\displaystyle\\int f(u)du=F(u)+C$ ($C$는 상수), $F$는 기함수라 할 때, 다음 적분의 값은?\n$$\\iint_\\Omega f\\!\\left(\\dfrac{y-x}{y+x}\\right)dA$$\n(단, $\\Omega$는 점 $(1,0),(2,0),(0,2),(0,1)$을 꼭짓점으로 하는 사다리꼴의 내부)",
    options:opts5("$\\dfrac{1}{2}F(1)$","$F(1)$","$\\dfrac{3}{2}F(1)$","$2F(1)$","$\\dfrac{5}{2}F(1)$"),
    correct:"3",
    explanation:"$y+x=u,\\,y-x=v$ 치환. 자코비안 $|\\partial(x,y)/\\partial(u,v)|=1/2$.\n사다리꼴 $\\to uv$ 평면: $u\\in[1,2],\\,v\\in[-u,u]$.\n$\\!\\iint f(v/u)\\cdot\\dfrac{1}{2}dudv=\\dfrac{1}{2}\\!\\int_1^2\\!\\!\\int_{-u}^{u}f(v/u)\\,dv\\,du$.\n$v/u=t,\\,dv=u\\,dt$: $\\dfrac{1}{2}\\!\\int_1^2 u\\!\\int_{-1}^{1}f(t)\\,dt\\,du=\\dfrac{1}{2}\\!\\int_1^2 u[F(1)-F(-1)]\\,du=\\dfrac{1}{2}\\cdot 2F(1)\\cdot\\dfrac{3}{2}=\\dfrac{3}{2}F(1)$ (∵ $F$ 기함수).",
  },
  {n:30, subject:"다변수함수", unit:"편미분", concept:"연속·미분·편미분 가능성",
    difficulty:"medium",
    question:"함수 $f(x,y)=\\begin{cases}\\dfrac{\\sqrt{|xy|}}{\\sqrt{x^2+y^2}}&((x,y)\\ne(0,0))\\\\0&((x,y)=(0,0))\\end{cases}$에 대한 설명으로 옳은 것은?",
    options:opts5("원점에서 연속이고 편미분가능하다.","원점에서 연속이고 미분불가능하다.","원점에서 불연속이고 편미분가능하다.","원점에서 불연속이고 미분가능하다.","원점에서 편미분가능하고 미분가능하다."),
    correct:"3",
    explanation:"극한: $y=mx$ 경로 $\\dfrac{\\sqrt{|m|}|x|}{|x|\\sqrt{1+m^2}}=\\dfrac{\\sqrt{|m|}}{\\sqrt{1+m^2}}$, 경로마다 다름 ⇒ 극한 없음, 불연속.\n축 방향 편미분: $f_x(0,0)=\\!\\lim_{h\\to 0}\\dfrac{f(h,0)-0}{h}=0$ (분자 0). $f_y(0,0)=0$. 편미분 가능.\n불연속 ⇒ 미분 불가능.",
  },
];

const TOTAL=PROBLEMS.length;
console.log(`총 ${TOTAL}문제 (객관식) 준비됨`);

const rows = PROBLEMS.map(p => {
  const id = `q-${YEAR}-${SCHOOL_EN}-${String(p.n).padStart(2,"0")}`;
  return {
    id, subject: p.subject, unit: p.unit, concept: p.concept, difficulty: p.difficulty,
    source_type: "imported", pool: "general", question: p.question, content_type: "latex",
    question_image: null, question_type: "multiple_choice",
    options: p.options, correct_option_id: p.correct,
    answer_text: null, explanation: p.explanation, explanation_content_type: "latex",
    explanation_image: null,
    tags: [YEAR, SCHOOL_KO, "past_exam", p.subject, p.unit, p.concept],
    created_at: new Date().toISOString(), updated_at: new Date().toISOString(),
  };
});

const { data, error } = await sb.from("questions").upsert(rows, { onConflict: "id" }).select("id");
if (error) { console.error("업로드 실패:", error); process.exit(1); }
console.log(`업로드 완료: ${data.length}건`);
